### PR TITLE
4535-Is-there-a-reason-new-completion-does-not-use-RBProgramNodeVisitor

### LINKED ISSUE #4535: Is there a reason new completion does not use RBProgramNodeVisitor?
The new completion has a visitor inheriting from Object. 

Is there a reason not to inherit from RBProgramNodeVisitor? Because currently, it seems to duplicate its logic.

### PR DESCRIPTION
**Pull request by jecisc**
Make CompletionProducer inherit from RBProgramNodeVisitor + rename it CompletionProducerVisitor

Fixes #4535

### CODE REVIEW

**Comment by jecisc** [comment]
I also add the missing method #visitSlotInitializationNode:. I returned `#()`, maybe this is not right but I don't know what it should return.

**Review by MarcusDenker — APPROVED** [review]
ok!

**Comment by MarcusDenker** [comment]
I tested the PR, works

**Comment by Ducasse** [comment]
Hi cyril
For now we are still in flux with the design of certain aspects of the class definition. 
I will adapt it and revisit everything once we know for slots and also based on the client needs.

**Pull request merged**
