### PR TITLE
22100-Add-exampleSuperReceiverexampleSelfReceiver-and-isSelfOrSuper

### PR DESCRIPTION
**Pull request by Ducasse**
add isSelfOrSuper and tests to cover isSelf, isSuper and isSelfOrSuper. 
We will be able to simplify some refactorings that way

### CODE REVIEW

**Comment by dionisiydk** [comment]
We should decide about <sampleInstance> at instance side. It looks a bit strange.
(I commented your issue)

**Comment by Ducasse** [comment]
Hi denis :)
I could not find your comment.

**Comment by Ducasse** [comment]
I do not understand why the build is failing because I just add more methods and more green tests.

**Comment by dionisiydk** [comment]
I mean this issue https://pharo.manuscript.com/f/cases/22098/Not-showing-icon-to-inspect-samplInstance

**Pull request merged**
