### PR TITLE
Method category cleanup - pass 2

### LINKED ISSUE #9384: Method category cleanup - pass 2
- fixed needed by categorizing uncategorized methods
- use "xxx - yyyy" pattern in some method categories (where it makes sense) instead of "xxx-yyy"
- remove a few dots at end of method body

### PR DESCRIPTION
**Pull request by astares**
fix #9384

### CODE REVIEW

**Comment by Ducasse** [comment]
This is strange since all the Fuel tests are breaking. I imagine that this is unrelated.

**Comment by astares** [comment]
Changes are simple. Can you restart CI on this? 🤔

**Comment by MarcusDenker** [comment]
If I lool at the diff, it seems that the PR removed some extension methods, this could be the reason. I will restart

**Comment by MarcusDenker** [comment]
The Fuel tests are failing in another PR check, too, so it seems to be not caused by this PR

**Pull request merged**
