### PR TITLE
3358-Why-do-we-have-RBRefactoryChangeManager-and-RBRefactoringManager

### LINKED ISSUE #3358: Why do we have RBRefactoryChangeManager and RBRefactoringManager???
which is basically doing

RBRefactoringManager >> addRefactoring: aRefactoring 
	RBRefactoryChangeManager instance performChange: aRefactoring changes.
	refactorings add: aRefactoring class name

and of course is yet another singleton...

### PR DESCRIPTION
**Pull request by Ducasse**
Fixes: #3358 
- Removed RBrefactoringManager
- simply moving the expression RBRefactoryChangeManager instance performChange: aRefactoring changes to the place it was called. 
- we can think about something better later.
- Remove deprecated since P60 class RBChangeBrowser
- Avoid hardcoding everywhere RBParser and RBParseTreeRewriter.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Failing tests seem related

unix-32 / Tests-unix-32 / testMoveDefinitionIntoBlockThatIsAReceiverOfACascadedMessage – Unix32.Refactoring2.Transformations.Tests.RBMoveTemporaryVariableDefinitionTransformationTest
<1s
unix-32 / Tests-unix-32 / testNowhereToMove – Unix32.Refactoring2.Transformations.Tests.RBMoveTemporaryVariableDefinitionTransformationTest
<1s
unix-32 / Tests-unix-32 / testMoveDefinition – Unix32.Refactoring2.Transformations.Tests.RBMoveTemporaryVariableDefinitionTransformationTest
<1s
windows-32 / Tests-windows-32 / testMoveDefinitionIntoBlockThatIsAReceiverOfACascadedMessage – Windows32.Refactoring2.Transformations.Tests.RBMoveTemporaryVariableDefinitionTransformationTest
<1s
windows-32 / Tests-windows-32 / testNowhereToMove – Windows32.Refactoring2.Transformations.Tests.RBMoveTemporaryVariableDefinitionTransformationTest
<1s

**Comment by Ducasse** [comment]
I will check. This is strange because I executed the tests before submitting and they were green.

**Comment by Ducasse** [comment]
In fact there are green on my machine 
Screen Shot 2019-06-13 at 18 41 04

**Comment by Ducasse** [comment]
I found the problem. One refactoring mixed things... fixing it now.

**Comment by Ducasse** [comment]
I do not know why I do not get the correct jenkins.

**Comment by MarcusDenker** [comment]
There is now a step 4: Benchmarks. The CI is green. "This commit looks good"

**Pull request merged**
