### PR TITLE
22449-Port-back-old-OSWindow-changes

### PR DESCRIPTION
**Pull request by ronsaldo**
Porting back old OSWindow changes.
22449 - https://pharo.fogbugz.com/f/cases/22449/Port-back-old-OSWindow-changes

### CODE REVIEW

**Comment by astares** [comment]
Would an additional "private - utilities" method like:

```Smalltalk
forAvailableHostWindowDo: aBlock orFallbackTo: anotherBlock 
   "Evaluate the first block when a native host os window is available. 
    If not evaluate anotherBlock."

  ^osWindow ifNil: aBlock ifNotNil: anotherBlock 
```

make the nil checking calls more understandable by turning them into:

```Smalltalk
activateCursor: aCursor 
   self forAvailableHostWindowDo: [ osWindow setMouseCursor: aCursor ] 
        orFallbackTo: [ aCursor primitiveBeCursor ]
```

**Comment by estebanlm** [comment]
CI broken?

**Comment by estebanlm** [comment]
I restarted the job, should be an unrelated problem.

**Comment by estebanlm** [comment]
yes :)

**Review by estebanlm — APPROVED** [review]

**Pull request merged**
