### PR TITLE
20456-FuelTests-package-should-be-renamed-to-Fuel-Tests

### PR DESCRIPTION
**Pull request by VincentBlondeau**
https://pharo.fogbugz.com/f/cases/20456/FuelTests-package-should-be-renamed-to-Fuel-Tests

### CODE REVIEW

**Comment by VincentBlondeau** [comment]
No new test failure

**Comment by astares** [comment]
This needs to be done in external Fuel repo too. Dont know who maintains it currently

**Comment by jecisc** [comment]
Maybe @theseion ?

**Comment by theseion** [comment]
Yes, me and @tinchodias. I'll take a look this weekend.

**Comment by theseion** [comment]
Looks good. I'll have to update the configuration first though. I'll do that tomorrow.

**Comment by tinchodias** [comment]
thanks Max

**Comment by theseion** [comment]
This PR should be closed. I took the opportunity to rename and reorganise all Fuel packages. Thanks @VincentBlondeau

**Comment by VincentBlondeau** [comment]
Cool! Thx @theseion :)

**Pull request closed without merging**
