### PR TITLE
21754-improve-API-to-evaluate-a-compiledMethod

### PR DESCRIPTION
**Pull request by MarcusDenker**
improve API to evaluate a compiledMethod
	https://pharo.fogbugz.com/f/cases/21754/improve-API-to-evaluate-a-compiledMethod

### CODE REVIEW

**Comment by MarcusDenker** [comment]
error not related

**Comment by dionisiydk** [comment]
Hi, Marcus. 
I doubt that value protocol is good idea for methods.
Because it is super easy to crash image using wrong method receiver:
```Smalltalk
 nil withArgs: #() executeMethod: Rectangle>>#width
```
And with your change it will be more easy:
```Smalltalk
(Rectangle>>#width) value.
```
#value can be easily sent to the method by some program error or just by incident during manual debugging.

**Comment by MarcusDenker** [comment]
Ups, that is bad... so this would need a vm change to make the primitive fail (like with blocks).
Not really worth it.

**Comment by dionisiydk** [comment]
From other side I would compare method with symbols.
We have Symbol>>value: which expects receiver as an argument. So we can do  
```Smalltalk
anArray collect: #printString
```
Do you want same for methods? Should I expect:
```Smalltalk
anArray collect: (Object>>printString)
```
Methods also require receiver for evaluation. 
So generally, what goal you would like to achieve with value protocol in methods?

**Comment by MarcusDenker** [comment]
Ok, so it seems to be not a good idea...

**Pull request closed without merging**
