### PR TITLE
22043-Deprecate-asIcon

### PR DESCRIPTION
**Pull request by Ducasse**
to control its reintroduction!

### CODE REVIEW

**Comment by MarcusDenker** [comment]
"self iconNamed:" means there is a method about graphics in Object? Not much better than on Symbol.

**Comment by Ducasse** [comment]
We know all that. 
Now it iconNamed: was not in Object before. The MODEL was taking care of it and denis decided to move it to object and this is not a nice idea. He did it to avoid duplication because people are fucking dirty and that do not get that any object cannot have automagically an icon!!! but that their #$%^&*&^ application should do the right job and provide icons. 
Now can you trust me on that. asIcon is plain bad. Because you cannot control the icons. 

So we should not have asIcon everywhere because this is yet another fucking singleton.
Can we ever stop to have singleton in Pharo?
Look at Smalltalk tools what a shit.

**Comment by Ducasse** [comment]
the KEY KEY KEY difference between SELF iconNamed: and asIcon is that the Application = SELF can decide and this is modular: each receiver can decide with 
asIcon there is ONLY ONE. so when we talk about OOP can we try to think modularly?
People apparently do not get dispatch.

**Comment by MarcusDenker** [comment]
there are 41 senders of asIcon

**Comment by dionisiydk** [comment]
I not remember completely. But plan was to move #iconNamed: to Morph. 
One problem was #systemIcon in Object class side. I tried to replace all implementors with #systemIconName. But then users should be adopted which I was not succeed.

**Comment by MarcusDenker** [comment]
the code (deprecation) seems to be already in the system. No idea why.

**Comment by jecisc** [comment]
It is. 

I got a transformation in my last PR.

**Comment by MarcusDenker** [comment]
then lets put it in the merged state...

**Comment by Ducasse** [comment]
Not only to Morph but applicationModel. We are missing the notion of Application.

**Pull request merged**
