### PR TITLE
20769-DateAndTime-now-returns-summer-time-in-winter-France-time-zone

### PR DESCRIPTION
**Pull request by pavel-krivanek**
https://pharo.fogbugz.com/f/cases/20769/DateAndTime-now-returns-summer-time-in-winter-France-time-zone

add missing startup list registrations

### CODE REVIEW

**Comment by svenvc** [comment]
Hmm, maybe it is me, but I can't see the Locale initialize in the changes ...

**Comment by pavel-krivanek** [comment]
try to fix all but the original issue ;-) Caused by mess with multiple images during preparation of the PR, thanks! 
The checks have big probability to fail but I didn't wanted to split the fixes into separate issues because then it would case a lot of merge conflicts.

**Comment by svenvc** [comment]
No problem, thanks for taking care

**Comment by pavel-krivanek** [comment]
we can merge, the image works well and the timezone is fixed

**Pull request merged**
