### PR TITLE
Update Fuel from upstream

### LINKED ISSUE #13985: Cleanup: Fuel package(s) should follow regular package naming order
We should have a 

- "Fuel-Core-Tests"

instead of 

- "Fuel-Tests-Core"

to be consistent with test package naming order

### LINKED ISSUE #14131: Update Fuel for Pharo 12

### PR DESCRIPTION
**Pull request by theseion**
- remove FuelPlatform
- properly store / load class comments and stamps
- skip problematic tests when clean blocks are enabled
- rename Fuel-Tests-Core to Fuel-Core-Tests

Fixes #14131

### CODE REVIEW

**Comment by theseion** [comment]
Fixed a lingering reference.

**Comment by theseion** [comment]
Test run looks good to me.

**Comment by MarcusDenker** [comment]
Hmm... lots of tests failing, e.g.

```
FLCreateTraitSerializationTest>>testCreateWithInternalTrait fais with: 'Attempt to read undeclared variable FLPlatform'
```

**Comment by theseion** [comment]
Oh silly me… I did not look at the tests tab. I’ll take care of it.

--

**Comment by theseion** [comment]
Looks good now, I think. There was some random error though.

**Pull request merged**
