### PR TITLE
Sync-Moose-Algos-Graph-with-Moose-Algos

### PR DESCRIPTION
**Pull request by jecisc**
Sync Moose-Algos-Grouph with MooseAlgos + add tests.

### CODE REVIEW

**Comment by jecisc** [comment]
This is synchronisation with v1.1.7 of MooseAlgos: https://github.com/moosetechnology/MooseAlgos/releases/tag/v1.1.7

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/moosetechnology/MooseAlgos">moosetechnology/MooseAlgos</a></strong></div><div>Moose Algos contains generic libraries for various analysis algorithms.  - moosetechnology/MooseAlgos</div></blockquote>

**Comment by Ducasse** [comment]
Thanks cyril
Did you see the PR on printString because I have the impression that it touches MooseAlgos.

**Comment by jecisc** [comment]
I'll check tomorrow

**Comment by jecisc** [comment]
I did a synchronisation, I moved the tests to another package, and I released v1.1.8 that is in sync with the content of this PR.

https://github.com/moosetechnology/MooseAlgos/releases/tag/v1.1.8

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/moosetechnology/MooseAlgos">moosetechnology/MooseAlgos</a></strong></div><div>Moose Algos contains generic libraries for various analysis algorithms.  - moosetechnology/MooseAlgos</div></blockquote>

**Pull request merged**
