### PR TITLE
Reenable FFICallbackTest on Windows

### LINKED ISSUE #9528: Reenable FFICallbackTest on Windows
FFICallbackTest>>#testCqsort
FFICallbackTest>>#testCqsortWithByteArray

had been commented and changed to not run on Windows.

image

I tried them with latest VM and they are green without any crash. Maybe we could / should reenable them again on this platform too.

### PR DESCRIPTION
**Pull request by astares**
Fix #9528

### CODE REVIEW

**Comment by astares** [comment]
CI is failing for Windows ... :(

**Comment by tesonep** [comment]
We should not integrate it, it is crashing the CI in Windows

**Comment by astares** [comment]
Yes - but the question is still: why?

**Comment by MarcusDenker** [comment]
The tests are now not anymore failing on Win

**Comment by MarcusDenker** [comment]
checked with pablo: ok to merge

**Pull request merged**
