### PR TITLE
Introduce Collections-Strings-Tests

### LINKED ISSUE #6974: Introduce Collections-Strings-Tests
- create a package Collections-Strings-Tests to further split Collections-Tests

### PR DESCRIPTION
**Pull request by astares**
Fix #6974

### CODE REVIEW

**Comment by MarcusDenker** [comment]
[64] MetacelloNotification: Project: KernelTests baseline
[64] MetacelloNameNotDefinedError: project group, or package named: 'Collections-Strings-Tests''Collections-Support-Tests' not found when used in requires: or includes: field of package: 'Collections-Tests' for version: baseline of BaselineOfKernelTests.
[64] [

**Comment by astares** [comment]
Test failures unrelated

**Comment by astares** [comment]
Ping

**Review by MarcusDenker — APPROVED** [review]
ok

**Pull request merged**
