### PR TITLE
Fix FileDialog to delete non-empty directories.

### LINKED ISSUE #6331: FileDialog raises an error when we want to delete a non empty folder.
**Describe the bug**
FileDialog raises an error when we want to delete a non empty folder. 
**To Reproduce**
You can try to remove a GitHub repo when Iceberg shows you where to clone a new one. 
It is nearly impossible to remove it.

### PR DESCRIPTION
**Pull request by ackerleytng**
Also add tests and refactor deleteFileOrDirectory.

Fixes #6331.

### CODE REVIEW

**Comment by tesonep** [comment]
Very nice feature, and with tests!! Thanks a lot. 
My only comment is that the use of #ensure: in the tests can be improved by deleting the files in the #tearDown of the test case. So, the tests get more clean.

Thanks

**Comment by tesonep** [comment]
Please ask me if you need help with that!

**Comment by ackerleytng** [comment]
Sure, I'll fix it! I have a question!

How do I delete the memory Filesystem in-between tests? I was assuming that it will be garbage collected since a new memory Filesystem is created before every test by the setUp method. Is that a good assumption?

If I can delete the memory Filesystem, then that will remove the need to delete the temporary files, so I'll remove the `[] ensure:` stuff.

**Comment by tesonep** [comment]
The memory fileSystem will be collected as it is not longer referenced. 
It is true, without keeping a reference to the fileSystem is not needed to delete the file. So the ensure and the delete of the directory can be removed.

**Comment by ackerleytng** [comment]
How should I explicitly delete the memory filesystem?

**Comment by tesonep** [comment]
I didn't explain it well.
It is a regular object. So, there is nothing to delete. There is nothing created in the disk file system. So, the creation of many memory file systems should not have-side effect

**Comment by ackerleytng** [comment]
I got confused as well. Thanks for your pointers! I made a last commit that removes the `ensure:` after the block

**Comment by Ducasse** [comment]
@ackerytng thanks a lot. What I can tell you is that I did what you are doing in the past. 
I tried to read as much as possible code and contribute to Squeak and after doing the same when I created Pharo and I learned (still learning) a lot.

**Comment by Ducasse** [comment]
This is unrelated but we got

```
You will need to log out and log back in for the limits to take effect.
[64] For more information please see
[64] https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/tag/r3732#linux
[64] FT2Error: Error reading bitmap from outline [error 20][invalid outline]
[64] FT2Library>>getBitmap:fromOutline:
[64] FreeTypeFace(FT2Face)>>renderGlyphIntoForm:pixelMode:
[64] FreeTypeFace(FT2Face)>>renderGlyphIntoForm:
[64] FreeTypeSubPixelAntiAliasedGlyphRenderer(FreeTypeGlyphRenderer)>>renderGlyph:depth:subpixelPosition:font:
[64] FreeTypeSubPixelAntiAliasedGlyphRenderer(FreeTypeGlyphRenderer)>>glyphOf:colorValue:mono:subpixelPosition:font:
[64] [
```

**Comment by Ducasse** [comment]
I would like to see if the FT2 error is reproducible.

**Comment by Ducasse** [comment]
This is strange because I have many regressions such as 
 testModificationTime – Unix64.FileSystem.Tests.Attributes.Tests.DiskFileAttributesTest
 testAccessTime – Unix64.FileSystem.Tests.Attributes.Tests.FileReferenceAttributeTest
 testChangeTime – Unix64.FileSystem.Tests.Attributes.Tests.FileReferenceAttributeTest

could you have a look.

**Comment by ackerleytng** [comment]
@Ducasse, are you opening and closing this issue to trigger the CI? Also, I'll look into

+ testModificationTime – Unix64.FileSystem.Tests.Attributes.Tests.DiskFileAttributesTest
+ testAccessTime – Unix64.FileSystem.Tests.Attributes.Tests.FileReferenceAttributeTest
+ testChangeTime – Unix64.FileSystem.Tests.Attributes.Tests.FileReferenceAttributeTest

I just rebased my changes on top of the latest Pharo9.0 branch,

**Comment by ackerleytng** [comment]
I just ran the tests on my image again and all the tests were green. How did you run those tests? Is it through CI? Are you able to access the CI server? When I click on Details above, I can't seem to reach the jenkins server:

```
ci.inria.fr took too long to respond.
```

**Comment by Ducasse** [comment]
I would like to see the tests running before integrating the PR.

**Comment by ackerleytng** [comment]
Yup, I'm looking into the build process to see where stuff went wrong!

**Comment by Ducasse** [comment]
Thanks a lot for your contribution!!!

**Pull request merged**
