### PR TITLE
20878-Alien tests should be in a Alien-Tests package

### PR DESCRIPTION
**Pull request by VincentBlondeau**
Split alien test package + improve comment

### CODE REVIEW

**Comment by astares** [comment]
https://pharo.fogbugz.com/f/cases/20878

Do NOT YET INCLUDE this one. This has an impact on VM building. 

We will first split it in the original repo - I will take care of this.

**Comment by MarcusDenker** [comment]
And in the past on the side of Squeak people really did not like to even consider changes like this..

**Comment by astares** [comment]
We should not care too much on the past when we all together want to invent the future,

Related:
http://lists.squeakfoundation.org/pipermail/vm-dev/2018-January/026351.html

http://lists.squeakfoundation.org/pipermail/vm-dev/2018-January/026375.html

**Comment by VincentBlondeau** [comment]
@astares Thanks! 
Please comment this PR when it is ok on the initial repo.

**Comment by astares** [comment]
Will do

**Comment by Ducasse** [comment]
What is the status of this PR?

**Comment by astares** [comment]
Ignore it for the time being.

**Comment by astares** [comment]
Done on Alien (MCZ) side

http://lists.squeakfoundation.org/pipermail/vm-dev/2018-March/026945.html

**Comment by MarcusDenker** [comment]
so does that mean we can remove the [IGNORE] and start to push for merging?

**Comment by astares** [comment]
Ich discussed yesterday with esteban, He wanted to take care on the pharo-vm and image side now. Please ask him what is the best way to proceed

**Comment by estebanlm** [comment]
if someone wants to take over the merge, go ahead. 
in image we need to have just Alien-Core. Tests are made through uFFI and Alien-Win32 was always a mistake ;)

**Comment by Ducasse** [comment]
Hi vincent 

if you understand what esteban is saying and you have a bit a time can you do it?

Stef

**Comment by estebanlm** [comment]
I just updated the correct version. 
I will close this PR because is covered in #1202 

(btw... I removed the test package because I think alien test is covered by UFFI... what do you think?)

**Pull request closed without merging**
