### PR TITLE
Moved back Array2D and its test into collection packages. 

### PR DESCRIPTION
**Pull request by bouraqadi**
It was by mistake tagged as deprecated
Fix for issue 22567

### CODE REVIEW

**Comment by Ducasse** [comment]
Good catch!!!
BTW noury you may want to have a look at https://github.com/Ducasse/Containers-Array2D
because I clean it and added a more tests.

**Comment by bouraqadi** [comment]
> On 11 Oct 2018, at 21:04, StéphaneDucasse <notifications@github.com> wrote:
> 
> Good catch!!!
> BTW noury you may want to have a look at https://github.com/Ducasse/Containers-Array2D <https://github.com/Ducasse/Containers-Array2D>
> because I clean it and added a more tests.
> 
Ok. will do.

Noury

**Comment by MarcusDenker** [comment]
this PR was done against a version were the bootstrap was broken. As the PR check uses this version, the PR test check stays broken even though we fixed the broken build in the meantime.

Solution: update the PR to be against the latest version.

**Comment by bouraqadi** [comment]
The branch has no conflict, but the commit cannot built. How to proceed from here?
Should I recreate a new branch with the fix?

**Comment by bouraqadi** [comment]
Closed this issue, and reopoen a new one instead.

**Pull request closed without merging**
