### PR TITLE
New tools parent menu entry

### PR DESCRIPTION
**Pull request by hernanmd**
This PR just add a single method to have a new menu entry item to the System menu so we can group and make new tools easily accessible specifying parent: #NewToolsMenu, as specified in #16377

### CODE REVIEW

**Comment by demarey** [comment]
As I explained in the issue, I would prefer not to expose in P12. It would add confusion.
I would prefer to make them the default tools early in P13.

**Comment by hernanmd** [comment]
It would be much better not to disrupt users by assuming that they will get confused, and let them decide for themselves which tools to use. Maybe we could add an description in the menu, something like "experimental" label.

But hiding the tools will only lead to less bugs being reported as they are less exposed.

**Comment by Ducasse** [comment]
We can add 'In preview' as menu item

**Comment by hernanmd** [comment]
> We can add 'In preview' as menu item

Done

**Review by demarey — APPROVED** [review]

**Pull request merged**
