### PR TITLE
Multiple cleaning of Protocol

### PR DESCRIPTION
**Pull request by jecisc**
- Remove Protocol class>>nullProtocolName because it is useless
- Rename #ambiguous to #traitProtocolConflictName and move it to TraitV2 package
- #canBeRemoved has been removed (yes, you, you can be removed ;) ) and #isEmpty is used instead. Those are equivalent now that AllProtocol magic has been removed
- Class comment has been improved
- I added some comments on methods has #isExtensionProtocol
- #canBeRenamed and #isVirtualProtocol were dead code
- Protocol class>>#defaultName has been removed in favor of #unclassified
- Some small other code cleanings

### CODE REVIEW

**Comment by jecisc** [comment]
CI crash is related :/ I'll cut again in smaller PR tomorrow

**Comment by jecisc** [comment]
The changes left in this PR are really small but the bootstrap still crash with a really cryptic error. This is really weird.

I guess I'll do even smaller PR?

**Comment by jecisc** [comment]
The crash seems to come from the update of the class comment. 

Most changes made it into the image through other PR, but I removed the update of class comment to integrate the last cleanings.

**Comment by jecisc** [comment]
Failure seems unrelated!

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
