### PR TITLE
2478-Separation-of-Glamour-PagerModel

### LINKED ISSUE #2478: Separation of Glamour-PagerModel
Let's move Glamour-PagerModel and GLMAsyncTask to standalone packages to make the Spotter model independent on the rest of Glamour

### PR DESCRIPTION
**Pull request by pavel-krivanek**
standalone Glamour-PagerModl and Glamour-Tasks

fixes #2478

### CODE REVIEW

**Comment by pavel-krivanek** [comment]
fixes #2478

**Comment by pavel-krivanek** [comment]
Iceberg haven't moved GLMPagerModel class correctly

**Comment by pavel-krivanek** [comment]
unrelated tests

```
windows-32 / Tests-windows-32 / testHostWindowIcon – Windows32.Graphics.Tests.Primitives.DisplayScreenTest
<1s
windows-32 / Tests-windows-32 / testHostWindowIconWrongTypeOfArgument – Windows32.Graphics.Tests.Primitives.DisplayScreenTest
<1s
windows-32 / Tests-windows-32 / testHostWindowIcon – Windows32.Graphics.Tests.Primitives.DisplayScreenTest
<1s
windows-32 / Tests-windows-32 / testHostWindowIconWrongTypeOfArgument – Windows32.Graphics.Tests.Primitives.DisplayScreenTest
<1s
osx-32 / Tests-osx-32 / testNoDeadWeakSubscriptions – MacOSX32.Announcements.Tests.Core.Tests.WeakAnnouncerTest
<1s
osx-32 / Tests-osx-32 / testWriteSnapshotWithoutOrganization – MacOSX32.MonticelloTonel.Tests.TonelWriterTest
<1s
osx-32 / Tests-osx-32 / testNoDeadSubscriptions – MacOSX32.Tests.SystemChangeNotification.SystemAnnouncerLiveTest
<1s
unix-32 / Tests-unix-32 / testNoDeadWeakSubscriptions – Unix32.Announcements.Tests.Core.Tests.WeakAnnouncerTest
<1s
unix-32 / Tests-unix-32 / testWriteSnapshotWithoutOrganization – Unix32.MonticelloTonel.Tests.TonelWriterTest
<1s
unix-32 / Tests-unix-32 / testNoDeadSubscriptions – Unix32.Tests.SystemChangeNotification.SystemAnnouncerLiveTest
<1s
windows-32 / Tests-windows-32 / testNoDeadWeakSubscriptions – Windows32.Announcements.Tests.Core.Tests.WeakAnnouncerTest
<1s
windows-32 / Tests-windows-32 / testWriteSnapshotWithoutOrganization – Windows32.MonticelloTonel.Tests.TonelWriterTest
<1s
windows-32 / Tests-windows-32 / testNoDeadSubscriptions – Windows32.Tests.SystemChangeNotification.SystemAnnouncerLiveTest
```

**Comment by Ducasse** [comment]
Pavel could you fix the as yet unclassified methods.

**Comment by pavel-krivanek** [comment]
the methods should be extension methods of the morphic related package... Iceberg mess. I will try to fix it

**Comment by Ducasse** [comment]
Tx Pavel. Broken tests are unrelated.

**Pull request merged**
