### PR TITLE
20898-MultiByteFileStream-upToAll-does-not-work-correctly-with-UTF-8

### PR DESCRIPTION
**Pull request by bpieber**
fixes case #20898 MultiByteFileStream upToAll: does not work correctly with UTF-8

### CODE REVIEW

**Comment by bpieber** [comment]
For some reasons the checks have failed. I have looked at the console output but cannot make sense of it. The changes should be straightforward. What should I do now. Can someone please help?

**Comment by MarcusDenker** [comment]
I have restarted running the tests

**Comment by bpieber** [comment]
Thanks for restarting the tests. However, there is still the same error. I found something suspicious in the log:
```
Fetched -> BaselineOfIDE-tonel.1 --- tonel:///builds/workspace/_and_branch_Pipeline_PR-632-IGGSTQ4MQMDPJ3KCNUUHOP7QC6ZR57ZKV5R2CWDYVA4DN2YIDVXQ/32/bootstrap-cache/../src --- tonel:///builds/workspace/_and_branch_Pipeline_PR-632-IGGSTQ4MQMDPJ3KCNUUHOP7QC6ZR57ZKV5R2CWDYVA4DN2YIDVXQ/32/bootstrap-cache/../src[31mSyntax Error on line 3: 'Variable or expression expected'
[32] =========================================================
[32] [0m0001: baseline: spec [ 
[32] 0002:     
[32] [31m0003: 	<baseline>
[32]       _^_
[32] [0m0004: 
[32] 0005:  	| repository | 
[32] 0006: 	
[32] 0007: 	repository := self packageRepositoryURL.
[32] 0008:        
[32] 0009: 	spec for: #common do: [
[32] 0010: 		spec postLoadDoIt: #'postload:package:'.
[32] 0011: 		
[32] 0012: 		spec baseline: 'BasicTools' with: [spec repository: repository].
[32] 0013: 
[32] 0014: 		spec baseline: 'Shift' with: [
[32] 0015: 			spec loads: 'shift-tests'. 
[32] 0016: 			spec repository: repository
[32] 0017: 		].
```
Looks like some corrupted file.

**Comment by bpieber** [comment]
Can someone please help me with the failing CI checks. I have no idea how you debug failures like this? Is there a way to run the checker locally?

**Comment by MarcusDenker** [comment]
You can find the tests when you go the the "Details" link. Here it seems the CI run crashed (happens sometimes, not often anymore). I will restart it

**Comment by bpieber** [comment]
Crashed again at the same place. :-/

**Comment by pavel-krivanek** [comment]
It must be related to the sources file management which uses MultiByteFileStream and was broken by this PR.

**Comment by pavel-krivanek** [comment]
I tried to apply your change and run all tests locally. All tests are green so it will not help us to find the sources of the build failure

**Comment by bpieber** [comment]
Any idea what to try next? Is there some other way to reproduce what the build is doing locally?

**Comment by guillep** [comment]
Hi @bpieber, It looks like when you read tonel files with your changes there are some "invisible"  characters left over in the stream. I think that first you should be able to reproduce the issue locally without bootstrapping by trying to import a tonel file in an image with your changes.
Just take any of the files inside Pharo's src/ directory and try:

```smalltalk
reader := TonelReader on: stream fileName: '...'.
reader loadDefinitions.
```

Once with the monticello definitions you can try to compile them or check if the source code in the methods have something strange...

If that fails, come back and we can do a skype trying to show you how to bootstrap :)

**Comment by tesonep** [comment]
I have fixed the conflict in the test, as the old test does not exists anymore. So we can resuscitate this PR.

**Comment by guillep** [comment]
Ok, moreover this class is not used by the system anymore.

**Pull request merged**
