### PR TITLE
Add back beautifulcomments

### PR DESCRIPTION
**Pull request by estebanlm**
this PR adds back BeautifulComments, but as external projects.

EDIT: I sneaked also some refactors to BaselineOfIDE because it was starting to look very ugly :P

### CODE REVIEW

**Comment by Ducasse** [comment]
Should I need to merge to integration branch

**Comment by estebanlm** [comment]
yep

**Comment by Ducasse** [comment]
Ok I will.

**Comment by Ducasse** [comment]
Do you have an idea how I should do it because not every packages of Microdown should be loaded in Pharo. 
So may be the baseline is loading the correct subset. 
For now I will push everything in master and integration.

**Comment by estebanlm** [comment]
I am loading just the packages included in "RichText" group of Microdown.
BeautifulComments is just a single package.

**Comment by Ducasse** [comment]
should I change the baseline of BeautifulComments to use something else than dev of Microdown?

**Comment by estebanlm** [comment]
nope. I load Microdown before, with the correct version.

**Comment by Ducasse** [comment]
shit when I load BC after MD I get 233 failures :(

**Comment by estebanlm** [comment]
oops
I am pushing the first version of this.

**Comment by Ducasse** [comment]
So I do not know what to do and I do not have the time nor energy. 
Could we not put BC in Pharo? Our tools are not good to manage projects.

**Comment by Ducasse** [comment]
Yes this is good to only load this package. Probably that BC is doing the same.

**Comment by estebanlm** [comment]
now this is ready :)

**Comment by MarcusDenker** [comment]
aargh... now merging 

Integrate Roassal3 v0.9.9e #10846

before leads to a conflict...

**Comment by estebanlm** [comment]
do not merge yet :)

**Comment by estebanlm** [comment]
now yes

**Pull request merged**
