### PR TITLE
Updated to latest changes in Fuel 3.0.0

### PR DESCRIPTION
**Pull request by theseion**
This also fixes the Fuel version number.

### CODE REVIEW

**Comment by theseion** [comment]
The failures don't seem to be related to my change.

**Comment by pavel-krivanek** [comment]
Do you have any explanation for the modified format of categories in Tonel?

**Comment by theseion** [comment]
Nope. I assumed that was an intended format change...

**Comment by pavel-krivanek** [comment]
I checked and all the current exported code uses #'...', strange that it is broken for you

**Comment by theseion** [comment]
Weird... I'll check.

**Comment by theseion** [comment]
This looks better. Interestingly, there were some categories that had the old format before and have now been updated in this PR.

**Comment by pavel-krivanek** [comment]
The test failures are related. The test checks if it is still able to load the data serialized in the old format. Please check

**Comment by Ducasse** [comment]
Hello Max
I relaunch the build with the latest version so that we can see what is happening. 
After if the tests are broken and you have time we will keep it open else we will close it so that 
you can take the time to fix and resubmit.
Is it ok for you?
Stef

**Comment by theseion** [comment]
Sure, I'll look at the failures.

**Comment by theseion** [comment]
Superseded by #2483

**Pull request closed without merging**
