### PR TITLE
Debugger fuel out stack command

### PR DESCRIPTION
**Pull request by StevenCostiou**
Actually fixes a new tools issue: https://github.com/pharo-spec/NewTools/issues/148

Now, what I do not really like is that it introduces a dependency from fuel to 2 new tools debugger packages.
Maybe the package with fuel commands (and actions for GT) for debuggers should be externalized from Fuel, but then where to put it?

If the PR passes the CI, I will leave that to think about to the community...

Screenshot 2020-12-18 at 09 10 28

### CODE REVIEW

**Comment by StevenCostiou** [comment]
Ok, not building because of dependencies...

**Comment by MarcusDenker** [comment]
I downloaded the build artefact: I can fuel out a stack and dropping that on the image opens a debugger.

**Comment by StevenCostiou** [comment]
Super :) Now if someone could review and merge, I need this PR to be accepted before doing the mirror changes in NewTools.

**Review by MarcusDenker — APPROVED** [review]

**Comment by Ducasse** [comment]
You can package it in a separate package this way the new debugger will not depend on fuel.

**Comment by StevenCostiou** [comment]
> You can package it in a separate package this way the new debugger will not depend on fuel.

Yes this is what I did last week ;)

**Pull request merged**
