### PR TITLE
Fix some typos in the docs

### PR DESCRIPTION
**Pull request by gcotelli**
Also fix some white-space issues in the docs

### CODE REVIEW

**Comment by gcotelli** [comment]
> This issue has either a default title or empty body. We would appreciate it if you could provide more information. Note: I am not a very intelligent bot, I can only react to new comments. Please add a comment for me if you update the body or title.

Done

**Comment by jecisc** [comment]
The Welcome doc was removed at the end of Pharo 11 release (in Favor of the welcome browser) and there is currently a PR to do the sync. So this should be merged after the sync to avoid yet another conflict on it (it already got some conflicts).

**Comment by gcotelli** [comment]
I suppose the PR in question is #13784

**Comment by jecisc** [comment]
Yes it is

**Review by jecisc — APPROVED** [review]
I checked all changes except the welcome pages. Once the synch PR will be merged, this one is good to go.

**Comment by Ducasse** [comment]
Thanks for fixing the doc :)

**Comment by Ducasse** [comment]
Ouch there is a conflict.

**Comment by gcotelli** [comment]
Fixed the conflicts

**Pull request merged**
