### PR TITLE
5991-In-place-edition-of-inspector-fails

### LINKED ISSUE #5991: In place edition of inspector fails
**Describe the bug**
In the inspector I wanted to do an in place edition (shift + click on a value, update it and save).

It fails: 

```Smalltalk
UndefinedObject(Object)>>doesNotUnderstand: #selectedClassOrMetaClass
UndefinedObject>>doesNotUnderstand: #selectedClassOrMetaClass
CompletionEngine>>openMenu
[ editor atCompletionPosition ifTrue: [ self openMenu ] ] in [ (Delay forMilliseconds: NECPreferences popupAutomaticDelay) wait.
UIManager default defer: [ editor atCompletionPosition ifTrue: [ self openMenu ] ] ] in CompletionEngine>>resetCompletionDelay in Block: [ editor atCompletionPosition ifTrue: [ self openM...etc...
WorldState>>runStepMethodsIn:
WorldMorph>>runStepMethods
WorldState>>doOneCycleNowFor:
WorldState>>doOneCycleFor:
WorldMorph>>doOneCycle
WorldMorph class>>doOneCycle
[ [ WorldMorph doOneCycle.
Processor yield.
false ] whileFalse: [  ] ] in MorphicUIManager>>spawnNewProcess in Block: [ [ WorldMorph doOneCycle....
[ self value.
Processor terminateActive ] in BlockClosure>>newProcess in Block: [ self value....
```

 - Version: Pharo 8.0

### PR DESCRIPTION
**Pull request by MarcusDenker**
backport fix from Pharo9. fixes #5991

### CODE REVIEW

**Comment by pavel-krivanek** [comment]
there is a merge conflict

**Comment by MarcusDenker** [comment]
aargh... I should have downloaded a fresh Pahro8 to do the change

**Comment by MarcusDenker** [comment]
Ah, no, changed the branch to pharo8 (was pharo9)

**Review by guillep — APPROVED** [review]
ok!

**Pull request merged**
