### PR TITLE
[WIP] Redo "Activate strict FFI""

### PR DESCRIPTION
**Pull request by guillep**
Redoes [pharo-project/pharo#15627](https://github.com/pharo-project/pharo/pull/15506)

We need to take care of some SDL functions before this is ready to fly

### CODE REVIEW

**Comment by Ducasse** [comment]
tests are green so I will push it.

**Comment by Rinzwind** [comment]
There’s an error when opening the image of build 1169 which I’m guessing is due to this pull request:

```
--- The full stack ---
FFICallout>>unsupportedUntypedLiteral:
FFIStrictResolutionMode>>resolveUndeclaredTypeForArgument:withResolver:
FFICallout>>resolveUntypedArgument:
[…]
SDL_Texture(Object)>>ffiCall:
SDL_Texture>>lockPixels:pitch:
[…]
OSSDL2FormRenderer>>updateAreas:immediate:
OSWorldRenderer>>updateDamage:
[…]
```

I’m not sure it was intended to already be merged as the title says “[WIP]”.

**Comment by Rinzwind** [comment]
The first comment also says:

> We need to take care of some SDL functions before this is ready to fly

And there’s a [comment in pull request #15228](https://github.com/pharo-project/pharo/pull/15228#issuecomment-1793438719) saying:

> no! not again! please do not integrate of markedvas WIP!

It might be better to use [draft pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests) for this, as for example done in pull request #14586.

**Comment by Ducasse** [comment]
I know. Now all the tests are green so we should use it to find problems.

**Comment by Ducasse** [comment]
Argh I did not see your comment I will revert this merge.

**Comment by Ducasse** [comment]
https://github.com/pharo-project/pharo/issues/15677#issuecomment-1837558958

**Comment by guillep** [comment]
Yep, sorry I'll start using the drafting PR feature to see if this works better.

Now, the thing is that this is a function that is not tested :).
Maybe we should explore in the future having some smoke tests that open the Pharo UI in the CI?

**Pull request merged**
