### PR TITLE
21611-Adapt-ImageReadWriter-hierarchy-to-need-only-pure-binary-streams

### PR DESCRIPTION
**Pull request by svenvc**
A set of changes that refactors the ImageReadWriter hierarchy to work with simple binary streams (need for Pharo 7 new stream/file implementation)

https://pharo.manuscript.com/f/cases/21611/Adapt-ImageReadWriter-hierarchy-to-need-only-pure-binary-streams

### CODE REVIEW

**Comment by MarcusDenker** [comment]
fails somehow to load the logo:

RVXYVAOCWNK5ZI6PMPLJT55UVSY3NXAZFMQHWWSTB5BIN2CW2PIQ/32/src --- cache
Finished atomic load
Evaluated -> baseline [BaselineOfMorphicCore] >> postload:package:'Starting postload action'
Error: image format not recognized
ImageReadWriter class(Object)>>error:
[ positionableReadStream close.
^self error: 'image format not recognized' ] in ImageReadWriter class>>readerClassFromStream: in Block: [ positionableReadStream close....
OrderedCollection(Collection)>>detect:ifFound:ifNone:
OrderedCollection(Collection)>>detect:ifNone:
ImageReadWriter class>>readerClassFromStream:
ImageReadWriter class>>formFromStream:
Form class>>fromBinaryStream:
PolymorphSystemSettings class>>pharoLogoForm
PolymorphSystemSettings class>>pharoLogo
[ self setDesktopLogoWith: self pharoLogo ] in PolymorphSystemSettings class>>desktopLogoChanged in Block: [ self setDesktopLogoWith: self pharoLogo ]

**Comment by svenvc** [comment]
OK, thanks for the help. Can I download this image after integration, somewhere ?

**Comment by MarcusDenker** [comment]
yes, foow the "Details" link to the CI, there is a "artefacts" link on the top. goes here:
(this fails very early in the bootstrap, so no full image was build)

https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-1323/1/artifacts

**Comment by svenvc** [comment]
OK, I am looking into the problem ...

**Comment by svenvc** [comment]
OK, I committed/pushed 3 more changes in Form to this PR - this should fix the problem.

What do I do now to continue the integration process ?

**Comment by MarcusDenker** [comment]
with the push, the PR is automatically updated and the CI is automatically triggered. So we just need to wait for it to finish.

**Comment by MarcusDenker** [comment]
It is green!

**Comment by svenvc** [comment]
Nice !

I am starting to like the new flow, the last iteration of Iceberg was a major improvement.

**Comment by jecisc** [comment]
@svenvc Since this PR was integrated I cannot load QuickAccess anymore.

This piece of code:

```Smalltalk
Form fromBinaryStream: (Base64MimeConverter mimeDecodeToBytes: self actionManagerIconContents readStream)
```

```Smalltalk
actionManagerIconContents

	^'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0
RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAF1SURBVBgZpcGxalRBFMfh35yZ
GwK72mrrO2yxoIXFvIBNGksrsbISFGuxMRDIGwhiCtttrq9hCgWxSLtVsor3nvN3RwxcggTC
fl+SxC7So+cfnz14uHi73mgmAREoAg9HIUKB3AkJueMR3N4bLk5Pz158endwXBb3F0fd/szu
7HMTs4uNHwHHZTPINutzburnIKN5+f6r/ufVh2+6zpM3n7VFkYJmtVrRdR21VqbW57/wUfgo
XMFvF/fu3sLDaQoSTdd11Fq5quRCSk7KIodRRtHE6DTFw7nU9z1NrZVL2cBSpiTwJNyCJjxo
TCGa5XJJU2tlKicwA8uQS2IvZ5oIp7EIZ6rve6ZSMYpBNigZLPNXRNCUcRiYqrUyZWyZkQGX
sCSacRhpTB5M9X3PlKWEpQQpkc3IKdEogqZEBM18PqfWylU5JZrMPznThERTzr7/OHl6OByE
O+GBuxMR+DDw+PUXQkLhyEUoUAQRNCdsJUnswtjRH6iT+f+z/UsKAAAAAElFTkSuQmCC'
```

Raise this error:

```
ImageReadWriter class(Object)>>error:
[ positionableReadStream close.
^ self error: 'image format not recognized' ] in ImageReadWriter class>>readerClassFromStream: in Block: [ positionableReadStream close....
OrderedCollection(Collection)>>detect:ifFound:ifNone:
OrderedCollection(Collection)>>detect:ifNone:
ImageReadWriter class>>readerClassFromStream:
ImageReadWriter class>>formFromStream:
Form class>>fromBinaryStream:
QACToolIcons class>>DoItIn:
```

**Comment by Ducasse** [comment]
We should add a test :)

**Comment by svenvc** [comment]
What is QuickAccess ?

Anyway, this works:

````
Form fromBinaryStream: 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0
RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAF1SURBVBgZpcGxalRBFMfh35yZ
GwK72mrrO2yxoIXFvIBNGksrsbISFGuxMRDIGwhiCtttrq9hCgWxSLtVsor3nvN3RwxcggTC
fl+SxC7So+cfnz14uHi73mgmAREoAg9HIUKB3AkJueMR3N4bLk5Pz158endwXBb3F0fd/szu
7HMTs4uNHwHHZTPINutzburnIKN5+f6r/ufVh2+6zpM3n7VFkYJmtVrRdR21VqbW57/wUfgo
XMFvF/fu3sLDaQoSTdd11Fq5quRCSk7KIodRRtHE6DTFw7nU9z1NrZVL2cBSpiTwJNyCJjxo
TCGa5XJJU2tlKicwA8uQS2IvZ5oIp7EIZ6rve6ZSMYpBNigZLPNXRNCUcRiYqrUyZWyZkQGX
sCSacRhpTB5M9X3PlKWEpQQpkc3IKdEogqZEBM18PqfWylU5JZrMPznThERTzr7/OHl6OByE
O+GBuxMR+DDw+PUXQkLhyEUoUAQRNCdsJUnswtjRH6iT+f+z/UsKAAAAAElFTkSuQmCC' base64Decoded asByteArray readStream
```

Did you not forget the last #readStream ?

**Comment by jecisc** [comment]
This is a project from @astares 

http://smalltalkhub.com/#!/~TorstenBergmann/QuickAccess

I don't have the rights to change its code. I know it works in Pharo 4 to 6.1 with the code I gave.

**Comment by svenvc** [comment]
Base64MimeConverter>>#mimeDecodeToBytes: is wrong in returning a deprecated class. Why the hell would it have to return a RWBinaryOrTextStream that is positioned at the end, really, this is crazy
 ?

**Comment by Ducasse** [comment]
I love this one :)
We should probably really fix Base 64 Mine Converter.

**Pull request merged**
