### PR TITLE
21242-improve-includesMethod

### PR DESCRIPTION
**Pull request by MarcusDenker**
improve #includesMethod:

https://pharo.fogbugz.com/f/cases/21242/improve-includesMethod

### CODE REVIEW

**Comment by MarcusDenker** [comment]
I do not understand why I get a conflict.

**Comment by MarcusDenker** [comment]
I just did these changes exactly on top of the changes that I now get told are conflicts. That makes no sense *at all*

**Comment by estebanlm** [comment]
me neither, but it should be fixed now. 
if it happens again, I will need to check :P

**Comment by jecisc** [comment]
Maybe it is not the same line return? CR/LF/CRLF.

**Pull request merged**
