### PR TITLE
Improving the performance of SourceFileArray in Pharo8

### PR DESCRIPTION
**Pull request by tesonep**
We have tested some performance regression in the use of SourceFileArray,
It affects method compilation and class and traits creation.

### CODE REVIEW

**Comment by dionisiydk** [comment]
How faster it's became?

**Review by guillep — APPROVED** [review]
This should get us closer to the performances when writing to the changes file in Pharo6.1.

**Comment by tesonep** [comment]
@dionisiydk I have sent a mail to the list with more details, basically, the following Benchmarks are improved.

Benchmark | Relative Change
-- | --
AddingAnInstanceVariableToAClassWithASubclass | -3.96%
AddingAnInstanceVariableToAClassWithoutASubclassAndInstances | -15.91%
AddingAnInstanceVariableToAClassWithoutSubclasses | -28.50%
ClassAndSubclassCreation | -25.67%
ClassUsingATrait | -90.05%
SimpleClassCreation | -26.55%
TraitCreation | -92.95%
TraitCreationUsingOtherTrait | -91.68%
CompileAMethodAndModifyIt | -32.92%
CompileAMethodInAClassUsingATrait | -83.28%
CompileAMethodInATraitNotUsed | -85.12%
CompileAMethodInATraitUsed | -88.16%
CompileANewMethod | -40.73%
CompileANewMethodUsingInstanceVariable | -33.93%
MethodAccessingAGlobal | -47.57%

A negative number represents a reduction of time from the original to the new.

**Comment by Ducasse** [comment]
And I see that the only breaking test is the one of maxlength I will try to continue to work on it because we have everything working in alain's repo except keystroke handling.

**Comment by dionisiydk** [comment]
Up to 90% speedup. It's amazing. And so simple change.

вт, 2 апр. 2019 г., 15:25 Pablo Tesone <notifications@github.com>:

**Pull request merged**
