### PR TITLE
3385-Sync-Spec

### LINKED ISSUE #3385: Sync Spec
Some people need the latest Spec features in Pharo so I'll do a sync.

### PR DESCRIPTION
**Pull request by jecisc**
Spec synchronisation.

Fixes #3385

Partial changelog:
- Add tests
- Improve robustness of some tests
- Make transmissions an independent package
- Begin to work on commands (WIP)
- Clean API of some presenters (such as lists)
- Work on context menu of Text presenter and table presenter
- Drop box list items can now be sorted
- Proceed the decomposition of Text and Code presenters
- Replace some variables and value holder by observable slots
- Improve demos
- Table columns are now expendables
- ...

### CODE REVIEW

**Comment by Ducasse** [comment]
Cyril we cannot load this PR.

[32] Loaded -> Spec-Layout-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-3387/32/src --- cacheError: This package depends on the following classes:
[32]   SpecInputPort

Do you have an automated job that loads systematically in P8?


 	Loaded -> Morphic-Widgets-TickList-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-3387/32/src --- cache
[32] 	Loaded -> System-Changes-FileServices-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-3387/32/src --- cache
[32] 	Loaded -> System-OSEnvironments-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-3387/32/src --- cache
[32] 	Loaded -> System-Identification-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-3387/32/src --- cache
[32] 	Loaded -> Tool-Base-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-3387/32/src --- cache
[32] Finished atomic load'Starting postload action'
[32] 
[32] Evaluated -> baseline [BaselineOfMorphic] >> postload:package:
[32] Loaded -> ParametrizedTests-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-3387/32/src --- cache
[32] SpecLegacyLayout>>buildAdapterFor:bindings: (SpecInterpreter is Undeclared) 
[32] 
[32] Loaded -> Spec-Layout-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-3387/32/src --- cacheError: This package depends on the following classes:
[32]   SpecInputPort
[32] You must resolve these dependencies before you will be able to load these definitions: 
[32]   RootsPresenterPort
[32]   RootsPresenterPort>>#incomingTransmission:from:
[32] 
[32] MCPackageLoader(Object)>>notify:
[32] MCPackageLoader>>warnAboutDependencies
[32] MCPackageLoader>>validate
[32] MCPackageLoader>>loadWithNameLike:
[32] MCVersionLoader>>basicLoadWithNameLike:
[32] [ self basicLoadWithNameLike: aString ] in MCVersionLoader>>loadWithNameLike: in Block: [ self basicLoadWithNameLike: aString ]
[32] [ returnValue := aBlock value ] in [ [ returnValue := aBlock value ] ensure: [ self announceLoadStop: aString ] ] in MCVersionLoader>>announceLoad:do: in Block: [ returnValue := aBlock value ]
[32] BlockClosure>>ensure:
[32] [ [ returnValue := aBlock value ] ensure: [ self announceLoadStop: aString ] ] in MCVersionLoader>>announceLoad:do: in Block: [ [ returnValue := aBlock value ] ensure: [ self a...etc...
[32] BlockClosure>>ensure:
[32] MCVersionLoader>>announceLoad:do:
[32] MCVersionLoader>>loadWithNameLike:
[32] [ self ensurePackage: version package.
[32] self loadWithNameLike: version info name ] in [ | version |
[32] version := versions first.
[32] [ self ensurePackage: version package.
[32] self loadWithNameLike: version info name ] asJob

**Comment by jecisc** [comment]
I'll take a look now. Thanks.

**Comment by Ducasse** [comment]
**thanks**

**Comment by jecisc** [comment]
Failures seems not related.

**Pull request merged**
