### PR TITLE
2467-cleanup-temp-var-reading

### PR DESCRIPTION
**Pull request by MarcusDenker**
- use same code for write as for read
- #indexFromIR not needed anymore 
- remove old comments and commented code

More to come later, just a first tiny cleanup

### CODE REVIEW

**Comment by MarcusDenker** [comment]
why does the CI not check this?

**Comment by Ducasse** [comment]
Retrying to get the CI to kick in.

**Comment by Ducasse** [comment]
It would be nice to have more method comments.

**Comment by Ducasse** [comment]
Broken tests are unrelated.

**Pull request merged**
