### PR TITLE
Deprecate-some-class-creation-methods-using-categories

### PR DESCRIPTION
**Pull request by jecisc**
Deprecate Class>>#subclass:instanceVariableNames:classVariableNames:category: and Class>>#subclass:instanceVariableNames:classVariableNames:poolDictionaries:category:

### CODE REVIEW

**Comment by guillep** [comment]
The build is broken because there are users of that method.

Still, please, let's not put stuff in the deprecated package anymore...

**Review by guillep — CHANGES_REQUESTED** [review]
The build is broken because there are users of that method.

Still, please, let's not put stuff in the deprecated package anymore...

**Comment by Ducasse** [comment]
Guille for me such a core method should be deprecated with a transform rule so that we can easily import old code.

**Comment by Ducasse** [comment]
And this are the typical methods that I would like to add to the migrator package.
Now all the broken code in Morphic and GT can be just removed. Code not working before should be removed.

**Comment by jecisc** [comment]
See discussion at for the Deprecated package: https://github.com/pharo-project/pharo/issues/4140#issuecomment-518162948

For the broken build, it's weird because I thought I fixed all users. I'll check when I'll have the time.

**Comment by Ducasse** [comment]
To see if it can compile.

**Comment by jecisc** [comment]
Apparently, the bug occurs while loading source files during the bootstrap.

**Comment by jecisc** [comment]
I do not find the file `bootstrap-cache/st-cache/Monticello.st` is it generated? Or stored somewhere else?

**Comment by jecisc** [comment]
Ok, apparently it's generated here: https://github.com/jecisc/pharo/blob/Deprecate-some-class-creation-methods-using-categories/bootstrap/src/Pharo30Bootstrap.package/PBBootstrap.class/instance/exportPackages.withBlacklistedClasses.withBlacklistedMethods.usingInitializeScript.intoFile..st

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/jecisc/pharo">jecisc/pharo</a></strong></div><div>Contribute to jecisc/pharo development by creating an account on GitHub.</div></blockquote>

**Comment by jecisc** [comment]
@guillep On which version of Pharo is the bootstrap launched?

The problem is that the bootstrap generates a script that uses the old API. If the bootstrap runs on Pharo 7 then I think we should backport the change to Pharo 7 before we proceed with this PR.

**Comment by jecisc** [comment]
Hum... That's not so simple because all class creation patterns do not have an equivalent with #package: instead of #category:...

I'll close this PR and we should do a pass on class creation methods

**Comment by guillep** [comment]
> @guillep On which version of Pharo is the bootstrap launched?
> 
> The problem is that the bootstrap generates a script that uses the old API. If the bootstrap runs on Pharo 7 then I think we should backport the change to Pharo 7 before we proceed with this PR.

On Pharo 6.1 :) But that does not matter: if you're bootstrapping pharo8 commit xxx, you'll end up having the version of monticello present in pharo8 commit xxx.

**Comment by guillep** [comment]
In other words, if you break monticello, it will not bootstrap :P

**Comment by jecisc** [comment]
@guillep The problem here is that during the bootstrap, the code that is exported use the API with `category:` instead of `package:`.

So, if we plan to remove later this API, we need to update the exporter. I did another PR as a first step toward the goal of updating the ST code writer.

**Comment by jecisc** [comment]
What I mean is that it's not Monticello that is broken, but the MCStWriter generate this kind of code:

```
Boolean subclass: #False
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Kernel-Objects'!
```

Instead of :

```Smalltalk
Boolean subclass: #False
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	package: 'Kernel-Objects'!
```

**Pull request closed without merging**
