### PR TITLE
Update licence

### PR DESCRIPTION
**Pull request by juliendelplanque**
To set "Pharo Contributors" in copyright.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
We should make sure that it is in sync with the in-image version

**Comment by juliendelplanque** [comment]
Sure, one step at a time, I just fixed the easy part bi GitHub web app.

**Comment by juliendelplanque** [comment]
This should be sync during the bootstrap from source ideally by the way.

**Comment by juliendelplanque** [comment]
Hum, the licence in image seems to be more complete, I will copy it here.

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
