### PR TITLE
Remove unused ivar selectedItem in deprecated TreePresenter

### LINKED ISSUE #8226: Remove unused ivar selectedItem in deprecated TreePresenter
a) we could either ignore deprecated classes when we test for unused ivars in image
b) or we could clean them too

I guess b) is the better option as we only have ivar selectedItem in deprecated TreePresenter to fix.

### PR DESCRIPTION
**Pull request by astares**
Fix #8226

### CODE REVIEW

**Comment by astares** [comment]
CI problems (PotentialOutDatedDependencyWarning) not caused by this PR. 

Any reviewer/approvers?

**Comment by Ducasse** [comment]
I do not know what is the context serialisation test I imagine that it is not related.

**Comment by Ducasse** [comment]
Hi torsten did you see this little helper I did https://github.com/pharo-project/pharo/pull/8192
Because I wanted to get the class and the iv. 
Now I was surprised that my PR broke the build.

**Comment by astares** [comment]
@Ducasse Yes - I saw the helper. But not all the cases could be fixed by just removing the unused ivars...

**Pull request merged**
