### PR TITLE
2578-Test-result-notification-uses-wrong-plural-forms

### PR DESCRIPTION
**Pull request by svenvc**
Improve TestResult>>#printOn: to better take singular/plural forms into account

https://github.com/pharo-project/pharo/issues/2578

### CODE REVIEW

**Comment by Ducasse** [comment]
This is strange because we have many broken and related tests. 
Can you have a look?

**Comment by Ducasse** [comment]
Ok we will have to update the tests because they checked the exact string.

**Comment by svenvc** [comment]
Right, there are a couple of tests that literally test the print string, duh. 
I should have checked those, not clever.
I will try to fix this as soon as possible.

**Comment by svenvc** [comment]
I fixed the tests, but they remain literal string tests

**Comment by svenvc** [comment]
Failed tests does not seem to be related (existed before)

**Comment by svenvc** [comment]
Fixes 2578

**Comment by Ducasse** [comment]
Thanks sven!!!. 
We will have a new pass on the testing framework soon and a tool with new features!

**Pull request merged**
