### PR TITLE
Remove FreeType2 dialog morphic usage

### LINKED ISSUE #16801: #dialog: method of setting builder is bound to Morphic
I found that some settings are using a method named #dialog:. This method expect that a morph get returned and this bind the settings to Morphic. 

Since we need to replace Morphic, this should be updated. I'm not yet sure what is the best way to replace it. Maybe with Spec instead of Morphic?

### PR DESCRIPTION
**Pull request by hernanmd**
This PR updates the setting of FreeType library to use a checkbox instead of a dialog (?) checkbox.

Fixes #16801

### CODE REVIEW

**Comment by Ducasse** [comment]
Strange the build failed. I will relaunch the server.

**Comment by Ducasse** [comment]
I cannot see the log :(

**Comment by hernanmd** [comment]
> I cannot see the log :(

As far as I can see, the build is still broken. There was a PR integrated in https://github.com/pillar-markup/Microdown/pull/909 but I couldn't find anywhere how to make that build integrate with Pharo.

**Comment by hernanmd** [comment]
Replayed in #17346

**Pull request closed without merging**
