### PR TITLE
Integrate Clap

### PR DESCRIPTION
**Pull request by cdlm**
I think BaselineOfIDE still has to be modified so that Clap actually gets included in new images.

### CODE REVIEW

**Comment by cdlm** [comment]
I think BaselineOfIDE still has to be modified so that Clap actually gets included in new images.

**Comment by Ducasse** [comment]
Thanks Damien. I think that we should ask Pablo or Guille since Clap should probably be in the bootstrap.

**Comment by Ducasse** [comment]
I added them as reviewers. I do not know the impact of this but we will see.

**Comment by guillep** [comment]
@Ducasse For a very first iteration we cannot just add Clap to BaselineOfIDE?
Then we can iterate on it: I'd suggest @cdlm to try bootstrapping and checking BaselineOfPharoBootstrap, where the packages used to bootstrap are declared, and PharoBootstrapInitialization where the image is initialized.

**Comment by svenvc** [comment]
I hope this won't interfere or break normal command line stuff, that would be a disaster.

**Comment by cdlm** [comment]
@svenvc For the moment there's a normal `clap` command-line handler which works as a prefix for all Clap commands and leaves the existing stuff untouched. But I do hope we manage to deprecate it in some finite number of releases…

**Comment by Ducasse** [comment]
@cdlm Damien did you follow what guille proposed? I really want to get clap integrated and create new command line handler. 
@svenvc we should really get  better way to define command line. And we need help. We will try to avoid impacting people but not at all cost.

**Comment by svenvc** [comment]
Where can I read about CLAP ?
What problem does it try to solve ?

**Comment by akgrant43** [comment]
> Where can I read about CLAP ?
> What problem does it try to solve ?

https://github.com/cdlm/clap-st

**Comment by svenvc** [comment]
Thanks for the pointer.
Sure, clap looks nice. I am all for improvements.
But please implement all complex real world use cases before talking about replacing anything.

**Comment by cdlm** [comment]
There's also a WIP booklet: https://github.com/SquareBracketAssociates/Booklet-ClapCommandLine

**Comment by Ducasse** [comment]
Hi sven 
I really agree with you. I started to write some command lines with Clap and we need more users. 
The old API is not really good - I faced it in Pillar. So if you give a try let us know.

**Comment by svenvc** [comment]
Let's integrate it with the prefix and then try to use it for real

**Comment by cdlm** [comment]
Had to re-do the PR without `TClapBase` after removing it with `git rm`…

**Comment by cdlm** [comment]
Bootstrap produces an image with Clap loaded but with a half-dozen `PrimitiveFailed: primitive #'bad argument' in File class failed` at boot time

**Comment by akgrant43** [comment]
Hi Damien,

> Bootstrap produces an image with Clap loaded but with a half-dozen `PrimitiveFailed: primitive #'bad argument' in File class failed` at boot time

Can you clarify what you mean by 'at boot time'?  Does this happen if I download the image and try to use it, or was it during the bootstrap process (I couldn't find it in the log)?

Thanks,
Alistair

**Comment by cdlm** [comment]
@akgrant43 I tried bootstrapping an image from my working copy of this PR, by running `bootstrap/scripts/bootstrap.sh`. The image builds, but when I launch it I get the errors mentioned.

I don't know where to download an image since CI fails for an unrelated reason.

**Comment by akgrant43** [comment]
Hi Damien,

Thanks for the clarification.  I'll have a go at reproducing this, although it might take a couple of days.

Cheers,
Alistair

**Comment by akgrant43** [comment]
Hi Damien,

>I don't know where to download an image since CI fails for an unrelated reason.

The image can be downloaded by clicking on the "Details" for the CI build, and then "Artifacts":

https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-2377/3/artifacts

The first three artifacts are the sources and 32 and 64 bit zip files.

If I download the 64 bit image and use the latest VM it starts without any problems.  I can run the File related automated tests without anything like what you're describing.

Can you provide the output of pharo --version?


Cheers,
Alistair.

**Comment by cdlm** [comment]
I saw later that it's only the windows build which fails, sorry.

Here's the VM that was used to do the bootstrap (I think). But then it's downloaded automatically by the bootstrap script, so it should be correct.
```
5.0 5.0.201806281256 Mac OS X built on Jun 28 2018 13:06:06 UTC Compiler: 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31) [Production Spur VM]
CoInterpreter VMMaker.oscog-eem.2401 uuid: 29232e0e-c9e3-41d8-ae75-519db862e02c Jun 28 2018
StackToRegisterMappingCogit VMMaker.oscog-eem.2401 uuid: 29232e0e-c9e3-41d8-ae75-519db862e02c Jun 28 2018
VM: 201806281256 https://github.com/OpenSmalltalk/opensmalltalk-vm.git
Date: Thu Jun 28 14:56:30 2018 CommitHash: a8a1dc1
Plugins: 201806281256 https://github.com/OpenSmalltalk/opensmalltalk-vm.git
```

**Comment by akgrant43** [comment]
Hi Damien,

That's a really old VM and doesn't have the required primitives for Pharo 8.  You should have one dated 5 Jan 2019 or later.

The CI build used:

Target VM: Date: Mon Feb 18 09:42:23 2019 CommitHash: f9ae4a14

Cheers,
Alistaiir

**Comment by cdlm** [comment]
urgh 😑
when do we fix that vm/image versioning hassle (and how…) ?

**Comment by akgrant43** [comment]
Not a solution, but at least makes the issue more explicit:

There's already a check in the image for the VM date.  I think I'll put forward a PR that updates the date.

At least the error will be meaningful (something like VM is too old).

**Comment by cdlm** [comment]
Images could start with a `#!/usr/bin/env pharo-image-runner` shebang, which would proceed to spawning the matching VM and sources file…

**Comment by akgrant43** [comment]
This could be used to ensure the VM is correct for the image type, i.e. 32 bit vs 64 bit, cog vs stack, etc., but it doesn't really handle versions / releases within those groups (at the moment).

**Review by akgrant43 — CHANGES_REQUESTED** [review]
Hi Damien,

Running the hello example results in:

```
$ ./pharo Pharo.image clap hello --shout you
Renamed to #implicitMeaning:efaultMeaning: called from ClapCodeEvaluator class>>#evaluate has been deprecated.
Renamed to #implicitMeaning:efaultMeaning: called from ClapCommand class>>#forHelp has been deprecated.
HELLO, YOU!
```

Can we get rid of the deprecation warnings before merging?

Thanks,
Alistair

**Review by akgrant43 — APPROVED** [review]
Deprecation messages are gone.

I tried this with a couple of my applications.  Only simple command lines, but it worked well.  I'm looking forward to having this in the image. :-)

**Comment by akgrant43** [comment]
Actually, I'll have to postpone the approval - there are a couple of automated test failures that look related:

- Unix32.Clap.Tests.Integration.ClapDocumentationTest
- MacOSX32.Clap.Tests.Integration.ClapDocumentationTest

**Comment by akgrant43** [comment]
Hi Damien,

ClapDocumentationTest>>testHelloShortUsage hasn't been updated to reflect the --language option that was added.

Cheers,
Alistair

**Comment by cdlm** [comment]
Sorry about that, should be fixed. I'm trying a bootstrap now… *edit* …and it seems to be working.

**Comment by akgrant43** [comment]
Hi Damien,

It looks like this is triggering a number of test failures:

- ClapPharoVersion is causing #testHashMethodNeedsToBeInComparingProtocol to fail.
- ClapMatchesTest is causing #testNoUnusedTemporaryVariablesLeft to fail.
- Several of the test #setUp methods don't call super setUp.

Cheers,
Alistair

**Comment by cdlm** [comment]
> * ClapPharoVersion is causing #testHashMethodNeedsToBeInComparingProtocol to fail.

That's because I use `#perform:`, which isn't really… satisfying… but easy to remedy by adding `#meaning:` blocks in the command spec.

> * ClapMatchesTest is causing #testNoUnusedTemporaryVariablesLeft to fail.
> * Several of the test #setUp methods don't call super setUp.

Easy to fix, just not sure I'll have enough focus time this weekend…

**Comment by akgrant43** [comment]
> > * ClapPharoVersion is causing #testHashMethodNeedsToBeInComparingProtocol to fail.
> 
> That's because I use `#perform:`, which isn't really… satisfying… but easy to remedy by adding `#meaning:` blocks in the command spec.

This just needs ClapPharoVersion>>hash to be moved to the 'comparing' protocol (from 'formats').

**Comment by Ducasse** [comment]
Thank you both. I really want to stress test more Clap because we should have a really clean way to create command line :). 

BTW I do not really these rules that raises issues instead of fixing them. We will have to do something about this because it slows us. 

@Alistair damien is travelling on the far west of france this week-end.

**Comment by akgrant43** [comment]
> BTW I do not really these rules that raises issues instead of fixing them. We will have to do something about this because it slows us.

I think the real issue here is all the noise created by all the other unrelated test failures.  If anyone could run the test suite and be confident that any failure was due to changes they made they would look much more closely at them.  The multiple repeating failures mean that people tend to miss the real issues.

That actually happened here.  I guess that one or more of the #testHashMethodNeedsToBeInComparingProtocol, #testNoUnusedTemporaryVariablesLeft and #setUp test failures were present when I reported the deprecated message sends.  Which has meant that Damien has had to go back and do multiple fixes (sorry about that, Damien).  This probably wouldn't have happened if the unrelated test failures weren't there.

This obviously isn't an easy problem to solve - several people have put quite a bit of effort in and it still persists.

Cheers,
Alistair

**Comment by cdlm** [comment]
I don't see what you report in the CI build logs from Jenkins, and when I push I get a mail from Travis with an unrelated issue (my account doesn't have credentials)… are you running those tests from the test runner by hand ?

**Comment by akgrant43** [comment]
Hi Damien,

I don't have CI credentials either.  Clicking on Details on this page takes me to Jenkins, I then select "Tests" from the top menu bar (it has a 12 next to it indicating 12 failures).

On the Tests page in the 9 existing failures are the three tests that I mentioned above (the #setUp test is  #testAndMakeSureSuperSetupIsCalledAsFirstMessageInSetupMethodsOfTestCases).

I then ran them by hand to confirm that it is Clap related classes that are triggering the failures.

HTH,
Alistair

**Comment by cdlm** [comment]
Thanks!

The test code isfixed. The `hash` redefinition requires a small redesign, working on that…

**Review by akgrant43 — APPROVED** [review]
- Deprecation messages and related test failures have all been resolved.
- Remaining test failures are pre-existing and unrelated.
- Examples work out-of-the-box


Ready to be merged...

**Comment by cdlm** [comment]
🔔

**Comment by Ducasse** [comment]
I was checking and this is good that this is in the baseline of ide!

**Pull request merged**
