### PR TITLE
22052-Adapt-menubar-style-to-fit-the-taskbar-style

### PR DESCRIPTION
**Pull request by jecisc**
Customize menubar style to fit the taskbar one.

https://pharo.fogbugz.com/f/cases/22052/Adapt-menubar-style-to-fit-the-taskbar-style

### CODE REVIEW

**Comment by astares** [comment]
Screenshot?

**Comment by jecisc** [comment]
Comming, for now I fight with some bugs :(

**Comment by jecisc** [comment]
@astares 
darkmenu
whitemenu

**Comment by astares** [comment]
Great!

**Comment by VincentBlondeau** [comment]
Needs to execute : MenubarMorph reset to see the changes

**Review by VincentBlondeau — APPROVED** [review]
Great!

**Comment by MarcusDenker** [comment]
now there is a conflict

**Comment by jecisc** [comment]
Corrected @MarcusDenker

**Pull request merged**
