### PR TITLE
22746 cleanup dirty package polymorph widgets into polymorph widgets core

### PR DESCRIPTION
**Pull request by astares**
https://pharo.fogbugz.com/f/cases/resolve/22746

### CODE REVIEW

**Comment by MarcusDenker** [comment]
there seems to be a conflict

**Comment by astares** [comment]
@MarcusDenker 

Mmmhh ... strange - latest  Pharo 7.0.0
Build information: Pharo-7.0.0+rc1.build.34.sha.ab528ddbee4c39cf2e4c2111184d21fbf217bc82 (64 Bit)
does not show the package as dirty anymore.

```Smalltalk
RPackageOrganizer default packages select: [:each | each isDirty ]
```

only "Calypso-SystemQueries" and "Reflectivity"....

**Comment by pavel-krivanek** [comment]
try on the repository: Extra - Recalculate dirty packages

**Comment by astares** [comment]
This one is not relevant in latest image as this package is not dirty anymore - we can close it.

Still Reflectivity and one from Calypso need to be fixed

**Pull request closed without merging**
