### PR TITLE
Rename "category" variables to "protocol"

### PR DESCRIPTION
**Pull request by jecisc**
We have 3 way to call protocols in the image and this is crazy to understand the code.

This is a tiny step toward unification: Renaming some variables "category" to use "protocol"

### CODE REVIEW

**Comment by MarcusDenker** [comment]
but take care: category is a symbol, while protocol is an instance of protocol (see class Protocol)

This got very confusing by someone adding #protocol to CompiledMethod and Behavior>>#protocols both to return categories... (aka symbols).

So this isn a mess and needs a bit more thinking.

**Comment by MarcusDenker** [comment]
There is https://github.com/pharo-project/pharo/issues/10856

**Comment by MarcusDenker** [comment]
- Does Protocol as an object even make sense?
- There is allProtocol, but we never use it
- if we keep Protocol, we should not have "#protocol" returning just a symbol, because that would be confusing
- what do we get from just renaming the term category to protocol if it stays a symbol?
- What do we even want? e.g. it feels that people would like to be able to tag methods as both 'private' and 'acessing', which neither protocols nor categories can do

**Comment by jecisc** [comment]
I'll close this until we discuss for Pharo 12

**Pull request closed without merging**
