### PR TITLE
6505-AbstractFileReference--directories-invokes-subclass-method-

### LINKED ISSUE #6505: AbstractFileReference >> directories invokes subclass method
```
AbstractFileReference >> directories
	"Return all the directories (by opposition to files) contained in the receiver"

	| reference |
	reference := self resolve.
	^ (reference fileSystem directoryNamesAt: reference path) 
		collect: [ :aName | self withPath: self path / aName ]
```

path is not defined in AbstractFileReference

### PR DESCRIPTION
**Pull request by sic-f**
Move `path` up to AbstractFileReference and out of sublcasses FileReference and FileLocator

Fixes #6505

### CODE REVIEW

**Comment by sic-f** [comment]
### Note:

**Please do not merge yet until you've tested this branch on your local machine:**

1. Checking out this branch in Pharo does not break the image.
2. If checking out this branch is successful, try checking out a different branch and see if the image won't break, or won't freeze.

If number 2 is to be expected then I guess this is good to go?

**Comment by MarcusDenker** [comment]
another idea to test: download the CI build artefact.

What is already very promising: the CI can run all tests, there is a test failure but it is not related.

**Comment by sic-f** [comment]
> another idea to test: download the CI build artefact.
> 
> What is already very promising: the CI can run all tests, there is a test failure but it is not related.

@MarcusDenker thanks. How does one download the CI build artifact?

**Comment by MarcusDenker** [comment]
if you go to the "Details:  link behind the "This Commit has test failures", you end up here:

https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-7309/2/pipeline

this has in the upper left an tab "Artefacts" where you end here:

https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-7309/2/artifacts

the bootstrap-cache/Pharo9.0-PR-64bit-eac1e4c.zip is the image.

**Comment by MarcusDenker** [comment]
The very last commit now has these tests failing:

unix-64 / Tests-unix-64 / testAccessTime – Unix64.FileSystem.Tests.Attributes.Tests.DiskFileAttributesTest
2s
unix-64 / Tests-unix-64 / testCreationTime – Unix64.FileSystem.Tests.Attributes.Tests.DiskFileAttributesTest
2s
unix-64 / Tests-unix-64 / testModificationTime – Unix64.FileSystem.Tests.Attributes.Tests.DiskFileAttributesTest
2s
unix-64 / Tests-unix-64 / testAccessTime – Unix64.FileSystem.Tests.Attributes.Tests.FileReferenceAttributeTest
<1s
unix-64 / Tests-unix-64 / testChangeTime – Unix64.FileSystem.Tests.Attributes.Tests.FileReferenceAttributeTest
<1s
unix-64 / Tests-unix-64 / testCreationTime – Unix64.FileSystem.Tests.Attributes.Tests.FileReferenceAttributeTest
<1s
unix-64 / Tests-unix-64 / testModificationTime – Unix64.FileSystem.Tests.Attributes.Tests.FileReferenceAttributeTest

**Comment by sic-f** [comment]
> if you go to the "Details: link behind the "This Commit has test failures", you end up here:
> 
> https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-7309/2/pipeline
> 
> this has in the upper left an tab "Artefacts" where you end here:
> 
> https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-7309/2/artifacts
> 
> the bootstrap-cache/Pharo9.0-PR-64bit-eac1e4c.zip is the image.

@MarcusDenker ok I'll try out the downloaded image and fix the failing specs. 

<blockquote><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-7309/2/pipeline">Jenkins</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-7309/2/artifacts">Jenkins</a></strong></div></blockquote>

**Comment by sic-f** [comment]
@MarcusDenker I will close this PR and start another one. I will try something different this time.

Update:
This is the new PR #7310

**Pull request closed without merging**
