### PR TITLE
Enh/refac: Factorize code in refactoring transformation

### PR DESCRIPTION
**Pull request by Ducasse**

### CODE REVIEW

**Comment by Ducasse** [comment]
Broken tests are unrelated.

**Comment by MarcusDenker** [comment]
a nicer title would be good for the Friday mail. "Enh/refac" says not that much

**Comment by MarcusDenker** [comment]
(I normally add nicer titles myself, but the PR has no description)

**Comment by jecisc** [comment]
I think a better title can be: Factorize code in refactoring transformation

**Pull request merged**
