### PR TITLE
22286-Some-tests-in-Collections-are-failing-in-64-bits-images

### PR DESCRIPTION
**Pull request by tomooda**
use strings for equal but non-identical elements of OrderedCollection.

### CODE REVIEW

**Comment by Ducasse** [comment]
This looks good to me. 
Tx Tomo

**Review by pavel-krivanek — APPROVED** [review]

**Comment by jecisc** [comment]
There is now a conflict.

**Comment by tomooda** [comment]
I rebased to the current pharo-project:development.

**Comment by tomooda** [comment]
The conflict was made because the development branch fixed a part of this issue and resulted in a duplicate fix with this PR. I rebased and solved the conflicts. OrderedCollectionTest is now all green.

**Comment by Ducasse** [comment]
Hi tomo
since this changes is touching really far too many files. Could you create a new independent PR because I'm a bit lost here. 

Stef

**Comment by tomooda** [comment]
ok, I'll close this and open a new one.

**Pull request closed without merging**
