### PR TITLE
Simplify and speed up  #classVarNames and #allClassVarNames

### PR DESCRIPTION
**Pull request by MarcusDenker**
- do not sort #classVarNames
-  #allClassVarNames  does not need to be a Set as the class vars are unique over the hierarchy
- implement #allClassVarNames simpler in the style of #allInstVarNames
- remove a #asOrderedCollection from the code completion as it is not needed anymore

### CODE REVIEW

**Comment by MarcusDenker** [comment]
[SmalltalkImage allClassVarNames] bench 

Before:
124457.417 per second

After:
820793.283 per second

>6 times faster

**Review by pavel-krivanek — APPROVED** [review]
looks ok

**Comment by MarcusDenker** [comment]
sadly there are tests failing

testDefinitionString
testClassSelected
testNormalKernelClasses

due to expecting sorted class variables...

**Comment by svenvc** [comment]
sort/convert before testing should help

**Comment by MarcusDenker** [comment]
Now i changed MC to not sort... but maybe this is not good as the class vars are stored in a dictionary which means that the order is not guaranteed... 

So not yet a good solution.

I think I might break this into multiple parts: first just not use Set and simplify (but still sort), then have a look at sorting...

**Comment by gcotelli** [comment]
Keep in mind that the order of the class vars do not change randomly when written in Tonel format. Because this causes unexpected changes when commiting code.

**Comment by MarcusDenker** [comment]
Yes... I will close this PR and do the "class vars are not a set" simplification...

**Pull request closed without merging**
