### PR TITLE
Improve faulty parsing: generalize code snippets

### PR DESCRIPTION
**Pull request by privat**
PR #12778 (especially commit 19ab7557eb4c0127d1801853c81bf4d191d8ae6d) introduced the idea that testing the parser requires extensive examples of corner cases.

To do so, the method `RBFormatterTest >> testParseError` was extended with numerous simple pieces of broken code and tasked to check that the formatting of these pieces of code was ok-ish (i.e that no important pieces of information where lost during parsing then formatting).

The code was hackish and limited since the pieces of code were defined in a simple but ad hoc way and that the usage of these pieces of code was specific to the parse then format test method. Moreover, the test was just a big ugly loop.

The present PR refactors the whole thing and tries to solve the aforementioned issues while bringing the following benefits:

* each individual piece of code is reified as an instance of the new class `RBCodeSnippet` that also includes additional information (e.g. `isFaulty` if the parsing is expected to fail or `formattedCode` for the expected formatted code) and some helper methods.
* snippets and groups of snippets are accessible (and extendable) trough class methods like `allSnippets` and `badExpressions`
* snippets are testable with the new class `RBCodeSnippetTest` that have a single simple test method per AST usage (e.g. `testParse`, `testFormatCode`, etc.)
* RBCodeSnippetTest is a ParametrizedTestCase and relies on matrix test cases to execute all snippets on all tests.
  Note that it is possible to skip the execution of some specific combinations if needed. 
* AST clients from different packages can add method extensions on these classes to comprehensively run tests tailored to their concerns. OpalCompiler (the compiler), Shout (the styler/highlighter) and Renraku (the rule/critique engine) are extended to test compilation, execution, styling and critiques on numerous faulty pieces of code

Additional benefits: spotted and fixed ~~two~~ three bugs in:
 * `ReBadMessageRule >> basicCheck:`
 * `SHRBTextStyler >> styleTempBars:`
 * `RBDumpVisitor >> visitLiteralArrayNode:`

This serious PR belongs to the serious PR series "improve faulty parsing" but future PR are postponed until this PR is merged to avoid awful conflict resolution on test related code.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
load problem:

```
MetacelloNotification: Loading -> OpalCompiler-Tests-tonel.1 --- tonel:///builds/workspace/est_and_branch_Pipeline_PR-12847/64/src --- cache
Error: Package OpalCompiler-Tests-Plugins depends on the following classes:
  RBCodeSnippetTest
  RBCodeSnippet
You must resolve these dependencies before you will be able to load these definitions: 
  RBCodeSnippet>>#compile
  RBCodeSnippetTest>>#testCompile
  RBCodeSnippetTest>>#testExecute
```

**Comment by privat** [comment]
Ahalala, I'm not sure how to declare such dependencies. Maybe I shouldn't have tried to put the correct method in the correct package :(
I tried something, but I basically don't know what I'm doing...

**Comment by privat** [comment]
Now I got « IceGitHubError: API rate limit exceeded for 128.93.193.1. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) » :(

**Comment by privat** [comment]
Tests are green \o/ (except on Windows, that currently has some ME vibes)

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
