### PR TITLE
13526-Attempt-to-release-a-shared-cairo-font-face

### LINKED ISSUE #13526: Attempt to release a shared cairo_font_face
**Bug description**
We are getting recently very often this inform box during image saving: `Attempt to release a shared cairo_font_face. Please report this on pharo-dev mailing list`.  Sometimes even a dozen of them.

It comes from: 'CairoFontFaceExecutor>>#finalize' and this PR describes the background of it: https://github.com/pharo-project/pharo/pull/565

> A cairo_font_face could still be referenced from external heap and further used.
> Thus we must NOT release the FT_Face until the external reference count drops to 1.
> 
> Thus the CairoFontFace is not a good place for retaining a strong reference to the FT2Face, because the reference will vanish as soon as the Smalltalk object is garbage collected, while some external cairo_font_face still point on it.
> It's better to have the strong reference in the executor, and avoid garbageCollecting the executor while there are external references to the resource data...
> 
> The solution is to use a specific CairoFontFaceExecutor.
> If the resource is shared, then we have no other choice than regularly polling the ref count in a new Process.
> This process must stop whenever the session change.

It is probably related to changes in ephemerons. So first question is, have you seen it as well? @nicolas-cellier-aka-nice

### PR DESCRIPTION
**Pull request by tesonep**
Fix #13526 and #13543

- The surfaces should be released even if they are not registered in the SurfacePlugin. The Plugin handles this scenario. Also, the findSurface primitive is only working for 32bits pointers.
- The CairoFontFace can be released when not used (it is using an internal reference counting mechanism, so it is safe to release them).
- The CairoFontFace should keep a strong reference to the FTFace, before it was kept in the executor (ugly... )
- The executor is not needed anymore and we can use the ExternalAddress as handle to finalize.

### CODE REVIEW

**Comment by tesonep** [comment]
Now it is safe to keep the reference in teh CairoFontFace as now using Epehemerons the objects is not dereferenced until the object is finalized.

https://github.com/pharo-project/pharo/pull/565

**Review by guillep — APPROVED** [review]
Good!

**Comment by jecisc** [comment]
CI hit github API rate limit. This was fixed only in P12

**Comment by Ducasse** [comment]
Thanks Pablo this is good to see all these improvements.

**Comment by Ducasse** [comment]
Should we backport it to P11?

**Comment by MarcusDenker** [comment]
the PR is for Pharo11, we should merge it here and then sync all the Pharo11 changes next week to Pharo12

**Pull request merged**
