### PR TITLE
Don't make SDL_Texture autoRelease from renderer

### LINKED ISSUE #8961: SDL_Renderer>>primCreateTextureFormat:(...) shouldn't register the texture for autoRelase
**Bug description**

The SDL_Renderer method that creates a texture, marks it for `autoRelease` by explicitly executing `SDL_Texture >> initialize`. Related code:

```
SDL_Renderer >>
createTextureFormat: format access: access width: width height: height
	^(self primCreateTextureFormat: format access: access width: width height: height) initialize.

SDL_Renderer >>
primCreateTextureFormat: format access: access width: width height: height
	^ self ffiCall: #( SDL_Texture SDL_CreateTexture ( self , Uint32 format , int access , int width , int height ) )

SDL_Texture >>
initialize
	self autoRelease
```

But this isn't how the SDL2 library expects to handle it:

- In SDL, when the texture is created by the renderer, it's appended in a linked list of textures:
https://github.com/spurious/SDL-mirror/blob/release-2.0.7/src/render/SDL_render.c#L547
- When the SDL renderer is destroyed, it iterates over that list and destroys the textures. 
https://github.com/spurious/SDL-mirror/blob/release-2.0.7/src/render/SDL_render.c#L2076
- The related SDL2 documentation that we found isn't very eloquent. But the example of use here shows that the texture isn't explicitly destroyed:
https://wiki.libsdl.org/SDL_CreateTexture

We detected this problem when debugging a bug in Bloc with OSWindow/SDL2 with @tesonep last month.

**To Reproduce**
1. Compile `SDL2Example>>demoAutoreleasedTexture` (see code below)
2. Execute it from workspace: `SDL2Example new demoAutoreleasedTexture`
3. Click on the IDE or resize the OS window of the image.
4. You will see a popup from SDL (see screenshot below), and this in the terminal: ` WARN: Assertion failure at SDL_DestroyTexture_REAL (/Users/travis/build/OpenSmalltalk/opensmalltalk-vm/build.macos64x64/pharo.cog.spur/build/third-party/SDL2-2.0.7/src/render/SDL_render.c:2038), triggered 6 times:
  'texture && texture->magic == &texture_magic'`

**Expected behavior**
Don't mark for autoRelease the texture.

**Version information:**
 - OS: MacOS (but multiplatform)
 - Pharo Version: 9

**Expected development cost**
I'm preparing the PR.

------

**Code**
Method to compile in `SDL2Example` (instance side):
~~~smalltalk
demoAutoreleasedTexture
	| window renderer texture |
	"Create the window and the renderer."
	window := SDL2
		          createWindow: 'Test Window'
		          x: 100
		          y: 100
		          width: 200
		          height: 200
		          flags: SDL_WINDOW_SHOWN.
	renderer := window createDefaultRenderer.

	"Create the texture"
	texture := renderer
		           createTextureFormat: SDL_PIXELFORMAT_XRGB8888
		           access: SDL_TEXTUREACCESS_STREAMING
		           width: Display width
		           height: Display height.
	texture updateTexturePixels: Display bits pitch: Display width * 4.

	"Quit"
	renderer destroy.
	window destroy
~~~

---

**Screenshots**
Screen Shot 2021-04-05 at 17 10 46

### PR DESCRIPTION
**Pull request by tinchodias**
Fixes #8961

### CODE REVIEW

**Comment by tinchodias** [comment]
@tesonep I forgot to push this change.

Also we could:
- inline primCreateTextureFormat:(...) into createTextureFormat:(...) as other public method in that class that just do the ffiCall.
- delete `SDL_Texture >> initialize`. If a library user wants to autoRelease, just send autoRelease without hiding it under initialize.

I don't have experience in SDL to tell all cases when the textures must be released explicitly but saw one on internet... a texture loaded from a file that they were destroying.

**Comment by Ducasse** [comment]
Martin can you open issue for the possible future actions?

**Comment by tinchodias** [comment]
Do you mean with more time in advance?
I opened an issue some minutes before sending the PR:
https://github.com/pharo-project/pharo/issues/8961

**Comment by tinchodias** [comment]
Ah, sorry. I re-read and now understand your request for future acitons.

**Pull request merged**
