### PR TITLE
5246--AST-Core-Tests-package-disappeared

### LINKED ISSUE #5246: AST-Core-Tests package disappeared
We lost all tests for the AST.

### PR DESCRIPTION
**Pull request by pavel-krivanek**
revert loading of AST-Core-Tests

fixes #5246

### CODE REVIEW

**Comment by MarcusDenker** [comment]
31 tests fail

**Comment by jecisc** [comment]
This is not that simple:

```Smalltalk
{ #category : #accessing }
RBParserTest >> exampleClasses [
	<sampleInstance>
	^ Array
		with: self parserClass
		with: RBScanner
		with: RBProgramNode
		with: BIConfigurableFormatter
]
```

**Comment by Ducasse** [comment]
I really hate when people do not respect dependencies. 
You see this method is terrible because it creates a dependencies from the AST core to its users. When will we start to consider that dependencies are important if we want to have a modular system. I did not even thought that they was a dependency and of course no baseline was reflecting this.

**Comment by Ducasse** [comment]
Thanks Pavel I owe you some beers :)

**Pull request merged**
