### PR TITLE
Update dependencies to Roassal and Array2D

### LINKED ISSUE #15147: Enhance roassal with version v1.05
The current version of Roassal in Pharo 12 is v1.04b, in object profile.
v1.05 is in pharo-graphics https://github.com/pharo-graphics/Roassal/releases/tag/v1.05

### PR DESCRIPTION
**Pull request by akevalion**
This pull request addresses these issues:
- https://github.com/pharo-project/pharo/issues/15147
- https://github.com/pharo-project/pharo/issues/12140

### CODE REVIEW

**Comment by MarcusDenker** [comment]
This PR was merged even though it makes tests fail. Now these tests fail for *every other PR* that we will run the tests for.

```
Error

an OrderedCollection('RSZoomTickDecoration>>#renderPlots') should have been empty
Stacktrace

TestFailure
an OrderedCollection('RSZoomTickDecoration>>#renderPlots') should have been empty
ReleaseTest(TestAsserter)>>assert:description:resumable:
ReleaseTest(TestAsserter)>>assert:description:
ReleaseTest(TestAsserter)>>assertEmpty:
ReleaseTest>>testNoSentButNotImplementedSelectors
ReleaseTest(TestCase)>>performTest
```

**Comment by akevalion** [comment]
Hi, I saw that these tedts failing on mac and linux. Sadly from pharo 12 I can not reproduce the error

**Comment by MarcusDenker** [comment]
the method sends #clipChildren: which does not exist

Untitled

**Comment by akevalion** [comment]
I will create a new pr

**Pull request merged**
