### PR TITLE
New emergency debugger

### PR DESCRIPTION
**Pull request by StevenCostiou**
https://thepharo.dev/2020/05/13/ed-your-new-emergency-debugger/

Note that further work will be done to improve its independence (for now it too tied on Morphic), and possible bugs.

It needs to be used to highlight bugs.

Can be deactivated in settings>emergency debugger.

### CODE REVIEW

**Comment by Ducasse** [comment]
Steven 
Running tests in 692 Packages
SystemNotification: EDDebuggingAPITest>>testTerminateSession(ed is shadowed)
SystemNotification: EDDebuggingAPITest>>testCloseEmergencySession(ed is shadowed)
SystemNotification: RBDummyRefactoryTestDataApp>>tempVarOverridesInstVar(temporaryVariable is shadowed)
SystemNotification: RBRefactoryTestDataApp>>tempVarOverridesInstVar(temporaryVariable is shadowed)
SystemNotification: RBSmalllintTestObject>>tempVarOverridesInstVar(temporaryVariable is shadowed)
SystemNotification: ReTempVarOverridesInstVarRuleTest>>sampleMethod:(dummy1 is shadowed)
SystemNotification: ReTempVarOverridesInstVarRuleTest>>sampleMethod:(dummy2 is shadowed)
SystemNotification: ReTempVarOverridesInstVarRuleTest>>sampleMethod:(dummy3 is shadowed)
NewUndeclaredWarning: UndefinedObject>>noMethod (Foo is Undeclared)
NewUndeclaredWarning: UndefinedObject>>noMethod (Foo is Undeclared)
NewUndeclaredWarning: UndefinedObject>>noMethod (Foo is Undeclared)
\\Sending interrupt signal to process
./pharo: line 11: 79891 Terminated: 15          "$DIR"/"pharo-vm/Pharo.app/Contents/MacOS/Pharo" --headless "$@"

**Comment by StevenCostiou** [comment]
> SystemNotification: EDDebuggingAPITest>>testTerminateSession(ed is shadowed)
> SystemNotification: EDDebuggingAPITest>>testCloseEmergencySession(ed is shadowed)

Thanks for the notification, I'll look into those.
However, the others are not in my commits... :/

**Comment by Ducasse** [comment]
We will check them.

**Comment by Ducasse** [comment]
Steven I think that there is a problem with the bootstrap because all the three builds are systematically crashing. But may be I'm wrong.

**Comment by Ducasse** [comment]
I do not know if DebugSession >> signalDebuggerError: anError is part of the core bootstrap. 
If this is the case this may be the cause for the problem. 
And it means that we should define a registration mechanism so that when ED is loaded later it can be invoked. Now I'm not sure.

**Comment by Ducasse** [comment]
I spent some times reading bootstrap scripts and I found that baseline: of BaselineOfPharoBootstrap does not contain a reference to the package of DebugSession so may be the problem does not come from there.

**Comment by StevenCostiou** [comment]
Thanks for the investigation.
I will try to run the image artifact locally and see what's failing.
I can also deactivate ed and let it as a setting to see if it works.

**Comment by StevenCostiou** [comment]
Still not passing.

**Comment by StevenCostiou** [comment]
I downloaded the artefact image.
Locally it runs. I'm running all tests to see.

**Comment by StevenCostiou** [comment]
> I downloaded the artefact image.
> Locally it runs. I'm running all tests to see.

So 8 tests fail, but it seems normal and they are absolutely not related. It's tests verifying that no packages are empty for ex., or that there are no obsolete classes (and they fail because pckgs or classes generated by other tests remain).

So I need a way to reproduce the failure of the CI :/

**Comment by Ducasse** [comment]
You can run the scripts on your machine.

**Comment by Ducasse** [comment]
Is your machine 32bits?

**Comment by Ducasse** [comment]
In the artefacts pane you can get access to some of the images and logs

**Comment by Ducasse** [comment]
This is really the case where I would love to be able to connect to an image remotely.
So EdRemote :)

**Comment by guillep** [comment]
Well, somehow the process systematically timeouts on all platforms while running the tests, so I cannot ignore there is a problem. The CI runs in headless mode. Maybe that triggers the problem? In headless mode there is no MorphicUIManager, and so on...

**Comment by StevenCostiou** [comment]
I took the image from the artefact panes and it works fine.
I'm on 64bits.
I need to test the scripts, I'll look in the artefact list, are they there?

**Comment by StevenCostiou** [comment]
> Well, somehow the process systematically timeouts on all platforms while running the tests, so I cannot ignore there is a problem. The CI runs in headless mode. Maybe that triggers the problem? In headless mode there is no MorphicUIManager, and so on...

Yes, I need to reproduce the same execution conditions (or as much as possible).
I'm looking for the scripts.

**Comment by guillep** [comment]
Check https://github.com/pharo-project/pharo/blob/Pharo9.0/bootstrap/scripts/runTests.sh

It's actually just doing:

```bash
$ ./pharo Pharo.image test --junit-xml-output --stage-name=totostage '.*'
```

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo">pharo-project/pharo</a></strong></div><div>Pharo is a dynamic reflective pure object-oriented language supporting live programming inspired by Smalltalk. - pharo-project/pharo</div></blockquote>

**Comment by Ducasse** [comment]
steven this is a super nice scenario for remote ED.

**Comment by Ducasse** [comment]
Guille gave me a little lecture on debugging:

- donwloaded the image
- donwloaded a 90 vm
- `./pharo Pharo.image test --junit-xml-output --stage-name=totostage '.*'`
- waiting until no more test results are outputted. 
- `kill - SIGUSR1 ...`

**Comment by Ducasse** [comment]
[crash.txt](https://github.com/pharo-project/pharo/files/4836239/crash.txt)

**Comment by Ducasse** [comment]
This shows that the Morphic UI process does not exist anymore so probably suspended.

**Comment by Ducasse** [comment]
Some ED tests are red probably the printing should be updated for new blocks.

```
printWithArgsValueOn: aStream
	| keywords |
	aStream << self method methodClass name.
	aStream << '>>'.
	self method numArgs = 0
		ifTrue: [ aStream << self method name.
```

method is a compiledBlock and not have name....

**Comment by Ducasse** [comment]
composeStackText
	| str stack |
	str := self newTextStream.
	stack := self shortStack.
	str cr.
	self
		writeSectionTitle:
			'STACK (' , stackSelectionIndex printString , '/'
				, debugAPI stackSize printString , ')'
		on: str.
	1 to: stack size do: [ :i | 
		| textStream text |
		textStream := self newTextStream.
		(stack at: i) printWithArgsValueOn: textStream.

**Comment by StevenCostiou** [comment]
> This shows that the Morphic UI process does not exist anymore so probably suspended.

Ha, probably I halt the process in the tests and I don't resume it!

**Comment by StevenCostiou** [comment]
> Some ED tests are red probably the printing should be updated for new blocks.
> 
> ```
> printWithArgsValueOn: aStream
> 	| keywords |
> 	aStream << self method methodClass name.
> 	aStream << '>>'.
> 	self method numArgs = 0
> 		ifTrue: [ aStream << self method name.
> ```
> 
> method is a compiledBlock and not have name....

Arg yes I did that before the new blocks!

**Comment by Ducasse** [comment]
`  ./pharo Pharo9.0-PR-64bit-6e56be3.image test --junit-xml-output --stage-name=totostage 'Emergency.*'` 
shows that the problem is kicked by ed tests themselves.

**Comment by Ducasse** [comment]
We removed 

```
terminateAllProcesses
	"self allRunningProcesses
		do: [ :process | process ifNotNil: [ process terminate ] ]"
```
and the tests are finishing!!!

**Comment by Ducasse** [comment]
Your turn :)

**Comment by StevenCostiou** [comment]
Thanks for the investigation @Ducasse @guillep :)
For the note this is related to that: #6421
Basically I took code from the process browser to know what processes I can kill or not, and I test the ED API to kill all other processes.
Of course, test processes are not in that list (which is normal).
This a question: how can I know what processes I can kill or not without destroying the image? 
I believe, as said there #6421, that a "system level" interface could help (i.e., give me critical process for the current image).

**Comment by StevenCostiou** [comment]
I think I will remove the test... for now I do not see how to make sure we don't kill the test process during the CI tests, while in your image you might want to kill all processes except the ones that keep the image running.

**Pull request merged**
