### PR TITLE
3463-StringencodeDoublingQuoteOn-does-not-do-work-anymore

### LINKED ISSUE #3463: String>>encodeDoublingQuoteOn: does not do work anymore
This method has no test and is not doing what it says. 

Expecting:

```Smalltalk
String streamContents: [ :s | 'Foo''bar' encodeDoublingQuoteOn: s ] "'''Foo''''bar'''"
```

Actual: 
```Smalltalk
String streamContents: [ :s | 'Foo''bar' encodeDoublingQuoteOn: s ] "'$''$F$o$o$''$''$b$a$r$'''"
```

### PR DESCRIPTION
**Pull request by jecisc**
Fix String>>encodeDoublingQuoteOn: and add test

Also do some cleanings

Fixes #3463

### CODE REVIEW

**Comment by jecisc** [comment]
Well, in fact I see that it is a duplication of the store on... So I'll just deprecate it.

**Comment by svenvc** [comment]
Indeed: thank you for reducing the number of methods on String by 1 ;-)

**Review by MarcusDenker — APPROVED** [review]
ok

**Comment by MarcusDenker** [comment]
failing test not related

**Pull request merged**
