### PR TITLE
Remove old RewriteTools

### PR DESCRIPTION
**Pull request by jordanmontt**
Removing the (old) Rewrite Tool that was available in NautilusRefactoring. Also I am removing some old packages that were never loaded into Pharo. Those were from a PR that I did some time ago.

In another PR I will add the new version of Rewrite Tools Set that I developed. I will do that PR to NewTools.

The new version
Capture d’écran 2023-02-09 à 22 37 19

### CODE REVIEW

**Comment by jecisc** [comment]
osx-64 / Tests-osx-64 / testNarrowingReturnsSameElementsThatCallingDirectly – MacOSX64.HeuristicCompletion.Tests.Core.CoNarrowHistoryFetcherTest<1s
unix-64 / Tests-unix-64 / testNarrowingReturnsSameElementsThatCallingDirectly – Unix64.HeuristicCompletion.Tests.Core.CoNarrowHistoryFetcherTest<1s
unix-64 / Tests-unix-64 / testAsDictionary – Unix64.System.OSEnvironments.Tests.OSEnvironmentTest<1s
unix-64 / Tests-unix-64 / testAssociations – Unix64.System.OSEnvironments.Tests.OSEnvironmentTest<1s
unix-64 / Tests-unix-64 / testKeys – Unix64.System.OSEnvironments.Tests.OSEnvironmentTest<1s
unix-64 / Tests-unix-64 / testValues – Unix64.System.OSEnvironments.Tests.OSEnvironmentTest<1s
windows-64 / Tests-windows-64 / testNarrowingReturnsSameElementsThatCallingDirectly – Windows64.HeuristicCompletion.Tests.Core.CoNarrowHistoryFetcherTest<1s
windows-64 / Tests-windows-64 / testAsDictionary – Windows64.System.OSEnvironments.Tests.OSEnvironmentTest<1s
windows-64 / Tests-windows-64 / testAssociations – Windows64.System.OSEnvironments.Tests.OSEnvironmentTest<1s
windows-64 / Tests-windows-64 / testKeys – Windows64.System.OSEnvironments.Tests.OSEnvironmentTest<1s
windows-64 / Tests-windows-64 / testValues – Windows64.System.OSEnvironments.Tests.OSEnvironmentTest

Some of them are known random failures but I’m not sure all are

**Comment by jecisc** [comment]
Lot of them are like this:

```st
Error
Illegal continuation byte for utf-8 encoding
Stacktrace
ZnInvalidUTF8
Illegal continuation byte for utf-8 encoding
ZnUTF8Encoder>>error:
ZnUTF8Encoder>>errorIllegalContinuationByte
ZnUTF8Encoder>>nextCodePointFromStream:
[ :stream |
		[ byteStream atEnd ] whileFalse: [ | codePoint |
			codePoint := self nextCodePointFromStream: byteStream.
			(codePoint > 255 and: [ stream originalContents isWideString not ])
				ifTrue: [ | wideString position |
					position := stream position.
					wideString := WideString from: stream originalContents.
					stream on: wideString; setFrom: position + 1 to: position ].
			stream nextPut: (Character value: codePoint) ] ] in ZnUTF8Encoder(ZnUTFEncoder)>>decodeBytes:
String class(SequenceableCollection class)>>new:streamContents:
String class(SequenceableCollection class)>>streamContents:
ZnUTF8Encoder(ZnUTFEncoder)>>decodeBytes:
ByteArray>>decodeWith:
ByteArray>>utf8Decoded
FFIExternalString>>basicHandle:at:
FFIExternalString(FFIExternalType)>>handle:at:
FFIExternalArray>>at:
UnixEnvironment>>environAt:
UnixEnvironment>>keysAndValuesDo:
UnixEnvironment(OSEnvironment)>>valuesDo:
[ :stream|
		self valuesDo: [ :value | stream nextPut: value ]] in UnixEnvironment(OSEnvironment)>>values
Array class(SequenceableCollection class)>>new:streamContents:
Array class(SequenceableCollection class)>>streamContents:
UnixEnvironment(OSEnvironment)>>values
OSEnvironmentTest>>testValues
OSEnvironmentTest(TestCase)>>performTest
```

**Comment by Ducasse** [comment]
I think that the broken tests are unrelated to the issue.

**Comment by demarey** [comment]
shouldn't the PR adding new version of Rewrite Tools be done before removing the old one? Else, we will get some Pharo versions without rewrite tools.

**Comment by jordanmontt** [comment]
PR to add the new Rewriting Tools is here: https://github.com/pharo-spec/NewTools/pull/464

I think this PR that removes the old one is ready to merge

**Review by guillep — APPROVED** [review]
Ok!

**Pull request merged**
