### PR TITLE
21483 Cleanup romanNumber and add test

### PR DESCRIPTION
**Pull request by astares**
https://pharo.fogbugz.com/f/cases/21483/Cleanup-romanNumber-and-add-test

### CODE REVIEW

**Review by peteruhnak — COMMENTED** [review]
Not sure why this is even part of the core... however it would be a good idea to have it symmetric to `Integer>>printStringRoman`, which can also produce negative numbers.

`-5 printStringRoman romanNumber`

And probably also a comment in each pointing to the other method.

**Comment by astares** [comment]
Yes - we can do provide it symmetric. But then this is a new feature and you should open a new
bug/PR after this one is merged.

**Comment by peteruhnak** [comment]
You are right, this is refactoring, not refactoring + feature changing. :)

I've made a separate issue https://pharo.fogbugz.com/f/cases/21504/String-romanNumber-should-be-symmetric-to-Integer-printStringRoman

**Review by peteruhnak — APPROVED** [review]

**Review by MarcusDenker — APPROVED** [review]
good!

**Pull request merged**
