### PR TITLE
4540-Integrate-DrTests

### LINKED ISSUE #4540: Integrate DrTests
Integrate DrTests project : https://github.com/juliendelplanque/DrTests

### PR DESCRIPTION
**Pull request by juliendelplanque**
Added DrTests v1.0.1 (https://github.com/juliendelplanque/DrTests/releases/tag/v1.0.1).

Fixes #4540

### CODE REVIEW

**Comment by juliendelplanque** [comment]
Can someone tell me if errors on CI are caused by my PR?

I think not but I am to sure.

**Comment by VincentBlondeau** [comment]
You don't, except if you patch Epicea or try to do things with it (related to test: testFileTreeRepository)

**Comment by juliendelplanque** [comment]
I do not get what you mean?

**Comment by VincentBlondeau** [comment]
Forgot the comma.... Try to run: testFileTreeRepository locally

**Comment by juliendelplanque** [comment]
I ran it and it works.

**Comment by juliendelplanque** [comment]
Ok, so now only OSX build crash.

**Comment by Ducasse** [comment]
Can you fix these two tests?

Error

Subclasses of TestCase should have #setUp methods in one of the following protocols #(#running)
Stacktrace

ProperMethodCategorizationTest(TestAsserter)>>assert:description:resumable:
ProperMethodCategorizationTest(TestAsserter)>>assert:description:
ProperMethodCategorizationTest>>assureAll:areCategorizedInProtocols:whenSubclassOf:
ProperMethodCategorizationTest>>testSetUpMethodInSUnitTestsNeedsToBeInRunningProtocol
ProperMethodCategorizationTest(TestCase)>>performTest
unix-32 / Tests-unix-32 / testTestCasesEndsWithTestOrTestCase – Unix32.ReleaseTests.Release.ReleaseTest
<1s
Error

A test class (subclass of TestCase) should have it's name ending with 'Test' or 'TestCase' Violations: - DTTestCoverageTestForCoverage

**Comment by juliendelplanque** [comment]
@Ducasse done!

**Pull request merged**
