### PR TITLE
4043-migration-of-BISettingPreviewer-to-Spec-2-

### PR DESCRIPTION
**Pull request by CafeKrem**
migration of BISettingPreviewer

### CODE REVIEW

**Comment by MarcusDenker** [comment]
there are tests failing that looks relevant to the change

**Comment by CafeKrem** [comment]
There is some easy issue to fix (new feature).
https://github.com/CafeKrem/PrettyPrinterUI/issues
feature #35 , #36 ,  #37

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/CafeKrem/PrettyPrinterUI">CafeKrem/PrettyPrinterUI</a></strong></div><div>Contribute to CafeKrem/PrettyPrinterUI development by creating an account on GitHub.</div></blockquote>

**Comment by MarcusDenker** [comment]
failing tests seem to be related:

windows-32 / Tests-windows-32 / testWhenAddNewWithSameAsAnOhterOneShouldRemoveTheOldOneFromTheSettingDropList – Windows32.BlueInk.Tests.Base.BISettingPreviewerTest
<1s
windows-32 / Tests-windows-32 / testWhenClickOnRemoveSettingButtonShouldRemoveItFromSettingDropListAndFromProvideMethodClass – Windows32.BlueInk.Tests.Base.BISettingPreviewerTest
<1s
windows-32 / Tests-windows-32 / testWhenClickOnSaveSettingButtonShouldCreateMethodClassSideWithProcolSettingsAndAddToSettingsDropList – Windows32.BlueInk.Tests.Base.BISettingPreviewerTest
<1s
windows-32 / Tests-windows-32 / testAndMakeSureSuperSetupIsCalledAsFirstMessageInSetupMethodsOfTestCases – Windows32.ReleaseTests.Tests.ProperlyImplementedSUnitClassesTest

**Comment by jecisc** [comment]
Please, do not integrate this one before I review it.

I might not have time before the next 2 weeks but I want to review it with Clément.

**Comment by Ducasse** [comment]
OK Cyril!

**Pull request closed without merging**
