### PR TITLE
Improve ProperClassCategorizationTest>>#testProperClassTagCasing

### LINKED ISSUE #9856: Improve ProperClassCategorizationTest>>#testProperClassTagCasing
Better use  

```
Smalltalk packages
```
as it is shorter and returns the packages already sorted (and also use better var name in block iteration)

### PR DESCRIPTION
**Pull request by astares**
Fix #9856

### CODE REVIEW

**Comment by MarcusDenker** [comment]
I think the reason that there is no Smalltalk reference is the idea to reduce references to globals... but then, it is true that "RPackageOrganizer default packages" is not really beautiful, either.

I sometimes think we need an explicit and easy way to send messages to "the image" that does not involve Globals, nor a Singleton pattern (which in the end not that much better...)

**Comment by astares** [comment]
OK, how to proceed?

Introduce a 

```Smalltalk
RPackageOrganizer defaultPackages
```
and use that? But it would be a reference to a global too, too a global class name.

**Comment by Ducasse** [comment]
Yes for example. 
We should not put it in Smalltalk :).

**Comment by MarcusDenker** [comment]
I really think we need to do an analysis of the Smalltalk references... today it is just clear "do not use it", but the alternatives are in some cases very ugly or even impossible, and in no case documented. (e.g. we need a way to send a message to "the system" without going via a class, e.g. to aks for the default compiler)

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
