### PR TITLE
fix: #10211 addSearch: -> addRule: adding two little tests to start

### PR DESCRIPTION
**Pull request by alesshosry**
Started to add some tests and method definition for missing methods.

### CODE REVIEW

**Comment by guillep** [comment]
Hi @AlessHo,

For documentation purposes, could you give some detail in the PR on:
 - what tests did you add?
 - why are they important?
 - Are there follow-ups expected?

**Comment by Ducasse** [comment]
We should go over RBDummyLint Test class side methods and check how we can turn them into executed tests.

**Comment by Ducasse** [comment]
- there are two tests in the PR. :)

**Comment by alesshosry** [comment]
Hi @guillep ,

1. 2 new tests are added under RBParseTreeSearcherTest subclass: **testSimpleAddSearch** and **testSimpleAddSearches**.
2. The purpose of adding these tests is to test **addSearch** and **addSearches** methods that were missing and added recently under RBParseTreeSearcher subclass. 
3. For the moment no more changes will be implemented, I will be checking the RBParseTreeSearcher and how it works ... then I will add some comments etc ... before implementing the same on RBDummyLint.

**Pull request merged**
