### PR TITLE
21494-Change-boostrap-to-not-load-Spec-Debugger

### PR DESCRIPTION
**Pull request by MarcusDenker**
Change boostrap to not load Spec-Debugger
	https://pharo.fogbugz.com/f/cases/21494/Change-boostrap-to-not-load-Spec-Debugger

### CODE REVIEW

**Comment by MarcusDenker** [comment]
SpecDebuggerTest needs to be removed, too

**Comment by MarcusDenker** [comment]
There is a reference in setGTDebuggerEnabledStatus:

**Comment by jecisc** [comment]
```
Error: This package depends on the following classes:
  SpecDebugger
  SpecPreDebugWindow
You must resolve these dependencies before you will be able to load these definitions: 
  GTSpecPreDebugWindow
  GTSpecPreDebugWindow>>#clear
  GTSpecPreDebugWindow>>#columnsFor:
  GTSpecPreDebugWindow>>#initialExtent
  GTSpecPreDebugWindow>>#initializeStackPane
  GTSpecPreDebugWindow>>#openFullDebugger
  SpecDebugger>>#availableAutomatically
  SpecDebugger>>#handlesContext:
  SpecDebugger>>#spanNewSessionFrom
```

**Review by dionisiydk — COMMENTED** [review]
Looks good. But I can't merge it into image and test

**Comment by pavel-krivanek** [comment]
download the prebuilt image

**Comment by MarcusDenker** [comment]
I tested it. Works.

**Pull request merged**
