### PR TITLE
Unify Slots and LiteralVariable in single hierarchy

### PR DESCRIPTION
**Pull request by dionisiydk**
We have three separate hierarchies of variables:
- Slot subclasses
- LiteralVariable subclases
- OCAbstractVariable subclasses

There are a lot of duplication between them
- compilation (emitStore:emitValue:)
- properties
- metalinks and breakpoints
- more

Here Slots and LiteralVariable are merged under common Variable superclass.
It is a first step:
- Variable with #name instance variable and corresponding compare methods from the Slot.
- properties protocol and class var are moved to Variable (most trivial thing to do)
- LiteralVariable is adopted to be polymorphic to Associations.

In next PRs more duplications will be removed.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
nice! I will have a look!

**Comment by dionisiydk** [comment]
Notice that loading it in the image will break it because of no migration support from Association to Variable. It's better to use the image from CI for review.  
(locally I have a migration script)

**Comment by dionisiydk** [comment]
tests show issues. I will fix them later

**Comment by MarcusDenker** [comment]
Failing tests not related.

**Review by MarcusDenker — APPROVED** [review]
This looks good! Very nice.

**Comment by dionisiydk** [comment]
Cool. Now lets cleanup other methods. I checked Yesterday that almost all metalink methods are duplicated.

**Pull request merged**
