### PR TITLE
Fix #12459 : text selection drag and drop problem.

### LINKED ISSUE #12459: Bug when commentary text zone in the Class Browser is drag'n drop with selection
This bug is easy to reproduce with the mouse (not trackpad), you need to do some drag'n drops with selection (by double clic for example), move the mouse inside the selected text and try to have the bug. This bug is very and it's come a lot of time during my programmation sessions :/ 

I think I have a fix, I send a PR soon.

# 1 Go into a commentary zone
image

# 2 Selection with double click
image

# 3 Drag and drop inside the selected text with the mouse cursor
image

My configuration : 
- Windows 11 Pro
- Pharo-11.0.0+build.483

### PR DESCRIPTION
**Pull request by labordep**
I propose this fix for #12459.
It is hard to reproduce with a test (complexe mouse events) but with this fix I haven't the bug.
Thanks.

### CODE REVIEW

**Comment by Ducasse** [comment]
Thanks Pierre!!!

**Review by guillep — CHANGES_REQUESTED** [review]
Thanks Pierre! I tested this on my side and it makes the bug go away.
I'd like if you can add some comments on why the arithmetic?

If you want to write a test, I suggest to take a look at `RubSelectionTest`

imagen

**Comment by labordep** [comment]
Hi,
Ok good news !
I will write unit test and comment and send a new PR soon :)

**Comment by labordep** [comment]
I have rewrite some code into the RubTextEditor with unit tests. The unit tests represent the search behavior that I suppose. The selection behavior on double click is not perfect but I think this is working better. Check my tests to have a reflexion about the targeted behavior.

**Comment by Ducasse** [comment]
I do not get why suddenly we get many dispersed broken tests

**Comment by labordep** [comment]
@Ducasse I have to do something ?

**Comment by MarcusDenker** [comment]
The PR seems to lead to these tests failing:

CompletionEngineTest
- testReplaceTokenWithCaretInTheMiddleOfWordReplacesEntireWord
- testReplaceTokenWithCaretOnEndOfWordReplacesEntireWord

ProperMethodCategorizationTest
- testSetUpMethodInSUnitTestsNeedsToBeInRunningProtocol
	
ProtocolConventionsTest
- testProperTestProtocolIsUsed

**Comment by labordep** [comment]
Thanks @MarcusDenker, I will check theses tests

**Comment by labordep** [comment]
I have fixed a bad index computation in the completion engine and all theses tests are ok for me : 

- CompletionEngineTest 
- ProperMethodCategorizationTest
- ProtocolConventionsTest
- RubTextEditorTest

I'm waiting for global test checking

**Comment by labordep** [comment]
@MarcusDenker @Ducasse  I don't know this system of auto verification, it appears very powerful. Apparently there is an error, how can I see where is the problem ?

**Comment by labordep** [comment]
image

**Comment by MarcusDenker** [comment]
the CI checks on 3 platforms, but the windows test runner seems to be out of disk space, so it stopped.

else it looks good.

I will open an issue for the windows test runner and put this PR on the "ready to review" status

**Comment by guillep** [comment]
I've manualy fixed the merge conflict. I'll integrate after we check it runs and I did not break anything :)

**Pull request merged**
