### PR TITLE
8669 aFloat asScaledDecimal loses precision

### PR DESCRIPTION
**Pull request by pablo-s**
In class Float, the method asScaledDecimal was overriden to set a custom scale (14) for floats.

The reasons for this number are:
1) IEEE 754 double precision numbers use 53 bits to encode mantissa. This means that the maximum amount of decimal digits that can be represented is log10(2^53) = 15,xx.
2) At least one of the decimal digits has to be placed to the left of the decimal point.

Therefore, if we round down the max amount of digits and we remove the digit that will not be to the right of the decimal point, we obtain a scale of 14.

### CODE REVIEW

**Comment by pablo-s** [comment]
Updated the description of this PR with more details.

**Comment by Ducasse** [comment]
Thanks for your contribution.

**Comment by guillep** [comment]
Hi @pablo-s this is great! It could be nice to add some tests and commentd in the PR. For example, documenting why you chose 15, and why it is enough, would be nice. Otherwise this is just a magic number and its rationalite is lost...

**Comment by pablo-s** [comment]
Thanks to all of you for your comments!

@guillep I have updated the scale value and I also included the reasoning. You can find it in: the first comment of this PR, and also in the method Float >> asScaledDecimal, where the "magic number" is used. I also included some tests.

Please, let me know if anything else is needed.

**Review by guillep — APPROVED** [review]
Good!

**Pull request merged**
