### PR TITLE
Cleanup condense refactoring packages - SECOND ATTEMPT

### LINKED ISSUE #12577: Cleanup: Condense Refactoring packages
```Smalltalk
cms := CompiledMethod allInstances select: [:each |
each package ifNil: [ false ] ifNotNil: [:p |
	p name beginsWith: 'Refactoring' ] ].
 
cms do: [:cm |
    ((RBRefactoryChangeFactory instance)
         addMethodSource: (ReMethodSourceCleaner clean: cm sourceCode) in: cm origin) execute ]
```

### PR DESCRIPTION
**Pull request by astares**
Fix #12577 with green tests

### CODE REVIEW

**Comment by astares** [comment]
image

**Comment by MarcusDenker** [comment]
failing test:

ReSmalllintTest>>testMultiplePeriodsTerminatingStatement

**Comment by astares** [comment]
@MarcusDenker Fixed now:

image

**Comment by astares** [comment]
Green on Unix, CI problems on the other

**Comment by MarcusDenker** [comment]
- [CI] test runs sometimes aborted due to SubscriptOutOfBounds error #12502
- [CI] Random failing: TKTNewProcessTaskRunnerTest>>#testNewProcessTaskRunnerRunsInNewProcessEveryTime #12221

**Pull request merged**
