### PR TITLE
extract return from ifTrue:ifFalse: expression

### LINKED ISSUE #12176: extract return from max: and min: methods
_extract return from max: and min: methods._

**Actual**
```
max: aMagnitude 
 self > aMagnitude
   ifTrue: [^self]
   ifFalse: [^aMagnitude]
```

**Expected**
```
max: aMagnitude 
 ^ self > aMagnitude
     ifTrue: [self]
     ifFalse: [aMagnitude]
```

**Version information:**
 - OS: [debian]
 - Version: [bullseye]
 - Pharo Version [Pharo-11.0.0+build.394.sha.25a66bd9b1ac0bf7b1dac4e147bbc0292f426f9e (64 Bit)]

### PR DESCRIPTION
**Pull request by vonbecmann**
fix: #12176

### CODE REVIEW

**Review by astares — APPROVED** [review]

**Comment by Ducasse** [comment]
Strange all builds are failing. Not related I imagine.

**Review by MarcusDenker — APPROVED** [review]

**Comment by MarcusDenker** [comment]
BlockClosureTest>>testTallyInstructions starts failing as the number of bytecodes executed changes due to this refactoring

**Comment by vonbecmann** [comment]
i have no idea how to change that test. it depends on the compilation context.

**Comment by vonbecmann** [comment]
i run the test with different settings but there is no difference in the actual value.
Pharo>>Settings>>Compiler 
Clean Block Closure [x] : the actual value is 27. expected 25.
Clean Block Closure [ ] : the actual value is 27. expected 26.

it may need a new test.

**Comment by MarcusDenker** [comment]
Yes, your change changes the bytecode that the test executes to test the bytecode interpreter.

This means that the test has to be updated (the number is checks for has to be changed)

As for Clean Blocks, just ignore that for now: the whole code path of the test has to be recompiled with clean blocks enabled to see a difference, we can do that later.

**Pull request merged**
