### PR TITLE
Rename test classes

### PR DESCRIPTION
**Pull request by jgfoster**
This doesn't affect my work, but it seems like it is inconsistent.

### CODE REVIEW

**Review by astares — APPROVED** [review]
OK, thanks!

**Review by gcotelli — APPROVED** [review]

**Comment by jecisc** [comment]
I have the impression there is something weird with this PR because the files were not renamed. I have the impression they should have been renamed.

**Comment by jgfoster** [comment]
Yes, renaming the files makes sense. I'll submit something on this soon.

**Comment by jecisc** [comment]
@jgfoster Are you working with a file editor or Pharo itself?
If you are working with a file editor, is there a reason to not work in Pharo? (I ask to know if there is something we might improve in Pharo to reduce barrier to entrance)

**Comment by jgfoster** [comment]
@jecisc Thanks for fixing the file names. And, yes, I'm using a file editor. I admit that I'm not doing things the conventional way, but I've run into issues trying to edit code in Pharo. Using PharoLauncher, when I try to launch the image in the checkout directory, nothing happens; also when I double-click on the image nothing happens. When I use Bootstrap to build images, and launch with PharoLauncher, then I can see and run code but attempting to commit gives an error (#4088). So I've just been editing files then re-running Bootstrap.

**Comment by jecisc** [comment]
If you wish, maybe we can sit together at esug if you are comming this year and check your troubles?

**Comment by jgfoster** [comment]
Yes, that might be helpful. I plan to be there for Sunday's Camp Smalltalk. Thanks!

**Comment by jecisc** [comment]
I plan to be there Sunday afternoon

**Pull request merged**
