### PR TITLE
2321-The-dark-age-is-coming

### LINKED ISSUE #2321: The dark age is coming
As a result of switching of themes with every release, we should change the default theme to the dark one again

### PR DESCRIPTION
**Pull request by pavel-krivanek**
Switch to the dark theme. 
Fixes #2321

### CODE REVIEW

**Comment by astares** [comment]
Ohhh - no - not again a dark age... 

So only Pharo 9 will be bright again. ;)

**Comment by Ducasse** [comment]
I would like to have the blueish one esteban is using.

**Comment by astares** [comment]
@Ducasse Blueish one? Any pointers or code to load?

**Comment by pavel-krivanek** [comment]
https://github.com/estebanlm/themes

**Comment by astares** [comment]
Thanks for the pointer

**Comment by estebanlm** [comment]
I think my dark metal theme (that I love) is too much for regular usage :)

**Pull request merged**
