### PR TITLE
Add-some-icons-to-commands

### PR DESCRIPTION
**Pull request by Lin777**
To improve menu

### CODE REVIEW

**Comment by Ducasse** [comment]
Is this Pr depending on the previous one?

**Comment by jecisc** [comment]
I think it is a subset of the previous one.
Evelyn started to split the previous one in more readable PRs

**Review by dionisiydk — APPROVED** [review]
@Lin777 Thanks for this extra work.

**Comment by dionisiydk** [comment]
> Is this Pr depending on the previous one?

It does not depends on anything and can be merged

**Pull request merged**
