### PR TITLE
22239-DataAndTimeTesttestAsDateAndTime-is-meaningful-2

### PR DESCRIPTION
**Pull request by svenvc**
https://pharo.manuscript.com/f/cases/22239/DataAndTimeTest-testAsDateAndTime-is-meaningful

fixed the test by moving the entries without TZ offset indication in a separate group and handling them differently.

by using the local offset, the test should become resilient to TZ/DST changes.

remove 2002-05-16T17:20:45.0000000001+01:01 as sub nanosecond precision is not supported.

### CODE REVIEW

**Review by akgrant43 — APPROVED** [review]
The #zipped #unzipped stuff appears unrelated to the subject, but...

It all looks good (including #zipped & #unzipped).

CI failure appears to be unrelated.

**Comment by svenvc** [comment]
argh yes that is from another branch/PR

**Comment by pavel-krivanek** [comment]
Sven, could you clean the PR from the unrelated changes?

**Comment by svenvc** [comment]
Hi Pavel, I think I managed to clean the PR ...

**Review by akgrant43 — APPROVED** [review]
Looks clean to me...

**Pull request merged**
