### PR TITLE
Fix completion benchmark examples and recover inspector extension

### PR DESCRIPTION
**Pull request by guillep**
The completion benchmark extensions were lost in Pharo 10.
Recover them and do a pass on the comments.

### CODE REVIEW

**Comment by Ducasse** [comment]
Broken tests are not related.

**Comment by MarcusDenker** [comment]
The PR leads to #testNoUncategorizedMethods  failing. 

I added an issue tracker entry: https://github.com/pharo-project/pharo/issues/17128

(the test will now fail for all PRs until it is fixed)

**Comment by Ducasse** [comment]
Again this super stupid logic that we generate as yet unclassified. 
What a bad idea. Now it was not fun to be forced to recover code in Pharo 90 because we removed "dead code" that was not dead and "lost" the inspector extensions. 
This is always like that we migrate but we do not care about things that we do not use
and then we lose really nice things. Here it was the tool to evaluate completion configurations.

**Comment by hernanmd** [comment]
> Again this super stupid logic that we generate as yet unclassified. What a bad idea. Now it was not fun to be forced to recover code in Pharo 90 because we removed "dead code" that was not dead and "lost" the inspector extensions. This is always like that we migrate but we do not care about things that we do not use and then we lose really nice things. Here it was the tool to evaluate completion configurations.

What I find amazing is that the CI "fails" because of a missing protocol assignment. To me, it sounds pedantic and I think CI should fail for important failures, not because of uncategorized methods.

I pushed a fix 2 weeks ago https://github.com/hpi-swa/smalltalkCI/pull/660 (not yet integrated) for which I had to make archeological editions (Pharo 90) in visual-studio code. Not fun at all

**Pull request merged**
