### PR TITLE
20387 Categorize methods in QACritiqueTest, QuestionDialogWindow, QuestionWithoutCancelDialogWindow

### PR DESCRIPTION
**Pull request by astares**
https://pharo.fogbugz.com/f/cases/20387/Categorize-methods-in-QACritiqueTest-QuestionDialogWindow-QuestionWithoutCancelDialogWindow

Categorize methods in QACritiqueTest, QuestionDialogWindow, QuestionWithoutCancelDialogWindow

### CODE REVIEW

**Comment by astares** [comment]
Timeout on CI

**Review by MarcusDenker — APPROVED** [review]
looks good, just recategorisation. When tests green -> Good to integrate

**Comment by MarcusDenker** [comment]
I restarted the test run

**Comment by MarcusDenker** [comment]
Failing test not related to the changes done

**Pull request merged**
