### PR TITLE
[cleanup] changed "message"  by "method" in the template method

### PR DESCRIPTION
**Pull request by hogoww**
This might be controversial, but i'm going for it !

messageSelectorAndArgumentNames
   "comment stating purpose of instance-side message"
(...)

In the current template we say we define a message, whereas as far as I understand, we're defining a method.

I therefore replaced it with
methodSelectorAndArgumentNames
   "comment stating purpose of instance-side method"

Let me know if you think this is right or not =)

### CODE REVIEW

**Review by pavel-krivanek — APPROVED** [review]
The name "method" makes sense to me here

**Comment by Ducasse** [comment]
I agree with pavel we are editing a method :)

**Comment by Ducasse** [comment]
So I will close it :) but thanks Pierre.

**Comment by hogoww** [comment]
wat.
We all agree then, don't we?
Currently in the image, the messages is using "message"
I changed it to have "method"
No..?

**Comment by MarcusDenker** [comment]
Yes, it should be merged, not closed?

**Pull request merged**
