### PR TITLE
Fix #10929 Graphic UI selection glitch with selected text on large screens

### LINKED ISSUE #10929: Graphic UI selection glitch with selected text on large screens
Hi,
I have a large screen (5120x1440) and I display the Pharo Window on all the available surface.
This is great but I have a funny bug :D when I select a text (from a source-code, or anything) the selection rectangle render is not visible.

See some screenshots after.

My Pharo desktop : 
image

And the selection bug in differents cases :
DirtySelection

On this gif we can see that there is "an invisible line", at the left off it the render is visible and at the right the render is cutted. May be this is the same problem for the vertical axe.

This is a problem when my selection is completely at the left of this line, I don't see the selection :S 
InvisibleSelection

This invisible line appear to be at 4095 pixels of the beginning of my screen (with a measure app), is the render clipped outside 4096 pixels ?

My config : 
Pharo 10.0.0
Build information: Pharo-10.0.0+build.399.sha.c4426366e83c26b8a002ef0680abe3a89a0b1a99 (64 Bit)
On Windows 10 Pro 64bits.

### PR DESCRIPTION
**Pull request by labordep**
All my explanation is on the ticket :)

### CODE REVIEW

**Comment by labordep** [comment]
I wanted to submit a fix from another branch from my pharo repo clone but it doesn't seem to work. 
There are commits from another branch (main) while the ones from this patch are just the last two commits.
Do know how to do ? How to have multiple PR propositions ?

**Comment by jecisc** [comment]
One thing you could do is to create a new branch from Pharo11 branch and cherry pick the commits with your fix, then open a new PR from this branch.

GitKraken is a nice tool to do this easily. In this tool you can create the new branch and right click on the commits you want to harvest and select « cherry pick »

**Comment by labordep** [comment]
Thanks @jecisc, I don't know this tool :). 
This is not possible to do that with GitHub ?

**Comment by jecisc** [comment]
From the website, I don’t think so.

Maybe from GitHub desktop but I don’t know since I never used it :)

**Comment by jecisc** [comment]
https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/cherry-picking-a-commit

<blockquote><div> GitHub Docs</div><div><strong><a href="https://ghdocs-prod.azurewebsites.net/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/cherry-picking-a-commit">Cherry-picking a commit - GitHub Docs</a></strong></div><div>You can pick a specific commit on one branch and copy the commit to another branch.</div></blockquote>

**Comment by jecisc** [comment]
This can also be done directly in Git bash

**Comment by labordep** [comment]
Thanks, before to use that I will check if I have done correctly my branch :)

**Comment by labordep** [comment]
Ok I succeed to do that with github, the way is :
- create a new branch from the original repo (not from my fork, I think my error was here)
image
- publish code on it

Thanks @jecisc ;) I will us your tool may be next time !

**Pull request closed without merging**
