### PR TITLE
Rename-Protocol-methods-into-methodSelectors

### PR DESCRIPTION
**Pull request by jecisc**
The API of Protocol is, currently, misleading. A protocol has a method #methods but this one does not return methods but selectors. 

In this PR I updated the API to #methodSelectors to be explicit.

### CODE REVIEW

**Review by dionisiydk — APPROVED** [review]

**Review by MarcusDenker — APPROVED** [review]

**Comment by MarcusDenker** [comment]
but bootstrap is failing, needs some more transformations as part of the PR

**Comment by jecisc** [comment]
@MarcusDenker I'm on it.

**Comment by jecisc** [comment]
@MarcusDenker Fixed.

**Comment by jecisc** [comment]
Running the tests I see some deprecations. I'll fixe them also.

**Comment by jecisc** [comment]
Test failure unrelated.

**Pull request merged**
