### PR TITLE
2146-Hardcode-class-rewriter-and-searcher-in-RB-class

### LINKED ISSUE #2146: RB classes should not hardcode class rewriter and searcher....
We should reduce the number of references to `RBParseTreeRewriter` and `RBParseTreeSearcher`

### PR DESCRIPTION
**Pull request by LaurineDargaud**
fix: #2146
From 62 to 23 references to RBParseTreeRewriter

### CODE REVIEW

**Comment by pavel-krivanek** [comment]
test failures seem to be related

**Comment by Ducasse** [comment]
LaurineDargaud can you check a bit the tests that are broken.

**Comment by Ducasse** [comment]
LaurineDargaud can you check a bit the tests that are broken.

**Comment by Ducasse** [comment]
getSearcher is an ugly name the one before was much better. 
Can you use the previous one? parseTreeSearcher
get is not idiomatic of Pharo. It feels super strange.


In addition what you can do 
introduce a method called 
```
parseTreeRewriterClass
  ^ RBParseTreeRewriter 
```
and 
``` 
parseTreeRewriter
    ^ self parseTreeRewriterClass new
```

and use them in the hieararchy.

**Comment by LaurineDargaud** [comment]
Alright, I'll open another PR with good names at top-level in classes hierarchy
I close this one

**Pull request closed without merging**
