### PR TITLE
A disable checked checkbox can be rendering a checked checkbox.

### PR DESCRIPTION
**Pull request by 570gina**
solve #3021

### CODE REVIEW

**Comment by 570gina** [comment]
t

**Comment by 570gina** [comment]
efrgthnybrvb
ntbybyn

**Comment by MarcusDenker** [comment]
"Note: I am not a very intelligent bot, I can only react to new comments. Please add a comment for me if you update the body or title."

**Comment by MarcusDenker** [comment]
Only a new comment will get the bot to remove the flag.

**Comment by 570gina** [comment]
The checkbox can show checked state when disabled:)

**Comment by Ducasse** [comment]
Hi gina

did you add a test? Because it would be great. 
We can do that in another issue. 

Stef

**Pull request merged**
