### PR TITLE
Enable CDClassParser in class definition in Calypso

### PR DESCRIPTION
**Pull request by dionisiydk**
Enable SourceCodeContext in class definition editor based on class parser node.

It brings following features to the class definition in the browser:
- source code menu (cmd+t) for selected variables and class names
- shortcuts for selected variables and class names (cmd+r for rename)

### CODE REVIEW

**Comment by dionisiydk** [comment]
the error seems unrelated

**Review by MarcusDenker — APPROVED** [review]

**Comment by Ducasse** [comment]
We are getting there and this is cool :)

**Comment by jecisc** [comment]
I got an error that seems to be linked today:

```
RBLiteralValueNode(Object)>>doesNotUnderstand: #selector
CDClassDefinitionParser>>parseSlotNode:
[ :slotStatement | self parseSlotNode: slotStatement ] in CDClassDefinitionParser>>parseSlotsNodesFromArrayNode: in Block: [ :slotStatement | self parseSlotNode: slotStateme...etc...
OrderedCollection>>do:
CDClassDefinitionParser>>parseSlotsNodesFromArrayNode:
CDClassDefinitionParser>>parseSelectorPart:withArgument:
[ :selectorPart :argument | self parseSelectorPart: selectorPart withArgument: argument ] in CDClassDefinitionParser>>visitMessageNode: in Block: [ :selectorPart :argument | self parseSelectorPart...etc...
Array(SequenceableCollection)>>with:do:
CDClassDefinitionParser>>visitMessageNode:
RBMessageNode>>acceptVisitor:
CDClassDefinitionParser>>parseRootNode:
CDClassDefinitionParser>>parse:
CDClassDefinitionParser class>>parse:
ClyClassDefinitionEditorToolMorph>>parseClassDefinition
ClyClassDefinitionEditorToolMorph>>selectedSourceNode
ClyClassDefinitionEditorToolMorph>>createTextContext
ClyClassDefinitionEditorToolMorph(ClyTextEditorToolMorph)>>createCommandContext
CmdKMDispatcher>>dispatch:
KMTarget>>dispatch:
[ :targetToDispatch | 
targetToDispatch dispatch: KMBuffer uniqueInstance buffer copy.
aKeyboardEvent wasHandled ifTrue: [ ^ self ] ] in KMDispatchChain>>dispatch: in Block: [ :targetToDispatch | ...
KMDispatchChain>>do:
KMDispatchChain>>dispatch:
CmdKMDispatcher(KMDispatcher)>>dispatchKeystroke:
RubEditingArea(Morph)>>dispatchKeystrokeForEvent:
RubEditingArea(RubAbstractTextArea)>>handleKeystroke:
KeyboardEvent>>sentTo:
RubEditingArea(Morph)>>handleEvent:
RubEditingArea(Morph)>>handleFocusEvent:
[ ActiveHand := self.
ActiveEvent := anEvent.
result := focusHolder handleFocusEvent: (anEvent transformedBy: (focusHolder transformedFrom: self)) ] in HandMorph>>sendFocusEvent:to:clear: in Block: [ ActiveHand := self....
BlockClosure>>on:do:
```

I was browsing methods so probably on a senders or implementors command.

**Comment by jecisc** [comment]
I found how I got it. It's when I try to delete an instance variable from the definition of a class. (slot template enabled)

**Comment by jecisc** [comment]
It works without the slot template.

**Comment by astares** [comment]
I got a #halt in CDClassDefinitionParser parseSlotNode: when I use a

Object 
	subclass: #FooBar
	slots: { MySlot initWith: 42. }
	classVariableNames: { }
	package: 'Example-Test'

as notation and not provide the slot notation with an    x =>...

**Comment by MarcusDenker** [comment]
the parseSlot method is missing this:

aRBMessageNode isLiteralNode ifTrue: [ | slot |
		slot := CDSlotNode
			node: aRBMessageNode
			name: aRBMessageNode value
			typeName: aRBMessageNode value
			start: aRBMessageNode start
			stop: aRBMessageNode stop.
		classDefinition addSlot: slot.
		^ self
	].

**Comment by Ducasse** [comment]
Thanks. 
Do not forget to add tests. When we started I guess that slots were still in flux.

**Pull request merged**
