### PR TITLE
Pharo10: 6191 find between substrings freezes the image

### PR DESCRIPTION
**Pull request by marcor**
As proposed here:

https://github.com/pharo-project/pharo/issues/6191#issuecomment-1247919755

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Lots of SystemDependency tests are failing, e.g.

```
SystemDependenciesTest>>testExternalBasicToolsDependencies


Error
key 'Fuel-Platform-Pharo-9' not found in Dictionary
```

This seems to be related to this PR, as the same happens in the version for Pharo11

**Comment by marcor** [comment]
Let me try something Marcus. I attached a v10.0.0-PR tag to the last commit, this should trick Jenkins into using the right image. [If I read this right.](https://github.com/pharo-project/pharo/blob/d9f862003a88bfc9a17ff12ab7a11abf1fe154a9/bootstrap/scripts/envversion.sh#L72)

Otherwise I'll prepare a fresh pull request and abandon this.

**Comment by marcor** [comment]
> Lots of SystemDependency tests are failing, e.g.
> 
> ```
> SystemDependenciesTest>>testExternalBasicToolsDependencies

I don't know why but this PR page links to test results for the Pharo11 PR, [here is the correct link](https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-11770/2/pipeline/).

**Comment by MarcusDenker** [comment]
failing tests not related 

- [CI] failing ReleaseTest: testMethodsContainNoHalt, testNoUncategorizedMethods #11805

**Comment by MarcusDenker** [comment]
re-check after merging https://github.com/pharo-project/pharo/pull/11785

**Comment by MarcusDenker** [comment]
This looks good:

- PR is build with the pharo10 name
- the image is indeed a pharo10 image
- with the known failing tests of Pharo10

**Review by MarcusDenker — APPROVED** [review]
As this is a forward port from Pharo9, it is ready to be merged

**Comment by MarcusDenker** [comment]
We merged the Pharo11 version of this fix (see https://github.com/pharo-project/pharo/pull/11771 ) 

If we do not get any problems on Pharo11, we should merge this in some days

**Comment by MarcusDenker** [comment]
The same PR is in Pharo11 for some days with no problem, so we can merge this

**Pull request merged**
