### PR TITLE
21402-Removing-Transcript-Core-from-the-Bootstraped-Image

### PR DESCRIPTION
**Pull request by tesonep**
Issue https://pharo.fogbugz.com/f/cases/21402/Removing-Transcript-Core-from-the-Bootstraped-Image

### CODE REVIEW

**Comment by astares** [comment]
Should'nt even in a minimal image be some support for output - which usually means to keep Transcript - but only as a facade and give its output to console or elsewhere?

So for instance if I have a minimal image but load an external package with 

   Transcript show: 'something to say'

messages in it it will still work and 
 - either output to nothing in the most minimal variant
 - or output to console for console images
 - or output to server log for web application images
 - or output to Transcript window for UI images

**Comment by tesonep** [comment]
Hi @astares the bootstraped image uses NonInteractiveTranscript, the ThreadSafeTranscript is only used with the UI. 
The same happens when using a command line tool.

**Comment by tesonep** [comment]
The next step is to change the package name to something more representative

**Comment by pavel-krivanek** [comment]
looks fine, restarting validation

**Review by pavel-krivanek — APPROVED** [review]

**Pull request merged**
