### PR TITLE
TaskIt: TKTRunner and TKTAbstractExecutor should be abstract

### LINKED ISSUE #8738: TaskIt: TKTRunner and TKTAbstractExecutor should be abstract
TKTRunner and TKTAbstractExecutor are not referenced. They are providing abstract
behavior and should implement #isAbstract to return true

### PR DESCRIPTION
**Pull request by astares**
Fix #8738

### CODE REVIEW

**Comment by noha** [comment]
As long as we just copy projects into pharo we should take care either doing pull request on the original source or doing it in both. Otherwise it is very likely these changes get reverted on next copy. Repository is at https://github.com/pharo-contributions/taskit


<blockquote><div> GitHub</div><div><strong><a href="https://github.com/pharo-contributions/taskit">pharo-contributions/taskit</a></strong></div><div>TaskIt is a library that ease Process usage in Pharo. It provides abstractions to execute and synchronize concurrent tasks, and several pre-built mechanisms that are useful for many application dev...</div></blockquote>

**Comment by MarcusDenker** [comment]
I do not think that this "I by chance know that the package has a repo but you can not know when fixing things in Pharo" will ever scale. It already now does not work.

**Comment by noha** [comment]
Nobody is satisfied with the situation. But as long as we rely on metacello there is no escape. So we just need to minimize potential for regressions

**Comment by astares** [comment]
@noha Yes - an unfortunate situation. Still one can not see what is managed internal and what external.

Ideally an external project aligns back with changes in Pharo to go more freely for the contributions. For instance Sven is now pulling back changes for Zinc and Zodiac.

**Pull request merged**
