### PR TITLE
2531-Removing-global-action-Introduce-DisplayableObject-

### PR DESCRIPTION
**Pull request by Ducasse**
Introducing DisplayableObject as a first step in the battle against the super super ugly: Smalltalk ui evil.
#2531
https://github.com/pharo-project/pharo/issues/2531

### CODE REVIEW

**Comment by Ducasse** [comment]
Broken tests are unrelated

**Comment by astares** [comment]
DisplayableObject is an unusual name.

I would suggest to name it "DisplayObject" as you will find in most other frameworks. (VisualSmalltalk, Adobe, ...)

**Comment by Ducasse** [comment]
well displayObject is not that nice. 
We will fix the name later. For now we need to clean all the mess around theme.

**Comment by astares** [comment]
"Nice" is subjective. An objectively look would reveal:

DisplayObject is more common (405000 Google hits)
DisplayableObject is less common (12300 Google hits)

However ... you seem to flog your own pull requests into the image ignoring any comments.

It would be really preferable if you would behave like a regular contributor where PR's 
are always merged by another person than the one who contributed.

**Pull request merged**
