### PR TITLE
4401-ZipArchive-should-not-convert-FileReference-to-paths

### LINKED ISSUE #4401: ZipArchive should not convert FileReference to paths
Indeed, it prevents to use a memory store (e.g. for test purposes)

### PR DESCRIPTION
**Pull request by demarey**
Always use a file reference as input for the read stream.
Fixes #4401

### CODE REVIEW

**Comment by Ducasse** [comment]
I will merge it now what do you think about adding a readFromStream: method?

**Comment by demarey** [comment]
For better understanding, it is easier to review commit one by one. They all have a very limited scope.

**Comment by Ducasse** [comment]
Do I understand correctly that we do not need a 
xxxFromFileNamed: to support backward compatible interface since the argument of that method was not path name but already a file?

**Comment by demarey** [comment]
xxxFromFileNamed: methods had a lot of duplicated code. They can be easily replaced by a call to xxxFrom: methods taking a stream as argument.
I put deprecations: https://github.com/pharo-project/pharo/pull/4402/files#diff-d3f332fd7c43641c2205b3e3efdc5717R1 so that users can switch.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo/pull/4402">4401-ZipArchive-should-not-convert-FileReference-to-paths by demarey · Pull Request #4402 · pharo-project/pharo</a></strong></div><div>Always use a file reference as input for the read stream.
Fixes #4401</div></blockquote>

**Comment by VincentBlondeau** [comment]
This PR has been integrated despite it was known to break the CI: 

> ..RETRY->BaselineOfTonel
> [32] ...RETRY->BaselineOfTonelMessageNotUnderstood: ByteString>>binaryReadStream
> [32] ByteString(Object)>>doesNotUnderstand: #binaryReadStream
> [32] ZipArchive>>readFrom:
> [32] MetacelloPharo30Platform(MetacelloPharoPlatform)>>extractRepositoryFrom:to:
> 
> [32] MCGitHubRepository class(MCGitBasedNetworkRepository class)>>projectDirectoryFrom:version:
> [32] MCGitHubRepository(MCGitBasedNetworkRepository)>>calculateRepositoryDirectory
> [32] MCGitHubRepository(MCGitBasedNetworkRepository)>>resolveLocalRespository
> [32] MCGitHubRepository(MCGitBasedNetworkRepository)>>ensureLocalRepository
> [32] MCGitHubRepository(MCGitBasedNetworkRepository)>>localRepository
> [32] MCGitHubRepository(MCGitBasedNetworkRepository)>>goferReferences

And so now, the CI is broken... I suggest to revert it for now...

**Comment by demarey** [comment]
The fix is there: https://github.com/demarey/pharo/commit/fb70a730f1e2e0e9e7e253398404202b553bf1cd
Indeed, the PR was integrated just before this commit.

**Comment by Ducasse** [comment]
Ok I got probably confused because normally I systematically check builds. 
Tx

**Pull request merged**
