### PR TITLE
Fix #8844 Avoid hardcoded #doTerminationFromYourself as a criteria

### LINKED ISSUE #8844: Avoid hardcoded #doTerminationFromYourself as a criteria for the isTerminated method
As as complementary proposal to PR #8567 I'd like to suggest a way to avoid hardcoding #doTerminationFromYourself and a particular position of the pc pointer to the termination criteria in the upcoming PR. It involves adding a "trap" method, let's call it Process>>#endProcess, and forwarding every processes being terminated to it. #endProcess would suspend the receiver and use a new <isTerminated> pragma to indicate the termination status of the receiver.

The idea has been also presented in #8567 (https://github.com/pharo-project/pharo/pull/8567#issuecomment-802321883).

In case of accidental resuming a terminated process the #endProcess method would just suspend it again eliminating the 'cannot return' errors that would otherwise be raised.

### PR DESCRIPTION
**Pull request by isCzech**
Fixes #8844

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Somehow it looks as if the tests time out on all platforms

**Comment by isCzech** [comment]
> Somehow it looks as if the tests time out on all platforms

Thanks, it looks like some debugger tests don't like the feature preventing 'cannot return' errors (i.e. simply suspending accidentally resumed terminated processes, without raising an error). So I just commented the feature out (leaving the other code intact) to make it available for future consideration. Sorry for missing this :)

**Comment by dionisiydk** [comment]
Hi @isCzech .

Sorry that I was not clear. But I expected that you will push your changes on top of mine.

Now it will cause a conflict with my PR (#8567 ). And considering the size of my changes I would be very happy to avoid remerging. It will require another pass on testing and rethinking of what I get. 
Not sure that I will have the time for this soon. But the PR fixes very critical problems. it is better to integrate it first and then do other improvements. 

So please wait the integration of #8567

**Comment by isCzech** [comment]
> Hi @isCzech .
> 
> Sorry that I was not clear. But I expected that you will push your changes on top of mine.
> 
> So please wait the integration of #8567

Hi @dionisiydk ,
sure! I hope the proposed changes will still be compatible :)

**Comment by Ducasse** [comment]
Hi denis

I heard today Pablo telling that he had a look and like it but wants guille to have a look too so that they can make sure that it is ok. 

S.

**Comment by isCzech** [comment]
Hi All,
I've opened an issue #8992 (Unwind mechanism during termination is broken - skips multiple unwind blocks and corrupts the image) which addresses a related but more important problem. Adjusting #isTerminated suggested here is of a way lower priority.

**Comment by estebanlm** [comment]
same as with  #8993, we want this, but is very dangerous so I am deferring.

**Comment by Ducasse** [comment]
Yes this is good to relabel it.

**Comment by guillep** [comment]
Hi all, it's been really difficult to review the batch of issues (#8567 , #8845, #9137, #8993, #8509).
We have spent in the last internal sprints several hours taking a look at them, but it is a reality that those changes are difficult to review, some like #8567 are very big, their effects in the system are difficult to foresee independently and even worse in combination.

@tesonep is correctly (!!) proposing to my ear that we make a single PR joining all of them to reduce the merge noise, let the CI test the combination of all issues. I then propose that we eagerly merge this (meta) PR and be ready to quickly apply hot-fixes as soon as possible or revert it in case of fire.

Thoughts? @dionisiydk @Ducasse @isCzech @estebanlm

**Comment by estebanlm** [comment]
Ok for me :)

**Comment by guillep** [comment]
Superseeded by https://github.com/pharo-project/pharo/pull/10429

**Comment by Ducasse** [comment]
Agreed because after they become baby monsters that grow up and that we cannot handle.

**Pull request closed without merging**
