### PR TITLE
HandMorph cleanups required: remove three ivars

### LINKED ISSUE #2564: HandMorph cleanups required
HandMorph allUnreferencedInstanceVariables 

returns "#(#keyboardListeners #eventSource #lastSystemEvent)"

Do we still need them?

### PR DESCRIPTION
**Pull request by MarcusDenker**
remove unreferenced keyboardListeners eventSource lastSystemEvent

fixes #2564

### CODE REVIEW

**Comment by MarcusDenker** [comment]
before merging, resulting mac artefact should be manually tested (see issue tracker entry)

**Comment by Ducasse** [comment]
BTW you will have to explain to me why if one slave fails and the other pass we should not integrate because I do not get then the rationale of running on three in parallel.
I did not get the UI showing the results.

**Comment by MarcusDenker** [comment]
I tested the mac image: works!

**Comment by MarcusDenker** [comment]
For slave: if a slave is *down* (that is, the CI setup can not start a virtual slave for that platform), then the *whole* CI process does not work. For example, the merge will not trigger a new build.

And I am not sure if the CI, when it waits for a build, shows the failing tests of the other builds correctly (e.g, last week a change was merged in that situation that broke lots of tests).

My rule is: if the CI setup is broken, I stop to merge.

**Comment by MarcusDenker** [comment]
But this means: "the CI setup is broken", not "one test run fails on one slave". These are two different things.

**Comment by MarcusDenker** [comment]
e.g. if the virtual disk is full on a slave (happens sometimes) it just fails. No problem to merge a if the change is not related to specially that platform in this case.

**Comment by Ducasse** [comment]
Ok you will show me how I can see that the slave is down. Because I confused it with a Vm crashed and one execution did not happen.

**Comment by jecisc** [comment]
I just tried and the image did not crash. 

The weird thing is that my startup preferences only loaded half of the stuff and this without error... I don't know if it comes from this fix or from a missing information in the bootstraped image.

**Comment by MarcusDenker** [comment]
I suggest we try and merge...

**Comment by jecisc** [comment]
The current Pharo 8 works fine for me for now.

**Pull request merged**
