### PR TITLE
Packages: Remove #definedSelectors cache

### PR DESCRIPTION
**Pull request by jecisc**
#definedSelectors cache is a dictionary of the classes defined in a package and the method selectors defined in those classes. 

This is used because to know the defined selectors of a class you need to reject the methods from traits and the extension methods and #isExtension was way too slow. 

Recently I did a huge speed up of #isExtension so we are now able to remove this cache and simplify the code! I also did a speed if of #includesClass: 

This PR just deal with the removal of the cache but we will be able to also remove more mecanism after this change. I'm just trying to do it step by step to not break the system. This will also avoid any synchronization missmatch between RPackage and Classes

### CODE REVIEW

**Comment by jecisc** [comment]
There must be something not consistant somewhere because the dependencies tests are failing. :/

Is this due to a missmatch between RPackage defined selectors and what we actually have in the image? I need to investigate

**Comment by jecisc** [comment]
Of course, those tests are working locally.. So maybe it's some tests that are messing things?

**Comment by jecisc** [comment]
So, I finally can reproduce. This happens when we run the tests of CoverageCollectorTest before the SystemDependencies tests. I need to find what is happening there

**Comment by jecisc** [comment]
This is CoverageCollectorTest>>#testExample that is messing things up

**Comment by jecisc** [comment]
So, the test is removing the #extensionPackage property of all method of Point and Rectangle so I guess something with reflectivity does not preserve the properties of methods

**Comment by jecisc** [comment]
This one is now ready for a review

**Comment by jecisc** [comment]
Marking as priority high because it blocks multiple other cleanings

**Comment by Ducasse** [comment]
Cyril there are failing tests (23 new ones related to traits-v2).
So I will not integrate it for now.

**Review by MarcusDenker — APPROVED** [review]

**Comment by Ducasse** [comment]
@MarcusDenker did you see that there were failing tests?

**Comment by jecisc** [comment]
They were known random failures I am starting to investigate

**Pull request merged**
