### PR TITLE
transform_32_into_64.sh: call envvars.sh

### PR DESCRIPTION
**Pull request by akgrant43**
envvars.sh is required to set up environment variables such as
BOOTSTRAP_REPOSITORY.

### CODE REVIEW

**Comment by pavel-krivanek** [comment]
causes the same CI failure

**Comment by akgrant43** [comment]
Slightly different, I think.  Before it was BOOTSTRAP_REPOSITORY that was missing, now it's BOOTSTRAP_ARCH.

I'll try and track down why it isn't still defined (it obviously was earlier in the pipeline).

**Comment by akgrant43** [comment]
I think this now solves the issue.  There are 4 existing test failures, however I don't think they're related (the tests wouldn't even get to run if there was a problem with this PR).

**Comment by demarey** [comment]
I will merge this PR because builds are failing mainly due to `BOOTSTRAP_REPOSITORY: unbound variable`. This PR looks ok.
@akgrant thanks for the fix. By the way, what does mean +x in `${BUILD_NUMBER+x}`? I do not know this notation

**Comment by demarey** [comment]
@estebanlm you were faster than me ;)

**Comment by akgrant43** [comment]
@demary - re "+x", take a look at https://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash.  It basically changes the check from "is empty" to "is set".  The two are typically regarded as the same, but are really different.  Most scripts don't care about the difference, but "set -o nounset" in the transform script causes an "is empty" test to fail if the variable isn't set.

**Pull request merged**
