### PR TITLE
merge spec2 0.3

### PR DESCRIPTION
**Pull request by estebanlm**
Main changes: 

- Application added #topWindow to know which windows is currently active.
- Transmission mechanism modified to not work on arrays but direct methods. 
- Layouts are now fully dynamic: You can add/remove presenters in runtime and you can change completely a layout in runtime.
- SpListPresenter: Added and experimental generator-based model.
- SpNotebookPresenter: Pages can now be closeable.
- Toolbar: Added Toggle buttons.
- Some work on documentation.
- Deprecated methods has been moved to Spec2-Deprecated packages and is not loaded anymore.
- Old layout is no longer needed, and it has been moved to a deprecated package and not loaded anymore either

### CODE REVIEW

**Comment by Ducasse** [comment]
Looks like the build did not run.

**Comment by Ducasse** [comment]
I rekicked it.

**Comment by tesonep** [comment]
There is a loading order error: 

```
Error: This package depends on the following classes:

  CustomHelp

You must resolve these dependencies before you will be able to load these definitions: 

  SpExamples

  SpExamples>>#bookName

  SpExamples>>#firstExample

  SpExamples>>#moreExamples

  SpExamples>>#pages

  SpExamples>>#secondExample

  SpHelpTopics

  SpHelpTopics>>#bookName

  SpHelpTopics>>#introduction

  SpHelpTopics>>#key

  SpHelpTopics>>#pages

  SpHelpTopics>>#terminology

  SpLayouts

  SpLayouts>>#bookName

  SpLayouts>>#columns

  SpLayouts>>#columnsAndRows

  SpLayouts>>#intro

  SpLayouts>>#pages

  SpLayouts>>#rows

  SpTheHeartOfSpec

  SpTheHeartOfSpec>>#bookName

  SpTheHeartOfSpec>>#connectPresenters

  SpTheHeartOfSpec>>#initializePresenters

  SpTheHeartOfSpec>>#intro

  SpTheHeartOfSpec>>#layouts

  SpTheHeartOfSpec>>#pages

  SpTheHeartOfSpec>>#widgetInstantiation

```

**Comment by estebanlm** [comment]
test error unrelated. 
Ready to integrate :)

**Review by tesonep — APPROVED** [review]

**Pull request merged**
