### PR TITLE
Add switch fullscreen option to welcome screen

### LINKED ISSUE #6109: Add switch fullscreen option to welcome screen
The welcome screen includes a quick setup to preconfigure Pharo (like light or dark theme).

We should add the fullscreen option too so one can easily switch to the full Pharo experience with a single click:

Screenshot from 2020-04-02 00-33-10

### PR DESCRIPTION
**Pull request by astares**
Fix #6109

### CODE REVIEW

**Comment by Ducasse** [comment]
We should pay attention because the full screen mode crash on some macs.

**Comment by Ducasse** [comment]
So I would prefer to have the option when we get the new VM and SDL support.

**Comment by astares** [comment]
I guess you are talking about https://github.com/pharo-project/pharo/issues/3151
which is closed. Have not heard about new cases or trouble recently.

**Comment by astares** [comment]
Anyone able to restart CI?

**Comment by astares** [comment]
ping

**Comment by tesonep** [comment]
pong :)
Restarted the CI.

**Comment by astares** [comment]
ping :)

Windows64.Hiedra.Tests.Model.HiExamplesTest failed unrelated ...

**Review by tesonep — APPROVED** [review]

**Comment by seandenigris** [comment]
@astares re fullscreen crashing, there is #4412, which is still open and verified in non-headless VMs

**Comment by astares** [comment]
@seandenigris:  known VM Bug: https://github.com/OpenSmalltalk/opensmalltalk-vm/issues/380 for Mac

**Pull request merged**
