### PR TITLE
22058-TabMorph-should-handle-wheel-click-and-close-itself-like-in-most-software-as-web-browsers

### PR DESCRIPTION
**Pull request by jecisc**
Close tabs on wheel click

https://pharo.fogbugz.com/f/cases/22058/TabMorph-should-handle-wheel-click-and-close-itself-like-in-most-software-as-web-browsers

### CODE REVIEW

**Comment by jecisc** [comment]
Error not related.

**Comment by jecisc** [comment]
Can we relaunch?

**Comment by estebanlm** [comment]
no check if tab is closable?

**Comment by jecisc** [comment]
@estebanlm It is handled by #close. See https://github.com/pharo-project/pharo/pull/1482/files#diff-a650b48f69328953fb8672a148f478afR452

**Review by pavel-krivanek — APPROVED** [review]
ok. We do not check modifiers (ctrl etc) but Chrome is not doing it as well ;-)

**Pull request merged**
