### PR TITLE
Cleanup: Condense Kernel packages

### LINKED ISSUE #12378: Cleanup: Condense Kernel packages
```Smalltalk
cms := CompiledMethod allInstances select: [:each |
each package ifNil: [ false ] ifNotNil: [:p |
	p name beginsWith: 'Kernel' ] ].
 

cms do: [:cm |
    ((RBRefactoryChangeFactory instance)
         addMethodSource: (ReMethodSourceCleaner clean: cm sourceCode) in: cm origin) execute ]
```

### PR DESCRIPTION
**Pull request by astares**
Fix #12378

### CODE REVIEW

**Comment by astares** [comment]
image

**Comment by MarcusDenker** [comment]
Note: CI did not run ("1 succesful check", it should be 2) => this means the CI has problems again and is down

**Comment by astares** [comment]
@MarcusDenker Yes, I already noticed that sometimes they become green right away without running. 

BTW: I always do the PR clean from a latest fresh image so that we do not have any conflicts.

**Comment by astares** [comment]
We close this in in favour of https://github.com/pharo-project/pharo/pull/12392
(got a conflict now due to other merges, so I redid with a fresh PR)

**Pull request closed without merging**
