### PR TITLE
[Opinion required] Add this context tester on the AST

### PR DESCRIPTION
**Pull request by hogoww**
I don't know whether that make sense or not.
I assume if it did, it would have been put in already.
But since I'm working on this topic, I wanted to offer it, for API consistency.

What do you all think about it? :)
(redo of previous PR, several commit got mixed in it)

### CODE REVIEW

**Comment by StevenCostiou** [comment]
Hi, do you have an example of use?
I imagine it could be used by tools that look over the AST...?

**Comment by hogoww** [comment]
I don't.
When I need to treat thisContextNodes, it's usually with other stuff, and I therefore use a visitor.

**Review by guillep — APPROVED** [review]
I think consistency is good.
And cheap.

**Comment by guillep** [comment]
Thanks @hogoww and @StevenCostiou for the review!

**Pull request merged**
