### PR TITLE
Fix #21602. Choose line ending convention in ZnCrPortableWriteStream.

### PR DESCRIPTION
**Pull request by guillep**
A ZnCrPortableWriteStream can be configured with the desired line ending convention using the methods 

converter forCr.
converter forLf.
converter forCrLf.
converter forPlatformLineEnding.

### CODE REVIEW

**Comment by jecisc** [comment]
I am wondering if the name of the class is right. Because IIUC it can us CR, LF and CRLF. Then why is there only "CR" in the name?

**Comment by jecisc** [comment]
Maybe @svenvc can be interested also.

**Comment by svenvc** [comment]
OK for the changes
Probably better to rename it, but not now, it is a critical class in the system

**Comment by svenvc** [comment]
No, #forPlatformLineEnding should do: OSPlatform current lineEnding

**Comment by jecisc** [comment]
Maybe on two Pharo versions. Renaming it in one version but keep this one as a subclasses to deprecate, and in the next Pharo version removing it?

**Comment by guillep** [comment]
I've patched #forPlatformLineEnding.

@jecisc this class was not part of any official Pharo release yet, just a temporary Pharo7 class...

**Comment by svenvc** [comment]
OK, good

**Comment by guillep** [comment]
I've added a new commit with the rename. Let's wait at least until the build runs to see if everything is ok.

@svenvc We would need to push a new version on Zinc afterwards.

**Comment by dionisiydk** [comment]
And we have another related issue https://pharo.fogbugz.com/f/cases/21618/Saving-code-is-broken.

**Comment by dionisiydk** [comment]
So let's integrate to sooner to fix another problem

**Review by dionisiydk — APPROVED** [review]
let's integrate

**Pull request merged**
