### PR TITLE
2922-the-class-builder-talks-about-sharedVariables-while-every-else-they-are-called-Class-Variables

### LINKED ISSUE #2922: the class builder talks about sharedVariables, while every else they are called Class Variables
this is very confusing. 

--> rename the ivar and accessor to classVariable

### PR DESCRIPTION
**Pull request by MarcusDenker**
fixes #2922

### CODE REVIEW

**Comment by Ducasse** [comment]
So that we get fresher feedabck

**Review by guillep — CHANGES_REQUESTED** [review]
This change impacts the bootstrap. The bootstrap uses the class builder to create classes, and during bootstrap interpretation automatic deprecations are not handled by the AST interpreter.
Maybe @carolahp can help @MarcusDenker with this? It should not be difficult to fix.

Also @carolahp, this is a clear example of bootstrap bug :)

**Comment by Ducasse** [comment]
I review it and it looks ok now we should check the bootstrap expert

**Comment by MarcusDenker** [comment]
I will let run the tests again, because it might have been using exactly the broken image of last weekend.

**Comment by guillep** [comment]
Hi, this PR requires changes in the bootstrap (I am not guessing, I checked the logs and I know the process). Closing and Reopening will not solve it automatically.

**Pull request closed without merging**
