### PR TITLE
Make Old events work as new ones in SDL2

### LINKED ISSUE #8171: Pharo latest on Mac: input broken
I tried to type "dvmason" in a playground and this is what I got:
Screen Shot 2020-12-24 at 8 45 49 AM

This was on the official version (64bit) as of this moment (refreshed PharoLauncher)... also Pharo Development version build 997 exhibits exact same behaviour.
MacOS Mojave 10.14.6
(borked is another word for fubar or afu or snafu or f****d)

### LINKED ISSUE #8300: Cannot type a pipe | character on an azerty keyboard
**Describe the bug**
Typing a pipe | character on an azerty keyboard (Alt-Gr + 6) in any text editor brings up a "choose color..." dialog (screenshot below) instead of typing |. Typing a | on a qwerty keyboard works normally.

image

First exploration:
The "choose color..." dialog is created by `RubTextEditor>>#changeEmphasis:`, when it is called by `RubTextEditor>>#performCmdActionsWith: aKeyboardEvent shifted: aBoolean return: return`.
image

The most recent changes to the RubTextEditor class are commits 0cadbda9173e00b65f0d5bb65afc12b20781846e ("restore Rubric events") and fdb02f7c29f7089f9b38fcdca4ab5d02b44be0aa ("Fix shortcuts in Rubric"), both from pull request #8156 by @guillep. Maybe that's what introduced this bug.

By the way, I don't know what this color dialog is supposed to do. Picking a color does not have an effect...

**Version information:**
 - OS: Windows 10

### LINKED ISSUE #8309: Pressing SHIFT scroll the focus to the carret in the code editor
**Describe the bug**

In the screenshot, the code is scrolling when I press the "SHIFT" key.
1PYN6Wiftm

**To Reproduce**
1. Go to a code browser with a long method
2. place the carret at the top
3. Scroll down to the bottom
4. Press shift with the focus in the window

**Expected behavior**
Click, press shift ,  click again, the text is selected between the 2 clicks:
fkMU9PcVRB

**Screenshots**
See above

**Version information:**
Pharo9.0.0
build: 1026, commit: 93d6505

**Expected development cost**
"everything is relative"

**Additional context**
I think it appears not so long ago...

### LINKED ISSUE #8317: Pipe character not possible to write an a German keyboard
**Describe the bug**
With the recent Pharo 9, there is not possible to write the pipe character (`|') on the German keyboard anymore. It is probably introduced by https://github.com/pharo-project/pharo/pull/8156 by @guillep .

To write the pipe character on the German keyboard with ISO layout, you need to pres right Alt (Alt Gr) together with a key next to the left shift: 
https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/KB_Germany.svg/825px-KB_Germany.svg.png

This event is then put in the queue by the OSWindow as [keyDown '<Ctrl-Cmd-<>'] 

Pharo_RFEMYSineM
 
And it leads to this DNU:

```
KeyboardKey(Object)>>doesNotUnderstand: #asInteger
String class>>with:
RubSmalltalkEditor(RubTextEditor)>>encloseWith:
RubSmalltalkEditor(RubTextEditor)>>performCmdActionsWith:shifted:return:
RubSmalltalkEditor(RubTextEditor)>>dispatchCommandOn:return:
RubSmalltalkEditor(RubTextEditor)>>dispatch:
RubSmalltalkEditor(RubTextEditor)>>keyDown:
[super keyDown: aKeyboardEvent ] in RubSmalltalkEditor>>keyDown: in Block: [super keyDown: aKeyboardEvent ]
RubSmalltalkEditor>>completionAround:keyDown:
RubSmalltalkEditor>>keyDown:
[ self editor keyDown: anEvent ] in RubEditingArea(RubAbstractTextArea)>>keyDown: in Block: [ self editor keyDown: anEvent ]
RubEditingArea(RubAbstractTextArea)>>handleEdit:
RubEditingArea(RubAbstractTextArea)>>keyDown:
RubEditingArea(Morph)>>handleKeyDown:
KeyboardEvent>>sentTo:
RubEditingArea(Morph)>>handleEvent:
RubEditingArea(Morph)>>handleFocusEvent:
[
		result := focusHolder handleFocusEvent: 
			(anEvent transformedBy: (focusHolder transformedFrom: self)).
	] in HandMorph>>sendFocusEvent:to:clear: in Block: [...
FullBlockClosure(BlockClosure)>>on:do:
WorldMorph>>becomeActiveDuring:
HandMorph>>sendFocusEvent:to:clear:
HandMorph>>sendEvent:focus:clear:
HandMorph>>sendKeyboardEvent:
HandMorph>>handleEvent:
[
		(morphicWorld activeHand isNotNil and: [ anEvent hand isNotNil ]) ifTrue: [
			morphicWorld activeHand handleEvent: anEvent
		]
	] in OSWindowMorphicEventHandler>>dispatchMorphicEvent: in Block: [...
WorldState>>runStepMethodsIn:
WorldMorph>>runStepMethods
WorldState>>doOneCycleFor:
WorldMorph>>doOneCycleNow
WorldMorph>>doOneCycle
```

Moreover, the `enclose:` method (already fixed in this stack trace by `encloseWith:`) was deprecated
https://github.com/pharo-project/pharo/pull/8316

### PR DESCRIPTION
**Pull request by guillep**
Latest cleanups in SDL2 broke input events in old VMs.
This PR brings it to the level of SDL2.
 - shortcuts are defined in terms of keys instead of characters
 - the keymapping shortcut framework has been revisited to transform characters to keys
 - mappings between keys and characters have been introduced to make it more backwards compatibility
 - Morphic events correctly receive now keydown and keyup for shortcut like events, and keystroke manage text

In my machine it fixes (tested many keyboard layouts):
Fix #8300
Fix #8317
Fix #8171
Fix #8309

### CODE REVIEW

**Comment by Ducasse** [comment]
This is cool.

**Comment by Ducasse** [comment]
@guillep you have 59 tests failing.

**Comment by guillep** [comment]
> @guillep you have 59 tests failing.

Yes I'm still working on it :)

**Comment by Ducasse** [comment]
Oki. I wanted to integrate :) so this is why i checked. :)

**Comment by Ducasse** [comment]
All tests are green (except Zn) so this is good

**Pull request merged**
