### PR TITLE
Add Toplo world menu entry (part 2)

### LINKED ISSUE #16289: Adding option to load Bloc / Toplo as there is for Roassal
We need to add the menu entry to load the stable version of Bloc and Toplo

### PR DESCRIPTION
**Pull request by tinchodias**
Add missing PharoCommonTools>>menuToploOn:
This complements https://github.com/pharo-project/pharo/pull/16429
To actually fix https://github.com/pharo-project/pharo/issues/16289

### CODE REVIEW

**Review by jecisc — COMMENTED** [review]
This causes some breaking system depedency tests.

Maybe they should be updated to already include the baseline of pharo in the list of packages to accept?

**Comment by estebanlm** [comment]
so... ?

**Comment by estebanlm** [comment]
hi @tinchodias  I will let this on Pharo12 (it will be in Pharo 12.0.1 or so...) but you will need to do a new PR to Pharo13 too (no, I cannot just merge P12 in P13 anymore).

**Comment by tinchodias** [comment]
@estebanlm okay, I still don't know why the PR broke things

**Comment by tinchodias** [comment]
@estebanlm @jecisc do you know what can I do to debug this? 
I wanted to see fresh CI output but closing/reopening the PR didn't trigger the CI again...

**Comment by Rinzwind** [comment]
Jenkins not starting a new build could be due to reopening too fast, causing it to not see the pull request as closed when it processes the ‘pull request closed’ event. You can look at the [‘Multibranch Pipeline Events’](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/indexing/events) log to see whether it has processed the event. I posted a [comment about this in pull request #16172](https://github.com/pharo-project/pharo/pull/16172#issuecomment-2052539481) with an example from the log.

For debugging, you could download ‘Pharo12.0-PR-64bit-aad814b.zip’ from the [‘bootstap-cache’ directory in the artifacts of build 3](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16478/3/artifact/build/bootstrap-cache/), it contains the image produced by the [‘Full Image-64’ stage](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16478/3/pipeline-console/?selected-node=25).

**Comment by estebanlm** [comment]
yeah, the problem is this menu introduces a dependency from Tool-Registry to BaselineOfPharo.

**Comment by estebanlm** [comment]
So I made a workaround to get this sorted (not a good solution, but it will be "good enough" until we find a better way of handling this (IMO, we need a special tool for loading previews, but this is clearly out of the scope).

**Pull request merged**
