### PR TITLE
21772-Redefinition-of-superclass-can-change-subclasses-definitions-

### PR DESCRIPTION
**Pull request by pavel-krivanek**
https://pharo.fogbugz.com/f/cases/21772/Redefinition-of-superclass-can-change-subclasses-definitions

fill the class builder only with the local slots

### CODE REVIEW

**Review by tesonep — APPROVED** [review]
Looks good, let's see the test results.

**Comment by tesonep** [comment]
I will add a test for this scenario

**Comment by pavel-krivanek** [comment]
thanks!

**Comment by MarcusDenker** [comment]
Now there is a conflict

**Pull request merged**
