### PR TITLE
21479 Better structure in UnifiedFFI-Tests and add class comments

### PR DESCRIPTION
**Pull request by astares**
https://pharo.fogbugz.com/f/cases/21479/Better-structure-in-UnifiedFFI-Tests-and-add-class-comments

### CODE REVIEW

**Review by dionisiydk — APPROVED** [review]
Ok

**Comment by astares** [comment]
Thanks!

**Comment by jecisc** [comment]
Is it in sync with UFFI repo?

**Comment by astares** [comment]
Why? This is not needed to my knowledge as UFFI is managed within git in Pharo directly now.

http://smalltalkhub.com/#!/~Pharo/FFI-NB is obsolete for P7 then but stay for older versions.

**Comment by jecisc** [comment]
I though it was still maintained outside as fuel or epicea.

**Pull request merged**
