### PR TITLE
3214-Spec-synchronization

### LINKED ISSUE #3214: Spec synchronization
I'll do a PR today with a Spec 2 synchronization.

### PR DESCRIPTION
**Pull request by jecisc**
Spec synch.

I'll try to do a quick changelog in a future comment.

Fixes #3214

### CODE REVIEW

**Comment by jecisc** [comment]
Fast changelog:

- Lot of new tests
- Improve testing capabilities of Spec
- Begin to Split ComposablePresenter between ComposablePresenter and Presenter
- Introduce the concept of an "Application"
- Deprecate widgets that will be removed later from Spec (TreeColumnPresenter, TreePresenter, FastTablePresenter, MultiColumnListPresenter, TabManagerPresenter, TabPresenter)
- Unify API: #when*: and #when*Do: to always use the second
- Begin to remove window logic from ComposablePresenter to put it in the window presenter. The user can now customize it via #initializeWindow: or #initializeDialog:
- New demos
- Improve the Notebook presenter (Possibility to add/remove pages and select tabs)
- Make menues independent of Morphic. Now they should return a MenuPresenter instead of filling a MenuMorph.
- Migrate TextFieldPresenter to RubTextFieldMorph in the Morphic backend
- Begin to split TextPresenter and CodePresenter (WIP)
- Improvements of the ListPresenter, TablePresenter, TreeTablePresenter...
- The widgets are not built by the SpecInterpreter anymore
- Improvement of the new executables layouts
- Begin to migrate old layouts to the new ones
- Deprecate presenters adding no real value (AbstractTwoButtons, DropListButton, ...)
- Adding transmissions as in Glamour
- Remove unfinished presenters such as the MonticelloBrowserPresenter

**Comment by tesonep** [comment]
Depends on #3215 as it introduces stateful traits for the observable slots.

**Comment by jecisc** [comment]
I forgot to add new packages. I'll do it when I'll have time.

**Comment by Ducasse** [comment]
So cyril should we wait to integrate this PR or we can do the other after?

**Comment by jecisc** [comment]
We should wait. In the current state it will make the bootstrap fail. I'll fix it tomorrow.

**Comment by jecisc** [comment]
Errors are not related.

**Pull request merged**
