### PR TITLE
21573-Remove-unused-variables-from-Behavior-hierarchy

### PR DESCRIPTION
**Pull request by tesonep**
Removing unused variables in Behavior hierarchy

https://pharo.fogbugz.com/f/cases/21573/Remove-unused-variables-from-Behavior-hierarchy

### CODE REVIEW

**Comment by jecisc** [comment]
Apparently there is a problem because I see much more changes that just variable removal.

**Comment by MarcusDenker** [comment]
It is more complex as it needs to improve the bootstrap

**Comment by MarcusDenker** [comment]
Which has been changed in the meantime. I wish we had more people reviewing so that we could merge faster.

**Comment by akgrant43** [comment]
> Which has been changed in the meantime. I wish we had more people reviewing so that we could merge faster.

I'll try and take a look as I've been playing with the bootstrap code, but it may take a couple of days.

**Comment by jecisc** [comment]
Problem is also that not everyone has the knowledge to review core changes. :(

**Comment by akgrant43** [comment]
This is looking good:

- I've successfully bootstrapped a 32 bit image
- Run the image and manually searched for the changes to the Behavior
  class hierarchy
- The following instance variables have been removed:
-- ClassDescription: instanceVariables
-- Class: traitComposition localSelectors

I haven't inspected the code in any meaningful way - it's too spread out
and I'm not familiar with it, but as described above the results look
good.

The bootstrap code has been modified since this branch was created, so
development HEAD will need to be merged in.

**Comment by Ducasse** [comment]
Hi Pablo 

this is super great to see cleans from this side. 
I do not know much this part. 
Now I have one question:

-					scope: (superLayout slotScope extend: #(superclass methodDict format layout instanceVariables organization subclasses name classPool sharedPools environment category traitComposition localSelectors))
 +					scope: (superLayout slotScope extend: #({1}))

Why #(1)

Stef

**Comment by tesonep** [comment]
During the bootstrap the stubs for the classes are created in the method: 

PBImageBuilder50 >> #createInitialObjects

This method used to have the list of instance variables in the class stubs. What I have done is moving the list of instance variables to a configuration object. This object is generated from the source code in the Pharo repository. 

I am just using format on the string to replace the list of instance variables into the Smalltalk code to evaluate to generate the Class stub. That's why I have used {1}, just not to be concatenating strings. Maybe there is a clearer way of doing so.

**Comment by akgrant43** [comment]
- Successfully bootstrapped 32 bit image
- Ran full automated test suite - small number of errors / failures that I think I've seen before
- The unused variables haven't reappeared. :-)

ready to integrate.

**Pull request merged**
