### PR TITLE
Update Spec 0.2.1

### PR DESCRIPTION
**Pull request by estebanlm**
merge Spec 0.2.1

fix dependency problems

### CODE REVIEW

**Comment by estebanlm** [comment]
I fixed the problems coming from Spec2 but now there are: 

1) Spec1 dependency problem (shouldn't we remove Spec1?)
2) testExternalUFFIDependencies
3) testExternalMorphicCoreDependencies 

I do not think this is related to my merge, but certainly those problems should not be there.

Any idea, @tesonep, @MarcusDenker ?

**Comment by Ducasse** [comment]
So esteban I should I merge?

**Comment by estebanlm** [comment]
if you want :)
I can still do a new PR to fix the remaining issues... but I wonder why I'm having them.

**Comment by tesonep** [comment]
This merge was integrated somewhere else....

**Comment by estebanlm** [comment]
who?

**Comment by tesonep** [comment]
I see it in the history, it is your commit but it cannot be said how it got
there. There is no merge, maybe it have been pushed in other pr or
directly, both by error. But we have to think how to avoid it. Although, it
is not easy.

This is already fixed, and also we can always revert commits, so it is not
a real issue.

**Pull request closed without merging**
