### PR TITLE
22179-remove-annotateRubricText-

### PR DESCRIPTION
**Pull request by MarcusDenker**
remove >annotateRubricText:
https://pharo.fogbugz.com/f/cases/22179/remove-annotateRubricText

### CODE REVIEW

**Comment by jecisc** [comment]
Tests failure:

 testCreationTime – Unix32.FileSystem.Tests.Attributes.FileReferenceAttributeTests
 testModificationTime – Unix32.FileSystem.Tests.Attributes.FileReferenceAttributeTests

**Comment by akgrant43** [comment]
Hi Cyril,

How did you determine what the test failures are?  I looked at pipeline.log and couldn't find any reference to FileReferenceAttributeTests or testCreationTime.  (sorry, I'm short of time for the next several days, and I added these tests, so would like to help resolve the issue).

Thanks,
Alistair

**Comment by jecisc** [comment]
Hi Alistair,

See this GIF:

**Comment by akgrant43** [comment]
Hi Cyril,

Neat GIF, thanks!

I can't reproduce the problem (32 or 64 bits on Ubuntu Linux).  I've seen something similar on Windows very occasionally where the time is out by up to 20 seconds.  I guess that somewhere the clock is being cached, resulting in the test failing.

It's really supposed to ensure that timezone and DST are being handled correctly, so adding a 30 second grace period isn't really going to invalidate the test.

I'll put it on my todo list.

Thanks again,
Alistair

**Pull request merged**
