### PR TITLE
21920-includesSubstring-should-be-in-testing-and-not-in-accessing

### PR DESCRIPTION
**Pull request by jecisc**
#includesSubstring: should be in #testing and not #accessing

Case https://pharo.fogbugz.com/f/cases/21920/includesSubstring-should-be-in-testing-and-not-in-accessing

### CODE REVIEW

**Comment by jecisc** [comment]
Really easy to review.

**Review by VincentBlondeau — APPROVED** [review]
Very easy to review indeed :)

**Comment by astares** [comment]
But important nonetheless - step by step it goes!

**Comment by estebanlm** [comment]
*very* important! Good categories makes the system a lot more understandable.

**Pull request merged**
