### PR TITLE
22774-Add-comments-to-SUnit

### PR DESCRIPTION
**Pull request by GDayne**
Commented  methods on TestAsserter Class

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Failing test is unrelated

**Review by astares — COMMENTED** [review]
Not a must but: usually method comment start with a tab and there is an additional empty line after them before the code starts.

Sometimes it is helpful to use the "Format" function in the editor for that.

**Comment by Ducasse** [comment]
I agree with Torsten. Please respect the indentation.

**Comment by bencoman** [comment]
@GDayne, very much appreciate your contribution.  Comments are often overlooked and in reviewing I learnt of a few methods I was unfamiliar with.  You comments read well.  

Sorry we hadn't provided any prominent coding convention so you could have dealt with this up front. But anyway, most PRs are an iterative process.  Just make the changes and commit/push again from the the Image you originally pushed to github from, and the PR will update.

@astares and @Ducasse
A CodingConvention.md page should be prominently linked from the main project README.md.
I've opened... https://pharo.fogbugz.com/f/cases/22820/Document-coding-conventions

**Comment by GDayne** [comment]
Thank you all for the info, I will fix it.

**Review by MarcusDenker — APPROVED** [review]
looks good

**Comment by Ducasse** [comment]
Changes look good. We can integrate them. 
Now dayne pay attention that the pretty printer is not good for stream API

**Pull request merged**
