### PR TITLE
3017-Remove-GLMWrapper

### LINKED ISSUE #3017: Remove GLMWrapper
GLMWrapper has some lint issues and is used only in one place that can be replaced by a text. 

We should remove it.

### PR DESCRIPTION
**Pull request by jecisc**
Remove GLMWrapper.

Fixes #3017

### CODE REVIEW

**Comment by Ducasse** [comment]
Could you remove also testTwiceDeliveredDataSholdBeDetected – MacOSX32.GT.EventRecorder.Tests.Core.GTEventRecorderTest

**Comment by jecisc** [comment]
I did it in another PR

**Comment by Ducasse** [comment]
Cyril what I meant (sorry) was not to remove  testTwiceDeliveredDataSholdBeDetected – MacOSX32.GT.EventRecorder.Tests.Core.GTEventRecorderTest because this looks like a tests of EventRecorder.

**Review by guillep — APPROVED** [review]
Looks ok, maybe dangerous to remove it?

**Pull request merged**
