### PR TITLE
Introduce Collection >> #sum:ifEmpty:

### PR DESCRIPTION
**Pull request by ronsaldo**
Fix issue https://github.com/pharo-project/pharo/issues/6373 by implementing the discussed solution.

### CODE REVIEW

**Comment by olekscode** [comment]
I just did that :)

**Comment by hogoww** [comment]
similar to #6453

**Comment by ronsaldo** [comment]
Sorry about that, I just got a scolding for not taking the card as working
on it...

**Comment by MarcusDenker** [comment]
#6453 has been merged, can this be closed?

**Pull request closed without merging**
