### PR TITLE
Modifying exception name based on feedback from PR

### PR DESCRIPTION
**Pull request by macta**
Renames the exception to VariableNotDeclared

### CODE REVIEW

**Comment by macta** [comment]
@guillep renames the error based on your feedback
fixes #2776

**Comment by MarcusDenker** [comment]
seems to have a boo trap issue:


[32]  0xc99d870 s UndefinedObject>doesNotUnderstand: findUndeclaredVariableIn:
[32]  0xc99d8f8 s UndefinedObject>doesNotUnderstand: findUndeclaredVariableIn:
[32]  0xc99d980 s UndefinedObject>doesNotUnderstand: name:
[32]  0xc99da08 s ByteSymbol(Symbol)>=>
[32]  0xc99da90 s UndefinedObject>DoIt
[32]  0xc99db00 s OpalCompiler>evaluate
[32]  0xc99db60 s OpalCompiler>evaluate:
[32]  0xc99dbe0 s [] in MCClassDefinition>variablesOfType:

**Comment by macta** [comment]
Ok - looking at it to see what happened with the merge

**Comment by macta** [comment]
I think the mistake I have made, is to base my correction on my original branch (which was too far out of date). Do I just close this PR, create a new branch and reference the issue myself? Not sure how best to do this.

**Comment by MarcusDenker** [comment]
yes, close it if you want to redo the PR

**Comment by macta** [comment]
Ok - closing this, and resubmitting with #2893 - its the same change but not from the original pr which was 90 commits behind (and hence merged badly)

**Pull request closed without merging**
