### PR TITLE
11018 SmallInteger isPrime is inefficient

### PR DESCRIPTION
**Pull request by johnhwoods**
Integer>>isPrime 2x speedup using well-known 6k method.

tested with the thousand biggest SmallIntegers and a million random SmallIntegers

### CODE REVIEW

**Comment by Ducasse** [comment]
Thanks!! looks good and all tests are passing.

**Comment by johnhwoods** [comment]
Sorry but, after merge, who closes the issue and when?  :-) j

**Comment by Ducasse** [comment]
We do it manually :)
Now if you put fix: #num github link them and close them automatically.

**Comment by Ducasse** [comment]
You see I did not even see the issue on this page.

**Pull request merged**
