### PR TITLE
Fix forked processes of TestResource from being terminated between TestCase methods being executed

### PR DESCRIPTION
**Pull request by ErikOnBike**
Fixes issue #3582

### CODE REVIEW

**Comment by ErikOnBike** [comment]
@dionisiydk could you please perform a review?

See also [Issue on Pharo forum](http://forum.world.st/TestCases-and-forked-processes-in-TestResource-don-t-play-well-td5100261.html)

**Comment by ErikOnBike** [comment]
Error in CI does not seem related (I think ;-).

**Comment by ErikOnBike** [comment]
There is something wrong with this PR. Some code ended up here that I did not change/touch explicitly. Will update later (today/tomorrow).

**Review by dionisiydk — APPROVED** [review]

**Comment by ErikOnBike** [comment]
Added another PR #3605 for Pharo7.0 branche (with same code/solution)

**Comment by MarcusDenker** [comment]
ci failure not related

**Review by MarcusDenker — APPROVED** [review]
ok

**Pull request merged**
