### PR TITLE
RB* and GR* should be renamed as Re* ... Rule - fixes: #5496

### PR DESCRIPTION
**Pull request by egvillalobos**
| pkgPrefix newClassPrefix env model |
pkgPrefix := 'General'.
newClassPrefix := 'Re'.
env := RBBrowserEnvironment new 
			forPackageNames: (RPackage organizer packageNames select: [ : pkgName | (pkgName beginsWith: pkgPrefix) ]).
model := (RBClassModelFactory rbNamespace onEnvironment: env) name: 'MyModel'; yourself.
RBClassRegexRefactoring new
	model: model;
	renameClasses; 					"Here I just want a rename no copy"
	replace: '^GR(.*)$' with: newClassPrefix,'$1';
  execute.

### CODE REVIEW

**Comment by Ducasse** [comment]
This is strange, Esteban we will have to check because I do not get why this refactoring broke so many tests. There should be one simple mistake.

**Comment by Ducasse** [comment]
Ok we should have a look at the problem.

**Comment by estebanlm** [comment]
please put a real name to the PR, otherwise is hard to keep tracking

**Comment by Ducasse** [comment]
We have this test failing. 
 testRule – Unix32.Renraku.Test.ReCritiqueTest
Can you have a look? Thanks

**Comment by Ducasse** [comment]
We will get there...

**Comment by Ducasse** [comment]
Tests are ok (we should check latter the setting ones). 
Thanks for your support.

**Pull request merged**
