### PR TITLE
Update BaselineOfPharo.class.st with new Roassal Version

### LINKED ISSUE #13991: Synch Roassal
It would be nice to synch Roassal in Pharo 12.

The pull request https://github.com/pharo-project/pharo/pull/13951 has a failing test of roassal that got fixed in the upstream. To be able to merge the PR we would need to integrate a more recent version of Roassal.

### PR DESCRIPTION
**Pull request by akevalion**
This pull request addresses the following issues:
- https://github.com/pharo-project/pharo/issues/13991

### CODE REVIEW

**Comment by jecisc** [comment]
Thank you Milton!

**Comment by MarcusDenker** [comment]
There are undeclared variables:

```
Found undeclared Variables:  RSLayoutNumberField in: RSAbstractBoxedLayout class>>#layoutDefinition RSLayoutDefinition in: RSAbstractBoxedLayout class>>#layoutDefinition RSLayoutPickerField in: RSClusteringLayout class>>#layoutDefinition
```

**Comment by akevalion** [comment]
I will fix it

**Comment by jecisc** [comment]
osx-64 / Tests-osx-64 / testLocalMethodsOfTheClassShouldNotBeRepeatedInItsTraits – MacOSX64.ReleaseTests.Release.ReleaseTest<1s
Error
If a class has a method in its trait composition, the method should not be implemented in the class. Violations:  - RSObjectWithProperty

osx-64 / Tests-osx-64 / testNoPeriodInMethodSignature – MacOSX64.ReleaseTests.Release.ReleaseTest2s
Error
Found methods with period in signature:an OrderedCollection(BaselineOfRoassal3>>#dependencies:)

**Comment by akevalion** [comment]
I have fixed the code but it's failing because RBRefactoringChangeMock

**Pull request merged**
