### PR TITLE
21424-Comment-explaining-StringexpandMacros--co

### PR DESCRIPTION
**Pull request by peteruhnak**
Added comment to String>>expandMacrosWithArguments:

Added more tests for expandMacrosWithArguments:

fixes #21424

### CODE REVIEW

**Comment by peteruhnak** [comment]
Woah... 137 files changed? 😱  This is not what Iceberg told me was changed.

**Comment by peteruhnak** [comment]
I guess Windows line endings... will fix it.

**Comment by pavel-krivanek** [comment]
line endings issue?

**Comment by pavel-krivanek** [comment]
TAAbstractComposition should implement #hash as shouldBeImplemented

**Comment by peteruhnak** [comment]
Ok, fixed.

**Review by tesonep — APPROVED** [review]

**Pull request merged**
