### PR TITLE
22621-FileReferencemoveTo-doesnt-work-with-directories

### PR DESCRIPTION
**Pull request by akgrant43**
22621 FileReference>>moveTo: doesn't work with directories

Fogbugz: https://pharo.fogbugz.com/f/cases/22621/

FileReference>>moveTo: calls FileSystem>>move:to: which states:

"Move the file /directory referenced as sourcePath to the destination referred as destPath."

However it fails if the source is a directory.

- Add the missing functionality
- Update #moveTo: comments to notify the user that the receiver is modified to point to the destination
- Add unit tests for the new functionality
-- Only in the memory file system so the test time isn't increased too much.

### CODE REVIEW

**Comment by akgrant43** [comment]
Test failure appears to be unrelated, but strange.  Try re-open.

**Comment by akgrant43** [comment]
I had hoped that re-opening the PR would restart the CI, but no.

I still think this is OK to integrate, but can someone restart the CI to confirm?

Thanks,
Alistair

**Comment by jecisc** [comment]
Done

**Comment by akgrant43** [comment]
Thanks, @jecisc !

The error still seems strange (and unrelated).  I've merged pharo/development back in to see if that helps.

**Comment by akgrant43** [comment]
Better - all checks passed :-)

**Review by pavel-krivanek — APPROVED** [review]

**Comment by akgrant43** [comment]
Thanks, @MarcusDenker , @pavel-krivanek & @jecisc !

**Pull request merged**
