### PR TITLE
4406-fix-class-def-parser-for-simple-definitions

### LINKED ISSUE #4406: fix class def parser for simple definitions
the parseSlot method is missing this:

aRBMessageNode isLiteralNode ifTrue: [ | slot |
		slot := CDSlotNode
			node: aRBMessageNode
			name: aRBMessageNode value
			typeName: aRBMessageNode value
			start: aRBMessageNode start
			stop: aRBMessageNode stop.
		classDefinition addSlot: slot.
		^ self
	].

And we need to test complex Slots.. (e.g. #var => LazySlot default: 5) but that is another issue

### PR DESCRIPTION
**Pull request by MarcusDenker**
support simplified slot defintions (using #symbol). fixes #4406

### CODE REVIEW

**Review by dionisiydk — APPROVED** [review]
For future improvements:
This method looks like it should go to the message node itself:
```Smalltalk
aRBMessageNode asSlotClassDefinitionNode
```

**Comment by dionisiydk** [comment]
Hey,  we need a test for this case.
It should be easy to add as there are other tests for this parser

**Comment by MarcusDenker** [comment]
I wil add tests later in another PR

**Comment by Ducasse** [comment]
What does it mean "aRBMessageNode isLiteralNode" ?

**Comment by MarcusDenker** [comment]
It is not a message. I just did a quick workaround to unblock people that wanted to work, I did that on the train with bad internet.
More work is needed.

**Pull request merged**
