### PR TITLE
Cleanup newlines and blanks in "ReflectionMirrors" packages

### LINKED ISSUE #10750: Cleanup newlines and blanks in "ReflectionMirrors" packages
see #10396 and fix it for all "ReflectionMirrors" related packages:

```Smalltalk
badCases := SystemNavigation default allMethodsSelect: [ :each | each sourceCode trimRight size ~= each sourceCode size ].

fixInPackage := badCases select: [:each | each package name beginsWith: 'ReflectionMirrors' ].

fixInPackage do: [:each |
	| refactoring classOrTrait |
	classOrTrait := each traitSource ifNil: [ each methodClass ] ifNotNil: [ each traitSource innerClass ].
	refactoring := RBAddMethodChange compile: each sourceCode trimRight in: classOrTrait for: nil.				 
	refactoring execute	
]
```

### PR DESCRIPTION
**Pull request by astares**
Fix #10750

### CODE REVIEW

**Comment by Ducasse** [comment]
Strange all the builds crashed.

**Comment by astares** [comment]
image

**Comment by astares** [comment]
Unrelated:  Spec2 test and Zodiac HTTP failed

**Comment by Ducasse** [comment]
Good that the builds passed.

**Pull request merged**
