### PR TITLE
Remove old Finder references in Baselines

### PR DESCRIPTION
**Pull request by hernanmd**
Continuation of #17420
This PR needs https://github.com/pharo-spec/NewTools/pull/909 to be integrated first

### CODE REVIEW

**Comment by Ducasse** [comment]
Strange it does not build.

**Comment by hernanmd** [comment]
> Strange it does not build.

I'm checking now why the Finder examples are broken

 ✗ #testConcatenationSearch (145ms)
 ✗ #testIndexOfSearch (144ms)
 ✗ #testNegatedSearch (141ms)
 ✗ #testFactorialSearch (137ms)

**Comment by jecisc** [comment]
```
Error: Package NewTools-Finder depends on the following classes:
  MethodFinder
  MethodFinderSend
You must resolve these dependencies before you will be able to load these definitions: 
  StMethodFinder
  StMethodFinder>>#findMethodsByExampleInput:andExpectedResult:timeout:
  StMethodFinder>>#methodFinderSendClass
  StMethodFinderSend
  StMethodFinderSend>>#=
  StMethodFinderSend>>#children
  StMethodFinderSend>>#copyTo:
  StMethodFinderSend>>#debug
  StMethodFinderSend>>#displayIcon
  StMethodFinderSend>>#evaluateWithTimeOut:
  StMethodFinderSend>>#forFinderPreview:
  StMethodFinderSend>>#handleError:
  StMethodFinderSend>>#hasBrowseAction
  StMethodFinderSend>>#hasChildren
  ```

**Comment by hernanmd** [comment]
> ```
> Error: Package NewTools-Finder depends on the following classes:
>   MethodFinder
>   MethodFinderSend
> You must resolve these dependencies before you will be able to load these definitions: 
>   StMethodFinder
>   StMethodFinder>>#findMethodsByExampleInput:andExpectedResult:timeout:
>   StMethodFinder>>#methodFinderSendClass
>   StMethodFinderSend
>   StMethodFinderSend>>#=
>   StMethodFinderSend>>#children
>   StMethodFinderSend>>#copyTo:
>   StMethodFinderSend>>#debug
>   StMethodFinderSend>>#displayIcon
>   StMethodFinderSend>>#evaluateWithTimeOut:
>   StMethodFinderSend>>#forFinderPreview:
>   StMethodFinderSend>>#handleError:
>   StMethodFinderSend>>#hasBrowseAction
>   StMethodFinderSend>>#hasChildren
> ```

This needs https://github.com/pharo-spec/NewTools/pull/909 to be integrated but the CI seems to be hanging now

**Comment by Ducasse** [comment]
It does not build now :( I hope that the previous PR I integrated did not break something but the build was green.

**Comment by Ducasse** [comment]
MetacelloNotification: Loaded -> NewTools-Scopes-Resources-C-Tests --- github://pharo-spec/NewTools:Pharo13/src(29c27a3)
[31mError: Package NewTools-Finder depends on the following classes:
  MethodFinder
  MethodFinderSend
You must resolve these dependencies before you will be able to load these definitions: 
  StMethodFinder
  StMethodFinder>>#findMethodsByExampleInput:andExpectedResult:timeout:
  StMethodFinder>>#methodFinderSendClass
  StMethodFinderSend
  StMethodFinderSend>>#=
  StMethodFinderSend>>#children
  StMethodFinderSend>>#copyTo:
  StMethodFinderSend>>#debug
  StMethodFinderSend>>#displayIcon
  StMethodFinderSend>>#evaluateWithTimeOut:
  StMethodFinderSend>>#forFinderPreview:
  StMethodFinderSend>>#handleError:
  StMethodFinderSend>>#hasBrowseAction
  StMethodFinderSend>>#hasChildren
  StMethodFinderSend>>#hasHierarchyAction
  StMethodFinderSend>>#hasImplementersAction
  StMethodFinderSend>>#hasInheritanceAction
  StMethodFinderSend>>#hasSendersAction
  StMethodFinderSend>>#hasVersionsAction
  StMethodFinderSend>>#hash
  StMethodFinderSend>>#implementersAction
  StMethodFinderSend>>#isClassResult
  StMethodFinderSend>>#isSelectorResult
  StMethodFinderSend>>#logInfo:
  StMethodFinderSend>>#matches:
  StMethodFinderSend>>#previewText
  StMethodFinderSend>>#profile
  StMethodFinderSend>>#resultIn:timeout:
  StMethodFinderSend>>#selectorForFinder
  StMethodFinderSend>>#sendersAction

[0mMCPackageLoader(Object)>>notify:
MCPackageLoader>>warnAboutDependencies
MCPackageLoader>>validate
MCPackageLoader>>load
MCVersionLoader>>basicLoad
[ self basicLoad ] in MCVersionLoader>>loadWithNameLike: in Block: [ self basicLoad ]
[ aBlock value ] in MCVersionLoader>>announceLoad:do: in Block: [ aBlock value ]
FullBlockClosure(BlockClosure)>>ensure:
MCVersionLoader>>announceLoad:do:
MCVersionLoader>>loadWithNameLike:
[
	self ensurePackage: version package.
	self loadWithNameLike: version info name ] in MCVersionLoader>>load in Block: [...
FullBlockClosure(BlockClosure)>>cull:
[ ^ block cull: self ] in [ self prepareForRunning.
	  CurrentJob 
		value: self 
		during: [ ^ block cull: self ] ] in Job>>run in Block: [ ^ block cull: self ]
[ activeProcess
			psValueAt: index
			put: anObject.
		aBlock value ] in CurrentJob(DynamicVariable)>>value:during: in Block: [ activeProcess...
FullBlockClosure(BlockClosure)>>ensure:
CurrentJob(DynamicVariable)>>value:during:
CurrentJob class(DynamicVariable class)>>value:during:
[ self prepareForRunning.
	  CurrentJob 
		value: self 
		during: [ ^ block cull: self ] ] in Job>>run in Block: [ self prepareForRunning....
FullBlockClosure(BlockClosure)>>ensure:
Job>>run
MCVersionLoader>>load
MetacelloMonticelloLoader>>loadAtomicPackageDirectives:
MetacelloMonticelloLoader>>loadPackageDirective:
MetacelloLoadTarget>>visitPackageLoadDirective:
MetacelloPackageLoadDirective>>acceptVisitor:
[ :dir |
		dir acceptVisitor: self ] in MetacelloLoadTarget>>visitLinearLoadDirective: in Block: [ :dir |...

**Comment by hernanmd** [comment]
> MetacelloNotification: Loaded -> NewTools-Scopes-Resources-C-Tests --- github://pharo-spec/NewTools:Pharo13/src(29c27a3) �[31mError: Package NewTools-Finder depends on the following classes: MethodFinder MethodFinderSend You must resolve these dependencies before you will be able to load these definitions: StMethodFinder StMethodFinder>>#findMethodsByExampleInput:andExpectedResult:timeout: StMethodFinder>>#methodFinderSendClass StMethodFinderSend StMethodFinderSend>>#= StMethodFinderSend>>#children StMethodFinderSend>>#copyTo: StMethodFinderSend>>#debug StMethodFinderSend>>#displayIcon StMethodFinderSend>>#evaluateWithTimeOut: StMethodFinderSend>>#forFinderPreview: StMethodFinderSend>>#handleError: StMethodFinderSend>>#hasBrowseAction StMethodFinderSend>>#hasChildren StMethodFinderSend>>#hasHierarchyAction StMethodFinderSend>>#hasImplementersAction StMethodFinderSend>>#hasInheritanceAction StMethodFinderSend>>#hasSendersAction StMethodFinderSend>>#hasVersionsAction StMethodFinderSend>>#hash StMethodFinderSend>>#implementersAction StMethodFinderSend>>#isClassResult StMethodFinderSend>>#isSelectorResult StMethodFinderSend>>#logInfo: StMethodFinderSend>>#matches: StMethodFinderSend>>#previewText StMethodFinderSend>>#profile StMethodFinderSend>>#resultIn:timeout: StMethodFinderSend>>#selectorForFinder StMethodFinderSend>>#sendersAction
> 
> �[0mMCPackageLoader(Object)>>notify: MCPackageLoader>>warnAboutDependencies MCPackageLoader>>validate MCPackageLoader>>load MCVersionLoader>>basicLoad [ self basicLoad ] in MCVersionLoader>>loadWithNameLike: in Block: [ self basicLoad ] [ aBlock value ] in MCVersionLoader>>announceLoad:do: in Block: [ aBlock value ] FullBlockClosure(BlockClosure)>>ensure: MCVersionLoader>>announceLoad:do: MCVersionLoader>>loadWithNameLike: [ self ensurePackage: version package. self loadWithNameLike: version info name ] in MCVersionLoader>>load in Block: [... FullBlockClosure(BlockClosure)>>cull: [ ^ block cull: self ] in [ self prepareForRunning. CurrentJob value: self during: [ ^ block cull: self ] ] in Job>>run in Block: [ ^ block cull: self ] [ activeProcess psValueAt: index put: anObject. aBlock value ] in CurrentJob(DynamicVariable)>>value:during: in Block: [ activeProcess... FullBlockClosure(BlockClosure)>>ensure: CurrentJob(DynamicVariable)>>value:during: CurrentJob class(DynamicVariable class)>>value:during: [ self prepareForRunning. CurrentJob value: self during: [ ^ block cull: self ] ] in Job>>run in Block: [ self prepareForRunning.... FullBlockClosure(BlockClosure)>>ensure: Job>>run MCVersionLoader>>load MetacelloMonticelloLoader>>loadAtomicPackageDirectives: MetacelloMonticelloLoader>>loadPackageDirective: MetacelloLoadTarget>>visitPackageLoadDirective: MetacelloPackageLoadDirective>>acceptVisitor: [ :dir | dir acceptVisitor: self ] in MetacelloLoadTarget>>visitLinearLoadDirective: in Block: [ :dir |...

This is weird because I explicitly defined `Message` as superclass of `StMethodFinderSend` here https://github.com/hernanmd/NewTools/blob/d0828c62dc20d5e328306daeeb27d96c7f684d70/src/NewTools-Finder/StMethodFinderSend.class.st#L10

And `Object` as the superclass of `StMethodFinder` here https://github.com/hernanmd/NewTools/blob/d0828c62dc20d5e328306daeeb27d96c7f684d70/src/NewTools-Finder/StMethodFinder.class.st#L10

So the build is not using the latest NewTools PR I think



<blockquote><div> GitHub</div><div><strong><a href="https://github.com/hernanmd/NewTools/blob/d0828c62dc20d5e328306daeeb27d96c7f684d70/src/NewTools-Finder/StMethodFinderSend.class.st">NewTools/src/NewTools-Finder/StMethodFinderSend.class.st at d0828c62dc20d5e328306daeeb27d96c7f684d70 · hernanmd/NewTools</a></strong></div><div>All development tools for Pharo, developed with Spec - hernanmd/NewTools</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/hernanmd/NewTools/blob/d0828c62dc20d5e328306daeeb27d96c7f684d70/src/NewTools-Finder/StMethodFinder.class.st">NewTools/src/NewTools-Finder/StMethodFinder.class.st at d0828c62dc20d5e328306daeeb27d96c7f684d70 · hernanmd/NewTools</a></strong></div><div>All development tools for Pharo, developed with Spec - hernanmd/NewTools</div></blockquote>

**Pull request merged**
