### PR TITLE
Cleanup OpalCompiler & CompilationContext

### PR DESCRIPTION
**Pull request by privat**
In the OpalCompiler ecosystem, cohesion was very low and coupling very high.
In order to pass around information (and worse, store it is some escaping objects like AST) between the various components, a god-dataclass (two smells in one!) called CompilationContext was used.

After a few weeks of intense cleaning, the cohesion is higher and coupling lower, and some data stored in CompilationContext is now used by only a single class: OpalCompiler. Therefore, the present PR move this data to the class that has the responsibility to use them.

* permitFaulty, permitUndeclared and failBlock. As they are now only used after the parse/semantic analysis to decide to abort the compilation pipeline or to continue.
* logged (boolean flag) used to fire announcement on evaluation or installation

Beside the increase of code quality, this has the advantage of reducing the memory footprint caused by escaping CompilationContext. (maybe it's not that much, it's hard to quantify).

What remain (for the moment) in CompilationContext are:

* All things related to scope and environment, including the badly named `noPattern`
* All things related to code optimization
* All "class methods" i.e. methods that return a class. It's used by reflectivity/metalinks
* Parse and transform plugins. Moving them breaks things. Need to investigate

### CODE REVIEW

**Review by jecisc — APPROVED** [review]
The code seems way nicer

**Comment by Ducasse** [comment]
Sweet! I love that.

**Comment by jecisc** [comment]
The formatter seems impacted by those changes:

```
#> was sent to nil

UndefinedObject(Object)>>doesNotUnderstand: #>

UndefinedObject>>doesNotUnderstand: #>

EFFormatter>>newLines:

[ 

			self newLines: (aMethodNode comments 

									ifEmpty: [ self numberOfNewLinesAfterMethodSignature ] 

			 						ifNotEmpty: [ self numberOfNewLinesAfterMethodSignatureWithMethodComment ]).

			self formatMethodCommentFor: aMethodNode.

			self formatPragmasFor: aMethodNode.

			self visitNode: aMethodNode body ] in EFFormatter>>formatMethodBodyFor: in Block: [ ...

FullBlockClosure(BlockClosure)>>ensure:

EFFormatter>>indent:around:

EFFormatter>>indentAround:

EFFormatter>>formatMethodBodyFor:

EFFormatter>>visitMethodNode:

RBMethodNode>>acceptVisitor:

EFFormatter(RBProgramNodeVisitor)>>visitNode:

[ 

			needsParenthesis

				ifTrue: [ codeStream nextPutAll: self spacesInsideParenthesesString ].

			super visitNode: aNode.

			(self formatCommentCloseToStatements or: [ aNode isMethod or: [ aNode isSequence or: [ aNode isBlock ] ] ])

				ifFalse: [  self spaceAndFormatComments: aNode. ].

			needsParenthesis

				ifTrue: [ codeStream nextPutAll: self spacesInsideParenthesesString ] ] in EFFormatter>>visitNode: in Block: [ ...

EFFormatter>>bracketWith:around:indentExtraSpaces:

EFFormatter>>visitNode:

EFFormatter>>format:

RBMethodNode(RBProgramNode)>>formattedCodeIn:

RBMethodNode(RBProgramNode)>>formattedCode

[aMethod origin compile: aMethod ast formattedCode classified: aMethod protocol] in [

		rewriteRule := self rewriterClass new

			replace: rule key with: rule value.

		(rewriteRule executeTree: node)

			ifFalse: [ ^ self signal ].

		node replaceWith: rewriteRule tree.

		Author

```

**Comment by privat** [comment]
I rebased the PR to let plugins in place. For some reason is breaks FFI on the CI but not on my machine.
So I need to investigate more.

Tests are now ok (beside #13446)

**Review by jecisc — APPROVED** [review]

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
