### PR TITLE
8189-testNoUnusedInstanceVariablesLeft-is-skipped

### PR DESCRIPTION
**Pull request by Ducasse**
fixes: 8189 - well a part of it.

### CODE REVIEW

**Comment by Ducasse** [comment]
Hi pablo/guille

'Errors in script loaded from /builds/workspace/uest_and_branch_Pipeline_PR-8192/64/bootstrap/scripts/bootstrap.st'
MessageNotUnderstood: RGUnknownSlot>>asExportedLiteral
RGUnknownSlot(Object)>>doesNotUnderstand: #asExportedLiteral

I wonder if the fact that I removed unused variables got an impact on the format. 
I could split this PR in smaller one to identify where the problem is.

**Comment by MarcusDenker** [comment]
I think the best is to just redo the PR step by step.. then we will find the problem eventually again

**Comment by astares** [comment]
I guess we should close this PR. I already sent pieces of the puzzle as separate issues and PRs 
(see https://github.com/pharo-project/pharo/issues/8189 to get an overview where I mention all of them depending on current progress)

**Comment by Ducasse** [comment]
To help me I coded 

```
"
 A little class to encapsulate some behavior to clean classes.
 "
 Class {
 	#name : #UnusedVariableRemover,
 	#superclass : #Object,
 	#category : #'ReleaseTests-CleanCode'
 }

  { #category : #analysis }
 UnusedVariableRemover >> classesWithUnusedVariables [
 	"self new classesWithUnusedVariables"

  	^ Smalltalk globals allBehaviors 
 		select: [ :each | each instanceVariables anySatisfy: [ :iv | iv isReferenced not] ]
 ]

  { #category : #analysis }
 UnusedVariableRemover >> unusedVariables [
 	"self new unusedVariables"

  	^ self classesWithUnusedVariables collect: [ :each | each -> (self unusedVariablesOf: each )]
 ]

  { #category : #analysis }
 UnusedVariableRemover >> unusedVariablesOf: aClass [
 	"self new unusedVariablesOf: CDClassDefinitionNode"

  	^ aClass instanceVariables select: [ :iv | iv isReferenced not]
 ]
```

**Comment by Ducasse** [comment]
Notice that for some classes I just added a dummy assignment and it can help you too.

**Pull request closed without merging**
