### PR TITLE
21748 allow s unit to detect when a test did not call assert or similar

### PR DESCRIPTION
**Pull request by juliendelplanque**
Hello,

This pull request is related to the one we did with @apblack some month ago (20755-Tests-that-make-no-assertions-should-fai).

This is a far less agressive implementation as a first step.

1. It does not change anything from a user point of view, test cases that do not call assert: or similar are just gathered by the TestResult silently
2. No change on the UI
3. The feature is only usable if you inspect an expression like this: `ArrayTest suite run assertionless`

A second step would be to correctly integrate this in SUnit UI and make its visibility configurable of course.

### CODE REVIEW

**Comment by pavel-krivanek** [comment]
2635 tests have failed :-)

**Comment by juliendelplanque** [comment]
I'll have a look at them then :-)

**Comment by juliendelplanque** [comment]
This is really strange because in my image, if I run the tests failing on the CI, they works.

How is that possible?

**Comment by juliendelplanque** [comment]
Apparently the exception signaled when no assertion is made is caught by the test engine of the CI? Is it possible?

**Comment by juliendelplanque** [comment]
After a discussion with @pavel-krivanek and @Ducasse, we found a way to implement this in a separated project so modifying SUnit is not mandatory. I close this PR.

**Pull request closed without merging**
