### PR TITLE
Spec2-sync

### PR DESCRIPTION
**Pull request by jecisc**
Spec synch 10/03/2019

Changelog comming soon

### CODE REVIEW

**Comment by jecisc** [comment]
# Changelog - Spec update 10/03/2019

## Bug fixes

* SpStyle crashes if there is a non related class named Font ([592ace4](https://github.com/pharo-spec/Spec/commit/592ace4ae592cf1f77450c74681e964be38059a2))
* Restore focus mecanism and enhance it to have a default focus order in Morphic ([d43669d](https://github.com/pharo-spec/Spec/commit/d43669d9df60cd644f9baf312ad79390d4078c5f))

## Enhancements

* Improve table filters ([ba240c9](https://github.com/pharo-spec/Spec/commit/ba240c9145d653223e34d7f810250a7fb6980a59))
* Improve miller lists ([cc1bda2](https://github.com/pharo-spec/Spec/commit/cc1bda2455e10ad0584031259f3b4b3d8cde88cf))

## New features

* Add menu button presenter ([f2ef2dc](https://github.com/pharo-spec/Spec/commit/f2ef2dc769408a2b90c15a3c7efb9212892330aa))

**Review by gcotelli — APPROVED** [review]

**Comment by gcotelli** [comment]
Sorry, I've misclicked the approve button while reviewing the changes... but cannot find a way to retract the review approval :man_shrugging:

**Comment by jecisc** [comment]
You should have an option « dismiss review » next to the list of checks at the bottom of the Conversation page

**Comment by Ducasse** [comment]
Cyril can you fix the following little glitches?

testTearDownMethodInSUnitTestsNeedsToBeInRunningProtocol – Unix32.ReleaseTests.Categorization.ProperMethodCategorizationTest
<1s
testAndMakeSureSuperSetupIsCalledAsFirstMessageInSetupMethodsOfTestCases – Unix32.ReleaseTests.Tests.ProperlyImplementedSUnitClassesTest
<1s
testNoNilAssignmentInInitializeMethod – Unix32.ReleaseTests.Release.ReleaseTest
<1s
testUndeclared – Unix32.ReleaseTests.Release.ReleaseTest

**Comment by Ducasse** [comment]
Thanks!

**Pull request merged**
