### PR TITLE
Implement ZnNewLineWriterStream >> #flush

### PR DESCRIPTION
**Pull request by cdlm**
…and cleanup its comment and a duplicate method in ZnEncodedStream

### CODE REVIEW

**Comment by svenvc** [comment]
Looks good (without testing)

BTW (and unrelated) but why ZnNewLineWriterStream and not simply ZnNewLineWriteStream (without the R) ?

**Comment by cdlm** [comment]
The inconsistency does irk me, I'm all for a rename… but didn't *you* pick that name ?

While we're at it, ZnCrPortableWriteStream could be removed as well since it's redundant and less flexible.

**Comment by svenvc** [comment]
No, these classes are not mine, the old name is there for backwards compatibility.

These class is critical in the image's startup, let's not rename it for now.

**Comment by MarcusDenker** [comment]
so this is good to merge?

**Pull request merged**
