### PR TITLE
21419-Integrate-Calypso

### PR DESCRIPTION
**Pull request by pavel-krivanek**
https://pharo.fogbugz.com/f/cases/21419/Integrate-Calypso

load Calypso

### CODE REVIEW

**Comment by MarcusDenker** [comment]
:-)

**Comment by tesonep** [comment]
I know I am asking too much, but it will be nice to remove Nautilus also.

**Comment by pavel-krivanek** [comment]
Denis still wants to let Nautilus there as a fallback for some time.

**Comment by jecisc** [comment]
Keeping both for some time can let us see what might be missing for poeple who did not tried Calypso yet.

**Comment by jecisc** [comment]
Also, is there a reason to load Iceberg and Calypso with a Metacello command and not as a common project dependency?

**Comment by pavel-krivanek** [comment]
We were discussing it with Denis. For now, we will let Calypso as semi-external project like Iceberg. It will be moved directly to the Pharo repository but not in the first weeks.

**Comment by tesonep** [comment]
I understand the rationality of both your reasons, but the history is on my
side... Cof cof EyeIspector, Spec Debugger.... Cof cof...

Keeping both seems intelligent, but only stops the people of using Calypso
or improving it, because it is easier to failback to Nautilus. As a result
we will keep Nautilus longer than needed.



On 26 Feb 2018 16:16, "CyrilFerlicot" <notifications@github.com> wrote:

Keeping both for some time can let us see what might be missing for poeple
who did not tried Calypso yet.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pharo-project/pharo/pull/966#issuecomment-368536115>,
or mute the thread

**Comment by dionisiydk** [comment]
We should keep Nautilus for a while. It helps to modify Calypso. Sometimes it leads to broken state during development and Nautilus allows to fix it.
 
But Calypso will be default browser.
And we should create another pull request which will remove Nautilus. So we can track the health of this change.

**Comment by dionisiydk** [comment]
Pavel, can you add "ClyBrowser beAllDefault" ?

**Comment by dionisiydk** [comment]
And another detail. We do not need all groups. So use following script:
```Smalltalk
Metacello new
  baseline: 'Calypso';
  repository: 'github://dionisiydk/Calypso:v0.10.1';
  load: #('FullEnvironment' 'SystemBrowser' 'Tests').
```
(There are some experiments which do not need to be I'm image)

**Review by jecisc — APPROVED** [review]

**Pull request merged**
