### PR TITLE
Fix Abstract instance variables command

### LINKED ISSUE #16362: Abstract instance variables DNU
- On a class with slots
- abstract instance variables and OK

imagen

### PR DESCRIPTION
**Pull request by jecisc**
Fixes #16362

### CODE REVIEW

**Comment by astares** [comment]
@jecisc Stupid question: what is the difference between "Abstract instance variable" and "Generate accessors" menu

Both open a (different) dialog, let you choose ivar's and generate accessor methods (while the  "Generate accessors" had an instance preview of the refactoring). Do I miss something obvious?

**Comment by jecisc** [comment]
> @jecisc Stupid question: what is the difference between "Abstract instance variable" and "Generate accessors" menu
> 
> Both open a (different) dialog, let you choose ivar's and generate accessor methods (while the "Generate accessors" had an instance preview of the refactoring). Do I miss something obvious?

To be honest I don't know. 

I opened an issue saying we should add descriptions to refactorings because I don't know what this one does and there is no description.

**Comment by Ducasse** [comment]
Generate an accessor is not a refactoring
just add the methods if needed.
Abstract variable is doing generate accessor + change all the direct accesses to use the accessors.

**Comment by jecisc** [comment]
Someone did the same change as me during the last sprint and it got integrated so I'll close

**Pull request closed without merging**
