### PR TITLE
Remove some unused methods from StrikeFont, FixedFaceFont, GrafPort and BitBlt

### PR DESCRIPTION
**Pull request by Rinzwind**
This pull request removes some unused methods from StrikeFont, FixedFaceFont, GrafPort and BitBlt.

### CODE REVIEW

**Comment by Ducasse** [comment]
We should pay attention to think also if we should not deprecate some methods.

**Comment by Ducasse** [comment]
This is strange but on linux we got this failure

```
OrderedCollection(Object)>>errorSubscriptBounds:
OrderedCollection>>at:
RubParagraph>>characterBlockForIndex:
RubShoutStylerDecorator(RubParagraphDecorator)>>characterBlockForIndex:
RubEditingState>>markIndex:pointIndex:
```

**Comment by Ducasse** [comment]
Between 
```
Running tests of Metacello-TestsPlatform
 and 
Running test of Epicea-Browser
```

**Comment by jecisc** [comment]
The CI had a strange state so I restarted it

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
