### PR TITLE
Add some timestamps and logs to the bootstrap

### PR DESCRIPTION
**Pull request by jecisc**
To help find bottlenecks or speed regression

### CODE REVIEW

**Comment by privat** [comment]
Nice.

It’s a shame that Jenkins does not already timestamp its log.
An alternative could be to pipe any jenkins script inovcation in `ts` https://manpages.debian.org/bullseye/moreutils/ts.1.en.html

<blockquote><div><strong><a href="https://manpages.debian.org/bullseye/moreutils/ts.1.en.html">ts(1) — moreutils — Debian bullseye — Debian Manpages</a></strong></div></blockquote>

**Comment by jecisc** [comment]
Yes, I also wanted to add those for when we play with the bootstrap locally :)

**Review by privat — APPROVED** [review]

**Comment by MarcusDenker** [comment]
the slow part seems to be just 3-prepare.sh, so we see there just one timestamp:

slow

**Comment by jecisc** [comment]
I've seen that, I plan to iterate. This is just a first tiny step for better bootstrap :)

**Pull request merged**
