### PR TITLE
FIX CI issues - FFIExternalString>>#basicHandle:at: calls deprecated message

### LINKED ISSUE #12404: FIX CI issues - FFIExternalString>>#basicHandle:at: calls deprecated message
We get CI errors in https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-12272/3/pipeline

due to FFIExternalString>>#basicHandle:at: calls deprecated message #fromCString which should now be #bytesFromCString

image

### PR DESCRIPTION
**Pull request by astares**
Fix #12404

### CODE REVIEW

**Comment by astares** [comment]
image

**Comment by astares** [comment]
While image tests are green the CI fails with a many tests, so I think 
https://github.com/pharo-project/pharo/pull/12393 needs to be merged first as this fixes:

image

**Review by MarcusDenker — APPROVED** [review]

**Comment by MarcusDenker** [comment]
Failing tests related to Tests.OSEnvironmentTest, not sure if just for this PR or not

```
osx-64 / Tests-osx-64 / testAsDictionary – MacOSX64.System.OSEnvironments.Tests.OSEnvironmentTest
osx-64 / Tests-osx-64 / testAssociations – MacOSX64.System.OSEnvironments.Tests.OSEnvironmentTest
osx-64 / Tests-osx-64 / testKeys – MacOSX64.System.OSEnvironments.Tests.OSEnvironmentTest
osx-64 / Tests-osx-64 / testValues – MacOSX64.System.OSEnvironments.Tests.OSEnvironmentTest
```

I opened: 

- Failing test on CI: OSEnvironmentTest #12424

**Comment by MarcusDenker** [comment]
With the other PRs not getting this error, it might be a side effect of the change (which is odd as it is just a deprecation transform). 

The errror for all the tests is:

```
"primitive #basicNew: in ByteArray class failed"
```

**Comment by MarcusDenker** [comment]
There was a #utf8Decoded missing

**Comment by MarcusDenker** [comment]
- [CI] Fail on WIN random: OmSessionStoreTest(OmStoreTest)>>testEntryForAbsentEntry #12126

**Pull request merged**
