### PR TITLE
TestRunner removal

### PR DESCRIPTION
**Pull request by hernanmd**
Completely remove TestRunner tool, as discussed in #14540
Adapt menu items and tool registration

### CODE REVIEW

**Comment by jecisc** [comment]
There is an error:

UndeclaredVariableRead: Attempt to read undeclared variable DrTests
UndeclaredVariable>>runtimeUndeclaredRead
BaselineOfBasicTools>>postload:package:

The class is maybe not loaded yet?

**Comment by hernanmd** [comment]
> There is an error:
> 
> UndeclaredVariableRead: Attempt to read undeclared variable DrTests UndeclaredVariable>>runtimeUndeclaredRead BaselineOfBasicTools>>postload📦
> 
> The class is maybe not loaded yet?

True. I moved the registration code to the post-load of DrTests baseline.
Let's wait the CI.

**Comment by hernanmd** [comment]
The build is green though is shown as aborted (?)

**Comment by jecisc** [comment]
The build pass. It has been month that windows is not working well

**Review by jecisc — APPROVED** [review]
Im approving and I am supporting this change. We need to push the last missing features of DrTest and it will not happen if we don't use it. And on top of that the old test runner was based on categories and morphs which we want to remove.

I'll not merge it myself because this is a big change, I want more reviews :)

**Comment by hernanmd** [comment]
Sure, this would be a perfect call for @MarcusDenker and @Ducasse ? :)

**Pull request merged**
