### PR TITLE
Fixes: #11345 not use  theNonMetaclass and theMetaclass anymore in RB

### LINKED ISSUE #11345: theNonMetaclass is deprecated but still used
Should rewrite the last users.

### PR DESCRIPTION
**Pull request by Ducasse**
convert theNonMetaclass and theMetaclass to their counterpart.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Really strange test failures on Windows:

Tests failing in OSEnvironmentTest with "Illegal leading byte for utf-8 encoding"

e.g.

```
Error
Illegal leading byte for utf-8 encoding
Stacktrace
ZnInvalidUTF8
Illegal leading byte for utf-8 encoding
ZnUTF8Encoder>>error:
ZnUTF8Encoder>>errorIllegalLeadingByte
ZnUTF8Encoder>>nextCodePointFromStream:
[ :stream |
		[ byteStream atEnd ] whileFalse: [ | codePoint |
			codePoint := self nextCodePointFromStream: byteStream.
			(codePoint > 255 and: [ stream originalContents isWideString not ])
				ifTrue: [ | wideString position |
					position := stream position.
					wideString := WideString from: stream originalContents.
					stream on: wideString; setFrom: position + 1 to: position ].
			stream nextPut: (Character value: codePoint) ] ] in ZnUTF8Encoder(ZnUTFEncoder)>>decodeBytes:
String class(SequenceableCollection class)>>new:streamContents:
String class(SequenceableCollection class)>>streamContents:
ZnUTF8Encoder(ZnUTFEncoder)>>decodeBytes:
ByteArray>>decodeWith:
ByteArray>>utf8Decoded
ExternalAddress>>fromCString
[ 
	nextString := environmentStrings fromCString.
	nextString ifEmpty: [ ^ self ].
	nextString first = $=
		ifFalse: [ self keysAndValuesDo: aBlock withAssociationString: nextString ].
	environmentStrings := environmentStrings + nextString size + 1 ] in Win32Environment>>keysAndValuesDo:
FullBlockClosure(BlockClosure)>>repeat
Win32Environment>>keysAndValuesDo:
Win32Environment(OSEnvironment)>>asDictionary
OSEnvironmentTest>>testAsDictionary
OSEnvironmentTest(TestCase)>>performTest
```

**Comment by Ducasse** [comment]
Another bug about the stream encoding. 
Now this is not related to my code. I'm working on mac and I did not any different than before.

**Comment by Ducasse** [comment]
To me this related to the latin encoding or something that we already fixed in the past. Probably in monticello again.

**Comment by Ducasse** [comment]
And I cannot reproduce it on my machine.

**Comment by MarcusDenker** [comment]
was redone as https://github.com/pharo-project/pharo/pull/11464

**Pull request closed without merging**
