### PR TITLE
3006-When-a-test-fails-open-the-debugger-on-the-test-instead-of-on-Objectassert

### PR DESCRIPTION
**Pull request by akevalion**
I have added <debuggerCompleteToSender> pragma to TestAsserter methods in the protocol #asserting

### CODE REVIEW

**Comment by MarcusDenker** [comment]
there is https://github.com/pharo-project/pharo/pull/3008, too

**Comment by akevalion** [comment]
Hi Marcus, how can I resolve this, should I wait for @dupriezt 's PR been accepted ? or should I re upload another PR.
In my PR, I change TestAsserter. Thank you for your time

**Comment by MarcusDenker** [comment]
This PR is in conflict. It can not be merged

**Comment by akgrant43** [comment]
Hi @akevalion ,

> how can I resolve this, should I wait for @dupriezt 's PR been accepted ? or should I re upload another PR.

You need to merge in the latest changes from the Pharo8.0 branch to your PR branch and resolve the conflicts.  When you push change changes back to github the CI will run again and it will show that the PR can be merged (which doesn't say anything about the CI results).

**Comment by akevalion** [comment]
Closed because there is a new PR https://github.com/pharo-project/pharo/pull/3116

**Pull request closed without merging**
