### PR TITLE
Speed up #assertCollection:hasSameElements: in case they are equals.

### LINKED ISSUE #13142: [CI] FLCreateClassSerializationTest takes too much time
The CI often randomly fails on windows because of FLCreateClassSerializationTest having tests taking too much time.

We should check if the tests have a performance problem or not. If it has, fix it. If it does not have any, increase the time limit.

### PR DESCRIPTION
**Pull request by jecisc**
Better fix for https://github.com/pharo-project/pharo/pull/13143

Fixes #13142

### CODE REVIEW

**Review by privat — CHANGES_REQUESTED** [review]
Why not simple if for early return and less indentation levels?
And why not two level of optimization:

```st
actual = expected ifTrue: [^self].

actualSet := actual asSet. "Or asBag is occurences is important, i don't know)"
expectedSet := expected asSet.
actualSet = expectedSet ifTrue: [ ^self].

"compute missing and additional here,
and you already have the set (or bag)
so it can also be faster
..."
```

**Comment by jecisc** [comment]
I was not feeling really good about calling an assert method that does not do assertions but it's dumb. I'll just do plain return yeah. 
I also like the idea of the set/bag. I'll check the behavior of the current assertion and do the same.

**Comment by privat** [comment]
How much faster? We want numbers!

**Review by privat — APPROVED** [review]

**Comment by jecisc** [comment]
Some tests went from 3.5seconds to 40ms :)
Is that fast enough? ;)

**Comment by jecisc** [comment]
The CI did not like it

**Comment by jecisc** [comment]
The tests are passing in my image

**Comment by jecisc** [comment]
Problem comes from Pharo itself

**Comment by jecisc** [comment]
[CI] Fail on WIN random: OmSessionStoreTest(OmStoreTest)>>testEntryForAbsentEntry #12126

**Pull request merged**
