### PR TITLE
Remove dead code in SHTextStyler

### LINKED ISSUE #10080: Syntax Highlighting: unused SHTextStyler>>#styleInBackgroundProcess:
There is still some (complex) code that used to be used to run text styling in a background process. 

See  SHTextStyler>>#styleInBackgroundProcess:

**Describe the request**
We need to decide what to do: just keeping code around so we can look at it in the future.. for that we have Git.

- the code is not used for years
- It was turned off as is lead to lots of race-conditions
- We solved the case of Huge methods (which are not nicely solved with this either) by not styling huge literals

### PR DESCRIPTION
**Pull request by jecisc**
Fixes #10080

### CODE REVIEW

**Comment by Ducasse** [comment]
This is cool to clean. The changes are good. Now I was wondering if using the background process was not a good idea for syntax highlighting.

**Comment by jecisc** [comment]
From what Marcus told me it’s not really possible because the text editor is not thread safe

**Comment by MarcusDenker** [comment]
Another thing is that Shout used it's own parser, now we use the normal AST which we have to create anyway for the tools to work (e.g. menu, code completion, and so on).

In practice sadly they all re-parse, but instead of investing time in a complex workaround like this we should make sure that Shout and all other tools re-use the AST from the code editor instead of re-parsing.

**Review by MarcusDenker — APPROVED** [review]

**Comment by MarcusDenker** [comment]
And if applying styles to the editor would be too slow, it should be solved on the level of the editor for all users who want to style text, nut just like this for only the code highlighter

**Comment by privat** [comment]
You should update the class comments that still talk about removerd stuff

**Comment by jecisc** [comment]
I'm not finished yet with the changes in shout. If it's alright with you i'd like to update the comment in a later PR

**Pull request merged**
