### PR TITLE
Simplify Socket>>waitForAcceptFor: 

### PR DESCRIPTION
**Pull request by jgfoster**
I need to replace Socket>>waitForAcceptFor: and Socket>>waitForAcceptFor:ifTimedOut: and it would be easier to do it in one place. Also, the code seems very similar and this is simpler overall and I believe it is equivalent.

### CODE REVIEW

**Comment by bencoman** [comment]
I am curious why the original **#waitForAcceptFor:** and  **#waitForAcceptFor:ifTimedOut:**
differ in their confirming `self isConnected`.  I've no clue whether it should be dropped or pushed into **#waitForAcceptFor:ifTimedOut**.  @Sven, You've dealt a lot with networking. Any thoughts?

For reference, Squeak 5.2 has...
```
(2003) Socket>>waitForAcceptFor: 
	[self waitForConnectionFor: timeout] on: ConnectionTimedOut do: [:ex | ^nil].
	^self isConnected
		ifTrue: [self accept].

(2008) Socket>>waitForAcceptFor: 
	self waitForConnectionFor: timeout ifTimedOut: [^ nil].
	^ self isConnected
		ifTrue:[self accept]

(2003) Socket>>waitForAcceptFor: timeout ifTimedOut: timeoutBlock
	"Wait and accept an incoming connection"
	self waitForConnectionFor: timeout ifTimedOut: [^timeoutBlock value].
	^self accept

(2007) Socket >> waitForAcceptFor: timeout ifTimedOut: timeoutBlock
	"Wait and accept an incoming connection"
	self waitForConnectionFor: timeout ifTimedOut: [^timeoutBlock value].
	^self isConnected
		ifTrue:[self accept]
```

**Comment by bencoman** [comment]
Since the diff doesn't show both methods, for quick reference, Pharo 7 has...
```
Socker>>waitForAcceptFor: timeout
	self waitForConnectionFor: timeout ifTimedOut: [^ nil].
	^ self isConnected
		ifTrue:[self accept]

Socket>>waitForAcceptFor: timeout ifTimedOut: timeoutBlock
	self waitForConnectionFor: timeout ifTimedOut: [^timeoutBlock value].
	^self accept
```

**Comment by bencoman** [comment]
```
Socket >> waitForConnectionFor: timeout ifTimedOut: timeoutBlock
   ...
   status := self primSocketConnectionStatus: socketHandle
   status = Connected ifFalse: [^timeoutBlock value].
```
```
Socket>>isConnected
	socketHandle == nil ifTrue: [^ false].
	^ (self primSocketConnectionStatus: socketHandle) == Connected
```

I'd guess the nil check is an optimisation to avoid calling **#primSocketConnectionStatus:**, since presumably nil socketHandle fails **#primSocketConnectionStatus:** and returns **InvalidSocket** rather than **Connected**.
But **#waitForAcceptFor:ifTimedOut:** already done the work calling **#primSocketConnectionStatus:**, so there seems redundant for a sender of **#waitForAcceptFor:ifTimedOut:** to also call **isConnected**.

**Comment by bencoman** [comment]
Side thought, with the coming [FullBlockClosure]<https://clementbera.wordpress.com/2016/10/06/copying-and-clean-blocks/> optimsation, rather than using non-local returns it would be interesting to see what **Socket >> waitForConnectionFor: timeout ifTimedOut: timeoutBlock ifConnected: connectedBlock** would have on network performance...
```
Socket >> waitForConnectionFor: timeout ifTimedOut: timeoutBlock ifConnected: connectedBlock
   ...
   status := self primSocketConnectionStatus: socketHandle
   ^ status = Connected 
           ifFalse: timeoutBlock
           ifTrue: connectedBlock

Socket>>waitForAcceptFor: timeout ifTimedOut: timeoutBlock 
	^ self waitForConnectionFor: timeout ifTimedOut: timeoutBlock ifConnected: [self accept]

Socket >> waitForAcceptFor: timeout
    ^ self waitForAcceptFor: timeout ifTimedOut: [nil].

```
So as not to further hijack this PR, if anyone finds that interesting it would be good to follow up in a new issue.
Regarding this PR.  LGTM.

<blockquote><div> Clément Béra</div><div><strong><a href="https://clementbera.wordpress.com/2016/10/06/copying-and-clean-blocks/">Copying and clean blocks</a></strong></div><div>Hi folks, A couple weeks ago the new closure implementation I co-designed and co-implemented with Eliot Miranda has reached the Pharo 6 alpha image. We’re now looking into failing tests to be…</div></blockquote>

**Review by bencoman — APPROVED** [review]

**Review by MarcusDenker — APPROVED** [review]
ok

**Pull request merged**
