### PR TITLE
5166-Update-STON-to-upstream-version

### PR DESCRIPTION
**Pull request by svenvc**
Sync to latest version of STON and add BaselineOfSton

https://github.com/pharo-project/pharo/issues/5166

### CODE REVIEW

**Comment by svenvc** [comment]
resolves https://github.com/pharo-project/pharo/issues/5166

**Comment by MarcusDenker** [comment]
One test on windows is failing:

Got 'FILE[''\\tmp\\foo.txt'']' instead of 'FILE[''/tmp/foo.txt'']'.
Stacktrace
STONWriterTest(TestAsserter)>>assert:description:resumable:
STONWriterTest(TestAsserter)>>assert:description:
STONWriterTest(TestAsserter)>>assert:equals:
STONWriterTest>>testDiskFile

**Comment by svenvc** [comment]
Yes, I was just looking at it, thanks.

I thought there was a platform independent FileReference representation, but apparently not. 

I was using #pringPath:on:

If the representation is different on each platform, it becomes a bit hard to test and not good as a platform independent representation, which is something that STON needs, of course.

**Comment by svenvc** [comment]
Failing

osx-32 / Tests-osx-32 / testGlyphAccessIsThreadSafe – MacOSX32.FreeType.Tests.Cache.FreeTypeCacheTest

does not seem related

**Review by MarcusDenker — APPROVED** [review]

**Comment by svenvc** [comment]
Thank you

**Pull request merged**
