### PR TITLE
Clean traits tests

### PR DESCRIPTION
**Pull request by jecisc**
This change cleans traits tests by simplifying the cleaning and updating the creation API to mimic the FluidClassBuilder

### CODE REVIEW

**Comment by Ducasse** [comment]
Cyril I was wondering why the reason of the change because this is an API internal to the tests.

**Comment by jecisc** [comment]
Some of the cleanings are good but it's true that some other are not so useful. I did them with a script while looking for the origin of a bug. I'll see to update this PR this week to keep only the impactful changes

**Comment by Ducasse** [comment]
I thought so :)

**Comment by jecisc** [comment]
Better fix: https://github.com/pharo-project/pharo/pull/15243

**Pull request closed without merging**
