### PR TITLE
22550-LinkedListdo-Replace--nil-by-isNil

### PR DESCRIPTION
**Pull request by vonbecmann**
Replace == nil by isNil

### CODE REVIEW

**Review by jecisc — APPROVED** [review]

**Comment by MarcusDenker** [comment]
the problem is that LinkedList is used by Process... changing == nil to isNil introduces an interrupt check, which can lead to problems. We managed to intruduce serious bugs just by doing changes to LinkedList in the past like that.

**Comment by MarcusDenker** [comment]
So it needs to be carefully checked that this is not the case here

**Comment by vonbecmann** [comment]
in that case, forget it.

**Comment by Ducasse** [comment]
Yes one day we should rename LinkedList as PrivateSchedulerLinkedList.

**Comment by Ducasse** [comment]
Last time we refactored this code, we got bug arriving after 15 days on the stressed servers of netstyle.

**Pull request closed without merging**
