### PR TITLE
allow system to react to a theme change

### PR DESCRIPTION
**Pull request by estebanlm**
title says all :P

### CODE REVIEW

**Comment by Ducasse** [comment]
Esteban can you use do: [each | instead of #symbol.

**Comment by estebanlm** [comment]
eh? 
I added just one line: 

```Smalltalk
SystemAnnouncer uniqueInstance announce: UIThemeChanged
```
no symbols there. 
all the rest is ancient history and not the purpose of the PR :P

**Comment by Ducasse** [comment]
```
(SystemWindow allSubInstances select:[:e | e owner isNil]) do: #themeChanged.
```
(SystemWindow allSubInstances select:[:e | e owner isNil]) do: [:each | each themeChanged].

**Comment by estebanlm** [comment]
yeah, but I didn't introduce that :P

**Comment by estebanlm** [comment]
can we merge this? I can't push the new version of spotter until this is in

**Pull request merged**
