### PR TITLE
Class Comments: use ivar in ClassDesciption

### PR DESCRIPTION
**Pull request by MarcusDenker**
This PR:

- changes all methods related to class comments in ClassDescription to use the source pointer of ClassDescription
- Change ClassOrganzier to forward to the class and remove the ivar there

after this we should change all code that calls the methods on the organizer and deprecate them

### CODE REVIEW

**Review by dionisiydk — APPROVED** [review]

**Comment by MarcusDenker** [comment]
The MAC CI is down, but the change is not platform specific

**Review by Bajger — APPROVED** [review]
I just wonder that no changes in unit tests needed. Nice!

**Comment by MarcusDenker** [comment]
we need to change one unit test back: the one that tests for un-used ivars has ClassDiscription as a false positive, I will fix that later.

**Comment by MarcusDenker** [comment]
strangely another PR shows that this introduces problems, I revert it for now

**Pull request merged**
