### PR TITLE
adding a nice documentation about the fluid class definition syntax.

### PR DESCRIPTION
**Pull request by Ducasse**
adding a nice documentation about the fluid class definition syntax.

### CODE REVIEW

**Comment by Ducasse** [comment]
May be we should do a backport since this is just a doc.

**Review by jecisc — APPROVED** [review]
I'd say yes for the backport

**Comment by Ducasse** [comment]
Let me know how I can do it

**Comment by jecisc** [comment]
https://github.com/pharo-project/pharo/pull/17154

**Pull request merged**
