### PR TITLE
Merge spec2 0.8.13

### LINKED ISSUE #1070: whenSelectedItemChangedDo: method of SpTreePresenter is broken
For example, is you create a tree presenter like:
```
treePresenter := self newTree.
treePresenter
	roots: Object asOrderedCollection;
	display: #name;
	children: #subclasses;
	whenSelectedItemChangedDo: [ :selectedItem | "some action" ]
```
When you click an element of the tree presenter an exception appears: `Instance of SpTreeSingleSelectionMode did not understand #second `

### LINKED ISSUE #9121: Inspect class : Instance of RubSmalltalkEditor did not undersand #pointIndex:
**Bug description**
I open browse->system browser. Then, I go in a random folder. Then I make a right click on a class, and I click on extra-> inspect.
After, a window open. Finally, I click on Meta menu, and I can see methods.

Here, I can edit a method and save it with ctrl + s. When I save, an error appears (Instance of RubSmalltalkEditor did not understand #pointIndex:). 
But, even if there is an error, the modification works.

**To Reproduce**
1. Go to browse->system browser
2. Click on class -> extra-> inspect
3. Scroll to meta menu, edit a method and save it

**Expected behavior**

**Screenshots**
bug1

**Version information:**
 - OS: Windows 10 Famille
 - Version: 2004
 - Pharo Version Pharo-9.0.0+build.1341

**Expected development cost**
As you know nothing happens magically, so do you have an idea of the development effort required? 
In addition, are you willing to help because after all Pharo is yours too?

**Additional context**

### PR DESCRIPTION
**Pull request by estebanlm**
https://github.com/pharo-spec/Spec/releases/tag/v0.8.13

- general: menu items now print correctly shortcuts (using KMShortcutPrinter)
- general: buttons disabled now "gray" icons. 
- fixed `SpGridLayout` homogeneous and span properties. 
- fixed trees selected paths and items when using multiple selection.
- fixed wrong accumulation of selected elements in multiple selection. 
- fixed https://github.com/pharo-spec/Spec/issues/1070 (thanks @jordanmontt)
- `SpTextPresenter` now implements `lineAtCursorPosition` method, which will enhance the selected based commands.
- fixes https://github.com/pharo-project/pharo/issues/9121
- replace usages of newVertical/newHorizontal when possible (we prefer newTopToBottom/newLeftToRight)
- `SpNotebookPresenter` fix a problem when setting pages directly with anything that is not an OrderedCollection (remove of pages was failing).
- `SpCodePresenter` now allow selecting a particular syntax highlight theme (default is still the one selected on settings).
- `SpApplication` implements `showWaitCursorWhile:` to allow different backend functionality (and start removing usages of UIManager). This is still "experimental", but works.
- fixed hidden dependencies in baseline and demos
- lots of cleanups
- lots of renames to make things more understandable (thanks @NourDjihan)
- lots of new tests

### CODE REVIEW

**Comment by Ducasse** [comment]
The borken tests are fuel on windows so I integrate the changes.

**Comment by estebanlm** [comment]
ok, this was huge... but changes will be faster to integrate from now :)

**Comment by Ducasse** [comment]
Excellent I would like to understand what make it easier to integrate. But we will discuss it live.

**Comment by estebanlm** [comment]
I am preparing a mail to explain it :P

**Pull request merged**
