### PR TITLE
fix/ffilibrary-should-return-itself

### PR DESCRIPTION
**Pull request by estebanlm**
FFILibrary needs to return self when calling #ffiLibrary

### CODE REVIEW

**Comment by akgrant43** [comment]
Hi Esteban,

This looks sensible, but was there a particular failure that triggered the realisation?

Thanks,
Alistair

**Review by MarcusDenker — APPROVED** [review]

**Comment by estebanlm** [comment]
@akgrant43 yes there was. 
In the cases were you use the library as an entry point for a function (take `LibC` as an example). The call to `#ffiLibrary` was actually answering `ffiLibraryName asFFILibrary` which is always an `FFIUnknownLibrary`.
The consequence is that we cannot change `#calloutAPI` or `#runner`, and obviously this is a bug :)

**Comment by akgrant43** [comment]
@estebanlm Thanks for the explanation!

**Comment by Ducasse** [comment]
Can we get a better method comment?

**Pull request merged**
