### PR TITLE
Cleanup some classes of Refactoring packages

### PR DESCRIPTION
**Pull request by Lin777**
Change of:
```
isEmpty not => isNotEmpty
isEmpty ifTrue: [] => ifEmpty: []
(detect: [] ifNone: [nil] ) notNil => anySatisfy: []
```

### CODE REVIEW

**Review by MarcusDenker — APPROVED** [review]

**Comment by Ducasse** [comment]
I have an important point about the change ifNotEmpty: 
ifNotEmpty: is costly, it uses cull:. 
So this means that this is not fully equivalent. 
I would be cautious not to apply this blindly. 

ifNotNil: ifNotNilBlock
	"Evaluate the block, unless I'm == nil (q.v.). If the receiver is not nil, pass it as argument to the block."

	"(2 ifNotNil: [ :o | o + 3]) >>> 5"
	"(nil ifNotNil: [:o | o +3 ]) >>> nil"

	^ ifNotNilBlock cull: self

**Comment by Ducasse** [comment]
For example 	

self superclass notNil ifTrue: [self superclass removeSubclass: self].
self superclass ifNotNil: [self superclass removeSubclass: self].

is not good because it should at least be
self superclass ifNotNil: [:sup| sup removeSubclass: self].

**Comment by Lin777** [comment]
Oh, I didn't know that difference; I thought they behaved the same way. I will be attentive if this change triggers an error. 

Thanks so much for the explanation :D

**Comment by Ducasse** [comment]
Once I really understand the implementation and optimisation I will write an email to the mailing-list.

**Pull request merged**
