### PR TITLE
21623-Update-Jenkinsfile-to-use-staged-bootstrap

### PR DESCRIPTION
**Pull request by akgrant43**
removing previous code duplication, which led to the code being out of
sync twice in the last month.

Fogbugz:
https://pharo.fogbugz.com/f/cases/21623/Update-Jenkinsfile-to-use-staged-bootstrap

### CODE REVIEW

**Comment by jecisc** [comment]
The build is green, I suppose it worked well :)

**Comment by akgrant43** [comment]
> The build is green, I suppose it worked well :)

I wish :-), but Jenkins doesn't allow Jenkinsfile to be replaced as part of a PR, so the CI check means nothing in this case (it used the original Jenkinsfile).

Guille knows what needs to be done to get it integrated correctly.

**Comment by guillep** [comment]
I'll check it tomorrow first time in the morning

**Comment by guillep** [comment]
@akgrant43, I've sent you an invitation to appear in the list of collaborators. That will make jenkins trust your changes in the JenkinsFile. Tell me when you've accepted them, I'll relaunch the build.

**Comment by akgrant43** [comment]
Hi @guillep,

Thanks!  I've accepted the invite.

Cheers,
Alistair

**Comment by akgrant43** [comment]
Hmm, not sure what happened, but it is still running the old Jenkinsfile.

**Comment by tesonep** [comment]
Last one has run with the new JenkinsFile, the error is not related. It was a recurrent problem with the cleaning of the unix nodes.

**Review by tesonep — APPROVED** [review]

**Comment by guillep** [comment]
Ouki, Thanks both

**Comment by akgrant43** [comment]
Thanks, Guille & Pablo!

**Pull request merged**
