### PR TITLE
prepare-fasttable-to-work-with-generator

### PR DESCRIPTION
**Pull request by estebanlm**
fast table need to work also with a "generator" approach. This change introduces this dimesion without affecting the regular behavior. 
(this is useful to display things that need time to be calculated)

### CODE REVIEW

**Review by tesonep — APPROVED** [review]

**Comment by Ducasse** [comment]
May be adding a comment on elementAt: stating that this is an important hook for lazy or paginated source would be good. 
We do not value enough comments.

**Comment by guillep** [comment]
> May be adding a comment on elementAt: stating that this is an important hook for lazy or paginated source would be good.
> We do not value enough comments.

Hi Stef, maybe you can add that as a "review" requesting changes?
A PR with requested changes is marked as red, while an approved PR is marked as green.
So we can identify/filter PRs super fast :)

**Comment by Ducasse** [comment]
How do I do that?

**Comment by guillep** [comment]
> How do I do that?

Please, do not insult me, it's github's interface that is bad :)

1. go to "Files Changed"

image

2. There you can click on the code and add commes to it:

image

You'll be asked if you want to "Start a review" or "add a single comment" => start a review

3. Once you finished reviewing, go to the top right, find the green button "Review Changes"

image

There you can input a general comment and choose: do you approve the changes? do you ask for changes? Or you just do comments.

Then submit the review :)

**Review by guillep — APPROVED** [review]
Good

**Comment by guillep** [comment]
@Ducasse see #5904

**Pull request merged**
