### PR TITLE
3027-Clean-flags-in-the-system

### LINKED ISSUE #3027: Clean flags in the system
With Stephane we will do a pass on the flags in the system.
Some of them are useless, some of them should be just comments, some of them should be Pharo issues, some of them are obsolete...

### PR DESCRIPTION
**Pull request by jecisc**
First step of cleaning flags.

- We removed some useless flags
- We removed some flags that will never be changed
- We corrected some issues raised by flags
- We now use flags prefixed with #pharo to make it easier to filter them in a future flag browser

Fixes #3027

### CODE REVIEW

**Comment by Ducasse** [comment]
Argh we got conflicts.
Cyril can you handle them?

**Comment by jecisc** [comment]
I’ll do it when I’ll have a computer and some time :)

**Comment by Ducasse** [comment]
Thanks. I do not know how to do it safely. I'm trying to learn how to do it. 
If I fail I will let you do it. :)

**Comment by Ducasse** [comment]
I tried but failed. 
I do not know how to push back the merge I did. And I get an error because I imagine that I cannot push to your repo. So I do not want to do a PR to you for three stupid methods.

**Comment by MarcusDenker** [comment]
before I merged slots I asked cyril and he told me I should merge first, he will fix the conflict after.

**Comment by Ducasse** [comment]
I relaunched it to try.

**Comment by jecisc** [comment]
I think the problems might come from the Pharo8.0 branch that was broken. I did a merge hoping to fix the issues.

**Comment by Ducasse** [comment]
I do not think that the broken tests are related so I push this because it is touching many packages and the changes are cosmetical.

**Pull request merged**
