### PR TITLE
3726-allBehaviorsDo-can-now-use-the-cached-allBehaviors

### LINKED ISSUE #3726: #allBehaviorsDo: can now use the cached allBehaviors
allBehaviorsDo:  in SystemDictionary can now be just

	self allBehaviors do: aBlock

it will be faster as it will use the cached behaviours

### PR DESCRIPTION
**Pull request by MarcusDenker**
fixes #3726

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Before:
"'128.021 per second'"

After:
"'8530.600 per second'"

**Comment by Ducasse** [comment]
super nice figures.

**Comment by Ducasse** [comment]
I do not understand the why I get this message when I want to integrate.

**Comment by MarcusDenker** [comment]
no idea, the "all methods in one file" means there are conflicts if you change the same class but different methods

I will redo the change with a fresh image

**Pull request closed without merging**
