### PR TITLE
Fix ring global variable

### PR DESCRIPTION
**Pull request by guillep**
There is a wrong inheritance relation.

Required by the bootstrap and compilation on ring

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Pharo12 build is broken, see https://github.com/pharo-project/pharo/issues/17472

**Comment by Ducasse** [comment]
I do not really get it. When I look at this "Details" I get the build green on mac and unix.

https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-17470/2/pipeline-graph/

<blockquote><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-17470/2/pipeline-graph/">Graph [Pharo » PR-17470 #2] [Jenkins]</a></strong></div></blockquote>

**Comment by Ducasse** [comment]
Capture 2024-12-01 at 17 34 46

**Comment by MarcusDenker** [comment]
Ah, I was wrong: the error described in the issue happens only in the other PR.

This one had a random crash, with a re-run that did not happen anymore.

This: good to merge

**Pull request merged**
