### PR TITLE
3471-SmallIntegers-comment-is-out-of-date (fixes #3471)

### LINKED ISSUE #3471: SmallInteger's comment is out of date
Only mentions 32 bit versions, but it actually maxVal/minVal actually depends on the architecture.

### PR DESCRIPTION
**Pull request by majella67**
SmallInteger comment 63bit update

### CODE REVIEW

**Comment by MarcusDenker** [comment]
this PR has strangely lots of other changes that are unrelated

**Comment by majella67** [comment]
My bad, still learning Git and Iceberg. Should I try again?

**Comment by jecisc** [comment]
Maybe merging Pharo8.0 branch into your branch might remove the unwanted changes?

**Comment by majella67** [comment]
I did the merge. Are there still problems?

**Comment by jecisc** [comment]
There is still one change not related to the PR but it's normal and it's fine to integrate it. 

For info on this change:

From what we saw with Julien, two people corrected the same problem at the same time and both PR where merged. This introduced a duplication of methods in SUnit. It's the reason this PR contains the removal of some methods. During a new export of the SUnit code, the duplicated methods are removed.

IMO it's fine to merge this PR :)

**Review by jecisc — APPROVED** [review]
Good! Thank you.

**Pull request merged**
