### PR TITLE
Cleanup: more instance side #initialize 	categorization cleanups

### LINKED ISSUE #12161: Cleanup: more instance side #initialize categorization cleanups
- bring the number down to 9

### PR DESCRIPTION
**Pull request by astares**
Fix #12161

### CODE REVIEW

**Comment by vonbecmann** [comment]
i did the same in
https://github.com/svenvc/zodiac/pull/12
https://github.com/svenvc/zinc/pull/109

**Comment by astares** [comment]
Only recategorization - should be easy to review. Anyone?

**Review by hogoww — APPROVED** [review]
Everything looks good!

**Comment by MarcusDenker** [comment]
Failing tests (on all plattforms)

 testClassTraitIfMetaclassAlreadyExists – MacOSX64.Ring.Tests.Core.RGEnsureTraitTest
testImplicitEnvironmentContentForMetaclassDefinition – MacOSX64.Ring.Tests.Core.RGEnvironmentBackendTest
testMetaSide – MacOSX64.Ring.Tests.Core.RGMethodTest

**Comment by astares** [comment]
Had some merging issues. I redid a new PR in  https://github.com/pharo-project/pharo/pull/12227

We close this one here and focus on #12227

**Pull request closed without merging**
