### PR TITLE
Proper categorization in Zodiac-Tests package #2353

### PR DESCRIPTION
**Pull request by astares**
Fix for #2353
- method category "testing" is not for tests, use "tests"
- group some tests into "testing - xxxx" categories

### CODE REVIEW

**Comment by astares** [comment]
@svenvc Can you please have a look and reintegrate into Zodiac?

**Comment by svenvc** [comment]
@astares could you please do a PR on https://github.com/svenvc/zodiac ?

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/svenvc/zodiac">svenvc/zodiac</a></strong></div><div>Zodiac is an open-source Smalltalk framework implementing TLS/SSL secure as well as regular socket streams. - svenvc/zodiac</div></blockquote>

**Comment by astares** [comment]
@svenvc done, see https://github.com/svenvc/zodiac/pull/8

**Comment by svenvc** [comment]
Thank you!

**Pull request merged**
