### PR TITLE
SequenceableCollection - Add executable comments for sorting protocol

### LINKED ISSUE #5450: Add executable comments in SequenceableCollection - sorting shuffling split protocol
There are a lot of opportunities to improve the comment using executable comments in the collection hierarchy and in particular SequencableCollection 

"#(a b c) allButFirst >>> #(b c)"

### PR DESCRIPTION
**Pull request by Lin777**
Only add executable comments to the sorting protocol because suffle always gives a different result and splitjoin protocol already has its executable comments

Fixes #5450

### CODE REVIEW

**Review by dionisiydk — COMMENTED** [review]
It would be nice to add also examples with sort function like
```Smalltalk
#(1 2 3 4) sort: #even ascending

```

**Comment by svenvc** [comment]
But this example makes little actual sense (sorting booleans).

What about

    #(xa xc xz xb xy) sort: #last ascending.

for sorting based on the last letter ?

**Comment by dionisiydk** [comment]
Sure, your example is better. Mine was just to show the sort function here

**Comment by Lin777** [comment]
Thanks for the suggestions @svenvc and @dionisiydk, I added some comments that contemplate this type of examples

**Review by dionisiydk — APPROVED** [review]
Great

**Pull request merged**
