### PR TITLE
remove  commentSourcePointer from ClassOrganization

### LINKED ISSUE #10958: [Memory] commentSourcePointer is not needed for MetaClasses
**Bug description**
the source pointer to comments is stored in ClassOrganization. Now both the class and the metaclass have a ClassOrganization instance, but the source pointer for the comment is only needed once.

**Why is this a problem?**
It is not a severe problem (else this would have already been fixed a loooong time ago). But it wastes a little bit of memory.
(just some ~75Kb in the current Pharo10).

**What needs to be done**
The reason why this is stored in the ClassOrganization is just that it was too hard to change Class itself without the bootstrap way back when it was added (ST80 did not save class comments in the .sources/changes).

That means: we just need to move the commentSourcePointer to Class, then MetaClass will not waste space with it anymore,

### PR DESCRIPTION
**Pull request by MarcusDenker**
this removes  commentSourcePointer from ClassOrganization, forwards for now the methods without deprecation

### CODE REVIEW

**Comment by MarcusDenker** [comment]
FLCreateClassSerializationTest>>testCreateWithComment
FLCreateTraitSerializationTest>>testCreateWithComment

**Comment by MarcusDenker** [comment]
So fuel just serializes the sourcePointer because it serializes the organization completely. This makes these tests green, but it is actually dangerours: if you load the class in anther image, this pointer will point just to a random place in the .changes

**Comment by MarcusDenker** [comment]
I suggest to

- change the tests for now to test for comments to be nilled, as this is much better than a wrong sourcePointer
- open an issue for Fuel to change serialization of classes to explicitly store the comment

**Review by jecisc — APPROVED** [review]
:)

**Pull request merged**
