### PR TITLE
22614-Integrate-Calypso-v0120

### PR DESCRIPTION
**Pull request by estebanlm**
https://pharo.manuscript.com/f/cases/22614/Integrate-Calypso-v0-12-0

### CODE REVIEW

**Comment by jecisc** [comment]
```
Loaded -> Calypso-SystemTools-OldToolCompatibillity-tonel.1 --- github://pharo-ide/Calypso:v0.12.0/src --- cache
...finished baselineKeyNotFound: key #ClyBrowser not found in SystemDictionary
SystemDictionary(Dictionary)>>errorKeyNotFound:
[ self errorKeyNotFound: key ] in SystemDictionary(Dictionary)>>at: in Block: [ self errorKeyNotFound: key ]
SystemDictionary(Dictionary)>>at:ifAbsent:
SystemDictionary(Dictionary)>>at:
BaselineOfIDE>>loadCalypso
BaselineOfIDE>>additionalInitialization
BaselineOfIDE>>postload:package:
[ :aLoader :pkgSpec | 
self project configuration
	perform: selector
	with: aLoader
	with: pkgSpec ] in MetacelloMCVersionSpec(MetacelloSpec)>>doItBlock: in Block: [ :aLoader :pkgSpec | ...
BlockClosure>>valueWithPossibleArgs:
[ block
	valueWithPossibleArgs:
		(Array with: aPostloadDirective loader with: aPostloadDirective spec) ] in MetacelloLinearLoadDirective(MetacelloVersionLoadDirective)>>loadPostloadDirective: in Block: [ block...
MetacelloPostLoadDirective(MetacelloPrePostLoadDirective)>>evaluateSupplyingAnswers:
MetacelloLinearLoadDirective(MetacelloVersionLoadDirective)>>loadPostloadDirective:
MetacelloPostLoadDirective>>loadUsing:gofer:
[ :directive | directive loadUsing: aLoaderDirective gofer: aGofer ] in MetacelloLinearLoadDirective(MetacelloVersionLoadDirective)>>loadLinearLoadDirective:gofer: in Block: [ :directive | directive loadUsing: aLoaderDirecti...etc...
OrderedCollection>>do:
MetacelloLinearLoadDirective(MetacelloVersionLoadDirective)>>loadLinearLoadDirective:gofer:
MetacelloLinearLoadDirective>>loadUsing:gofer:
[ :directive | directive loadUsing: aLoaderDirective gofer: aGofer ] in MetacelloLinearLoadDirective(MetacelloVersionLoadDirective)>>loadLinearLoadDirective:gofer: in Block: [ :directive | directive loadUsing: aLoaderDirecti...etc...
OrderedCollection>>do:
MetacelloLinearLoadDirective(MetacelloVersionLoadDirective)>>loadLinearLoadDirective:gofer:
MetacelloLinearLoadDirective>>loadUsing:gofer:
MetacelloLinearLoadDirective(MetacelloVersionLoadDirective)>>loadWithPolicy:
MetacelloLoaderPolicy>>load
MetacelloFetchingMCSpecLoader>>doLoad
[ fetchLoader doLoad ] in [ | fetchLoader |
fetchLoader := self
	fetchRequiredFromArray: (self defaultPackageNamesToLoad: anArray).
MetacelloPlatform current
	do: [ fetchLoader doLoad ]
	displaying: 'Loading ' , displayString.
Transcript
	cr;
	show: '...finished ' , self versionNumber printString.
^ fetchLoader ] in MetacelloMCVersion>>doLoadRequiredFromArray: in Block: [ fetchLoader doLoad ]
[ :bar | 
bar value: 1.
aBlock value.
bar value: 2 ] in MetacelloPharo30Platform(MetacelloPharoCommonPlatform)>>do:displaying: in Block: [ :bar | ...
BlockClosure>>cull:
[ ^ block cull: self ] in [ self prepareForRunning.
CurrentJob value: self during: [ ^ block cull: self ] ] in Job>>run in Block: [ ^ block cull: self ]
[ activeProcess psValueAt: index put: anObject.
aBlock value ] in CurrentJob(DynamicVariable)>>value:during: in Block: [ activeProcess psValueAt: index put: anObject....
BlockClosure>>ensure:
starting...
UIThemeRegistry
```

**Comment by jecisc** [comment]
@estebanlm `ClyBrowser` was renamed `ClyBrowserMorph`

**Comment by estebanlm** [comment]
test passed but is stalled, no idea why. 
@guillep can you look at it and tell me what happens?

**Comment by estebanlm** [comment]
now, tests seems unrelated :S

**Comment by estebanlm** [comment]
still tests not related

**Pull request merged**
