### PR TITLE
22466-Add-readWriteStream-and-readWriteStreamDo-in-FileSystem

### PR DESCRIPTION
**Pull request by svenvc**
https://pharo.fogbugz.com/f/cases/22466/Add-readWriteStream-and-readWriteStreamDo-in-FileSystem

Add FileReference>>#binaryReadWriteStream to be used by SourceFile>>#tryOpenReadOnly:

Modify FileReference>>#binaryWriteStream to no longer return a read/write stream but just a write stream

Patch MemoryFileWriteStream>>#close by adding a #flush

Remove IV writeStream from MemoryFileWriteStream

Remove the unused MemoryWriteStream

Fix MemoryFileSystemTest>>#testModifiedTimeWhenFileWrittenTo and MemoryFileSystemTest>>#testModifiedTimeWhenFileModifiedWithBinaryWriteStream to write bytes to a binary stream instead of strings

Fix StdioStreamTestResource>>#setUp by removing #wrappedStream

Collapse the streams and streams-compatibility protocols in the FileReference hierarchy

Categorise all methods in SourcFile

### CODE REVIEW

**Comment by svenvc** [comment]
this needs a review, preferably by guille

**Review by guillep — CHANGES_REQUESTED** [review]
Hi, I've checked the changes (sorry for the delay), I think they go in the right direction. However, I've found a regression that makes write streams not being buffered anymore by default.

Before the change:

```
ref := 'Pharo.image' asFileReference.
ref fileSystem binaryWriteStreamOn: ref.
"a BinaryFileStream"

ref := 'Pharo.image' asFileReference.
ref fileSystem binaryReadStreamOn: ref.
"a ZnBufferedReadStream"

'Pharo.image' asFileReference readStream.
"ZnCharacterReadStream -> ZnBufferedReadStream -> BinaryFileStream"

'Pharo.image' asFileReference writeStream.
"ZnCharacterWriteStream -> ZnCharacterReadWriteStream -> BinaryFileStream"

'Pharo.image' asFileReference binaryReadStream.
"ZnBufferedReadStream -> BinaryFileStream"

'Pharo.image' asFileReference binaryWriteStream.
"BinaryFileStream"

'Pharo.image' asFileReference binaryReadWriteStream.
"ZnBufferedReadWriteStream -> BinaryFileStream"
```

After the change:
```
ref := 'Pharo.image' asFileReference.
ref fileSystem binaryWriteStreamOn: ref.
"a BinaryFileStream"

ref := 'Pharo.image' asFileReference.
ref fileSystem binaryReadStreamOn: ref.
"a ZnBufferedReadStream"

'Pharo.image' asFileReference readStream.
"ZnCharacterReadStream -> ZnBufferedReadStream -> BinaryFileStream"

'Pharo.image' asFileReference writeStream.
"ZnCharacterWriteStream -> BinaryFileStream"

'Pharo.image' asFileReference binaryReadStream.
"ZnBufferedReadStream -> BinaryFileStream"

'Pharo.image' asFileReference binaryWriteStream.
"BinaryFileStream"

'Pharo.image' asFileReference binaryReadWriteStream.
"ZnBufferedReadWriteStream -> BinaryFileStream"
```

I'm going to fix it myself as a punishment for the delay ^^

**Comment by guillep** [comment]
Well, I've re-merged against development (that's why there is some more noise).

My changes are actually in this single commit: https://github.com/pharo-project/pharo/pull/1924/commits/88e5af14002b53587db6bc70c3d94050d8d29d37

Let's wait until tests run.

**Review by guillep — APPROVED** [review]

**Comment by svenvc** [comment]
I don't understand why this does not get integrated ?

**Review by akgrant43 — APPROVED** [review]
Sven's changes all look good.  I also agree with Sven that Guille's changes make sense, but haven't tested them.

Slightly off topic: Can this be merged while all the noise is present?  If it wouldn't have any affect, why does the noise show up?

Not a git expert,
Alistair

**Pull request merged**
