### PR TITLE
ClassParser: methods polymorphic to RB-nodes for Calypso integration

### PR DESCRIPTION
**Pull request by dionisiydk**
- parent field is added to CD nodes
- methods polymorphic to RB-nodes which are required for Calypso integration (isLiteralVariable, isVariable, isGlobalVariable, etc)

### CODE REVIEW

**Comment by guillep** [comment]
Hi Denis, this change is at least breaking the three following tests:

image

**Comment by dionisiydk** [comment]
Hi @guillep.
Thanks for notice (always skip failure reports). I fixed tests. 

What do you think to rename more messages for testing the type of class in definition? (in another PR).
I feel it a bit weird to read "aClassDefinitionNode isBytes". I think it would be better to have a pattern like "definesTypeNameClass": definesImmediateClass, definesBytesClass, definesNormalClass and so on.

**Comment by Ducasse** [comment]
Hi denis

Indeed we should improve the API. 
We should aslo remove some duplicated code I was forced to introduce. 
Stef

**Comment by guillep** [comment]
> What do you think to rename more messages for testing the type of class in definition? (in another PR).
> I feel it a bit weird to read "aClassDefinitionNode isBytes". I think it would be better to have a pattern like "definesTypeNameClass": definesImmediateClass, definesBytesClass, definesNormalClass and so on.

Yes maybe that could be good? Do you want to add that to this PR or to add a new one?

@Ducasse have you reviewed the changes?

**Comment by dionisiydk** [comment]
I will do rename in another PR

вт, 16 апр. 2019 г., 14:07 Guille Polito <notifications@github.com>:

**Review by guillep — APPROVED** [review]
Ok!

@Alisu maybe you want to merge also these changes into ClassInfrastructure?

**Pull request merged**
