### PR TITLE
[DrTests] Other test hierarchies than TestAssertable are not handled by DrTest

### LINKED ISSUE #7482: [DrTests] Other test hierarchies than TestAssertable are not handled by DrTest
**Describe the request**
Tests from a parallel class hierarchy should be recognized by Dr.Test as soon as isTestClass is implemented on the class side and answer true

**Expected development cost**
WIP

### PR DESCRIPTION
**Pull request by VincentBlondeau**
First try

### CODE REVIEW

**Comment by Ducasse** [comment]
Yes there is not need to check TestCase explicitly.

**Comment by Ducasse** [comment]
There 6 related broken tests:
unix-64 / Tests-unix-64 / testReRunResultIsDTTestRunnerResult – Unix64.DrTests.Tests.DrTestsTestRunnerTest
<1s
unix-64 / Tests-unix-64 / testRunResultBuildTreeForUI – Unix64.DrTests.Tests.DrTestsTestRunnerTest
<1s
unix-64 / Tests-unix-64 / testRunResultIsDTTestRunnerResult – Unix64.DrTests.Tests.DrTestsTestRunnerTest
<1s
unix-64 / Tests-unix-64 / testTestResultIsNotEmpty – Unix64.DrTests.Tests.DrTestsTestRunnerTest
<1s
unix-64 / Tests-unix-64 / testRunTestsUpdatesUIWithResults – Unix64.DrTests.Tests.DrTestsTestRunnerUITest
<1s
unix-64 / Tests-unix-64 / testExternalSUnitKernelDependencies – Unix64.System.DependenciesTests.SystemDependenciesTest

**Review by tesonep — APPROVED** [review]

**Comment by MarcusDenker** [comment]
Tests failing are related to the change

**Comment by Ducasse** [comment]
the following tests are broken

nix-64 / Tests-unix-64 / testReRunResultIsDTTestRunnerResult – Unix64.DrTests.Tests.DrTestsTestRunnerTest
<1s
unix-64 / Tests-unix-64 / testRunResultBuildTreeForUI – Unix64.DrTests.Tests.DrTestsTestRunnerTest
<1s
unix-64 / Tests-unix-64 / testRunResultIsDTTestRunnerResult – Unix64.DrTests.Tests.DrTestsTestRunnerTest
<1s
unix-64 / Tests-unix-64 / testTestResultIsNotEmpty – Unix64.DrTests.Tests.DrTestsTestRunnerTest
<1s
unix-64 / Tests-unix-64 / testRunTestsUpdatesUIWithResults – Unix64.DrTests.Tests.DrTestsTestRunnerUITest

**Comment by VincentBlondeau** [comment]
Failure : DependenciesTests.SystemDependenciesTest> testExternalSUnitKernelDependencies 
Seems to already exists on the current image.

**Pull request merged**
