### PR TITLE
Rename AST-Core classes to start by AST

### LINKED ISSUE #10815: Cleanup: Prefix change from "RB" to "AST" for Abstract syntax tree related classes
From the historic point of view Smalltalk started I guess Smalltalk refactorings had their roots in the Refactoring Browser (RB) and can be traced back to work at UIUC (University of Illinois, Urbana-Champaign) by Don Roberts, John Brant, and Ralph Johnson

 - https://wiki.c2.com/?RefactoringBrowser
 - https://refactory.com/refactoring-browser
 - https://www.researchgate.net/publication/220346807_A_Refactoring_Tool_for_Smalltalk

Following this history the classes like RBNode had an "**RB**" prefix for **RefactoringBrowser**.

But logically now in newer Pharo we have put them into packages for "AST" - Abstract Syntax Tree

image

If you think about it for a while it would be more logically to have them prefixed with "AST" instead of "RB". Yes - we know it is heritic and means effort and deprecation/transition/migration - but for Pharo we want to constantly improve, get clean and do for the better.

Additionally this would also help people who are comming from other (more mainstream) languages to find it in alignment with the AST concepts and namings there.

### PR DESCRIPTION
**Pull request by jecisc**
Rename classes from AST-Core to start by AST instead of starting by RB.

Since AST-Core is loaded by Hermes I just need to check if the initializes are executed.

Fixes #10815

### CODE REVIEW

**Comment by Ducasse** [comment]
there is a conflict

**Comment by MarcusDenker** [comment]
With the aliases, renamings like that are finally possible... but sometimes I wonder if we should not wait till we have a real module system: any prefix is just bad. Whatever it is. But changing it just because it feels nicer is still a change that everyone has to deal with... for what in the end ?

**Comment by Ducasse** [comment]
I like the idea because it is not clear why we have RB for nodes.

**Comment by Ducasse** [comment]
And this is not tomorrow that we will have modules because it raises a lof of questions.

**Comment by Ducasse** [comment]
@jecisc I think that we should redo this PR

**Comment by jecisc** [comment]
I did a smaller PR because this one is too big

**Pull request closed without merging**
