### PR TITLE
8198 reorganize world menu

### PR DESCRIPTION
**Pull request by gcorriga**
Reorganize the world menu as per [(https://github.com/pharo-project/pharo/issues/8198)] .

Change is structured as follows:
- change order score for the main menus from 0,1,2,etc to 0,10,20...99
- structure the menu in groups. Individual menu items use these groups as parents as opposed to the main menus.

Changes to individual menu items are as per screenshots in the linked issue.

### CODE REVIEW

**Comment by Ducasse** [comment]
Under VCS we should have iceberg as first entry and I would put (Monticello Browser) and (catalog Browser) 
to indicate that they are deprecated.

**Comment by Ducasse** [comment]
DependencyAnalyser could go on tools or develop.
Iceberg could also have an etnry on develop because we use it all the time.

**Comment by gcorriga** [comment]
Iceberg is meant to be the first entry - not sure why that's not happening when loading the code. I'll take a look.

Not sure if wrapping menu items in parenthesis does convey the right message - I would suggest adding '(Legacy)' to the labels:
image

**Comment by gcorriga** [comment]
The reason the Iceberg menu item isn't included is that the standard pharo repository entry as set up in the image does not include the Iceberg packages.

How should I include this change? Do I need to send a separate PR for Iceberg?

**Comment by gcorriga** [comment]
> DependencyAnalyser could go on tools or develop.
> Iceberg could also have an etnry on develop because we use it all the time.

The idea behind the current set up is to split the menu items between Develop (tools to browse and change the behavour of the image) and VCS (tools to manage code changes, packages, and collaboration). This is regardless of how often the tools are used.

**Comment by Ducasse** [comment]
Excellent idea. 
This is important that people know the status of things. 
Could you put (preview) after drTest ?

**Comment by gcorriga** [comment]
(Preview) added.

Can you please confirm how we should proceed with the 'Iceberg' menu entry?

**Comment by astares** [comment]
@Ducasse Can you please ellaborate why DrTest still a preview? Would be nice to know more details. I guess it is a useful tool. 
It was a preview in Pharo 8, is now part of the image since over a year and got cleaned now also in Pharo 9. Why declaring it as "Preview" for Pharo 9 still?

**Comment by Ducasse** [comment]
Because it means that they are some parts that we want to improve but did not get the time and julien left for a Java shop :(

**Comment by Bajger** [comment]
Hi @gcorriga ! Can we rename VCS menu item to just "Version Control" or "Versioning"? I know, such abbreviation is quite obvious to SW developers, but still it is abbreviation. 
Also, what remains in Tools? Is it just Roassal? Can it be "Community" or rather "Visualization"? I just think stating "Tools" is a bit ambiguous compared to other development or debug tools. 
Thanks for your insight!

**Comment by gcorriga** [comment]
@Bajger happy to change from VCS to something else, but I'm not keen on using either multiple words or -ing suffixes for a top-level menu name. So I would suggest some other alternatives:

Source
Versions
Changes

As for tools, it needs to be kept at least for pharo 9 for backwards compatibility. But in general the idea is to keep it as the default entry point for any non-standard tools that someone might want to have loaded in the image. E.g. if you load Teapot, the two menu items would be found there.

**Comment by Ducasse** [comment]
Can you use Version Control?

I would like to integrate this so that we can get feedback else it will rot.

**Comment by Bajger** [comment]
Ok, got it! Maybe we could ask for some feedback on discord (kind of survey with just buttons 1, 2, 3 for each alternative)...Just curious what other think...

**Comment by Ducasse** [comment]
Yes this is a good idea but I'm more than super busy in this moment so if you want to take the lead on this be our guest :)

**Comment by Bajger** [comment]
I replied with results on original issue. I guess there were quite few other ideas in place, I was trying to put it together.

**Comment by gcorriga** [comment]
I've updated the PR with the latest changes given the feedback received.

**Comment by Ducasse** [comment]
Nice!

**Comment by Ducasse** [comment]
Broken tests are unrelated.

**Comment by Ducasse** [comment]
I revert because this is not good and it is broken see.... 
https://github.com/pharo-project/pharo/issues/8412

**Pull request merged**
