### PR TITLE
3838-Add-release-test-to-ensure-we-do-not-have-shadow-variable-in-the-image

### LINKED ISSUE #3838: Add release test to ensure we do not have shadow variable in the image
To ensure what James removed is not introduced again.

### PR DESCRIPTION
**Pull request by jecisc**
Add release test + remove shadowed variables.

This PR will not be broken until Tonel is fixed :(

Fixes #3838

### CODE REVIEW

**Comment by jecisc** [comment]
This PR requires the integration of a Tonel version with this fix: https://github.com/pharo-vcs/tonel/pull/79

**Comment by MarcusDenker** [comment]
The problem is that we now have to wait for the already fix to show up in Pharo8.

**Comment by jecisc** [comment]
Yes, I know :( But I still did the PR otherwise I would have forgotten it.

**Comment by MarcusDenker** [comment]
could you split this into two: the test only and all the cleanups?

The test is so small then that it could be part of the issue, not the PR.

(PRs need to be actionable, else they just use up space here...)

**Comment by MarcusDenker** [comment]
This shows again that we can not afford to rely on code in the image where trivial fix takes weeks to do

**Comment by jecisc** [comment]
Here is the first step: https://github.com/pharo-project/pharo/pull/4193

When it will be integrated we can merge Pharo8 in this PR and get only the test.

**Pull request merged**
