### PR TITLE
[Calypso] Refactor and bugfix on ClySystemEnvironment

### PR DESCRIPTION
**Pull request by sonibla**
Hello there

I refactored and improved the class compilation in ClySystemEnvironment.
Now it is more readable, tested, and some #todo removed.

Issue fixed: when trying to create a method only with a name from the class definition, a "Subscript out of bonds" error was created.

Possible improvements: more robust parsing of class/trait definition (see isTraitDefinition, isClassDefinition methods for example), for example support comments

Improvement of #8773 , but the error already existed before the PR

### CODE REVIEW

**Comment by Ducasse** [comment]
Thanks! It was on my list but the logic of this code always made me sick.

**Comment by dionisiydk** [comment]
Hi.
It's improvement of course but all this logic should be replaced by class parser

**Comment by Ducasse** [comment]
We have one CDClassDefinitionParser. It should be made more robust.

**Comment by Ducasse** [comment]
Hi @sonibla 
could you help on the new bug https://github.com/pharo-project/pharo/issues/8878
Because I think that we introduced a regression. We cannot define testcase anymore in fluid class mode and 
we get an error when we want to redefine an existing class?
I do not have cycles to look now.

**Comment by sonibla** [comment]
Ok i'll look

**Pull request merged**
