### PR TITLE
[Do not integrate] Update bootstrap to pharo7

### PR DESCRIPTION
**Pull request by carolahp**

### CODE REVIEW

**Comment by bencoman** [comment]
Can you comment on why its "do not integrate".

**Comment by carolahp** [comment]
> Can you comment on why its "do not integrate".

This is an intermediate step. It is necessary to create definitive versions of the related repositories (in progress). Besides, I prefer to wait for the Pharo7 release.

**Comment by Ducasse** [comment]
What should we do on this one? we are now in P8

**Comment by tesonep** [comment]
The process is still using Pharo6.1, it should be passed to use Pharo7 (as it is the stable).
@carolahp maybe it will be better to open a new PR with the modification to take all the changes. 
Also, we need to generate a release of Ring2 with the required support.

**Pull request closed without merging**
