### PR TITLE
EmbeddedFreeTypeFontFontDescription should be EmbeddedFreeTypeFontDescription

### LINKED ISSUE #7587: EmbeddedFreeTypeFontFontDescription should be EmbeddedFreeTypeFontDescription
- rename EmbeddedFreeTypeFontFontDescription into EmbeddedFreeTypeFontDescription (with a single "Font" in the name)
- deprecate old EmbeddedFreeTypeFontFontDescription class by moving it into Deprecated90 package with tag EmbeddedFreeType

Note: this also changes the superclass of LucidaGrandeRegular, SourceCodeProRegular and SourceSansProRegular correctly

### PR DESCRIPTION
**Pull request by astares**
Fix #7587

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Build failure:


SubclassResponsibility: EmbeddedFreeTypeFontFontDescription class had the subclass responsibility to implement #fontContents
EmbeddedFreeTypeFontFontDescription class(Object)>>subclassResponsibility

**Comment by astares** [comment]
Unrelated CI failing

**Comment by MarcusDenker** [comment]
build fails with:

SubclassResponsibility: EmbeddedFreeTypeFontFontDescription class had the subclass responsibility to implement #fontContents

No tests were run as it can not create an image in the first place

**Comment by astares** [comment]
CI failing unrelated

**Comment by astares** [comment]
@MarcusDenker can we proceed with merge?

**Comment by MarcusDenker** [comment]
to me the CI looks like it break the build. No tests run, as a full image was never created.

the failure:


SubclassResponsibility: EmbeddedFreeTypeFontFontDescription class had the subclass responsibility to implement #fontContents

**Comment by astares** [comment]
Will send a new PR

**Pull request closed without merging**
