### PR TITLE
22159 Categorize and comment STON-Core and STON-Tests

### PR DESCRIPTION
**Pull request by astares**
https://pharo.fogbugz.com/f/cases/22159/Categorize-and-comment-STON-Core-and-STON-Tests

### CODE REVIEW

**Review by jecisc — APPROVED** [review]

**Comment by svenvc** [comment]
Not that I am against this change, but why ? What is the underlying reasoning ? Doing it like this will leave us with thousands of packages.

**Comment by astares** [comment]
Hi @svenvc,

why do you think so? It's a tagging/categorization only - no introduction of new packages!

We still have only the two packages "STON-Core" and "STON-Tests" as before but within
the package we have better grouping.

Bye
T.

**Comment by svenvc** [comment]
OK then.
But still I would like to have a heads up when you do this.
STON is managed externally so that older Pharo version can load the latest version too.
I was just working on merging changes back in, this makes it a lot harder.

**Comment by astares** [comment]
Sorry for that and thanks for reintegration. It is still hard to find out or remember which packages are externally and which ones are internally managed.

**Comment by MarcusDenker** [comment]
The whole "manage externally" is very very hard to work with... it is not clear what is external and what not, and then, how to actually contribute.

**Comment by astares** [comment]
Maybe (as a workaround) we should assembly an in-image list of the externally managed packages so that Iceberg can give a warning at least.

**Comment by svenvc** [comment]
What is the status of this PR ? 

Either it gets integrated or not.

I want to work on STON and I need a decision.

My main point is that I don't understand how this is a good change, as there are no clear rules for how to package things, apart from a couple of conventions. I am also not saying it is bad, but I could come up with another organisation that is equally acceptable. Given the ambiguity I feel it is up to the author (me) to organise its own code.

**Comment by guillep** [comment]
Well, not being personally attached for integrating or not, I have to say that @astares has been slowly doing this kind of re-organization to all other pharo packages. This gives at least some coherence in the system, and since it's him that took the effort to do it, the convention is enforced coherently. From that point of view, I vote for integrating this.

I'd prefer that we have some architectural rules testing this kind of things in the CI too, to make this conventions "harder".

Now, to avoid dragging this forever, unless there is some objection I'll integrate it later this afternoon.

**Pull request merged**
