### PR TITLE
Update Roassal to v1.06

### PR DESCRIPTION
**Pull request by jecisc**
## What's Changed
* Reimplement some explicitly required methods to speed up shapes by @jecisc in https://github.com/pharo-graphics/Roassal/pull/54
* Make RSAthensMorph apply the world renderer canvas scale factor by @Rinzwind in https://github.com/pharo-graphics/Roassal/pull/56
* Added .gitignore file and Removed DS_Store file by @jordanmontt in https://github.com/pharo-graphics/Roassal/pull/57
* Feature add relative y axis label values by @jordanmontt in https://github.com/pharo-graphics/Roassal/pull/58

## New Contributors
* @jecisc made their first contribution in https://github.com/pharo-graphics/Roassal/pull/54
* @jordanmontt made their first contribution in https://github.com/pharo-graphics/Roassal/pull/57

**Full Changelog**: https://github.com/pharo-graphics/Roassal/compare/v1.03...v1.06

### CODE REVIEW

**Review by jordanmontt — APPROVED** [review]

**Comment by MarcusDenker** [comment]
```
MetacelloNotification: Project: Tonel
MetacelloNotification: Project: LibGit
MetacelloNotification: Loaded -> BaselineOfLibGit --- unresolved
Instance of Protocol did not understand #isEmptyOrNil
Protocol(Object)>>doesNotUnderstand: #isEmptyOrNil
MCMethodDefinition>>initializeWithClassName:classIsMeta:selector:category:timeStamp:source:
MCMethodDefinition class>>className:classIsMeta:selector:category:timeStamp:source:
CompiledMethod>>basicAsMCMethodDefinition
CompiledMethod>>asMCMethodDefinition
```

**Comment by MarcusDenker** [comment]
very strange, this PR can not be the reason for the DNU (Protocol(Object)>>doesNotUnderstand: #isEmptyOrNil)

**Comment by jecisc** [comment]
Something seems weird because the build loads the package Roassal-Pharo that breaks Pharo 12 and seems to be the origin of the problem. But in the baseline it should be loaded only in Pharo 11. So I don't get why it is loaded here

**Comment by jecisc** [comment]
I think I found the problem but the baseline of roassal seems a little like a mess because it is redefining everything for each Pharo version instead of having a common base and adding some specificities on some Pharo versions

**Pull request merged**
