### PR TITLE
Switch to pharo-icon-pack v1.0.1-idea11

### LINKED ISSUE #8088: Fix small glitches in icons
1. in the standard icon set for "eclipse" and "famfam" theme the icon for Class ("C") and Traits ("T") are positioned to high
2. add an extra icon for abstract classes to all icon sets (still using the standard default icon for Class ("C") but combined with a small overlay "A") 

This was already fixed in 
 1. - https://github.com/pharo-project/pharo-icon-packs/commit/43363711121cf31907b2b6de779d49894a16a5c8 (eclipse)
     - https://github.com/pharo-project/pharo-icon-packs/commit/bbaf61e6402b949a12e94ae6fc9b0f259bbfbd9d (famfam)
 2. - https://github.com/pharo-project/pharo-icon-packs/commit/6e419bcc92d7852218b1f897e83708fa00fe8842 (eclipse)
     - https://github.com/pharo-project/pharo-icon-packs/commit/abda7146ca24ea0f61ee2062e3bcb2694535bbc0 (idea11)
     - https://github.com/pharo-project/pharo-icon-packs/commit/bbaf61e6402b949a12e94ae6fc9b0f259bbfbd9d (famfam)

and released as icon set fix release "v1.0.1-idea11". 

It also need to be activated for the bootstrap download process

### PR DESCRIPTION
**Pull request by astares**
Fix #8088

### CODE REVIEW

**Comment by Ducasse** [comment]
Good idea.

**Comment by astares** [comment]
CI Exceptions unrelated
(This **OupsDummyDebugger** seem to kick in now more regulary - we really need a more stable CI integration)

**Comment by StevenCostiou** [comment]
> CI Exceptions unrelated
> (This **OupsDummyDebugger** seem to kick in now more regulary - we really need a more stable CI integration)

I will look at this, this should not crash CIs... this class is not even a real class but used to test the debugger infrastructure.

**Comment by StevenCostiou** [comment]
> > CI Exceptions unrelated
> > (This **OupsDummyDebugger** seem to kick in now more regulary - we really need a more stable CI integration)
> 
> I will look at this, this should not crash CIs... this class is not even a real class but used to test the debugger infrastructure.

Ok, the Oups thing is a side effect of the debugger infrastructure, but this is not what seem to crash the CIs. Your working CI (the OSx one) also has the Oups errors. They are only due to the fact that exceptions  for which a debugger  cannot be found are dumped into the log instead of crashing the image. I need to fix this to avoid noise in the CI.

But in your crashing CIs the errors are a zero divide in `SessionErrorHandlingTest>>testErrorCaughtAndDefferedIfExceptionSignaledAtStartupWhenStartupUiManagerActive` (which might still be unrelated to your PR and is a horrible test case name).

**Comment by astares** [comment]
Thanks for checking - yes it is unrelated to the PR. CI in general is a little bit waggly but when I run

testErrorCaughtAndDefferedIfExceptionSignaledAtStartupWhenStartupUiManagerActive 

several time in the browser sometimes it's green and sometimes it crashes the VM on Windows.

**Comment by Ducasse** [comment]
May be we should open a bug entry for it because we want to increase the stability on Windows. Now our slaves are boring... We should really make sure that they crash less and this is why I think that we should clean the errors that are listed in the log to get a log clean bar.

**Comment by guillep** [comment]
All the conversation here around the issue is unrelated :) So I'll merge

**Pull request merged**
