### PR TITLE
ProtocolOrganizer cleanings

### PR DESCRIPTION
**Pull request by jecisc**
This does two things:
- Put code import specific methods in CodeImport package
- Inline some behavior of ProtocolOrganizer in ClassOrganization

This is madness:

```st
aClass organization protocolOrganizer hasProtocolNamed: aString	
```

I'm trying to make Demeter a little happier even if there are still work to do about that.

### CODE REVIEW

**Review by privat — APPROVED** [review]

**Comment by MarcusDenker** [comment]
And this will make it easier to merge ProtocolOrganizer and ClassOrganizer

**Comment by jecisc** [comment]
It's the end goal indeed :) 
Since changing the kernel is backfiring a lot on me recently, I'm trying to do tiny steps to not bring the wrath of the gods

**Comment by jecisc** [comment]
IceGitHubError: API rate limit exceeded for 128.93.193.1. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

Again :(

**Comment by jecisc** [comment]
Failures seems unrelated

**Pull request merged**
