### PR TITLE
merge-newtools-0.4.3

### PR DESCRIPTION
**Pull request by estebanlm**
https://github.com/pharo-spec/NewTools/releases/tag/v0.4.3

- remove all misleading settings.
- remove remaining access to `Smalltalk tools debugger`
- improvements on inspector nodes
- improvements on inspecting variables in a debugger
- add ranks to debugger to match what new Oups expects.
- add more inspector extensions
- bugfixes

### CODE REVIEW

**Comment by Ducasse** [comment]
super cool. 
Let us move on. 

S.

**Comment by astares** [comment]
Yes - super cool.  

Side note:
This PR provides hard coded classes in the code, for instance a reference to StDebuggerInspector in StDebugger:

```Smalltalk
inspector := self
		instantiate: StDebuggerInspector			             
                 ...
```
which could be improved as 

```Smalltalk
inspector := self
		instantiate: self debuggerInspectorClass			             
                 ...
```
with a method #debuggerInspectorClass returning the StDebuggerInspector class.

This would allow to subclass StDebugger and return / provide custom inspector class.

On some places this is already done (see defaultObjectInspectorClass)

**Comment by StevenCostiou** [comment]
> Side note:
> This PR provides hard coded classes in the code, for instance a reference to StDebuggerInspector in StDebugger:
> 
> ```smalltalk
> inspector := self
> 		instantiate: StDebuggerInspector			             
>                  ...
> ```
> 
> which could be improved as
> 
> ```smalltalk
> inspector := self
> 		instantiate: self debuggerInspectorClass			             
>                  ...
> ```
> 
> with a method #debuggerInspectorClass returning the StDebuggerInspector class.
> 
> This would allow to subclass StDebugger and return / provide custom inspector class.
> 
> On some places this is already done (see defaultObjectInspectorClass)

Please can you make a PR to https://github.com/pharo-spec/NewTools with those improvements?
Note that the debugger makes certain assumptions on its own inspector and that it would maybe not be immediate to just swap it with another one. This could also be improved later.


<blockquote><div> GitHub</div><div><strong><a href="https://github.com/pharo-spec/NewTools">pharo-spec/NewTools</a></strong></div><div>Contribute to pharo-spec/NewTools development by creating an account on GitHub.</div></blockquote>

**Comment by MarcusDenker** [comment]
There is only HiSpecExampleTest failing, I added an issue for that already as it times out *very* often

**Comment by estebanlm** [comment]
crashed on osx, but green on linux and windows. 
so I would say "on y va" :)

**Pull request merged**
