### PR TITLE
add-shortcut-printer

### PR DESCRIPTION
**Pull request by estebanlm**
adding a generic shortcut printer (needed to properly print menus for different platforms and backends).

### CODE REVIEW

**Comment by Ducasse** [comment]
esteban this is cool. Now having some tests would be nice too. 
Because one day we will break it.

**Comment by estebanlm** [comment]
not finished :)

**Comment by Ducasse** [comment]
:) but going to bed now :)

**Comment by estebanlm** [comment]
now is good to integration.

**Comment by Ducasse** [comment]
You see 
ToggleMenuItemShortcut >> color [

 	^ color ifNil: [ Smalltalk ui theme ghostTextColor ]
 ]

I think that this guy should either be a subclass of displayableObject. 
We should stop adding Smalltalk ui theme and other like that in the code.

**Comment by estebanlm** [comment]
you ask it, you have it

**Comment by Ducasse** [comment]
Ok cool now I do not understand why I still see 

ToggleMenuItemShortcut >> color [

 	^ color ifNil: [ Smalltalk ui theme ghostTextColor ]
 ]
It should probably be something like [self theme ghostTextColor] no?

**Comment by estebanlm** [comment]
is just that my network was failing and the push didn't arrive until a bit later.

**Comment by Ducasse** [comment]
oki

**Pull request merged**
