### PR TITLE
switch theme to white (Pharo 8.0 is a white themed release)

### PR DESCRIPTION
**Pull request by estebanlm**

### CODE REVIEW

**Comment by astares** [comment]
To explain more deeply the issue:

Pharo releases are alternating regarding the UI theme because there is no common sense which one people prefer. Therefore one time we use a dark theme - one time the light theme. 

For Pharo 7 we used the dark theme - so for Pharo 8 it is time to use the light theme again.

**Comment by guillep** [comment]
Hi guys, Pharo 7 **was** white themed, Pharo 6 was dark themed,
 => Pharo 8 became dark themed at the beginning of the cycle to be able to debug possible theme glitches.
 => Pharo 9 should be white themed...

Is this change good?

**Comment by Ducasse** [comment]
We can keep it black we will redo the videos for the mooc in white anyway.

**Comment by estebanlm** [comment]
in fact Guille is right. P8 was dark, not white.
Should we revert?

**Comment by Ducasse** [comment]
Go ahead. 
I would have been nice to a different one.

**Pull request merged**
