### PR TITLE
Added  rule and test to check for dead methods.

### PR DESCRIPTION
**Pull request by LionelAkue**
TODO: Replace #basicCheck by #forCritic:Do:

### CODE REVIEW

**Comment by MarcusDenker** [comment]
^ (aMethod senders isEmpty) and: [ aMethod messages isEmpty ].

No, I think what it should check is if there is at least one message in the messages:

Something like:

(aMethod senders isEmpty) and: [ aMethod messages anySatisfy: [:selector | selector implementors isEmpty ]].

**Comment by LionelAkue** [comment]
okay thanks.
Let me see

**Comment by LionelAkue** [comment]
(A little iceberg mess in the while)

**Comment by MarcusDenker** [comment]
I think this is somehow already integrated

**Comment by pavel-krivanek** [comment]
code integrated

**Pull request closed without merging**
