### PR TITLE
Fix for Wrong text selection: selection selects an extra character

### PR DESCRIPTION
**Pull request by hernanmd**
This PR handles #15408.

Here the duplicated find in source behavior is cleaned from Rubric, so we have one implementation based in Command avoiding multiple results as reported in the issue.
This PR introduces a Command which can be now found in the method editor in Calypso as follows:

- Select any text to find.
- Right click in the method editor
- Source code -> Method source with it

### CODE REVIEW

**Comment by Ducasse** [comment]
Why removing the functionality from RubEditor? I do not like it. 
The command should be as empty as possible and delegates as much as possible. 
In particular because we want to remove Cmd and only use Cm2.0.

**Comment by hernanmd** [comment]
> Why removing the functionality from RubEditor? I do not like it. The command should be as empty as possible and delegates as much as possible. In particular because we want to remove Cmd and only use Cm2.0.

Thanks for the feedback Stef. I tried to re-use the Commander 2 but there were lot of errors. Anyway, I will rework it so we can use 1 implementation instead of 3 (which differ for the same feature).

**Comment by Ducasse** [comment]
Yes thanks hernan. People do not get that duplication is evil.

**Review by jordanmontt — APPROVED** [review]
The code looks good. But I don't know too much about Calypso

**Review by jecisc — APPROVED** [review]

**Pull request merged**
