### PR TITLE
2708-Deprecate-subscribesendto

### PR DESCRIPTION
**Pull request by Ducasse**
Fixes: #2708  https://github.com/pharo-project/pharo/issues/2708
Deprecated and rewrote all users.

### CODE REVIEW

**Comment by svenvc** [comment]
Looks good (read the code changes, did not load them)

**Comment by Ducasse** [comment]
Cool only two broken tests and unrelated to the changes. I will wait for another review and push it.

**Comment by Ducasse** [comment]
To run again the tests.

**Comment by Ducasse** [comment]
Only spec window tests.

**Pull request merged**
