### PR TITLE
20781-update-to-iceberg-064

### PR DESCRIPTION
**Pull request by estebanlm**
closes issue #20781

### CODE REVIEW

**Comment by jecisc** [comment]
I see this error in the logs

```
[32] 	postload : baseline [BaselineOfIDE] >> postload:package:+ ./vm/pharo Pharo7.0-32bit-fca1702.image eval --save 'FFIMethodRegistry resetAll. PharoSourcesCondenser condenseNewSources'
[32] [31mError: MessageNotUnderstood: receiver of "finish" is nil
[32] [0mUndefinedObject(Object)>>error:
[32] [ :err :rcvr | 
[32] "Handle a drawing error"
[32] | errCtx errMorph |
[32] errCtx := thisContext.
```

Someone know what is the problem?

**Comment by estebanlm** [comment]
nope :(

**Comment by astares** [comment]
Nope. But we now show the welcome window again since this week. And maybe this is initialized by BaselineOfIDE. 

Maybe a drawing error there or return of font FT2 issue?

**Comment by MarcusDenker** [comment]
(Pavel told me ok to merge)

**Pull request merged**
