### PR TITLE
Improve ReBaselineProperlyPackagedRule and ReBaselineWithProperSuperclassRule and cover with tests

### LINKED ISSUE #16646: Improve ReBaselineProperlyPackagedRule and ReBaselineWithProperSuperclassRule and cover with tests
The two new rules for baselines (from PR #16633 and PR #16630) unfortunately have a small glitch: they lament on class side for correct baseline as this case needs to excluded in the #basicCheck: method.

Therefore we should also cover the two new rules with proper tests which was on my todo list anyway.

### PR DESCRIPTION
**Pull request by astares**
Fix #16646

### CODE REVIEW

**Comment by astares** [comment]
CI issue, Windows is green

**Comment by jecisc** [comment]
I think the CI failures are related.

```
[osx-64 / Tests-osx-64 / MacOSX64.System.Dependencies.Tests.SystemDependenciesTest.testExternalIDEDependencies](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16648/1/testReport/MacOSX64.System.Dependencies.Tests/SystemDependenciesTest/osx_64___Tests_osx_64___testExternalIDEDependencies/)
 Error Details

Given Collections do not match!  additions : #('BaselineOfPharo')  missing: #()
```

**Comment by astares** [comment]
Let me check. But why is it green on Windows then?

**Comment by astares** [comment]
@jecisc OK - now tests pass

**Comment by jecisc** [comment]
> Let me check. But why is it green on Windows then?

The window slave is currently down :/ It's hard to keep this one up

**Pull request merged**
