### PR TITLE
20519 Package OmbuTests should be Ombu-Tests

### PR DESCRIPTION
**Pull request by astares**
Renamed the package

### CODE REVIEW

**Comment by astares** [comment]
https://pharo.fogbugz.com/f/cases/20519/Package-OmbuTests-should-be-Ombu-Tests

**Comment by astares** [comment]
According to Pavel this need to be synched first in http://smalltalkhub.com/mc/MartinDias/Epicea/main/

**Comment by astares** [comment]
Wrote an email to Martin Dias on 25.10.2017 8pm to have a look at the case. So far no response.

**Comment by estebanlm** [comment]
similar to ZincTests issue. 
Retry later?

**Comment by tinchodias** [comment]
I'll check and sync with sthub... Is it easier if the project were in github? I'd like to move.

**Comment by jecisc** [comment]
@tinchodias Where are we about this issue?

**Comment by tinchodias** [comment]
I've created https://github.com/tinchodias/epicea and https://github.com/tinchodias/hiedra in tonel format. Now I have to ask how to proceed to integrate a PR with this code.

**Comment by tinchodias** [comment]
Do the files in this project care about where epicea code cames from? I mean, if epicea comes from sthub or github?

**Comment by tinchodias** [comment]
https://github.com/pharo-project/pharo/pull/1366

**Comment by tinchodias** [comment]
Maybe should reopen

**Comment by MarcusDenker** [comment]
I would not re-open. This is very old. Maybe even from before we moved to the new GIT format.

Just do a new one.

**Pull request closed without merging**
