### PR TITLE
Check matches of ReGlobalVariablesUsageRule against list of known globals

### LINKED ISSUE #6321: Ignore known globals when checking RBGlobalVariablesUsageRule
**Describe the request**
RBGlobalVariablesUsageRule treats known globals like `Smalltalk` and `Processor` as normal global variables. While `Smalltalk` could be replaced with `SmalltalkImage current` (which actually uses the global variable `Smalltalk`), there is no replacement for `Processor`.

I suggest to treat the following globals as known: 
- ActiveEvent
- ActiveHand
- ActiveWorld
- Display
- Processor
- Sensor
- Smalltalk
- SourceFiles
- SystemOrganization
- Transcript
- Undeclared
- World

**Expected behavior**
RBGlobalVariablesUsageRule should ignore matches of known globals.

**Expected development cost**
10 Minutes

### PR DESCRIPTION
**Pull request by theseion**
Fixes #6321

### CODE REVIEW

**Comment by MarcusDenker** [comment]
ReGlobalVariablesUsageRuleTest has failing tests that seem related

**Comment by theseion** [comment]
Thanks Marcus. I've updated the test case. The CI checks appear to be fine now.

**Comment by MarcusDenker** [comment]
Hmm... CI still looks strange. I close and re-open to merge with latest

**Comment by MarcusDenker** [comment]
There are still tests failing in ReGlobalVariableRuleTest

**Comment by MarcusDenker** [comment]
ReGlobalVariableRuleTest can just be removed 
- ReGlobalVariablesUsageRuleTest test the rule already
- the test here test just what you changed

**Comment by theseion** [comment]
Thanks Marcus, I'll look at it right now.

**Comment by theseion** [comment]
Looks good to me. Failures are all related to Zinc.

**Comment by MarcusDenker** [comment]
I still think it is good to merge this. yes, we need rules for most of these Globals that tells users to not use them. 

For now, the rule as it is in the image tells me multiple times per day that I am not allowed to use "Smalltalk image" or "Smalltalk compiler" and that makes me mad.

**Comment by MarcusDenker** [comment]
and because we waited, of course there is now a conflict

**Comment by theseion** [comment]
I'll update the PR to merge into the latest changes.

**Comment by theseion** [comment]
Merged with tip of Pharo9.0. I hope this does the trick.

**Comment by theseion** [comment]
Good to go.

**Pull request merged**
