### PR TITLE
Use more protocol object in RPackage

### PR DESCRIPTION
**Pull request by jecisc**
The main change of this PR is to use more real protocols instead of protocol name. But this also includes some cleanings such as dead code removal or variable renaming.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
failing tests look related

**Comment by jecisc** [comment]
I fixed a test. A second one still fails, I'll take a look later

**Comment by Ducasse** [comment]
Lot of tests are broken

**Comment by jecisc** [comment]
It's hard to track all implications of those changes so I'll probably extract one portion in another PR to wake it easier. 

RPackage is complex and it's not easy to unify things

**Comment by jecisc** [comment]
3 tests are still failing but it's way less than before :)

**Comment by jecisc** [comment]
Tests finally passed on this one :)

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
