### PR TITLE
Cleanup newlines and blanks in "Collection" packages

### LINKED ISSUE #10414: Cleanup newlines and blanks in "Collection" packages
see #10396 and fix it for all "Collection" related packages:

```Smalltalk
badCases := SystemNavigation default allMethodsSelect: [ :each | each sourceCode trimRight size ~= each sourceCode size ].

fixInPackage := badCases select: [:each | each package name beginsWith: 'Collection' ].

fixInPackage do: [:each |
	| refactoring |
	refactoring := RBAddMethodChange compile: each sourceCode trimRight in: each methodClass for: nil.				 
	refactoring execute	
]
```

### PR DESCRIPTION
**Pull request by astares**
Second attempt to Fix #10414 - now respecting the traits

### CODE REVIEW

**Review by kasperosterbye — APPROVED** [review]
Nice cleanup - I presume you ran a script to do this. Perhaps approving the script would have been easier :-)

**Comment by astares** [comment]
@kasperosterbye Original script and updated script had been included in the issue to solve. Just check #10414

**Comment by kasperosterbye** [comment]
Thanks, my bad!

**Comment by astares** [comment]
@kasperosterbye No - my fault. It was not that obvious - maybe better should have put it into the comments of the PR. 

Thanks for the approval!

**Comment by MarcusDenker** [comment]
- [CI] Failing randomly: StPlaygroundPageTest>>testContent (windows)
- [CI] Failing randomly: TestExecutionEnvironmentTest>>testIgnoreLongTestWhenItIsSuspendedAsUnderDebug #10459
- [CI] Failing randomly: SemaphoreTest>>testMutualExclusion #10469

**Pull request merged**
