### PR TITLE
deprecate taskbarIcon and systemIcon

### PR DESCRIPTION
**Pull request by estebanlm**
do not use taskbarIcon and systemIcon. Use taskbarIconName and systemIconName instead.

### CODE REVIEW

**Comment by Ducasse** [comment]
It would be nice to be able to get rid of this kind of code `Smalltalk tools fileList`

**Comment by estebanlm** [comment]
yes, eventually all those Smalltalk singletons needs to be move to the running application (StPharoApplication, in this case).
this will easy things, but still a lot of things to think and re-design :/

In any case, my next public enemy N. 1 is Object>>#iconNamed:, which is also a huge problem ;)

**Comment by Ducasse** [comment]
Before redesigning we could have a tools registry in StApplication and we can move all the `Smalltalk tools` to `self toolNamed:`.
I can do it if you want or we can take 1 hours per week and do some pair programming and do it. It can be fun.

**Comment by estebanlm** [comment]
no idea why that test is failing, it does not seems related with the change..

**Comment by Ducasse** [comment]
I agree that killing Object>>iconNamed: is good.

**Comment by MarcusDenker** [comment]
one failing test is a known failing test:

- [CI] Failing test: ProperMethodCategorizationTest>>testNoUncategorizedMethods #11669

but these are new and do not fail currently in Pharo11:

- SpMorphicBoxLayoutTest>>testClassIsDisplayedWithCorrectAlignment
- SpDemoTest>>testSmokeTestForDemoPages

**Comment by MarcusDenker** [comment]
for testSmokeTestForDemoPages this is a generic on: Error handler, we need to check what the real error is:

```
	on: Error
			do: [ :e | 
				self fail: 'Broken demo page: ' , demoPage asString , '

```

**Comment by MarcusDenker** [comment]
It seems both are due to the same problem:

- the rewrite in the deprecated method Object>>#systemIcon is missing a @:

```
	transformWith: '`@receiver systemIcon' -> '`@receiver iconNamed: `@receiver systemIconName'.
```

**Comment by MarcusDenker** [comment]
Just checked: tests are green after that, I will try to edit the PR directly

**Comment by estebanlm** [comment]
oops :)

**Comment by MarcusDenker** [comment]
Test look good now, but of course now the MacosX executor is down...

**Review by MarcusDenker — APPROVED** [review]

**Comment by estebanlm** [comment]
yes, that's exactly what I'm doing now :)
but moving things takes time too, so... slowly :(

**Pull request merged**
