### PR TITLE
22146-update-metacello-to-allow-alternate-filetree-formats

### PR DESCRIPTION
**Pull request by estebanlm**
https://pharo.manuscript.com/f/cases/22146/update-metacello-to-allow-alternate-filetree-formats

### CODE REVIEW

**Comment by jecisc** [comment]
It failed :(

```
You will need to log out and log back in for the limits to take effect.
For more information please see
https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/tag/r3732#linux
Error: Unknown repository type: github://pharo-vcs/tonel:v1.0.5
MCRepository class(Object)>>error:
[ self error: 'Unknown repository type: ' , aRepositorySpec description ] in MCRepository class>>newRepositoryFromSpec:on: in Block: [ self error: 'Unknown repository type: ' , aRepos...etc...
OrderedCollection(Collection)>>detect:ifFound:ifNone:
OrderedCollection(Collection)>>detect:ifNone:
MCRepository class>>newRepositoryFromSpec:on:
MetacelloPharo30Platform(MetacelloPlatform)>>creat
```

**Comment by estebanlm** [comment]
yeah, I forget some dependency (maybe tonel itself)

**Comment by jecisc** [comment]
I still see the same error.

**Comment by jecisc** [comment]
@estebanlm Maybe it also needs to be added here: https://github.com/pharo-project/pharo/blob/development/bootstrap/scripts/03-metacello-bootstrap/01-loadMetacello.st

**Comment by estebanlm** [comment]
green :)

**Pull request merged**
