### PR TITLE
New tools v0.5.1.1 advanced steps

### PR DESCRIPTION
**Pull request by StevenCostiou**
Advanced steps (experimental) from the debugger toolbar.
Also contains fixes that were not merged in NewTools v0.5.1

**Demos**
From an opened debugger, stepping until the execution calls a method in the current receiver (example with a visitor):

step-until-visitor-is-called

From an opened debugger, stepping until the execution creates a new object:

stepToNextInstanceCreation

More details: https://github.com/pharo-spec/NewTools/releases/tag/v0.5.1.1

### CODE REVIEW

**Comment by Ducasse** [comment]
Oh this is exciting and looks super nice. :)
I will tweet about these.

**Comment by Ducasse** [comment]
```
MetacelloNotification: Fetched -> NewTools-ObjectCentricBreakpoints-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-8303/64/src --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-8303/64/src
MetacelloNotification: Fetched -> NewTools-Sindarin-Commands-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-8303/64/src --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-8303/64/src
MetacelloNotification: ...RETRY->NewTools-Sindarin-Commands-Tests
MetacelloNotification: ...RETRY->NewTools-Sindarin-Commands-Tests
MetacelloNotification: ...FAILED->NewTools-Sindarin-Commands-Tests
Could not resolve: NewTools-Sindarin-Commands-Tests [NewTools-Sindarin-Commands-Tests] in /builds/workspace/uest_and_branch_Pipeline_PR-8303/64/bootstrap-cache/pharo-local/package-cache tonel:///builds/workspace/uest_and_branch_Pipeline_PR-8303/64/src
MetacelloFetchingMCSpecLoader(MetacelloCommonMCSpecLoader)>>retryingResolvePackageSpecReferences:gofer:
[ 
      | references nearestReference cachedReference externalReference mcVersion loadedVersionInfos |
      cach
```

**Comment by StevenCostiou** [comment]
> MetacelloNotification: ...RETRY->NewTools-Sindarin-Commands-Tests
> MetacelloNotification: ...RETRY->NewTools-Sindarin-Commands-Tests
> MetacelloNotification: ...FAILED->NewTools-Sindarin-Commands-Tests


Oops little mistake there, I will fix it...

**Comment by StevenCostiou** [comment]
Still wrong, need more work. I mixed up something when merging my NewTools changes into Pharo.

**Comment by StevenCostiou** [comment]
128 failing tests... this is going to be fun :)

**Comment by StevenCostiou** [comment]
Unrelated tests failing

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
