### PR TITLE
20215-Undo-in-Rubric-laves-a-part-of-autocompleted-keyword-message

### PR DESCRIPTION
**Pull request by nicolaihess**
use editors replace method, so it records an undo change.

https://pharo.fogbugz.com/f/cases/20215/Undo-in-Rubric-laves-a-part-of-autocompleted-keyword-message

### CODE REVIEW

**Comment by dionisiydk** [comment]
I not understand why diff shows so many changes. Looks like in most places left and right texts are same.

**Comment by jecisc** [comment]
@dionisiydk The original line endings are LF and here they are CRLF.

This is a bug in iceberg/tonel. 

Esteban proposed to correct the PR soon.

**Comment by estebanlm** [comment]
yes, I will... not time yet, sorry. 
I also want to fix the problem *in general*, for windows contributors.

**Comment by MarcusDenker** [comment]
can we fix this PR before?

I could redo one if I would know what the changes are

**Comment by estebanlm** [comment]
thing is dealing with windows line endings.
while I want to provide a generic fix for this on pharo (with a .gitattributes), I think regular workaround is to set a `core.autocrlf` property

**Comment by MarcusDenker** [comment]
But this PR itself is not about this?  Why would we not fix the issue independently?

**Review by MarcusDenker — APPROVED** [review]
yes, this behaviour is better

**Pull request merged**
