### PR TITLE
add Open as external window option

### PR DESCRIPTION
**Pull request by pavel-krivanek**
The main purpose is to reveal more bugs :-)

### CODE REVIEW

**Review by astares — APPROVED** [review]

**Comment by astares** [comment]
Nice one - thanks!

**Comment by estebanlm** [comment]
I am scared about this in P12.
I guess better to do it in P13 and have a full iteration to fix?

**Comment by jecisc** [comment]
I agree that it night be better in P13

**Comment by pavel-krivanek** [comment]
Yes, sure, P12 is frozen. But there is not yet Pharo13 branch available ;)

**Comment by jecisc** [comment]
Updating the base to P13 instead of P12

**Pull request merged**
