### PR TITLE
Another Smalltalk globals removal

### PR DESCRIPTION
**Pull request by Alisu**
This time in OpalCompiler and Monticello.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Breaks bootstrap

**Comment by MarcusDenker** [comment]
I would make sampler PRs. e.g. base rule: *never* mix a change in the compiler with any other change. Compiler changes are hard to get right.

**Comment by Alisu** [comment]
Indeed, i think i will revert the changes in the compiler.

**Comment by MarcusDenker** [comment]
I would not do any PR for this that changes two different packages at the same time.

**Review by CafeKrem — APPROVED** [review]

**Comment by Alisu** [comment]
Failure

**Pull request closed without merging**
