### PR TITLE
3663-Integrate-Spec-2

### LINKED ISSUE #3663: Integrate Spec 2
I will integrate Spec 2 update in Pharo. Changelog to come.

### PR DESCRIPTION
**Pull request by jecisc**
Integrate Spec 2.

Remove Spec-Tools and Spec-Inspector since they are now in Spec2.

Fixes #3663

### CODE REVIEW

**Comment by jecisc** [comment]
## Important changes

* ComposablePresenter is now named SpPresenter
*  Rename all classes to start with Sp and not conflict with Spec 1 ([a4e5b6f](https://github.com/pharo-spec/Spec/commit/a4e5b6f3181f59f90e66b10f8c175627b079c1d2))
*  Integrate Commander2 support  ([f2c53e9](https://github.com/pharo-spec/Spec/commit/f2c53e98db905e08f8cc4c69c2b766be2220462b))

## New Features

*  Add output port to Text presenter ([4db397b](https://github.com/pharo-spec/Spec/commit/4db397b02d171f8a8063da94754966409759029f))
*  The TablePresenter should have update in API ([c33998d](https://github.com/pharo-spec/Spec/commit/c33998d93a1b626c49fcd12905d9671755d6a6d3))

## Bug fixes

*  autoScale in ImagePresenter not changeable ([0cc50ae](https://github.com/pharo-spec/Spec/commit/0cc50aef16cdeaf08771ad74ac13732a2c34b6da))
*  TreeTableAdapter doesNotUnderstand UpdateMenu ([c02f97e](https://github.com/pharo-spec/Spec/commit/c02f97e0e0a9fa5bcfd72bcd6cdb65452650887a))
* Fix bugs in 

## Cleaning

* Remove a lot of useless extension methods
*  Proceed on layout migration ([db63ce9](https://github.com/pharo-spec/Spec/commit/db63ce91ef44d0bb61b7bab215751c2642675f42))
*  Remove extensions conflicts with Spec 1 ([736aa2e](https://github.com/pharo-spec/Spec/commit/736aa2e24ce480e748c975219f12d47c8cd102ef))
*  Some methods seems to comes from old widgets implementations ([323cfb6](https://github.com/pharo-spec/Spec/commit/323cfb6c2df7e2d97909b15ab8c9f824f9946506))
*  Remove centerWidget  company ([e7502c5](https://github.com/pharo-spec/Spec/commit/e7502c56a10c1ffd34a3f0a92a397d047b34f317))
*  Finish cleaning of modal  ([e71eb76](https://github.com/pharo-spec/Spec/commit/e71eb7656796b41ff823bb9ed80c8cb2796a451f))
*  Remove extensions methods that are now in Pharo 8 ([f2ae224](https://github.com/pharo-spec/Spec/commit/f2ae224eeb5f14b0e554048dd7d1ab188a18011e))
* Using currentWorld instead World ([8104f0e](https://github.com/pharo-spec/Spec/commit/8104f0ef4a73f233d4a850f1249a291a151dd449))
*  Cleanup comments and typos in Spec Examples ([cd244f1](https://github.com/pharo-spec/Spec/commit/cd244f1d36689675b2326c7d08f846ab6e82ff9b))
*  Fix typo MeruPresenter   MenuPresenter ([6d10928](https://github.com/pharo-spec/Spec/commit/6d10928a838e6431fe48bbd4e92534fc642d8833))
*  SpecSelectionsValueHolder and SpecSelectionValueHolder are not used ([4f2a286](https://github.com/pharo-spec/Spec/commit/4f2a286484a32d5cb8522ca31d6619efee7851ea))
* Transform value holders into observable slots ([39b9bc0](https://github.com/pharo-spec/Spec/commit/39b9bc0f045bcdbfd188fed857463315e6e9cdae))

**Comment by Ducasse** [comment]
Cyril the PR could be loaded because of 

[32] Loaded -> Tool-DependencyAnalyser-Tests-Data-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-3667/32/src --- cache
[32] Loaded -> Kernel-Rules-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-3667/32/src --- cacheError: This package depends on the following classes:
[32]   EyeInspector
[32] You must resolve these dependencies before you will be able to load these definitions: 
[32]   EyeInspector>>#selectedMessage
[32] 
[32] MCPackageLoader(Object)>>notify:
[32] MCPackageLoader>>warnAboutDependencies
[32] MCPackageLoader>>validate
[32] MCPackageLoader>>loadWithNameLike:
[32] MCVersionLoader>>basicLoadWithNameLike:

**Comment by jecisc** [comment]
Now there is one related failure. I’ll try to check it soon.

**Comment by jecisc** [comment]
Weird, the test pass in the image in the archived files... I'll relaunch.

**Comment by jecisc** [comment]
I cannot reproduce locally so I'll update the test to print a better log on failure.

**Comment by jecisc** [comment]
Error seems not related

**Comment by Ducasse** [comment]
***THANKS*** All tests are green.

**Pull request merged**
