### PR TITLE
Tests that CI handle properly Syntax Errors during tests

### PR DESCRIPTION
**Pull request by privat**
The best way to test the CI is to do a PR that runs the CI I assume :)

Cf https://github.com/pharo-project/pharo/pull/12778#issuecomment-1431549288

### CODE REVIEW

**Comment by privat** [comment]
It could be related to #12595

**Comment by privat** [comment]
CI broken as suspected.

**Comment by jecisc** [comment]
> It could be related to #12595

There is a PR for this issue: https://github.com/pharo-project/pharo/pull/12782

But I don’t see how this issue could product this effect on the CI?

**Comment by jecisc** [comment]
Is this still needed?

**Comment by privat** [comment]
Is the CI still broken? Let's see...

**Comment by privat** [comment]
CI still broken :(

**Comment by MarcusDenker** [comment]
What this PR does to test:


```
 testParseExpressionDontFreeze
 	"Force a parse error (from a simple tool class).
 	The image (and CI) should not freeze :)"
 	self parserClass parseExpression: '#'
```	

We would expect that this leads to a failing test. But instead, the image quits.	

Handling Syntax errors is a bit, uhm, arcane... what happens is that the exception in the end
calls #syntaxErrorNotificationDefaultAction: on the UIManager.

And the non-interactive UI manager (and CommandLineUIManager) explicitly exit:

```
syntaxErrorNotificationDefaultAction: aSyntaxErrorNotification

	"display and log the syntax error"
	super syntaxErrorNotificationDefaultAction: aSyntaxErrorNotification.

	"in noninteractive mode simply quit"
	^ self exitFailure
```


While DummyUIManager>>#syntaxErrorNotificationDefaultAction: does something more resonable:

```
syntaxErrorNotificationDefaultAction: anException
	self traceCr: '*** SYNTAX ERROR ***'.
	self traceCr: anException.
	self
		traceCr: (thisContext stack first: (20 min: thisContext stack size)).
	anException return
```


we should maybe not do the  "self exitFailure" for NonInteractive and CommandLine

(and we should get rid of this #syntaxErrorNotificationDefaultAction: alltogether...)

**Comment by privat** [comment]
A radical solution to the issue #12910 :)

**Comment by privat** [comment]
Thanks to #12910, the CI now behave nicely.

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
