### PR TITLE
Improving comment of class DebugSession

### PR DESCRIPTION
**Pull request by dupriezt**

### CODE REVIEW

**Comment by Ducasse** [comment]
Thanks.
Could you put Pharo code instead of Smalltalk code :).
And we push it into the system

**Comment by dupriezt** [comment]
*"Could you put Pharo code instead of Smalltalk code :)."*
@Ducasse I don't understand.

**Comment by estebanlm** [comment]
s/Smalltalk/Pharo/g

:)

**Review by estebanlm — CHANGES_REQUESTED** [review]
What Stef asks is to replace "Smalltalk" with "Pharo".
Then it will be ok :P

**Comment by dupriezt** [comment]
Ah ok. It is done now.
I also fixed a few typos while I was at it.

**Pull request merged**
