### PR TITLE
Fixing shared variable remove

### PR DESCRIPTION
**Pull request by Ducasse**
- Introduce removeSharedVariable driver and many other fixes.
- Add tests
- Improve RBCondition. 
- Next step remove one openBrowser: from RBCondition

### CODE REVIEW

**Comment by Ducasse** [comment]
I do not succeed to handle the conflict. 
I need help.

**Comment by Ducasse** [comment]
I cannot edit the files. 
I cannot check the PR because it removes the changes that were made. 
I cannot merge my changes into the current head and push to the same PR.

**Comment by jecisc** [comment]
I'll try to do it. It might take some times since I don't know the changes that were made

**Comment by jecisc** [comment]
I think I fixed the conflict. I hope I kept the good changes. 

RBRenameMethodDriver >> furtherActionFor: was using #runRefactoring two days ago and is now using #browse.

I kept #browse, I hope that was the good call to make :)

**Comment by jecisc** [comment]
There is one related failing test: osx-64 / Tests-osx-64 / testIsInstanceSide – MacOSX64.Refactoring.Tests.Core.RBClassTest

**Comment by Ducasse** [comment]
Ok it was good. I will check why the test is not passing but this is a new one just documenting better the API

**Pull request merged**
