### PR TITLE
Cleanup newlines and blanks in "STON" packages

### LINKED ISSUE #10905: Cleanup newlines and blanks in "STON" packages
see #10396 and fix it for all "STON" related packages:

```Smalltalk
badCases := SystemNavigation default allMethodsSelect: [ :each | each sourceCode trimRight size ~= each sourceCode size ].

fixInPackage := badCases select: [:each | each package name beginsWith: 'STON' ].

fixInPackage do: [:each |
	| refactoring classOrTrait |
	classOrTrait := each traitSource ifNil: [ each methodClass ] ifNotNil: [ each traitSource innerClass ].
	refactoring := RBAddMethodChange compile: each sourceCode trimRight in: classOrTrait for: nil.				 
	refactoring execute	
]
```

### PR DESCRIPTION
**Pull request by astares**
Fix #10905

### CODE REVIEW

**Comment by svenvc** [comment]
Please not again !

STON was finally in sync and now you are going to break it again, and why ?

Unless you make a PR for the upstream STON I am against it.

**Comment by astares** [comment]
@svenvc Should we stop or do we still want to move?  

Do not see your real problem. If it was in synch you can either merge back with git or apply the 
same script mentioned in https://github.com/pharo-project/pharo/issues/10905 also to your codebase. No?


And why did I break it already? Tests are green for this PR - at least locally:

image

**Comment by svenvc** [comment]
You have to agree than on the scale from useless to super useful, these kind of changes rank quite low.

With breaking I mean that you make my life (maintaining/comparing/merging) much harder for little gain.

All I am asking is that you make a PR to the upstream repo.

And yes, I admit it, I am not a hero managing changes between different git repos.

**Comment by astares** [comment]
Hi @svenvc 
Your ranking might be right - but every small step is a move and we should not let out the STON packages from https://github.com/pharo-project/pharo/issues/10396 

I know that no one of us is a hero in git (me neither) as it allows for many things. I also understand that you do not want to spend too much time picking changes to merge back. ´ 

Hope this one makes your life easier:  https://github.com/svenvc/ston/pull/32

**Comment by svenvc** [comment]
Thx, merged.

**Pull request merged**
