### PR TITLE
22134-Extract-Flashback-configuratuion-to-its-own-baseline

### PR DESCRIPTION
**Pull request by jecisc**
Extract Flashback to its baseline and add comments to Flashback packages.

https://pharo.fogbugz.com/f/cases/22134/Extract-Flashback-configuratuion-to-its-own-baseline

### CODE REVIEW

**Comment by MarcusDenker** [comment]
error not related

**Review by pavel-krivanek — APPROVED** [review]
fine, should be revalidated before merging to be sure it will not be in conflict with some previous bootstrap related PR

**Comment by MarcusDenker** [comment]
There is now a merge conflict

**Comment by jecisc** [comment]
Resolved.

**Comment by MarcusDenker** [comment]
failed with: missing workspace /builds/workspace/and_branch_Pipeline_PR-1537-4GZ335OT5GZJWM2OHVVQCNCPPTQF4KYUZQSRQGYXSK3W5KKRHRYA on pharo-ci-jenkins2-bootstrap-unix-2

Not related

**Pull request merged**
