### PR TITLE
Add Toplo world menu entry

### PR DESCRIPTION
**Pull request by tinchodias**

### CODE REVIEW

**Comment by tesonep** [comment]
Fix #16289

**Comment by tinchodias** [comment]
I just downloaded P12 via zeroconf and don't see the menu entry. After 6 hours. I have to wait more or it was reverted?

Build information: Pharo-12.0.0+SNAPSHOT.build.1474.sha.723e992378842828924aea037a6d2da975cd8da4 (64 Bit)

**Comment by Rinzwind** [comment]
It wasn’t reverted, but in the build that was triggered for the commit in which this pull request was merged ([build 1475](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo12/1475/)), the [‘Full Image-64’ stage](https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/Pharo12/1475/pipeline/25) failed due to issue #16443, and while the issue seems to have been fixed, there hasn’t been another build yet.

**Comment by Rinzwind** [comment]
It would have been nice if the change to Spec that seems to fix issue #16443 would have triggered a new build so that there would be an image with the changes of this pull request, I have opened an issue about that: issue #16452.

**Comment by Rinzwind** [comment]
@tinchodias: There are images for newer builds now. There’s no Toplo world menu item as far as I can tell though. The class BlLoadProjectWorldMenu seems to be missing methods with a `<worldMenu>` pragma.

**Comment by tinchodias** [comment]
@Rinzwind many thanks! Silly me, I forgot to include a method in the PR changes. Luckily I located the image where I worked that day and was able to push the missing method addition (PR #16478)

**Comment by Rinzwind** [comment]
Ah OK! I wasn’t quite sure whether the `<worldMenu>` pragma method was missing or whether the menu item was supposed to get added in some other way that I was not seeing.

I wanted to take a look because I was wondering whether the menu item would load a version including the world renderer canvas scale factor support and the Toplo demo browser which I added in [Bloc pull request #465](https://github.com/pharo-graphics/Bloc/pull/465) and [Toplo pull request #120](https://github.com/pharo-graphics/Toplo/pull/120).

**Comment by tinchodias** [comment]
@Rinzwind This menu entry loads the Pharo12 branch of Toplo, and we will take care it loads a reasonably good version of Toplo and Bloc, and should have a stable version that works well in Pharo 12 release and can update from time to time to a more recent version.

**Pull request merged**
