### PR TITLE
Fixing spotter error

### PR DESCRIPTION
**Pull request by tesonep**
- Fixing when the windows collection is empty
- Spotter should report all errors, removing all the machinery to do not presenting the errors.
If the error is not shown to the user, it is not possible to fix it.

### CODE REVIEW

**Review by guillep — APPROVED** [review]
ok! Looks like you want to keep your stats in code removal...

**Comment by guillep** [comment]
Let's wait for the CI

**Comment by tesonep** [comment]
> ok! Looks like you want to keep your stats in code removal...

Macheter!!!!

**Comment by guillep** [comment]
Tests passed. There is a fleaky test in fuel due to context serialization

```
  0x7fff53422210 I Context>copyStack 0x1141b2e38: a(n) Context
  0x7fff53422248 M [] in FLContextSerializationTest>testDoIt 0x113500990: a(n) FLContextSerializationTest
```

I'll lot a separate issue for that.
Thanks @tesonep !

**Comment by JurajKubelka** [comment]
What about creating another handler that pass all errors? And you could add a settings to change the default one. There is a good reason to suppress errors. Imagine that you load a buggy Spotter extension definition and you will not be able to use Spotter until you fix this particular extension. And I mean literally "not being able to use Spotter". Neither for searching classes, methods, or another Spotter extension to understand how to fix the broken one.

**Comment by JurajKubelka** [comment]
@guillep, @tesonep: Consider the above thought ^^^  Particularly if you believe there are users who do use Spotter and are not willing to spent an extra time on fixing tools while they need to work on their projects.

**Pull request merged**
