### PR TITLE
Deprecation Transform: add #flag at method start

### PR DESCRIPTION
**Pull request by MarcusDenker**
When a deprecation transforms code, it is not clear why the method changed. This PR adds a #flag call at the method start

### CODE REVIEW

**Comment by jecisc** [comment]
Hum... Maybe we should have a setting for this.

Personally, I love the automatic transformations but I would not like to commit methods with such a flag. And it will make me lose a lot of time to remove all the flag each time.

**Comment by jecisc** [comment]
Maybe an alternative would be to have a browser recording all automatic transformations in the current session and to open it (if it's not already opened) when a transformation happens.

**Comment by Ducasse** [comment]
Yes I agree with Cyril.

**Comment by MarcusDenker** [comment]
Ok

**Pull request closed without merging**
