### PR TITLE
Fix 9150-Right-click-is-broken-on-variables-in-the-Calypso-browser 

### PR DESCRIPTION
**Pull request by VincentBlondeau**

### CODE REVIEW

**Comment by Ducasse** [comment]
Thanks vincent. 
You fix is strange :)
I would not have expected it like that at all. 
To me this looks strange that something related to extract method is called on classvariables.

**Comment by Ducasse** [comment]
But I can reproduce it also on instance variables :(.

**Comment by Ducasse** [comment]
I confirm that your fix is correct. It fixes also instance var.

**Comment by VincentBlondeau** [comment]
The fix is just a revert of the old version like described in #9150

**Comment by Ducasse** [comment]
@Evelyn may be this will impact the extract Setup.

**Pull request merged**
