### PR TITLE
2790-standalone-Tool-Registry

### LINKED ISSUE #2786: Improve usability of the minimal image
We need some refactorings to be able to clearly use TelePharo on top of the minimal image

### LINKED ISSUE #2790: standalone Tool-Registry
The images that have no GUI but still have tools like the minimal image with the TelePharo need the ToolRegistry that is now part of Tool-Base package together with other UI dependent code. We need to make it as a standalone package

### PR DESCRIPTION
**Pull request by pavel-krivanek**
ToolRegistry in standalone Tool-Registry package

fixes #2790

### CODE REVIEW

**Comment by Ducasse** [comment]
Hi pavel 

this is cool. Now could we avoid 
        Smalltalk tools whenToolRegistered: [ worldState defaultWorldMenu ].
 	Smalltalk tools whenToolUnregistered: [ worldState defaultWorldMenu ].

We should not use Smalltalk and Smalltalk tools directly. 
This is evil.

**Comment by pavel-krivanek** [comment]
I agree but what is the current alternative?

**Comment by Ducasse** [comment]
May be add an instance variable and initialize it so that you have only one place?

**Comment by noha** [comment]
This is super. Fixes a big problem with TelePharo

**Pull request merged**
