### PR TITLE
22836-Update-to-iceberg-150

### PR DESCRIPTION
**Pull request by guillep**
Update to iceberg 1.5.1

# Documentation related

- issue 1094: Improve doc
- issue 1115: Update README.md

# New Features

- issue 1079: 1074-cannot-checkout-a-tag
- issue 1101: 1099-Gitlab-integration-should-manage-non-default-port  enhancement

# Non-feature enhancements and cleanups

- issue 1083: 1080-Update-to-Commander-v071
- issue 1098: Removed leftover halts  review

# Bug fixes

- issue 1105: Entering an issue in create a branch raises a DNU
- issue 1106: Moving a class between packages not properly catched bug easy
- issue 1104: pushTo: leads to error on some branches bug

### CODE REVIEW

**Comment by Ducasse** [comment]
Hi guille 

I wanted to integrate it but I saw: 
[32] ...RETRY->BaselineOfCommander
[32] ...RETRY->BaselineOfCommander
[32] ...FAILED->BaselineOfCommanderCould not resolve: BaselineOfCommander [BaselineOfCommander] in /builds/workspace/uest_and_branch_Pipeline_PR-2123/32/bootstrap-cache/pharo-local/package-cache github://pharo-ide/Commander:v0.7.1

**Comment by jecisc** [comment]
I found the problem and did a PR. https://github.com/pharo-vcs/iceberg/pull/1125

**Comment by Ducasse** [comment]
Thanks Cyril 
It still fails on 
[32] ...RETRY->BaselineOfCommander
[32] ...RETRY->BaselineOfCommander
[32] ...FAILED->BaselineOfCommanderCould not resolve: BaselineOfCommander [BaselineOfCommander] in /builds/workspace/uest_and_branch_Pipeline_PR-2123/32/bootstrap-cache/pharo-local/package-cache github://pharo-ide/Commander:v0.7.1
[32] MetacelloEnsureFetchingMCSpecLoader(MetacelloCommonMCSpecLoader)>>retryingResolvePackageSpecReferences:gofer:
[32] [ | references nearestReference cachedReference externalReference mcVersion loadedVersionInfos |

**Comment by guillep** [comment]
The problem is not yet solved, I'm working on it. Details of this (finally funny) issue in here if you want to follow:
https://github.com/pharo-vcs/iceberg/pull/1125

I'll soon post a solution, I've caught the bug.

**Comment by guillep** [comment]
Strange enough, most of the broken tests seem related to the changes in printOn: and not related to iceberg changes at all...

**Comment by Ducasse** [comment]
This is probably true and I may have introduced bugs stupidly.

**Comment by Ducasse** [comment]
I fixed the printString problem in https://github.com/pharo-project/pharo/pull/2131

**Pull request merged**
