### PR TITLE
Fixes-5260 - Add x64 tests run in the CI

### PR DESCRIPTION
**Pull request by VincentBlondeau**
See #5260 Add x64 tests run

### CODE REVIEW

**Comment by svenvc** [comment]
Sometimes even the simplest things might work, let's try.

**Comment by VincentBlondeau** [comment]
It is not working since I do not have right accesses on the repo. Someone of the project should do it. Or integrate with eyes closed ;)

See https://support.cloudbees.com/hc/en-us/articles/227246367-Why-Jenkinsfile-changes-Are-Not-Reflected-in-PR-Build

<blockquote><div>CloudBees Support</div><div><strong><a href="http://support.cloudbees.com/hc/en-us/articles/227246367-Why-Jenkinsfile-changes-Are-Not-Reflected-in-PR-Build">Why Jenkinsfile changes Are Not Reflected in PR Build</a></strong></div><div>Issue


When a user modify the Jenkinsfile and opens a PR, the build does not take the changes into account


Console logs shows one of the following depending on the GitHub Branch Source plugin ve...</div></blockquote>

**Comment by guillep** [comment]
I'll try to give you access :)

**Comment by guillep** [comment]
Bof, I've tried to change jenkins settings, but apparently it cannot be done that way.
I've further seen https://support.cloudbees.com/hc/en-us/articles/227246367-Why-Jenkinsfile-changes-Are-Not-Reflected-in-PR-Build. So this can only be added by giving push requests on the repo...

Two things:
 - I'll try to take ownership of this PR if this does not bother you, like that the JenkinsFile changes are taken into account...
 - What if we only run tests for 64 bits? It should be the default platform for most people (outside still existing 32bit arm machines). Because otherwise this will multiply the test-running by 2 demanding twice as slaves/resources, making the build slower and less reliable...

What do you think?
I invoke also @estebanlm @tesonep so they can give their opinion.

<blockquote><div>CloudBees Support</div><div><strong><a href="http://support.cloudbees.com/hc/en-us/articles/227246367-Why-Jenkinsfile-changes-Are-Not-Reflected-in-PR-Build">Why Jenkinsfile changes Are Not Reflected in PR Build</a></strong></div><div>Issue


When a user modify the Jenkinsfile and opens a PR, the build does not take the changes into account


Console logs shows one of the following depending on the GitHub Branch Source plugin ve...</div></blockquote>

**Comment by VincentBlondeau** [comment]
You can take ownership of PR. I just care about running the x64 tests. And I thank that running the x32 ones could be nice to compare if the x64 fails.

**Comment by guillep** [comment]
Work continued in #5268 . Let's continue the discussion there.

**Pull request closed without merging**
