### PR TITLE
Updated Fuel (and users of Fuel) to 5.0.4

### LINKED ISSUE #10318: Use Fuel 5
Fuel 4.0.0 was released, we should update the build to use it

```
Short-list of the most interesting things:

builder API
support for talents and anonymous classes
support for FullBlockClosure
full serialization support by default (no more need to load FuelMetalevel to serialize classes and methods)
full serialization support for Squeak
The complete release notes are over on GitHub: https://theseion.github.io/Fuel/releases/4.0.0/.

We hope that you'll like what we've done and we're excited to see, what kind of magic you will do with it.
If you are using Fuel in a project, please let us know and we'll add it to the list of projects on GitHub (good for us and you ;)).

As always, please report any issues to https://github.com/theseion/Fuel/issues and we'll try to help you out.
```

### PR DESCRIPTION
**Pull request by theseion**
Also opened PR's for [NewTools](https://github.com/pharo-spec/NewTools/pull/357) and [Roassal3](https://github.com/ObjectProfile/Roassal3/pull/439).

### CODE REVIEW

**Comment by MarcusDenker** [comment]
sadly now the CI is in a strange state. Maybe it is time to start Easter holidays...

**Comment by theseion** [comment]
I would ;)

**Comment by theseion** [comment]
Updated to 5.0.3

**Comment by MarcusDenker** [comment]
Failing tests (on all platforms, I copy the Linux ones):
```
 testSerializeContextToFileNamed – Unix64.NewTools.Debugger.Fuel.Tests.FLDebuggerStackSerializerTest

 testSerializeStackFromContext – Unix64.NewTools.Debugger.Fuel.Tests.FLDebuggerStackSerializerTest

 testNoUnusedClassVariablesLeft – Unix64.ReleaseTests.CleanCode.NoUnusedVariablesLeftTest

 testNoUnusedInstanceVariablesLeft – Unix64.ReleaseTests.CleanCode.NoUnusedVariablesLeftTest

 testNoUnusedTemporaryVariablesLeft – Unix64.ReleaseTests.CleanCode.NoUnusedVariablesLeftTest

 testLocalMethodsOfTheClassShouldNotBeRepeatedInItsTraits – Unix64.ReleaseTests.Release.ReleaseTest

 testWriteToFile – Unix64.Roassal3.Global.Tests.Shapes.RSMonitorEventsTest

 testExternalBasicToolsDependencies – Unix64.System.DependenciesTests.SystemDependenciesTest

 testExternalMorphicDependencies – Unix64.System.DependenciesTests.SystemDependenciesTest

 testExternalSpec2Dependencies – Unix64.System.DependenciesTests.SystemDependenciesTest

 testExternalUIDependencies – Unix64.System.DependenciesTests.SystemDependenciesTest

 testCreateStrategiesForParentClass – Unix64.SystemCommands.ClassCommands.Tests.SycRemoveClassStrategyTest

 testCreateStrategiesForReferencedClass – Unix64.SystemCommands.ClassCommands.Tests.SycRemoveClassStrategyTest

 testCreateStrategiesForRemovableClass – Unix64.SystemCommands.ClassCommands.Tests.SycRemoveClassStrategyTest

 testCreateStrategiesForUsedTrait – Unix64.SystemCommands.ClassCommands.Tests.SycRemoveClassStrategyTest

```

**Comment by theseion** [comment]
Thanks. I always forget those release an dependency tests...

**Comment by theseion** [comment]
Rebased onto Pharo11, fixed lint issues, updated ReleaseTest and SystemDependenciesTest.

The failures in `SycRemoveClassStrategyTest` aren't my fault, AFAICT.

The failures in `RSMonitorEventsTest` and `FLDebuggerStackSerializerTest` have already been addressed in separate PRs to NewTools and Roassal.

**Comment by MarcusDenker** [comment]
I will check the SycRemoveClassStrategyTest problem

**Comment by MarcusDenker** [comment]
Strangely, the SycRemoveClassStrategyTest is green in the downloaded release artefact

**Comment by MarcusDenker** [comment]
```
KeyNotFound
key #ClassForTestToBeDeleted1 not found in SystemDictionary
SystemDictionary(Dictionary)>>errorKeyNotFound:
[self errorKeyNotFound: key] in SystemDictionary(Dictionary)>>at:
SystemDictionary(Dictionary)>>at:ifAbsent:
SystemDictionary(Dictionary)>>at:
[ :title | self environment at: title ] in SystemOrganizer>>orderedTraitsIn:
Array(SequenceableCollection)>>collect:
SystemOrganizer>>orderedTraitsIn:
SystemOrganizer>>removeSystemCategory:
[:c | self removeSystemCategory: c] in SystemOrganizer>>removeCategoriesMatching:
Array(SequenceableCollection)>>do:
SystemOrganizer>>removeCategoriesMatching:
ClassFactoryForTestCase>>deletePackage
ClassFactoryForTestCase>>cleanUp
SycRemoveClassStrategyTest>>tearDown

```

I think what happens:

ClassFactoryForTestCase>>#deleteClasses should call #deleteClasses

deleteClasses now calls #delete:, but that does not remove the class from createdClasses


I will make another PR for that

**Comment by theseion** [comment]
I think there's a different issue. The classes are cleaned up properly (even without your fix). After `#delete:` has finished, the category will already have been removed from the organisation. Still, in `#orderedTraitsIn:` at least one class exists in the category that the factory uses. This suggests to me that some other test has not properly cleaned up its classes _and_ uses the same category.

**Comment by theseion** [comment]
And of course... the culprit is probably Fuel... 😭 Let me fix that.

**Comment by theseion** [comment]
Good news: it's not my fault :)
Bad news: suspending the `SystemAnnouncer` causes the issue, e.g., in `ClassFactoryForTestCase`:

```smalltalk
newClass
	SystemAnnouncer uniqueInstance suspendAllWhile: [
		^ self
			  newSubclassOf: self defaultSuperclass
			  instanceVariableNames: ''
			  classVariableNames: '' ]
```

My guess is that the `SystemAnnouncer` is suspended because the image runs headless.

**Comment by MarcusDenker** [comment]
One idea could be to harden SystemOrganizer>>removeSystemCategory: to be ok to remove categories that contain names of classes that do not exist anymore in the environment. (it removes the category after all, so it does not care if it is bad).

But then, this is more a workaround than a fix.

**Comment by theseion** [comment]
Ok, I think I fixed it (my earlier comment was wrong). The issue is that `ClassFactoryForTestCase` interacts with `SystemOrganization`. Fuel, however, uses its own implementation of `ClassFactoryForTestCase` that uses a custom environment, so the global SystemDictionary does not get polluted. That has worked really well but I hadn't considered that registration and cleanup of classes still runs through the global `SystemOrganization`. Hence, after Fuel tests have run, `SystemOrganization` will be polluted with those classes.

I've now implemented proper cleanup on the Fuel side. Sorry for the mess.

**Comment by theseion** [comment]
Looks like it worked! :)

**Comment by MarcusDenker** [comment]
Wow! Great! I merge this and then the other PRs of the external projects

**Pull request merged**
