### PR TITLE
[WIP] 12082 finder UI should be rewritten using spec2

### PR DESCRIPTION
**Pull request by n1toxyz**
This my first start for rewriting the Finder tool in Spec2.

At first I wanted to just port the FinderUI class to Spec2, but noticed that the old Finder model didn't seem to fit into
the Spec2 programming style. It is imho complicated and not very extensible.
So I began to create a new model and separate the searches into their own classes as well. With the new model you can even add new searches to a running Finder instance and creating a new search is done by simply subclassing FinderSearch and implementing 3 methods.
Additional I use Announcements to notify FinderPresenter of changes from the model. This is important as the search is
done in its own subprocess.

I am still not quite done and not all searches are implemented yet. However, I am interested in feedback. Is this so far to your liking or do you think I am going in the wrong direction? Please let me know as I am still new to Spec2 und
contributing :)

The old Finder is not changed or deleted yet. I plan to replace the Finder class with one of the same name but as a subclass of SpApplication.

You can try the new Finder by running the following code, once loaded: `(FinderPresenter on: FinderModel new) open`

### CODE REVIEW

**Comment by Ducasse** [comment]
Thanks this is cool!
I'm working on the Spec 20 book and learning a lot :).

Could you rename FinderPresenter into StFinderPresenter because we are trying to have all the tools starting with St. I'm sure that Hernan @hernanmd will have a look :). Monday I hope to get some free time to have a look.

**Comment by Ducasse** [comment]
I'm thinking how we could share changes and progress. I do not know if we are able to push to your PR. 
May be we could have a separate package in a separate project and when we are happy we push it to Pharo.

**Comment by n1toxyz** [comment]
> Could you rename FinderPresenter into StFinderPresenter because we are trying to have all the tools starting with St. 

Of course I can rename the class. Will do that for the next PR. I assume  that the naming then applies to the support classes too.

I forgot to mention a bug, which I can't seem to pinpoint. but the first search performed doesn't seem to be displayed by the SpTreePresenter. The nesting just doesn't show up. All further searches work though.

> May be we could have a separate package in a separate project and when we are happy we push it to Pharo.

I don't quite know what you mean. Should I create a new git repository? How would this work. I am not that familiar with git workflows yet.

**Comment by Ducasse** [comment]
About the support classes we do not have a convention. The convention I know is for Presenter.

About the workflow. 
When we have a potentially long PR were several people can help this is difficult (if not impossible to be several to push to the PR). Since Spec20 is not updated regularly/systematically. 
I think that it will be easier for you if you create one git project with one package and people can do PR to this project. Once it is ready then we can do a PR to Pharo to push the package into Spec. 
I worked like that for the DocumentBrowser with Kasper in http://github.com/pharo-spec/

**Comment by n1toxyz** [comment]
So I created a new repository for the development of [NewTools-Finder](https://github.com/n1toxyz/NewTools-Finder).
I renamed the classes too. Now they beginn with with _St_. For consistency I decided to rename all the classes in this way.
Additionally I added a baseline, but I need some help with that. I just don't know yet how this works yet.

**Comment by hernanmd** [comment]
> So I created a new repository for the development of [NewTools-Finder](https://github.com/n1toxyz/NewTools-Finder). I renamed the classes too. Now they beginn with with _St_. For consistency I decided to rename all the classes in this way. Additionally I added a baseline, but I need some help with that. I just don't know yet how this works yet.

I think there is a typo in your baseline: method.

```smalltalk
baseline: spec
	<baseline>

	spec for: #common do: [
		spec
			package: #'NewTool-Finder';
			package: #'NewTool-Finder-Tests' with: [ spec requires: #( #'NewTool-Finder' ) ] ]
```

According to your repository it should be NewTool**s**-Finder instead of NewTool.

**Comment by n1toxyz** [comment]
> I think there is a typo in your baseline: method.

Thanks for reporting. Fixed the typo.

I also added the two missing finder widget classes which I forgot to add yesterday.

**Comment by Ducasse** [comment]
Thanks I feel bad not having more cycle for this. 
My life is a bit tough in this moment and I hope to get more time in the future. 
In any case what you are doing is cool.

**Comment by n1toxyz** [comment]
Don't worry. I am not able to work as much on it as I want to too. This weekend I am probably not going to have any time do expand on this, but we will get there.

**Comment by guillep** [comment]
This is a super job @n1toxyz !!

Would you mind adding in the description of the PR a bullet list of things that are required to move this PR from WIP to ready state? That would give some visibility on its *readiness*, and maybe other community members could jump in to help

**Comment by n1toxyz** [comment]
Hi @guillep, that is a good idea. I added a first todo list to the README of the project. I will list it here nonetheless. Contributions are welcome.

The tool is already usable, but does not implement all kinds of searches of the old Finder tool yet.

- [ ] Implement missing searches as subclasses of StFinderSearch, e.g. `StFinderExampleSearch`
- [ ] Implement tests!!! Right now there are none...
- [ ] Improve GUI. Ideas welcome!
  - provide more information about the search environment (how many packages are selected, etc), e.g. by adding an StatusBar
  - explore ways to display results in a better way
- [ ] Check baseline for missing dependencies

**Comment by jordanmontt** [comment]
Nice work :)
And yes, I agree this will be easier to review in a separated repo.

And when it will be ready, I think it will be better to integrate this to NewTools instead of Pharo

**Comment by Ducasse** [comment]
Yes once ready we should mobe it to NewTools
I will see if this afternoon I have a bit of time to look at it.

**Comment by jordanmontt** [comment]
I can help you reviewing it if you like

**Comment by n1toxyz** [comment]
Thanks for looking at it. I am happy for any feedback. I didn't have much time the last weeks and will be busy this weekend too, but hope to get a lot more done afterwards. However I noticed yesterday when implementing the Pragma search, that it was more or less broken in the current Finder as some buttons result in exceptions when clicked und others not performing the correct action.

At the same time I find the current layout and the layout of my rework a bit slow in regards to the UI/UX and I myself am using mostly the Spotter to find stuff. I think however that the Finder has some advantages/potential which the Spotter is not going to fullfill, like displaying/finding results related to each other. 

Thats why I have been looking around at other Finder tools in other IDEs for some ideas, but ultimately I want to do a little survey in the mailinglist to get an idea how or if people are using the Finder, what features do they like and what gets on their nerves and most importantly what are they missing?

Otherwise, I think, we are wasting potential. I can for example think about adding an additional search for repositories and commits, which lets you easily find changes or a simple calculator by evaluating math expressions in the search bar. I cant to get rid of the button bar at the bottom and have these options displayed in a context menu on right clicking the desired result. Additional the standard keybindings should also work as expected (Ctrl+b for browse, etc...).
This way we are more flexible in regards to the actions we can perform on the results, which will benefit other types of searches.

But I am going to stop rambling for now. I have some ideas but I have to bring them to paper first in a structured fashion and maybe do some wireframing.

**Comment by Ducasse** [comment]
:)

I would say, make it, release it, iterate :)

**Comment by jordanmontt** [comment]
It is good that you are thinking on how to improve the Finder! Like Stéphane said, I will also say that to first make it work and then we can iterate. When you will have the time, moving the code to a separated repo and maybe documented a little will help us review it and help with the things that are not working as expected

**Comment by Ducasse** [comment]
I could not load the baseline (but I do not get why it is not working) so I loaded the packages manually

**Comment by Ducasse** [comment]
When I do 
```
StFinderPresenter new open
```
I get a DNU

**Comment by Ducasse** [comment]
When I load the tests package it is empty and I do not know if this is normal.

**Comment by Ducasse** [comment]
I will do some PRs. 
I will try to see how I can add example based search because this is one that is really important to me.

**Comment by Ducasse** [comment]
This is the way to open it

```
open 
	<script>
	
	(self on: StFinderModel new) open
```

**Comment by Ducasse** [comment]
Oops it looks like I pushed directly the repo. Sorry about it.

**Comment by n1toxyz** [comment]
> I would say, make it, release it, iterate :)

Yes, I will focus for now on shipping a Spec2 version of the old Finder with its bugs fixed. That way it can be merged and is already available.

> I could not load the baseline (but I do not get why it is not working) so I loaded the packages manually

Sadly I don't understand baselines myself yet, but yes it needs fixing.

> When I load the tests package it is empty and I do not know if this is normal.

Yes, it is empty for now. I just created it for future tests, but have not implemented any yet. In some cases
I am not sure how to implement tests for searching yet. I plan to use a minimal environment (1 package) and search
in it for things like selectors and then compare the results with results gotten manually through reflection.

@Ducasse Thanks for your work. I merged the changes. I planned from the beginning to eventually implement a class named StFinder which subclasses SpApplication and which will provide the tools to the presenter and model, but haven't done it yet as I still lack a bit of understanding how to correctly use SpApplication and wanted to focus on the core functionality first.

> I will try to see how I can add example based search because this is one that is really important to me.

This is the last missing piece. Afterwards it is mostly wrapping things up, polishing and testing, but all the functionality of the old Finder should be implemented by then.

**Comment by Ducasse** [comment]
I have the impression that we should just open stFinder via the StApplication. 
StApplication should be the application for the Pharo tools so no need to subclass it. 
If there are behavior missing we can extend StApplication. 
I guess that there is a tools management or something like that.

**Comment by jecisc** [comment]
The application holds things like:
- The theme to use
- The icon set
- The backend to use
- ...

It should not be hard to use it for a new tool

**Comment by Ducasse** [comment]
Now we should show the result in a text pane too. We should probably use a SpCodePresenter with beForMethod:

**Comment by n1toxyz** [comment]
> StApplication should be the application for the Pharo tools so no need to subclass it.

I didn't know about that. But makes sense when the other tools are started from there too.

The result pane is missing, you are right. I thought we can implement this as a vertical split next to the result tree, instead of opening below the buttons at the bottom, but this might be to small for a code listing. I will test this.

**Comment by n1toxyz** [comment]
Has moved to the [NewTools](https://github.com/pharo-spec/NewTools/pull/656#event-11521085736) repository.

**Pull request closed without merging**
