### PR TITLE
Rule to check class side #reset methods are in 'class initialization' protocol

### PR DESCRIPTION
**Pull request by gypsydave5**
Relating to #2607, this is a start on writing a Renraku rule. I'd like some feedback and advice!

### CODE REVIEW

**Comment by gypsydave5** [comment]
I've just added an automated fix for this rule

**Comment by MarcusDenker** [comment]
One failing test: testAndMakeSureSuperTearDownIsCalledAsLastMessageInTearDownMethodsOfTestCases (missing "super tearDown"

**Comment by gypsydave5** [comment]
Bah - I remember thinking about that. Thanks Marcus!

**Comment by gypsydave5** [comment]
@MarcusDenker - just a qq - what tests should I be running locally so that I don't do this again?

**Comment by MarcusDenker** [comment]
We need to add an easy way to run a subset of tests, e.g. by adding a button to the git commit UI.

**Review by MarcusDenker — APPROVED** [review]
ok

For the instance side, #reset can have many meanings, but class side it is good to have it in a defined category.

**Review by guillep — APPROVED** [review]
Good

**Pull request merged**
