### PR TITLE
Cleanup: Remove <- from collection

### LINKED ISSUE #16185: Cleanup: Remove <- from collection
There is a method called #<- implemented in Collection
- it just has a single sender in AdditionalMethodState class>>#propertiesToPersist (the other two are tests for it) 
- and AdditionalMethodState class>>#propertiesToPersist could be more easily written using #asSet

We should deprecate and remove it.

### PR DESCRIPTION
**Pull request by astares**
Fix #16185

### CODE REVIEW

**Comment by jecisc** [comment]
This was a new feature implemented in P12 IIRC

**Comment by astares** [comment]
Feature for what? Confusing people?

**Comment by jecisc** [comment]
To be able to write code such as `Set <- #(1 2 3)`

**Comment by jecisc** [comment]
Originally Stephane wanted to have something like `{ :Set 1 . 2 . 3 }` but some people prefer not to change Pharo's parser and proposed this alternative

**Comment by astares** [comment]
> To be able to write code such as `Set <- #(1 2 3)`

What about:    Set withAll: #(1 2 3) ?

**Comment by Ducasse** [comment]
The problem is that withAll: is a keyword so you have to put () all over the place. This is why I like {:Set 1 . 2 . 3} in the first place. At least it was fun to implement.

**Pull request closed without merging**
