### PR TITLE
Iss 4161 less trancript hardcoded references

### LINKED ISSUE #4161: Less Transcript hardcoded references
(SystemNavigation default allGlobalRefsOn: #Transcript) 
	reject: [ :each | each package name = #Kernel ]

>>> 118 cases and many are not good.

### PR DESCRIPTION
**Pull request by GeraldineGalindo**
Addition to fixes https://github.com/pharo-project/pharo/issues/4161

### CODE REVIEW

**Comment by Ducasse** [comment]
Geraldine I suggest to do smaller PRs like that we can really make a differences. 
Some of your changes are obvious and good while some others could be expressed differently or we need to take the time to think.

**Comment by GeraldineGalindo** [comment]
Thanks for the observation! I will review my changes, the tests and try to do them more separately.

**Comment by Ducasse** [comment]
I will integrate it

**Comment by GeraldineGalindo** [comment]
Good night, thanks a lot for the message, I reviewed it and I am deeply
sorry for the confusion, I had closed the pull request months ago and
because of personal reasons I was not able to work on them again but some
tests were failing and the suggestion was to implement changes in different
pull requests. I will close the pull request again.

Best regards and thanks once more.
Geraldine Galindo.

**Comment by Ducasse** [comment]
But I review it and it is good.
I closed and reopened it to relaunch the build

**Comment by Ducasse** [comment]
I will check your changes and run the tests locally to understand because we want less Transcript show.

**Comment by Ducasse** [comment]
Pablo this is strange because I thought that we fix the broken tests. 
I think that we should redo it calmly.

**Comment by Ducasse** [comment]
we should retry later because the refactoring tests are not that good.

**Pull request closed without merging**
