### PR TITLE
Creates Graphical UI for AndreasProfiler and TimeProfiler

### PR DESCRIPTION
**Pull request by carolahp**
Creating a graphical user interface to profile code using both AndreasProfiler and TimeProfiler.
Fixes [issue #10260 Integrate Profiler improvements](https://github.com/pharo-project/pharo/issues/10260)

### CODE REVIEW

**Comment by MarcusDenker** [comment]
failing test not related:

- #skipOnPharoCITestingEnvironment seems to not work on WIN and MAC #11425

**Comment by astares** [comment]
@Ducasse / @MarcusDenker / @carolahp 

Why has it been merged into Pharo 10 and not Pharo 11 branch and why without a review ??? 
P10 (as already released) should be closed for new features and only available for backported fixes

**Comment by carolahp** [comment]
@astares we think this new feature is useful and has no impact on other parts of the system. 
I will do a PR for Pharo 11 too

**Comment by astares** [comment]
@carolahp it was merged into souce but is not part of the new image after build as new package(s)  have not been included in baseline

**Comment by fmqa** [comment]
fwiw it does not work :(
`ProfilerTreeTablePresenter class >> adapterName` references `#ProfilerTreeTableAdapter` which does not exist in the Pharo10 tree or objectspace. I assume this should be `#SpMorphicProfilerTreeTableAdapter`.

**Comment by Ducasse** [comment]
Thanks for the report. Can you open a bug entry because like that we will follow it and fix it.

**Comment by fmqa** [comment]
@Ducasse Tracked as #11611

**Pull request merged**
