### PR TITLE
Use #includesBehavior: instead of testing manually for class identity…

### PR DESCRIPTION
**Pull request by gcotelli**
… or inheritance

### CODE REVIEW

**Comment by jecisc** [comment]
Not for this PR but maybe we could have a lint rule to detect such cases and add a release test checking the rule is not violated in the image.

**Review by jecisc — APPROVED** [review]

**Comment by MarcusDenker** [comment]
there are failing tests. they might be related

**Comment by MarcusDenker** [comment]
testSingleTraitCreation
testAnnouncement

**Comment by gcotelli** [comment]
I will take a look at the failing tests

**Comment by gcotelli** [comment]
@MarcusDenker @jecisc I reviewed the failing tests, the problem it's with the `isKindOf:` change, the previous version considered a Trait as a valid argument instead of a class. In this specific case the problem is in `SystemDictionary>>#fillCaches` because with the new code traits are not included anymore in the `classNames` cache so `traitNames` is not responding with the proper trait names.

I can see two options here:
1. Revert the `isKindOf:` change , and in that case add a comment explaining that it can work with classes or traits. But it will remain inconsistent with the `includesBehavior: ` semantics IMHO, because traits are treated different.
2. Change `SystemDictionary>>#traitNames` to respond with the proper result and this will fix the failing tests.

I will wait for your input on how to proceed.

**Comment by MarcusDenker** [comment]
I would do first 1). Because this way we already have a lot of of the way.

Then we do 2) in as a new issue. Because it is a bit more complex and we need to think about it a bit.
(the nice thing is that we actually do not need the name cache in dictionary anymore...)

**Comment by gcotelli** [comment]
@MarcusDenker I've reverted this specific change and created #3958 for discussion.

**Comment by MarcusDenker** [comment]
good! I will merge when the tests show that everything is good.

**Pull request merged**
