### PR TITLE
WIP: ContextSimplifyExecutedPC

### PR DESCRIPTION
**Pull request by MarcusDenker**
Experiment to use the same logic in #executedPC as we use in  #pcRangeContextIsActive:

- use #endPC for dead context as in #pcRangeContextIsActive:

### CODE REVIEW

**Comment by guillep** [comment]
Can we not push experimental code to the main branch?

**Comment by MarcusDenker** [comment]
I want to check if the tests are green, I added "WIP" to the title.

**Comment by MarcusDenker** [comment]
(but in general I prefer to do small changes that then everyone uses and we see fast if they are wrong instead of doing 20 of these just in my own image and then later merge them all at once...)

**Comment by guillep** [comment]
Sure, but we should avoid integrating immature things.
Moreover, this PR does not add a test for the change, so it's difficult to see its effect.

**Comment by MarcusDenker** [comment]
The nice thing is that we have already tests... and what I want is to check that nothing changes. So writing a test that fails before but is green is kind of hard...

But in the end: yes, I should setup another CI for this.

**Comment by Ducasse** [comment]
may be we could have a ci for the branches under dev.

**Comment by estebanlm** [comment]
there is already a CI for that.
1) all PRs will build an image artefact.
2) all branches under pharo-project/pharo will be built.

The only difference is *where* you get the image if you want to work taking that into account.
(you take it from "artefacts" on Jenkins)

**Comment by Ducasse** [comment]
I do not get it. But if during 3 months we work on PR, it will always be in the PRs list and we will see it constantly.

**Comment by estebanlm** [comment]
Yes... and sometimes is what you want. 
You may prefix them with WIP marking that is not finish (which reminds me I need to make mergeable the one on calypso). 
If you do not want to appear as PR, you work in a branch (under pharo-project/pharo), which is the point 2 of what I described (of course, not many people can do that, just the most trusted developers). 

In both cases you will have an artefact to work on as a result.

**Comment by Ducasse** [comment]
Ok I did not know the story about the branch

**Comment by MarcusDenker** [comment]
Nice thing: it's green and I will do a cleanup PR later based on this. I close this.

**Pull request closed without merging**
