### PR TITLE
22658-Better-manage-encoding-of-environment-variables

### PR DESCRIPTION
**Pull request by guillep**
Enhance management of encoding of environment.
 - common API manages encoding automatically by the system
 - *nix provides raw* and *encoding:* versions that allow getting the raw bytes and to provide an encoding

Issue: https://pharo.fogbugz.com/f/cases/22658/Better-manage-encoding-of-environment-variables

### CODE REVIEW

**Comment by dionisiydk** [comment]
getEnv selector maybe sounds not nice. But it allows really simple queries to find all OS var accessors. With #at: message it will be quite difficult to do.
Can we avoid general collection API?

**Comment by guillep** [comment]
Actually, getEnv: and at: both existed from before. But they were at different levels. From usages and the internal implementation it seems that the public API was the collection like, and getEnv was the private low level API.

I personally prefer the collection-like one. I don't find it confusing. It will only pose problems of detecting usages, but that's the same with whatever piece of smalltalk code following smalltalk conventions...

**Comment by dionisiydk** [comment]
I don't mean confusion. But for this case we really work with special dictionary. So you are right, it is ok. 

From the first look I thought It is a case when object exposes internal dictionary access with such methods. But it is a dictionary by itself.

References to class should give enough information because users will always access this "natural" singleton

**Comment by pavel-krivanek** [comment]
DependenciesTests are failing

**Comment by guillep** [comment]
Test failure not related

unix-32 / Tests-unix-32 / testInitializeBlockSetsTextSelectionForTextPresentation – Unix32.Glamour.Tests.Rubric.GLMRubricTextMorphicTest

**Pull request merged**
