### PR TITLE
Added coverage highlighting in DrTest

### PR DESCRIPTION
**Pull request by CarolinaMelendez**
Added coverage highlighting in the coverage plugin of DrTest. It shows covered lines, uncovered lines and partially covered lines highlighted with green, red and yellow colors.

highlightingCoveragePluguin

About the implementation it is a little long but in summarize: I created 2 subClases of the Coverage Package (of coverageCollector and CoverageResult ) to return the list of partially covered method and not to erase the atribute of "executed". 

The hard part is in the subClass DTCoveragePluginPresenter. Where I added the panel that displays the lines covered by colors. And I left an short description of its function of the new methods created in the comment section.

### CODE REVIEW

**Comment by astares** [comment]
Really cool addition! Adding this to the regular browser would be nice too.

**Comment by Ducasse** [comment]
Really cool! I will integrate it and we should continue to improve DrTests and remove the old test runner browser.

**Comment by Ducasse** [comment]
@CarolinaMelendez what are the next steps? Because we should check how to use package TestRunner - not loaded in Pharo but in the pharo repo (this is not UI) but a runner that we should use to run the tests.

**Review by astares — APPROVED** [review]
Looks good

**Comment by astares** [comment]
Tests green but Windows did not run

image

Anyone able to retrigger the CI?

**Comment by Gabriel-Darbord** [comment]
> Tests green but Windows did not run

@astares This is a current known issue with the CI, this shouldn't be blocking this PR.

**Review by jecisc — APPROVED** [review]

**Comment by jecisc** [comment]
Really nice feature :3

**Comment by CarolinaMelendez** [comment]
Thank you for your time and the code review.

**Comment by CarolinaMelendez** [comment]
@Ducasse  Thanks for the interest, I am currently in the Gsoc program.And I am still planning to add some features to DrTest. Like grouping by classes in the results panel. Also add a Mutation Testing Plugin (Which is the second half of my project).

About you second comment, I didn't quite understand what you mean. I'm not really working on TestRunner in particular but in the coverage plugin. I am focused on completing my Gsoc program but will be a pleasure to give a little help if it is needed

**Comment by Ducasse** [comment]
If you check in the Pharo repository there is an extra package that contains a TestRunner (not ui) but model. This testrunner is a missing abstraction in SUnit. By configuring this TestRunner you can for example shuffle the tests before executing them. 
So one idea is to check this runner and see how we can use it inside DrTest.

In DrTests it would be good to be able to rerun the failing-tests.

**Comment by lopezca** [comment]
Killer feature!
Please backport to pharo 11!

**Pull request merged**
