### PR TITLE
6595-SpDemoTest-should-close-the-open-windows

### LINKED ISSUE #6595: SpDemoTest should close the open windows
**Describe the problem**
If the test fails for timeout reasons, the window IV is not set and the window is not closed

**Classes involved**
SpDemoTest 

**Proposal**
Use the presenter IV to close the window

**Version information:**
Latest

**Expected development cost**
done

### PR DESCRIPTION
**Pull request by VincentBlondeau**
Fix #6595

### CODE REVIEW

**Comment by Ducasse** [comment]
I was about to integrate it but none of the tests run. So I'm pretty sure that this is not related to the fix but I will rekick them.

**Comment by VincentBlondeau** [comment]
Weird error on the CI:
```
 ./pharo Pharo.image test --junit-xml-output --stage-name=Tests-osx-64 '.*'
bootstrap/scripts/runTests.sh: line 38: ./pharo: No such file or directory
```
It seems that the vm was not able to be downloaded..

And other slaves have crashed too...

**Comment by VincentBlondeau** [comment]
2 issues on the CI:
- OSX: wget is not in the PATH of the slave. But it is installed on the server when logging is as the ci user.
The right path should be added to the jenkins slave agent. I do not know how to do that properly.
- Unix + Windows: the build takes more than 35 mins to run so fall into timeout. We could increase the timeout period but I'm not sure that is what we would like.

@demarey Any specific thought?

**Comment by MarcusDenker** [comment]
It seems the slaves work again. I started the run

**Comment by MarcusDenker** [comment]
Now they Fail all again. This is strange

**Comment by estebanlm** [comment]
hey @VincentBlondeau 
can this fixes be pushed to [Spec](http://github.com/pharo-spec/Spec) ?
Otherwise I have to make a very expensive merge to not lose it when I integrate next release of Spec.

**Comment by VincentBlondeau** [comment]
Hey @estebanlm !
Sure will do!
Thanks!

**Comment by MarcusDenker** [comment]
do we merge it here, too?

**Comment by guillep** [comment]
> do we merge it here, too?

@estebanlm ?

Or do we wait until your next spec integration?

**Comment by Ducasse** [comment]
ping?

**Comment by MarcusDenker** [comment]
No answer on simple things means I can decide. And I merge it.

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
