### PR TITLE
Fixed mc writing

### PR DESCRIPTION
**Pull request by guillep**
- extend CrPortableWriteStream to provide the line ending convention
- use a binary stream to write mc zip file

### CODE REVIEW

**Comment by svenvc** [comment]
All good and well, but you can't keep changing the Zn* classes, I can't keep up, because I have to get these changes back upstream and make sure everything works for older pharo versions (which you did not take into account)

If I don't do this, nobody can load Zn in pharo 7, because all your additions are then removed

**Comment by guillep** [comment]
But Zn is already in Pharo 7! And that is the core of the problem.
This is a problem with any so called *external project* that is included in Pharo.
And it is worse with *Zinc-Character-Encoding-Core* because that package in particular is now really tightly coupled with Pharo (because encoding is something required in many places...).
We are even removing the old encoding stuff...

I understand this is complicated to manage. It would be easier if one automatically mirrors the other, but that would either remove the freedom of changing the one in the Zinc repository or complicate the build of Pharo.

Either way, being positive, what could be a satisfactory solution?

 - Acknowledge the fact that Pharo7 is still on development and maybe Seaside may not work on every commit/until a stable release is announced? This will remove pressure on keeping Zinc up to date.

 - Not touching Zinc-Character-Encoding-Core is a no go... What I could do is to publish a new version of the package into Zinc repository too, so it is available in bleeding edge. But this could become complicated when touching many packages from different projects at the same time.

 - Move the ZnCrPortableWriteStream to another package that is not under the Zinc Umbrella?
That class has nothing to do with encoding in general after all... (you'll have to commit to zinc in any case the class removal...)

 - A more radical version of the one above: move Zinc-Character-Encoding-Core entirely as part of Pharo? This is the only Zinc related package that is in the bootstrap (see https://github.com/pharo-project/pharo/blob/development/src/BaselineOfPharoBootstrap/BaselineOfPharoBootstrap.class.st)
 
 - Update seaside to not load Zinc-Character-Encoding-Core on Pharo 7?

And again, where I say "Zinc*" let's read also "GT*", "Calypso*"...

**Comment by svenvc** [comment]
I just want you (1) to tell me when you make a change to Zn* packages [ right now, I just have to find out even if I follow all ML ] and (2) not make arbitrary changes like the one here [ you were fixing a bug, not need to fix style in another package ]

It would be even better that (3) any change to Zn should be portable back to Pharo 3 [ yes that is heavy, but people depend on Zinc for HTTP, a lot ]

Anyway, I want to stay positive, I am right now trying fix everything upstream, but it is a lot of work, we'll see where we get

**Comment by guillep** [comment]
I reverted my commit to only include for this one the change that has nothing to do with Zn*.

The other change was not style/arbitrary, it's a bug in src/MonticelloFileTree-Core/MCFileTreeAbstractStWriter.class.st that I found in filetree writing. My bad I wanted to publish both in a single commit. I'll open another issue and see what is the best solution there.

I'll keep you updated about Zn changes.

**Comment by svenvc** [comment]
OK, thanks

Look OK to me

**Comment by jecisc** [comment]
The portability of Zinc is really welcolmed. We still load the stable zinc in Pharo 4 at Synectique to get encoding detection.

**Pull request merged**
