### PR TITLE
Migrating RBRenamePackage into Refactoring2

### PR DESCRIPTION
**Pull request by miguelcamp**
Using a composite transformation since RBCopyPackage will be composite and this will preserve the same hierarchy

### CODE REVIEW

**Comment by demarey** [comment]
Class comments are missing.
Could you add them? Else, it looks ok for me.

**Comment by miguelcamp** [comment]
I have added the missing class comments. Sorry about the delayed response

**Comment by Ducasse** [comment]
Thanks!

**Comment by demarey** [comment]
Thanks Miguel

**Pull request merged**
