### PR TITLE
6755-Integrate-Roassal3

### LINKED ISSUE #6755: Integrate Roassal3
```
Metacello new
    baseline: 'Roassal3';
    repository: 'github://ObjectProfile/Roassal3:v0.9.1';
    load: #( 'Core' 'Tests').
```

since 

```
Metacello new
    baseline: 'Roassal3';
    repository: 'github://ObjectProfile/Roassal3:v0.9.1';
    load: 'Core'.
```

does not load the tests

### PR DESCRIPTION
**Pull request by Ducasse**
fixes: #6755 Include roassal30 0.9.2  'Core' 'Tests'

### CODE REVIEW

**Comment by Ducasse** [comment]
https://github.com/ObjectProfile/Roassal3/issues/275

**Comment by tesonep** [comment]
Hi, @akevalion 

These tests are failing, they are validations of the quality of the code, please check what it is missing.

- This test is failing because there are unused temporaries left. Please check them.
 
NoUnusedTemporaryVariablesLeftTest >> #testNoUnusedTemporaryVariablesLeft

- These tests are failing because there are invalid categorized methods

ProperMethodCategorizationTest >> #testCopyMethodNeedsToBeInCopyingProtocol
ProperMethodCategorizationTest >> #testHashMethodNeedsToBeInComparingProtocol
ProperMethodCategorizationTest >> #testPostCopyMethodNeedsToBeInCopyingProtocol
ProperMethodCategorizationTest >> #testSetUpMethodInSUnitTestsNeedsToBeInRunningProtocol

- Check that there are some #setUp message not calling super as first operation.
ProperlyImplementedSUnitClassesTest >> #testAndMakeSureSuperSetupIsCalledAsFirstMessageInSetupMethodsOfTestCases

- Methods from traits are duplicated and not marked as should be implemented.
ReleaseTest >> #testExplicitRequirementMethodsShouldBeImplementedInTheirUsers
ReleaseTest >> #testLocalMethodsOfTheClassShouldNotBeRepeatedInItsTraits

- There are initialization to nil of instance variables
ReleaseTest >> #testNoNilAssignmentInInitializeMethod

- Missing help in a world menu option.
ReleaseTest >> #testWorldMenuHasHelpForAllEntries

- There are settings without default values, or the default value does not match with the real one in the image. 
SystemSettingsPersistenceTest >> #testDefaultImageDoesNotStoreAnySetting

**Comment by akevalion** [comment]
Hi @tesonep I will update roassal keeping in mind this tests

**Comment by Ducasse** [comment]
Thanks!

**Comment by akevalion** [comment]
Hi @tesonep I have changed Roassal3 considering your commend.

https://github.com/ObjectProfile/Roassal3/commit/8a9eaa67d09f1b8dccdedf9a0f114b83a896ada8

Also I have create pull requests to fix:

- `testHashMethodNeedsToBeInComparingProtocol` in https://github.com/pharo-contributions/Geometry/pull/2

- `testNoUnusedTemporaryVariablesLeft` in https://github.com/pharo-contributions/Athens-SVG/pull/3

**Comment by tesonep** [comment]
I have pushed a new commit targeting the commit in roassal that @akevalion has done.
If this works, we can make a release of Roassal and point there.

**Comment by tesonep** [comment]
@akevalion I tried with the commit you added and there is a problem with a #hash method not in "comparing" category
Check the test ProperMethodCategorizationTest>>testHashMethodNeedsToBeInComparingProtocol

**Comment by akevalion** [comment]
> @akevalion I tried with the commit you added and there is a problem with a #hash method not in "comparing" category
> Check the test ProperMethodCategorizationTest>>testHashMethodNeedsToBeInComparingProtocol

That is related to the pull request for this repository:

- testHashMethodNeedsToBeInComparingProtocol in pharo-contributions/Geometry#2
- and testNoUnusedTemporaryVariablesLeft in pharo-contributions/Athens-SVG#3

Should I talk with someone in order to have these PRs accepted?

**Comment by Ducasse** [comment]
Can you issue PRs to such projects? this way I will see if I can integrate them.

**Comment by akevalion** [comment]
I have created issues for that pull requests in each repository
Geometry
Athens-SVG

Cheers

**Comment by akevalion** [comment]
Athens-SVG has accepted my pull request.

Now wait for Geometry

**Comment by Ducasse** [comment]
May be you should ping norbert.

**Comment by akevalion** [comment]
@tesonep Norbert has accepted the Pull request for Geometry!

**Comment by tesonep** [comment]
I have updated the baseline, if it goes we can go for the release of Roassal

**Comment by tesonep** [comment]
Ok @akevalion, can you do a release so we can point to the release and see how to follow. 
Thanks

**Pull request merged**
