### PR TITLE
Cleanup MockWithComplexSlot in Kernel-Tests

### LINKED ISSUE #8287: Cleanup MockWithComplexSlot in Kernel-Tests
- add accessor so ivar is not unused
- add class comment

### PR DESCRIPTION
**Pull request by astares**
Fix #8287

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Bootstrap fails with:

MessageNotUnderstood: RGUnknownSlot>>asExportedLiteral
RGUnknownSlot(Object)>>doesNotUnderstand: #asExportedLiteral

**Comment by astares** [comment]
Can you retrigger the CI - the change is in accessor addition in a kernel test package. I doubt this change has broken the Bootstrap.

**Comment by MarcusDenker** [comment]
same effect

**Comment by astares** [comment]
Strange. Maybe @guillep has an idea about the failing bootstrap.

**Comment by MarcusDenker** [comment]
I think it has to do with the problem that the Slot that the class uses is not defined in the Kernel.
This leads Ring to model it using RGUnknownSlot, which is missing the  #asExportedLiteral methods.

**Comment by astares** [comment]
@MarcusDenker but how did it work before? The slot is not changed ...

**Comment by guillep** [comment]
The entire stack, to really understand the error is:

```
MessageNotUnderstood: RGUnknownSlot>>asExportedLiteral
RGUnknownSlot(Object)>>doesNotUnderstand: #asExportedLiteral
HEAssociation>>value:
HEAssociation class(HEExportedLiteral class)>>for:
Association>>asExportedLiteral
[ :e | e asExportedLiteral ] in HEMethod>>fillLiteralsAndBytecode: in Block: [ :e | e asExportedLiteral ]
Array(SequenceableCollection)>>collect:
HEMethod>>fillLiteralsAndBytecode:
HERing2ToHermesBuilder>>visitMethod:
RGMethod>>acceptVisitor:
[ :e | e acceptVisitor: self ] in HERing2ToHermesBuilder>>visitMethodContainer:using: in Block: [ :e | e acceptVisitor: self ]
Array(SequenceableCollection)>>collect:
HERing2ToHermesBuilder>>visitMethodContainer:using:
HERing2ToHermesBuilder>>visitClass:
RGClassStrategy>>acceptVisitor:
RGBehavior(RGBehaviorStrategyUser)>>acceptVisitor:
[ :e | aHEPackage addClass: (e acceptVisitor: self) ] in HERing2ToHermesBuilder>>visitPackage: in Block: [ :e | aHEPackage addClass: (e acceptVisitor: self...etc...
Array(SequenceableCollection)>>do:
HERing2ToHermesBuilder>>visitPackage:
[ :packageName | 
oldPackage := ringEnvironment ask packageNamed: packageName.
hePackage := HERing2ToHermesBuilder new visitPackage: oldPackage.
writer := HEBinaryReaderWriter new
	stream:
		(File
			openForWriteFileNamed: (self bootstrapCacheDirectory / packageName , 'hermes') fullName);
	yourself.
hePackage writeInto: writer.
writer flush.
writer close ] in PBBootstrap>>generateHermesFiles in Block: [ :packageName | ...
Array(SequenceableCollection)>>do:
PBBootstrap>>generateHermesFiles
PBBootstrap>>prepareBootstrap
PBBootstrap>>bootstrap
UndefinedObject>>DoIt
OpalCompiler>>evaluate
DoItChunk>>importFor:logSource:
[ :declaration | 
requestor ifNotNil: [ requestor contents: declaration contents ].
value := declaration importFor: requestor logSource: logSource ] in CodeImporter>>evaluate in Block: [ :declaration | ...
OrderedCollection>>do:
CodeImporter>>evaluate
[ codeImporter evaluate ] in STCommandLineHandler>>installSourceFile: in Block: [ codeImporter evaluate ]
2021-01-07T09:39:36.94436+01:00 PBStepStartedSignal Starting  Process.
script returned exit code 1
```

My guess is that `MockWithComplexSlot` had a slot that was actually unused.
Adding the method in this PR makes the slot to be used, and that exercises a path that was never tested nor intended to work so far: serializing methods using slots. Notice this breaks when serializing the methods, and not loading them. This means this package is not in the bootstrap, but it is meant to be loaded in the binary loading step that follows just after the bootstrap where slots are not yet ready.

I think we should not support arbitrary slots in the boostrap, they should be loadable on top of a simple kernel. So a solution should be to move this class and the associated tests to a slot related package.

**Comment by MarcusDenker** [comment]
I close this for now: I have added MockWithComplexSlot to the exceptions for the release test of unused methods.

(the issue related to this PR of course stays open)

**Pull request closed without merging**
