### PR TITLE
Make finalization registry entry removal O(1)

### PR DESCRIPTION
**Pull request by guillep**
Turn the finalization registry into a double-linked list.
This turns removal into an O(1) operation while making ephemeron objects a bit bigger (2 inst vars for previous and next).

### CODE REVIEW

**Comment by guillep** [comment]
Using Ephemerons as a linked lists unveiled a problem in the scavenger. There is an upcoming fix in https://github.com/pharo-project/pharo-vm/pull/668

**Comment by jecisc** [comment]
```
Instance of FinalizationRegistry did not understand #keys
FinalizationRegistry(Object)>>doesNotUnderstand: #keys
File class>>retryWithGC:until:forFileNamed:
File class>>deleteFile:
File>>delete
HDTestReport>>openProgressStream
HDTestReport>>setUp
[ 
			self setUp.
			suiteTime := [ self runAll ]
```

**Comment by jecisc** [comment]
```
UndeclaredVariableRead: Attempt to read undeclared variable ephemeronCollection
UndeclaredVariable>>runtimeUndeclaredRead
FinalizationRegistry>>keys
File class>>retryWithGC:until:forFileNamed:
File class>>deleteFile:
File>>delete
HDTestReport>>openProgressStream
HDTestReport>>setUp
[ 
			self setUp.
			suiteTime := [ self runAll ]
```

**Comment by jecisc** [comment]
We are down to 2 failing tests which is nice!

testWeakSubscriptionRelease – MacOSX64.Announcements.Core.Tests.Tests.WeakAnnouncerTest10s
testFinalizationOfMultipleResources – MacOSX64.Kernel.Tests.Finalization.ObjectFinalizerTest

**Comment by guillep** [comment]
Related Tests are fixed, two tests remain but are unrelated.

- testDoBrowseMethodReferences breaks due to a blocking dialog
- testTraitWithClassTraitCompositionHasTraitComposition is flaky

**Pull request merged**
