### PR TITLE
Cleanup on The package TestRunner

### PR DESCRIPTION
**Pull request by aboubacardiawara**
The cleanup concerns the following point:
- category
- code formating
- classes reference

### CODE REVIEW

**Comment by MarcusDenker** [comment]
failing tests not related

**Comment by estebanlm** [comment]
I like it, but I would do two steps : 
1. integrate
2. remove old TestRunner
3. rename NewTestRunner, NewCommandLineRunner classes to just TestRunner and CommandLineRunner.

**Review by estebanlm — APPROVED** [review]

**Comment by estebanlm** [comment]
also: CommandLineRunner needs to be renamed to  CommandLineTestRunner
and we need an UI

and now that I see, names are messed up since TestRunner is the current name of the UI (and your NewTestRunner is an executor).

**Review by estebanlm — CHANGES_REQUESTED** [review]
we need to align names and API a little bit :)

**Comment by Ducasse** [comment]
This is cool that you review this.

**Comment by aboubacardiawara** [comment]
Thanks for your review. I will apply your suggested changes.

**Comment by Ducasse** [comment]
I'm trying to find the code but I do not find it in the image in the latest P11.

**Comment by aboubacardiawara** [comment]
> I'm trying to find the code but I do not find it in the image in the latest P11.

It can be found after cloning the Pharo project again in a loaded image. Before that I couldn't find it either

**Comment by Ducasse** [comment]
Thanks!

**Pull request merged**
