### PR TITLE
Revert "5443-Reading-out-of-range-Float-exponents-is-inconsistent"

### PR DESCRIPTION
**Pull request by MarcusDenker**
Reverts pharo-project/pharo#5444

### CODE REVIEW

**Comment by Ducasse** [comment]
I can find how I can switch branch to 9.0.

**Comment by Ducasse** [comment]
I found it, this is in edit. We have a conflict

**Comment by MarcusDenker** [comment]
But this "revert" PR is for Pharo8?

**Comment by MarcusDenker** [comment]
I close the revert and redo in Pharo9 (we keep the change for Pharo8)

**Pull request closed without merging**
