### PR TITLE
Protocol for all class side methods `#reset` changed to `initialization`

### LINKED ISSUE #2607: #reset methods should be in 'initialization' protocol and a test should ensure we do not have regression
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/20683
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 13 November 2017 1:33:33 pm
	
Description:
	
First we should correct and integrate the subcases. 

We should add a test/rule to ensure #reset methods are in 'initialization' by convention. 

See : http://forum.world.st/Convention-for-quot-reset-quot-methods-td5019493.html

### PR DESCRIPTION
**Pull request by gypsydave5**
starts to fix #2607, at least for this repo.

Should finally add the test when all of the other repos are fixed.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Failing tests not related, open issue for the failing tests:

- https://github.com/pharo-project/pharo/pull/10000
- https://github.com/pharo-project/pharo/issues/9996
- https://github.com/pharo-project/pharo/issues/9995

**Comment by MarcusDenker** [comment]
Ah, the question came up if it should not be "class initialization" instead (see issue tracker)

**Comment by gypsydave5** [comment]
> Ah, the question came up if it should not be "class initialization" instead (see issue tracker)

Could do with some guidance on this point!

**Comment by astares** [comment]
@gypsydave5 
- on the instance side the category is called "initialization" and typically hosts instance methods like #initialize
- on the class side the category is often called "class initialization" and typically hosts class methods like #initialize (for class initialization) or #reset (to reset state of class variables or other)

So if you adopt your PR to put the method into a category named "class initialization" instead of "initialization" because you moved it to the class side now then I guess your PR will be happily accepted.

**Comment by gypsydave5** [comment]
> adopt your PR to put the method into a category named "class initialization" instead of "initialization"

easy enough!

**Comment by gypsydave5** [comment]
OK, this should now be the same but with `class initialization` protocol instead of `initialization`.

(now I have to do the same with all the other PRs 🤣)

**Comment by gypsydave5** [comment]
@astares @MarcusDenker - is this now in a state where it can be merged? The failed check looks Win specific, a regression that's been fixed? I'd rerun the check but I'm not sure how (or if I can).

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
