### PR TITLE
2023 12 29 rename method driver

### PR DESCRIPTION
**Pull request by Ducasse**
Migrating the old rename driver to the new model.

### CODE REVIEW

**Comment by Ducasse** [comment]
Working on it. Please do not review nor integrate.

**Comment by Ducasse** [comment]
I do not get why this is not loading. I have exactly the same dependency than before. Commands are refering to drivers as before. I changed nothing on that side.

**Comment by Ducasse** [comment]
Now P12 is unstable and I got many bugs (unrelated with the PR). I will try to load it in a more recent image to see.

**Comment by Ducasse** [comment]
I tried to load the PR in a more recent image but I could not repair the image :(
I tried to 
- sync my repo
- fetch from Pharo
- load the PR
- I could not understand I had such huge list of changes
- So I got super confused. 
Capture 2023-12-31 at 22 32 22

**Comment by Ducasse** [comment]
I do not get the following error and I do not know how to solve it. I love this "Press Proceed to try to load them again "

```
NewUndeclaredWarning: SycMigrateReferencesOfClassCommand>>prepareFullExecutionInContext: (ClyAllClassesQuery is Undeclared)
MetacelloNotification: Loaded -> SystemCommands-ClassCommands --- tonel:///builds/workspace/est_and_branch_Pipeline_PR-15881/64/src
Error: The following definitions had errors while loading.  Press Proceed to try to load them again (they may work on a second pass):
  SycRenameMessageCommand

MCPackageLoader(Object)>>notify:
MCPackageLoader>>warnAboutErrors:
[ self warnAboutErrors: errorDefinitions ] in MCPackageLoader>>loadClassDefinitions in Block: [ self warnAboutErrors: errorDefinitions ]
FullBlockClosure(BlockClosure)>>cull:
OrderedCollection(Collection)>>ifNotEmpty:
MCPackageLoader>>loadClassDefinitions
MCPackageLoader>>basicLoadDefinitions
[ self basicLoadDefinitions ] in MCPackageLoader>>basicLoad in Block: [ self basicLoadDefinitions ]
[ aBlock value ] in SourceFileArray>>deferFlushDuring: in Block: [ aBlock value ]
FullBlockClosure(BlockClosure)>>ensure:
SourceFileArray>>deferFlushDuring:
```

**Comment by Ducasse** [comment]
I checked again and I do not understand why I get this problem.

**Comment by Ducasse** [comment]
My impression is that the baseline of refactoring should be loaded before system commands.


```
{BaselineOfAthens.
	BaselineOfBasicTools.
	BaselineOfDisplay.
	BaselineOfFlashback.
	BaselineOfIDE.
	BaselineOfMenuRegistration.
	BaselineOfMorphic.
	BaselineOfMorphicCore.
	BaselineOfSlot.
	BaselineOfSUnit.
	BaselineOfTraits.
	BaselineOfUI.
	BaselineOfUnifiedFFI.
	BaselineOfClassAnnotation.
	BaselineOfSystemCommands.
	BaselineOfClassParser.
	BaselineOfReferenceFinder.
	BaselineOfSortFunctions.
	BaselineOfGeneralTests.
	BaselineOfMisc.
	BaselineOfEpicea.
	BaselineOfRefactoring.
	BaselineOfOSWindow.
	BaselineOfQA.
	BaselineOfManifest.
	BaselineOfDependencyAnalyzer.
	BaselineOfQualityAssistant.
...
```
But I do not know if this is the problem.

**Comment by Ducasse** [comment]
Because normally we should only get an undeclared on a driver class similarly to the `NewUndeclaredWarning: SycDeprecateClassCommand>>prepareFullExecutionInContext: (ClyAllClassesQuery is Undeclared)`
below

```
NewUndeclaredWarning: RefactoringSettings class>>scopeList (ClyNavigationEnvironment is Undeclared)
MetacelloNotification: Loaded -> SystemCommands-RefactoringSupport --- tonel:///builds/workspace/est_and_branch_Pipeline_PR-15881/64/src
NewUndeclaredWarning: SycDeprecateClassCommand>>prepareFullExecutionInContext: (ClyAllClassesQuery is Undeclared)
NewUndeclaredWarning: SycMigrateReferencesOfClassCommand>>prepareFullExecutionInContext: (ClyAllClassesQuery is Undeclared)
MetacelloNotification: Loaded -> SystemCommands-ClassCommands --- tonel:///builds/workspace/est_and_branch_Pipeline_PR-15881/64/src
Error: The following definitions had errors while loading.  Press Proceed to try to load them again (they may work on a second pass):
  SycRenameMessageCommand
```

**Comment by guillep** [comment]
I checked and the only thing in the PR that stands out are the changes in the traits:

imagen

I'll try to fix it manually. If that is the problem, I'll try to do during the week a PR to fix the original cause

**Comment by guillep** [comment]
Now this means that we should have better error reporting when something does not load in the CI, otherwise we are debugging blindly...

**Comment by guillep** [comment]
It was seemingly that!

imagen

Now, I debugged it a bit and I did not manage to reproduce it yet

**Comment by Ducasse** [comment]
Ouch I did not thought about it. if you put it back it does not fail anymore?

**Comment by Ducasse** [comment]
I will integrate it and fix the problems later because I have a super instable image and I pushed a bad commit in that PR locally. 
And I do not know how to remove the commit.

**Comment by guillep** [comment]
I only see two broken tests caused by this PR:

imagen

**Pull request merged**
