### PR TITLE
Fix metacello override cases

### LINKED ISSUE #15936: MetacelloMCBaselineOfProjectSpect did not understand #loadVersion:
**Bug description**
Loading previously working Metacello baselines now fail in Pharo 12. This does not happen always, so it is not clear to me yet if it's related with loading Bloc in a specific way. (Loading [Bloc](https://github.com/pharo-graphics/Bloc) as documented in the [Installation](https://github.com/pharo-graphics/Bloc#installation) section loads without problems).

**To Reproduce**
```smalltalk
Metacello new
	repository: 'github://Ducasse/Myg';
	baseline: 'Myg';
	onConflictUseLoaded;
	load.
```

**Screenshots**
Screenshot 2024-01-08 at 12 37 56

### PR DESCRIPTION
**Pull request by guillep**
Fix #15936

@estebanlm @hernanmd can you test this works as expected given your scenarios?

### CODE REVIEW

**Comment by hernanmd** [comment]
Thanks, now the load works as expected. (the screenshot is blocked because there is another unrelated problem initializing Bloc):

Screenshot 2024-01-08 at 14 19 13

**Comment by estebanlm** [comment]
seems to work :)

**Comment by Ducasse** [comment]
Hernan Myg read me mentions v1.0.1 so that it works.

**Comment by Ducasse** [comment]
Later I can try loading microdown because in P12 it was not working.

**Comment by Ducasse** [comment]
How can I load the PR?
I try to do a fetch on pharo-project but I cannot see it.

**Comment by Ducasse** [comment]
Trying view PullRequests from Pharo

**Comment by hernanmd** [comment]
> How can I load the PR? I try to do a fetch on pharo-project but I cannot see it.

I cloned the guille's repository from CLI, then from Pharo in Iceberg I selected pharo-project and click Repair with Locate local repository option.
Once finished, right-click to check out the branch "fix-metacello-overrides" discarding image changes and load the repository version.

**Comment by Ducasse** [comment]
Thanks I did review PullRequest and had to add Guillep remote. 
Now it does not solve my issue https://github.com/pharo-project/pharo/issues/15930

I will retry it and try to minimise the problem.

**Comment by guillep** [comment]
> Thanks I did review PullRequest and had to add Guillep remote. Now it does not solve my issue #15930
> 
> I will retry it and try to minimise the problem.

Yes this is for sure a separate issue

**Comment by Ducasse** [comment]
So I will merge then?
I'm unsure since the newtools issue was integrated.

**Pull request merged**
