### PR TITLE
Apply addition of discardBuffer to ZnBufferedReadStream>>#readInto:startingAt:count in the case that the buffer is bypassed

### PR DESCRIPTION
**Pull request by Rinzwind**
This pull request applies the changes from [Zinc commit ca180a2](https://github.com/svenvc/zinc/commit/ca180a2fe12baab91bdbca397f0824e2b9596efc). This is related to issue #14235.

### CODE REVIEW

**Review by demarey — APPROVED** [review]

**Comment by demarey** [comment]
Thanks for the contribution.

**Comment by Ducasse** [comment]
Thanks a lot Kris this is cool to have you around and contributing.

**Comment by Rinzwind** [comment]
@demarey Pharo Launcher also fails to extract some of the ZIP files from our Jenkins server. I backported this fix to Pharo 12 in pull request #17112. It would be nice to have Pharo Launcher updated to Pharo 12 so it has the fix. I could backport the fix to Pharo 11 as well, but another reason to update to Pharo 12 would be [Pharo Launcher issue #695](https://github.com/pharo-project/pharo-launcher/issues/695).

**Comment by Rinzwind** [comment]
@demarey I opened a pull request to backport the fix to Pharo 11 as well: pull request #17382.

**Comment by Rinzwind** [comment]
@demarey Pull request #17382 was merged and a new Pharo 11 image including the fix is available (build 733), could you maybe update Pharo Launcher as well?

**Comment by jecisc** [comment]
The launcher should take the latest image automatically normally

**Comment by Rinzwind** [comment]
@jecisc I’m not sure I understand what you mean, I meant to have Pharo Launcher itself updated. We use a [‘private’ template category](https://github.com/pharo-project/pharo-launcher/blob/4f7343ebd1f4748668c359126724e6d5d68f2a01/doc/templates.md#create-your-own-list-of-template-categories) for our Jenkins server. Creating an image from some of its templates signals an error at the step ‘Extracting archive to target directory’. Pharo Launcher v3.2 is based on Pharo 11 build 726 so it doesn’t yet have the fix for issue #14235.

**Pull request merged**
