### PR TITLE
Cannot-rewrite-code-with-empty-replacement

### PR DESCRIPTION
**Pull request by jecisc**
Allows one to write a rule to remove a node from the AST. 

In order to do that I introduced a RBEmptyNode in the AST to use when the rewrite rule contains nothing instead of an empty RBSequenceNode.

### CODE REVIEW

**Comment by jecisc** [comment]
Tests are related :(

**Comment by jecisc** [comment]
Tests passed but do not integrate it yet please. We need to think about it with Marcus to see if we can do better.

**Comment by Ducasse** [comment]
This is cool 
Now I wonder why do we need 

{ #category : #accessing }
	RBEmptyNode >> allDefinedVariables [
		^ self temporaryNames asOrderedCollection
			addAll: super allDefinedVariables;
			yourself
	]
	
	{ #category : #accessing }
	RBEmptyNode >> allTemporaryVariables [
		^ self temporaryNames asOrderedCollection
			addAll: super allTemporaryVariables;
			yourself
	]
	
	{ #category : #accessing }
	RBEmptyNode >> children [
		^ OrderedCollection withAll: self temporaries
	]


And why you need to change the formatter?

**Comment by jecisc** [comment]
Well, this is why I said we should think a little more about it before integrating. To make tests pass, I needed to duplicate a lot of the SequenceNode code in the EmptyNode. So I think there is something wrong there. I need to think a little more about it to find a better solution.

**Comment by Ducasse** [comment]
OKI

**Pull request closed without merging**
