### PR TITLE
extract-return-from-conditionals-for-packages-h-to-k

### PR DESCRIPTION
**Pull request by jecisc**
Extract returns from conditionals for packages starting by h to k

This makes the code more readable since we can directly know that the conditional will necessarily return something and the execution can be stoped.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
testTallyInstructions fails which might be related (code that it counts was changed?)

**Comment by jecisc** [comment]
Indeed, the test failure is related to the PR

**Comment by MarcusDenker** [comment]
"Got 28 instead of 27"
I think these are just smoke tests and you can just edit the number that it expects

**Comment by MarcusDenker** [comment]
There's now a conflict. as this was auto-generated, can we close the PR for it to be redone?

**Pull request closed without merging**
