### PR TITLE
Created a simple and a complex test for the changes file flushing issue

### LINKED ISSUE #6491: Create test cases for changes file flushing
Create test cases for issue #6063

### PR DESCRIPTION
**Pull request by theseion**
Fixes #6491

### CODE REVIEW

**Comment by theseion** [comment]
Do you want a separate PR for Pharo 8? I think backporting would be fine without the tests.

**Comment by MarcusDenker** [comment]
No, Pharo9 is enough

**Comment by Ducasse** [comment]
SUPERB!!! NO other words!!!
THANKS!!!

**Comment by theseion** [comment]
Thanks Stef :)

**Pull request merged**
