### PR TITLE
Quote URL interpolated into xdg-open command string

### LINKED ISSUE #6102: WBUnixWebBrowser does not quote the URL parameter
**Describe the bug**
The `#openNativeWebBrowserOn:` class method of `WBUnixWebBrowser` does not quote the URL parameter, meaning any URL with more than one query parameter be truncated to the first query parameter, as `&` is interpreted as a special character by the shell.

**To Reproduce**
1. Run the latest dev version of Pharo on a Linux OS
2. In the Playground, enter `WebBrowser openOn: 'https://duckduckgo.com/?q=pharo&atb=v167-1&iax=videos&ia=videos'` and "Do It".
3. A new browser tab is opened, but the URL is truncated to `https://duckduckgo.com/?q=pharo`

**Expected behavior**
The correct URL `https://duckduckgo.com/?q=pharo&atb=v167-1&iax=videos&ia=videos` should be opened in the browser.

**Version information (please complete the following information, you can get it from Help->about):**
 - OS: Kubuntu 19.10
 - Version: Pharo 9.0
 - Commit info: 2c38e9fbc05c63fbe5db1b23db83fa442500d7f3

### PR DESCRIPTION
**Pull request by EwanDawson**
fixes #6102

### CODE REVIEW

**Comment by EwanDawson** [comment]
request-info: Updated title and description.

**Review by astares — APPROVED** [review]
Verified - OK

**Comment by astares** [comment]
CI problem is unrelated, change has no issue with the tests

**Review by guillep — APPROVED** [review]
Ok! Thanks all for the PR and the review :)

**Pull request merged**
