### PR TITLE
introduce a hook so that we can access changes from the tests.

### PR DESCRIPTION
**Pull request by Ducasse**
introduce a hook so that we can access changes from the tests.

### CODE REVIEW

**Comment by Ducasse** [comment]
Not sure how to solve that conflict.

**Comment by Ducasse** [comment]
I just removed my version that I did not touch so normally no impact.

**Review by balsa-sarenac — APPROVED** [review]
Nice improvement!

**Comment by balsa-sarenac** [comment]
The CI failed on Unix. Can someone trigger a re-run?

**Comment by MarcusDenker** [comment]
I restarted it

**Pull request merged**
