### PR TITLE
Fix lint in ReShouldSendSuperSetUpAsFirstMessage class>>#checksMethod

### LINKED ISSUE #16616: Fix lint in ReShouldSendSuperSetUpAsFirstMessage class>>#checksMethod
Screenshot from 2024-05-13 18 52 22

and a few other simple categorization lints

### PR DESCRIPTION
**Pull request by astares**
Fix #16616

### CODE REVIEW

**Comment by astares** [comment]
- CI issue, unrelated
- Windows is green

**Review by jecisc — APPROVED** [review]

**Review by jecisc — CHANGES_REQUESTED** [review]
CI failures *are* related. 

Some methods got copied from a used traits and are the same. They should be removed

**Comment by astares** [comment]
Strange - will check

**Comment by astares** [comment]
Lets close this PR and use https://github.com/pharo-project/pharo/pull/16643

**Pull request closed without merging**
