### PR TITLE
Improving the OSWindow backend for the world

### PR DESCRIPTION
**Pull request by tesonep**
It fixes:
  - The clipboard
  - The CMD/CTRL/ALT + Point
  - Improves mouse and key events.

### CODE REVIEW

**Review by estebanlm — APPROVED** [review]

**Comment by Ducasse** [comment]
self currentWorld worldState worldRenderer
could be 
self worldRenderer
No?

**Comment by estebanlm** [comment]
you mean add a method in Object? I would not pollute it so much. 
maybe we could do instead?
```
self currentWorld worldRenderer
```

**Comment by estebanlm** [comment]
but this is orthogonal to this change :)

**Comment by Ducasse** [comment]
No!!! How can you think that I would like to add a method in Object!
I mean in this class OSWindowClipboard!

**Comment by Ducasse** [comment]
There is no need to duplicate chains of method call.

**Pull request merged**
