### PR TITLE
Harvest latest changes from STON

### LINKED ISSUE #9390: [STON] Ston materialization fails for sorted collections with references to other graph objects
**Bug description**
If in an object graph, there is an sorted collection that points to other objects in the object graph. The STON materialization fails because it tries to work with STON references as with materialized objects.

**To Reproduce**
1. file-in this simple example: [ObjectWithSortedCollection.zip](https://github.com/pharo-project/pharo/files/6590190/ObjectWithSortedCollection.zip).
2. execute  `ObjectWithSortedCollection issue`
3. `Instance of STONReference did not understand #'<='`

Basically, it does this: 
```smalltalk
	data := (1 to: 2) collect: [ :e | ObjectWithSortedCollection new ].

	data do: [ :each | 
		data do: [ :object | 
			each sortedCollection add: object ] ].

	serialized := STON toString: data.
	materialized := STON fromString: serialized.
```

image

### PR DESCRIPTION
**Pull request by guillep**
Harvest latest STON changes as per https://github.com/svenvc/ston/commit/c5f69da6f9ce13bf33575c11e594d286203d82ec.

This PR is the sister of https://github.com/svenvc/ston/pull/30 which harvest changes done in Pharo back into STON.

Fixes #9390

### CODE REVIEW

**Comment by svenvc** [comment]
The upstream merge into the STON repo was done, Thank you, Guille !

**Comment by guillep** [comment]
Thanks! This means that this PR brings Pharo9 up to commit https://github.com/svenvc/ston/commit/c5f69da6f9ce13bf33575c11e594d286203d82ec of STON (that includes the merge). I'll update the description.

**Comment by MarcusDenker** [comment]
These tests fail on all platforms:

```
unix-64 / Tests-unix-64 / testNoUnusedClassVariablesLeft – Unix64.ReleaseTests.CleanCode.NoUnusedVariablesLeftTest
<1s
unix-64 / Tests-unix-64 / testSortedCollections – Unix64.STON.Tests.Write.Read.STONLargeWriteReadTest
<1s
unix-64 / Tests-unix-64 / testSortedCollections – Unix64.STON.Tests.Write.Read.STONWriteAsciiOnlyReadTest
<1s
unix-64 / Tests-unix-64 / testSortedCollections – Unix64.STON.Tests.Write.Read.STONWritePrettyPrinterReadTest
<1s
unix-64 / Tests-unix-64 / testSortedCollections – Unix64.STON.Tests.Write.Read.STONWriteReadCommentsTest
<1s
unix-64 / Tests-unix-64 / testSortedCollections – Unix64.STON.Tests.Write.Read.STONWriteReadTest
```

**Comment by svenvc** [comment]
Strange, that test passes in https://github.com/svenvc/ston/runs/3046156715?check_suite_focus=true

<blockquote><div> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 65 million people use GitHub to discover, fork, and contribute to over 200 million projects.</div></blockquote>

**Comment by guillep** [comment]
> Strange, that test passes in https://github.com/svenvc/ston/runs/3046156715?check_suite_focus=true
> 
> >  GitHub**[Build software better, together](https://github.com)**GitHub is where people build software. More than 65 million people use GitHub to discover, fork, and contribute to over 200 million projects.

We checked with @tesonep , this is a problem in the order of dependencies. `STON` is loaded early in the construction of the Pharo images, even before the `SortFunction` packages are loaded. This means that all the extensions are not loaded.

Pablo split the "convenience extensions" into a new package to allow them to be loaded separately.
We will publish a new PR to STON soon.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 65 million people use GitHub to discover, fork, and contribute to over 200 million projects.</div></blockquote>

**Pull request merged**
