### PR TITLE
22274-Rewrite-the-method-finder

### PR DESCRIPTION
**Pull request by Karnaj**
Rewrite the method finder using this approach:

- each class has a list of methods that can be tested by the finder and a list of a method that cannot,
- the finder browse the receiver's hierarchy to found all approved methods and run them. 

https://pharo.fogbugz.com/f/cases/22274/Rewrite-the-method-finder

### CODE REVIEW

**Review by VincentBlondeau — COMMENTED** [review]
There is a need to add your new package in the baseline. I'll do a pull request on your branch for that

**Review by VincentBlondeau — CHANGES_REQUESTED** [review]
See https://github.com/Karnaj/pharo/pull/1
And it will be nice to see how to integrate these changes into the FinderUI. 
Take a look to: Finder>>testObjects:strings: . The API is not the same than for MethodFinder. So I was not able to test it... 

Furthermore, could you give some examples of what your finder brings compare to the current one?

**Comment by pavel-krivanek** [comment]
We do not want to introduce a new version of a tool without removing of the old one

**Comment by tesonep** [comment]
I will integrate, I have created and issue to address in the Sprint for removing the old tool.
https://pharo.manuscript.com/f/cases/22283/Remove-old-Finder-Unused-Code

**Pull request merged**
