### PR TITLE
Changing QuotedPrintableMimeConverter>>#newline into initialization category

### LINKED ISSUE #10173: Put QuotedPrintableMimeConverter>>#newline: into initialization category
Put QuotedPrintableMimeConverter>>#newline: into initialization category

### PR DESCRIPTION
**Pull request by kausthubtm**
Fix [#10173](https://github.com/pharo-project/pharo/issues/10173)

### CODE REVIEW

**Comment by kausthubtm** [comment]
Second commit Fixes : [#10395](https://github.com/pharo-project/pharo/issues/10395)

**Comment by Ducasse** [comment]
Thanks for your PR. Now I noticed that you have changes to the refactoring engine in addition to the protocol names.

**Comment by kausthubtm** [comment]
Thank you for the review. I have removed the additional changes. Could you review it now @Ducasse ?

**Comment by Ducasse** [comment]
Thanks I will. 
Waiting for the CI to build.

**Comment by Ducasse** [comment]
Many refactoring tests are broken and I imagine that this is due to the fact that the method you (correctly) renamed was used. 
Did you use a refactoring to perform the changes?
If not then you should manually check the callers of the previous method and fix them and run the tests.

**Comment by Ducasse** [comment]
windows-64 / Tests-windows-64 / testCompileInClass – Windows64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
windows-64 / Tests-windows-64 / testCompileInMetaclass – Windows64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
windows-64 / Tests-windows-64 / testPerformAddRemoveClassMethod – Windows64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
windows-64 / Tests-windows-64 / testPerformAddRemoveMethod – Windows64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
windows-64 / Tests-windows-64 / testPerformAddRemoveMethodInteractively – Windows64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
windows-64 / Tests-windows-64 / testPerformChangeMethod – Windows64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
windows-64 / Tests-windows-64 / testPerformCompositeChange – Windows64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
windows-64 / Tests-windows-64 / testRemoveClass – Windows64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
windows-64 / Tests-windows-64 / testRemoveClassNamed – Windows64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
windows-64 / Tests-windows-64 / testRemoveMethod – Windows64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
windows-64 / Tests-windows-64 / testAsClassRuleTransformation – Windows64.Renraku.Tests.RenrakuTest
<1s
Existing failures - 22
unix-64 / Tests-unix-64 / testCompileInClass – Unix64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
unix-64 / Tests-unix-64 / testCompileInMetaclass – Unix64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
unix-64 / Tests-unix-64 / testPerformAddRemoveClassMethod – Unix64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
unix-64 / Tests-unix-64 / testPerformAddRemoveMethod – Unix64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
unix-64 / Tests-unix-64 / testPerformAddRemoveMethodInteractively – Unix64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
unix-64 / Tests-unix-64 / testPerformChangeMethod – Unix64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
unix-64 / Tests-unix-64 / testPerformCompositeChange – Unix64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
unix-64 / Tests-unix-64 / testRemoveClass – Unix64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
unix-64 / Tests-unix-64 / testRemoveClassNamed – Unix64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
unix-64 / Tests-unix-64 / testRemoveMethod – Unix64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
unix-64 / Tests-unix-64 / testAsClassRuleTransformation – Unix64.Renraku.Tests.RenrakuTest
<1s
osx-64 / Tests-osx-64 / testCompileInClass – MacOSX64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
osx-64 / Tests-osx-64 / testCompileInMetaclass – MacOSX64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
osx-64 / Tests-osx-64 / testPerformAddRemoveClassMethod – MacOSX64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
osx-64 / Tests-osx-64 / testPerformAddRemoveMethod – MacOSX64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
osx-64 / Tests-osx-64 / testPerformAddRemoveMethodInteractively – MacOSX64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
osx-64 / Tests-osx-64 / testPerformChangeMethod – MacOSX64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
osx-64 / Tests-osx-64 / testPerformCompositeChange – MacOSX64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
osx-64 / Tests-osx-64 / testRemoveClass – MacOSX64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
osx-64 / Tests-osx-64 / testRemoveClassNamed – MacOSX64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
osx-64 / Tests-osx-64 / testRemoveMethod – MacOSX64.Refactoring.Tests.Changes.RBRefactoringChangeTest
<1s
osx-64 / Tests-osx-64 / testAsClassRuleTransformation – MacOSX64.Renraku.Tests.RenrakuTest

**Comment by kausthubtm** [comment]
Oh ! I hadn't used refactoring. I have to follow the steps shown [here](https://www.youtube.com/watch?v=tHdt11WDq2o) right ? Also can I close this PR create a new PR with the changes ? This one is getting quite clumsy.

**Comment by MarcusDenker** [comment]
it is better to do only one fix per PR...it sometimes feels bad for trivial change, but it is better as we then can merge one fix without the other...

**Comment by MarcusDenker** [comment]
I close the PR. it contains one good change and one that breaks things, so it can not be merged.

It is better to do # #10395 in a PR that just fixes that issue.

**Pull request closed without merging**
