### PR TITLE
Fix 9631 (Sources should not contain NULL character) for Pharo 9

### LINKED ISSUE #9631: Sources should not contain NUL character
Hi 🙂 Stable Pharo9 sources (`Pharo9.0-64bit-e58ef49.sources`) contain `<NUL>` characters on lines `642448` and `834535`.

```
SystemNavigation default allMethods select: [ :m | m sourceCode includes: Character null ]
```
05566EBA-0E14-4A6F-9ED7-169C19CD493E
734C7E71-92A5-4CCF-9A65-602800D92CDA
BA17D391-5319-4EB2-8952-FEB8551B08B1

### PR DESCRIPTION
**Pull request by astares**
Fix #9631

### CODE REVIEW

**Comment by MarcusDenker** [comment]
git seems to think that the file is binary: when looking at the diff, I get "Binary file not shown"

**Comment by astares** [comment]
@MarcusDenker Yes - but this is due to the \00 in the original files - so it switches to binary during comparision. 

When you check the files in branch https://github.com/astares/pharo/tree/9631-Sources-should-not-contain-NULL-character-third you will see they are regular text files

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/astares/pharo">GitHub - astares/pharo at 9631-Sources-should-not-contain-NULL-character-third</a></strong></div><div>Contribute to astares/pharo development by creating an account on GitHub.</div></blockquote>

**Comment by astares** [comment]
Still there seems to be a problem with utf-8 encoding. Will check that.

**Comment by MarcusDenker** [comment]
ready to merge?

**Comment by astares** [comment]
From my side yes

**Pull request merged**
