### PR TITLE
Fix #9907: improes DoesNotUnderstand exception's messageText

### LINKED ISSUE #9907: Enhance DoesNotUnderstand exception with a better message text
**Describe the request**

Right now, the message text of a does not understand is `Class>> #selector`.
Printing it is not very useful as it does not say that there was a DNU.
Also, it adds an extra space which feels random and ugly.

**Expected behavior**
A better message in the style of `Message not understood: Class>>#selector`

**Version information:**
 - Pharo 10

**Additional information**
This is important to give better inspector feedback. See https://github.com/pharo-spec/NewTools/issues/276

### PR DESCRIPTION
**Pull request by gypsydave5**
Thrown a test in for good measure

### CODE REVIEW

**Comment by gypsydave5** [comment]
I've obviously done this for the Pharo10 branch; should I do the same for Pharo9 ?

**Comment by MarcusDenker** [comment]
Thanks! I think for Pharo9 we should only backport very important fixes... it is so easy to introduce new problems :-)

**Comment by gypsydave5** [comment]
> Thanks!

You're welcome! I'm just picking up the easier issues while I get comfortable with the workflow.

**Comment by MarcusDenker** [comment]
Failing test: #testPrintDoesNotUnderstand

```
Error
Got 'Error printing: Message not understood: StObjectWithPrintDoesNotUnderstand >> #iShouldNotUnderstandThis' instead of 'Error printing: StObjectWithPrintDoesNotUnderstand>> #iShouldNotUnderstandThis'.
Stacktrace
TestFailure
Got 'Error printing: Message not understood: StObjectWithPrintDoesNotUnderstand >> #iShouldNotUnderstandThis' instead of 'Error printing: StObjectWithPrintDoesNotUnderstand>> #iShouldNotUnderstandThis'.
StObjectPrinterTest(TestAsserter)>>assert:description:resumable:
StObjectPrinterTest(TestAsserter)>>assert:description:
StObjectPrinterTest(TestAsserter)>>assert:equals:
StObjectPrinterTest>>assertIsError:expectedMessage:
StObjectPrinterTest>>testPrintDoesNotUnderstand
```

**Comment by MarcusDenker** [comment]
@ypsydave5 there is a test that tests the old print #testPrintDoesNotUnderstand, can you update your PR with an updated test?

**Comment by gypsydave5** [comment]
@MarcusDenker - sorry about that - what's a good set of tests to be running (or a way to run all tests?) before I commit?

**Comment by gypsydave5** [comment]
Looking at this, the failure is in the `pharo-newtools` repo. Should I open a separate PR there?

**Comment by MarcusDenker** [comment]
Yes!

**Comment by gypsydave5** [comment]
PR opened in NewTools - https://github.com/pharo-spec/NewTools/pull/291

**Comment by MarcusDenker** [comment]
newtools pr is merged

**Comment by gypsydave5** [comment]
woohoo!

**Pull request merged**
