### PR TITLE
7412-preparing-the-integration-of-fluid-class-part-2

### PR DESCRIPTION
**Pull request by Ducasse**
Adding a new message to encode the kind of the layout.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
the commit somehow removes the #category  on the level of the git format:

#'Kernel-Layout' is turned into #Kernel

**Comment by Ducasse** [comment]
yes I do not know why

**Comment by Ducasse** [comment]
I think that this is the move to package refactoring that is changing this and I do not know what to do.

**Comment by Ducasse** [comment]
I do not understand because I commit I removed explicitly from the selection the class definition changes :(. 
If I would have blindly committed I could understand but this is not the case :(

**Pull request merged**
