### PR TITLE
[cleanup] isArgOrTemp transformation to isLocalVariable

### PR DESCRIPTION
**Pull request by hogoww**
as we talked about in : #6195

### CODE REVIEW

**Comment by MarcusDenker** [comment]
strange error when building:


[64] 'VersionInfo: Pharo9.0-PR-g5da7deb7e4ff36f456162e36bcf0490cf8585cd6'
[64] 'Errors in script loaded from /builds/workspace/uest_and_branch_Pipeline_PR-6702/64/bootstrap/scripts/bootstrap.st'
[64] TonelParseError: Can't parse method body
[64] TonelSourceScanner>>scan

**Comment by hogoww** [comment]
line it fails to scan is `PBBootstrap fromCommandLine bootstrap`
Very weird indeed..

**Comment by MarcusDenker** [comment]
Very strange.. I restarted to CI

**Comment by hogoww** [comment]
Same error. 
Guess I'll have to run the bootstrap (If I can) to find out why

**Pull request closed without merging**
