### PR TITLE
Add a reported missing dependency breaking the build.

### PR DESCRIPTION
**Pull request by hernanmd**
Related to #16099

### CODE REVIEW

**Comment by guillep** [comment]
There is an error in the build, very probably related

```
Error: Name not found: NewTools-Core
```

**Comment by hernanmd** [comment]
> There is an error in the build, very probably related
> 
> ```
> Error: Name not found: NewTools-Core
> ```

I know, unfortunately I had to send PR's to check the build.
I'm trying to understand the Baseline order. This I what I have so far:

| Type   |      BaselineOf      |  Required Baselines |
|----------|:-------------:|------|
| Internal |  UI | Morphic, Commander2, Spec |
| Internal | BasicTools | SUnitCore, UI, Reflectivity, Athens, SUnit, EnlumineurFormatter, Refactoring ]
| Internal |  IDE  |  BasicTools, Athens, Flashback, ReflectionMirrors, FuzzyMatcher, QA, OSWindow, EmergencyDebugger, Misc, GeneralTests, Zodiac, SortFunctions, Equals, ReferenceFinder, ClassParser, Ring, HeuristicCompletion, SpecCode, NewTools, DrTests, Microdown, BeautifulComments, NewToolsDocumentBrowser, WelcomeBrowser, Roassal, ThreadedFFI |
| External | NewTools | Sindarin, Chest, ColorPicker |

So if I want to add a System-Spec package which uses the NewTools file dialogs (because some tools complaint about it in the build), that would require to add a requirement of NewTools to BaselineOfUI ? But as NewTools is defined as an external project I don't know what to do.

Any suggestion?

**Comment by guillep** [comment]
> > There is an error in the build, very probably related
> > ```
> > Error: Name not found: NewTools-Core
> > ```
> 
> I know, unfortunately I had to send PR's to check the build. I'm trying to understand the Baseline order. This I what I have so far:

Have you tried using the Baseline dependency graph in Calypso?

imagen

> So if I want to add a System-Spec package which uses the NewTools file dialogs (because some tools complaint about it in the build), that would require to add a requirement of NewTools to BaselineOfUI ? But as NewTools is defined as an external project I don't know what to do.
> 
> Any suggestion?

I don't know :)
Without thinking too much, some ideas:
 - move this package to new-tools or to a separate baseline/repo. Instead of making projects depend on NewTools, we invert/cut the dependency.
 - or we cut this BaselineOfUI in many baselines that are loaded in separate stages during the bootstrap (so you can load NewTools as part of BaselineOfUI). But this is more work

**Comment by hernanmd** [comment]
Closing as this will be pull requested as a new package in NewTools

**Comment by hernanmd** [comment]
> > > There is an error in the build, very probably related
> > > ```
> > > Error: Name not found: NewTools-Core
> > > ```
> > 
> > 
> > I know, unfortunately I had to send PR's to check the build. I'm trying to understand the Baseline order. This I what I have so far:
> 
> Have you tried using the Baseline dependency graph in Calypso?
> imagen
> 
> > So if I want to add a System-Spec package which uses the NewTools file dialogs (because some tools complaint about it in the build), that would require to add a requirement of NewTools to BaselineOfUI ? But as NewTools is defined as an external project I don't know what to do.
> > Any suggestion?
> 
> I don't know :) Without thinking too much, some ideas:
> 
>     * move this package to new-tools or to a separate baseline/repo. Instead of making projects depend on NewTools, we invert/cut the dependency.
> 
>     * or we cut this BaselineOfUI in many baselines that are loaded in separate stages during the bootstrap (so you can load NewTools as part of BaselineOfUI). But this is more work

Thanks. I will add the UI support as a new package in NewTools so does not add complexity.

**Pull request closed without merging**
