### PR TITLE
Speed up refactoring tests by constricting refactoring models

### PR DESCRIPTION
**Pull request by carolahp**
Refactoring tests take too long to run, this PR constrains the model of many refactoring tests (specifically parametriezed tests) to make them run faster. 
This PR is a continuation of [PR#15486](https://github.com/pharo-project/pharo/pull/15486). 

This PR does not speed up all refactoring tests. This work will continue in future PRs

### CODE REVIEW

**Comment by Ducasse** [comment]
Oh this is nice!

**Comment by carolahp** [comment]
Refactoring related tests are passing. Failing tests look unrelated to this PR

**Comment by Ducasse** [comment]
Looks good to me.

**Comment by carolahp** [comment]
Hello @MarcusDenker , I have merged the Pharo13 branch and all tests are passing now, could you please take a look?

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
