### PR TITLE
integrate-taskit-core

### PR DESCRIPTION
**Pull request by estebanlm**
include taskit (from https://github.com/pharo-contributions/taskit/tree/v1.1.1)

### CODE REVIEW

**Comment by MarcusDenker** [comment]
MetacelloNotification: Loaded -> TaskIt-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-6698/64/src --- cache
[64] Error: This package depends on the following classes:
[64]   ParametrizedTestCase

**Comment by estebanlm** [comment]
yeah, I wonder why ParametrizedTests is part of BaselineOfUI and not BaselineOfBaseLibraries ?

**Comment by MarcusDenker** [comment]
ReleaseTest>>testUnknownProcesses is failing

**Comment by estebanlm** [comment]
I would approve this, but I made the PR at first instance.

**Pull request merged**
