### PR TITLE
10190-Literal-Sharing-unify-nested-arrays

### LINKED ISSUE #10190: Literal Sharing: unify nested arrays
If you look at ImageCleaner #shareLiterals, it recurses into nested literal arrays to build the table.

But then it only unifies the literals of methods using the table. 

We should in addition go over the arrays recursively and unify the contents using the table.

### PR DESCRIPTION
**Pull request by MarcusDenker**
This impoves literal sharing: unify all the nested arrays using the table that we created.

fixes #10190

### CODE REVIEW

**Comment by svenvc** [comment]
Any idea on how much memory is being recycled this way ?

In any case, it is impressive that this is possible. Little steps multiplying.

**Comment by MarcusDenker** [comment]
It seems the image ~ 2 MB smaller with just doing literal sharing as it we merged today. I did not test this additonal improvement yet.

**Comment by MarcusDenker** [comment]
(but image size is not a good measure.. it seems to be a bit different each time and of course loading/deleting code change sit all the time) but gives just some impression)

**Comment by MarcusDenker** [comment]
Hmm.... Tests show that there are problems

**Comment by MarcusDenker** [comment]
Looking at the tests, it seems that #(1 2) is changed to #(2 2) somewhere. This array has to nested in another array (else we would the the problem already with the current version).

**Comment by svenvc** [comment]
but wouldn't the readonly property guard against that modification ?

**Comment by MarcusDenker** [comment]
For the version alrady integrated I found a test that tested read-only itself that was making a literal read-write and changed it.

But for this case, my theory is that it might be some FFI related test.

I need to check all nested literal arrays that contain #(1 2), maybe it will be obvious where it happens.

**Comment by MarcusDenker** [comment]
I was testBeRecursivelyWritableObject

**Comment by MarcusDenker** [comment]
This is now working, I merge it

**Pull request merged**
