### PR TITLE
Fixed #7187. Removed SystemReporter and SizeReporter. They were replaced with Spec-based StSystemReporter and StSizeReporter

### LINKED ISSUE #7187: Remove System Reporter
It uses old morphic lists and it got rewritten in spec2.

### PR DESCRIPTION
**Pull request by olekscode**

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Build failure: Could not resolve: Tool-SystemReporter [Tool-SystemReporter] in /builds/workspace/uest_and_branch_Pipeline_PR-7637/64/bootstrap-cache/pharo-local/package-cache tonel:///builds/workspace/uest_and_branch_Pipeline_PR-7637/64/src

**Comment by Ducasse** [comment]
oleksandr the package should probably be removed from the baseline too.

**Comment by carolahp** [comment]
> oleksandr the package should probably be removed from the baseline too.

I am on it

**Comment by carolahp** [comment]
When I try to do a PR to Oleks repository I can't find it in the list of base repositories. 
Maybe due to a permission issue?

Screen Shot 2020-10-30 at 18 38 56

**Comment by olekscode** [comment]
@carolahp I have invited you as collaborator
You can try fixing it
Or we can do it together tomorrow

**Comment by carolahp** [comment]
@olekscode I just sent you a PR. 
If it keeps failing we can check later if you have time, if not we see it on Monday :)

**Comment by olekscode** [comment]
@MarcusDenker please look at the updated version

**Comment by Ducasse** [comment]
Excellent! It works!
Thanks!

**Comment by Ducasse** [comment]
Oleksandr could you also add the StSystemReporter to the menu because this is the most important one.

**Comment by olekscode** [comment]
Ok, I will do it

**Comment by olekscode** [comment]
Hello @Ducasse, I have checked and StSystemReporter is already in the menu.
It is under
`System > SystemReporter`

**Comment by Ducasse** [comment]
Ok

**Pull request merged**
