### PR TITLE
Cleanup FuzzyMatcher packages

### LINKED ISSUE #6271: Cleanup FuzzyMatcher packages
FuzzyMatcher
- #isSeperator should be #isSeparator, deprecate (it's private but nonetheless)
- return your self in #pattern: on class side
- better categorization
- remove unnecessary dots
- formatting
- use aCollectionOfStrings as argument name instead of additional comments

FuzzyMatcherExample
- add #script pragma to #open
- remove unnecessary dots
- formatting

FuzzyMatcherTest
- rename #testIsSeperator into #testIsSeparator
- remove unnecessary dots
- formatting

### PR DESCRIPTION
**Pull request by astares**
Fix #6271

### CODE REVIEW

**Comment by Ducasse** [comment]
Hi torsten 
This is cool. 
Now there is test that is related
osx-64 / Tests-osx-64 / testClassSideAPI – MacOSX64.FuzzyMatcher.Tests.Tests.FuzzyMatcherTest
and does not pass.

**Comment by astares** [comment]
@Ducasse Ahh ... sorry. I only had a few minutes between other things and did not check properly. Is green now.

**Comment by Ducasse** [comment]
Cool Tx

**Comment by Ducasse** [comment]
Cool Tx

**Pull request merged**
