### PR TITLE
3006-When-a-test-fails-open-the-debugger-on-the-test-instead-of-on-Objectassert

### PR DESCRIPTION
**Pull request by akevalion**
Fix: https://github.com/pharo-project/pharo/issues/3006
Added  debuggerCompleteToSender pragma to TestAsserter  and some objects like Process, Object, Exception, Context and BlockClosure

### CODE REVIEW

**Comment by akevalion** [comment]
I have created a new PR because the last one https://github.com/pharo-project/pharo/pull/3108 has conflicts

**Review by akgrant43 — CHANGES_REQUESTED** [review]
This PR seems to have the same issues as #3008 - it adds the pragma to Object>>assert:, but not to Object>>assert:description:, so the debugger will open in #assert:description: instead of the caller of #assert:.

Can you also close #3008 and #3108 with a link back to this PR so that it is clear what should be reviewed at the moment.

**Comment by akevalion** [comment]
Hi @akgrant43 I have test it. In test classes when you use `Object>>#assert:` this calls `TestAsserter>>#assert:description:` For that reason the debugger opens directly on the failing test method. However I have commit the change for `Object>>#assert:description`

**Review by guillep — APPROVED** [review]
Looks ok!

**Review by akgrant43 — APPROVED** [review]
> Hi @akgrant43 I have test it. In test classes when you use `Object>>#assert:` this calls `TestAsserter>>#assert:description:` For that reason the debugger opens directly on the failing test method. However I have commit the change for `Object>>#assert:description`

Hmm, that's not what I see in Pharo 8.0.  In the attached image you can see that the stack shows:

UndefinedObject(Object)  assert:description:
UndefinedObject(Object)  assert:
UndefinedObject  DoIt

TestAsserter isn't part of the stack (this can be confirmed by opening the debugger, the comments in TestAsserter>>assert:description: and Object>>assert:description: are different).

Regardless, I agree with Guille, the PR looks good.

Thanks,
Alistair


Screenshot from 2019-04-02 19-25-24

**Comment by akevalion** [comment]
Hi, do I need to change something to Integrate it on pharo8

**Comment by guillep** [comment]
Let's integrate it and we can enhance it further if needed :).
Thanks Milton!!

**Pull request merged**
