### PR TITLE
Following symbolic links when canonicalising FileReferences.

### LINKED ISSUE #14757: AbstractFileReference>>canonicalize doesn't follow symbol links
**Bug description**
`#canonicalize` currently doesn't follow symbolic links, e.g. 

```
'/a/b/symlink/../c' asFileReference canonicalize
">>> /a/b/c"
```

regardless of where `symlink` points.  If `symlink` points to `/d/e/f` the result should be `/d/e/c`.

**To Reproduce**
See `FileReferenceTest>>testSymbolicLink` and 'FileReferenceTest>>testSymbolicLinkTargetPath` in the PR that will be referenced below.

**Expected behavior**
`#canonicalize` returns the correct FileReference.

**Screenshots**

**Version information:**
 - OS: NixOS
 - Version: 23.05
 - Pharo Version: Pharo 12

**Expected development cost**
PR on the way.

**Additional context**

### PR DESCRIPTION
**Pull request by akgrant43**
Fixes: https://github.com/pharo-project/pharo/issues/14757

Additional unit tests:

- DeleteVisitorTest >> testSymbolicLink
- FileReferenceTest >> testSymbolicLink
- FileReferenceTest >> testSymbolicLinkInMemory
- FileReferenceTest >> testSymbolicLinkTargetPath

### CODE REVIEW

**Comment by akgrant43** [comment]
The CI VM crash on OSX-64 looks related - I'll look in to this (but it will be a few days before I get a chance).

**Comment by akgrant43** [comment]
Hi @MarcusDenker,
Thanks for re-running the tests.
The failures appear to be unrelated and occur in other PRs.

**Comment by MarcusDenker** [comment]
We have FileReferenceAttributeTest>>testTargetFile failing:

```
Error

Assertion failed
Stacktrace

TestFailure
Assertion failed
FileReferenceAttributeTest(TestAsserter)>>assert:description:resumable:
FileReferenceAttributeTest(TestAsserter)>>assert:description:
FileReferenceAttributeTest(Object)>>assert:
FileReferenceAttributeTest(TestAsserter)>>should:raise:
FileReferenceAttributeTest>>testTargetFile
FileReferenceAttributeTest(TestCase)>>performTest
```

**Comment by akgrant43** [comment]
@MarcusDenker thanks for pointing that out, I'd only looked at the build errors.  I've updated the test to match the modified behavior (most programs regard the target file of an actual file as itself).

**Comment by MarcusDenker** [comment]
Tests are green. But the Win CI is in a bad shape and does not run tests... do we know if it works there (with files being very platform dependend)

**Comment by akgrant43** [comment]
Good point - I was just thinking of linux and Mac.  I'll check Windows manually and get back to you.

**Comment by akgrant43** [comment]
Force rebuild

**Comment by MarcusDenker** [comment]
The failing tests / problem on linux are not related. And windows CI setup still has problem (not cause by this PR)

**Comment by akgrant43** [comment]
I've manually ran the tests on Windows successfully, so if the Windows CI isn't likely to be fixed soon, this can probably be merged.

**Comment by akgrant43** [comment]
Thanks @MarcusDenker  & @jecisc !

**Pull request merged**
