### PR TITLE
Revert "RPackage: Clean bootstrap initialization"

### PR DESCRIPTION
**Pull request by MarcusDenker**
Reverts pharo-project/pharo#14462

### CODE REVIEW

**Comment by Ducasse** [comment]
We cannot revert because of a new error

#StartupPreferencesLoader #FileSystem)
++ date -u
+ echo Fri Aug 25 12:47:41 UTC 2023 '[Compiler] Initializing the packages in the Kernel'
Fri Aug 25 12:47:41 UTC 2023 [Compiler] Initializing the packages in the Kernel
+ /builds/workspace/est_and_branch_Pipeline_PR-14528/64/bootstrap-downloads/vmtarget/pharo --headless Pharo12.0-PR-compiler-64bit-cdc4285.image --no-default-preferences initializePackages --protocols=protocolsKernel.txt --packages=packagesKernel.txt --save
Instance of RPackage did not understand #addClassDefinition:
RPackage(Object)>>doesNotUnderstand: #addClassDefinition:
RPackageOrganizer>>initializeFor:

**Comment by jecisc** [comment]
@Ducasse I did another PR to try to fix the underlying problem: https://github.com/pharo-project/pharo/pull/14530

**Comment by jecisc** [comment]
The other fix got integrated. Let's see if this is enough

**Comment by Ducasse** [comment]
I close it.

**Pull request closed without merging**
