### PR TITLE
Use primitive 158 for string comparison

### PR DESCRIPTION
**Pull request by jecisc**
New benches with this version:

```st
[ 'This is a test' = 'This is a test' ] bench.
"Before: '9355881.447 per second'"
"After: '20778310.951 per second'"

[ 'This is a test' = 'This isn''t a test' ] bench.
"Before: '36158262.390 per second'"
"After: '44224637.090 per second'"

[ 'This' = 'This' ] bench.
"Before: '8328492.501 per second'"
"After: '22076675.065 per second'"

[ 'This' = 'That' ] bench.
"Before: '7764724.510 per second'"
"After: '25353916.817 per second'"
```

### CODE REVIEW

**Comment by jecisc** [comment]
Tests passed :) I'll be able to try to do the next steps!

**Comment by astares** [comment]
Great initiative

**Comment by jecisc** [comment]
I tried to remove the AsciiOrder when possible to be able to use the jitted primitive instead of the non jitted primitive but then the image crash. There is probably a bug in the jitted primitive. We plan to investigate with @PalumboN in VM dojo.

In the meantime, we can still use the non jitted primitive when the next vm will be released.

**Comment by jecisc** [comment]
The jitted primitive fix was integrated. When a new version of the dev VM will be available I’ll retry to speed up further this feature

**Comment by jecisc** [comment]
This time should be good! I hope...

If this pass, we can integrate after the next VM release :)

New benches with this version:

```st
[ 'This is a test' = 'This is a test' ] bench.
"Before: '9355881.447 per second'"
"After: '20778310.951 per second'"

[ 'This is a test' = 'This isn''t a test' ] bench.
"Before: '36158262.390 per second'"
"After: '44224637.090 per second'"

[ 'This' = 'This' ] bench.
"Before: '8328492.501 per second'"
"After: '22076675.065 per second'"

[ 'This' = 'That' ] bench.
"Before: '7764724.510 per second'"
"After: '25353916.817 per second'"
```

**Comment by Ducasse** [comment]
thanks a lot cyril for your constant push.

**Comment by jecisc** [comment]
I don't like to see half-done transitions :)

**Comment by jecisc** [comment]
It breaks the bootstrap now :( I'll need to check why

**Comment by jecisc** [comment]
This seems to work nowwwww! 

A new VM fix everything needed seems to have been released the 10 march so it should be fine to merge it now :)

**Comment by Ducasse** [comment]
Cool!

**Comment by PalumboN** [comment]
Bravoooooo!!! 🚀

**Comment by astares** [comment]
Great - thanks!

**Comment by guillep** [comment]
Thanks!!!

**Pull request merged**
