### PR TITLE
21124 ffi should work without the sources

### PR DESCRIPTION
**Pull request by VincentBlondeau**
Following of: https://github.com/pharo-project/pharo/pull/749

Fix tests
Add a pragma based search of ffiCalloutSelectors with cache and auto update with announcements
Add scripts to install and uninstall

### CODE REVIEW

**Comment by VincentBlondeau** [comment]
image
Test failure seems to be old

**Comment by VincentBlondeau** [comment]
Still have an issue however:
https://pharo.fogbugz.com/f/cases/21124/FFI-should-work-without-the-sources

**Comment by VincentBlondeau** [comment]
Hum....

--2018-01-30 18:48:01--  (try: 2)  https://ci.inria.fr/pharo/view/5.0-VM-Spur/job/Spur-Git-Tracker/lastSuccessfulBuild/artifact/vmmaker-image.zip

Connecting to ci.inria.fr (ci.inria.fr)|193.51.193.223|:443... connected.
HTTP request sent, awaiting response... 503 Service Temporarily Unavailable
2018-01-30 18:48:01 ERROR 503: Service Temporarily Unavailable.
script returned exit code 8

**Comment by VincentBlondeau** [comment]
Ok for a first version.

To install the plugin in the system, just do: `FFICompilerPlugin install.`
To uninstall: `FFICompilerPlugin uninstall.`

FFI works without the .sources and .changes.
Some methods are wrongly decompiled, but can still be executed.

**Comment by VincentBlondeau** [comment]
> 
>     Some methods are wrongly decompiled, but can still be executed.
> 
> What you mean by this?

I mean that sometimes, the method is not rightly decompiled: it is the FFI compiled version that is used instead of the initial version. And I get a wrong source code. However, the FFI compiled method is still there and can be executed.

**Comment by VincentBlondeau** [comment]
All the failing tests are passing when I download the built image...
https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-750/18/artifact/bootstrap-cache/Pharo7.0-32bit-088a134.zip

**Comment by MarcusDenker** [comment]
Now there is a merge conflict, from a part of the image that is completely unrelated.

**Comment by VincentBlondeau** [comment]
Failing tests not related:

image

**Review by MarcusDenker — APPROVED** [review]
Ok!

**Comment by VincentBlondeau** [comment]
Thanks Marcus!

**Pull request merged**
