### PR TITLE
Rewrite `== nil ifTrue:` to `ifNil:`

### PR DESCRIPTION
**Pull request by jecisc**
Simple changes

### CODE REVIEW

**Comment by Ducasse** [comment]
Cyril 
there are not simple and in particular we should not touch kernel methods. 
Why because == is not preempted while ifNil is a preemption point. 
With changes like that we got race conditions on servers after 2 weeks in the past. 
So we decided to pay attention to not touch kernel methods.

**Comment by MarcusDenker** [comment]
"== nil ifTrue:" is save to replace, as it is compiled the same as "ifNil:"

We have to be more careful to introduce new messages. e.g. replacing a "== nil" with isNil would introduce an interrupt check were none was before (e.g. GC can then happen). 

But this PR is save.

**Comment by Ducasse** [comment]
I saw that you did not modify the processList code.

**Comment by jecisc** [comment]
I tried in the past a PR that was replacing both `== nil ifTrue:` and `== nil` and it failed. In between I learned that `== nil ifTrue:` is safe to update as said Marcus so it's the reason I did a PR with only those :)

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
