### PR TITLE
Cleanup: Condense Athens- package

### LINKED ISSUE #12189: Cleanup: Condense Athens- package
- using the cleanup to remove unnecessary tabs, spaces and final dots in methods

### PR DESCRIPTION
**Pull request by astares**
Fix #12189

### CODE REVIEW

**Comment by astares** [comment]
image

**Comment by gcotelli** [comment]
The overall changes look good to me. @astares, may I ask why there's now a need to declare `ffiLibraryName` in several classes but no actual senders are added in this PR?

**Comment by astares** [comment]
@gcotelli Strange. The code changes should only be removals of unnecessary tabs, spaces after expressions and removal of final dots. No direct code changes.

I applied it using the following script

```Smalltalk
cms := CompiledMethod allInstances select: [:each |
each package ifNil: [ false ] ifNotNil: [:p |
	p name beginsWith: 'Athens-'
 ]
].

cms do: [:cm |
  ((RBRefactoryChangeFactory instance)
addMethodSource: (ReMethodSourceCleaner clean: cm sourceCode) in: cm methodClass) execute ]
```

maybe there is some other deprecation transformation happening as a side effect.

Can you show a screenshot or point me to an example?  So I can see more clearly about a side effect?

**Comment by astares** [comment]
Ah OK. I see 

image

but I do not know how this got added.

Need to investigate - **DO NOT INTEGRATE FOR THE MOMENT**

**Comment by astares** [comment]
Lets close this PR and use  https://github.com/pharo-project/pharo/pull/12200

which does not have the additional #ffiLibraryName (which seems to be coming from trait TCairoLibrary)

**Pull request closed without merging**
