### PR TITLE
Ensure methods are in a protocol

### PR DESCRIPTION
**Pull request by jecisc**
All methods should be in a protocol when installed in a class.  Currently, this is not the case. Some methods are added silently and never added to the class protocols. Then we have hacks that check if a method is classified or not in the protocol management.

Here I ensure that if a method is not classified while been added to a class, we put it in the unclassified protocol.  If the method is installed by Opal or if the method was already classified in the past, then this will do nothing.

I hope that this move will help me to deal with the hacks in protocols preventing me from simplifying further the protocol management.

### CODE REVIEW

**Comment by jecisc** [comment]
It works but the CI time increased a lot :/ 

I'm not sure it's a good move to integrate the change in that state

**Comment by MarcusDenker** [comment]
The whole point of #addSelectorSilently:withMethod: is to *not* raise any announcements. That's why it is called "silent".

**Comment by jecisc** [comment]
Yes indeed. I need to see what is the best plan here.
I think I'll pause that and do other cleanup to see what is the best way to do this.
Either fix the sender to categorize the method. Or classify silently. Or maybe both. Fix some senders that should announce classification and classify silently for the few cases that are left. 

It's still hard to find really the places that add methods without classifying them so I need to investigate that before pushing this PR.

**Comment by MarcusDenker** [comment]
With "silent" means no Announcing, why whould you need to turn off the announcer for calling  ClassOrganization>>#silentlyClassify:under: ? 

Following the "silently" idea, it should do whatever it does without announcing anything.

**Pull request closed without merging**
