### PR TITLE
[IGNORE] 4941b-withoutGT

### PR DESCRIPTION
**Pull request by pavel-krivanek**
This is a testing PR to prove that we are able to build an image without Glamour, GT and dependants (Iceberg, Catalog)

### CODE REVIEW

**Comment by Ducasse** [comment]
👍

**Comment by Ducasse** [comment]
So pavel can I close this issue?

**Comment by pavel-krivanek** [comment]
I created this PR mainly to let build some image that Esteban can use for his work. On Wednesday, I asked him if it is still needed. He had not much time to work on this topic. I think we should keep it and let him close this PR.

**Comment by Ducasse** [comment]
OK. I did not know. Perfect for me.

**Comment by estebanlm** [comment]
yes, we will comeback to this later, when I can commit more time. 
In the meantime, @pavel-krivanek, do not remove this branch from your fork! :)

**Pull request closed without merging**
