### PR TITLE
Revert "22679-Metacello-attributes-should-be-based-on-SystemVersion-instead-of-hardcoding"

### PR DESCRIPTION
**Pull request by estebanlm**
Reverts pharo-project/pharo#1999

### CODE REVIEW

**Comment by MarcusDenker** [comment]
yes, green!

**Comment by jecisc** [comment]
Do you have a copy of the failing build? Because the check was green at the time we integrated this PR. I would like to understand where is the problem. 
Maybe we use the Metacello attributes before setting the system version? But in that case, why the check was green?

**Comment by MarcusDenker** [comment]
every CI test run now fails with

Errors in script loaded from /builds/workspace/uest_and_branch_Pipeline_PR-2032/32/bootstrap/scripts/bootstrap.st'
[32] MessageNotUnderstood: EPUndeclaredBinding>>markWrite
[32] EPUndeclaredBinding(Object)>>doesNotUnderstand: #markWrite


We can not integrate anymore as all tests of all PRs are read. Only this one now is green again

**Comment by MarcusDenker** [comment]
my theory is that it leads to an Undeclared in the bootstrap somehow. And that triggers a bug with the bootstrap that makes the bootstrap fail

**Comment by MarcusDenker** [comment]
it actually triggers a bug in the bootstrap: the bootstrap is broken when there are undeclared as the are managed somehow with subclasses of Association (EPUndeclaredBinding), but this should be a subclass of LiteralVariable instead.

But I do not even know where that class comes from, the I can not fix it. (it is not on the image)

**Comment by estebanlm** [comment]
anyway, I will integrate :)

**Comment by tesonep** [comment]
To fix it, it should be an extension method in Metacello, not a method in the kernel. It is adding a new dependency with SystemVersion and this is not handled.

**Pull request merged**
