### PR TITLE
Deprecate unused method asUncommentedCode

### PR DESCRIPTION
**Pull request by hernanmd**
Reported in #16029 this method has no users and it is a reminiscent of the old SmalltalkEditor, not present anymore in Pharo 12.

### CODE REVIEW

**Review by jecisc — COMMENTED** [review]
I wonder if this should not be done via deprecation

**Comment by hernanmd** [comment]
> I wonder if this should not be done via deprecation

I checked Github and couldn't find users. Maybe on GitLab but I don't find a critical usage scenario neither.
So I don't know.

**Comment by astares** [comment]
As it is impossible to check all users (all public repos or private projects) using a deprecation is the better practice

**Comment by hernanmd** [comment]
> As it is impossible to check all users (all public repos or private projects) using a deprecation is the better practice

Done

**Comment by jecisc** [comment]
Some class renaming got mixed up in the last commit I think

**Comment by astares** [comment]
@hernanmd 
When you not only deprecate it but also change the package to "Deprecated12" (so it becomes an extension on String from this package) it will also get removed in Pharo 13 iteration when "Deprecated12" package is removed and a new "Deprecated13" package is created. 

This way we typically keep the method as deprecated method within next release (here Pharo 12). This give users a chance to migrate when moving from P11 to P12 to P13. Then in P13 release it will not be there anywmore. So we keep the deprecated for a single iteration before removing.

**Comment by hernanmd** [comment]
> @hernanmd When you not only deprecate it but also change the package to "Deprecated12" (so it becomes an extension on String from this package) it will also get removed in Pharo 13 iteration when "Deprecated12" package is removed and a new "Deprecated13" package is created.
> 
> This way we typically keep the method as deprecated method within next release (here Pharo 12). This give users a chance to migrate when moving from P11 to P12 to P13. Then in P13 release it will not be there anywmore. So we keep the deprecated for a single iteration before removing.

Thank you for the suggestions. If I understood correctly the deprecation process I will move the method to Deprecated12.

**Review by astares — APPROVED** [review]

**Comment by hernanmd** [comment]
Replaced by #16081

**Pull request closed without merging**
