### PR TITLE
update Spec2 to 0.2.0

### PR DESCRIPTION
**Pull request by estebanlm**
update Spec2 to 0.2.0 and Commander2 to 2.1.0: 

- Add search capabilities to tables, lists and trees
- Make `SpComponentListPresenter` behave as a list (actionable, selectable, searchable)
- `SpEditableList` renamed to `SpEditableListPresenter` (and make it work)
- Toggle buttons now can have icons (for some reason it was not allowing them before)
- Radio buttons now accept an initial state of "none selected"
- `SpCodePresenter` now have more actions defined.
- Dialogs now can define a "default" button (which will be executed on meta+s)
- Trait names renamed to match code conventions (prefix is `SpT` and not `TSp`)

### CODE REVIEW

**Comment by Ducasse** [comment]
Hi esteban threre a re probems but mainly with dependencies and release tests

**Comment by Ducasse** [comment]
We have 
windows-32 / Tests-windows-32 / testChangeListInPresenterUpdatesWidget – Windows32.Spec2.Backend.Tests.SpTableCommonPropertiestTest and some setting persistent tests that are broken

**Comment by estebanlm** [comment]
ok, I have a green test :)

**Comment by MarcusDenker** [comment]
This PR breaks the predebug window of the Debugger. It is used when executing 

self notify: 'hi'

I will add an issue for that

**Pull request merged**
