### PR TITLE
Use ACM Code of Ethics and Professional Conduct

### PR DESCRIPTION
**Pull request by jgfoster**
Could we use something less controversial?

### CODE REVIEW

**Comment by estebanlm** [comment]
Hi @jgfoster, thanks for this. 
I think this is a step in the right direction but I find it a bit bloated :P 
Can't we just use the one proposed by Yukihiro Matsumoto, Ruby's creator as base?

> Contributor Code of Conduct
> 
> As contributors and maintainers of this project, and in the interest of fostering an open and welcoming community, we pledge to respect all people who contribute through reporting issues, posting feature requests, updating documentation, submitting pull requests or patches, and other activities.
> 
> We are committed to making participation in this project a harassment-free experience for everyone, regardless of level of experience, gender, gender identity and expression, sexual orientation, disability, personal appearance, body size, race, ethnicity, age, religion, belief, or nationality.
> 
> Examples of unacceptable behavior by participants include:
> 
> The use of sexualized language or imagery
> Personal attacks
> Trolling or insulting/derogatory comments
> Harassment
> Publishing other's private information, such as physical addresses, without explicit permission
> Other unethical conduct
> Project maintainers may remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct.
> 
> Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting a project maintainer at [INSERT EMAIL ADDRESS]. All complaints will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances. Maintainers are obligated to maintain confidentiality with regard to the reporter of an incident.

Honestly, it feels a lot better for me :)

**Comment by noha** [comment]
For me, too

**Comment by astares** [comment]
Yes

**Comment by Ducasse** [comment]
Frankly I do not see the point of the CoC of ruby. Do we care to have one in that case?
I like this part in the ACM one

Computing professionals should consider whether the results of their efforts will respect diversity, will be used in socially responsible ways, will meet social needs, and will be broadly accessible. They are encouraged to actively contribute to society by engaging in pro bono or volunteer work that benefits the public good.

**Comment by Ducasse** [comment]
I prefer the ACM one because it has this notion of social needs. 
The one of ruby is just a welcome and be nice. So we could just have "welcome and be nice with others"

**Comment by estebanlm** [comment]
@Ducasse, Yes, but in exchange, it has some notions of "professional responsibilities" I found arguably and not matching well for an open source community (it was written in 92, after all).

**Comment by estebanlm** [comment]
Maybe we can complement Yukihiro's proposal with the concept of social needs you like?
 For me a "welcome and be nice" should be enough to just continue as before. I find the introduction of CoC was a noise we didn't need, our community was doing well and self-regulated without problem until now.

**Comment by noha** [comment]
@Ducasse I don't think such a text can be more about "welcome and be nice". The community has to actively maintain the culture. So a text with more detail does not serve the bigger need. If someone is not nice we explain that as we did before and finger point to that little text.

**Comment by gnaritas** [comment]
> Do we care to have one in that case?

There's frankly no need for one; the community has been fine all these years without one and no one has yet made a valid case there even is such a need, or any case at all. Just delete the thing and be done with it. The only purpose of a code of conduct is to enable enforcement of it, it's authoritarian thought policing in a community that has no need for it.

**Comment by eleitl** [comment]
> There's frankly no need for one; the community has been fine all these years without one and no one has yet made a valid case there even is such a need, or any case at all. Just delete the thing and be done with it. The only purpose of a code of conduct is to enable enforcement of it, it's authoritarian thought policing in a community that has no need for it.

Exactly. There is no need for a CoC, so don't fix what's not broken. 

Inversely, the main reason why CoCs are introduced is for subversion of organizations and communities by machiaviellian sociopaths. 

I don't know Serge Stinckwich from Adam, but this reply does makes me wonder whether he's such a machiavellian sociopath, or a useful idiot.

> I'm the one who submit the PR for the CoC. Similar text are adopted by a                                                                                                                       
lot of open-source communities or conferences in order to enhance diversity.                                                                                                                   
I read again this morning the document here:                                                                                                                                                   
https://github.com/pharo-project/pharo/blob/Pharo8.0/CODE_OF_CONDUCT.md                                                                                                                        
and for me this quite neutral and I see nothing political here.                                                                                                                                
I agree with you that this kind of document should have been discussed by                                                                                                                      
the Pharo board and you can propose it for the next meeting.                                                                                                                                   
                                                                                                                                                                                               
I'm a bit suprised by some overeactions here on the mailing-list.                                                                                                                              
Apparently the Pharo community will be soon be doomed or under attack of                                                                                                                       
nasty leftist activists ...                                                                                                                                                                    
But I will not discuss endlessly about that.

**Comment by Ducasse** [comment]
Hi I'm sorry but as a rule I do not talk to foreigners that do not present themselves and you can keep for yourself your statements about Serge Stinckwich! Period. You look like these right party activists that have nothing to do with our projects (Same apply for left-activists but so far they did not talk to us). So I do not care about what you can say and think and I do not talk with people with an empty github account!!! 
@esteban @norbert I agree with you.

**Comment by Ducasse** [comment]
@esteban I found quite funny that the ACM had such strong "social responsible" CoC. It is really a surprise to me. I would not follow it because it is far too much elaborated but it is nice to know. To me it is far more advanced that the one under scrutiny. Thanks James for the pointer.

**Comment by estebanlm** [comment]
just as explanation, Stef was answering to a troll that entered this thread. 
Troll is blocked and comment is now removed, that's why his comment looks out of place.

**Comment by noha** [comment]
Yes, but I think we are over the point that we want to use ACM. So this can be closed

**Comment by bencoman** [comment]
Thanks James for providing an alternative, but I also find it too verbose.  I only got a quarter way through it before I lost interest, so the rest was of no use.  I believe for a CoC to have real impact, its needs to be shorter and punchier - similar to a Mission Statement.  

Having a CoC is useful mostly because in today's world not having one can be a troublesome vacuum, plus it provides a baseline expectation to refer to.  

I prefer GoLang's adaption (https://golang.org/conduct), particularly the priority of goals spelled out in the "About" introduction, and the way the "Enforcement" section is replaced by "Conflict Resolution" 

The Linux CoC sidebar has some good points (https://www.kernel.org/doc/html/latest/process/code-of-conduct-interpretation.html#code-of-conduct-interpretation)

Maybe it could be as simple as...
https://dart.dev/code-of-conduct

<blockquote><div><strong><a href="https://golang.org/conduct">Go Community Code of Conduct - The Go Programming Language

Search</a></strong></div><div>Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.</div></blockquote>
<blockquote><div><strong><a href="https://www.kernel.org/doc/html/latest/process/code-of-conduct-interpretation.html#code-of-conduct-interpretation">Linux Kernel Contributor Covenant Code of Conduct Interpretation — The Linux Kernel  documentation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://dart.dev/code-of-conduct.html">Code of conduct</a></strong></div><div>Be excellent to each other.</div></blockquote>

**Comment by gnaritas** [comment]
> I believe for a CoC to have real impact

And what does impact mean other than targeting the community for people to exclude?

> Having a CoC is useful mostly because in today's world not having one can be a troublesome vacuum

If that's the best reason one can come up to justify its existence, it sounds like not a valid reason.  If you want a CoC, at least try and justify the need for it with some actual reasoning and evidence that one is needed rather than just hopping on the bandwagon of "today's world".

Who do you want ejected from the community?  That's what a CoC is for, to setup rules to justify getting rid of people. Where's any evidence at all anywhere that a CoC is needed to keep this community civil? Anything?

**Comment by estebanlm** [comment]
Ok, since this has taken too much time, we believe this new proposal (#4660) will be satisfying for everybody. 
Thanks again @jgfoster to think about this in a positive (and proactive) way, but we believe that for now at least, the ACM code is too verbose.

**Comment by jgfoster** [comment]
I'm very satisfied with this outcome. My primary goal was moving from negative talk on the mailing list to positive/proactive Pull Requests. The choice of ACM not so important; I mostly wanted to demonstrate that anyone could propose an improvement!

**Pull request closed without merging**
