### PR TITLE
21269 Provide tags in package Announcements-Core for better structure

### PR DESCRIPTION
**Pull request by astares**
https://pharo.fogbugz.com/f/cases/21269/Provide-tags-in-package-Announcements-Core-for-better-structure

### CODE REVIEW

**Comment by astares** [comment]
Only tagging, no change in behavior

**Comment by Ducasse** [comment]
Hi torsten 
Please do not do empty commit because it will make our life more difficult when chasing parent commits.

**Comment by Ducasse** [comment]
I'm not sure that it is worth to have 3 tags for 10 classes in total.

**Comment by astares** [comment]
Sure it is worth - because giving a package structure means to give also informations to the users.
This is independent from the number of contained classes.

**Pull request merged**
