### PR TITLE
Conditional breakpoints: refactoring, and alllowed the use of 'super'…

### PR DESCRIPTION
**Pull request by dupriezt**
… in the condition (that will work as expected). Also added tests.

### CODE REVIEW

**Comment by dionisiydk** [comment]
Hi. You should contribute to Calypso. Look at ClyAddConditionalBreakpointCommand which requires your changes.
Suggestions are kind of deprecated with Calypso.

**Comment by MarcusDenker** [comment]
Yes, for Calypso I wanted to look into it. I think we should move more if the implementation to the breakpoint class (or a subclass). 

I will review this first, the calypso change is then one of the next steps

**Comment by dupriezt** [comment]
I looked a bit into the calypso conditional breakpoint.
One thing I noted is that it attempts to execute the condition before installing the breakpoint, to make sure it returns a boolean before proceeding.
The problem with that is that if the condition sends a message to an object that does not exist yet (for example the content of a variable), it raises a DNU and prevents the breakpoint installation.

**Comment by dupriezt** [comment]
Another thing is that, hm, calypso conditional breakpoints do not work?
I set one with 'true' as the condition, and executing the code containing it did not trigger it.

**Comment by MarcusDenker** [comment]
calypso just uses the old code... before your changes.

**Comment by dionisiydk** [comment]
Everything can be changed.
And yes, I know about problem. But it was same in Nautilus. I just copied implementation with a bit of extra logic which can be removed

**Comment by MarcusDenker** [comment]
I merge this and then will help moving the code to Calypso.

**Pull request merged**
