### PR TITLE
Fix missing users of shared pools 

### PR DESCRIPTION
**Pull request by hernanmd**
This PR implements a query to browse the class references to a shared pool, using Ctrl/CMD + N on the selected pool name, as reported by @Ducasse in ##16991.

It also includes tests in `ClySharedPoolReferencesQueryTest`.

### CODE REVIEW

**Review by jecisc — APPROVED** [review]

**Comment by Rinzwind** [comment]
This seems to have broken the use of ⌘N in a browser to find senders of a selector, that doesn’t work anymore in builds 186 and 183, while it does work in build 182.

**Comment by hernanmd** [comment]
Thanks for reporting. Please don't revert this I will fix ASAP in another PR

**Comment by Rinzwind** [comment]
Thanks, it works again in build 187.

**Comment by Ducasse** [comment]
I see this is on the class definition pane! Tx

**Pull request merged**
