### PR TITLE
3186-UFFI-Rename-FFIExternalObject-into-FFIExternalPointer-and-deprecate-old-name

### LINKED ISSUE #3186: UFFI Rename FFIExternalObject into FFIExternalPointer (and deprecate old name)
According to a Discord discussion between "hfreyther" and @estebanlm:

 - FFIExternalObject has a bad name
 - and it should be named FFIExternalPointer

image

So I suggested for Pharo 8 to rename **FFIExternalObject** into **FFIExternalPointer**, and create an empty subclass FFIExternalObject which we can then deprecate so we have a transition path to a better name

image

### PR DESCRIPTION
**Pull request by estebanlm**
fixes #3186
sneak  in missing FFILiteralArgument>>emitArgument: context: objectClass:instVarName:

### CODE REVIEW

**Comment by guillep** [comment]
This impacts the booklet https://github.com/SquareBracketAssociates/Booklet-uFFI/

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/SquareBracketAssociates/Booklet-uFFI">SquareBracketAssociates/Booklet-uFFI</a></strong></div><div>about the new Unified FFI frameworks. Contribute to SquareBracketAssociates/Booklet-uFFI development by creating an account on GitHub.</div></blockquote>

**Comment by estebanlm** [comment]
there are no references to `FFIExternalObject` in the booklet

**Comment by guillep** [comment]
> there are no references to `FFIExternalObject` in the booklet

Ok!

For the failing build, it seems it's because of the class-side `initialize` order after loading in SDL2 & co... Maybe something in the PR alters the order in which monticello initializes the classes?
I don't know what the order would be...

Maybe this was working until now because we are lucky...
We should check

````
MCMethodDefinition>>postloadOver:
...
OrderedCollection(Collection)>>do:displayingProgress:
[64] MCPackageLoader>>basicLoadDefinitions
[64] [self basicLoadDefinitions] in MCPackageLoader>>basicLoad in Block: [self basicLoadDefinitions]
[64] [ aBlock value ] in SourceFileArray>>deferFlushDuring: in Block: [ aBlock value ]
[64] BlockClosure>>ensure:
[64] SourceFileArray>>deferFlushDuring:
[64] MCPackageLoader>>basicLoad
```

**Comment by estebanlm** [comment]
I will comeback to this later

**Pull request closed without merging**
