### PR TITLE
17033 Requesting references to globals in Calypso raises error

### PR DESCRIPTION
**Pull request by demarey**
https://github.com/pharo-project/pharo/issues/17033

### CODE REVIEW

**Comment by hernanmd** [comment]
Your PR replacement does not work. This is the result when I click CMD+N on a selected pool: 

Screenshot 2024-08-30 at 11 38 14

The result should be:

Screenshot 2024-08-30 at 11 40 53

I propose to re-open my original PR or re-work this to make it work.

**Comment by demarey** [comment]
Good catch, I forgot the value message. Should now work as expected

**Comment by hernanmd** [comment]
Why this is still failing?

**Comment by demarey** [comment]
You should show me because it works in my image

**Comment by jecisc** [comment]
The failing test is unrelated

**Review by jecisc — APPROVED** [review]

**Pull request merged**
