### PR TITLE
21259-Add-an-option-to-protect-by-password-command-lines-for-deployment

### PR DESCRIPTION
**Pull request by jecisc**
First try to the implementation of a password protection to command line.

The password is hashed with pepper and iterations. 

Case 21259 : https://pharo.fogbugz.com/f/cases/21259/Add-an-option-to-protect-by-password-command-lines-for-deployment

### CODE REVIEW

**Comment by jecisc** [comment]
I need to do more test on this. I'll way images generated by the CI to test more. 

I would like a good review also before any merge. Maybe @VincentBlondeau will be interested.

**Comment by VincentBlondeau** [comment]
MessageNotUnderstood: BasicCommandLineHandler>>mustBeBooleanInMagic:
BasicCommandLineHandler(Object)>>doesNotUnderstand: #mustBeBooleanInMagic:
BasicCommandLineHandler(Object)>>mustBeBoolean
BasicCommandLineHandler>>handleSubcommand
BasicCommandLineHandler>>handleArgument:

**Comment by VincentBlondeau** [comment]
Tests need to be added

**Comment by jecisc** [comment]
/!\ DO NOT MERGE /!\ 
At the begining of next week I'll try to add some tests and do some corrections. 

For example currently the method #removePasswordProtection will just throw a DNU.

**Comment by estebanlm** [comment]
please edit the PR name once you are ready for integration

**Comment by jecisc** [comment]
@estebanlm Does the CI failure comes from the title renamed?

**Comment by tesonep** [comment]
@jecisc it has failed with a comunication problem in the Jenkins

Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to pharo-ci-jenkins2-bootstrap-unix-2
[32] 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1693)
[32] 		at hudson.remoting.UserResponse.retrieve(UserRequest.java:310)
[32] 		at hudson.remoting.Channel.call(Channel.java:908)
[32] 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
[32] 		at sun.reflect.GeneratedMethodAccessor213.invoke(Unknown Source)
[32] 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[32] 		at java.lang.reflect.Method.invoke(Method.java:498)
[32] 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
[32] 		at com.sun.proxy.$Proxy103.execute(Unknown Source)
[32] 		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1083)
[32] 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1123)
[32] 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:109)
[32] 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:83)
[32] 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:73)
[32] 		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
[32] 		at hudson.security.ACL.impersonate(ACL.java:260)
[32] 		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
[32] 		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

**Comment by jecisc** [comment]
@tesonep Can I do something about it?

**Comment by tesonep** [comment]
Just wait... the CI is a little unstable now, I am trying to clean it up because there are a lot of merged PRs taking disc space. I will retried this job.

**Comment by jecisc** [comment]
When CI and @VincentBlondeau will validate, we can remove the [IGNORE] in the title.

**Comment by tesonep** [comment]
https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-816/9/ have failed because the package System-BasicCommandLineHandler-Tests is added as a package in the BaselineOfIDE but never referenced in a group. So, it is never loaded in the image and the checking of dependencies fails. Also if you check, the tests are never running.

**Comment by jecisc** [comment]
Ok, I'll see to correct that. Maybe tomorrow, maybe today.

**Review by VincentBlondeau — APPROVED** [review]
Only if the jenkins is ok

**Comment by jecisc** [comment]
@estebanlm Ready

**Pull request merged**
