### PR TITLE
fix 8661: enables IM support in SDL2

### PR DESCRIPTION
**Pull request by tomooda**
This PR provides support for IM-related support for SDL2 library, and solves https://github.com/pharo-project/pharo/issues/8661 .

Some natural languages needs a support agent so-called IM to input letters/symbols including emojis.
IMs are most often provided by OSs and Desktop environments, including macOS, Linux desktops and Windows platforms.
IM accepts keyboard inputs and offers candidate letters/symbols/strings so that the user can choose what should be poured into a text widget.

SDL2 provides a generic API to support IMs.
An SDL2 application should respond to two events: TextEditing and TextInput.
TextEditing is triggered when the user is choosing from candidate strings, and TextInput is triggered when the choice is done.

This PR is to define the events at different layers of frameworks (SDL and morphic) and implements handlers for them.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Strangely the tests do not finish running and the CI runs are aborted

**Comment by MarcusDenker** [comment]
We need to to find out why the tests can not be run on the CI. I marked it "needs more work" for now.

**Comment by tomooda** [comment]
I found an obsolete instance of MyTestClass is making some troubles. Also found some other problems. I'll dig them out, and then update this PR.

**Comment by MarcusDenker** [comment]
Tests look good now! the two failing tests seem to be not related:

- known failing test on linux for Roassal
- timeout testWorkerPoolDoesNotExceedPoolSizeWhenSchedulingTasksInParallel

**Pull request merged**
