### PR TITLE
Add `newTenured` allocation methods

### PR DESCRIPTION
**Pull request by jordanmontt**
This is the same as https://github.com/pharo-project/pharo/pull/14994
But with the merging conflicts solved

### CODE REVIEW

**Comment by jordanmontt** [comment]
This is ready to merge !

**Comment by jecisc** [comment]
It might be nice to add tests if possible :)

**Comment by jordanmontt** [comment]
i don't know how to test this. But there are tests on the VM-side

**Comment by jordanmontt** [comment]
Maybe one test that tests that the object is allocated? But we are not able to test if the object is in the old space from the image-side

**Pull request merged**
