### PR TITLE
Creating a user interface for Time Profiler and Andreas Profiler

### PR DESCRIPTION
**Pull request by carolahp**
Porting to Pharo11 the solution proposed in PR #11621

### CODE REVIEW

**Comment by carolahp** [comment]
> This issue has either a default title or empty body. We would appreciate it if you could provide more information. Note: I am not a very intelligent bot, I can only react to new comments. Please add a comment for me if you update the body or title.

Added description to PR

**Comment by Ducasse** [comment]
Hi caro 
there are two tests related

```
Error

Found undeclared Variables:  SpMethodToolbarPresenter in: AbstractMessageCentricBrowser>>#initializePresenters
Stacktrace

TestFailure
Found undeclared Variables: 
SpMethodToolbarPresenter in: AbstractMessageCentricBrowser>>#initializePresenters
ReleaseTest(TestAsserter)>>assert:description:resumable:
ReleaseTest(TestAsserter)>>assert:description:
ReleaseTest>>testUndeclared
ReleaseTest(TestCase)>>performTest
```

and (but it does not look related)

```
Error

the following classes have uncategorized methods: an OrderedCollection(LGitMessageDecoder class)
Stacktrace

TestFailure
the following classes have uncategorized methods: an OrderedCollection(LGitMessageDecoder class)
ProperMethodCategorizationTest(TestAsserter)>>assert:description:resumable:
ProperMethodCategorizationTest(TestAsserter)>>assert:description:
ProperMethodCategorizationTest>>testNoUncategorizedMethods
ProperMethodCategorizationTest(TestCase)>>performTest
```

**Comment by Ducasse** [comment]
Ok I saw that the first failing test is related to spec and not your PR.
So I will integrate it so that we move.

**Comment by Ducasse** [comment]
Caro can you redo a PR for Pharo 11?

**Comment by carolahp** [comment]
> Caro can you redo a PR for Pharo 11?

This PR is for Pharo 11. Should we PR in Pharo 10 after some time testing in P11?

**Comment by Ducasse** [comment]
No we only push to P11.
@MarcusDenker I do not get because caro is saying that this PR for P11 but you revert it because it went in P10 branch.

**Comment by MarcusDenker** [comment]
There are two PRs: one against Pharo10, wrongly merged weeks ago, a new one (this) merged in Pharo11,

I reverted the Pharo10 (that is, there is a PR, it can only be merged after the CI is working again)

**Comment by Ducasse** [comment]
Ok I got confused because I thought that you reverted the one I just merged!
So everything is good then.

**Pull request merged**
