### PR TITLE
Changed 'Transcript show:' construct to 'self trace'

### PR DESCRIPTION
**Pull request by PosledniAmir**
Hello, I would like to start contributing, I have picked this [issue 15843](https://github.com/pharo-project/pharo/issues/15843), where the goal was to find usage of `Transcript show: 'message'` and change it to something like `'message' trace`.

### CODE REVIEW

**Comment by Ducasse** [comment]
Thank you! This is really nice to want to help.

**Review by jecisc — APPROVED** [review]

**Comment by jecisc** [comment]
I'm closing and reopening because the CI did not kick in

**Review by MarcusDenker — APPROVED** [review]

**Comment by jecisc** [comment]
This PR introduced a failing test that is testCodeCruftLeftInMethods

**Comment by jecisc** [comment]
I've a PR ready to fix this

**Pull request merged**
