### PR TITLE
[Testing] Modifying the script to use the latest VM

### PR DESCRIPTION
**Pull request by tesonep**
Do not integrate, this PR is just to test the latest VM with the bootstrap process

### CODE REVIEW

**Comment by jecisc** [comment]
Today there was a pre release of the vm: http://forum.world.st/ANN-Pre-release-201804030952-td5072867.html

Maybe we could have a PR to test this one?

On files.pharo.org it is those vms:

Win 32 :  http://files.pharo.org/vm/pharo-spur32/win/pharo-win-i386-201804030952-29f50cf.zip

Win 64 : http://files.pharo.org/vm/pharo-spur64/win/pharo-win-x86_64-201804030952-29f50cf.zip

Linux 32 : http://files.pharo.org/vm/pharo-spur32/linux/pharo-linux-i386threaded-201804030952-29f50cf.zip

Linux 64 : http://files.pharo.org/vm/pharo-spur64/linux/pharo-linux-x86_64threaded-201804030952-29f50cf.zip

OSX 32 : http://files.pharo.org/vm/pharo-spur32/mac/pharo-mac-i386-201804030952-29f50cf.zip

OSX 64 :  http://files.pharo.org/vm/pharo-spur64/mac/pharo-mac-x86_64-201804030952-29f50cf.zip

**Comment by guillep** [comment]
Hi @jecisc this is what this pr is doing. Those VMs are in latest since yesterday night.

**Comment by jecisc** [comment]
I think there was new release after the one tagged as prerelease. (for win 32 for example I see that the latest is this one: http://files.pharo.org/vm/pharo-spur32/win/pharo-win-i386-201804032021-0ce1378.zip)

But it's probable that they are almost the same since they were built the same day :)

**Comment by akgrant43** [comment]
Hi Pablo,

Could we try running this with:

```
Date: Tue Apr 10 07:27:57 2018 +0200 $ CommitHash: 1c16013 $
```

I think this could be a candidate for a new stable VM.

Thanks,
Alistair

**Comment by MarcusDenker** [comment]
can this now be closed?

**Comment by estebanlm** [comment]
I will close this since is not needed anymore (at least for the moment).

**Pull request closed without merging**
