### PR TITLE
4735-Implement-pcRange-on-Context-using-sourceNodeExecuted

### LINKED ISSUE #4735: Implement pcRange on Context using #sourceNodeExecuted
We have right now #pcRangeContextIsActive: on Context. This means that the highlight of the debugger depends on the UI to tell if the context is the top most context or not.

But we have already #sourceNodeExecuted, which returns exactly the right AST node.

We thus could implement pcRange on Context as:

^self sourceNodeExecuted debugHighlightRange

and remove quite some code that is not needed anymore

### PR DESCRIPTION
**Pull request by MarcusDenker**
- implement pcRange for context in terms of #sourceNodeExecuted
- remove all not needed code

fixes #4735

### CODE REVIEW

**Comment by MarcusDenker** [comment]
tests are green

**Comment by MarcusDenker** [comment]
I merge this so we can test it tomorrow at the sprint

**Comment by jecisc** [comment]
80BBDCE9-C3B2-4F59-9D58-CD92D3059C04

I don’t know if it is related but I got this in Moose CI today

**Comment by MarcusDenker** [comment]
This means that moose uses low level things it should not.

**Comment by MarcusDenker** [comment]
There was *never* a reason to use the debuggerMap directly, all the methods always have been on Context.

**Comment by jecisc** [comment]
The origin in the stack was an #assert:equals:description:

**Comment by jecisc** [comment]
Maybe it is SmalltalkCI that is using it wrongly.

**Comment by jecisc** [comment]
https://github.com/hpi-swa/smalltalkCI/blob/master/repository/SmalltalkCI-Pharo-Core.package/SCIPharoTestRunner.class/instance/stackTraceString.of..st

Do you know what should be the replacement?

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/hpi-swa/smalltalkCI">hpi-swa/smalltalkCI</a></strong></div><div>Framework for testing Smalltalk projects on Linux, macOS, and Windows and on Travis CI, AppVeyor, and GitLab CI/CD. - hpi-swa/smalltalkCI</div></blockquote>

**Comment by MarcusDenker** [comment]
Maybe we can add a departed version with transformations for the #debuggerMap methods...

**Comment by MarcusDenker** [comment]
pcRange := context debuggerMap rangeForPC: context pc contextIsActiveContext: false.

is now just

pcRange := context pcRange.

**Comment by MarcusDenker** [comment]
but that does not exist in Pharo7

**Comment by MarcusDenker** [comment]
I will back port it.

**Comment by jecisc** [comment]
We will have to manage it somehow because SmalltalkCI run on much older Pharo versions.

**Comment by MarcusDenker** [comment]
add back the method for now: https://github.com/pharo-project/pharo/pull/4756

**Pull request merged**
