### PR TITLE
Fix for:  UFFI/TFFI call for WebBrowser with specific URL length adds strange characters to the URL #15980

### PR DESCRIPTION
**Pull request by VincentBlondeau**
Pushing to pharo 10.
Feel free to backport on pharo 11 and 12.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Pharo 12 fix was merged: https://github.com/pharo-project/pharo/issues/15980

**Comment by astares** [comment]
@VincentBlondeau be aware that you only change the String* to String in your PR #16253 which is slightly different from #16262 for a backport.

If you want to stay compatible with my changes in P12 you could/should also have the "int" definition for the first parameter. 

see: https://github.com/pharo-project/pharo/pull/16262/files for the diff

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo/pull/16262">FFIUnsupportedUntypedLiteral when using WebBrowser classes on Windows by astares · Pull Request #16262 · pharo-project/pharo</a></strong></div><div>fix #16261
fix #15980</div></blockquote>

**Comment by VincentBlondeau** [comment]
@astares Thanks for the review. I just changed the file so it is properly backported.

**Review by astares — APPROVED** [review]

**Comment by carolahp** [comment]
I have backported this solution to [Pharo 11](https://github.com/pharo-project/pharo/pull/16284).

I've checked and the solution was already backported to [Pharo 12](https://github.com/pharo-project/pharo/blob/a60aa3a0c27121a51d4d207491933574673f5622/src/WebBrowser-Core/WBWindowsWebBrowser.class.st#L27)

**Pull request merged**
