### PR TITLE
Cleanup newlines and blanks in "System" packages

### LINKED ISSUE #10922: Cleanup newlines and blanks in "System" packages
see #10396 and fix it for all "System" related packages:

```Smalltalk
badCases := SystemNavigation default allMethodsSelect: [ :each | each sourceCode trimRight size ~= each sourceCode size ].

fixInPackage := badCases select: [:each | each package name beginsWith: 'System' ].

fixInPackage do: [:each |
	| refactoring classOrTrait |
	classOrTrait := each traitSource ifNil: [ each methodClass ] ifNotNil: [ each traitSource innerClass ].
	refactoring := RBAddMethodChange compile: each sourceCode trimRight in: classOrTrait for: nil.				 
	refactoring execute	
]
```

### PR DESCRIPTION
**Pull request by astares**
Fix #10922

### CODE REVIEW

**Comment by Ducasse** [comment]
Apparently we get over the limit of request in non authenticated way :(

**Comment by astares** [comment]
@Ducasse What do you mean?

**Comment by Ducasse** [comment]
The build did not proceed with that kind of message

**Comment by Ducasse** [comment]
Ok it is passing.

**Pull request merged**
