### PR TITLE
Fit column width to content on double clicking a MorphTreeResizerMorph

### LINKED ISSUE #9604: Fit column width to content
A double click on a column resizer morph should fit the column width to the columns content.

### PR DESCRIPTION
**Pull request by bpieber**
This is my first pull request since three and a half years.
fixes #9604

### CODE REVIEW

**Comment by bpieber** [comment]
I updated the body of the pull request.

**Comment by bpieber** [comment]
I have no idea why the builds failed. From the logs it does not look related to my changes. Can someone more knowledgeable
please help me?

**Comment by MarcusDenker** [comment]
I restarted the CI run as the crash looks random

**Comment by Ducasse** [comment]
Thanks for this PR.

**Comment by Ducasse** [comment]
It would be really nice to have more tests for such part of the system. I read the code and the changes look ok to me.

**Comment by bpieber** [comment]
Thanks for the fast merge, Stéphane!

**Pull request merged**
