### PR TITLE
introduce a NullDebugger

### PR DESCRIPTION
**Pull request by demarey**

### CODE REVIEW

**Comment by guillep** [comment]
Build failed with error:

```
MessageNotUnderstood: SmalltalkImage>>tools
SmalltalkImage(Object)>>doesNotUnderstand: #tools
NoDebugger class>>register
NoDebugger class>>initialize
```

The `#tools` method is introduced by the `Tool-Base` package. It's maybe not available at the moment the class is introduced?

**Comment by Ducasse** [comment]
What we can do is to load the NoDebugger first and after the registration. 
BTW I hate this registration it is a disguised global variable.

**Comment by jecisc** [comment]
So what are the next steps to make this PR usable?

**Comment by MarcusDenker** [comment]
I think we need to have a time-out for PRs: keep the issue tracker entry, but close PRs if they are get very old

**Comment by estebanlm** [comment]
I will close this, please comeback when you finish a new version :)

**Pull request closed without merging**
