### PR TITLE
assert:equal: cleanups in FileSystem-Tests-Core

### LINKED ISSUE #3069: assert:equal: cleanups in FileSystem-Tests-Core package required

### PR DESCRIPTION
**Pull request by astares**
- use assert:equals:
- some unnecessary dots removed
- format one method

fixes #3069

### CODE REVIEW

**Comment by estebanlm** [comment]
please @astares add title not, just a number to the PR

**Comment by astares** [comment]
sorry

**Review by MarcusDenker — APPROVED** [review]
ok

**Comment by MarcusDenker** [comment]
this failing test seem related: 
PathTest>>testExtendingPath

**Review by MarcusDenker — APPROVED** [review]
tests are now ok

**Pull request merged**
