### PR TITLE
21711-Monticello-does-not-have-support-for-traits-with-slots

### PR DESCRIPTION
**Pull request by pavel-krivanek**
MC support for slots in traits

### CODE REVIEW

**Review by dionisiydk — APPROVED** [review]
Code looks fine

**Comment by ThierryGoubier** [comment]
No test on the FileTree format change. I've added an issue on FileTree.

**Comment by pavel-krivanek** [comment]
Thanks, I firstly wanted to let check it with CI to see what will it break

**Comment by ThierryGoubier** [comment]
@pavel-krivanek , if you manage to write a test case for FileTree, that would be great (a test package with a small test repo, and an oracle).

**Comment by pavel-krivanek** [comment]
well, my original assumptions were wrong. There was a bug in making a deep copy of metaclasses. Thanks

**Comment by dionisiydk** [comment]
Good. Thanks

**Pull request merged**
