### PR TITLE
22500-LinkedListrejectthenCollect-is-slow

### PR DESCRIPTION
**Pull request by vonbecmann**
Optimized version of SequenceableCollection>>#reject:thenCollect:

### CODE REVIEW

**Comment by juliendelplanque** [comment]
Did you benchmarked your change before/after to sustain the claim that this version is faster?

And to know how much master is it?

**Comment by vonbecmann** [comment]
you can test it if you want.
see https://pharo.fogbugz.com/f/cases/22500/LinkedList-reject-thenCollect-is-slow
to find the simple benchmark.

**Comment by juliendelplanque** [comment]
Thank you, I also benchmarked using this script run once before changing the method and once after:
```
allBenchs := OrderedCollection new.

(1000 to: 100000 by: 1000) do: [ :x |
	|benchs l|
	benchs := OrderedCollection new.
	l := LinkedList withAll: (1 to: x).
	
	50 timesRepeat: [
		benchs add: ([ l reject: #odd thenCollect: #yourself ] timeToRunWithoutGC) ].
	allBenchs add: x -> benchs ] displayingProgress: 'Bench'.

allBenchs
```

The optimised version seems to be really better than the original one, no need to show results, try to run it with and without the change you'll see the new version is far better.

Thank you for this optimisation!

**Review by juliendelplanque — APPROVED** [review]

**Comment by vonbecmann** [comment]
I'm stealing that benchmark. :)
LinkedList inherits from SequenceableCollection some unsuitable implementations.

**Pull request merged**
