### PR TITLE
Rotten green tests plugin for DrTests

### PR DESCRIPTION
**Pull request by aboubacardiawara**
> <<... rotten green tests guarantee nothing: they give a bogus feeling of confidence ...>>
>
> -- <cite>extracted [here](https://rmod-files.lille.inria.fr/Team/Texts/Papers/Delp19a-RottenGreenTests-ICSE2019-v2.pdf)</cite>.

In this PR, i create a DrTests plugin for Rotten green tests. The Rotten green tests finder was already implemented by @juliendelplanque and maintened by @tesonep for pharo 11. I used the package to create a plugin with.

rotten

### CODE REVIEW

**Comment by Ducasse** [comment]
This is super cool :)

**Comment by Ducasse** [comment]
Now I have to think how we can get the new packages loaded in P11 as part of DrTests

**Comment by Ducasse** [comment]
Thanks

**Comment by aboubacardiawara** [comment]
> Thanks

You're welcome

**Comment by aboubacardiawara** [comment]
I want this PR to be rebuilt that is why i'm closing it in order to reopen it then

**Comment by MarcusDenker** [comment]
Failing test not related
- #skipOnPharoCITestingEnvironment seems to not work on WIN and MAC #11425

**Pull request merged**
