### PR TITLE
Enable Fluid Class Definitions

### PR DESCRIPTION
**Pull request by MarcusDenker**
Enable Fluid by default.

The goal is to check of there are stll problems with tests

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Failing tests shown by this PR to be fixed:

- ChangeSetClassChangesTest>>testChangeClassCategory
- EpRevertTest>>testClassRemoval
- EpRevertTest>>testTraitRemoval
- RBRefactoringChangeTest>>testAddMetaclassPattern
- RBRefactoringChangeTest>>testAddTraitPattern

**Comment by Ducasse** [comment]
Nice to know. 
We should probably open an issue for each.

**Comment by Ducasse** [comment]
I cannot reproduce this one `ChangeSetClassChangesTest>>testChangeClassCategory`

**Comment by MarcusDenker** [comment]
I opened issues for al the TODO, I close this for now

**Pull request closed without merging**
