### PR TITLE
Update Roassal version v0.9.9m

### LINKED ISSUE #12790: Enhance roassal with version v0.9.9m
The current version of Roassal in Pharo 11 is 0.9.9L
Roassal3 has been improved to face integration with Pharo11

### PR DESCRIPTION
**Pull request by akevalion**
This pull request addresses the following issues:
- https://github.com/pharo-project/pharo/issues/12790
- https://github.com/pharo-project/pharo/issues/12572

Also this pull request needs this changes to be approved
- https://github.com/pharo-project/pharo/pull/12771

### CODE REVIEW

**Comment by jordanmontt** [comment]
Thanks Milton!!

**Review by jordanmontt — APPROVED** [review]

**Comment by MarcusDenker** [comment]
Failing tests:

```
ReleaseTest>>testUndeclared and RSSpecExamplesTest>>testRunExamples



Found undeclared Variables:  RSEasel in: RSSpecExamplesTest>>#testRunExamples RSLayoutDefinition in: RSAbstractCircleLayout class>>#layoutDefinition RSLayoutNumberField in: RSAbstractCircleLayout class>>#layoutDefinition RSLayoutAngleField in: RSAbstractCircleLayout class>>#layoutDefinition RSColorPaletteChooser in: RSSpecExamplesTest>>#testRunExamples RSPieChartExample in: RSSpecExamplesTest>>#testRunExamples




Error
receiver of "new" is nil
Stacktrace
MessageNotUnderstood
receiver of "new" is nil
UndefinedObject(Object)>>doesNotUnderstand: #new
UndefinedObject>>doesNotUnderstand: #new
[ :cls | cls new asWindow open delete ] in RSSpecExamplesTest>>testRunExamples
Array(SequenceableCollection)>>do:
RSSpecExamplesTest>>testRunExamples
RSSpecExamplesTest(TestCase)>>performTest
```

**Comment by MarcusDenker** [comment]
this is what i hate with "external packages": you can just never just fix a triviality. Fixing a trivial things always means a sync, and a sync always leads to problems.

**Comment by akevalion** [comment]
Thanks I will fix them in the morning

**Comment by akevalion** [comment]
I have update the code then these error should not be present, ci should verify the new changes

**Comment by jecisc** [comment]
[CI] testInstanceSideInitializeMethodNeedsToBeInInitializationProtocol started failing #12795
[CI] Fail on WIN random: OmSessionStoreTest(OmStoreTest)>>testEntryForAbsentEntry #12126


CI is good

**Comment by akevalion** [comment]
It is failing because of  testEntryForAbsentEntry  on windows, not related to roassal

**Pull request merged**
