### PR TITLE
More comments, better tests and better API 

### PR DESCRIPTION
**Pull request by Ducasse**
Started to 
- add tests
- better comments
- add Methods counter parts.

Next steps add tests for 
(SubclassOfA slotNamed: #a) isAccessedIn: SubclassOfA >>#foo3 SubclassOfA hasMethodAccessingVariable: (SubclassOfA slotNamed: #a)

### CODE REVIEW

**Comment by Ducasse** [comment]
Coding in P12 is quite painful because we are losing changes :(

**Comment by jecisc** [comment]
> Coding in P12 is quite painful because we are losing changes :(

Do you have a way to reproduce this? Since my recent fix on extension methods I did not lose anything

**Comment by jecisc** [comment]
osx-64 / Tests-osx-64 / testWhichMethodsAccessSubclassState – MacOSX64.Refactoring.Tests.Core.LowLevelReflectiveAPITest7s
osx-64 / Tests-osx-64 / testWhichSelectorsAccessSubclassState – MacOSX64.Refactoring.Tests.Core.LowLevelReflectiveAPITest7s
unix-64 / Tests-unix-64 / testWhichMethodsAccessSubclassState – Unix64.Refactoring.Tests.Core.LowLevelReflectiveAPITest10s
unix-64 / Tests-unix-64 / testWhichSelectorsAccessSubclassState – Unix64.Refactoring.Tests.Core.LowLevelReflectiveAPITest

**Comment by Ducasse** [comment]
Seriously I do not understand how copy can fail because I do not touch this code nor any code that can be used by them. 
I added comments and added new methods that are not used by the system.

**Comment by Ducasse** [comment]
Pharo is getting a pain in fact.

**Comment by Ducasse** [comment]
I do not get anything because the tests are green in my image.

**Comment by Ducasse** [comment]
RBCopyPackageParametrizedTest are green.
LowLevelReflectiveAPITest are all green.
So if the build does not pass I will close the issue and do something else.

**Comment by Ducasse** [comment]
My last commit. I removed potential sources of indeterminism.

**Comment by Ducasse** [comment]
Tests pass. The failing ones are about test data as usual.

**Pull request merged**
