### PR TITLE
3276-adding-initializeSlots-may-break-instance-initialization

### LINKED ISSUE #3276: adding initializeSlots: may break instance initialization
`initializeSlots:` is being added to class initialize when we define slots who `wantsInitalization`.

The problem is that it is being added as last action of the initialize method and it should be the first (because the initialisation chain could be giving value to the variables that will be reseted when calling initializeSlots).

Additionally, `initializeSlots:` is being added without taking into account that it may have been added before in the initialisation chain (making the slots to be initialised multiple times).

### PR DESCRIPTION
**Pull request by estebanlm**
traverse initialize in class to verify initializeSlots is there.

Fixes #3276

### CODE REVIEW

**Review by MarcusDenker — APPROVED** [review]
looks good

**Comment by MarcusDenker** [comment]
Failing tests... it seems the generated code is bidding a . somehow?

receiver of "super" is nil
Stacktrace
UndefinedObject>>doesNotUnderstand: #super
SlotTestsClassA>>initialize
SlotTestsClassA class(Behavior)>>new
HistorySlotTest>>testAddTwoElements

**Comment by estebanlm** [comment]
now is ok.
@MarcusDenker, can you re-review?

**Review by MarcusDenker — APPROVED** [review]
ok1

**Pull request merged**
