### PR TITLE
restore-wrongly-removed-method

### PR DESCRIPTION
**Pull request by estebanlm**
this method was lost in last integration (no idea why). Restoring it.

### CODE REVIEW

**Comment by estebanlm** [comment]
hold this. It may be a correct removal.

**Comment by guillep** [comment]
There should be no senders to that method... I'll check it after lunch

**Comment by akgrant43** [comment]
I'm getting a slight variation of the same issue:

```
FFITypeDeclaration>> #emitReturn:resultTempVar:context:
FFITypeDeclaration(Object)>>doesNotUnderstand: #emitReturn:resultTempVar:context:
TFCalloutMethodBuilder>>generateFFICallout:spec:
[ :builder | self generateFFICallout: builder spec: functionSpec ] in TFCalloutMethodBuilder(FFICalloutMethodBuilder)>>generateMethodFromSpec: in Block: [ :builder | self generateFFICallout: builder spec...etc...
IRBuilder class>>buildIR:
TFCalloutMethodBuilder(FFICalloutMethodBuilder)>>generateMethodFromSpec:
TFCalloutMethodBuilder(FFICalloutMethodBuilder)>>generate
TFCalloutMethodBuilder(FFICalloutMethodBuilder)>>build:
TFCalloutAPI(FFICalloutAPI)>>function:library:
TFCalloutAPI(FFICalloutAPI)>>function:module:
LGitLibrary(FFILibrary)>>ffiCall:
LGitLibrary>>libgit2_shutdown
```

**Comment by guillep** [comment]
I think this is a duplicate of #5534. However, this is a problem of TFFI. Please follow the changes in https://github.com/pharo-project/threadedFFI-Plugin/issues/20 and https://github.com/pharo-project/threadedFFI-Plugin/issues/21.

I'll close this issue ^^.

**Pull request closed without merging**
