### PR TITLE
Add the trace operation to Array2D class

### PR DESCRIPTION
**Pull request by rakki-18**
The operation to find the trace (sum of the diagonal elements of the matrix) of a matrix has been added in this PR.

### CODE REVIEW

**Comment by StephanEggermont** [comment]
Does this implementation have better performance than the more idiomatic one using #inject:into: ?

**Review by StephanEggermont — CHANGES_REQUESTED** [review]
Method name should start with a lower case letter

**Comment by rakki-18** [comment]
@StephanEggermont I have changed the method name now to `tr`. Should I squash the two commits and rebase my PR?

**Comment by rakki-18** [comment]
> Does this implementation have better performance than the more idiomatic one using #inject:into: ?

I am not sure yet.

**Comment by Ducasse** [comment]
Thanks for your contribution. 
Now pay attention that a better implementation of Array2D is available in http://github.com/pharo-containers/Container-Array2d

Then on your code: I think that it is better not to consider Array2D as a Matrix and it is better to enhcance PMMatrix from the Polymath package. We should remove from Array2D all idea of math support.

**Comment by rakki-18** [comment]
@Ducasse Thank you. I will look more into enhancing PMMatrix then. I will also look into the better [implementation](https://github.com/pharo-containers/Containers-Array2D) of Array2D.

**Comment by Ducasse** [comment]
Great!

**Pull request closed without merging**
