### PR TITLE
Speed up FreeTypeFont>>widthOf:

### PR DESCRIPTION
**Pull request by jecisc**
This method is heavily called in rubric. This will make ti faster to display text in rubric.

This bring #13114 from 6sec to 4sec. Not perfect but still better

### CODE REVIEW

**Comment by jecisc** [comment]
In an image I used a while, I have 95 instances of free type font. This cache should not impact much the memory

**Review by privat — APPROVED** [review]
Nice.

As always with cache, it's hard to measure the cost/benefit in the long term.
But 6s to 4s is good short term benefits anyway :)

Just by curiosity, I looked and there is already a LRUCache class in (core?) Pharo, but I don't know what it's worth.

**Comment by privat** [comment]
Maybe it could be good for Pharo11?

**Comment by MarcusDenker** [comment]
at some point we have to stop changing Pharo11... I will merge in Pharo12, at least we have to test it

**Pull request merged**
