### PR TITLE
2383 Cleanup DoubleLinkedList packages

### PR DESCRIPTION
**Pull request by astares**
Fixes issue https://github.com/pharo-project/pharo/issues/2383

### CODE REVIEW

**Comment by Ducasse** [comment]
Hi torsten

Why do you add a group? We should pay attention not to over clean. 
I have a lot of things that I think that we should improve and adding tag to test package is for me too much. 

Stef

**Comment by astares** [comment]
@Ducasse 
No - it is not overclean. It is consistent as we have tags for others too. Look at packages with many classes and many tests - we tag the classes and their tests similar so they will be easily found. This should basically also be true for packages with not so many classes/tags. Because otherwise the question would be: where do we draw the line.  

Also as soon as we have a manifest we have it in tag "Manifest" - not tagging the others would leave them as "Uncategorized". 

Believe me: if you do things more consistent you as well as others (especially newbees) would feel right at home and more comfortable. That's why P7 already looks more consistent and clean compared to any other previous version.

Additionally: in the mid-term we should think also about merging LinkedList support into regular collection packages.  

Rembering the https://en.wikipedia.org/wiki/Broken_windows_theory

**Comment by Ducasse** [comment]
Tx for this PR. Now we will not integrate it for the reason mentioned above.

**Comment by guillep** [comment]
Ok, I've followed the discussion.
This PR, besides the new `Base` tag, 
 - adds a manifest
 - and blacklists a lint rule

Making other issues gone.
I think it's good enough to go in.

**Comment by guillep** [comment]
hi @astares I'm ok with integrating this.
Could you fix the merge issues? I've tried on my side, but I cannot push the merge commit to your PR. So I'd have to do a new PR.

Tell me so I know if I do the new PR or not.

Thanks

**Comment by guillep** [comment]
Duplicate of https://github.com/pharo-project/pharo/pull/6022. The PR has been redone

**Pull request closed without merging**
