### PR TITLE
Activate strict FFI

### PR DESCRIPTION
**Pull request by guillep**
FFI callouts should (unless told otherwise) specify the types for **all call arguments**.
Otherwise this leads to ambiguities that the FFI engine cannot correctly state:
 - what is the type of 0? signed or unsigned? 1, 2, 4 or 8 bytes long?
 - what is the type of 1.5? a float or a double?
 - what is the type of self?

When the strict mode is disabled, types are inferred, and code will execute mistakenly in many cases.
**Important:**  This could lead to crashes.
Instead, the strict mode just throws an exception when this happens.

Notice that this option can be disabled locally per library (just redefining the `options` method), but I strongly encourage people to fix their lib bindings instead of using the non-strict mode.

Regarding adoption in the Pharo core IDE, we should check if this works as is, or if we should disable it momentarily for some of the libraries used internally in Pharo (e.g., SDL) that would prevent us migrating.

### CODE REVIEW

**Comment by Ducasse** [comment]
Yes!

**Comment by estebanlm** [comment]
why this now?
EDIT: this was ironic, since *I know why this now* (and I realize it may be interpreted differently) :P

**Comment by jecisc** [comment]
FreeType does not seems to comply with this change

```
MetacelloNotification: Evaluating -> baseline [BaselineOfIDE] >> postload:package:
FFIUnsupportedUntypedLiteral
FFICallout>>unsupportedUntypedLiteral:
FFIStrictResolutionMode>>resolveUndeclaredTypeForArgument:withResolver:
FFICallout>>resolveUntypedArgument:
FFIUndefinedTypeDeclaration>>resolveUsing:forArgument:
FFIConstantArgument>>resolveUsing:
[ :e | e resolveUsing: aResolver ] in FFIFunctionSpec>>resolveUsing: in Block: [ :e | e resolveUsing: aResolver ]
OrderedCollection>>do:
FFIFunctionSpec>>resolveUsing:
TFCalloutMethodBuilder(FFICalloutMethodBuilder)>>generateMethodFromSpec:
TFCalloutMethodBuilder(FFICalloutMethodBuilder)>>generate
TFCalloutMethodBuilder(FFICalloutMethodBuilder)>>build:
TFCalloutAPI(FFICalloutAPI)>>function:library:
FT2Library(Object)>>ffiCall:library:options:fixedArgumentCount:
FT2Library(Object)>>ffiCall:library:options:
FT2Library(Object)>>ffiCall:
FT2Library>>ffiNewFace:fromMemory:size:index:
FreeTypeFace(FT2Face)>>newFaceFromExternalMemory:index:
[ "we use the primNewFaceFromFile:index: method because we want to do this as fast as possible and we don't need the face registered because it will be explicitly destroyed later"
	face newFaceFromExternalMemory: externalMem index: i.
	face loadFields] in EmbeddedFreeTypeFontInstaller>>addFromFileContents:baseName: in Block: [ "we use the primNewFaceFromFile:index: metho[..]
FullBlockClosure(BlockClosure)>>on:do:
EmbeddedFreeTypeFontInstaller>>addFromFileContents:baseName:
SourceCodeProRegular class(EmbeddedFreeTypeFontDescription class)>>installFontsIn:
[ :each | each installFontsIn: provider ] in EmbeddedFreeTypeFontDescription class>>installAllFontsIn: in Block: [ :each | each installFontsIn: provider ]
OrderedCollection>>do:
EmbeddedFreeTypeFontDescription class>>installAllFontsIn:
EmbeddedFreeTypeFontInstaller>>installAllFontsIn:
```

**Comment by guillep** [comment]
> why this now? EDIT: this was ironic, since _I know why this now_ (and I realize it may be interpreted differently) :P

Answering seriously, if you think the timing is not right, we can postpone it. But I believe this is super important.
It's largely preferable to have an exception than a crash because a value was type-marshalled wrongly :).

**Comment by guillep** [comment]
This has found a bug in libgit. We should fix that before moving forward with this change. :)

**Comment by astares** [comment]
We should also try a few projects that use FFI heavily or on different platforms and that are covered with many tests like

- https://github.com/pharo-rdbms/Pharo-SQLite3

- https://github.com/astares/Pharo-OS-Windows
- https://github.com/astares/Pharo-OS-Linux-Ubuntu
- https://github.com/astares/Pharo-OS-OSX

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/pharo-rdbms/Pharo-SQLite3">GitHub - pharo-rdbms/Pharo-SQLite3: Community-owned official SQLite3 binding for Pharo</a></strong></div><div>Community-owned official SQLite3 binding for Pharo - GitHub - pharo-rdbms/Pharo-SQLite3: Community-owned official SQLite3 binding for Pharo</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/astares/Pharo-OS-Windows">GitHub - astares/Pharo-OS-Windows: Support for Windows operating system for Pharo</a></strong></div><div>Support for Windows operating system for Pharo. Contribute to astares/Pharo-OS-Windows development by creating an account on GitHub.</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/astares/Pharo-OS-Linux-Ubuntu">GitHub - astares/Pharo-OS-Linux-Ubuntu</a></strong></div><div>Contribute to astares/Pharo-OS-Linux-Ubuntu development by creating an account on GitHub.</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/astares/Pharo-OS-OSX">GitHub - astares/Pharo-OS-OSX</a></strong></div><div>Contribute to astares/Pharo-OS-OSX development by creating an account on GitHub.</div></blockquote>

**Comment by guillep** [comment]
Well, if those projects have exceptions, that means that they have bugs in their bindings ;) so they should be updated.
That’s not a problem. Again, I think exceptions are preferable to potential crashes

**Comment by jecisc** [comment]
Tests passed now :)

**Comment by guillep** [comment]
This is creating problems during image boot. I'll revert.

```
FFIUnsupportedUntypedLiteral
FFICallout>>unsupportedUntypedLiteral:
FFIStrictResolutionMode>>resolveUndeclaredTypeForArgument:withResolver:
FFICallout>>resolveUntypedArgument:
FFIUndefinedTypeDeclaration>>resolveUsing:forArgument:
FFIConstantArgument>>resolveUsing:
[ :e | e resolveUsing: aResolver ] in FFIFunctionSpec>>resolveUsing: in Block: [ :e | e resolveUsing: aResolver ]
OrderedCollection>>do:
FFIFunctionSpec>>resolveUsing:
TFCalloutMethodBuilder(FFICalloutMethodBuilder)>>generateMethodFromSpec:
TFCalloutMethodBuilder(FFICalloutMethodBuilder)>>generate
TFCalloutMethodBuilder(FFICalloutMethodBuilder)>>build:
TFCalloutAPI(FFICalloutAPI)>>function:library:
SDL_Texture(Object)>>ffiCall:library:options:fixedArgumentCount:
SDL_Texture(Object)>>ffiCall:library:options:
SDL_Texture(Object)>>ffiCall:
SDL_Texture>>lockPixels:pitch:
```

**Comment by tinchodias** [comment]
I don't understand why this seems to be merged weeks ago but only last days Bloc/Alexandrie started to error.

**Comment by jecisc** [comment]
> I don't understand why this seems to be merged weeks ago but only last days Bloc/Alexandrie started to error.

This was reverted and done again in https://github.com/pharo-project/pharo/pull/15683#event-11802661422

**Comment by tinchodias** [comment]
Thanks! fixing it on Alexandrie

**Pull request merged**
