### PR TITLE
Cleanup: Condense Athens- package - SECOND ATTEMPT

### LINKED ISSUE #12189: Cleanup: Condense Athens- package
- using the cleanup to remove unnecessary tabs, spaces and final dots in methods

### PR DESCRIPTION
**Pull request by astares**
Fix #12189  - without #ffiLibraryName

### CODE REVIEW

**Comment by Ducasse** [comment]
BTW can you wait that my PR of refactoring tests got integrated because it was boring to do it. I do not know when I will time to fix the last three tests (I could skip them for now). I have the impression that one is even wrong but I need real concentration for that.

**Comment by astares** [comment]
@Ducasse which PR is it? Is it #12195?   

How does it relate to the Athens package?

**Comment by Ducasse** [comment]
It is not related to Athens but I wanted to contact you and I lost your email :)

**Comment by Ducasse** [comment]
This PR https://github.com/pharo-project/pharo/pull/12195

**Comment by astares** [comment]
@Ducasse e-mail? Why? You can chat with me directly on Discord - also in a private chat 

Your changes in PR #12195 are for "Refactoring-xxx" packages. It will take some time until I reach this 
package - as I plan to clean up the packages alphabetically. Step by step. So take your time.

I also have to wait for #12202 before I will be able to continue with other packages (that have traits).

**Review by gcotelli — APPROVED** [review]

**Pull request merged**
