### PR TITLE
22450 stack should not inherit from linked list

### PR DESCRIPTION
**Pull request by juliendelplanque**
Now Stack does not inherit from linked list.

Additionally, the old Stack is deprecated and replaced by LinkedListStack since the implementation was using a LinkedList.

I also added an OrderedCollectionStack which uses OrderedCollection to implement the API.

I am curious to see results of the CI after a change to such a core feature of the system.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
The one thing I do not like: the name. The whole idea of Stack was to have a class that a) is called Stack b) is *only* a stack and can not be accessed differently (the change to be a subclass was very bad). We should try to keep "Stack" as the name... even though it might not be 100% backward compatible.

**Comment by MarcusDenker** [comment]
the OrderedCollection vs. LinkedList: in a perfect world,  this should be configurable for the Stack class (it should have a Meta Object Protocol to configure the implementation)

**Comment by juliendelplanque** [comment]
@MarcusDenker maybe a strategy design pattern then?

With methods in class-side like: `Stack usingLinkedList` and the default strategy would be the linked list?

**Comment by juliendelplanque** [comment]
@MarcusDenker I updated the implementation and CI seems ok 👍

**Comment by Ducasse** [comment]
I like the strategy idea.

**Comment by Ducasse** [comment]
Now do we need a linked list and array stack?
I tried to relaunch the build and it could not get enough slaves.

**Comment by juliendelplanque** [comment]
@Ducasse Well, I came to this change because I wanted a stack with a limited arbitrary-fixed size.
And I saw that currently the stack implementation was:
1. Not secure because it allows to access LinkedList's API (so this is not a stack restricted to push, pop and top).
2. Impossible to change the underlaying data structure.

So I wanted to refactor a little the stack to fix 1. and allow 2.

However, I am not against *not shipping* the OrderedCollectionStackStrategy with the default image, but I think keeping the strategy pattern is good if one needs a specific data structure to implement the stack.

**Comment by Ducasse** [comment]
OK :)
Thanks for all your good energy.

**Comment by juliendelplanque** [comment]
@MarcusDenker is the PR ok with the latest changes?

**Comment by pavel-krivanek** [comment]
We should not integrate it for Pharo 7

**Pull request closed without merging**
