### PR TITLE
Cleanup: Condense Zinc packages

### LINKED ISSUE #12759: Cleanup: Condense Zinc packages
```Smalltalk
cms := CompiledMethod allInstances select: [:each |
each package ifNil: [ false ] ifNotNil: [:p |
	p name beginsWith: 'Zinc' ] ].
 

cms do: [:cm |
    ((RBRefactoryChangeFactory instance)
         addMethodSource: (ReMethodSourceCleaner clean: cm sourceCode) in: cm origin) execute ]
```

### PR DESCRIPTION
**Pull request by astares**
Fix #12759

### CODE REVIEW

**Comment by jecisc** [comment]
CI failure unrelated. 
But I don’t have the time to review manually all the changes

**Comment by demarey** [comment]
These changes should also be proposed as a PR to the original repository: https://github.com/svenvc/zinc

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/svenvc/zinc">GitHub - svenvc/zinc: Zinc HTTP Components is an open-source Smalltalk framework to deal with the HTTP networking protocol.</a></strong></div><div>Zinc HTTP Components is an open-source Smalltalk framework to deal with the HTTP networking protocol. - GitHub - svenvc/zinc: Zinc HTTP Components is an open-source Smalltalk framework to deal with...</div></blockquote>

**Comment by jecisc** [comment]
I did a PR in zinc repo. I think we should close this PR here because we plan to sync Zinc soon to fix other issues also.

**Comment by jecisc** [comment]
Present in: https://github.com/pharo-project/pharo/pull/12794

**Pull request closed without merging**
