### PR TITLE
2383 Cleanup DoubleLinkedList packages

### PR DESCRIPTION
**Pull request by astares**
Fix issue #2383 a second time with a new branch (same changes as PR #2384 but based on lates P9)

### CODE REVIEW

**Comment by astares** [comment]
CI fails seems to be unrelated

**Review by guillep — APPROVED** [review]
ok!

**Comment by guillep** [comment]
I've relaunched the CI and logged the issue in https://github.com/pharo-project/pharo/issues/6024

**Comment by guillep** [comment]
Looks ok, test failures seem unrelated.

Thanks!!

**Pull request merged**
