### PR TITLE
Deprecated #addSelector:withMethod:notifying: methods should be in De…

### LINKED ISSUE #3889: Deprecated #addSelector:withMethod:notifying: methods should be in Deprecated package
Move deprecated methods

   Behavior>>#addSelector:withMethod:notifying: into
   TraitedClass>>#addSelector:withMethod:notifying: into

into Deprecated80 package so we can later easily remove them

Side note:
I guess they were forgotten during P7 development because a similar method #addAndClassifySelector:withMethod:inProtocol:notifying: 
is in Deprecated70 already

### PR DESCRIPTION
**Pull request by astares**
…precated package

Fix #3889

Move deprecated methods

Behavior>>#addSelector:withMethod:notifying: into
TraitedClass>>#addSelector:withMethod:notifying: into

into Deprecated80 package so we can later easily remove them

### CODE REVIEW

**Comment by MarcusDenker** [comment]
The PR adds a method to SHRBTextStyler, that is strange

**Comment by jecisc** [comment]
The problem is not that it adds a method. The problem is that the method is not removed from the original package.

**Comment by astares** [comment]
@MarcusDenker 
I guess this is because I used the *extension functionality in Calypso - and it looks like this is pushing it down to the class instead of keeping the extension on the trait.

**Comment by MarcusDenker** [comment]
I removed the method from with the git interface

**Comment by MarcusDenker** [comment]
but that seems to break tonel loading?

**Pull request merged**
