### PR TITLE
Fixing broken tests from PR #11060 

### PR DESCRIPTION
**Pull request by carolahp**
Fixing SycRefactoringPreviewTest failing tests by adapting Mock classes

### CODE REVIEW

**Comment by jordanmontt** [comment]
Enregistrement-de-lecran-2022-03

The failing tests for the class `RBRenameMethodParametrizedTest` check that the YES/NO confirmation dialog is displayed. We removed this behaviour because:

1) Is redundant. If you choose yes, you still have to select the changes that you want to apply and click again in "Ok".
2) the implementation mixes UI and logic. Because the dialog is called from the refactoring class. And then, the presenter is asking for confirmation one more time.

The two tests that are failing is because of the removal.

**Comment by MarcusDenker** [comment]
The test RBRenameMethodParametrizedTest>>testMultipleSelectors is failing

**Comment by jordanmontt** [comment]
Yes, those two tests are failing because of what we described in the above message. 
Do you think that we can remove those two tests?

**Comment by Ducasse** [comment]
Sure if the tests are bad remove them.

**Review by MarcusDenker — APPROVED** [review]

**Comment by MarcusDenker** [comment]
we can merge this and then do another PR to remove the test

**Comment by MarcusDenker** [comment]
made a pr: https://github.com/pharo-project/pharo/pull/11073

**Pull request merged**
