### PR TITLE
5369-stepToSendOrReturn-causes-an-error-on-a-dead-context

### PR DESCRIPTION
**Pull request by j-brant**
fix and test for sending stepToSendOrReturn to a dead context -- issue #5369

### CODE REVIEW

**Comment by Ducasse** [comment]
Tx. Looks ok to me. I will let a chance to other to know that changes and integrate it.

**Review by Ducasse — COMMENTED** [review]
Hi John

when discussing with Guille, we are thinking that a simpler way to create a dead context that may be more reliable is to just create a new context and set the PC to nil. 

The forking and signalling of semaphore depend on the fact that when the test process resumes
the second context has already return.

S. and G.

**Comment by j-brant** [comment]
I changed the code so that it doesn't need to run the new process: 
```
deadContext
	| process context |
	process := [  ] newProcess.
	context := process suspendedContext.
	context pc: nil.
	^ context
```

**Comment by Ducasse** [comment]
Thanks this is cool because we are fighting with flaky tests.

**Pull request merged**
