### PR TITLE
7923-Broken-traits-definitions

### PR DESCRIPTION
**Pull request by Ducasse**
adding missing bits.

### CODE REVIEW

**Comment by Ducasse** [comment]
I do not understand why I can get a conflict. 
I did not touch this code.

**Comment by MarcusDenker** [comment]
My theory: There was a rewrite that was done in your image automatically, but at the same time we merged already a PR with the same rewrite.

**Comment by Ducasse** [comment]
:)

**Comment by pavel-krivanek** [comment]
Is the failure caused by the content of this PR? I do not see any reason why it should.

**Comment by Ducasse** [comment]
I relaunch it.

**Pull request merged**
