### PR TITLE
Fixes #10673 by adding missing method method to display a MessageTally identified

### LINKED ISSUE #10673: DNU in MessageTally>>#displayStringOn:
**Bug description**
`MessageTally>>#displayStringOn:` contains send of unimplemented method `displayIdentifierOn:`.

**To Reproduce**
1. evaluate `(MessageTally spyOn: [ self notNil ]) inspect`

### PR DESCRIPTION
**Pull request by carolahp**
Test solution executing
```
mt := MessageTally  
	spyOn: [ self notNil ]
	reportOtherProcesses: false 
	cutoff: 1 
	openResultWindow: true 
	closeAfter: false. "if true, the instance will be closed immediately and its identifier will not be displayed"
mt inspect.
mt close
```

### CODE REVIEW

**Comment by Ducasse** [comment]
In P9 we got

```
MessageTally >> displayIdentifierOn: aStream
	class displayStringOn: aStream.
	self method methodClass ~~ class 
		ifTrue: [ aStream nextPut: $(; print: self method methodClass; nextPut: $) ].
	aStream 
		nextPutAll: '>>';
		store: self method selector
```

**Comment by Ducasse** [comment]
@carolahp may be this is better to use the version of P9 and not to have the test to the Time class variable

**Comment by MarcusDenker** [comment]
review asks question: more work needed

**Comment by carolahp** [comment]
> @carolahp may be this is better to use the version of P9 and not to have the test to the Time class variable

@Ducasse the version of P9 fails when executing  ```(MessageTally spyOn: [ self notNil ]) inspect```
because the instance variables method and class are set to ```nil``` at the end of ```spyOn:```

Maybe I could check only these IVs and not the class var ```Time``` in my method ```isClosed```?

**Comment by Ducasse** [comment]
Ok :) Yes I found strange to check the status of a class variable in a printOn because the class variable looks like a global

**Comment by MarcusDenker** [comment]
Just randomly failing test:
- FFITypesTest>>testSignedLongLong sometimes failing on the CI #9931

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
