### PR TITLE
New try at removing Pharo 9 metacello attributes

### LINKED ISSUE #10794: Pharo 10 still loads Pharo 9 specific packages in Metacello
**Bug description**
Pharo 10 still declares Pharo 9 tags in Metacello attributes. 
This makes it impossible to load packages in Pharo 9 but not Pharo 10. 

**Expected development cost**
It's one small update to SmalltalkImage>>#metacelloPlatformAttributes method

### PR DESCRIPTION
**Pull request by jecisc**

### CODE REVIEW

**Comment by jecisc** [comment]
This time it fails because Roassal 3 defines its baseline for Pharo 9 but not Pharo 10. 

Since roassal is managed outside Pharo I cannot fix it in this PR. It needs to be fixed in roassal and this PR rekicked once Roassal baseline will manage Pharo 10.

**Comment by jecisc** [comment]
@bergel Hi Alex, I don't know who is currently the maintainer of Roassal but if you can point the maintainer to this issue it'd be great.

**Comment by astares** [comment]
maybe @akevalion should also notice this PR

**Comment by astares** [comment]
image

**Comment by akevalion** [comment]
I have create a Pull request with version0.9.9f for pharo10 that fixes the the baseline

**Comment by akevalion** [comment]
Pull request with version0.9.9f has been accepted, can you check if this issue is valid?

**Comment by MarcusDenker** [comment]
I triggered a re-run of the CI using the latest code

**Comment by MarcusDenker** [comment]
Only networking related tests are failing (we have some problem for the CI right now)

**Comment by bergel** [comment]
It seems that the failure in CI is not related to Roassal. It would be great to restart the build...

**Comment by MarcusDenker** [comment]
Re-Run of the CI now us green!

**Review by MarcusDenker — APPROVED** [review]

**Comment by bergel** [comment]
Thanks @MarcusDenker !

**Comment by svenvc** [comment]
I am not sure this plays well with SmalltalkCI. My builds now suddenly fail with:
```
NotFound: [ :cl | cl isPlatformCompatible ] not found in OrderedCollection
OrderedCollection(Collection)>>errorNotFound:
[self errorNotFound: aBlock] in OrderedCollection(Collection)>>detect: in Block: [self errorNotFound: aBlock]
OrderedCollection(Collection)>>detect:ifFound:ifNone:
OrderedCollection(Collection)>>detect:ifNone:
OrderedCollection(Collection)>>detect:
SmalltalkCI class>>platformClass
...
```

**Comment by jecisc** [comment]
This seems to be a problem on SmalltalkCI side. 
Pharo 10 should not declare to be a pharo9 image. I checked fast but I didn't see where the problem was in SmalltalkCI (but I didn't had a lot of time to check)

**Comment by svenvc** [comment]
No it should not

**Pull request merged**
