### PR TITLE
Reduce users of current world

### PR DESCRIPTION
**Pull request by guillep**
Partial fix of #5917 harvesting easily dropping fruit.

Getting down to 178 references.
- About half of the removed ones are non-necessary usages of currentWorld for theming (see #5923).
- Others were simple refactorings of repeated accessors to `displayScaleFactor`
- Others were `currentWorld` => `world`

On the 178 remaining references, I've identified several families. They should be easy to solve in isolation.

### CODE REVIEW

**Comment by Ducasse** [comment]
Two little related broken tests
testIntoWorldCollapseOutOfWorld and CircleMorph.

**Comment by Ducasse** [comment]
I do not really understand the impact of 

removing 	self currentWorld activeHand addEventListener: self.
and 

```
		autoAccept: autoAccept;
 		setTextWith: self initialContents.
 	self currentWorld activeHand addEventListener: self.
 	editor announcer
 		when: MorphLostFocus send: #whenEditorLostFocus: to: self;
 		when: RubTextAccepted send: #whenTextAccepted: to: self;
 @@ -229,7 +228,6 @@ RubFloatingEditorBuilder >> openEditorWithContents: aText thenDo: aBlock [

 { #category : #'announcement handling' }
 RubFloatingEditorBuilder >> whenEditorDeleted: anAnnouncement [
 	anAnnouncement morph activeHand removeEventListener: self.
 	anAnnouncement morph announcer unsubscribe: self.
 	editor := nil
 ]
```

**Comment by guillep** [comment]
> I do not really understand the impact of
> 
> removing self currentWorld activeHand addEventListener: self.

Me neither. What I noticed is:
1 - removing that did not break it
2 - that class it not very used

What that line does is to redirect ALL events to that morph.
Regardless the focus, regardless the morph composition.
Which I don't think is needed for that morph either (it's actually a super corner case).

If it breaks something, we can re-add that line.

**Comment by estebanlm** [comment]
I guess it may be used for modal views?

**Comment by guillep** [comment]
> I guess it may be used for modal views?

Maybe, dunno...
If that was the case, there are other more elegant ways to do it (like subscribing to FocusLost :P) than listening to ALL events

**Pull request merged**
