### PR TITLE
Rewrite with TDD the updateTasks to avoid race conditions

### PR DESCRIPTION
**Pull request by VincentBlondeau**
BTW: we are not able to use the commit function integrated in Pharo8.0 correctly (we are probably to dumb for this, we will need a tutorial... jk). So we decided with Stephan Eggermont to file out the modifications we made see in the Fileout folder ;) 

PS: You could maybe try to load it in another image to successfully integrate our changes. Though, you will need to change the right baseline to add the new package we created for morphic tests

### CODE REVIEW

**Comment by VincentBlondeau** [comment]
Sorry for the cr, I use windows

**Comment by jecisc** [comment]
Line endings are crlf instead of lf.

**Comment by StephanEggermont** [comment]
the change to updateTasks is missing

**Comment by StephanEggermont** [comment]
See Issue #2974

**Comment by Ducasse** [comment]
Guys I have no idea what you are talking about. 
What is the updateTasks?

Stef

**Comment by Ducasse** [comment]
Can you explain what did not work exactly?
I use iceberg daily and it works. So I would like to understand.

**Comment by StephanEggermont** [comment]
We started with a Pharo 8 branch where we had already made a fix and a PR. We only noticed that when trying to commit, and then tried to fix the situation. #2953 #2954 #2961 #2963 #2964 #2965 #2966 #2967 and then we were confused and just did a fileout. Somehow it also misses the last change to actually use the new updateTask form which is found in the test code.

We noticed there might be race conditions in CI with the taskbar, and tried to find out where they might be coming from. The stack trace lead us to updateTasks in TaskbarMorph, which we found difficult to understand. We decided to rewrite it TDD

**Comment by StephanEggermont** [comment]
Keep open

**Comment by VincentBlondeau** [comment]
ping

**Comment by VincentBlondeau** [comment]
test failure not related:
windows-32 / Tests-windows-32 / testisZipArchive – Windows32.Compression.Tests.Archives.ZipArchiveTest

**Comment by VincentBlondeau** [comment]
ping

**Review by MarcusDenker — APPROVED** [review]
ok

**Pull request merged**
