### PR TITLE
21577 Cannot read from /dev/urandom

### PR DESCRIPTION
**Pull request by martinmcclure**
See https://pharo.fogbugz.com/f/cases/21577/Cannot-read-from-dev-urandom.

### CODE REVIEW

**Comment by svenvc** [comment]
Approved.

Integrated upstream as well.

===
Name: Zinc-Character-Encoding-Core-SvenVanCaekenberghe.58
Author: SvenVanCaekenberghe
Time: 15 March 2018, 9:19:04.331919 am
UUID: 7bddb7e1-d023-0d00-a5dd-901d0ecc2760
Ancestors: Zinc-Character-Encoding-Core-SvenVanCaekenberghe.57

Apply Martin McClure's patch to ZnBufferedReadStream>>readInto:startingAt:count: (do not rely on #atEnd)
===

**Comment by MarcusDenker** [comment]
build crashes... very odd.

**Comment by martinmcclure** [comment]
Looks like perhaps `InflateStream` relies on `#atEnd` being sent in order to read/decompress the final few bits of a zip file. Which as a design decision is... odd. If I'm right about that (just a quick glance so far) and a `ZipReadStream` is then buffered by a `ZnBufferedReadStream`, then removing the frequent sends of `#atEnd` by `ZnBufferedReadStream` could cause this problem. Will look a little deeper.

**Comment by martinmcclure** [comment]
Well, upon digging, I cannot understand why it's failing. My hypothesis from earlier today does not look correct. Also the stack reported by Jenkins includes `next:into:startingAt:`, which is not sent by `ZnBufferedReadStream` to an `InflateStream`, so it's not clear how my change to `ZnBufferedStream` could have caused this.
I also can't find any code in `InflateStream` that would account for the stack, which I've copied below for the record.
I'm considering putting an empty commit on the branch to force CI to re-run the tests, just to confirm that this is actually a reproducible failure.

```
SubscriptOutOfBounds: 1
ByteArray(Object)>>errorSubscriptBounds:
ByteArray(Object)>>at:
ByteArray>>byteAt:
ZipReadStream(InflateStream)>>nextByte
ZipReadStream(InflateStream)>>nextBits:
ZipReadStream(InflateStream)>>getNextBlock
ZipReadStream(InflateStream)>>pastEndRead
ZipReadStream(InflateStream)>>next
ZipReadStream(InflateStream)>>next:into:startingAt:
```

**Comment by martinmcclure** [comment]
Sigh. It fails the same way a second time. I've spent several hours (when I really should have been working on other things) trying to understand this, and I don't. If someone does get to the bottom of it, I'll be glad to hear what the cause is.

**Comment by akgrant43** [comment]
Hi Martin,

I've been able to reduce this to a simple reproducible case.  It only happens with a specific mcz file (second issue within a month that is only triggered in the bootstrap process, sigh).

| zip stream members contents |

zip := ZipArchive new.
stream := 'System-Changes-tonel.1.mcz' asFileReference binaryReadStream.
zip readFrom: stream.
members := zip members.
contents := members first contents.
{ zip. stream. members. contents. }.

Triggers the issue with your patch.

Can you look at this as I'd like to focus on getting the atEnd fix in to the VM (as mentioned in the fogbugz issue)?

Cheers,
Alistair


[mcz.zip](https://github.com/pharo-project/pharo/files/1844318/mcz.zip)

**Comment by martinmcclure** [comment]
Thanks again for the reproduction case, Alistair -- it allowed me to find my stupid error. :-)

**Comment by akgrant43** [comment]
No problem, glad I could help.

**Comment by akgrant43** [comment]
Hi Martin,

#readInto:startingAt:count: was quite difficult to read before (for me, anyway), and the introduction of a return in the middle of an arithmetic statement makes it that much more difficult.

What do you think of modifying part of the code to be:

	^ read
		+
			(requestedCount - read < (buffer size / 2) ifTrue: [ 
				self nextBuffer.
				limit = 0
					ifTrue: [ 0 ]	"All available elements have already been copied to collection."
					ifFalse: [ self readInto: collection 
										startingAt: offset + read 
										count: requestedCount - read ] ]
			ifFalse: [ 
				stream readInto: collection startingAt: offset + read count: requestedCount - read ])


Cheers,
Alistair

**Comment by martinmcclure** [comment]
Hi Alistair,
I see your point. Also, thinking about readability of that method in general, the method was doing more than one thing. Accordingly, I've refactored it into multiple methods and attempted to make it more readable. See if you find it easier to understand.
Regards,
-Martin

**Comment by akgrant43** [comment]
Hi Martin,

I like the refactoring.  But there's a bug - part of #readInto:startingAt:count: should be:

```smalltalk
	((self shouldBufferReadOfCount: countYetToRead)
		ifTrue: [ self nextBuffer.
			limit > 0
				ifTrue: [ self readInto: collection startingAt: newOffset count: countYetToRead ]
				ifFalse: [ 0 ] ]
		ifFalse: [ stream readInto: collection startingAt: newOffset count: countYetToRead ]) ].
```

Running the Test Runner with 'File|Zinc' packages selected will highlight the error.

Cheers,
Alistair

**Comment by martinmcclure** [comment]
HI Alastair,
I'm sorry that you had to look at the failed code -- earlier today I saw that the checks had failed and attempted to send a comment but for some reason GitHub gave me a "you cannot comment now" message. 

Regardless, thanks for finding my bug, and pointing me at the larger test suite (before committing I had run the Zinc tests for that package, but apparently not all File|Zinc packages). I'll take a look and push a correction.

Regards,
-Martin

**Comment by martinmcclure** [comment]
OK, that looks better. I felt that the "arithmetic expression" had too much non-strictly-arithmetic stuff in it that made it harder to understand, and no arithmetic needed to be done in the case that errored, so I factored the arithmetic into two separate expressions, each hopefully easier to read.
-Martin

**Comment by estebanlm** [comment]
ok :)

**Comment by akgrant43** [comment]
Hi Martin,

I would have approved this PR, but Esteban got in before me. :-)

Thanks for taking all the feedback constructively.

Cheers,
Alistair

**Comment by estebanlm** [comment]
beacuse I followed discussions in list and here so I knew it was ready ;)

**Comment by martinmcclure** [comment]
Hi Alistair,
Thanks for nudging me to not just fix the bug, but improve the code quality as well.
-Martin

**Pull request merged**
