### PR TITLE
22089-Integrate-new-Calypso-0115

### PR DESCRIPTION
**Pull request by dionisiydk**
New version 0.11.5 provides adaptation to renamed Commander classes:

Command word is omitted in common activation strategies:
- CmdShortcutActivation instead of CmdShortcutCommandActivation
- CmdContextMenuActivation instead of CmdContextMenuCommandActivation 
- CmdDragAndDropActivation instead of CmdDragAndDropCommandActivation
- ClyToolbarActivation instead of ClyToolbarCommandActivation

Now old names are available as deprecated classes. Deprecation ensures that users will receive new class instances.

https://pharo.fogbugz.com/f/cases/22089/Integrate-new-Calypso-0-11-5

### CODE REVIEW

**Comment by dionisiydk** [comment]
IMPORTANT for testing:

It is important that deprecation is really work in fresh image.
Open iceberg and check context menu and  shortcuts (cmd + s). They should work

**Comment by dionisiydk** [comment]
Forgot one version update in baseline. Please restart validation

**Comment by Ducasse** [comment]
I restarted the job!

**Comment by Ducasse** [comment]
Hi denis

It looks like we have some command test failing. 

unix-32 / Tests-unix-32 / testConvertingCommandToActivator – Unix32.Commander.Core.Tests.CmdCommandActivatorTests
<1s
unix-32 / Tests-unix-32 / testConvertingToActivator – Unix32.Commander.Core.Tests.CmdCommandActivatorTests
<1s
unix-32 / Tests-unix-32 / testUndeclared – Unix32.ReleaseTests.Release.ReleaseTest
<1s
windows-32 / Tests-windows-32 / testConvertingCommandToActivator – Windows32.Commander.Core.Tests.CmdCommandActivatorTests
<1s
windows-32 / Tests-windows-32 / testConvertingToActivator – Windows32.Commander.Core.Tests.CmdCommandActivatorTests
<1s
windows-32 / Tests-windows-32 / testUndeclared – Windows32.ReleaseTests.Release.ReleaseTest
<1s
osx-32 / Tests-osx-32 / testConvertingCommandToActivator – MacOSX32.Commander.Core.Tests.CmdCommandActivatorTests
<1s
osx-32 / Tests-osx-32 / testConvertingToActivator – MacOSX32.Commander.Core.Tests.CmdCommandActivatorTests
<1s
osx-32 / Tests-osx-32 / testUndeclared – MacOSX32.ReleaseTests.Release.ReleaseTest

**Comment by dionisiydk** [comment]
Yes, I will check loading script. Some problem with updating Commander version

**Comment by dionisiydk** [comment]
I checked script in fresh image and it works correctly:
```Smalltalk
Metacello new
		baseline: 'Calypso';
		repository: 'github://pharo-ide/Calypso:v0.11.5';
		onConflict: [ :err | err useIncoming ];
		load: #('FullEnvironment' 'SystemBrowser' 'Tests').
```
So I don't know what the problem and how to fix it.

**Comment by MarcusDenker** [comment]
now oddly it does not show the ci check anymore

**Comment by jecisc** [comment]
I relaunched it.

**Comment by estebanlm** [comment]
still not passing. 
@dionisiydk, can you check?

**Comment by dionisiydk** [comment]
It should pass when Iceberg with new commander version will be released and
integrated.
I will check if it's already done

ср, 27 июня 2018 г., 11:00 Esteban Lorenzano <notifications@github.com>:

**Comment by estebanlm** [comment]
now?

**Comment by dionisiydk** [comment]
Did new Iceberg released? I did not see any notice about it

пн, 23 июля 2018 г., 9:52 Esteban Lorenzano <notifications@github.com>:

**Comment by dionisiydk** [comment]
So Iceberg was not released. Still waiting

2018-07-23 10:24 GMT+01:00 Denis Kudriashov <dionisiydk@gmail.com>:

**Comment by guillep** [comment]
I do not understand the problem. I don't see what happens. Is commander not upgraded? The log in the CI is somehow eating all metacello output :/

Now, Iceberg is not ready for integration and Calypso should not care about this. If upgrading commander was really urgent you should have said it, and we could have done a patch release of Iceberg before with just that change. But without information we cannot work. We just integrated your patch which seemed ok.

I've used introduced `#onUpgrade:` on your loading script, which should solve the problem, but it doesn't because Commander's baseline does not define

```
projectClass
    ^ MetacelloCypressBaselineProject
```

- Redefining `projectClass` to this in the baselines tells metacello to reload the packages. Otherwise, since calypso is loaded without iceberg, it will use place Cypress/Filetree and think that all packages are the same (and thus not upgrade from 0.6.2 to 0.6.3).
- Also Calypso baseline should avoid copying dependencies like

```
project: 'ClassAnnotationTests' copyFrom: 'ClassAnnotation' with: [
	spec loads: 'Tests'];
```

That has issues with cypress projects too, see issue: https://github.com/Metacello/metacello/issues/494

Now, I'm trying to test this locally but it seems it has to be fixed in both Commander and ClassAnnotation, otherwise this does not work.

In any case, this would mean to change already deployed versions, so
 - to fix this right away, I'll make a patch version of Iceberg with the new version of Commander.
 - We will need a new version of Commander and Class annotation using MetacelloCypressBaselineProject, and Iceberg has to move to those versions too as soon as possible with another patch version, otherwise metacello raises an error.

Please communicate better next time. I've lost all the morning to understand why all this not works.

**Comment by guillep** [comment]
Only one test, not related I think

unix-32 / Tests-unix-32 / testExpiring – Unix32.System.Caching.Tests.TTLCacheTests

that test is in any case failing because of a delay... Whichi is not related to the change.

@estebanlm could you check it?

**Comment by dionisiydk** [comment]
Thanks Guille. I also loose time with it. Manually it was always working.

2018-07-27 14:35 GMT+01:00 Guille Polito <notifications@github.com>:

> I do not understand the problem. I don't see what happens. Is commander
> not upgraded? The log in the CI is somehow eating all metacello output :/
>
> Now, Iceberg is not ready for integration and Calypso should not care
> about this. If upgrading commander was really urgent you should have said
> it, and we could have done a patch release of Iceberg before with just that
> change. But without information we cannot work.
>
I just noticed that Iceberg releases start to be frequent. So I can't
imagine that it will be a problem.

> We just integrated your patch which seemed ok.
>
> I've used introduced #onUpgrade: on your loading script, which should
> solve the problem, but it doesn't because Commander's baseline does not
> define
>
> projectClass
>     ^ MetacelloCypressBaselineProject
> ```.
>
> - Redefining `projectClass` to this in the baselines tells metacello to reload the packages. Otherwise, since calypso is loaded without iceberg, it will use place Cypress/Filetree and think that all packages are the same (and thus not upgrade from 0.6.2 to 0.6.3).
>
> I wonder how anybody could know about this. As other people I just copied
some of existing Pharo baselines.
Now I think all my projects are affected by this issue.

>
> - Also Calypso baseline should avoid copying dependencies like
>
>
> project: 'ClassAnnotationTests' copyFrom: 'ClassAnnotation' with: [
> spec loads: 'Tests'];
>
So instead I should copy original baseline spec? I even don't sure that it
will work because I need the name different than baseline.
All this metacello story is full of crap.

>
> That has issues with cypress projects too, see issue: https://github.com/Metacello/metacello/issues/494
>
> Now, I'm trying to test this locally but it seems it has to be fixed in both Commander and ClassAnnotation, otherwise this does not work.
>
> I always only implement baseline method (as I am sure others do). I have
no idea about other parts of Baseline class because it was always copy of
working baseline (which I thought is working)

>
>
> In any case, this would mean to change already deployed versions, so
>  - to fix this right away, I'll make a patch version of Iceberg with the new version of Commander.
>  - We will need a new version of Commander and Class annotation using MetacelloCypressBaselineProject, and Iceberg has to move to those versions too as soon as possible with another patch version, otherwise metacello raises an error.
>
> But do you know why loading(updating) script works fine when executing
manually from playground?

**Pull request merged**
