### PR TITLE
22426 Cleanup LzwGifEncoder and GIFReadWriter

### PR DESCRIPTION
**Pull request by astares**
https://pharo.fogbugz.com/f/cases/22426/

This change
- categorizes what is uncategorized
- delete what is unsent
- removes what is unused 
to fix what was introduced in https://github.com/pharo-project/pharo/pull/1666

to get back to the situation with an image that had not unused temps

### CODE REVIEW

**Comment by jecisc** [comment]
I relaunched the CI. Failure seemed unrelated.

**Review by MarcusDenker — APPROVED** [review]
ok

**Comment by astares** [comment]
Green - @MarcusDenker can you merge?

**Comment by astares** [comment]
Thanks!

This is required for https://github.com/pharo-project/pharo/pull/1782

**Pull request merged**
