### PR TITLE
BracedCollection ready for review and integration

### PR DESCRIPTION
**Pull request by Ducasse**
- Added support for broken situation
- now semanticAnalyzer is doing something
- fix the completion to at least not bark
- couple more tests Ready for reviews
- introduced a specific method withAllForBrace: so that other candidates can just redefine this method if needed.
Please review

### CODE REVIEW

**Comment by jecisc** [comment]
```
Instance of RBParseErrorNode did not understand #binding
RBParseErrorNode(Object)>>doesNotUnderstand: #binding
OCASTTranslator>>visitLiteralCollectionNode:
RBLiteralCollectionNode>>acceptVisitor:
OCASTTranslator(RBProgramNodeVisitor)>>visitNode:
OCASTTranslator>>visitNode:
[:each |
		self visitNode: each] in OCASTTranslator>>emitMessageNode: in Block: [:each |...
OrderedCollection>>do:
OCASTTranslator>>emitMessageNode:
```

**Comment by Ducasse** [comment]
This is strange that it crashed again on the same because we can now recompile the complete image.

**Comment by jecisc** [comment]
Related pheps: https://github.com/pharo-project/pheps/pull/22

**Comment by Ducasse** [comment]
I prefer not to extend the parser for the sake of it. So I will close my PR and extension proposal. 
I think that the parser extension is only good if we can get a real gain such as not creating the array but I do not see how it would be possible.

**Pull request closed without merging**
