### PR TITLE
Sync ston

### PR DESCRIPTION
**Pull request by jecisc**
Brings:
- [Improve float parsing accuracy as prototyped by](https://github.com/svenvc/ston/commit/a9959114c3036aad1dd5c327a5b8ac3309e4c3e5) [https://github.com/weâ¦](https://github.com/webwarrior-ws)
- [Comment all class side methods of the STON facade, add executable exaâ¦](https://github.com/svenvc/ston/commit/81b28d9cc1e2056cd4ea9b7332377e54c08e161c)
- [Track categorization changes in Pharo 11 [initialization]](https://github.com/svenvc/ston/commit/e49b179a330740f7b274fd66fa421a71514810c5)
- [Use OSPlatform current lineEnding as default for STONWriter's newlineâ¦](https://github.com/svenvc/ston/commit/90eed086f79aca4cbd0f5c45ab05d8a6f79b0d57)
- [The result of ReMethodSourceCleaner clean (spaces in source code)](https://github.com/svenvc/ston/commit/747f14062c2855adc7f9b7f0befd953203363b7e)

### CODE REVIEW

**Comment by jecisc** [comment]
This cause CI failures that seems related. 
I’ll take a look later

osx-64 / Tests-osx-64 / nil – MacOSX64.PharoDocComment.Base.CommentTestCase4s
osx-64 / Tests-osx-64 / testInstanceSideInitializeMethodNeedsToBeInInitializationProtocol – MacOSX64.ReleaseTests.Categorization.ProperMethodCategorizationTest<1s
osx-64 / Tests-osx-64 / testStore – MacOSX64.System.Settings.Tests.SettingsStonWriterTest<1s
osx-64 / Tests-osx-64 / testStoreShouldNotCloseBackingStream – MacOSX64.System.Settings.Tests.SettingsStonWriterTest<1s
osx-64 / Tests-osx-64 / testStoreTwoObjects – MacOSX64.System.Settings.Tests.SettingsStonWriterTest<1s
osx-64 / Tests-osx-64 / testStoreSettingNodes – MacOSX64.System.Settings.Tests.SystemSettingsPersistenceTest<1s
unix-64 / Tests-unix-64 / nil – Unix64.PharoDocComment.Base.CommentTestCase6s
unix-64 / Tests-unix-64 / testInstanceSideInitializeMethodNeedsToBeInInitializationProtocol – Unix64.ReleaseTests.Categorization.ProperMethodCategorizationTest<1s
unix-64 / Tests-unix-64 / testStore – Unix64.System.Settings.Tests.SettingsStonWriterTest<1s
unix-64 / Tests-unix-64 / testStoreShouldNotCloseBackingStream – Unix64.System.Settings.Tests.SettingsStonWriterTest<1s
unix-64 / Tests-unix-64 / testStoreTwoObjects – Unix64.System.Settings.Tests.SettingsStonWriterTest<1s
unix-64 / Tests-unix-64 / testStoreSettingNodes – Unix64.System.Settings.Tests.SystemSettingsPersistenceTest

**Comment by svenvc** [comment]
At least the failures in System-Settings are related to line end conventions that changed.

Now, LF is used, the platform default on mac, while the tests expects CR as a result.

**Comment by svenvc** [comment]
Here is one way to fix #testStore
```
testStore
	| settingNode |
	settingNode := MockSettings booleanSettingNode.
	writer addSetting: (StoredSettingsFactory new from: settingNode).
	writer store.
	fileStream flush.
	self 
		assert: fileReference contents 
		equals: (OSPlatform current lineEnding join: MockSettings oneStoredSettingSTONString lines)
```
It is dangerous/brittle to test absolute expected output like this.

**Comment by svenvc** [comment]
There also seems to be a problem with the executable comment in STON class>>#toJsonString: but I don't think this can be solved. The double quote needs to be doubled inside the comment, but is seems to remain doubled when processed as executable comment.

**Comment by jecisc** [comment]
I just finished what I was doing so I’ll take a look.

Thank you for the test you already fixed

**Comment by svenvc** [comment]
I did commit some changes in STON

**Comment by jecisc** [comment]
I’m doing right now a PR to fix the escaping in string in executable comments

**Comment by jecisc** [comment]
https://github.com/pharo-project/pharo/pull/12830

Once it will be integrated, it should be safe to keep the executable comment

**Comment by jecisc** [comment]
Some failures are related. I'll check later

**Comment by jecisc** [comment]
[CI] Windows testrunner has problems [CI] Windows testrunner has problems #12763

Tests passed! This is ready to be reviewed

**Review by demarey — APPROVED** [review]

**Pull request merged**
