### PR TITLE
validate callback failure on exit

### PR DESCRIPTION
**Pull request by estebanlm**
... and try to answer default value if callback failed.

this improves TFFI stability but it does not prevents all crashes (because a default answer can be a wrong answer a lot of times)

### CODE REVIEW

**Comment by tesonep** [comment]
@estebanlm are some changes missing? Like the users of the methods? 😄

**Comment by estebanlm** [comment]
not really since the users are for the moment in the Gtk backend (I know, I should push them up :P)

**Comment by Ducasse** [comment]
@estebanlm Just a novice question, why do you initialise by default success and not failed

**Comment by estebanlm** [comment]
because by default is success. A callback fails just if an error that pops up a debugger happens, which is not very frequent (hopefully).

**Review by guillep — APPROVED** [review]
Ok!

**Pull request merged**
