### PR TITLE
Rework init logic in DamageRecorder

### LINKED ISSUE #6113: Rework init logic in DamageRecorder
The class DamageRecorder overwrites the new methods

```Smalltalk
new

	^ super new reset
```
and provides a reset like

```Smalltalk
reset
	"Clear the damage list."

	invalidRects := OrderedCollection new: 15.
	totalRepaint := false
```

This looks like a strange pattern. It would be better to have an instance side #initialize method.
Such an #initialize method is usually expected to see what and which initialization happens - this makes overwriting the "new" unnecessary.

### PR DESCRIPTION
**Pull request by astares**
- remove class side #new as #initialize is provided (which is called anyway
- removal of unncessary dots

Fix #6113

### CODE REVIEW

**Comment by astares** [comment]
Unrelated failing of osx-64 / Tests-osx-64 / testExpressionInIncompleteParanthesis – MacOSX64.NECompletion.Tests.CompletionContextTest
```
Error
Improper store into indexable object
Stacktrace
Error
Improper store into indexable object
ByteString(Object)>>error:
ByteString(Object)>>errorImproperStore
ByteString>>at:put:
WriteStream>>nextPut:
[ :aStream |
aStream
nextPut: 'Expecting to find #sin 
```

**Comment by Ducasse** [comment]
I was wondering how much time per second this method is used. because we could also remove the super initialize to have exactly the same behavior.

**Comment by guillep** [comment]
None. There is a single instance per world. Created at bootstrap time. (from what I see in the code :P)

**Comment by astares** [comment]
@guillep: a single instance is not correct, Basically we have three instances: DamageRecorder is instantiated in HandMorph and WorldState- We have a single hand, a world with a world state and as the MenuMorph (taskbar) instantiates one as well we have 3 instances afterall. Each with a damage recorder.

But I agree - we only have a few of them. Overhead is minimal.

**Side note:**
As we (usually can be sure) that we have a damage recorder in the world state I wonder why 
the nil test in #invalidate of WorldState is required:

```Smalltalk
invalidate
	self worldRenderer invalidate.
	damageRecorder 
		ifNil: [damageRecorder := DamageRecorder new]
		ifNotNil: [damageRecorder doFullRepaint]
```
maybe here a few cycles could be saved.

**Review by guillep — APPROVED** [review]

**Comment by guillep** [comment]
Thanks!!

**Pull request merged**
