### PR TITLE
12131 introduce a non misleading not equals selector 

### PR DESCRIPTION
**Pull request by demarey**

### CODE REVIEW

**Comment by Ducasse** [comment]
Hi christophe 
this is really a change that introduces incompatibility. So at least we should keep ~= 
now my question is how do we express identity difference because it is ~~

**Comment by MarcusDenker** [comment]
this will not be that easy:

some package are meant to run on quite old Pharo versions (all the Zinc packages, Fuel)

So this can not be done for those... 

and yes, we have to keep the compatibility methods, but that was always the idea I think.

What has to be checked is special selectors:

BytecodeEncoder class>>#specialSelectors

```
	^ #(#+ #- #< #> #'<=' #'>=' #= #'~=' #* #/ #'\\' #@ #bitShift: #'//' #bitAnd: #bitOr: #at: #at:put: #size #next #nextPut: #atEnd #'==' nil "class" #'~~' #value #value: #do: #new #new: #x #y)
```

and EncoderForSistaV1>>#genSendSpecial:numArgs: shows that there is even a bytecode for ~=, which means that this would have impact on performance, too

**Comment by MarcusDenker** [comment]
To me this is a typical project of a complexity that would be good for a "Pharo Enhancement Proposal" (see https://github.com/pharo-project/pheps) as it has lots of non-trivial implications




<blockquote><div> GitHub</div><div><strong><a href="https://github.com/pharo-project/pheps">GitHub - pharo-project/pheps: Pharo Enhancement Proposals</a></strong></div><div>Pharo Enhancement Proposals. Contribute to pharo-project/pheps development by creating an account on GitHub.</div></blockquote>

**Comment by demarey** [comment]
> Hi christophe this is really a change that introduces incompatibility. So at least we should keep ~= now my question is how do we express identity difference because it is ~~

Yes, this is the idea. There is more information on the issue: https://github.com/pharo-project/pharo/issues/12131.

> To me this is a typical project of a complexity that would be good for a "Pharo Enhancement Proposal" (see https://github.com/pharo-project/pheps) as it has lots of non-trivial implications

I just started one: https://github.com/pharo-project/pheps/pull/12

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/pharo-project/pheps">GitHub - pharo-project/pheps: Pharo Enhancement Proposals</a></strong></div><div>Pharo Enhancement Proposals. Contribute to pharo-project/pheps development by creating an account on GitHub.</div></blockquote>

**Comment by MarcusDenker** [comment]
I close this for now (it has conflicts)

**Comment by astares** [comment]
I would not do != just to align with mainstream, because then you would also have to support <> for NOT EQUAL. 

So the question is where do stop then:

image

**Pull request closed without merging**
