### PR TITLE
3022-Use-WeakValueDictionary-for-Undeclared

### LINKED ISSUE #3022: Use WeakValueDictionary for Undeclared
When deleting a class, we check if the class is still referenced and if yes, add it to the Undeclared dictionary. (see #removeFromSystem:)

Suggestion of Pablo:
- use WeakValueDictionary 
- remove the #isReferenced check in #removeFromSystem:, always add the class to Undeclared and then let the GC remove the unused classes
- we have to keep #cleanOutUndeclared as the GC will not remove a class that e.g. is referenced somewhere even though not from code.

This will help to improve the speed as discussed in https://github.com/pharo-project/pharo/issues/2369

### PR DESCRIPTION
**Pull request by jecisc**
Make Undeclared a WeakValueDictionary instead of a Dictionary. Then, when we remove a class, we always add it to Undeclared. The non referenced classes will be removed with the next GC.
 
This speed-up the removal of packages. I removed all test packages from Pharo. Before the change it took 160sec. After, 33sec.

Fixes #3022

### CODE REVIEW

**Comment by jecisc** [comment]
Weird, the CI did not launch.

**Comment by guillep** [comment]
> Weird, the CI did not launch.

Yesterday the CI was down

**Comment by guillep** [comment]
there is a DNU during bootstrap. Does it fail locally in your machine too?
It seems that `ActiveWorld` is undeclared but with a value other than nil.

```
MessageNotUnderstood: SetElement>>actualScreenSize
[32] SetElement(Object)>>doesNotUnderstand: #actualScreenSize
[32] DisplayScreen class>>actualScreenSize
[32] BaselineOfDisplay>>postload:package:
[32] [:aLoader :pkgSpec |  self project configuration perform: selector with: aLoader with: pkgSpec ] in MetacelloMCVersionSpec(MetacelloSpec)>>doItBlock: in Block: [:aLoader :pkgSpec |  self project configuration p...etc...
[32] BlockClosure>>valueWithPossibleArgs:
[32] [ block valueWithPossibleArgs: (Array with: aPostloadDirective loader with: aPostloadDirective spec) ] in MetacelloLinearLoadDirective(MetacelloVersionLoadDirective)>>loadPostloadDirective: in Block: [ block valueWithPossibleArgs: (Array with: aPostl...etc...
[32] MetacelloPostLoadDirective(MetacelloPrePostLoadDirective)>>evaluateSupplyingAnswers:
[32] MetacelloLinearLoadDirective(MetacelloVersionLoadDirective)>>loadPostloadDirective:
[32] MetacelloPostLoadDirective>>loadUsing:gofer:
[32] [:directive |  directive loadUsing: aLoaderDirective gofer: aGofer ] in MetacelloAtomicLoadDirective(MetacelloVersionLoadDirective)>>loadLinearLoadDirective:gofer: in Block: [:directive |  directive loadUsing: aLoaderDirecti...etc...
[32] OrderedCollection>>do:
[32] MetacelloAtomicLoadDirective(MetacelloVersionLoadDirective)>>loadLinearLoadDirective:gofer:
[32] MetacelloAtomicLoadDirective>>loadLinearLoadDirective:gofer:
[32] MetacelloLinearLoadDirective>>loadUsing:gofer:
[32] [:directive |  directive loadUsing: self gofer: aGofer ] in MetacelloAtomicLoadDirective>>loadAtomicLoadDirective:gofer: in Block: [:directive |  directive loadUsing: self gofer: aG...etc...
[32] OrderedCollection>>do:
[32] MetacelloAtomicLoadDirective>>loadAtomicLoadDirective:gofer:
[32] MetacelloAtomicLoadDirective>>loadUsing:gofer:
[32] [:directive |  directive loadUsing: self gofer: aGofer ] in MetacelloAtomicLoadDirective>>loadAtomicLoadDirective:gofer: in Block: [:directive |  directive loadUsing: self gofer: aG...etc...
[32] OrderedCollection>>do:
[32] MetacelloAtomicLoadDirective>>loadAtomicLoadDirective:gofer:
[32] MetacelloAtomicLoadDirective>>loadUsing:gofer:
[32] [:directive |  directive loadUsing: aLoaderDirective gofer: aGofer ] in MetacelloLinearLoadDirective(MetacelloVersionLoadDirective)>>loadAtomicLoadDirective:gofer: in Block: [:directive |  directive loadUsing: aLoaderDirecti...etc...
[32] OrderedCollection>>do:
[32] MetacelloLinearLoadDirective(MetacelloVersionLoadDirective)>>loadAtomicLoadDirective:gofer:
[32] MetacelloAtomicLoadDirective>>loadUsing:gofer:
[32] [:directive |  directive loadUsing: aLoaderDirective gofer: aGofer ] in MetacelloLinearLoadDirective(MetacelloVersionLoadDirective)>>loadLinearLoadDirective:gofer: in Block: [:directive |  directive loadUsing: aLoaderDirecti...etc...
[32] OrderedCollection>>do:
[32] MetacelloLinearLoadDirective(MetacelloVersionLoadDirective)>>loadLinearLoadDirective:gofer:
[32] MetacelloLinearLoadDirective>>loadUsing:gofer:
[32] 
[32] DisplayScreen class>>actualScreenSize (ActiveWorld is Undeclared) 
[32] 
[32] DisplayScreen class>>actualScreenSize (ActiveWorld is Undeclared) 
```

**Comment by jecisc** [comment]
I did not try locally but it's a weird error because I cannot see how this change can produce this error. I merge Pharo8 into the branch in case this was caused by another change.

**Comment by dionisiydk** [comment]
@jecisc Can you explain the introduction of new kind of Dictionary? Why it was needed and what is the difference with superclass?

**Comment by jecisc** [comment]
WeakValueDictionary cannot be used because the values are SetElements when they are nil instead of nil and the global lookup does not goes via the usual API. So this UndeclaredDictionary is a try to get a special dictionary that has weak value and is compatible with the global variable lookup. 
It’s possible there is an easier way to do it but for now I am still learning on how this part of the system work. I will discuss a little more with Marcus this weak and see if I can simplify the code.

**Comment by astares** [comment]
Still valid?

**Comment by jecisc** [comment]
It needs more work. 
I have no time for it right now but it's still on my todo.

**Pull request closed without merging**
