### PR TITLE
22118-Move-and-rename-AthensMorphicGradientPaint

### PR DESCRIPTION
**Pull request by jecisc**
Cut dependency from Athens-Core to Athens-Morphic. 

- Rename AthensMorphicGradiantPaint to AthensGradiantPaint
- Move this class to Athens-Core since it uses nothing from Morphic
- Depercate the old class

### CODE REVIEW

**Comment by jecisc** [comment]
Since I'm not familiar with Athens review are welcomes!

**Comment by jecisc** [comment]
Error not related

**Comment by jecisc** [comment]
I got some feedback on Discord and I'll update this PR to move everything related to Balloon to the Athens-Balloon package. And it will probably cut another dependency from Athens-Core :)

**Comment by jecisc** [comment]
Error seems not related.

**Review by pavel-krivanek — APPROVED** [review]
thank you

**Pull request merged**
