### PR TITLE
Rename some AST abstract classes to start with AST

### PR DESCRIPTION
**Pull request by jecisc**
I tried in the past to rename all AST classes at once but it failed. 

Now I'm doing step by step and I'm finding some origins of the errors I got. For example, the hook generator is calling methods based on class names and the renaming messes that. Or some classes are referenced in some bootstrap scripts.

Here I'm renaming 3 abstract classes. RBProgramNode, RBLiteralNode and RBValueNode.

### CODE REVIEW

**Comment by Ducasse** [comment]
@jecisc there is a conflict.

**Comment by jecisc** [comment]
Fixed

**Comment by Ducasse** [comment]
I tried to kill the windows slave because it is spinning with 20 hours.

**Comment by Ducasse** [comment]
I tried to relaunch the build on jenkins but without killing it so no idea if this is working.

**Review by demarey — APPROVED** [review]

**Pull request merged**
