### PR TITLE
Remove old comment editors

### PR DESCRIPTION
**Pull request by demarey**
as they are now replaced by their mardown-based version from Beautiful Comments.
Needs to be merged after https://github.com/pillar-markup/BeautifulComments/pull/40

### CODE REVIEW

**Comment by MarcusDenker** [comment]
build failure:

```
MetacelloNotification: Loading -> BeautifulComments-tonel.1 --- github://pillar-markup/BeautifulComments:integration/src --- cache
Error: Package BeautifulComments-Core depends on the following classes:
  ClyClassCommentEditorToolMorph
  ClyPackageCommentEditorToolMorph
You must resolve these dependencies before you will be able to load these definitions: 
  ClyClassCommentEditorToolMorph>>#new
  ClyPackageCommentEditorToolMorph>>#new
  ClyPackageRichTextCommentEditorToolMorph
  ClyPackageRichTextCommentEditorToolMorph>>#browserTabActivation
  ClyPackageRichTextCommentEditorToolMorph>>#browserTabActivation2
  ClyPackageRichTextCommentEditorToolMorph>>#asRenderedText
  ClyPackageRichTextCommentEditorToolMorph>>#asRenderedText:
  ClyPackageRichTextCommentEditorToolMorph>>#disable
  ClyPackageRichTextCommentEditorToolMorph>>#enable
  ClyPackageRichTextCommentEditorToolMorph>>#fillStatusBar
  ClyPackageRichTextCommentEditorToolMorph>>#initialize
  ClyPackageRichTextCommentEditorToolMorph>>#setBackgroundColor:
  ClyRichTextClassCommentEditorToolMorph
  ClyRichTextClassCommentEditorToolMorph>>#classCommentTabActivation
  ClyRichTextClassCommentEditorToolMorph>>#classTabActivation
  ClyRichTextClassCommentEditorToolMorph>>#asRenderedText:
  ClyRichTextClassCommentEditorToolMorph>>#disable
  ClyRichTextClassCommentEditorToolMorph>>#enable
  ClyRichTextClassCommentEditorToolMorph>>#fillStatusBar
  ClyRichTextClassCommentEditorToolMorph>>#initialize
  ClyRichTextClassCommentEditorToolMorph>>#setBackgroundColor:
```

**Comment by demarey** [comment]
> build failure:
> 
> ```
> MetacelloNotification: Loading -> BeautifulComments-tonel.1 --- github://pillar-markup/BeautifulComments:integration/src --- cache
> Error: Package BeautifulComments-Core depends on the following classes:
>   ClyClassCommentEditorToolMorph
>   ClyPackageCommentEditorToolMorph
> You must resolve these dependencies before you will be able to load these definitions: 
>   ClyClassCommentEditorToolMorph>>#new
>   ClyPackageCommentEditorToolMorph>>#new
>   ClyPackageRichTextCommentEditorToolMorph
>   ClyPackageRichTextCommentEditorToolMorph>>#browserTabActivation
>   ClyPackageRichTextCommentEditorToolMorph>>#browserTabActivation2
>   ClyPackageRichTextCommentEditorToolMorph>>#asRenderedText
>   ClyPackageRichTextCommentEditorToolMorph>>#asRenderedText:
>   ClyPackageRichTextCommentEditorToolMorph>>#disable
>   ClyPackageRichTextCommentEditorToolMorph>>#enable
>   ClyPackageRichTextCommentEditorToolMorph>>#fillStatusBar
>   ClyPackageRichTextCommentEditorToolMorph>>#initialize
>   ClyPackageRichTextCommentEditorToolMorph>>#setBackgroundColor:
>   ClyRichTextClassCommentEditorToolMorph
>   ClyRichTextClassCommentEditorToolMorph>>#classCommentTabActivation
>   ClyRichTextClassCommentEditorToolMorph>>#classTabActivation
>   ClyRichTextClassCommentEditorToolMorph>>#asRenderedText:
>   ClyRichTextClassCommentEditorToolMorph>>#disable
>   ClyRichTextClassCommentEditorToolMorph>>#enable
>   ClyRichTextClassCommentEditorToolMorph>>#fillStatusBar
>   ClyRichTextClassCommentEditorToolMorph>>#initialize
>   ClyRichTextClassCommentEditorToolMorph>>#setBackgroundColor:
> ```

It is expected. As I wrote, https://github.com/pillar-markup/BeautifulComments/pull/40 has to be merged first

**Comment by Ducasse** [comment]
I integrated your changes in BC dev. 
Now I do not know why this would break P11 because we did not push anything to probably I push the changes in the integration branch but I do not know.

**Comment by demarey** [comment]
> I integrated your changes in BC dev. Now I do not know why this would break P11 because we did not push anything to probably I push the changes in the integration branch but I do not know.

In this PR I remove ClyClassCommentEditorToolMorph and ClyPackageCommentEditorToolMorph.
Current BC integration branch still has extension methods on theses classes that are now gone.
Once BC/integration branch is updated, it will be ok

**Comment by demarey** [comment]
tests are passing. Only Windows64.Fuel.Tests.Core.Base.FLContextSerializationTest is failing.
See https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-11945/2/pipeline

**Pull request merged**
