### PR TITLE
Revert "Fix #17471: custom Job interruption"

### LINKED ISSUE #17471: Enhance JobProgressBarMorph with custom interruption logic
When we start a `Job`, a `JobProgressBarMorph` is created to display the progress.
This bar has a big red button, *presumably* to stop the process.
image

Clicking anywhere on the bar (not just the button, but that's not the current issue) triggers an event handler to **debug** the process.
image

When the click event is triggered, `debug` is sent to JobProgressBarMorph, which in turn sends `debug` to the process.
image

The issue is that this debugging behavior is hard-coded and may not be what the user/developer intended.
For example, we may want to simply stop the job, without opening the debugger.

To change this behavior, I think the `Job` class should have a configurable interruption logic, i.e. a block.
Instead of sending `debug`, we could send a message such as `interrupt` or `terminate`, and the job should delegate to the configured block.
The default behavior can be to debug, to preserve the original behavior.

### PR DESCRIPTION
**Pull request by tesonep**
Reverts pharo-project/pharo#17474

We need to revert this PR, because we are having some issues .

@astares reported:

I typically use a Laptop and a second monitor as an additional extended screen. When I start and use current Pharo 13 on Windows with the Launcher it appears on the Laptop screen. When I move it to a second monitor screen it is not possible to click into the Pharo main window to open the world menu or any of the tools.
Pharo just hangs and I can only kill it using

taskkill -f /im Pharo.exe

In Pharo 12 I do not see this effect - it works properly.

### CODE REVIEW

**Comment by astares** [comment]
Please do not revert yet. Lets wait and integrate another totally independent PR to see **if the next regular image build** has the same problem or not.

**Comment by astares** [comment]
OK - I have the same effect now also with the latest image build from yesterday:  Pharo13.0-SNAPSHOT.build.383.sha.c3a1fa
so I tested:

- Pharo13.0-SNAPSHOT.build.**383**.sha.c3a1fa - **NOT WORKING**
- Pharo13.0-SNAPSHOT.build.**382**.sha.7f5c321f22.arch.64bit - **NOT WORKING**
- Pharo13.0-SNAPSHOT.build.381.sha.a9008bdd4c.arch.64bit - WORKING
- Pharo13.0-SNAPSHOT.build.380.sha.0902cb2e28.arch.64bit - WORKING

When I move the Pharo window from Laptop screen to external screen with the two non-working images (Build 383 or 382) 
it happes like:
- I move the window to the second screen and it instantly looks like frozen
- there is a white area at the top of the Pharo main window
- size of fonts seem to be bigger than normal
- I can not click anymore into the Pharo window to open world menu or other
- it is not possible (I have to use taskkill)

Here is the effect of a **non working image** as a video from the second screen when I move the 
window to it:
https://github.com/user-attachments/assets/716c41eb-ef4f-4069-a78a-3f3d9dced9af

Here is what a **working image** (Build 381) would look like when moved to the second screen:
https://github.com/user-attachments/assets/df983afa-53cd-4d0b-83c4-47094e0a9453

INTERESTING: As you see the working image also displays the Pharo screen a little bit bigger than normal first - 
but then downsizes and works. Looks like this is a Phase of screen scaling adoption where the **non working images** 
seen to start freezing

System is a Windows 11:
image

The working images and the non-working images **both use the same VM**:

C:\Users\astar\Documents\Pharo\vms\130-x64\Pharo.exe
CoInterpreter VMMaker-tonel.1 uuid: 4041da92-80dd-0d00-9c4a-5c840e3463e4 Sep  2 2024
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: 4041da92-80dd-0d00-9c4a-5c840e3463e4 Sep  2 2024
v10.3.1 - Commit: 6cdb1e5d - Date: 2024-09-02 09:56:37 +0200

Pharo 10.3.1 built on Sep  2 2024 01:39:00 Compiler: 4.2.1 Compatible Clang 8.0.1 (tags/RELEASE_801/final)
VMMaker versionString v10.3.1 - Commit: 6cdb1e5d - Date: 2024-09-02 09:56:37 +0200
CoInterpreter VMMaker-tonel.1 uuid: 4041da92-80dd-0d00-9c4a-5c840e3463e4 Sep  2 2024
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: 4041da92-80dd-0d00-9c4a-5c840e3463e4 Sep  2 2024

**Comment by astares** [comment]
@tesonep Please revert to see if that reverts the bad effect

**Review by astares — APPROVED** [review]

**Comment by guillep** [comment]
hi guys, be careful, I don't think this PR reverts the right thing.

the build in question includes 4 different PRS, and one is related to 4k screens, which seems more related to it.

See the list of prs:

Screenshot_20241213_014153

**Comment by guillep** [comment]
@astares could you test locally by undoing the changes in #17496?

**Comment by astares** [comment]
I tried and it does not help. Same VM - but image > build 281  freeze when moving to the other monitor on my primary laptop with Windows 11. 

I will update the display driver on this one again to see if this has any effect.

**Comment by guillep** [comment]
> I tried and it does not help. Same VM - but image > build 281 freeze when moving to the other monitor on my primary laptop with Windows 11.
> 
> I will update the display driver on this one again to see if this has any effect.

You may beed to apply the change, save and restart, because I think the SDL session/window is not recreated when moving the window from one screen to another.

**Comment by astares** [comment]
@guillep Misunderstanding on my side: I thought you wanted me to manually revert 17512 which had no effect.

Now I checked and can confirm that the issue comes from:

https://github.com/pharo-project/pharo/pull/17496/files

When I use "SDL_RENDERER_PRESENTVSYNC" which is 4 then Pharo gets stuck when moving to the other screen. 
When I use 0 (the old value) then Pharo works also in the new images.

So I think we have to revert #17496 or find a better way to solve #17439

This PR here makes no sense - we should close it and open one to either revert #17496 or have a proper fix for  #17439

**Comment by guillep** [comment]
> @guillep Misunderstanding on my side: I thought you wanted me to manually revert 17512 which had no effect.

No problem ;)

> Now I checked and can confirm that the issue comes from:
> 
> https://github.com/pharo-project/pharo/pull/17496/files
> 
> When I use "SDL_RENDERER_PRESENTVSYNC" which is 4 then Pharo gets stuck when moving to the other screen. When I use 0 (the old value) then Pharo works also in the new images.

Great!
 
> So I think we have to revert #17496 or find a better way to solve #17439

Yes, I don't have now an answer, but it would require some investigation.
There are 100 issues in the SDL repo referencing the `SDL_RENDERER_PRESENTVSYNC` option

https://github.com/search?q=repo%3Alibsdl-org%2FSDL+SDL_RENDERER_PRESENTVSYNC&type=issues

> This PR here makes no sense - we should close it and open one to either revert #17496 or have a proper fix for #17439

Thanks! I'm glad that looking at PRs during insomnia paid off :)

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo/pull/17496">Fix crash of Mac on 4K display by jecisc · Pull Request #17496 · pharo-project/pharo</a></strong></div><div>Fixes #17439
I'm just applying the fix proposed in the issue</div></blockquote>

**Pull request closed without merging**
