### PR TITLE
2309-Add-assertIsEmpty

### LINKED ISSUE #2309: Add #assertEmpty:
I would like to introduce an #assertIsEmpty: because when a test fails on the CI because a collection is not empty, it's hard to debug without seeing the collection.

### PR DESCRIPTION
**Pull request by jecisc**
Introduce #assertEmpty: and #denyEmpty: + use them

The commit also contains some cleanings such as replacing some `assert: something = true` by `assert:` etc.

Fixes #2309

### CODE REVIEW

**Comment by Ducasse** [comment]
I relaunched the CI.

**Comment by jecisc** [comment]
@svenvc My proposal impacts Zinc tests. If this is approved and pass checks (when the CI will be back), do you agree to integrate those changes to Zinc with a compatibility package that would be loaded in Pharo < 8? I can do the PR to do that.

**Comment by astares** [comment]
I'm not convinced we should have it. See my notes in #2309

**Comment by svenvc** [comment]
Hi Cyril,

I understand the rationale, but I think the effect on Zn will be more negative than positive (as I try to maintain compatibility over more Pharo versions), this is also not worth the trouble of an extra compatibility package. The gain is too small, this is more of a style difference to me.

I hope you understand,

Sven

**Comment by jecisc** [comment]
@svenvc Ok

**Comment by Ducasse** [comment]
So what do we do? I would add it because this is nice and after people can use it or not.

**Comment by jecisc** [comment]
I am waiting for the CI to work so that I can check I did not introduce any regression.

**Comment by Ducasse** [comment]
Argh Cyril the package GTSpotter-EventRecorder was removed! Can you resubmit your changes?
Tx

**Comment by astares** [comment]
If you put objections aside then why not: 
 - add the new methods #assertIsEmpty: only in this PR as the subject says. 
 - change the tests that should really use it in separate PR(s)

**Comment by Ducasse** [comment]
Cyril can you check because you have conflict with the removed packages?

**Comment by jecisc** [comment]
I'll do as Astares said to split in 2 PR because I agree it's a really big PR and if a problem arises, it will be easier to repair if we have two PR.

**Comment by jecisc** [comment]
First PR: https://github.com/pharo-project/pharo/pull/2400
Second PR: https://github.com/pharo-project/pharo/pull/2401

**Pull request closed without merging**
