### PR TITLE
2855 autocompletion of a method parameter when typing in a method should be higher

### LINKED ISSUE #2855: autocompletion of a method parameter when typing in a method should be higher
when faced with a method like:
```
executeShould: aBlock inScopeOf: anExceptionalEvent withDescriptionContaining: aString
	^[aBlock value.
 	false] on:  <cursor here>
		do: [:ex | ex return: (ex description includesSubstring: aString) ]
```

And your cursor is after the on: - if you start to type "anE" - the exception parameter is not your first item in the list (its the third, after some letter matching in some un-related classes). I would argue that matching method parameters should always be first in the list - as other wise you always have to scroll down the list, or type more, to easily autocomplete the most commonly used variables?

image

### PR DESCRIPTION
**Pull request by bergel**
Pair programmed with Alejandro Infante. We fixed https://github.com/pharo-project/pharo/issues/2855

### CODE REVIEW

**Comment by macta** [comment]
This is awesome guys, Would be great if this one might be considered for a future Pharo7 update (assuming we do one at some point).

**Comment by Ducasse** [comment]
Thx. I checked the code and it looks ok. Did not try. I plan to rename such classes.

**Comment by Ducasse** [comment]
GLMRubricTextMorphicTest has some red tests but not on my machine.

**Comment by Ducasse** [comment]
I checked and it is working :)

**Pull request merged**
