### PR TITLE
Revert-Spec1-changes

### PR DESCRIPTION
**Pull request by jecisc**
Revert changes to done to Spec 1 during Pharo 8.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
bootstrap seems to fail

**Comment by jecisc** [comment]
I'm on it ;) 

I expect other errors but since it's messy to launch all Pharo tests locally I'll wait for the CI.

**Comment by jecisc** [comment]
I'm working on the new error

**Comment by Ducasse** [comment]
Hi cyril now the revert of iceberg is integrated so it may help you.

**Comment by Ducasse** [comment]
cyril we have 75 failing tests so may be this is better to fix some of them before integrating else we will not see if we break more. What do you think?

**Comment by jecisc** [comment]
I agree.

**Comment by jecisc** [comment]
I reverted some changes to NautilusRefactoring and DependencyAnalyzer that are not yet migrated but still used Spec 2 methods.

**Comment by jecisc** [comment]
I'll take care of the last failures tomorrow

**Pull request merged**
