### PR TITLE
21801 Class comments on some system tests

### PR DESCRIPTION
**Pull request by astares**
https://pharo.fogbugz.com/f/cases/21801/Class-comments-on-some-system-tests

### CODE REVIEW

**Comment by astares** [comment]
Additions of comments - no change in behavior

**Comment by astares** [comment]
test failures unrelated

**Review by jecisc — APPROVED** [review]
I wonder if it is useful to comment Test classes but it cost not much to accept this PR :)

**Comment by jecisc** [comment]
Unrelated failures:

testByteEncoderFromUrl – Unix32.Zinc.Character.Encoding.Tests.ZnCharacterEncoderTests
testByteEncoderFromUrl – Unix32.Zinc.Character.Encoding.Tests.ZnCharacterEncoderTests

**Pull request merged**
