### PR TITLE
Cleanups GradienFillStyle

### LINKED ISSUE #3869: Cleanups GradienFillStyle
- comment #sample is not working
- wrong categorization
- ,,,

### PR DESCRIPTION
**Pull request by astares**
- comment #sample is not working
- wrong categorization
...

Fix #3869

### CODE REVIEW

**Review by MarcusDenker — APPROVED** [review]

**Comment by MarcusDenker** [comment]
This now seems to make tests fail:

Error
GradientFillStyle class>>sample
Stacktrace
GradientFillStyle class(Object)>>doesNotUnderstand: #sample
FLInMemoryBasicSerializationTest(FLBasicSerializationTest)>>testGradientFillStyle
FLInMemoryBasicSerializationTest(TestCase)>>performTest

**Comment by jecisc** [comment]
Also `<script: 'self example inspect'>` should be replaced by `<sampleInstance>`

**Comment by astares** [comment]
I will open a new issue and fix it

**Comment by astares** [comment]
Fixed in https://github.com/pharo-project/pharo/issues/3886
also using ```<sampleInstance>```
@MarcusDenker

**Pull request merged**
