### PR TITLE
21519-RemoveFromSystem-does-not-work-well-with-Undeclareds

### PR DESCRIPTION
**Pull request by MarcusDenker**
RemoveFromSystem does not work well with Undeclareds
	https://pharo.fogbugz.com/f/cases/21519/RemoveFromSystem-does-not-work-well-with-Undeclareds

### CODE REVIEW

**Review by guillep — APPROVED** [review]
Looks good. Also some cleanups to RB

**Comment by MarcusDenker** [comment]
Ups. The RB cleanups where not supposed to be there... but no problem

**Comment by MarcusDenker** [comment]
(I think I forgot to switch back the branch before starting a new one)

**Comment by MarcusDenker** [comment]
There are tests failing that should not.\

testFixObsoleteSharedPools – Unix32.ReleaseTests.ObsoleteTest
testClassNotReferenced – Windows32.GeneralRules.Migrated.Test.RBSmalllintTest


very strange

**Comment by MarcusDenker** [comment]
isReferenced  this is wrong, correct:

isReferenced
	"returns true if the class is referenced from a method"
	^self environment allBehaviors 
		anySatisfy: [ :behavior | behavior hasSelectorReferringTo: self binding]

**Comment by MarcusDenker** [comment]
even more tests failing.

**Comment by MarcusDenker** [comment]
I will redo this (in two steps). It seems that by moving classes to Undeclared, we get Obsolete classes in some situations where we did not before, this needs some analysis. The #isReferenced change is independent, I will do that before.

**Pull request closed without merging**
