### PR TITLE
Do not disable system announcements during rpackage tests

### PR DESCRIPTION
**Pull request by jecisc**
RPackage tests were disable the system announcer but this causes multiple problems such as:
- Automatic transformation was happening but no tool were aware of it (Calypso did not update the source, Iceberg did not catch the change...)
- Coding in debugger was dangerous because no system announcements were happening 
- The system was vulnerable during the execution of those tests

So I propose to just keep the system announcer while testing RPackage

Also I shipped some deprecation rewrites now that Iceberg notice them :)

### CODE REVIEW

**Review by privat — APPROVED** [review]
This is interesting. We want announcements to not necessarily be global (especially for tests), but in practice it's hard to achieve.

**Comment by jecisc** [comment]
Yes!

The problem here is that the way to not do system announcement impact everything.

Ideally, you want an announcer specific for the code generated by your new package organizer and keep the global one for the code of the tests itself.

Maybe a solution would be to make RPackageOrganizer hold an announcer and use this one. Default RPackageOrganizer would use the system announcer and the test would have their own instance that is not the global one?

**Comment by jecisc** [comment]
Let's note that for now this is hard to do because it's SystemOrganizer that launches the announcements. But when RPackageOrganizer will replace SystemOrganizer, it should be easy not to use global announcer everywhere :)

**Comment by jecisc** [comment]
testOnlyWeakSubscriptions fails and seems to be related.

**Comment by jecisc** [comment]
RPackage tests where using strong subscription to announcements. I added a fix to make all subscriptions weak

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
