### PR TITLE
21976-imagePath-should-be-correctly-encoded-and-decoded

### PR DESCRIPTION
**Pull request by samakhov**
Fix imagePath encodings

### CODE REVIEW

**Review by dionisiydk — COMMENTED** [review]
Is it ensured by VM that image path is returned as utf8 byte string?

**Comment by samakhov** [comment]
We test it on linux, and that is what the vm was excepting. (probably on Mac so)

**Comment by dionisiydk** [comment]
I am just sure that on old Windows (XP, 7) it will not work with Russian location. Because it used 1251 encoding. I got such problems in past.
Now it could be not a problem with modern Windows. But I think it would be better to make this encoding configurable than hardcode it.
I think we already have some location objects in system. So we can delegate this logic there.

**Comment by guillep** [comment]
We are checking the VM code. It looks like:
 - in osx it uses utf8 encoding (https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/6908eda8f6c7d63258a5c592c5370ebbd3e440e4/platforms/Mac%20OS/plugins/FilePlugin/sqMacUnixFileInterface.c)
 - in windows it just uses the raw bytes (https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/6908eda8f6c7d63258a5c592c5370ebbd3e440e4/platforms/win32/plugins/FilePlugin/sqWin32FilePrims.c)

But in any case, right now we are performing no encoding at all, so russian does not work either :)
I'd say to (if build goes ok) we integrate this and then we can iterate it. The perfect solution is difficult to have here all at once because it is very platform dependent.

**Comment by Ducasse** [comment]
I relaunch the build, even if the broken tests do not seem related (mostly traits)

**Comment by pavel-krivanek** [comment]
retrying

**Comment by akgrant43** [comment]
Just for the record for people (like me) not familiar with the mac:

Mac OS file names are Mac-specific decomposed UTF8 encoded strings.  The Mac provides the libraries to convert from precomposed UTF8 (what Pharo typically deals with) and the decomposed UTF8.

The approach I've seen in the VM so far is that the VM takes care of converting between the decomposed and precomposed UTF8 on the Mac platform.  I didn't look through sqMacUnixFileInterface.c that Guille linked to above, but it probably does the right thing.

Cheers,
Alistair

**Pull request merged**
