### PR TITLE
22165-During-Pharo-development-add-Alpha-to-the-Pharo-logo

### PR DESCRIPTION
**Pull request by jecisc**
During Pharo development add "Alpha" to the logo.

https://pharo.fogbugz.com/f/cases/22165/During-Pharo-development-add-Alpha-to-the-Pharo-logo

### CODE REVIEW

**Comment by jecisc** [comment]
image

**Comment by jecisc** [comment]
I think this might help to clarify that this version of Pharo is not for production but for development and testing.

**Comment by jecisc** [comment]
@estebanlm What do you think if this? I can also add a "Pharo beta" image for when you announce a Pharo freeze phase.

**Comment by bencoman** [comment]
good idea

**Comment by astares** [comment]
I would find it disturbing and I dislike this idea for several reasons:

 - this is a logo and not the version we display here (the version is already in the reporter and
    the about box) and the version clearly says it is alpha
 - this makes work as we have to adopt the right logo anytime we switch from alpha to beta to release
 - even in alpha phase we try to be production ready
    (even with a release we are not finished and can have bugs or an unstable image - thats why we have backports) 
 - people who are on Pharo 7 typically know that they are running alpha code
   (there never was a complain from people that it is not like this)
 - anyone should have the freedom to decide if he runs already such (possibly) unstable images in production
- it looks like this is the logo of a "Pharo ALPHA" software - if a newbee does not know about 
  running into alpha version he might not know what "alpha" really means.

I do not understand which deep problem we try to solve with that? 

You want to keep non-developers/non-contributers from lamenting and point them to the previous "perfect" release. Impossible ;)

Because even a release is not perfect, it's a snapshot in time and people won't stop finding bugs.
See "Perfection & Feedback Loops" from @MarcusDenker

**Comment by jecisc** [comment]
- Not everyone checks the about box. I think it's cool to have it displayed directly in the World
- For adapting the logo, later I would like to have a more automatic way to do releases. Maybe SystemVersion could know if we currently are in alpha/beta/release?
- But it stays an alpha phase
- Since I'm in the community, I see many people complain about the stability of Pharo 7. And I don't talk about people reporting bugs, but people complaining that some things are broken in the Pharo alpha. 
- That would not remove this right. Usually, when people use Pharo in production it's either headless or the logo is changed to use the logo of the product.

Also, this PR only adds a logo for the Alpha, but I think it would be interested to have a logo for the beta also. Currently, it's not obvious to know when we are in freezing phase or not because it is just one mail on the ML in general.

**Comment by jecisc** [comment]
Most of the tools I use on alpha/beta have it written in their logo to make it really explicit. Not just hidden in an "info" box.

Also, for example, there are teachers using Pharo 7 for teaching. I don't know if they say to their students it's an alpha version. At least with that, if a student gets a bug, he knows he is in an alpha version.

**Comment by astares** [comment]
It may be annoying to you but it is good that they complain - because this is the driver to repair broken things. Would you like them to be silent so we do not find issues that we broke in P7alpha quickly?

I'm by 100% sure that exchanging the logo wont help you with that. 

The last official "stable" release like 6.1 is on the webpage, the others are marked 
as alpha already:
 - in versioning like "Pharo-7.0.0-alpha.build.1067.sha.8c2828a.arch.32bit"
 - in downloads like PharoLauncher and ZeroConf with the following distinction
        "https://get.pharo.org/stable"
        "https://get.pharo.org/alpha"

So someone has to do additional steps/effort to come into the "alpha" release and 
if he is there and wants nonetheless to complain I doubt the changed logo will stop
him from doing so...

**Comment by pavel-krivanek** [comment]
bikeshedding.
For me, the logo is really not a place where to put this information. I would understand if we would have a version number e.g. in the top right corner of the main menubar because then it can be used for custom version information too (if you have project images in many different versions, you may find it useful), but, please, not in the logo.

**Comment by estebanlm** [comment]
Hi, @jecisc. 

Sorry, I do not like this change. 
And I do not think the people needs a hint of the version they are using. People downloading 7.0 knows is a development version. If you want a clear hint in your development process, you can always add a start-up action.

**Pull request closed without merging**
