### PR TITLE
21611-Adapt-ImageReadWriter-hierarchy-to-need-only-pure-binary-streams

### PR DESCRIPTION
**Pull request by svenvc**
A set of changes that refactors the ImageReadWriter hierarchy to work with simple binary streams (need for Pharo 7 new stream/file implementation)

https://pharo.manuscript.com/f/cases/21611/Adapt-ImageReadWriter-hierarchy-to-need-only-pure-binary-streams

### CODE REVIEW

**Comment by svenvc** [comment]
This needs some Zinc changes before it can be integrated

**Comment by svenvc** [comment]
Now that https://github.com/pharo-project/pharo/pull/1318 is integrated, this can now proceed.

How do I reactivate it ?

**Comment by estebanlm** [comment]
I restarted the test

**Comment by guillep** [comment]
Still, I don't think that will be enough because it will test against the same version of the target branch as before (I don't know if that's a jenkins or github problem...). If restarting does not work, try  closing and reopening the PR.

**Comment by estebanlm** [comment]
not like this... you need to close this and do a new PR from your branch :)

**Comment by svenvc** [comment]
OK, I am stuck.

With a newly downloaded Pharo 7 with the Zn changes (newer than where the issue branch was created from), I tried to merge from my local issue branch into the image. 

That worked in the sense that the changes that I saw were correct (to Graphics-Files and Graphics-Tests), but the actual merge in the image failed to load all code (I think all new methods/classes were lost). I did get a warning that merging into a non-clean image is experimental, I proceeded.

I also cannot make a new PR, it says that a PR already exists for that branch (validation error). See attached screenshot.

screen shot 2018-05-09 at 14 30 02

**Comment by estebanlm** [comment]
you can try now :)

**Comment by svenvc** [comment]
OK, thanks, I think I did it.

But still, I would have felt better if I could review my own PR in a newer image, because the merge did not completely succeed.

> On 9 May 2018, at 14:44, Esteban Lorenzano <notifications@github.com> wrote:
> 
> you can try now :)
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Sven Van Caekenberghe - mailto:sven@beta9.be
Beta Nine - software engineering - http://www.beta9.be

**Pull request closed without merging**
