### PR TITLE
Typo on the word "occurrences"

### LINKED ISSUE #7012: Typo on the word Occurrences
I did a typo in a Spotter research by typing "occurence" instead of "occurrence" and I got 14 implementors with this typo. 

I would be nice to fix them. This can be a really easy issue for beginners or a sprint.

### PR DESCRIPTION
**Pull request by sic-f**
Fixes #7012 

Fix typo "occurence" to correct spelling "occurrence"

### CODE REVIEW

**Comment by Ducasse** [comment]
Thanks!!!
can you check because we have related broken tests
- testCopyReplaceAllWithManyOccurrence – Unix64.Collections.Tests.Sequenceable.IntervalTest
- testCopyReplaceAllWithManyOccurrence – Unix64.Collections.Tests.Sequenceable.LinkedListTest
- testTAddWithOccurrences – Unix64.Collections.Tests.Sequenceable.LinkedListTest
- testLocalMethodsOfTheClassShouldNotBeRepeatedInItsTraits – Unix64.ReleaseTests.Release.ReleaseTest

**Comment by Ducasse** [comment]
This is strange that we get such broken tests because your changes are looking good.
This is the power of tests. Helping us :)

**Comment by sic-f** [comment]
> This is strange that we get such broken tests because your changes are looking good.
> This is the power of tests. Helping us :)

Yeah weird those tests weren't even used by the client test classes.

**Comment by sic-f** [comment]
@Ducasse found the culprit. I did not update the traits usage declaration in those tests that were referencing the trait methods with the typo (for exclusion purposes). The test cases that were being excluded (with the typo) are now being included because of the now different spelling, which causes the tests to fail, as they were not intended to be included at all.

**Comment by Ducasse** [comment]
Indeed! May be the refactorings was not good enough!

**Comment by Ducasse** [comment]
I think that you modified the methods in the class instead of the traits. So the system created a new method instead of reusing the existing one.  In any case this is cool that you help us!

unix-64 / Tests-unix-64 / testLocalMethodsOfTheClassShouldNotBeRepeatedInItsTraits – Unix64.ReleaseTests.Release.ReleaseTest
<1s
Error

If a class has a method in its trait composition, the method should not be implemented in the class. Violations:  - StringTest - SortedCollectionTest - SortedCollectionTest - FloatArrayTest - SortedCollectionTest - SymbolTest - ArrayTest - ArrayTest - OrderedCollectionTest - StringTest - StringTest - FloatArrayTest - OrderedCollectionTest - SymbolTest - SortedCollectionTest - SymbolTest - FloatArrayTest - ArrayTest - StringTest - FloatArrayTest - OrderedCollectionTest - SymbolTest - OrderedCollectionTest - ArrayTest
Stacktrace

TestFailure
If a class has a method in its trait composition, the method should not be implemented in the class.
Violations: 
- StringTest
- SortedCollectionTest
- SortedCollectionTest
- FloatArrayTest
- SortedCollectionTest
- SymbolTest
- ArrayTest
- ArrayTest
- OrderedCollectionTest
- StringTest
- StringTest
- FloatArrayTest
- OrderedCollectionTest
- SymbolTest
- SortedCollectionTest
- SymbolTest
- FloatArrayTest
- ArrayTest
- StringTest
- FloatArrayTest
- OrderedCollectionTest
- SymbolTest
- OrderedCollectionTest
- ArrayTest
ReleaseTest(TestAsserter)>>assert:description:resumable:
ReleaseTest(TestAsserter)>>assert:description:
ReleaseTest>>assertValidLintRule:withExceptions:
ReleaseTest>>testLocalMethodsOfTheClassShouldNotBeRepeatedInItsTraits
ReleaseTest(TestCase)>>performTest

**Comment by sic-f** [comment]
> I think that you modified the methods in the class instead of the traits. So the system created a new method instead of reusing the existing one. In any case this is cool that you help us!

@Ducasse Yeah I just reviewed the changes and there were new methods implemented in those test classes in the error even if I did not implement them. The computer somehow magically put those methods in the test classes.

I redid that one commit wherein the changes were just for typos in comments. But somehow again, those methods in the trait were magically implemented in the test classes. Weird. So I just did not include those changes. 

Hope the CI passes this time.

**Comment by sic-f** [comment]
@Ducasse now it's the _TestTookTooMuchTime_ error. Is this just a matter of rebuilding the CI?

**Comment by Ducasse** [comment]
TestTookTooMuchTime is a bad watch dog because we cannot control the build machine.

**Comment by Ducasse** [comment]
But I wonder why we would get this warning for Unix64.Collections.Tests.Sequenceable.LinkedListTest 
may be there is an infinite loop and the test infrastructure is catching it.

**Comment by Ducasse** [comment]
Could you run  testTAddWithOccurrences on your image?

**Comment by sic-f** [comment]
> Could you run testTAddWithOccurrences on your image?

@Ducasse ok let me do that.

**Comment by Ducasse** [comment]
Do you see the last error reported by the CI?

**Comment by sic-f** [comment]
> Do you see the last error reported by the CI?

@Ducasse yes I saw the last error in Jenkins, sorry was busy yesterday. I'll take a look at this tomorrow.

**Comment by sic-f** [comment]
@Ducasse I've found out the problem that solved the `testTAddWithOccurrences` failure and have pushed another commit

Not sure this time what is the problem in Jenkins

jenkins___Test_pending_pull_request_and_branch_Pipeline___PR-7158____4

I have tried running all the tests in `Collections-Tests` and everything was fine. Any idea?

**Comment by Ducasse** [comment]
Great all the tests pass! So I push it. Thanks!

**Comment by Ducasse** [comment]
Thanks again for your contribution!

**Comment by sic-f** [comment]
> Thanks again for your contribution!

No problem. Glad to help!

**Pull request merged**
