### PR TITLE
6962-Spec2-add:expand:fill

### LINKED ISSUE #6962: [Feature Request] SpBoxLayout should have "add:expand:fill" method
I think that it will be useful to have an `add:expand:fill` in the SpBoxLayout class. I have experienced some cases where I want to add a presenter with `expand` and `fill` properties but not modifying padding. So, I have the following situation:
```
^ SpBoxLayout new
        add: #aPresenter 
        expand: true
        fill: true
        padding: 0
```
Which I found that will be better just to call `add:expand:fill`.

### PR DESCRIPTION
**Pull request by jordanmontt**
fixes #6962

### CODE REVIEW

**Comment by Ducasse** [comment]
Thanks Sebastian I let esteban answer you.

**Comment by estebanlm** [comment]
Hi, @jordanmontt 
This will work :) ;
But... I it requires a twin method for addLast... (addLast:expand:fill:).
If you add it, I will accept the PR 

thanks!
Esteban

**Comment by jordanmontt** [comment]
Hi Esteban,
I added the twin method.
Thanks

**Review by estebanlm — APPROVED** [review]
but let's wait until I merge 0.7.3 to include it ;)

**Comment by MarcusDenker** [comment]
I committed it to the spec repo

**Pull request closed without merging**
