### PR TITLE
Unsubscribe announcements from finalization registry

### PR DESCRIPTION
**Pull request by guillep**
Announcements are not correctly removed from the finalization registry when explicitly removed.
This causes a bloat of ephemerons related to change sets that are created during the bootstrap.

Also, improve a bit the bootstrap to allow out of source builds.

I'll produce a backport to Pharo11

### CODE REVIEW

**Comment by jecisc** [comment]
There is an error on the bootstrap probably linked to the changes in the bootstrap file:

```
Archiving artifacts
‘bootstrap-cache/*.zip’ doesn’t match anything, but ‘build/bootstrap-cache/*.zip’ does. Perhaps that’s what you mean?
No artifacts found that match the file pattern "bootstrap-cache/*.zip,bootstrap-cache/*.sources". Configuration error?
```

**Review by tesonep — APPROVED** [review]

**Comment by MarcusDenker** [comment]
Error is still there:

`` ‘bootstrap-cache/*.zip’ doesn’t match anything, but ‘build/bootstrap-cache/*.zip’ does. Perhaps that’s what you mean?``

**Comment by jecisc** [comment]
We have a bunch of related test failures. The weird thing is that it passes in P11. Maybe something in Pharo changed?

**Comment by jecisc** [comment]
I took the artefact and launched the failing tests and they are passing. So it might be that some tests are breaking something in the image and that it causes those tests to fail. I'll try to restart the ci just in case

Here it the list of failing tests:

osx-64 / Tests-osx-64 / testSessionStackProvidesSameStackAsTheActionModelOne – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest<1s
osx-64 / Tests-osx-64 / testToolbarInDNUContext – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest9s
osx-64 / Tests-osx-64 / testMethodModified – MacOSX64.Reflectivity.Tests.Base.LinkInstallerTest7s
osx-64 / Tests-osx-64 / testMethodRemoved – MacOSX64.Reflectivity.Tests.Base.LinkInstallerTest6s
osx-64 / Tests-osx-64 / testNodesRemovedFromLinkWhenMethodRemovedFromObject – MacOSX64.Reflectivity.Tests.Base.LinkInstallerTest7s
osx-64 / Tests-osx-64 / testBuildingClassesWithSlotsClassifiesItsMethods – MacOSX64.Shift.ClassInstaller.Tests.ShClassInstallerTest4s
osx-64 / Tests-osx-64 / testChangingASharedPoolUpdatesCorrectlyUsers – MacOSX64.Shift.ClassInstaller.Tests.ShClassInstallerTest6s
osx-64 / Tests-osx-64 / testChangingSlotCallsInitializeSlotOnInstanceMigration – MacOSX64.Shift.ClassInstaller.Tests.ShClassInstallerTest4s
osx-64 / Tests-osx-64 / testClassWithSlotCallsInitializeSlotOnInstanceCreation – MacOSX64.Shift.ClassInstaller.Tests.ShClassInstallerTest4s
osx-64 / Tests-osx-64 / testClassWithSlotHasInitializeMethodWithInitializeSlots – MacOSX64.Shift.ClassInstaller.Tests.ShClassInstallerTest4s
osx-64 / Tests-osx-64 / testDuplicateClassPreserveMethods – MacOSX64.Shift.ClassInstaller.Tests.ShClassInstallerTest5s
osx-64 / Tests-osx-64 / testDuplicateClassPreserveSlots – MacOSX64.Shift.ClassInstaller.Tests.ShClassInstallerTest4s
osx-64 / Tests-osx-64 / testModifyingClassKeepsOrganizationOfMethods – MacOSX64.Shift.ClassInstaller.Tests.ShClassInstallerTest6s
osx-64 / Tests-osx-64 / testPackageOfRemovedTrait – MacOSX64.TraitsV2.Tests.T2TraitWithPackagesTest<1s
unix-64 / Tests-unix-64 / testLinkToClassVarNameWrites – Unix64.Reflectivity.Tests.Base.MetaLinkObjectAPITest<1s
unix-64 / Tests-unix-64 / testLinkToSlotNamedAll – Unix64.Reflectivity.Tests.Base.MetaLinkObjectAPITest<1s
unix-64 / Tests-unix-64 / testLinkToSlotNamedReads – Unix64.Reflectivity.Tests.Base.MetaLinkObjectAPITest<1s
unix-64 / Tests-unix-64 / testLinkToSlotNamedWrites – Unix64.Reflectivity.Tests.Base.MetaLinkObjectAPITest<1s
unix-64 / Tests-unix-64 / testLinkToTempVarNameAll – Unix64.Reflectivity.Tests.Base.MetaLinkObjectAPITest<1s
unix-64 / Tests-unix-64 / testLinkToTempVarNameReads – Unix64.Reflectivity.Tests.Base.MetaLinkObjectAPITest<1s
unix-64 / Tests-unix-64 / testLinkToTempVarNameWrites – Unix64.Reflectivity.Tests.Base.MetaLinkObjectAPITest<1s
unix-64 / Tests-unix-64 / testPackageOfRemovedTrait – Unix64.TraitsV2.Tests.T2TraitWithPackagesTest

**Comment by jecisc** [comment]
This fix seems to pass the tests but there are still some leaks that Pablo is currently fixing in Pharo 11. Once this is done, this PR will be updated and we can merge. For now we should wait for this one

**Pull request merged**
