### PR TITLE
21914 integrate epicea v8.3.0

### PR DESCRIPTION
**Pull request by tinchodias**
In fogbugz: https://pharo.fogbugz.com/f/cases/21914/Integrate-Epicea-8-3-0

I'd like to move Epicea*, Ombu* and Hiedra* packages to github repositories (first and second are too related so they share repo). I've already:

- https://github.com/tinchodias/epicea
- https://github.com/tinchodias/hiedra

The code there is a copy from the directories in pharo:development + applying the package renames EpiceaTest->Epicea-Test and similar.

What needs review are my changes to BaselineOfIDE. I tried to imitate how Iceberg is loaded.

### CODE REVIEW

**Comment by pavel-krivanek** [comment]
Project: IDE baseline  Error: Name not found: OmbuTests

**Comment by tinchodias** [comment]
@pavel-krivanek how should I inspect the log? I open the link and either see or download the lod and it's empty

**Comment by tinchodias** [comment]
Also, I didn't find how to re-launch the build manually (without a new commit). Can I?

**Comment by MarcusDenker** [comment]
it fails very early


[ [ actionBlock on: MetacelloLookupProjectSpec , MetacelloLookupProjectSpecForLoad , MetacelloProjectSpecLoadedNotification , MetacelloScriptEnsureProjectLoadedForDevelopment , MetacelloLookupBaselineSpecForEnsureLoad do: [:ex |  ex handleResolutionFor: self ] ] on: MetacelloAllowProjectDowngrade , MetacelloAllowProjectUpgrade , MetacelloAllowConflictingProjectUpgrade do: [:ex |  ex handleResolutionFor: self ] ] in [ [ [ actionBlock on: MetacelloLookupProjectSpec , MetacelloLookupProjectSpecForLoad , MetacelloProjectSpecLoadedNotification , MetacelloScriptEnsureProjectLoadedForDevelopment , MetacelloLookupBaselineSpecForEnsureLoad do: [:ex |  ex handleResolutionFor: self ] ] on: MetacelloAllowProjectDowngrade , MetacelloAllowProjectUpgrade , MetacelloAllowConflictingProjectUpgrade do: [:ex |  ex handleResolutionFor: self ] ] on: MetacelloAllowLockedProjectChange do: [:ex |  ex handleResolutionFor: self ] ] in MetacelloScriptEngine>>handleNotificationsForAction: in Block: [ [ actionBlock on: MetacelloLookupProjectSpec , M...etc...

BaselineOfIDE>>postload:package: (EpMonitor is Undeclared) 
starting...
UIThemeRegistry
bitmap fonts loaded
UIManager changed:NonInteractiveUIManager
SmalltalkEditor initialized.
 ------------ Obsolete ------------
#()
 ............ Obsolete ............
script returned exit code 1

**Comment by MarcusDenker** [comment]
I wonder if it is even possible to load Epicea late... shouldn't the mechanism to log source code be core functionality?

**Comment by MarcusDenker** [comment]
Considering the original idea was that it was one part of being able to not have .changes anymore

**Comment by tinchodias** [comment]
Hi @MarcusDenker thanks for the log. I wonder why I couldn't find it by myself. I don't know what to answer to your question.

**Comment by tinchodias** [comment]
Epicea subscribes to system announcements to log its stuff. The only special thing (hack) I remember is using Job to determine if a code change is triggered
- by the user or
- by Monticello loading, or
- by Epicea applying a redo or undo.
which made me push a small change in some method of Monticello and maybe some other package too.
If my memory doesn't fail, there was no need to consider Epicea to be special in core. Maybe I didn't understand your question.

**Comment by Ducasse** [comment]
Hi martin. 
So what do we do? I do not know how to relaunch the validation.

Stef

**Comment by Ducasse** [comment]
I relaunched the build and I get

[32] Loaded -> BaselineOfMetacello-tonel.1 --- tonel:///builds/workspace/and_branch_Pipeline_PR-1366-DXBUCT6E4AU7XRO5KR57YQYKUXCB2FNYEOBMP4S3LPPPZP53OC6A/32/src --- cache
[32] Loaded -> ReferenceFinder-Core-tonel.1 --- tonel:///builds/workspace/and_branch_Pipeline_PR-1366-DXBUCT6E4AU7XRO5KR57YQYKUXCB2FNYEOBMP4S3LPPPZP53OC6A/32/src --- cacheMessageNotUnderstood: receiver of "current" is nil
[32] UndefinedObject(Object)>>doesNotUnderstand: #current
[32] BaselineOfIDE>>postload:package:
[32] [:aLoader :pkgSpec |  self project configuration perform: selector with: aLoader with: pkgSpec ] in MetacelloMCVersionSpec(MetacelloSpec)>>doItBlock: in Block: [:aLoader :pkgSpec |  self project configuration p...etc...
[32] BlockClosure>>valueWithPossibleArgs:
[32] [ block valueWithPossibleArgs: (Array with: aPostloadDirective loader with: aPostloadDirective spec) ] in MetacelloLinearLoadDirective(MetacelloVersionLoadDirective)>>loadPostloadDirective: in Block: [ block valueWithPossibleArgs: (Array with: aPostl...etc...
[32] MetacelloPostLoadDirective(MetacelloPrePostLoadDirective)>>evaluateSupplyingAnswers:
[32] MetacelloLinearLoadDirective(M

**Comment by guillep** [comment]
Martin check that the BaselineOfIDE is trying to initialize some Epicea
class.

EpMonitor current enable.

If you remove Epicea from Pharo like that you should be careful of:
 - removing all Epicea packages from the repository (I mean, deleting the
files)
 - Checking that the Postloads work ok

This said, I'm not sure moving Epicea to an external based approach is
necessarily good.
Already with Iceberg and Calypso is a bit painful.
But we can try...

**Comment by Ducasse** [comment]
To be I would not move epicea out of Pharo repo. 
Yes it will be a huge pain. I heard that google has many projects under the same projects

**Comment by tinchodias** [comment]
@guillep @Ducasse thanks. Yes, I answered Marcus but didn't have time to fix the reference to EpMonitor he pointed. 

**BUT...**

After reading your opinions, I think we can go for another alternative:
- keep all Epicea, Ombu and Hiedra code in this repo, and 
- consider this as the "official" repository for Epicea and Hiedra, and
- stop using sthub/Epicea as official repo.

If Pharo 6.1 still needs some patch, then it will be loaded from sthub/Epicea.
For Pharo > 6.1, this will be the official code.

**Explanation:**

With this PR, I had no other interest than making contributions/maintenance easier for all... and it looked easier to make github PRs than either:
- talk with me to get write permission to commit in sthub/Epicea (I could make it public, ok).
- commit into this Pharo repo and then I have to copy/merge changes back to official sthub/Epicea, to create a new version in ConfigurationOfEpicea and then create a PR to integrate into this repo the new version.

I mean, first is harder for contributor, second is harder to maintainer. So I wanted to fix that in some way.

**Comment by tinchodias** [comment]
If you agree with my previous message, then let's 
- close this PR
- deprecate [sthub/epicea](http://smalltalkhub.com/#!/~MartinDias/Epicea) (update its readme) for pharo > 6.1
- delete [jenkins job](https://ci.inria.fr/pharo-contribution/job/Epicea/)

**Comment by Ducasse** [comment]
Thanks martin because right now and probably for still a long period, each time we separate a project it makes changes a lot harder.

**Comment by MarcusDenker** [comment]
yes, I think that is better

**Comment by astares** [comment]
https://pharo.fogbugz.com/f/cases/21914/ is still not solved, how do we proceed on that?

**Pull request closed without merging**
