### PR TITLE
3289-beForText-is-deprecated-but-there-are-two-senders

### LINKED ISSUE #3289: #beForText is deprecated but there are two senders
... one is in createNotifierPaneWidgets of the debugger.

This means that one gets an infinite loop as soon as the debugger tries to open

### PR DESCRIPTION
**Pull request by MarcusDenker**
fixed #3289

### CODE REVIEW

**Review by StephanEggermont — CHANGES_REQUESTED** [review]
Uhm, not calling the deprecated method is not going to result in the correct widget being used?

**Comment by jecisc** [comment]
Before TextPreserter managed Text and Code. Now we have two different presenters. 

So if we instantiate a text presenter, the behavior will be correct. If we instantiated a Code presenter, it will not be correct. 

In case we want a code presenter which can sometimes present text (it happens for example in the changes sorter), esteban is working on the disabling of syntax highlighting for the CodePresenter.

**Comment by MarcusDenker** [comment]
failing tests not related

**Comment by Ducasse** [comment]
Indeed it looks good. Tx Cyril.

**Comment by StephanEggermont** [comment]
So yes, the correct widgets are being used. The pre-debugger doesn't show code, and the behavioral change in TextPresenter is that it now shows text by default, not code.

**Pull request merged**
