### PR TITLE
Deprecate Gofer

### PR DESCRIPTION
**Pull request by jecisc**
Gofer does not seems to be used anymore. This change finished to deprecate gofer and removes the tests.

### CODE REVIEW

**Comment by Ducasse** [comment]
Yes :)

**Comment by Ducasse** [comment]
This is probably not related but we have a broken build

```


SystemNotification: Loading Metacello-GitHub-tonel.1.mcz
SystemNotification: Loading Metacello-Bitbucket-tonel.1.mcz
SystemNotification: Loading MetacelloCommandLineHandler-Core-tonel.1.mcz
+ /builds/workspace/est_and_branch_Pipeline_PR-15897/64/build/bootstrap-downloads/vmtarget/pharo --headless Pharo12.0-PR-metacello-64bit-6c25fc0.image --no-default-preferences eval --save 'Metacello new baseline: '\''Tonel'\'';repository: '\''github://pharo-vcs/tonel:Pharo12'\'';onWarning: [ :e | Error signal: e messageText in: e signalerContext ]; load: '\''core'\'''
NotFound: BaselineOfTonel
[ NotFound signal: aName ] in MCGitHubRepository(MCRepository)>>packageNamed: in Block: [ NotFound signal: aName ]
MCFileTreeRepository(MCRepository)>>packageNamed:ifPresent:ifAbsent:
MCGitHubRepository(MCGitBasedNetworkRepository)>>packageNamed:ifPresent:ifAbsent:
MCGitHubRepository(MCRepository)>>packageNamed:ifAbsent:
MCGit

```

**Comment by guillep** [comment]
Yes, the build is broken because of this PR https://github.com/pharo-spec/NewTools-WelcomeBrowser/pull/16

I'll try to fix it fast, or otherwise revert it.

**Comment by Ducasse** [comment]
Strange the build failed.

**Comment by guillep** [comment]
we just need to re run it :) Last time it ran the build was broken

**Comment by Ducasse** [comment]
But I just rerun it because of that :)

**Comment by Ducasse** [comment]
I do not see how this is related to Gofer.
```
SystemNotification: Creating Snapshot of: Zinc-Character-Encoding-Core
SystemNotification: Creating Snapshot of: Zinc-Resource-Meta-Core
SystemNotification: Loading Debugging-Core-tonel.1.mcz
SystemNotification: Loading Ring-OldChunkImporter-tonel.1.mcz
SystemNotification: Loading System-Announcements-tonel.1.mcz
An error happened while reading MCZ. We will fallback to another format. Short error stack: ReadStream(Object)>>doesNotUnderstand: #nextWordsInto:
WideString class>>newFromStream:
MCDataStream>>readWordLike
MCDataStream>>next
MCClassDefinition(Object)>>readDataFrom:size:
MCDataStream>>readInstance
MCDataStream>>next
MCDataStream>>readArray
MCDataStream>>next
MCSnapshot(Object)>>readDataFrom:size:

SystemNotification: Loading Files-tonel.1.mcz
An error happened while reading MCZ. We will fallback to another format. Short error stack: ReadStream(Object)>>doesNotUnderstand: #nextWordsInto:
WideString class>>newFromStream:
MCDataStream>>readWordLike
MCDataStream>>next
MCClassDefinition(Object)>>readDataFrom:size:
MCDataStream>>readInstance
MCDataStream>>next
MCDataStream>>readArray
MCDataStream>>next
MCSnapshot(Object)>>readDataFrom:size:

```

**Comment by Ducasse** [comment]
And I do not get it because I could run the build of another PR that I did about Mock object documentation and rename refactoring lost menu.
SO this is strnage that this is only breaking for this one.

**Comment by Ducasse** [comment]
In addition there is 
```
+ /builds/workspace/est_and_branch_Pipeline_PR-15897/64/build/bootstrap-downloads/vmtarget/pharo --headless Pharo12.0-PR-metacello-64bit-7a60c36.image --no-default-preferences eval --save 'Metacello new baseline: '\''Tonel'\'';repository: '\''github://pharo-vcs/tonel:Pharo12'\'';onWarning: [ :e | Error signal: e messageText in: e signalerContext ]; load: '\''core'\'''
NotFound: BaselineOfTonel
[ NotFound signal: aName ] in MCGitHubRepository(MCRepository)>>packageNamed: in Block: [ NotFound signal: aName ]
MCFileTreeRepository(MCRepository)>>packageNamed:ifPresent:ifAbsent:
MCGitHubRepository(MCGitBasedNet
```

**Comment by guillep** [comment]
I found the potential cause:

There is a method that I wrongly packaged with Gofer, and thus this PR is "removing it" from the kernel as deprecated.

imagen

Thus lookup goes up to the superclass definition and fails.
We should move `MCFileBasedRepository>>packageNamed:ifPresent:ifAbsent:` to its own class.

**Comment by jecisc** [comment]
Thank you Guille for finding this. I updated the PR

**Comment by guillep** [comment]
Oh that was fast!

**Pull request merged**
