### PR TITLE
Deprecated-TextMorphForEditView

### PR DESCRIPTION
**Pull request by jecisc**
Since PluggableTextMorph is deprecated, TextMorphForEditView should also be deprecated.

Deprecated this class, its subclass and the features of the image only used by this class.

### CODE REVIEW

**Comment by jecisc** [comment]
The failure seems related.

**Comment by Ducasse** [comment]
YES!!!

**Comment by jecisc** [comment]
I fixed the problem raised by the CI. Let's see if it finds a new problem.

**Comment by Ducasse** [comment]
Let us check again

**Comment by MarcusDenker** [comment]
tests look ok

**Comment by estebanlm** [comment]
recheck

**Comment by MarcusDenker** [comment]
I changed the PR to be for pharo9

**Comment by guillep** [comment]
Should this go now to `Deprecated90` instead of `Deprecated80`?

Otherwise I think the change is good.

**Comment by guillep** [comment]
I'll time out this PR on friday :)

**Comment by Ducasse** [comment]
One of the problem is that we have still some users of PluggableListMorph. 
Developing Pharo is a guerre eternelle.

**Comment by guillep** [comment]
Ok, I've talked to @jecisc , he'll take care of it later.
I'll close the PR, that does not kill the branch, so a future PR could be done with the same branch.

**Pull request closed without merging**
