### PR TITLE
Allow using ProfilerPresenter on code blocks

### LINKED ISSUE #12137: "ProfileIt" doesn't work
**Bug description**

Trying to profile my code in Playground using the "Profile" it menu, but it doesn't work.

**To Reproduce**

In playground: `1000 timesRepeat: [10 factorial]` -> Profile it -> nothing.

**Expected behavior**

Profiler is open with the profiling results.

**Screenshots**

n/a

**Version information:**

OS: Windows
Version: 11 x86_64
Pharo Version: 10 (Pharo-10.0.0+build.535.sha.f72dfb7a95cb072d485373b28b33e8c256b9a3f2 (64 Bit))

**Expected development cost**

n/a

**Additional context**

Origin: #12125

### LINKED ISSUE #12840: ProfilerPresenter should be able to launch a profiling on a bloc
I learned that there was a new profiler. Currently it seems that we can just open the UI, write some code and profile it. It would be great if we could do something like in the old UI like:

```st
ProfilerPresenter spyOn: [ my code ]
```

And the opened interface would not have the top section to write code

### PR DESCRIPTION
**Pull request by JanBliznicenko**
Allow using `ProfilerPresenter` on code blocks.

* fixes https://github.com/pharo-project/pharo/issues/12840
* does a step towards https://github.com/pharo-project/pharo/issues/12334
* serves as preparation for implementing `Profile It` command in order to fix https://github.com/pharo-project/pharo/issues/12137

EDIT:
* added St prefixes to all the presenters

### CODE REVIEW

**Comment by Ducasse** [comment]
Jan could you rename the ProfilerPresenter StProfilerPresenter? Tx

**Comment by JanBliznicenko** [comment]
> Jan could you rename the ProfilerPresenter StProfilerPresenter? Tx

Of course. There are also multiple components of it, like ProfilerResultsPresenter, ProfilerTreeTablePresenter and many others, so I renamed them as well.

Just note that the ProfilerPresenter is part of this Pharo repository, not https://github.com/pharo-spec/NewTools, where most of the St stuff is.

**Review by MarcusDenker — APPROVED** [review]

**Comment by hernanmd** [comment]
@MarcusDenker should we move the profiler presenter to NewTools?

**Comment by MarcusDenker** [comment]
Yes, I think that would make sense

**Comment by JanBliznicenko** [comment]
Ok, I have created issue for that (https://github.com/pharo-project/pharo/issues/15795) and will do it.

**Comment by hernanmd** [comment]
> Ok, I have created issue for that (#15795) and will do it.

You might want to look at https://github.com/pharo-project/pharo/pull/15792 and https://github.com/pharo-spec/NewTools/pull/646 because I did started something, not much anyway.

**Comment by JanBliznicenko** [comment]
> > Ok, I have created issue for that (#15795) and will do it.
> 
> You might want to look at #15792 and [pharo-spec/NewTools#646](https://github.com/pharo-spec/NewTools/pull/646) because I did started something, not much anyway.

Thank you, but I, unfortunately, did not notice your PR in time and did the same thing anyway (along with removing the actual package and removing the baseline from `BaselineOfIDE`).

So, I have proposed 3 PRs:
* https://github.com/pharo-spec/Spec/pull/1491 that removes Profile it command
* https://github.com/pharo-project/pharo/pull/15797 that removes ProfilerUI from Pharo repository
* https://github.com/pharo-spec/NewTools/pull/648 that adds (NewTools-)ProfilerUI to NewTools

The order of accepting all is:

1. Accept https://github.com/pharo-spec/Spec/pull/1491
1. Accept https://github.com/pharo-project/pharo/pull/15797
1. Wait for new pharo image build to be done
1. Re-run CI of https://github.com/pharo-spec/NewTools/pull/648
1. Accept https://github.com/pharo-spec/NewTools/pull/648 (if CI is green)

**Comment by hernanmd** [comment]
Thanks Jan. I will close my PR's then so we don't generate confusion.

**Pull request merged**
