### PR TITLE
Added hooks to locally redefine the formatter

### PR DESCRIPTION
**Pull request by guillep**
Added hooks to locally redefine the formatter in a class and a package manifest.
The formatter is looked up from the class up to the formatter.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Bootrap problem:

```
SystemNotification: [Hermes] Installing CodeImportCommandLineHandlers.hermes
SystemNotification: [Hermes] Remaining Undeclared variables in the system: #(#FileLocator #FileAttributeNotSupported #StartupPreferencesLoader #FileSystem)
+ /builds/workspace/est_and_branch_Pipeline_PR-11318/64/bootstrap-downloads/vmtarget/pharo --headless Pharo10.0-PR-compiler-64bit-697a0a9.image --no-default-preferences eval --save 'OpalCompiler register. CompilationContext initialize. OCASTTranslator initialize.'
Instance of RPackage did not understand #packageManifest
RPackage(Object)>>doesNotUnderstand: #packageManifest
RBMethodNode class(ClassDescription)>>formatter
RBMethodNode(RBProgramNode)>>formattedCodeIn:
RBMethodNode(RBProgramNode)>>formattedCode
RBSequenceNode(RBProgramNode)>>asDoit
OpalCompiler>>transformDoit
OpalCompiler>>parseDoIt
OpalCompiler>>compileDoit
```

**Comment by MarcusDenker** [comment]
This shows, of course,  that our implementation of DoIts that needs transformations is not a good one.

**Comment by PalumboN** [comment]
I don't understand why it throws `MNU`. Because it's an extension method?

**Comment by guillep** [comment]
Yes, and it's not being installed at the time the system wants to format some code.

**Comment by Ducasse** [comment]
Now the question is why formatting the code during the bootstrap. 
This is why I got endless loops on error because block code was formatted.

**Comment by guillep** [comment]
> Now the question is why formatting the code during the bootstrap.

:(

> This is why I got endless loops on error because block code was formatted.

Yes

**Comment by MarcusDenker** [comment]
Good news: the need for transforming temp access in DoItIn: is now gone.

We now just do two things: add the "DoIt" / "DoitIn:" selector and transforming the last statement into a return.

I think we can do both without the need to edit and print the AST and then we do not need the Pretty Printer anymore for DoiT.

**Comment by guillep** [comment]
Thanks, I'll take a look at it during the sprint!

**Comment by Ducasse** [comment]
This is cool!

**Comment by MarcusDenker** [comment]
The method to look at is RBProgramNode>>#asDoit.  We need to somehow not format the code here, with the additional problem that we do transform the AST (#transformLastToReturn).

Long term I want to explore if we can compile a block closure here instead of a method (which returns the last statement).
But I have not checked how much change that would need.

```
asDoit
	"The VM can only evaluate methods. wrap this ast in a doit MethodNode"
	| methodNode |
	
	methodNode := RBMethodNode 
		selector: #DoIt
		body: self asSequenceNode transformLastToReturn.
	methodNode source: methodNode formattedCode.
	^methodNode
```

**Comment by MarcusDenker** [comment]
Hmmm... +12,936 −2,921, Files changed 437

**Comment by guillep** [comment]
Github has just gone crazy because I did the merge the other way around...

**Comment by guillep** [comment]
CI seems ok
imagen

Failing test seems unrelated

```
unix-64 / Tests-unix-64 / testLabelsTopPosition – Unix64.Roassal3.Global.Tests.DSM.RSDSMTest5s
Error
Assertion failed
Salida
TestFailure
Assertion failed
RSDSMTest(TestAsserter)>>assert:description:resumable:
RSDSMTest(TestAsserter)>>assert:description:
RSDSMTest(Object)>>assert:
[ :box : label | 
		| x x1 x2 |
		x := label encompassingRectangle bottomRight x.
		x1 := box encompassingRectangle topLeft x.
		x2 := box encompassingRectangle topRight x.
		self assert: (x between: x1 and: x2)
		 ] in RSDSMTest>>testLabelsTopPosition
Array(SequenceableCollection)>>with:do:
RSDSMTest>>testLabelsTopPosition
```

**Comment by dionisiydk** [comment]
We have remove reformatting completely from DoIts:

simpleDoIt

Notice no #DoIt header at all. It's of course questionable change. But it is what user really selects and execute.
I will push PR with this proposal for discussion.

**Pull request merged**
