### PR TITLE
21959-Package-Slot-Traits-is-empty-and-can-be-removed

### PR DESCRIPTION
**Pull request by samakhov**
Remove Slot-Traits from BaselineOfTraits

### CODE REVIEW

**Review by MarcusDenker — APPROVED** [review]
Good!

**Comment by MarcusDenker** [comment]
Some problem:

#Display #Bitmap #RGMethodDefinition)'
'[Hermes] Reading OpalCompiler-Traits.hermes'
'[Hermes] Installing OpalCompiler-Traits.hermes'
'[Hermes] Remaining Undeclared variables in the system: #(#RGCommentDefinition #ChangeRecord #StartupPreferencesLoader #PragmaCollector #ChangeSet #Display #Bitmap #RGMethodDefinition)'
'[Hermes] Reading Slot-Traits.hermes'
FileDoesNotExistException: 'Slot-Traits.hermes'
File>>openForWrite:
File>>openForRead
File>>readStream
HermesCommandLineHandler>>processFile:

**Comment by pavel-krivanek** [comment]
it needs to be removed from bootstrap/scripts/4-build.sh too

**Comment by MarcusDenker** [comment]
errors not related

**Pull request merged**
