### PR TITLE
Small cleanups - class side initialize and other in Monticello

### LINKED ISSUE #10017: Small cleanups - class side initialize and other in Monticello
Similar to #9882 we want to clean Monticello (classes starting with MC)

### PR DESCRIPTION
**Pull request by astares**
Fix #10017

### CODE REVIEW

**Comment by astares** [comment]
Chicken and egg problem - remaining tests need to fixed in Tonel - but this is managed externally

**Comment by Ducasse** [comment]
This breaks tonel tests (they are probably too brittle).

**Comment by astares** [comment]
@Ducasse no, they are not too brittle - the problem is that I would have to 
 - have the changes of this PR
 - adopt the tonel tests at the same time 
 but unfortunately Tonel is an external package.
 
So it can not be done **with a single PR** and therefore the PR is impossible to get green.

**Comment by Ducasse** [comment]
I think that we should revisit tonel tests not to be dependent on MC package protocol.
(at least this is what I understand). 
Because once this is done we will not have this dependency anymore.

**Comment by astares** [comment]
Tonel uses the mock classes defined in MC packages, which I guess is fine as they belong to standard image. 
The issue just arises as we have to adopt on two places at the same time.

Or maybe there is a way:
 - to change Tonel and provide a new release first
 - then make a PR with the changes on MC mock classes side + the new version of Tonel in one go

**Pull request closed without merging**
