### PR TITLE
Calypso should use SpNotebookMorph instead TabManager

### PR DESCRIPTION
**Pull request by estebanlm**
Since tab manager handles tabs by forking process and that's suboptimal.
SpNotebookMorph will load tabs lazily.

### CODE REVIEW

**Comment by Ducasse** [comment]
why we should not integrate :)?

**Comment by dionisiydk** [comment]
Hi Esteban.

I am curious, what is the goal? To remove old TabManagerMorph?
I am asking because I would expect here the full Spec2 reimplementation of tab component. So why this intermediate step? (especially that you are now mixing morph and spec in the implementation)

**Comment by estebanlm** [comment]
> why we should not integrate :)?

because is not finished :)

> I am curious, what is the goal? To remove old TabManagerMorph?

Yes, because old `TabManagerMorph` spawns a process for each tab and this is affecting systems with heavy charge. 
And yes, this is an intermediate solution since we are going to replace the UI with a Spec2 UI... but that, as you know, is a lot of work and we need a solution for big images now :)
(This, of course, is not "the solution", is just one of the many details we want to tweak to enhance the Pharo experience).

**Comment by estebanlm** [comment]
it can be integrated now :)

**Comment by estebanlm** [comment]
bump

**Comment by Ducasse** [comment]
Esteban why do we name Morph with Sp?

**Comment by estebanlm** [comment]
because this is a Morph made to be used with Spec2, hence the name (yes, I know Calypso does not uses Spec2, but I used it in a couple of cases).

**Comment by estebanlm** [comment]
And yes... it could be extracted/generalised...but is not made yet :)

**Pull request merged**
