### PR TITLE
Small cleanups - class side initialize and other

### LINKED ISSUE #9882: Small cleanups - class side initialize and other
- class side #initialize methods should be in 'class initialization'  category (fixes lint issue)
- methods called from class side #initialize method should be in 'private - initialization' category
- formatting
- removal of dots
- remove unnecessary dots

Side note for first point:
This should reduce the number of methods lint is lamenting about. One can find them using:
```Smalltalk
(SystemNavigation default allImplementorsOf: #initialize) select: [:each |	
	each methodClass isMeta and: [each category ~= #'class initialization'] ]
```

### PR DESCRIPTION
**Pull request by astares**
fix #9882

### CODE REVIEW

**Comment by astares** [comment]
Reviewers? Anyone?

**Comment by astares** [comment]
CI problem unrelated. Green on two of three platforms

**Comment by astares** [comment]
19 days and not merged? What's wrong?

**Review by MarcusDenker — APPROVED** [review]

**Review by guillep — APPROVED** [review]
Good!

**Pull request merged**
