### PR TITLE
[WIP]3256-Remove-Halt-from-Kernel

### LINKED ISSUE #3256: Remove Halt from Kernel
I propose as a first step to move Halt from Kernel and put it in Debugging-Core.

### PR DESCRIPTION
**Pull request by jecisc**
Extract Halt in Debugging-Core to reduce Kernel size.

Fixes #3256

### CODE REVIEW

**Comment by Ducasse** [comment]
I do not really understand because none of the jobs worked but the system reports 96 broken tests.

**Comment by Ducasse** [comment]
Trying to relaunch the builds

**Comment by jecisc** [comment]
Errors seem related. I'll need to check

**Comment by jecisc** [comment]
I'll close this one and start a new PR. Here it removes Halt from Kernel but not from the bootstrap. We should remove Halt from the bootstrap since Halt relies on the compiler that is not in the image at the bootstrap level.

**Pull request closed without merging**
