### PR TITLE
Revert "Remake PR 5412"

### PR DESCRIPTION
**Pull request by guillep**
Reverts pharo-project/pharo#5902

Follow discussion in #5903

### CODE REVIEW

**Comment by guillep** [comment]
Let's let the build run, integrate it after.

**Comment by Ducasse** [comment]
This still poses the questions about the design of a language that would avoid all such globals plague. This is why newspeak had this environment everywhere.

**Comment by guillep** [comment]
> This still poses the questions about the design of a language that would avoid all such globals plague. This is why newspeak had this environment everywhere.

yes.

**Review by guillep — COMMENTED** [review]
Failures not related: fleaky tests

image

**Pull request merged**
