### PR TITLE
21388-Zinc-tests-using-remote-servers-should-have-bigger-timeout

### PR DESCRIPTION
**Pull request by oliveiraallex**
Introduce requiresNetworkConnection message wich set timeout 10 seconds

### CODE REVIEW

**Comment by svenvc** [comment]
Have you seen how ZnHTTPSTests deals with this ? See #testTransfers 

I don't like add this confusing message #requiresNetworkConnection each time

Also, #timeLimit: does not work in older Pharo version which Zinc needs to support

There has to be a better solution.

**Comment by dionisiydk** [comment]
I also not understand this change. Because it sets timeout to 10 seconds which is already  current default value for system in general.
But there are test classes which override it with same value. Idea was to make default value mush smaller and specify bigger values where it is required.
For example look at ZnHTTPSTests class>>#defaultTimeLimit. It is the way how to set up time out for all tests in class.

**Comment by pavel-krivanek** [comment]
Hmm, at least we should have a way how to mark such tests because this way we will have a way how to skip them globally for platforms without a network connection (like on SqueakJS, some IoT).

I think that we should remove the network access from the encoder tests because it should not be there (because of bootstrap) and then probably create a superclass for all Zinc tests that will implement such method. What do you think?

**Comment by dionisiydk** [comment]
About encoder tests:
We should not remove them but move them into separate package like EncodingImport-Tests. It is important and useful functionality.

**Comment by dionisiydk** [comment]
About platforms:
Why we need to mark separate tests? If network is not supported we should skip network  packages completely. And better would be to not load network at all.
Because if we load tests and run them on squeakJS they are supposed to fail. It shows that network does not work there which is really good indication.

I think same problem would be with files. Does files work on SqueakJS?

**Comment by pavel-krivanek** [comment]
Files work on SqueakJS. You are right with the failing tests.

**Comment by estebanlm** [comment]
postponed (we need a better/compatible solution)

**Pull request closed without merging**
