### PR TITLE
Update-Spec2-and-Commander-2

### PR DESCRIPTION
**Pull request by jecisc**
Update Spec 2 and Commander 2

### CODE REVIEW

**Comment by jecisc** [comment]
# Spec 2 integration of the 13 of September 2019

## Features

* Add padding management of `SpBoxLayout` for Morphic
* Add demo on Box Layout ([978220b](https://github.com/pharo-spec/Spec/commit/978220b249d8ab74f55d5b2ad1b7855efca13097))
* Add package comments ([20ffe7a](https://github.com/pharo-spec/Spec/commit/20ffe7a65b2743fa805f101c35579b77d33a1119))
* Add contextMenu to `Athens` presenters ([78aefa5](https://github.com/pharo-spec/Spec/commit/78aefa5a183d81aac01927960cb92fb4007c5f9e))
* Allow to add an image in the layout without declaring an image presenter ([748bc59](https://github.com/pharo-spec/Spec/commit/748bc59545ff1f96581779033ef9f9a7cb7209f8))
* Add InputPort to `SpPresenterWithModel` ([5f7d07c](https://github.com/pharo-spec/Spec/commit/5f7d07c450c75ffcdbffb8b32c4a0a7cdf84b762))
* Improve demos ([d2e1bf1](https://github.com/pharo-spec/Spec/commit/d2e1bf1bf63cdfa67edb4084b250ee58b3e71701))
* Add possiblity to pass action to link presenter ([3903717](https://github.com/pharo-spec/Spec/commit/390371739889b9a30ca2e33882a2a53def258415))
* Add component list presenter ([cb26690](https://github.com/pharo-spec/Spec/commit/cb26690bbf2c49fbb2d8c79691bfc42e3b93079c))
* Add possibility to defer UI via Spec ([da86831](https://github.com/pharo-spec/Spec/commit/da868315c43ae4e500b3cfcc6bade5a410c6a584))
* Introduce new API: `initializePresenters` and `connectPresenters` instead of `initializeWidgets` and `initializePresenter` ([6c7ebc1](https://github.com/pharo-spec/Spec/commit/6c7ebc161d3e4eb12848403a671ea191175da552))
* Use toolbar and not toolBar ([f2f807f](https://github.com/pharo-spec/Spec/commit/f2f807fb4c3c324bfd338e69f2adbdacfb9dfceb))
* Create builder for SpActionBarPresenter ([c5f1e59](https://github.com/pharo-spec/Spec/commit/c5f1e59434563c904cc84805757d3b1ab97da1bf))
* TextPresenter Add a placeHolder ([7b7d4b5](https://github.com/pharo-spec/Spec/commit/7b7d4b53176e138f0a8cc60b63c0a67fe39a44d3))
* Add the method clearContent in the class SpAbstractTextPresenter ([16a842d](https://github.com/pharo-spec/Spec/commit/16a842d41eb216acb73f7e64ceb5a1f49ceac468))
* feature/improvementsForIceberg ([246c1a7](https://github.com/pharo-spec/Spec/commit/246c1a7f24adaf711653d082ae7ef5804cf262bb))

### Commander 2 integration

* Change dependency to Commander2 so it uses v110 ([5ca15b3](https://github.com/pharo-spec/Spec/commit/5ca15b3332d96c54d28138bf84361de3c8045534))
* Update commander2 version ([4ac485a](https://github.com/pharo-spec/Spec/commit/4ac485a97f514b68b24a73eb367fe712043dc9af))
* Change dependency to Commander2 for v120 ([15945ac](https://github.com/pharo-spec/Spec/commit/15945ac2d858bc44c3d7f9a10abe2dccbc555f3a))
* Migrate Spec to use Commander2 v200 ([c4c5350](https://github.com/pharo-spec/Spec/commit/c4c5350e1574c6a7a1a51cb60d5ccefb03103c08))
* Implement method to convert spec command as ButtonPresenter ([dab0312](https://github.com/pharo-spec/Spec/commit/dab03121fe9fa6c064b4fd837157c88e1e8505bd))
* Allows one to change the default context set on commands when their context is nil ([152af5e](https://github.com/pharo-spec/Spec/commit/152af5e2fd1cce07b45cbcc89f6fe8b4b27124f8))
* Commander2 should provide easier way to use command group on list tree etc ([d80a965](https://github.com/pharo-spec/Spec/commit/d80a9658675687a343b91f54d1cb3d1449177269))
* Commander2 layer should set the presenter as context of commands when not done ([d0f2889](https://github.com/pharo-spec/Spec/commit/d0f288989f6b551556b85f5c91a65565d04f665d))

## Bugfixes

* Replace `Smalltalk` references ([c1cc561](https://github.com/pharo-spec/Spec/commit/c1cc56152dd753e08757c2961e99aa9e7bb10c43))
* Fix grid layout tests ([85719bc](https://github.com/pharo-spec/Spec/commit/85719bcd016f58273fbbad778293762c15c4b1e3))
* SpAbstractPresenter should be abstract ([de681a0](https://github.com/pharo-spec/Spec/commit/de681a0a95d4aa61c4edec8e7132b48602483273))
* Migrate more layouts to executable layouts ([cee71ae](https://github.com/pharo-spec/Spec/commit/cee71ae1742b8237c6f27102bdc6ec39800db181))
* Use theme instead of hardcoded color in Modal adapter ([be583d8](https://github.com/pharo-spec/Spec/commit/be583d81f760971898560ed50ea9a1571432f2e2))
* TextPresenter placeholder does not work in Pharo 7 ([6bbdc7b](https://github.com/pharo-spec/Spec/commit/6bbdc7bb88c7116619a78240f1ac1e7111b5850c))
* Instance of TreeTablePresenter did not understand activatesOnDoubleClick ([9cda46c](https://github.com/pharo-spec/Spec/commit/9cda46c5c878d83b433f65a06cab945edfc1e27d))
* Fixing SpCodePresenter in pharo8 ([fc5b7e8](https://github.com/pharo-spec/Spec/commit/fc5b7e8e2c6aa7a5665a056726b39644955faaae))
* Some table columns are editable ([c630a0e](https://github.com/pharo-spec/Spec/commit/c630a0ea7222228381b18083366894c1872af2aa))
* Fixing Baseline ([3f3ac6d](https://github.com/pharo-spec/Spec/commit/3f3ac6dcf9d7402e86a6c443fa76fe60ed2e7b85))

## Cleanings 

* Migrate `initializeWidgets` and `initializePresenter` to new API ([dd74217](https://github.com/pharo-spec/Spec/commit/dd74217cf643a4a7d80cae17c2bf9ee73f796746))
* Clean package structure ([a0706ba](https://github.com/pharo-spec/Spec/commit/a0706ba159feb748f324a8790f070639cade396f))
* Remove dependency between Spec2 Commands and Commander ([56ae6d4](https://github.com/pharo-spec/Spec/commit/56ae6d414a5d9bbe1f2612a06a13c4f9c36a0380))
* Commander2 v2 migration ([0d029c0](https://github.com/pharo-spec/Spec/commit/0d029c077721a0f7a966abc2be361b4c322eea3c))
* Remove all commented pragmas ([ed6e844](https://github.com/pharo-spec/Spec/commit/ed6e844c7bbaf1f7610c061a2f05a9ff5485c011))
* cleanup ([05839d7](https://github.com/pharo-spec/Spec/commit/05839d7862554cfb8f0198868dc5e55e99836407))
* Deprecate asSpAdapter ([cb5f47c](https://github.com/pharo-spec/Spec/commit/cb5f47ca0a1aca9c49c2e86c8ee1ab842ff23f37))
* Move spec related methods on class side of CmCommand and CmCommandGroup to spec integration package ([f95eca0](https://github.com/pharo-spec/Spec/commit/f95eca0e993a9958ce8db6197bb36f4b275d2365))
* Remove ComposablePresenter references ([ef8c984](https://github.com/pharo-spec/Spec/commit/ef8c984ecb733783c4bd5f1306420d9a9a684440))
* Unnecessary initialize method in SpMorphPresenter ([4b6828b](https://github.com/pharo-spec/Spec/commit/4b6828b0e3579bda3db73d8cdc698b430b4d457e))
* SpExecutableLayoutresolvePresentermodelbindings should be SpExecutableLayoutresolvePresenterpresenterbindings ([caa37db](https://github.com/pharo-spec/Spec/commit/caa37dba4df51134a0add0ef372cb29a12a78c80))
* Fix calls to canBeRun and replace them with canBeExecuted ([822db0c](https://github.com/pharo-spec/Spec/commit/822db0c09225eeed57d4b620e89460de6a03e2e6))
* PolyWidget SpChooseMethod improvement ([fe964f9](https://github.com/pharo-spec/Spec/commit/fe964f9027f2d84fe79cee6701e6e2148bde7405))
* Comment of SpPresenter mentions ComposablePresenter ([d46e348](https://github.com/pharo-spec/Spec/commit/d46e348a0ee69ac6011064f42944cb18d2edc463))
* Rename SpTestingComposerWithModel into SpTestingPresenterWithModel ([092e6c4](https://github.com/pharo-spec/Spec/commit/092e6c415cb118f53973ed59011f320a97c7c3a1))

## Infrastructure

* Harvest pharo changes ([ef8835a](https://github.com/pharo-spec/Spec/commit/ef8835ad5e200b041391e157ec71324ff90edd31))
* Harvest Pharo changes ([250df0c](https://github.com/pharo-spec/Spec/commit/250df0cfed71bd9e7815085cc0f013937a37b19b))
* Making tests to use adapters ([715050c](https://github.com/pharo-spec/Spec/commit/715050c5091217ce6303b1ee8bea8374fd21d17f))
* Harvest Pharo changes ([6d4cc44](https://github.com/pharo-spec/Spec/commit/6d4cc449cbfeea04a11151a50e43b458b95c9404))
* Harvest Pharo changes ([ec4e30e](https://github.com/pharo-spec/Spec/commit/ec4e30e900c8e75e3ce72072ab1919044031b631))

# Commander 2 integration of the 13 of September 2019

## Features 

* Add `#register:after:` and `#register:before:`. ([ad5041c](https://github.com/pharo-spec/Commander2/commit/ad5041cccdd34a7b021ca505323ce6d9a5912480))
* Implemented part of the missing API and implemented corresponding tests. ([5c91fac](https://github.com/pharo-spec/Commander2/commit/5c91facd019e952b993750725bd187f2346db6d9))

## Bug fixes

* Added missing deprecation methods to make transition from v1 to v2 smoother. ([3fef319](https://github.com/pharo-spec/Commander2/commit/3fef31976b6daa4aeef0dcab9f3fcde6a860a484))
* Changed string returned by #defaultDescription to be 'Not described command.' ([71ad574](https://github.com/pharo-spec/Commander2/commit/71ad574eb3af5a88ba2aca47b45f8e7caffc0192))


## Cleanings 

* Preparing for major release, removing deprecated methods we do not want in next major version: - #canBeRun - #canBeRunBlock - #canBeRunBlock: - #defaultCommandName - #runWith: ([3dbd6b1](https://github.com/pharo-spec/Commander2/commit/3dbd6b184d76d1cdd94683b7dc611d5aa531103e))
* Updated baseline to be more flexible. - Do not provide migrator in default group. - Provide core,test and migrator groups. ([7a7491b](https://github.com/pharo-spec/Commander2/commit/7a7491b8ed4a6925d836922e0b84d683caa4799e))
* Enhanced comment. ([8379fb3](https://github.com/pharo-spec/Commander2/commit/8379fb34a40826e8b3681bf2ede30696a656b9f8))
* Did migration with the following renamings (order is important): #name -> #dynamicName. #description -> #dynamicDescription. #basicName -> #name. #basicDescription -> #description. ([1a8f4e8](https://github.com/pharo-spec/Commander2/commit/1a8f4e8a1b7da5bdcc44c2a1d952557a71b6f351))
* wrap environment into RBNamespace. ([723cddd](https://github.com/pharo-spec/Commander2/commit/723cdddb42780305a6366660d0fc40ad8bec6623))
* Put #runWith: in deprecations package. ([cc9025d](https://github.com/pharo-spec/Commander2/commit/cc9025d89b168ba2159b4db610ff00c2dff707f8))
* Removed #runWith: ([c78dd09](https://github.com/pharo-spec/Commander2/commit/c78dd0977727ad2dc103c36ac326d18520f247e4))
* Renamed #defaultCommandName as #defaultName. Used deprecation. ([c1bad44](https://github.com/pharo-spec/Commander2/commit/c1bad4407a55e654b0183005c885289177dc0b04))
* Renamed #canBeRunBlock as #canBeExecutedBlock via a deprecation. ([5a87a11](https://github.com/pharo-spec/Commander2/commit/5a87a1185e071990dd2c684444e7931faa25b67d))
* Moved spec related methods in class-side of CmCommandGroup to spec package. ([4ae2f84](https://github.com/pharo-spec/Commander2/commit/4ae2f8478b2b59d9051bdb1a65ca2b4a0d8eee18))
* Moved spec-specific methods on class side of CmCommand to Spec integration package. ([11d7997](https://github.com/pharo-spec/Commander2/commit/11d799799ec055d5113ccf589f42cf58822ab322))
* Renamed #canBeRun as #canBeExecuted to be more consistent. Created a deprecation to ease migration of users. ([152e6a7](https://github.com/pharo-spec/Commander2/commit/152e6a72261a8f1f6fb4e9ad579a199b73dba036))
* Reclassified all #canBeRun methods in 'testing' protocol. ([813cda2](https://github.com/pharo-spec/Commander2/commit/813cda255f8a0cc6df592bbe22d5f26850fbcb31))
* Reclassified #execute methods in 'executing' protocol. Brings consistence and solves issue #9 ([19c1ee0](https://github.com/pharo-spec/Commander2/commit/19c1ee0db83830abe3ee68ea0a11581765e90df6))
* Renaming of CmCommandGroupTest to CmCommandsGroupTest. ([5f20942](https://github.com/pharo-spec/Commander2/commit/5f20942c03cbb529b285883d9d1c9db2c870c942))
* Renamed test class to match class under test. ([8ab2c3b](https://github.com/pharo-spec/Commander2/commit/8ab2c3bb15b664b2cfa46ade33d1e4d656f40741))

**Comment by Ducasse** [comment]
osx-32 / Tests-osx-32 / testNoUnusedTemporaryVariablesLeft – MacOSX32.ReleaseTests.CleanCode.NoUnusedTemporaryVariablesLeftTest
<1s
osx-32 / Tests-osx-32 / testUndeclared – MacOSX32.ReleaseTests.Release.ReleaseTest
<1s
osx-32 / Tests-osx-32 / testAndMakeSureSuperTearDownIsCalledAsLastMessageInTearDownMethodsOfTestCases – MacOSX32.ReleaseTests.Tests.ProperlyImplementedSUnitClassesTest
<1s
osx-32 / Tests-osx-32 / testExternalBasicToolsDependencies – MacOSX32.System.DependenciesTests.SystemDependenciesTest
<1s
osx-32 / Tests-osx-32 / testExternalIDEDependencies – MacOSX32.System.DependenciesTests.SystemDependenciesTest
<1s
osx-32 / Tests-osx-32 / testExternalSpec2Dependencies – MacOSX32.System.DependenciesTests.SystemDependenciesTest
<1s
osx-32 / Tests-osx-32 / testExternalUIDependencies – MacOSX32.System.DependenciesTests.SystemDependenciesTest

**Comment by jecisc** [comment]
Looking at it now.

**Comment by jecisc** [comment]
Tests are now passing.

**Comment by Ducasse** [comment]
Massive

**Comment by guillep** [comment]
Hi Cyril, can you put in the issue description / commit comment what tag corresponds to this version? so we can track it back :D

**Pull request merged**
