### PR TITLE
Fix-DeprecationRewrites 

### PR DESCRIPTION
**Pull request by MarcusDenker**
This PR fixes some of the deprecation rewrites you see when running all tests.

(this should be all in the image, others are in external packages)

### CODE REVIEW

**Comment by MarcusDenker** [comment]
odd crash on windows, but linux and mac are green

**Comment by guillep** [comment]
It's not a crash. It's an infinite recursion that made the CI time out. Why it happened in windows only, I don't know.
But it seems a `halt` in a `printOn:`

```
[...]
Halt
FullBlockClosure(Object)>>halt
FullBlockClosure(BlockClosure)>>printOn:
NullStream(Stream)>>print:
Context>>printOn:
Context>>printOn:
Context>>printOn:
NullStream(Stream)>>print:
Context>>errorReportOn:
Error printing the compiledBlock in SmalltalkImage>>logError:inContext: in Block: Cannot print the closure
Error printing the compiledBlock in SmalltalkImage>>logDuring: in Block: Cannot print the closure
FullBlockClosure(BlockClosure)>>ensure:
SmalltalkImage>>logDuring:
SmalltalkImage>>logError:inContext:
Error printing the compiledBlock in NonInteractiveUIManager(CommandLineUIManager)>>quitFrom:withMessage: in Block: Cannot print the closure
FullBlockClosure(BlockClosure)>>ensure:
NonInteractiveUIManager(CommandLineUIManager)>>quitFrom:withMessage:
NonInteractiveUIManager(CommandLineUIManager)>>unhandledErrorDefaultAction:
Halt(Exception)>>unhandledErrorAction
Halt(UnhandledException)>>defaultAction
UndefinedObject>>handleSignal:
Context>>handleSignal:
Context>>handleSignal:
Context>>handleSignal:
Context>>handleSignal:
Context>>handleSignal:
Context>>handleSignal:
Context>>handleSignal:
Halt(Exception)>>signal
Halt class(Exception class)>>signal
Halt class>>now
Halt
FullBlockClosure(Object)>>halt
FullBlockClosure(BlockClosure)>>printOn:
NullStream(Stream)>>print:
Context>>printOn:
Context>>printOn:
Context>>printOn:
[...]
```

**Comment by MarcusDenker** [comment]
There are 

StObjectWithPrintHalt>>#printOn:
ObjectWithPrintingRaisingHalt>>#printOn:

And it seems that opening the debugger does a deprecation rewrite for #open, maybe that is related?

**Comment by MarcusDenker** [comment]
I wil restart the CI run

**Comment by MarcusDenker** [comment]
a PR to commit the deprecation transform in the debugger is here: https://github.com/pharo-spec/NewTools/pull/330

**Comment by MarcusDenker** [comment]
Now win is green but linux had some problem (but not the same)

I propose we merge this as it seems to be not related to these changes

**Pull request merged**
