### PR TITLE
Simplify and deprecate ClassDescription>>allProtocolsUpTo:

### PR DESCRIPTION
**Pull request by jecisc**
allProtocolsUpTo: is not used in the image so I propose to deprecate it.  In case an external tool is using it, I updated the method to be simpler so it can probably just be inlined.

### CODE REVIEW

**Comment by jecisc** [comment]
IceGitHubError: API rate limit exceeded for 128.93.193.1. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

**Review by privat — APPROVED** [review]

**Comment by MarcusDenker** [comment]
there is now a merge conflict

**Comment by jecisc** [comment]
Fixed

**Comment by MarcusDenker** [comment]
- [CI] Fail on WIN random: OmSessionStoreTest(OmStoreTest)>>testEntryForAbsentEntry #12126

**Pull request merged**
