### PR TITLE
SourceFileBufferedReadWriteStreamTest-readOnlyLiteral

### PR DESCRIPTION
**Pull request by MarcusDenker**
SourceFileBufferedReadWriteStreamTest should not use literal strings directly when writing (as it changes the literals...)

### CODE REVIEW

**Comment by Ducasse** [comment]
While reading the changes, ie. copying the argument. I wondering if we could not provide a method that will send the copy to the argument and one that does not know. Because we put the logic on the client and I would prefer to have it internalised.

**Comment by MarcusDenker** [comment]
I do not think that there are many use cases for that. We do it here only because we create a WriteStream on a literal.. which you just should not do.

**Comment by Ducasse** [comment]
Oki
So why not changing WriteStream with: '' into WriteStream with: String new.
This way we do not promote a special usage.

**Comment by MarcusDenker** [comment]
empty arrays like objects are an interesting case in general: they can only grow by being copied, in which case the literal is not changed.

The Stream re-uses the underlying string as long as it does not need to grow, it creates a copy as soon as it grows.

(old Smalltalk -80 used become far more for these things (not sure if for arrays, but for Dictionary it did...), as it was a very cheap operation with the object table)

**Pull request merged**
