### PR TITLE
6790-BaselineOfMD-V2

### LINKED ISSUE #6790: BaselineOfMicrodown is not loaded
Microdown packages are in the repo the baselineOfMicrodown but not loaded

### PR DESCRIPTION
**Pull request by Ducasse**
fixes: #6790

### CODE REVIEW

**Comment by Ducasse** [comment]
I do not really understand because I made the Clap part for P8 conditional and all the builds are loading in P8 and P9 in travis. I'm puzzled.

**Comment by Ducasse** [comment]
Thanks Pablo, do you know if I should also  commit the new version (in sync normally with the PR) of the packages in the repo?

**Comment by tesonep** [comment]
Are there changes in the repository of Microdown? If they are maybe it is a good idea to sync them.
I do not understand completely the question. If my change work we need to push it to the microdown repo.

**Comment by Ducasse** [comment]
No there is no changes. I tagged the version I pushed so that I can follow changed.
First I would like to get MD in.

**Comment by Ducasse** [comment]
The conflict is resolved and I should check what is the problem

**Comment by Ducasse** [comment]
I do not get why I lost a class in the process. So the tests are failing because the test context is not set. I going super slowly to understand how I can push in the PR. I thought it would be simple
but I have problem to get your changes and commit in this PR. May be because I'm tired.

**Comment by Ducasse** [comment]
I found a way to pull the PR. 
I'm looking for the PRDocumentSample.
It is in Pillar-Tests-Model and should be moved to core. 
Now if I load from microdown repo I will lose the changes. So I loaded from pharo
I will do it tomorrow. 
Now I have to check because travis works. But tomorrow since I'm dead

**Comment by Ducasse** [comment]
I will merge this one and fix the Pillar packages with the missing classes afetr because I cannot spent 3 hours on this.

**Pull request merged**
