### PR TITLE
12081 another duplicates of itemchooser

### PR DESCRIPTION
**Pull request by n1toxyz**
Fixes issue #12081 as proposed.

### CODE REVIEW

**Comment by n1toxyz** [comment]
I noticed that I don't need a separate Dialog class in Spec as #openDialog already opens a presenter in a dialog window.
Thus we can replace two classes with just a few lines.

**Comment by Ducasse** [comment]
Thanks this is cool. Ideally we should rewrite the Finder to use Spec2.0. But this is good to have one less chooser in the image!

**Comment by Ducasse** [comment]
I will relaunch the build because it is broken on all platforms and this is not related to the change.

**Comment by Ducasse** [comment]
This is cool to see less code :). Tx!

**Pull request merged**
