### PR TITLE
Cleanup newlines and blanks in "Monticello" packages

### LINKED ISSUE #10552: Cleanup newlines and blanks in "Monticello" packages
see #10396 and fix it for all "Monticello" related packages:

```Smalltalk
badCases := SystemNavigation default allMethodsSelect: [ :each | each sourceCode trimRight size ~= each sourceCode size ].

fixInPackage := badCases select: [:each | each package name beginsWith: 'Monticello' ].

fixInPackage do: [:each |
	| refactoring classOrTrait |
	classOrTrait := each traitSource ifNil: [ each methodClass ] ifNotNil: [ each traitSource innerClass ].
	refactoring := RBAddMethodChange compile: each sourceCode trimRight in: classOrTrait for: nil.				 
	refactoring execute	
]
```

### PR DESCRIPTION
**Pull request by astares**
Fix #10552

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Failing tests seem to be related (they fail on all platforms)

unix-64 / Tests-unix-64 / testMethodDefinitionWithBangs – Unix64.Monticello.Tests.IO.MCStWriterTest
unix-64 / Tests-unix-64 / testWriteSnapshot – Unix64.MonticelloTonel.Tests.TonelWriterTest
unix-64 / Tests-unix-64 / testWriteSnapshotWithoutOrganization – Unix64.MonticelloTonel.Tests.TonelWriterTest

**Comment by astares** [comment]
I was able to fix #testWriteSnapshot - additionally also the other two. But they need to be fixed in Tonel using the two changed methods in the attached changeset, not in standard image.

[10533-Tonel.zip](https://github.com/pharo-project/pharo/files/7637248/10533-Tonel.zip) adopting
  - expectedMCMockClassAClassSt
  - expectedMCSnapshotTestExtensionSt
to get the test green.

But here is now a kind of strange interaction between a dependency and internal- vs. external managed package: 
- TonelWriterTest requires MonticelloMocks to test 
- Monticello is in the image but Tonel is managed with releases outside if image and get included at build time

Not really chicken and egg - but close.

To be green we need to adopt Monticello and Tonel at the same time. So the puzzle to solve is how can we merge 
this PR and get an updated Tonel release at the same time???

Maybe 

Option A)
 - by adding the two changed methods from the zipped changeset to Tonel first
 - providing a Tonel release
 - adding the increase of the Tonel version to this PR here.

Option B)
 - we have a Tonel that is not using the mocks from MonticelloMocks package but own ones

Any comments?  @estebanlm @tesonep @guillep 


Side note: I provided a zip because github can not upload *.cs changeset files.

**Comment by astares** [comment]
image
1055

**Comment by astares** [comment]
Will look into another issue on Tonel side. Then maybe a new Tonel version could be tagges for integration and then we can move on here. 

For the moment keep it on "Needs more work" and assign it to me. Thanks!

**Comment by astares** [comment]
Can we retrigger the CI?

**Comment by guillep** [comment]
> Can we retrigger the CI?

done

**Comment by MarcusDenker** [comment]
Now this has conflicts... maybe it is better to close it for now?

**Comment by MarcusDenker** [comment]
As this is not directly actionable, I linked the PR to the issue tracker entry. This way we can close it here.

**Pull request closed without merging**
