### PR TITLE
Synch zinc zodiac

### PR DESCRIPTION
**Pull request by jecisc**
In Zinc the package Zinc-Zodiac is called Zinc-Zodiac-Tests

This PR aligns this

### CODE REVIEW

**Comment by svenvc** [comment]
Yes, that is it. Thank you

**Comment by MarcusDenker** [comment]
Failing tests:

- ZnHTTPSTests>>testGmailEncrypted fails with to many redirects, this was #10290
- NoUnusedVariablesLeftTest>>testNoUnusedTemporaryVariablesLeft for ZnHTTPSTests>>#testGetPharoVersion
- ReleaseTest>>testTestCasesEndsWithTestOrTestCase
- ProperlyImplementedSUnitClassesTest>>testTestClassesShouldBeSingular

**Comment by jecisc** [comment]
A few comments:
- The test still fails because of too many redirection: I propose to increase the limit in the test
- The class was renamed in Pharo to not have the "s" because there is a rule that test case needs to ed with "TestCase" or "Test" in Pharo to be coherent
- The test about pharo version was commented in zinc. I propose to just remove it

I'll update this PR and do one in Zinc too

**Comment by jecisc** [comment]
The little sister of this PR: https://github.com/svenvc/zinc/pull/112

**Review by demarey — COMMENTED** [review]
Are you sure we do not need the tests with Gitlab and pharo version?
We could add them in another class not packaged in Zodiac if needed.
I would ask to Pharo devs before removing them.

**Comment by jecisc** [comment]
This fix a failing test of the ci. Maybe we can merge it and create a new PR for those two tests?

**Comment by jecisc** [comment]
https://github.com/pharo-project/pharo/issues/12939

**Pull request merged**
