### PR TITLE
(Re)Moved ProfilerUI package

### PR DESCRIPTION
**Pull request by JanBliznicenko**
Removed ProfilerUI package in order to move it to the NewTools repository. Part of efforts towards resolving issue https://github.com/pharo-project/pharo/issues/15795, alternative to https://github.com/pharo-project/pharo/pull/15792.

### CODE REVIEW

**Comment by jecisc** [comment]
Hi @JanBliznicenko 

Can you remind me the order of the operations to do for this change? Should we merge this one?

**Comment by JanBliznicenko** [comment]
> Hi @JanBliznicenko
> 
> Can you remind me the order of the operations to do for this change? Should we merge this one?

Yes, this one is the one to merge now.

1. Accept https://github.com/pharo-spec/Spec/pull/1491
1. Accept https://github.com/pharo-project/pharo/pull/15797
1. Wait for new pharo image build to be done
1. Re-run CI of https://github.com/pharo-spec/NewTools/pull/648
1. Accept https://github.com/pharo-spec/NewTools/pull/648 (if CI is green)

**Comment by guillep** [comment]
Hi @JanBliznicenko the latest images do not yet have the profiler back.
Is there something missing here? I urgently need the profiler :)

**Comment by guillep** [comment]
Ok, I saw that it got lost seemingly in a merge. I've added it back here: https://github.com/pharo-spec/NewTools/pull/680

**Pull request merged**
