### PR TITLE
21216-Trait-isBehaviour-should-be-true

### PR DESCRIPTION
**Pull request by dionisiydk**
TraitBehavior with isBehavior returning true.

https://pharo.fogbugz.com/f/cases/21216/Trait-isBehaviour-should-be-true

### CODE REVIEW

**Comment by dionisiydk** [comment]
Single test failed TraitFileOutTest>>testFileOutCategory

**Comment by Ducasse** [comment]
This looks ok for me. Now I cannot see the details :(

**Comment by dionisiydk** [comment]
The problem described in fog bugs

**Comment by Ducasse** [comment]
If you click on Details I get that the tests are not run.

**Comment by Ducasse** [comment]
How can we rerun the tests?

**Comment by dionisiydk** [comment]
Stef, But did you check comments in fog bugs? 
I am not sure how good is this change. Logically #isBehaviour should be true for traits. But it affects users (which I fixed with last commits)

**Comment by dionisiydk** [comment]
With new traits it is now true by default. One method from my fix is missing I will create another pull request for this

**Pull request closed without merging**
