### PR TITLE
Hook for custom syntaxhighlight

### PR DESCRIPTION
**Pull request by estebanlm**
it requires https://github.com/pharo-project/pharo/pull/12429 to be integrated first!

### CODE REVIEW

**Comment by estebanlm** [comment]
damn it, I have a case of "works on my machine" :(

**Comment by jecisc** [comment]
@estebanlm It fails on mine if you want to take a look at some point

**Comment by jecisc** [comment]
And after loading the PR I don’t have coloration anymore

**Comment by estebanlm** [comment]
don't worry, I will fix it from the PR artifact :)

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
