### PR TITLE
Stepping mecanisme should be used by model and morph. But it is curre…

### LINKED ISSUE #2241: Remove step related methods from Object
Object implements some methods related to the step mechanism of Morph. Those methods should be removed/push down to Morph. 

Methods:
- stepAt:in:
- stepIn:
- stepTime
- stepTimeIn:
- wantsSteps
- wantsStepsIn:

### PR DESCRIPTION
**Pull request by jecisc**
…ntly also present on Object.

This PR depercates it. 

Fixes #2241

### CODE REVIEW

**Comment by MarcusDenker** [comment]
- [CI] Fail on WIN random: OmSessionStoreTest(OmStoreTest)>>testEntryForAbsentEntry #12126

**Comment by MarcusDenker** [comment]
I now get a lot of calls to the deprecated method during use

**Comment by jecisc** [comment]
Do you have a way to reproduce it so that I can check what needs to be updated?

**Comment by StephanEggermont** [comment]
Create method in the debugger is affected

**Comment by jecisc** [comment]
I’ll take a look as soon as I’ll have time

**Pull request merged**
