### PR TITLE
21763-TraitedMetaclass-should-empty-the-localMethods-and-baseLocalMethods-when-becoming-obsolete

### PR DESCRIPTION
**Pull request by pavel-krivanek**
https://pharo.fogbugz.com/f/cases/21763/TraitedMetaclass-should-empty-the-localMethods-and-baseLocalMethods-when-becoming-obsolete

clean additional method dictionaries

### CODE REVIEW

**Review by dionisiydk — COMMENTED** [review]
Looks good.
But sadly we have no tests for this method

**Comment by tesonep** [comment]
@dionisiydk is right. Tomorrow I will add some tests to the PR. It is important to add test to any fix.

**Review by dionisiydk — APPROVED** [review]
Good

**Comment by pavel-krivanek** [comment]
test failure not related: 
```
testInjectingMultipleExceptionHandlersIntoNotRunningProcess – Unix32.Kernel.Tests.Processes.ProcessTest
```

**Comment by dionisiydk** [comment]
I created another issue for those tests https://pharo.fogbugz.com/f/cases/21790/Process-tests-for-injection-error-handler-still-unstable

**Pull request merged**
