### PR TITLE
Renaming

### PR DESCRIPTION
**Pull request by NourJihene**
This PR renames classes: 
MorphicModel —> ModelMorph 
> - ToggleMenuItemShortcutWithText —> ToggleWithTextMenuItemShortcut
> - DialogWindow —> DialogWindowMorph
> - MorphTreeChunkPager —> TreeChunkPagerMorph
> - MorphTreePager —> TreePagerMorph
> - MorphTreeNavigationBar —> TreeNavigationBarMorph
> - MorphTreeColumnButton —> TreeColumnButtonMorph
> - Slider —> SliderMorph
> - ScrollBar —> ScrollBarMorph
> - GeneralScrollBar —> GeneralScrollBarMorph
> - GeneralScrollPane —> GeneralScrollPaneMorph
> - TabWithNoContents —> TabWithNoContentsError
> - FTFunctionWithField —> FTWithFieldFunction
> - FTFilterFunctionWithAction —> FTWithActionFilterFunction
> - MockObjectForEventTests —> ForEventTestMock

### CODE REVIEW

**Comment by Ducasse** [comment]
@NourDjihan I have the impression that MorphicModel -> ModelMorph and not ModelMorphic

**Comment by NourJihene** [comment]
Yes you are right. Do you want to change it or I?

Nour

**Comment by Ducasse** [comment]
Please

**Comment by Ducasse** [comment]
I think that it would be better to have 
FTFunctionWithField —> FTFieldFunction
FTFilterFunctionWithAction —> FTActionFilterFunction

**Comment by NourJihene** [comment]
Done!



Le jeu. 5 août 2021 à 10:57, StéphaneDucasse ***@***.***> a
écrit :

**Comment by Ducasse** [comment]
argh I do not know how to resolve such conflicts. I will check.

**Pull request merged**
