### PR TITLE
Report exception message text when class definition loading fails

### PR DESCRIPTION
**Pull request by hernanmd**
This PR includes a minor change for Pharo 12 so we can see error messages in the Transcript when loading class definitions fail in `MCPackageLoader`.

It addresses the issue #15958.

### CODE REVIEW

**Review by jecisc — APPROVED** [review]

**Comment by jecisc** [comment]
I get a 404 while trying to access the CI result. I'll restart it

**Review by guillep — CHANGES_REQUESTED** [review]
Hi @hernanmd , could you explain how this fixes the issue?

Because this is adding an ensure only, but exceptions are caught already inside the loop. So the call to #warnAboutErrors: will happen in any case. What am I missing?

**Comment by hernanmd** [comment]
We checked this with @jecisc some weeks ago and this happened because I had an error in in the whileFalse block, of course errors were recorded, but they were not reported at all because the "Finally we warn about the errors we could not fix." was never reached.

**Review by guillep — APPROVED** [review]
ok!

**Pull request merged**
