### PR TITLE
Inconsistent usage of categories with "-" included

### PR DESCRIPTION
**Pull request by astares**
Fix many cases from #9371

### CODE REVIEW

**Comment by astares** [comment]
Ci Problem unrelated

**Comment by Ducasse** [comment]
Hi torsten

Indeed this is better to batch many of such renamings. 
Now there is one test failing that seems related: osx-64 / Tests-osx-64 / testProtocol – MacOSX64.Tests.Files.SourceFileArrayTest

**Comment by astares** [comment]
@Ducasse This one is green. Seems to be a CI problem yet again

image

**Comment by Ducasse** [comment]
This is strange because we get

```
Error

Got 'accessing - class hierarchy' instead of 'accessing class hierarchy'.
Stacktrace

TestFailure
Got 'accessing - class hierarchy' instead of 'accessing class hierarchy'.
SourceFileArrayTest(TestAsserter)>>assert:description:resumable:
SourceFileArrayTest(TestAsserter)>>assert:description:
SourceFileArrayTest(TestAsserter)>>assert:equals:
SourceFileArrayTest>>testProtocol
SourceFileArrayTest(TestCase)>>performTest
```

**Comment by astares** [comment]
@Ducasse OK - fixed it. Looked Iceberg went out of synch (even when I saved the image).

**Pull request merged**
