### PR TITLE
Failing tests to show inconsistencies in traits removal

### PR DESCRIPTION
**Pull request by ClotildeToullec**
Tests meant to show expected behavior when removing all traits from a class.
Failing for now. Related to #8549

### CODE REVIEW

**Comment by ClotildeToullec** [comment]
@tesonep @Ducasse

**Comment by Ducasse** [comment]
Thanks we will have a look.

**Comment by MarcusDenker** [comment]
Failing tests as a PR are a bit bad to handle... PRs are there to be integrated, while this one can not.

Maybe just a fileout attached to the issue tracker entry would be better?

**Comment by jecisc** [comment]
Things evolved since this change. Maybe we should check if those tests are still failing in P12?

**Comment by jecisc** [comment]
I'm closing this PR in favor of: https://github.com/pharo-project/pharo/pull/16739

I already fixed some bugs linked to those tests in some PRs and with the PR I linked I'm fixing all tests present here. I'm also adding new ones. And I added the tests present here to ensure there is no regression

**Pull request closed without merging**
