### PR TITLE
21949 not possible to save settings

### PR DESCRIPTION
**Pull request by carlotxra**
Fix https://pharo.fogbugz.com/f/cases/21949/Not-possible-to-save-settings

### CODE REVIEW

**Comment by carlotxra** [comment]
Argh I see this is a duplicate of https://pharo.fogbugz.com/f/cases/21982/Store-Settings-on-Setting-Browser-fails-with-PrimitiveFailed-primitive-flush-in-File-class-failed

**Comment by MarcusDenker** [comment]
the other one seems to have a solution, too. Can you check which is better?

**Comment by carlotxra** [comment]
The change to SettingsStonWriter is pretty much identical.
The only real benefit to this PR is that there are some new tests in SettingsStonWriterTest and SystemSettingsPersistenceTest.
A negative of this PR is that to add those tests above changes were made in MemoryFileSystemFile, MemoryFileWriteStream, and MemoryStore.

**Comment by VincentBlondeau** [comment]
Some changes for the tests here: https://github.com/carlotxra/pharo/pull/1
Then ok for me.

**Comment by Ducasse** [comment]
Ok vincent and carlotxra I integrate this.
Can you close the other bug entry?

**Comment by VincentBlondeau** [comment]
@Ducasse @carlotxra It would have been nice to integrate  https://github.com/carlotxra/pharo/pull/1 before. Because in the tests the write stream is closed twice. I think it isbetter to flush in the test then close in the teardown. See the PR

**Comment by Ducasse** [comment]
Ok. What is means is that this is super unclear what we should do. 

So where is the other PR? Because I do not get what is the PR in another repo.

**Comment by VincentBlondeau** [comment]
@Ducasse For the git PR workflow, there are 2 solutions for me to add changes to existing PR:

- I create a brand new PR with the existing changes and my changes on the Pharo repo, but the current one has to be closed and @carlotxra cannot commit anymore on my PR (or he has the same choices I am that I explain here)
- I create a PR on the PR in the @carlotxra git repository. This way, there is no issue with the creation of a new PR in the Pharo repo, but @carlotxra has to merge the PR I made to the PR to Pharo

To answer your question, the other PR is made from my repo to the @carlotxra repo (Link: https://github.com/carlotxra/pharo/pull/1). The commits are in my repo in the branch 21949-Not-possible-to-save-settings. As a member of the Pharo github project, you are able to modify the PR before merging, especially by adding more commits if needed.

HTH

**Comment by carlotxra** [comment]
Hi @Ducasse and @VincentBlondeau.

Sorry about the confusion, still getting to grips with Iceberg vs Pharo3/filetree.
Hopefully this should sort out the issue. What I've done is implement the changes suggested by @VincentBlondeau and created PR https://github.com/pharo-project/pharo/pull/1524

**Comment by Ducasse** [comment]
Thanks!!!!

**Pull request merged**
