### PR TITLE
22374 create button in debugger doesnt work for classes like it does for methods

### PR DESCRIPTION
**Pull request by macta**
Modifies the Create button in the debugger to support the creation of Classes dynamically (like it already does for methods).

To see this in action, create a class DebuggerClassCreation, with a method:

testMethod
	"self new testMethod"
	FooObject new someMethod 

When you save, use the "leave undeclared" option.

In a playground then evaluate: 
DebuggerClassCreation new testMethod

Try the create button both in the pre debug window and the full debug window - in both cases you get prompted for a class and the debugger then continues to the missing method.

NOTE: for methods, the code seems to delegate to the DebugSession and then to a DynamicMessageImplementor. I wasn't sure if it was worth putting my createClass code into the DebugSession as well (it seems like prompting code doesn't live in that, and I'm piggy backing of the OCUndeclaredVariableWarning defineClass: method to prompt and create - so I held back from pushing the code into there).

### CODE REVIEW

**Comment by MarcusDenker** [comment]
tests in DynamicMessageImplementorTest are failing

**Comment by macta** [comment]
I reverted the removal of the trailing "." on shouldBeImplemented both to fix the test (my bad) and also to reflect a preference to keep it (from the mailing list)

**Comment by macta** [comment]
The failing test appears to be a flakey test unrelated to this change?

**Review by MarcusDenker — APPROVED** [review]
Looks good. I found a way to make it fall back to creating a method in UndefinedObject for the case that is can not find a undefined global. I will merge this and do then a pass to add the improvement

**Pull request merged**
