### PR TITLE
Refact/clean

### PR DESCRIPTION
**Pull request by Ducasse**

### CODE REVIEW

**Review by jecisc — APPROVED** [review]

**Comment by Ducasse** [comment]
osx-64 / Tests-osx-64 / testModelReplaceMethodWithLessArgs(#rbClass->RBReplaceMessageSendTransformation) – MacOSX64.Refactoring2.Transformations.Tests.SingleParametrized.RBReplaceSendersMethodParametrizedTest
10s
osx-64 / Tests-osx-64 / testModelReplaceMethodWithMoreArgs(#rbClass->RBReplaceMessageSendTransformation) – MacOSX64.Refactoring2.Transformations.Tests.SingleParametrized.RBReplaceSendersMethodParametrizedTest
10s
osx-64 / Tests-osx-64 / testModelReplaceMethodWithSameArgs(#rbClass->RBReplaceMessageSendTransformation) – MacOSX64.Refactoring2.Transformations.Tests.SingleParametrized.RBReplaceSendersMethodParametrizedTest
10s
osx-64 / Tests-osx-64 / testRemoveMessageSendTransform – MacOSX64.Refactoring2.Transformations.Tests.Test.RBTransformationsTest
1s
osx-64 / Tests-osx-64 / testUndeclared – MacOSX64.ReleaseTests.Release.ReleaseTest
<1s
unix-64 / Tests-unix-64 / testModelReplaceMethodWithLessArgs(#rbClass->RBReplaceMessageSendTransformation) – Unix64.Refactoring2.Transformations.Tests.SingleParametrized.RBReplaceSendersMethodParametrizedTest
10s
unix-64 / Tests-unix-64 / testModelReplaceMethodWithMoreArgs(#rbClass->RBReplaceMessageSendTransformation) – Unix64.Refactoring2.Transformations.Tests.SingleParametrized.RBReplaceSendersMethodParametrizedTest
10s
unix-64 / Tests-unix-64 / testModelReplaceMethodWithSameArgs(#rbClass->RBReplaceMessageSendTransformation) – Unix64.Refactoring2.Transformations.Tests.SingleParametrized.RBReplaceSendersMethodParametrizedTest
10s
unix-64 / Tests-unix-64 / testRemoveMessageSendTransform – Unix64.Refactoring2.Transformations.Tests.Test.RBTransformationsTest
<1s
unix-64 / Tests-unix-64 / testUndeclared – Unix64.ReleaseTests.Release.ReleaseTest

**Comment by Ducasse** [comment]
This is strange because there are classes that I did not touch.
I will investigate.

**Comment by Ducasse** [comment]
('called:', 'on:) asSymbol is to protect when doing replace message sends.... because some tests are lazy and do not create/use a private model but the system.

**Comment by Ducasse** [comment]
"please note that this strange way to create symbol is because some tests are counting symbol
	and rewriting the code in a bad way so for now do not change them."

**Comment by Ducasse** [comment]
Broken tests are unrelated and this PR is blocking me so if this is just a wrong category I will fix it in the next one.

**Pull request merged**
