### PR TITLE
21263-WorldState--displayWorldsubmorphs--canvas--finish---canvas-can-be-nil-at-startup-of-the-image

### PR DESCRIPTION
**Pull request by VincentBlondeau**
https://pharo.fogbugz.com/f/cases/21263/WorldState-displayWorld-submorphs-canvas-finish-canvas-can-be-nil-at-startup-of-the-image

### CODE REVIEW

**Review by DraagrenKirneh — CHANGES_REQUESTED** [review]
@VincentBlondeau 
The nil check happens to late -> after canvas #roundCornersOf:during: . 
I think that the code should just return self after the #ifFalse: that is calling #assuredCanvas. 
It does not make much sense to run the rest of the code if there is no canvas to draw on.

**Comment by VincentBlondeau** [comment]
@DraagrenKirneh 
doDeferredUpdatingFor: and assuredCanvas both set a canvas.
I added a test for roundCornersOf:during: but I suspect a more high process thread concurency  between the destruction of the canvas and its creation.

**Comment by DraagrenKirneh** [comment]
> I added a test for roundCornersOf:during: 

There is still one more reference to canvas and the rest of the code may use the Display directly, so I still hold to that the check should be done at the top and exit fast if there is no canvas, as running the rest of the code when a canvas is nil makes no sense.

>but I suspect a more high process thread concurency between the destruction of the canvas and its creation.

AFAIK The startup code runs in the UI thread so this should not be possible, so if this is happening then you may have multiple UI threads running which is a bigger problem.

@VincentBlondeau 
Do you have a reproducible case / Image?

**Comment by VincentBlondeau** [comment]
Except if the image goes to sleep and message is deferred. 
To reproduce (on windows):
```
PasteUpMorph compile: 'closeAllWindowsForced
	World systemWindows
		do: [ :w | 
			w makeClosable.
			[ w delete ] valueSupplyingAnswer: false ]'
```
Cmd line:
`Pharo.exe --headless MyImage.image eval --save "World closeAllWindowsForced"`
Open the image

**Comment by Ducasse** [comment]
So we can integrate?
I checked and it seems ok for me but better checking twice

**Pull request merged**
