### PR TITLE
3217-copy-class-do-not-copy-class-side-instanceVariableNames

### LINKED ISSUE #3217: copy class do not copy class side instanceVariableNames
copy a class where there are instanceVariableNames in class side
and you wil see that the new class do not have any instanceVariableNames in class side.

### PR DESCRIPTION
**Pull request by MarcusDenker**
fixes  #3217

### CODE REVIEW

**Comment by Ducasse** [comment]
Marcus
Was test broken?
Because else it means that we should add a test to cover this behavior else it may break unnoticed.

**Comment by MarcusDenker** [comment]
I added a test

**Comment by MarcusDenker** [comment]
error not related

**Review by jecisc — APPROVED** [review]
Seems fine!

**Pull request merged**
