### PR TITLE
2366-Spotter-UI-and-Model-separation

### LINKED ISSUE #2366: Spotter UI and Model separation
Let's do separation of GT-Spotter model and UI to be able to replace this alien UI. At least it will be more clear if the model part is worth to save.

### PR DESCRIPTION
**Pull request by pavel-krivanek**
add GT-Spotter-UI

fixes #2366

### CODE REVIEW

**Comment by Ducasse** [comment]
Argh I do not understand why there is a conflict. The failing tests are not related.

**Comment by pavel-krivanek** [comment]
it has probably conflicts because of the removal of the event recorder. I'll try to fix it

**Comment by Ducasse** [comment]
Tx pavel

**Comment by Ducasse** [comment]
Again a conflict and this previous link from GLMBrick ;(

**Comment by Ducasse** [comment]
The failing tests are unrelated!

**Pull request merged**
