### PR TITLE
Fixes: #9656 unload GT

### PR DESCRIPTION
**Pull request by Ducasse**

### CODE REVIEW

**Comment by MarcusDenker** [comment]
test are failing 

StAbstractProcessorTest>>#setUp

references SptDefaultSourceFactory forTest which is removed by this PR

**Comment by MarcusDenker** [comment]
Much better but still some problems:

- DAMessageSendAnalyzerTest>>testShouldGetPotentialMatchForUnimplementedCalls
- DADependencyCheckerTest>>testShouldGetUnresolvedDependencies
- SystemDependenciesTest>>testExternalIDEDependencies  - UndefinedObject(Object)>>doesNotUnderstand: #name
- SettingBrowserTest>>testOpeningOnPackage  -> key 'GT-Playground' not found in RPackageOrganizer
- ReleaseTest>>testUndeclared - some Undeclared 

```
Found undeclared Variables:  GTObjectPrinter in: GLMCompositeBrick class>>#gtExampleTable GTSpotterCandidateLink in: IceProxyMCVersionInfo>>#asSpotterCandidateLink BaselineOfPharoGT in: SystemDependenciesTest>>#testExternalIDEDependencies
```

**Comment by Ducasse** [comment]
We should turn the broken tests as issues and close them. 
I thought that esteban fixed some in the tests of SpSpotter.

**Comment by Ducasse** [comment]
I created #9708, #9709, #9710, #9711
Now some would be easier to fix once the issue is integrated.

**Pull request merged**
