### PR TITLE
Added Rewrite Basic Editor.

### PR DESCRIPTION
**Pull request by jordanmontt**
(Copy-pasted from: #6737 ) The next step is to add an ExampleBasedEditor (you can build a rule based on Pharo's code) and to integrate this tool with MatchTool.

Stef's observations have been attended and the following changes have been added:

- Protocol name has been renamed to package name.
- Class creation has been extracted to a different method.
- The UIManager has been separated from rule creator.
- The default template rule is not hard-coded anymore. It is loaded from a saved rule.
- Several tests have been added.

### CODE REVIEW

**Comment by Ducasse** [comment]
- Pay attention setUp method should do a super setUp.

**Comment by Ducasse** [comment]
- you can replace Smalltalk globals by self class environment

**Comment by Ducasse** [comment]
- you can replace Smalltalk globals by self class environment
- (RBCustomTransformationRule subclasses collect: [ :each | each ]) => RBCustomTransformationRule subclasses

**Comment by Ducasse** [comment]
Can you tell me how you load your packages?
I think that we should have a baselineOfRewriter loading your packages.

**Comment by jordanmontt** [comment]
> Can you tell me how you load your packages?
> I think that we should have a baselineOfRewriter loading your packages.

I have this same code in [my repo](https://github.com/jordanmontt/RewriteTool-Spec2) and I have the baseline there. I will add it here as well.

**Pull request merged**
