### PR TITLE
21476 Use isNil in add: methods (Dictionary and WeakSet)

### PR DESCRIPTION
**Pull request by astares**
https://pharo.fogbugz.com/f/cases/21476/Use-isNil-in-add-methods-Dictionary-and-WeakSet

### CODE REVIEW

**Comment by dionisiydk** [comment]
I think "== nil" here is important to ensure that we do not send any message to contained objects. It is important when we work with some "naked objects" which has no messages at all.
Maybe we should not touch core collections for such cases

**Comment by MarcusDenker** [comment]
in this case #isNil is slower... adding to dictionary is a operation where we should be as fast as possible. I would want to keep == nil for speed.

**Comment by astares** [comment]
Ok, then we close this one without merging

**Comment by pavel-krivanek** [comment]
@astares can you close?

**Comment by MarcusDenker** [comment]
I can close...

**Pull request closed without merging**
