### PR TITLE
make Fonts-Infrastructure independent on FreeType

### PR DESCRIPTION
**Pull request by pavel-krivanek**
motivation: Fonts-Infrastructure is the dependency of Spec2-Core so it cleans Spec dependencies

### CODE REVIEW

**Comment by pavel-krivanek** [comment]
I will need to check manually the artifacts if they display fonts correctly

**Review by tesonep — APPROVED** [review]
The changes looks nice.

**Comment by tesonep** [comment]
Let's wait for the output of the bootstrap process

**Comment by pavel-krivanek** [comment]
the resultant image seems to work ok

**Pull request merged**
