### PR TITLE
3287-Redefine isClass in Trait

### PR DESCRIPTION
**Pull request by Alisu**
Should correct issue #3287

### CODE REVIEW

**Review by MarcusDenker — DISMISSED** [review]
Yes, that looks like a good change. no tests break with this

**Comment by dionisiydk** [comment]
Looking at senders of #isClass it will affect some existing behaviour.
For example CompiledMethod>>#referencedClasses will not return referenced traits. Maybe it is expected change but some tools could rely on it.

Generally considering that Trait is now subclass of Class I feel it confusing that isClass will return false while "Trait inheritsFrom: Class" will be true

**Review by tesonep — APPROVED** [review]
I like the change, if there is need for changes they should be added as tests. 
The method in CompiledMethod should use #isBehavior if that is required.

**Review by astares — APPROVED** [review]
OK

**Review by tesonep — APPROVED** [review]

**Pull request merged**
