### PR TITLE
21684-Integrate-Iceberg-0.7.1

### PR DESCRIPTION
**Pull request by guillep**
Integrate Iceberg 0.7
https://github.com/pharo-vcs/iceberg/releases/tag/v0.7.1

Pharo issue:
https://pharo.fogbugz.com/f/cases/21684/Integrate-Iceberg-0-7

Iceberg changes log:

First release of new model and UI. To be integrated in Pharo 7, and compatible with Pharo 6.1.

Changeslog:

Backend Cleanup.

Iceberg's backend was cleaned up. Most API methods are commented and clean. Abstractions were clarified.
All caches were reviewed and minimized. Only a couple of caches were kept or implemented when profiling indicated so.
IceWorkingCopy cleanups.
Previous Iceberg version had an abstraction called IceLoadedCode. In the new version this class was renamed as IceWorkingCopy and given more reponsibilities.

it knows the packages that belong to the repository
it holds the commit from where the repository code was loaded
This point is particularly important. Previous iceberg version tried to calculate the current commit from its MC packages, causing some hiccups when part of the packages of a repository where also commited or loaded from Monticello.
it manages the merge and the commit operations
it manages package dirtyness, behavior that was decoupled from monticello. This simplifies extensively iceberg and decouples it from MC. Further, this permits us:
to have one package as part of two repositories
to avoid refresh bugs when committing from monticello
New Working copy states
Iceberg now detects problems in the repository and de-synchronization between repository and image. This includes also managing detached HEAD state and the new detached working copy state. Several repair actions are proposed with explanations on their potential consequences.

New Merge Algorithm
The merge of Pharo code should be done inside Pharo to avoid the typical merge markers used by git (<<< >>>).
Otherwise these markers may break our parser and tools.

The new merge algorithm fixes the following bugs:

external resources are not ignored anymore (the old version was ignoring them, provoked some times their lost)
manage well cases such as fast-forward to avoid creating extra merge commits when not necessary
It includes also the following enhancements:

single merge for all packags in a project instead of one merge per package
New Changes Model
To correctly support the new merge algorithm we had to review the changes model.
Monticello change model was reused when possible, but Iceberg had to extend it to support external resources.

Lots of tests
More than 200 test were added for the new changes model, the new merge algorithm and the new backend.
Tests were sped up using Ring2 to be able to run them in a couple of seconds instead of minutes.
An iceberg backend designed to be used for testing was introduced to enforce a clean API.

New UI based on Spec and Commander. Cleaner and clearer. Tutorials incoming.

### CODE REVIEW

**Comment by guillep** [comment]
1 failing test, not related.

https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/view/change-requests/job/PR-1188/lastCompletedBuild/testReport/

**Comment by estebanlm** [comment]
still some undeclared :(

**Comment by estebanlm** [comment]
is introduced by the merge with master

**Comment by estebanlm** [comment]
ok merging... *crosses fingers*

**Pull request merged**
