### PR TITLE
21650-rename-the-class-Key-to-something-less-generic

### PR DESCRIPTION
**Pull request by pavel-krivanek**
https://pharo.fogbugz.com/f/cases/21650/rename-the-class-Key-to-something-less-generic

rename the class Key to KeyboardKey

### CODE REVIEW

**Review by jecisc — COMMENTED** [review]
Maybe you should let a #Key class as a subclass of KeyboardKey and with a deprecation in the initialization?

**Comment by pavel-krivanek** [comment]
I do not think that this class deserves deprecation. I have doubts it is used in any external project.

**Review by MarcusDenker — APPROVED** [review]
ok

**Review by jecisc — APPROVED** [review]
Then I approve too. @MarcusDenker I think it's ready for a merge.

**Comment by seandenigris** [comment]
FYI it was used by Bloc. PR here: https://github.com/pharo-graphics/Bloc/pull/40

**Pull request merged**
