### PR TITLE
Reflectivity-AddPragmaSupport 

### PR DESCRIPTION
**Pull request by MarcusDenker**
This PR adds support (and a test) for metalinks on Pragmas. (Test was from #8374)

- add testSetLinkOnPragma
- adds support in the compiler (see #visitPragmaNode:)
- adds support to ask for reifications on RBPragmaNode

### CODE REVIEW

**Comment by guillep** [comment]
I don't think this should go for Pharo 10.
This goes in the *experimental range of things* to me, and we should stop adding features as we talked.

**Comment by MarcusDenker** [comment]
It is not used outside of the test.. and it could be seen as a bug

**Comment by MarcusDenker** [comment]
But I have no problem to postpone that one to Pharo11

**Comment by guillep** [comment]
> It is not used outside of the test.. and it could be seen as a bug

That is not the point, the point is that as soon as it is inside the system, people will use it. And bugs will arrive. And that will put more pressure on us :)

I propose that this is kept in a separate project/branch or even a repository. It can be downloaded optionally, and later in the future we can evaluate it for integration when we know it is stable. Reality is that you will probably do many iterations on it until you're happy with it too.

**Pull request merged**
