### PR TITLE
5437-Add-Package-queries

### LINKED ISSUE #5437: Add Package queries
We should add two query methods to `RPackageOrganizer`:

```smalltalk
organiser selectPackages: [ :each | ... ]
```

```smalltalk
organiser selectPackageWithName: [ :name | ...  ]
```

On top of those, users could easily build more complex queries (beginsWith, endsWith, substrings, regex-based...)

### PR DESCRIPTION
**Pull request by MoussaSak**
Adding test Methods to includesPackage and includesPackageNamed and IncludingWith and testMatching and testStartingWith. fixes: #5437

### CODE REVIEW

**Comment by guillep** [comment]
Hi @MoussaSak what about the `select*` methods in the main description of the issue?

**Comment by MoussaSak** [comment]
@guillep  the main description was updated, i started the work with the old description the names of the methods were: includingWith: and includesPackageNamed:.  I can update the names of these methods if you want?

**Comment by guillep** [comment]
> @guillep the main description was updated, i started the work with the old description the names of the methods were: includingWith: and includesPackageNamed:. I can update the names of these methods if you want?

Yes please, it would be good to have a simple variant with a block only.
The block allows to define your own queries much more easily.
Check the description of the issue as I modified it.

Thanks!!

**Comment by guillep** [comment]
Hi @MoussaSak what is the status of this?

**Comment by guillep** [comment]
Ok, I'll close this. Please reopen if necessary.

**Pull request closed without merging**
