### PR TITLE
include iceberg 1.8.6

### PR DESCRIPTION
**Pull request by estebanlm**
this will add subprojects to the list of pharo projects: 

pharo
pharo-spec2
pharo-newtools

This will make easier people to contribute to those projects.

### CODE REVIEW

**Comment by Ducasse** [comment]
Esteban this breaks the build

**Comment by Ducasse** [comment]
```
MetacelloNotification: Loading -> Iceberg-Libgit-Tonel-tonel.1 --- github://pharo-vcs/iceberg:v1.8.6 --- cache
MetacelloNotification: Loaded -> Iceberg-Libgit-Tonel-tonel.1 --- github://pharo-vcs/iceberg:v1.8.6 --- cache
MetacelloNotification: Evaluating -> baseline [BaselineOfIceberg] >> postLoadWithDirective:projectSpec:
MetacelloNotification: Evaluated -> baseline [BaselineOfIceberg] >> postLoadWithDirective:projectSpec:
MetacelloNotification: ...finished baseline
#newUnbornProject was sent to nil
UndefinedObject(Object)>>doesNotUnderstand: #newUnbornProject
UndefinedObject>>doesNotUnderstand: #newUnbornProject
IceUnknownCommit>>project
IceWorkingCopy>>refreshProjectFromRepository
IceWorkingCopy>>referenceCommit:
```

**Comment by estebanlm** [comment]
... and I have no idea why, I just updated iceberg version :/

**Comment by Ducasse** [comment]
May be martin knows?

**Comment by estebanlm** [comment]
No, there is a problem with how iceberg handles this.
Anyway, I do not like this solution, I will think in a better way.

**Comment by Ducasse** [comment]
A you mean iceberg updating itself....

**Comment by tinchodias** [comment]
Yesterday I fixed in dev-1.9 the error "UndefinedObject>>doesNotUnderstand: #newUnbornProject"

**Comment by tinchodias** [comment]
This PR can revive after rebasing on dev-1.8 and releasing again.

**Pull request closed without merging**
