### PR TITLE
Introduce-LocalVariable

### PR DESCRIPTION
**Pull request by MarcusDenker**
Instead of the old structure with OCTemVariable with a subclass OCArgumentVariable, this now tries to model the level of the name analysis the same as what we have on the AST:

-> We have an abstract class LocalVariable with subclasses ArgumentVariable and TemporaryVariable
-> #isTemp now answers false for ArgumentVariable

compieler tests are green... this will allow us to clean up the #isArg, isTemp and #isArgOrTemp on the ast level easier, I hope...

Needs a careful review

### CODE REVIEW

**Comment by MarcusDenker** [comment]
@hogoww another run against the wall :-) It will fall... 

What is nice is that now the semantic level is in line what you started to do on the AST level, which I think should simplify further cleanups there

**Review by dionisiydk — APPROVED** [review]
I do not see any class deprecation. Do you think they are redundant for these variables?

**Comment by MarcusDenker** [comment]
I wanted to add subclasses for OCTempVariable and OCArgumentVariable.

Another thing that needs to be fixed is isLocal vs. isLocalVariable. #isLocal on slot is used to check if the Slot is from a Trait or not.

**Comment by dionisiydk** [comment]
> I wanted to add subclasses for OCTempVariable and OCArgumentVariable.
> 
> Another thing that needs to be fixed is isLocal vs. isLocalVariable. #isLocal on slot is used to check if the Slot is from a Trait or not.

Yes. It should be simple rename. There are not much senders. For the name I would use #isDefinedByOwningClass.

**Pull request merged**
