### PR TITLE
Fix (P7) forked processes of TestResource from being terminated between TestCase methods being executed

### PR DESCRIPTION
**Pull request by ErikOnBike**
Fixes issue number 3582 in Pharo7.0 branche (another PR is already created for Pharo8.0 branche)

### CODE REVIEW

**Comment by ErikOnBike** [comment]
CI error seems unrelated

**Review by dionisiydk — APPROVED** [review]

**Comment by MarcusDenker** [comment]
This should be merged after #3583 has been merged in Pharo8

**Comment by MarcusDenker** [comment]
#3583  has been merged and seems to work.

**Comment by MarcusDenker** [comment]
We use this in Pharo 8 for some days with no reported problems: save to merger

**Pull request merged**
