### PR TITLE
Make drtests spec2 compatible

### PR DESCRIPTION
**Pull request by estebanlm**
I made a pass to adapt DrTests to latest Spec2.
There are also some enhancements on how information is presented (some coloring and autoexpand of nodes)
is in general usable now :)

### CODE REVIEW

**Comment by MarcusDenker** [comment]
```
MetacelloNotification: Loading -> DrTests-tonel.1 --- tonel:///builds/workspace/est_and_branch_Pipeline_PR-11859/64/src --- cache
Error: Package *DrTests depends on the following classes:
  StPharoStyleContributor
  StPresenter
```

**Comment by Ducasse** [comment]
Cool!!!
Could we have the same for the rewrite tool because we need it too. https://github.com/jordanmontt/RewriteToolsSet
I would like to have it in NewTools (we could start to have it as an optional projet) and the microdown document browser too.


<blockquote><div> GitHub</div><div><strong><a href="https://github.com/jordanmontt/RewriteToolsSet">GitHub - jordanmontt/RewriteToolsSet: A set of tools that allows to do complex searches and code transformations using the refactoring engine in Pharo!</a></strong></div><div>A set of tools that allows to do complex searches and code transformations using the refactoring engine in Pharo!  - GitHub - jordanmontt/RewriteToolsSet: A set of tools that allows to do complex s...</div></blockquote>

**Comment by Ducasse** [comment]
I was looking at the way you cover color into style and I have two questions: 
- how do we declare the style
- and in initializeItemsListAndLabel the theme is using a color. Does it use the styler?

```
initializeItemsListAndLabel [

 	itemsList := self newFilterableListPresenter.
 	itemsList
 		displayIcon: [ :aClass | self iconNamed: aClass systemIconName  ];
 		displayColor: [ :aClass | (self packagesSelected includes: aClass package)
 		displayColor: [ :aClass | 
 			(self packagesSelected includes: aClass package)
 				ifTrue: [ self theme textColor ]
 				ifFalse: [ self theme classExtensionColor ] ]

```

**Comment by Ducasse** [comment]
DTStyleContributor ;) for the first question.

**Comment by Ducasse** [comment]
Does it manage that an expanded node stays expanded?
Because this would be super cool.

**Comment by estebanlm** [comment]
> Does it manage that an expanded node stays expanded? Because this would be super cool.

I did just few modifications. I am not convinced about the tree as a way to show results but right now I let it like that, as my times are limited. 
What I did is: 
- errors and failures nodes are expanded by default.
- errors, failures and passing nodes are show with colors (in case there are results). 

Like this: 

image

Still not great (and we should keep expanded nodes opened from run to run too, in another step)

**Comment by estebanlm** [comment]
> Cool!!! Could we have the same for the rewrite tool because we need it too. https://github.com/jordanmontt/RewriteToolsSet I would like to have it in NewTools (we could start to have it as an optional projet) and the microdown document browser too.
> 
> >  GitHub**[GitHub - jordanmontt/RewriteToolsSet: A set of tools that allows to do complex searches and code transformations using the refactoring engine in Pharo!](https://github.com/jordanmontt/RewriteToolsSet)**A set of tools that allows to do complex searches and code transformations using the refactoring engine in Pharo!  - GitHub - jordanmontt/RewriteToolsSet: A set of tools that allows to do complex s...

sure, I will add it to my "for-when-I-m-bored" todo list ;)

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/jordanmontt/RewriteToolsSet">GitHub - jordanmontt/RewriteToolsSet: A set of tools that allows to do complex searches and code transformations using the refactoring engine in Pharo!</a></strong></div><div>A set of tools that allows to do complex searches and code transformations using the refactoring engine in Pharo!  - GitHub - jordanmontt/RewriteToolsSet: A set of tools that allows to do complex s...</div></blockquote>

**Comment by estebanlm** [comment]
> I was looking at the way you cover color into style and I have two questions:
> 
>     * how do we declare the style
> 
>     * and in initializeItemsListAndLabel the theme is using a color. Does it use the styler?
> 
> 
> ```
> initializeItemsListAndLabel [
> 
>  	itemsList := self newFilterableListPresenter.
>  	itemsList
>  		displayIcon: [ :aClass | self iconNamed: aClass systemIconName  ];
>  		displayColor: [ :aClass | (self packagesSelected includes: aClass package)
>  		displayColor: [ :aClass | 
>  			(self packagesSelected includes: aClass package)
>  				ifTrue: [ self theme textColor ]
>  				ifFalse: [ self theme classExtensionColor ] ]
> ```

nope, this is an inconsistency in spec I want to work on next (but believe it or not, is not so easy).

**Comment by estebanlm** [comment]
> DTStyleContributor ;) for the first question.

this is a way to add styles to the stylesheet of `StPharoApplication`, because otherwise we create an undesirable dependence.

**Comment by Ducasse** [comment]
Ok cool. It is already an improvement. About the failure color orange would be better.

**Pull request merged**
