### PR TITLE
ZnStaticFileDecoratorDelegate>>#path: should be in "accessing", not "accesing"

### LINKED ISSUE #11024: ZnStaticFileDecoratorDelegate>>#path: should be in "accessing", not "accesing"
wrong category

image

### PR DESCRIPTION
**Pull request by astares**
Fix #11024

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Same as https://github.com/pharo-project/pharo/pull/10967

**Comment by svenvc** [comment]
Picked up upstream: https://github.com/svenvc/zinc/commit/8042884dea032b9250f18506fcdce3f029cc6e74

**Comment by astares** [comment]
@svenvc 
PR for Zinc repo is https://github.com/svenvc/zinc/pull/87

**Comment by MarcusDenker** [comment]
I merged the other PR

**Pull request closed without merging**
