### PR TITLE
22039-Introduce-displayScaleFactor

### PR DESCRIPTION
**Pull request by pavel-krivanek**

### CODE REVIEW

**Comment by jecisc** [comment]
@pavel-krivanek I tried to launch the generated image on Windows 10 but it did not open and I have a process Pharo at more than 20% of CPU running.

**Comment by pavel-krivanek** [comment]
Strange, I tried the image on the Windows 10 too now without any issue

**Comment by pavel-krivanek** [comment]
actually, I see no reason why this PR should cause such behavior

**Comment by jecisc** [comment]
I can still reproduce... Maybe it is a problem with the generated image and not this PR?

**Comment by jecisc** [comment]
Oh no, you said you tried this image...

**Comment by pavel-krivanek** [comment]
I tried the launcher and I have the same behavior without any possibility to discover the reason... great OS...

**Comment by jecisc** [comment]
I also use the Launcher.

**Comment by pavel-krivanek** [comment]
it is recursive error in FFI - LogicalFontManager

```
[31mCould not find accessor for variable named "'dest'"
[0mFFICallout>>loaderForArgNamed:
FFICallout>>loaderForArgNamed:indirectIndex:
FFICallout>>argName:indirectIndex:type:ptrArity:
FFIFunctionParser>>parseArgument
FFIFunctionParser>>parseArguments
FFIFunctionParser>>parseNamedFunction:
FFICalloutMethodBuilder>>parseSignature:
FFICalloutMethodBuilder>>generate
FFICalloutMethodBuilder>>build:
FFICalloutAPI>>function:module:
LibC(Object)>>ffiCall:
LibC>>memCopy:to:size:
LibC class>>memCopy:to:size:
FreeTypeExternalMemory>>primCopyToExternalMemory:
FreeTypeExternalMemory>>validate
EmbeddedFreeTypeFontInstaller>>addFromFileContents:baseName:
SourceCodeProRegular class(EmbeddedFreeTypeFontFontDescription class)>>installFontsIn:
[ :arg2 | arg2 installFontsIn: arg1 ] in EmbeddedFreeTypeFontFontDescription class>>installAllFontsIn: in Block: [ :arg2 | arg2 installFontsIn: arg1 ]
OrderedCollection>>do:
EmbeddedFreeTypeFontFontDescription class>>installAllFontsIn:
EmbeddedFreeTypeFontInstaller>>installAllFontsIn:
[ :arg1 | arg1 installAllFontsIn: self ] in FreeTypeFontProvider>>updateEmbeddedFreeTypeFonts in Block: [ :arg1 | arg1 installAllFontsIn: self ]
OrderedCollection>>do:
FreeTypeFontProvider>>updateEmbeddedFreeTypeFonts
FreeTypeSettings class>>updateFreeType
FreeTypeSettings class>>startUp:
ClassSessionHandler>>startup:
[ :arg2 | arg2 startup: arg1 ] in WorkingSession>>runStartup: in Block: [ :arg2 | arg2 startup: arg1 ]
[ arg2 value: arg3 ] in [ :arg3 | 
[ arg2 value: arg3 ]
	on: Exception
	do: [ :arg4 | self errorHandler handleError: arg4 ] ] in WorkingSession>>runList:do: in Block: [ arg2 value: arg3 ]
BlockClosure>>on:do:
[0m[31mFFIVariableNameNotFound: Could not find accessor for variable named "'aPointer'"
[0mFFICallout>>loaderForArgNamed:
FFICallout>>loaderForArgNamed:indirectIndex:
FFICallout>>argName:indirectIndex:type:ptrArity:
FFIFunctionParser>>parseArgument
FFIFunctionParser>>parseArguments
FFIFunctionParser>>parseNamedFunction:
FFICalloutMethodBuilder>>parseSignature:
FFICalloutMethodBuilder>>generate
FFICalloutMethodBuilder>>build:
FFICalloutAPI>>function:module:
FT2Library(Object)>>ffiCall:
FT2Library>>ffiInitFreeType:
FT2Library>>checkLibrary
FT2Library>>isAvailable
FreeTypeFontProvider>>fontFor:familyName:
[ :arg4 | 
| tmp4 tmp6 |
tmp6 := tmp4 := arg4 fontFor: arg1 familyName: arg3.
tmp6 ifNotNil: [ ^ tmp4 ] ] in [ :arg3 | 
fontProviders
	do: [ :arg4 | 
		| tmp4 tmp6 |
		tmp6 := tmp4 := arg4 fontFor: arg1 familyName: arg3.
		tmp6 ifNotNil: [ ^ tmp4 ] ].
tmp2 := TextStyle named: arg3.
tmp2
	ifNotNil: [ tmp3 := tmp2 fontOfPointSize: arg1 pointSize.
		tmp3 ifNotNil: [ ^ tmp3 emphasized: arg1 emphasis ] ] ] in LogicalFontManager>>bestFontFor:whenFindingAlternativeIgnoreAll: in Block: [ :arg4 | ...
OrderedCollection>>do:
[ :arg3 | 
fontProviders
	do: [ :arg4 | 
		| tmp4 tmp6 |
		tmp6 := tmp4 := arg4 fontFor: arg1 familyName: arg3.
		tmp6 ifNotNil: [ ^ tmp4 ] ].
tmp2 := TextStyle named: arg3.
tmp2
	ifNotNil: [ tmp3 := tmp2 fontOfPointSize: arg1 pointSize.
		tmp3 ifNotNil: [ ^ tmp3 emphasized: arg1 emphasis ] ] ] in LogicalFontManager>>bestFontFor:whenFindingAlternativeIgnoreAll: in Block: [ :arg3 | ...
Array(SequenceableCollection)>>do:
LogicalFontManager>>bestFontFor:whenFindingAlternativeIgnoreAll:
LogicalFontManager>>bestFontFor:
LogicalFont>>findRealFont
LogicalFont>>realFont
LogicalFont>>xTable
CompositionScanner(CharacterScanner)>>setActualFont:
CompositionScanner>>setActualFont:
CompositionScanner(CharacterScanner)>>setFont:
TextFontChange>>emphasizeScanner:
(text attributesAt: lastIndex forStyle: textStyle) in CompositionScanner(CharacterScanner)>>setFont in Block: (text attributesAt: lastIndex forStyle: textStyle)...etc...
Array(SequenceableCollection)>>do:
[0m[31mFFIVariableNameNotFound: Could not find accessor for variable named "'aPointer'"
[0mFFICallout>>loaderForArgNamed:
FFICallout>>loaderForArgNamed:indirectIndex:
FFICallout>>argName:indirectIndex:type:ptrArity:
FFIFunctionParser>>parseArgument
FFIFunctionParser>>parseArguments
FFIFunctionParser>>parseNamedFunction:
FFICalloutMethodBuilder>>parseSignature:
FFICalloutMethodBuilder>>generate
FFICalloutMethodBuilder>>build:
FFICalloutAPI>>function:module:
FT2Library(Object)>>ffiCall:
FT2Library>>ffiInitFreeType:
FT2Library>>checkLibrary
FT2Library>>isAvailable
```

**Comment by pavel-krivanek** [comment]
problem on windows seems to be fixed

**Pull request merged**
