### PR TITLE
2546 Small cleanup UFFI to better distinguish architecture type

### LINKED ISSUE #2546: Small cleanup UFFI to better distinguish architecture type
- better distinguish into abstract and concrete architectures by providing an #isAbstract implementation 
  on class side and using it
- add tests

This will also improve #uniqueInstance implementation as it is not necessary to have an implementation in FFI_x86_64 (only in FFIArchitecture)

### PR DESCRIPTION
**Pull request by astares**
Fixes #2546

### CODE REVIEW

**Review by tesonep — APPROVED** [review]

**Comment by jecisc** [comment]
I relaunched the CI.

**Comment by MarcusDenker** [comment]
errors not related

**Comment by MarcusDenker** [comment]
I will close/open so it will run against the latest

**Comment by MarcusDenker** [comment]
error not related, I will merge (has been reviewed by pablo)

**Comment by astares** [comment]
Thx

**Pull request merged**
