### PR TITLE
use DoubleByteLayout and DoubleWordLayout

### LINKED ISSUE #7498: Bootrap need to be able to load classes with layout #DoubleByteLayout
**Describe the bug**
When changing the layout of DoubleByteArray to #DoubleByteLayout, the boostrap can not load the class definition, see https://github.com/pharo-project/pharo/pull/7497

Error: Unrecognized class type
MCClassDefinition(Object)>>error:
MCClassDefinition>>kindOfSubclass

**Solution**

We can add the version of  MCClassDefinition>>#kindOfSubclass that we have in Pharo9 as an overriding extension method to the MonticelloTonel-Compatibility package here:

https://github.com/pharo-vcs/tonel/tree/master/MonticelloTonel-Compatibility.package

If we do that and add the needed creation methods that start with variableDoubleByteSubclass: , it should be possible to load classes like that with the bootstrap.

kindOfSubclass
	type = #normal ifTrue: [^ ' subclass: '].
	type = #words ifTrue: [^ ' variableWordSubclass: '].
	type = #variable ifTrue: [^ ' variableSubclass: '].
	type = #bytes ifTrue: [^ ' variableByteSubclass: '].
	type = #weak ifTrue: [^ ' weakSubclass: ' ].
	type = #compiledMethod ifTrue: [^ ' variableByteSubclass: ' ].
	type = #immediate ifTrue: [ ^ ' immediateSubclass: ' ].
	type = #ephemeron ifTrue: [ ^ ' ephemeronSubclass: ' ].
	type = #DoubleByteLayout ifTrue: [ ^' variableDoubleByteSubclass: ' ].
	type = #DoubleWordLayout ifTrue: [ ^' variableDoubleWordSubclass: ' ].
	"hack to support user defined layouts"
	(Smalltalk hasClassNamed: type) ifTrue: [ ^type asString].
	self error: 'Unrecognized class type', type asString

### PR DESCRIPTION
**Pull request by MarcusDenker**
This PR fixes the class layouts of DoubleByteArray and DoubleWordArray
This should now be possible with the updated bootstrap

fixes #7498

### CODE REVIEW

**Comment by MarcusDenker** [comment]
The method "MCClassDefinition>>kindOfSubclass" used by the boostrap seems to be not the one from Pharo9:

```
+ ./pharo Pharo.image --no-default-preferences /builds/workspace/uest_and_branch_Pipeline_PR-9792/64/bootstrap/scripts/bootstrap.st --ARCH=64 --BUILD_NUMBER=1 --VERSION_INFO=Pharo10.0-PR-g790b61f556273ba46530b1fdea58d69bc8982651 --quit
Architecture: 64
BuildNumber: 1
VersionInfo: Pharo10.0-PR-g790b61f556273ba46530b1fdea58d69bc8982651Error: Unrecognized class type
MCClassDefinition(Object)>>error:
MCClassDefinition>>kindOfSubclass
MCClassDefinition>>printDefinitionOn:
[:s | definition printDefinitionOn: s] in MCStWriter>>writeClassDefinition: in Block: [:s | definition printDefinitionOn: s]
```

**Comment by MarcusDenker** [comment]
I close it for now and redo after boostrap fix

**Comment by guillep** [comment]
This is failing because the bootstrap has an override on MCClassDefinition

https://github.com/pharo-project/pharo/blob/Pharo10/bootstrap/src/Pharo30Bootstrap/MCClassDefinition.extension.st

We should remove it

**Comment by MarcusDenker** [comment]
Next problem: ring2LayoutType does not support the double layouts, I have opened:

https://github.com/pharo-project/pharo/issues/10191

**Comment by MarcusDenker** [comment]
I think we need to make a new version for the bootrap image that contains the new #ring2LayoutType

**Comment by MarcusDenker** [comment]
Random failing tests:
- [CI] Failing randomly: Spec related tests with DNU SmallFloat64 >> #nextCell: #10522
- FFITypesTest>>testSignedLongLong sometimes failing on the CI #9931

**Pull request merged**
