### PR TITLE
22894-Unecessary-dialogs-during-refactorings

### PR DESCRIPTION
**Pull request by dionisiydk**
It updates Calypso: v0.15.1 which fixes the issue

### CODE REVIEW

**Comment by dionisiydk** [comment]
https://pharo.manuscript.com/f/cases/22894/Unecessary-dialogs-during-refactorings

**Comment by dionisiydk** [comment]
VM crash is unrelated.
The fix was really trivial: it removes explicit first item selection from initiaization of scope drop list. Drop list itself selects first item when new list is specified. So extra #selectItem: was redundant and it leaded to double selection handler.

**Comment by guillep** [comment]
@jecisc since you're the one invoved in the calypso issue, do you think this is for Pharo7?

**Comment by jecisc** [comment]
Definitively.

You do not want to have two times the same warnings each time you rename a method. That's something we do often.

**Comment by dionisiydk** [comment]
Notice it is one line change

пн, 14 янв. 2019 г., 9:48 CyrilFerlicot notifications@github.com:

**Comment by dionisiydk** [comment]
I updated version to 0.15.2 to include another fix (also one line) for broken setUp method tab

**Comment by dionisiydk** [comment]
And version 0.15.3 includes fix for class remove command:
https://pharo.manuscript.com/f/cases/22895/Cannot-remove-a-class-that-has-spurious-references-to-it

**Comment by MarcusDenker** [comment]
error not related.

**Pull request merged**
