### PR TITLE
21730-There-is-packages-not-loaded-in-Pharo-s-repository

### PR DESCRIPTION
**Pull request by jecisc**
Remove package not loaded in the image and add a script to do this if we need later. 

Close 21730 : https://pharo.fogbugz.com/f/cases/21730/There-is-packages-not-loaded-in-Pharo-s-repository

### CODE REVIEW

**Review by MarcusDenker — APPROVED** [review]
looks good: all the deleted code is not loaded by the bootstrap.

**Comment by tesonep** [comment]
@jecisc Can we add the script to run in the bootstrap process so we check if new packages are created by error? 

Thanks

**Comment by jecisc** [comment]
Yes! 

I think it's more "not removed after been removed from the baselines" than "created by error".

Either you tell me how/where to do it, or you can do it :)

**Comment by MarcusDenker** [comment]
I suggest we merge this and then do another step for automatisation

**Pull request merged**
