### PR TITLE
2607-reset-methods-should-be-in-initialization-protocol-and-a-test-should-ensure-we-do-not-have-regression

### PR DESCRIPTION
**Pull request by hilaire**
Merge 987c7671182b5323c2ce7ef8533fa0cab69cd872

### CODE REVIEW

**Comment by hilaire** [comment]
Is this pull request ok? Because Pharo repeatedly crashed so I have to install a new one, the repo was out of sync. 
While I resync some unwished commit was inserted, I try do delete from github this commit (EpLogBrowserPresenter.class.st) and I need to know if it is fine.
Is the "Delete EpLogBrowserPresenter.class.st" commit clearly a diff delete and not a file delete from repo?
Thanks

**Comment by MarcusDenker** [comment]
the PR deletes class EpLogBrowserPresenter. Which is strange, as if this should be done it would be better done it it's own PR.

**Comment by hilaire** [comment]
I don't want to delete this file but delete its diff. When I pushed, Pharo did a pull where this diff on EoLogBrowserPresenter shows up.

**Comment by MarcusDenker** [comment]
it might be that EpLogBrowserPresenter calls a deprecated method and gets transformed automatically (the transcript should have a log about it).

These auto-transformed methods can be just committed, even as part of another PR, I think.

**Comment by hilaire** [comment]
Hum, yes. And about my questioning?

**Comment by MarcusDenker** [comment]
This PR still deletes a whole class. The easiest is to just redo it... there are now merge conflicts in addition.

**Comment by estebanlm** [comment]
:( 
Please, submit a new PR.

**Pull request closed without merging**
