### PR TITLE
Remove convertInterval:for: of tests of Refactoring

### PR DESCRIPTION
**Pull request by Lin777**
Remove unnecessary and redundant method convertInterval:for:, this only return the interval, put inline the interval in all senders of this method

### CODE REVIEW

**Comment by Ducasse** [comment]
I do not get why this is better to inline the definition of conbertInterval:for: 
to me this is regression.

**Comment by Lin777** [comment]
The method is this:
```
convertInterval: anInterval for: aString 
	"Convert the interval to ignore differences in end of line conventions."

	^anInterval
```
I think it was unnecessary, but maybe it was created for some future work. The next one I will create an Issue before, to know if this change is necessary or not

**Comment by Ducasse** [comment]
Ok I was confused reading the code.

**Comment by MarcusDenker** [comment]
the build now has test failing

**Comment by MarcusDenker** [comment]
testInlineComponentIntoCascadedMessage :RBInlineMethodFromComponentTest
testInlineEmptyComponentMethod – RBInlineMethodFromComponentTest

both doesNotUnderstand: #convertInterval:for:

**Pull request merged**
