### PR TITLE
Deprecate-removed-projects

### PR DESCRIPTION
**Pull request by jecisc**
Deprecate BlueInk and GTEnventRecorder.

### CODE REVIEW

**Comment by Ducasse** [comment]
So you should also fix the dependencies.
And we will have to remove again the dependencies in P9.
And you can remove also the tests of BlueInk.

**Comment by jecisc** [comment]
Hi,

The two projects are loaded last in the image and it builds well. There is no dependence on the image to those two projects.

All the dependency tests are green.

For the removal, everything is in a deprecated section in the BaselineOfPharo. It is as simple as to remove this section since it is loaded last and in general, I take care of it:
- https://github.com/pharo-project/pharo/pull/5006
- https://github.com/pharo-project/pharo/pull/2760
- https://github.com/pharo-project/pharo/pull/2307

**Review by VincentBlondeau — APPROVED** [review]
Built image with the deprecated packages. The load of the PR is not possible on an old image though. 

Thanks Cyril!

**Comment by estebanlm** [comment]
this is already handled

**Pull request closed without merging**
