### PR TITLE
New finalization

### PR DESCRIPTION
**Pull request by guillep**
[Disclaimer] This PR requires the latest VM to run. We are going to streamline it for testing first. This will integratable be as soon the new VM is marked as stable.

- Introduce a new `FinalizationRegistry` that uses ephemerons
- Cleanup users of `WeakRegistry` to use `FinalizationRegistry` instead.
- Define `WeakRegistry>>default` to return `FinalizationRegistry default` to keep backwards compatibility

Interesting class comment: in `src/System-Finalization/FinalizationRegistry.class.st`

Main checklist before integration:
- [x] VM PR https://github.com/pharo-project/pharo-vm/pull/511
- [x] Introduce nightly builds in zeroconf

### CODE REVIEW

**Comment by Ducasse** [comment]
Great. You will have to explain me what was the problem we saw :)

**Comment by Ducasse** [comment]
SystemNotification: Loading System-SourcesCondenser-tonel.1.mcz
SystemNotification: Loading Shift-ClassInstaller-tonel.1.mcz
SystemNotification: Loading CodeExport-Traits-tonel.1.mcz
SystemNotification: Loading Collections-Sequenceable-tonel.1.mcz
[ERROR] 2022-12-02 17:13:43.000 error (src/debug.c:45):Recursive not understood error encountered

VM Error Fri Dec  2 17:13:43 2022


/builds/workspace/est_and_branch_Pipeline_PR-12042/64/bootstrap-downloads/vmtarget/pharo-vm/lib/pharo
PharoVM version:5.0-Pharo 9.0.20 built on Oct  5 2022 14:59:22 Compiler: 5.4.0 20160609 5.4.0 20160609 [Production Spur 64-bit VM]
Built from: CoInterpreter * VMMaker-tonel.1 uuid: c1e676da-aaa6-0d00-9da1-e5e408c6380e Oct  5 2022
 With:StackToRegisterMappingCogit * VMMaker-tonel.1 uuid: c1e676da-aaa6-0d00-9da1-e5e408c6380e Oct  5 2022
 Revision: v9.0.20 - Commit: 2f226ea - Date: 2022-10-05 14:39:39 +0200

C stack backtrace & registers:
	rax 0x1f1a3d9000000000 rbx 0x0d57d860 rcx 0x7fa574e7f3dd rdx 0x00000000
	rdi 0x7ffe73be6af0 rsi 0x7ffe73be6af0 rbp 0x00000014 rsp 0x7ffe73be6af0
	r8  0x7fa57514e770 r9  0x7fa57570d700 r10 0x7fa57514e770 r11 0x7fa57570d700
	r12 0x0ca1af80 r13 0x00000000 r14 0x00000097 r15 0x00000000
	rip 0x7fa575216254
*/builds/workspace/est_and_branch_Pipeline_PR-12042/64/bootstrap-downloads/vmtarget/pharo-vm/lib/libPharoVMCore.so(printStatusAfterError+0x24)[0x7fa575216254]
/

**Comment by guillep** [comment]
> SystemNotification: Loading System-SourcesCondenser-tonel.1.mcz SystemNotification: Loading Shift-ClassInstaller-tonel.1.mcz SystemNotification: Loading CodeExport-Traits-tonel.1.mcz SystemNotification: Loading Collections-Sequenceable-tonel.1.mcz [ERROR] 2022-12-02 17:13:43.000 error (src/debug.c:45):Recursive not understood error encountered
> 
> VM Error Fri Dec 2 17:13:43 2022
> 
> /builds/workspace/est_and_branch_Pipeline_PR-12042/64/bootstrap-downloads/vmtarget/pharo-vm/lib/pharo PharoVM version:5.0-Pharo 9.0.20 built on Oct 5 2022 14:59:22 Compiler: 5.4.0 20160609 5.4.0 20160609 [Production Spur 64-bit VM] Built from: CoInterpreter * VMMaker-tonel.1 uuid: c1e676da-aaa6-0d00-9da1-e5e408c6380e Oct 5 2022 With:StackToRegisterMappingCogit * VMMaker-tonel.1 uuid: c1e676da-aaa6-0d00-9da1-e5e408c6380e Oct 5 2022 Revision: v9.0.20 - Commit: 2f226ea - Date: 2022-10-05 14:39:39 +0200
> 
> C stack backtrace & registers: rax 0x1f1a3d9000000000 rbx 0x0d57d860 rcx 0x7fa574e7f3dd rdx 0x00000000 rdi 0x7ffe73be6af0 rsi 0x7ffe73be6af0 rbp 0x00000014 rsp 0x7ffe73be6af0 r8 0x7fa57514e770 r9 0x7fa57570d700 r10 0x7fa57514e770 r11 0x7fa57570d700 r12 0x0ca1af80 r13 0x00000000 r14 0x00000097 r15 0x00000000 rip 0x7fa575216254 */builds/workspace/est_and_branch_Pipeline_PR-12042/64/bootstrap-downloads/vmtarget/pharo-vm/lib/libPharoVMCore.so(printStatusAfterError+0x24)[0x7fa575216254] /

Yes, this PR introduces by default the ephemeron finalization, which is failing in the stable VM.
When this runs on the latest VM it should work ok!

**Comment by Ducasse** [comment]
I want to know what was the problem we got :).

**Comment by guillep** [comment]
The PR is failing for now because it requires the new VM with ephemeron support to run.
We are working on it.

**Comment by demarey** [comment]
I do not see new finalization tests in the PR. Maybe an omission?

**Comment by jecisc** [comment]
Pablo already did a PR to use the latest VM all the time. Tests passed we just need a merge

**Review by estebanlm — APPROVED** [review]

**Pull request merged**
