### PR TITLE
3606 - Add option to rename parameters

### LINKED ISSUE #3606: Refactoring: Missing rename parameters option
Missing rename parameters option  for extract method refactoring

### PR DESCRIPTION
**Pull request by Lin777**
Added the option of renamed to the extract method refactoring, however you can only perform the rename by modifying the preview used in SystemCommands. fixes #3606

### CODE REVIEW

**Comment by Ducasse** [comment]
I evelyn this sounds good to me. Now could you rename dictParameters into parameterDictionary or parameterMap?

**Comment by Lin777** [comment]
Of course, I modify it now

**Review by myroslavarm — APPROVED** [review]
looks good!

btw what does this syntax with ~ mean? in line
key ~= value ifTrue: [ self renameParameterWith: key to: value ]]
I'm not sure I know it

**Comment by Ducasse** [comment]
Check the implementors of  ~=
this is == not

**Comment by jecisc** [comment]
The work of Clément was integrated into Pharo 8. Can you please check how it can integrate with it?

Here I see a copy of the UI to rename a method. Maybe it could change the current one instead.

**Comment by Lin777** [comment]
Sure, I'm preparing a PR to integrate the new views and modify according to the new integrations of spec2

**Comment by guillep** [comment]
Hi @Lin777, can you give us un updated on this?
 - there is a merge conflict, can you solve it?
 - is this ready to integrate

@jecisc are the issues you saw with @CafeKrem's code still valid?

**Comment by Lin777** [comment]
Hi, @guillep I did a new [PR](https://github.com/pharo-project/pharo/pull/4126) that contain this changes, integrate with new SycMethodNameEditor class, and add other features.

**Comment by jecisc** [comment]
Can you close this one then? Thank you

**Pull request closed without merging**
