### PR TITLE
fixes #8421 sp tree table presenter with multiple columns has unintended indentation

### LINKED ISSUE #8421: SpTreeTablePresenter with multiple columns has unintended indentation
All the examples I was able to find using SpTreeTablePresenter and is older brothers (FTTableMorphs ...) only had a single column. For my case I wanted the tree expansion, but also several columns. This example code is an adaption of the example in SpTablePresenter:

```smalltalk
SpTreeTablePresenter new
		addColumn: (SpCompositeTableColumn new
			title: 'Classes';
			addColumn: ((SpImageTableColumn evaluated: [:c| c systemIcon]) width: 20);
			addColumn: (SpStringTableColumn evaluated: #name);
			width: 200;
			yourself);
		addColumn: (SpStringTableColumn new
			title: 'Methods';
			evaluated: [:class | class methodDictionary size asString];
			width: 80);
		roots: { Object };
		children: [ :aClass | aClass subclasses ];
		openWithSpec
```

When I open this and open a few rows, I might get this image:

Untitled

I can kind of understand what happens with the wrong indentation, namely that the arrows are not included in the computations of where the columns start, and that it looks fine in single column tree tables. Nevertheless, I think it is a bug. I fear it is buried deep in the FT part. Perhaps it is easier to adjust the header columns than the actual columns - that would look kind of odd, but also acceptable I think.

If I do not include the `width: 200`, I get even more unacceptable results:
Untitled 2

### PR DESCRIPTION
**Pull request by kasperosterbye**
Added an example, and fixed the very simple bug

### CODE REVIEW

**Comment by guillep** [comment]
@estebanlm maybe you would like to review this one?

**Comment by Ducasse** [comment]
@estebanlm can you have a look at this issue so that we close it?

**Comment by estebanlm** [comment]
please, @kasperosterbye... can you push this changes to https://github.com/pharo-spec/Spec ?
Otherwise I will need to push them... and my times are very tight, especially with the recurrent lockdowns  we have these days :)

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/pharo-spec/Spec">pharo-spec/Spec</a></strong></div><div>Spec is a framework in Pharo for describing user interfaces. - pharo-spec/Spec</div></blockquote>

**Comment by kasperosterbye** [comment]
I'll see if I can figure out how to push to that repo @estebanlm, it will be sometime this week.

**Comment by estebanlm** [comment]
is easy: you do the same as with `pharo` but with the `pharo-spec` project :)

**Comment by estebanlm** [comment]
this was integrated directly to pharo-spec

**Pull request closed without merging**
