### PR TITLE
5154-Improve-CompiledCodehasLiteralThorough-literal

### PR DESCRIPTION
**Pull request by demarey**
Simplify hasLiteralThorough: by dispatching literal checking on objects.
Rename hasLiteralThorough: to refersToLiteral:

### CODE REVIEW

**Comment by MarcusDenker** [comment]
I close and reopen to run the latest tests

**Comment by MarcusDenker** [comment]
I did simple benchmark, and the new code is even a tiny bit faster!

[#do: senders] bench 

After:  "'3.525 per second'"
Before: "'3.499 per second'"

**Review by MarcusDenker — APPROVED** [review]
ok

**Comment by MarcusDenker** [comment]
failing test not related

**Comment by guillep** [comment]
> After: "'3.525 per second'"
> Before: "'3.499 per second'"

This benchmark makes no sense Marcus, 3.525 means 3 and a half times per second, not 3 thousand. So it's no real improvement at all.

**Pull request merged**
