### PR TITLE
Merge NewTools v0.4.2.1 with debugger fixes

### LINKED ISSUE #6960: Context with block argument looks strange.
Screenshot 2020-07-22 at 23 51 47

### PR DESCRIPTION
**Pull request by StevenCostiou**
Contains NewTools 0.4.2.1 
https://github.com/pharo-spec/NewTools/releases/tag/v0.4.2.1
Fixes #6960 #6954 #6946

### CODE REVIEW

**Comment by Ducasse** [comment]
Do you unregister to SystemAnnouncer after this test

```
StHaltCacheTest >> testCacheActivation [
 	cache := StHaltCache new.
 	cache isActive: true.
 	self assert: cache isActive.
 	self assert: (SystemAnnouncer uniqueInstance hasSubscriber: cache) 
 ]
```

**Comment by StevenCostiou** [comment]
> Do you unregister to SystemAnnouncer after this test
> 
> ```
> StHaltCacheTest >> testCacheActivation [
>  	cache := StHaltCache new.
>  	cache isActive: true.
>  	self assert: cache isActive.
>  	self assert: (SystemAnnouncer uniqueInstance hasSubscriber: cache) 
>  ]
> ```

No I do not unregister, because the halt cache uses weak subscriptions to the system announcer.
I could add a test to be sure that the used system announcer is weak.

**Review by MarcusDenker — APPROVED** [review]

**Comment by dionisiydk** [comment]
Even if it is weak it's very important to leave the system clean after
test.
There always can be a side effect which will impact other tests. And with
weak structure it will be intermittent. It's super hard to debug such cases

ср, 29 июл. 2020 г., 22:14 Steven Costiou <notifications@github.com>:

**Comment by StevenCostiou** [comment]
I will fix this in the next merge.

**Pull request merged**
