### PR TITLE
3802-make-code-completion-experiment-the-default-for-feedback

### PR DESCRIPTION
**Pull request by myroslavarm**
adding test completion as default

### CODE REVIEW

**Review by jecisc — CHANGES_REQUESTED** [review]
There is a merge conflict.

**Comment by myroslavarm** [comment]
@jecisc yes, i saw, should be fixed now

**Review by MarcusDenker — APPROVED** [review]
OK!

**Comment by astares** [comment]
@MarcusDenker 
@myroslavarm 
@pavel-krivanek 
@jecisc 

Can we please roll back this PR #3835 and better put the switch to the TestCompletionController into 
the method "BaselineOfIDE>>additionalInitialization" method which according to what I see is the place where such configuration setups are currently done.

So we would have them all on a single place....

**Comment by MarcusDenker** [comment]
this is just temporary anyway... and reverting would not change anything: the status before this change was that the Completion controller was registered using this method. Yes, can be improved, but that is another TODO.

**Pull request merged**
