### PR TITLE
5486-DictionaryUpdate

### PR DESCRIPTION
**Pull request by kasperosterbye**
Fixes issue #5486
This is a fix made for Pharo9.0 directly

### CODE REVIEW

**Comment by kasperosterbye** [comment]
@MarcusDenker - I think this PR at least is clean, despite it failing badly in the CI chain.

**Comment by MarcusDenker** [comment]
Yes, we somehow managed to break the boo trap (I added another issue tracker for that already)

**Comment by MarcusDenker** [comment]
Bootstrap is fixed, I close and reopen to run the latest code

**Review by MarcusDenker — APPROVED** [review]

**Comment by kasperosterbye** [comment]
Hmm, those two test succeed on my machine.

**Comment by MarcusDenker** [comment]
one ran into a time out (Process>>pvtSignal:list:). this is a side effect if the virtualised machine is too slow, I think.

The other is an odd failure that happens sometimes, I have not found out why. Maybe I will just delete the test.

**Pull request merged**
