### PR TITLE
Removed obsolete Fuel packages

### LINKED ISSUE #6016: Merge Fuel 3.0.2 in P9
Fuel 3.0.2 has been integrated in P8 and we should integrate it in P9
https://github.com/pharo-project/pharo/pull/5871

### PR DESCRIPTION
**Pull request by theseion**
Fixes #6016

### CODE REVIEW

**Comment by guillep** [comment]
I restarted the CI to recheck fast. But probably the bootstrap is trying to build/load those removed packages...

**Comment by theseion** [comment]
That would be weird... Are there other places in Bootstrap where the package are referenced?

**Comment by guillep** [comment]
Well, looking at the CI log, I see

```
Could not resolve: Fuel-Platform-Pharo-07 [Fuel-Platform-Pharo-07] in /builds/workspace/uest_and_branch_Pipeline_PR-6146/64/bootstrap-cache/pharo-local/package-cache tonel:///builds/workspace/uest_and_branch_Pipeline_PR-6146/64/src
```

and a quick code search yielded

```smalltalk
BaselineOfFuel >> baseline: spec 
    
	<baseline>
	
	spec package: 'Fuel-Core'.
	spec package: 'Fuel-Platform-Core'.
	spec package: 'Fuel-Platform-Pharo-Core'.
====>>>	spec package: 'Fuel-Platform-Pharo-07'. 
```

**Comment by theseion** [comment]
Thanks. I'll look into it.

**Comment by theseion** [comment]
Yeah, I effed up. Should be fixed now.

**Comment by Ducasse** [comment]
Thanks Max. 
I relanched the build because it was strange.

**Comment by theseion** [comment]
There's still something not right... I'll fix it.

**Comment by theseion** [comment]
There's something weird going on with `SystemDependencyTests`. In the other PR, the test didn't fail on the CI but locally, in this PR it doesn't fail locally but does on the CI... Well, I'll check again...

**Comment by theseion** [comment]
I don't get it. The test is green locally. Maybe it has something to do with the merge process??

**Comment by guillep** [comment]
Hi @theseion , the system dependency tests calculate the dependency information and cache it in a class instance variable I think. You may want to reset that?

**Comment by pavel-krivanek** [comment]
The SestemDependencies tests cache the computed information. Have you tried to reset `SystemDependenciesTest class>>#resetDependenciesReport`?

**Comment by theseion** [comment]
Yes, I know. I've reset the report before each run.

**Comment by theseion** [comment]
I've performed the CI build step for step on my machine and the test indeed fails locally when run from the command line. I'll have to find out where the difference is, because bootstrapping before didn't make the test fail...

**Comment by theseion** [comment]
Found it. There was an extension dependency from `GT-Debugger` that for some reason didn't show up when I ran bootstrap before. Maybe I had made mistake there.

**Comment by theseion** [comment]
Looks good.
The windows build failed and there's a stack trace in one other test (looks like a heisenbug) but everything related to this PR seems to be OK. Can someone restart the build?

**Comment by Ducasse** [comment]
Of course :)

**Comment by theseion** [comment]
Thanks Stef. That doesn't seem to have worked though.

**Comment by Ducasse** [comment]
Hi max I see that more than 44K tests run so it passed. no?

**Comment by theseion** [comment]
Yes :) I just figured we'd like to have a clean run. But yes, from my point of view the PR is good.

**Comment by Ducasse** [comment]
Argh now we have a conflict with Systemdependencies.
If I would know I would fix it now.

**Comment by theseion** [comment]
@Ducasse I don't see a test failure or conflict for SystemDependenciesTest. All the failures and failing tests seem unrelated to me.

**Comment by guillep** [comment]
This PR is dating a bit. I'll close. Reopen if needed.

**Pull request closed without merging**
