### PR TITLE
set again fluid to be enabled by default

### PR DESCRIPTION
**Pull request by MarcusDenker**
...  to check which tests fail

### CODE REVIEW

**Comment by jecisc** [comment]
The failing tests are the one in ChangeSetClassChangesTest and IIRC they are random failures

**Comment by Ducasse** [comment]
This strange that the package is not correct.

**Comment by Ducasse** [comment]
```
'Object << #ClassForTestToBeDeleted249  slots: {};  package: ''CategoryForTestToBeDeleted-TestPackage1''' instead of 'Object << #ClassForTestToBeDeleted249  slots: {};  package: ''TestPackage2'''.
```

**Comment by MarcusDenker** [comment]
Yes, this has to do with old class defintion printing the category, while fluid prints the package name. 

Maybe AbstractEnvironmentTestCase does something wrong, There is https://github.com/pharo-project/pharo/issues/13315

**Pull request closed without merging**
