### PR TITLE
Fix the preconditions related to packages in refactorings

### PR DESCRIPTION
**Pull request by jecisc**
This PR includes multiple cleanings in refacotrings related to packages.

- Use #hasPackage: instead of #includesPackage(Named): that will be deprecated
- Remove useless catch blocks that cannot be triggered
- Remove usage of validatePackageDoesNotExist: because this should be a private method of RPackageOrganizer and use #hasPackage: instead with a better error message
- Do not throw refactoring errors but use #errorString in the preconditions
- Use #packageOrganizer instead of `RPackage organizer` because the later will be deprecated soon 

There are still some things I am unsure about like the usage of #packageOrganizer because it will return the package organizer of the system. Maybe later we should access the packageOrganizer throught the environment? BUT! This should not change the current behavior so this is for a future change. (I'll probably not do it myself, or not before a long time sorry).

Another problem is that I think we have a duplication between RBRenamePackageRefactoring and RBRenamePackageTransformation. But I don't know how to fix that without reading more code of Refactorings and this is not in my current roadmap. Maybe @balsa-sarenac will know how to do that.

This depends on https://github.com/pharo-project/pharo/pull/14232. If you want to review this change before the PR is integrated, you can check the latest commit.

### CODE REVIEW

**Review by balsa-sarenac — APPROVED** [review]
Looks good to me.

Regarding duplication between rename transformations and refactoring that's something that we're actively working on. It's on our roadmap, so it'll be taken care of.

**Comment by Ducasse** [comment]
the following changes got broken

```
x-64 / Tests-osx-64 / testNotEnvironment – MacOSX64.Refactoring.Tests.Environment.RBBrowserEnvironmentTest
9s
osx-64 / Tests-osx-64 / testCopyPackageAndChangesCopyReferences(#rbClass->RBCopyPackageRefactoring) – MacOSX64.Refactoring2.Transformations.Tests.SingleParametrized.RBCopyPackageParametrizedTest
7s
osx-64 / Tests-osx-64 / testCopyPackageWithParameters(#rbClass->RBCopyPackageRefactoring) – MacOSX64.Refactoring2.Transformations.Tests.SingleParametrized.RBCopyPackageParametrizedTest
7s
osx-64 / Tests-osx-64 / testFailureExistingPackage(#rbClass->RBCopyPackageRefactoring) – MacOSX64.Refactoring2.Transformations.Tests.SingleParametrized.RBCopyPackageParametrizedTest
7s
osx-64 / Tests-osx-64 / testFailureExistingPackage(#rbClass->RBRenamePackageRefactoring) – MacOSX64.Refactoring2.Transformations.Tests.Parametrized.RBRenamePackageParametrizedTest
7s
osx-64 / Tests-osx-64 / testRenamePackage(#rbClass->RBRenamePackageRefactoring) – MacOSX64.Refactoring2.Transformations.Tests.Parametrized.RBRenamePackageParametrizedTest
7s
osx-64 / Tests-osx-64 / testFailureExistingPackage(#rbClass->RBRenamePackageTransformation) – MacOSX64.Refactoring2.Transformations.Tests.Parametrized.RBRenamePackageParametrizedTest
7s
osx-64 / Tests-osx-64 / testRenamePackage(#rbClass->RBRenamePackageTransformation) – MacOSX64.Refactoring2.Transformations.Tests.Parametrized.RBRenamePackageParametrizedTest
7s
unix-64 / Tests-unix-64 / testNotEnvironment – Unix64.Refactoring.Tests.Environment.RBBrowserEnvironmentTest
```

**Comment by jecisc** [comment]
I tried to fix them. I'll check what the CI says

**Comment by jecisc** [comment]
Failing test does not seems related (But I've never seen this one)

**Pull request merged**
