### PR TITLE
5275-Why-CharacterTable-in-Character-is-nil

### LINKED ISSUE #5275: [Cleanup] CharacterTable in Character -- Bootrap change needed
No idea...

### PR DESCRIPTION
**Pull request by MarcusDenker**
remove dead code from Character: CharacterTable class variable has just an accessor, which itself is never called. fixes #5275

### CODE REVIEW

**Comment by MarcusDenker** [comment]
interesting:


KeyNotFound: key #CharacterTable not found in EPRemoteDictionary
EPRemoteDictionary>>at:
PBImageBuilderSpur5032bit(PBImageBuilder50)>>createInitialObjects
PBImageBuilderSpur5032bit(PBImageBuilder50)>>bootstrap

**Comment by MarcusDenker** [comment]
I close this as it needs some change on the bootstrap level

**Comment by guillep** [comment]
Marcus, would you mind checking to fix the bootstrap?

**Comment by guillep** [comment]
I close this. It's ok if its not done :)

**Pull request closed without merging**
