### PR TITLE
[Backport] Fix for #3410-[Trait] Impossible to use from a classTrait a method that is also defined in a subclass of Behavior even when following the doc

### PR DESCRIPTION
**Pull request by VincentBlondeau**
add tests for issue
Fix previous failing test

### CODE REVIEW

**Comment by VincentBlondeau** [comment]
#3410

**Comment by MarcusDenker** [comment]
one failing test seems related:

Error
Subclasses of TestCase should have #tearDown methods in category running
Stacktrace
ProperMethodCategorizationTest(TestAsserter)>>assert:description:
ProperMethodCategorizationTest>>assureAll:areCategorizedIn:whenSubclassOf:
ProperMethodCategorizationTest>>testTearDownMethodInSUnitTestsNeedsToBeInRunningProtocol

**Comment by VincentBlondeau** [comment]
Fixed

**Comment by MarcusDenker** [comment]
The Pharo 8 change has been merged. We should wait some days to see if there are any bad side effects, if not we can merge this

**Review by MarcusDenker — APPROVED** [review]

**Comment by MarcusDenker** [comment]
We used it for some days: no problem.

**Comment by VincentBlondeau** [comment]
Thanks Marcus!

**Pull request merged**
