### PR TITLE
More debugger tests

### PR DESCRIPTION
**Pull request by dupriezt**
Solves issue #3025

### CODE REVIEW

**Comment by Ducasse** [comment]
This is cool to see all these tests! Thanks Thomas.
I could have review this PR but now I'm dropping out from the integrator team for lack of common vision.
Thanks for your time. Ask esteban to review and integrate PR.

**Comment by MarcusDenker** [comment]
It seems that 

ErrorWasInUIProcessTests>>testErrorWasInUIProcessIsTrueWhenDebugSessionWasCreatedByTheUIProcess

is still failing

**Comment by dupriezt** [comment]
I added a `SmalltalkImage current isHeadless` check to that test so that it does not run when the image is headless.
Judging by the CI result, it worked for Unix and Mac... but not for Windows????

**Comment by Ducasse** [comment]
Hi thomas this is cool. If a test is still failing we will do another PR for now this is cool to have more tests.

**Pull request merged**
