### PR TITLE
Merge NewTools 0.6

### LINKED ISSUE #161: No key/value view in the Inspector on a SmallDictionary
The Dictionary-like classes SmallDictionary and OrderedDictionary that are not subclasses of Dictionary need to implement the same inpector presentation.

### LINKED ISSUE #171: DNU when programmatically opening a StPlayground on some code
**How to reproduce**
Execute `StPlayground openContents: 'hello'` in a playground.
This should open a playgound on code 'hello', but it instead signals a DNU, because `StPlayground` does not understand `#content`
image

Pharo 9.0.0
Build information: Pharo-9.0.0+build.1106.sha.9afecccd243b4fae30fff90924e06746b2a186ee (64 Bit)

### LINKED ISSUE #176: Inspector pane on OrderedDictionary shows items as it is a simple Collection
It does not show the key-values nature of the collection.
It should be shown as a Dictionary preserving the order.

### LINKED ISSUE #8765: StInspector: Clicking on breakpoint raises a DNU transform:
```
removeBreakpointCommandFor: presenter
	| cmd |
	cmd := StRemoveBreakpointCommand forSpecContext: presenter.
	cmd iconName: #smallDelete.
	cmd decoratedCommand
		transform: [ :ctx | ctx methodsWithBreakpoints selection selectedItem ].
	^ cmd
```

I was browsing a FileSystem
and selected a PNG file, then click on the Breakpoint tab.

May be this is related with Object centric or a bug in Commander or in StInspector. 
No idea.

### PR DESCRIPTION
**Pull request by estebanlm**
NewTools 0.6
===

https://github.com/pharo-spec/NewTools/releases/tag/v0.6

- This version introduces new `Spotter` tool!
- uses style contributor (thanks @tesonep) to add styles for each tool (using it in spotter) 
- fixes cmd+p, and cmd+i, etc on playground.
- fixes https://github.com/pharo-spec/NewTools/issues/171 
- fixes https://github.com/pharo-project/pharo/issues/8765
- fixes https://github.com/pharo-spec/NewTools/issues/161
- fixes https://github.com/pharo-spec/NewTools/issues/176
- several debugger fixes
- cleanups 

Spec 0.8.6
===

https://github.com/pharo-spec/Spec/releases/tag/v0.8.6

- add cursorPositionIndex: to input fields
- add beEditable property to input fields

### CODE REVIEW

**Comment by estebanlm** [comment]
errors not related

**Comment by estebanlm** [comment]
but wait... I introduced a bug in toolbars

**Comment by estebanlm** [comment]
ok, errors not related and now I think it is ready :)

**Comment by Ducasse** [comment]
Nice :)

**Pull request merged**
