### PR TITLE
#11799 a nice little help method for converting integers into corresp…

### PR DESCRIPTION
**Pull request by Ducasse**
…onding file size.

### CODE REVIEW

**Comment by svenvc** [comment]
Note that there already is Integer>>#humanReadableSIByteSize

**Comment by Ducasse** [comment]
Now this is not the same

```
"(1000 * 1000 * 1000) humanReadableSIByteSize >>> '1.00 GB'"
"(1024 * 1024 * 1024) humanReadableSIByteSize '>>> 1.07 GB'"

"(1000 * 1000 * 1000) asFileSizeString >>> '953 MB'"
"(1024 * 1024 * 1024) asFileSizeString >>> '1 GB'"
```

So which one is correct.

**Comment by marcor** [comment]
First one is correct, second should read KiB, MiB, etc.

**Comment by svenvc** [comment]
Yeah, this is annoying and confusing. In standard SI terminology, the K, M, G are multiples of 1000, while in computer science they are sometimes multiples of 1024. And indeed, the KiB notation exists to make this clear, but not many really use this in practice, relying more on context.

**Comment by Ducasse** [comment]
So I do not really know what to do. Personally on my harddisc I want 1024 and not 1000 so we could have 

```
(1000 * 1000 * 1000) asFileSizeString
=> 
(1000 * 1000 * 1000) humanReadableByteSize
```
and I would not add the i because nobody will ever use that.

**Comment by Ducasse** [comment]
Now what I do not like about humanReadableByteSize and humanReadableSIByteSize is that it does not return a number so this is not a size but a string. This is why my original method was asFileSizeString.
I can rename humanReadableByteSize into humanReadableByteSizeString
and 
humanReadableSIByteSize into humanReadableSISizeString

**Comment by Ducasse** [comment]
Because I do not understand the byte part in humanReadableSIByteSizeString while I can understand it in humanReadableByteSizeString

**Comment by marcor** [comment]
SI is synonymous of "metric", I don't think it would be clear what "size" refers to. For comparison Cuis uses these method names:  printStringAsBytes and printStringAsBytesDecimal. Apparently in Pharo "humanReadable" is only used in 2 classes, Integer and Duration.

**Comment by Ducasse** [comment]
I should say that I'm neither fond of human readable nor print. I would prefer as...
Now the Cuis names are not that good either.

**Comment by marcor** [comment]
I'll throw asByteSizeString in the mix. :D

**Comment by Ducasse** [comment]
Ok so it would be asByteSizeString and asSIByteSizeString or asByteSizeString and asSISizeString.

**Comment by Ducasse** [comment]
Finally I let the methods as there are named. We can decide later.

**Pull request merged**
