### PR TITLE
22143-BaselineOfMorphicCore-has-too-many-dependencies

### PR DESCRIPTION
**Pull request by jecisc**
Move dependencies from BaselineOfMorphicCore to BaselineOfMorphic.

https://pharo.fogbugz.com/f/cases/22143/BaselineOfMorphicCore-has-too-many-dependencies

### CODE REVIEW

**Comment by jecisc** [comment]
I'll need to correct this conflict.

**Comment by estebanlm** [comment]
I'm still not happy with something like SUnit living on a baseline of Morphic (Core or not).

**Comment by pavel-krivanek** [comment]
```
[32] Starting atomic load*** EXCEPTION ***

[32] Error: This package depends on the following classes:
  PragmaMenuAndShortcutRegistration
  PluggableMenuSpec
  PluggableMenuItemSpec
  PragmaMenuBuilder
You must resolve these dependencies before you will be able to load these definitions: 
  PluggableMenuItemSpec>>#addToMenuGroupModel:
  PluggableMenuItemSpec>>#addToMenuItemModel:
  PluggableMenuItemSpec>>#asMenuItemMorphFrom:isLast:
  PluggableMenuItemSpec>>#morphClass
  PluggableMenuSpec>>#exampleWithOneSingleItem
  PluggableMenuSpec>>#exampleWithSubMenu
  PluggableMenuSpec>>#exampleWithTwoSimpleItems
  PluggableMenuSpec>>#addToMenuModel:
  PluggableMenuSpec>>#asMenuMorph
  PluggableMenuSpec>>#asMenuMorphOfKind:
  PluggableMenuSpec>>#asMenubarMenuMorph
  PluggableMenuSpec>>#buildWith:
  PluggableMenuSpec>>#morphClass
  PragmaMenuAndShortcutRegistration>>#attachShortcutCategory:to:
  PragmaMenuAndShortcutRegistration>>#setAsGlobalCategory:
  PragmaMenuBuilder>>#fallbackMenu
  PragmaMenuBuilder>>#menu
  PragmaMenuBuilder>>#menuAt:
  PragmaMenuBuilder>>#menuEntitled:
  PragmaMenuBuilder>>#menuFrom:
```

**Comment by jecisc** [comment]
I'll close it for now and go back at it in P8 development if I have the time.

**Pull request closed without merging**
