### PR TITLE
20592-SizeInMemory-is-not-updated-to-handle-32-and-64-bits-for-WordLayout

### PR DESCRIPTION
**Pull request by tesonep**
Fixing sizeInMemory to handle properly WordLayout objects.
Also fixing the tests to handle both 32 and 64 bits.

### CODE REVIEW

**Comment by astares** [comment]
typo  "a world per instance variable"

**Review by pavel-krivanek — APPROVED** [review]

**Comment by pavel-krivanek** [comment]
Pablo says we should postpone it because he wants check some Eliot's ideas

**Comment by tesonep** [comment]
I integrated the new implementation proposed by Eliot and it seems to work, the tests seems unrelated.

**Comment by Ducasse** [comment]
Made by Pablo :)

**Pull request merged**
