### PR TITLE
Add a RewriteRuleEditor and RewriteRuleChangesBrowser. First version:…

### PR DESCRIPTION
**Pull request by StephanEggermont**
… run over all packages

### CODE REVIEW

**Comment by StephanEggermont** [comment]
First step for #6397

**Comment by StephanEggermont** [comment]
The failing build looks weird

**Comment by StephanEggermont** [comment]
Ahem, does the rename refactoring work for SpPresenter subclasses?

**Comment by kasperosterbye** [comment]
Those tests (or some similar) failed for my PR (#6278) failed too.

**Pull request merged**
