### PR TITLE
5584-enabling-pharo9x-in-pharo90

### LINKED ISSUE #5584: enabling pharo9.x in pharo90
SmalltalkImage>>#metacelloPlatformAttributes

### PR DESCRIPTION
**Pull request by Ducasse**
Fixes: #5584 like that we can start differentiating 8.0 from 9.0!

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Build failure:

MetacelloNotification: Starting atomic load
Error: This package depends on the following classes:
  MessageBrowser
You must resolve these dependencies before you will be able to load these definitions: 
  MessageBrowser>>#example

MCMultiPackageLoader(Object)>>notify:
MCMultiPackageLoader(MCPackageLoader)>>warnAboutDependencies
MCMultiPackageLoader(MCPackageLoader)>>validate
MCMultiPackageLoader(MCPackageLoader)>>loadWithNameLike:
MCVersionLoader>>basicLoadWithNameLike:

**Comment by Ducasse** [comment]
What a shit.
We change one number and we get such kind of error.

**Comment by Ducasse** [comment]
I have NO idea why this is happening. 
I have no idea why the example on MessageBrowser would be impacted especially since it is ridiculously stupid

```
example
	self browseSendersOf: #flag:
```
How come this could be a dependency. 
The bug is somewhere else. :(

Now this change is blocking me so I will go an code in Pharo 80 since I cannot load the packages in Pharo 90. What

**Comment by Ducasse** [comment]
Pablo do you have an idea about this problem? 
Because we cannot express baselines for Pharo 9.0.

**Pull request merged**
