### PR TITLE
Rubric/Calypso improve menu entries (especially browse)

### PR DESCRIPTION
**Pull request by privat**
I just discovered why *Browse class* did behave so badly: it is a "do it" action that evaluates then browse the class, and not a navigation that statically resolves class names.

I'm very fine with this new acquired knowledge, but I blame the rubric menu to be so bad:

* "browse" in is the same submenu "code search..." with entries like "senders" and "source code with strings", instead of with other related doit actions (like "inspect it" for instance).
* The label is "Browse full class" that do not hint any kind of evaluation or doit action.

Because hacking compilers requires high quality hacking tools, this PR does the following:

* Move "browse it" with other "doit" action menu (I use the browser icon).
* Precise "Do &" in front of "doit" actions. This helps discoverability of tools.
* Add some menu entry for actions that have keybinding but no menu entries: diff & widen.
* Small fixes because they were easy to do.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
I do not like "browse it" to evaluate, to me there should be a real difference between *Navigation* and *Execution*

There are some issues open regarding this:

- "Browse it" evaluates code. Can lead to bad side effects #8515
- Meta issue for all problems around "Browse it" #10773

**Comment by privat** [comment]
I did not know about those issues, they seem political :)
Frankly, I do not care that much if "browse it" evaluates or not, what I do care is that the current menu is misleading. And that's what the PR is trying to fix.

**Comment by guillep** [comment]
Yes, I think that renaming the menu to "Do it and browse" is a good trade-off :)

**Review by MarcusDenker — APPROVED** [review]

**Comment by privat** [comment]
Tests are fine, except windows that... segfaulted this time. Oh, it's a new one.

```
Returning an object but pool is full./pharo: line 11:  3363 Segmentation fault      "$DIR"/"pharo-vm/PharoConsole.exe" --headless "$@"
```

**Comment by MarcusDenker** [comment]
yes, it is a good solution

**Pull request merged**
