### PR TITLE
Improve OCUndeclaredVariableWarning>>declareTempAndPaste

### PR DESCRIPTION
**Pull request by privat**
Low-hanging fruit. A small cleanup of declareTempAndPaste that reduces the hackish level a little

* reclassify and remove hack
* remove unused math (and a parameter)

### CODE REVIEW

**Comment by Ducasse** [comment]
Thanks for cleaning this prehistorical code (and it was not the original compiler but a "new one" but with left over of other hacks).

**Comment by MarcusDenker** [comment]
Yes, and the whole idea (to fix the code during exception handling) is just plain bad.

**Comment by estebanlm** [comment]
please do not submit more enhancements until we open P12 development.
right now, we are just accepting bugfixes.

**Comment by privat** [comment]
@estebanlm yes, it is intended pf P12. Unfortunately, I'm not able to set the pharo12 tag myself.

**Review by MarcusDenker — APPROVED** [review]

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
