### PR TITLE
22698-OSEnvironment-is-missing-setEnvvalue-method

### PR DESCRIPTION
**Pull request by jecisc**
Add missing abstract method to OSEnvironment

Fixes #22698

### CODE REVIEW

**Comment by jecisc** [comment]
https://pharo.fogbugz.com/f/cases/22698/OSEnvironment-is-missing-setEnv-value-method

**Review by akgrant43 — APPROVED** [review]
Approved, except they call the platform specific set environment routine, not getenv() (see the comment) :-)

**Comment by jecisc** [comment]
@akgrant43 Updated.

**Comment by akgrant43** [comment]
All good, thanks!

**Comment by guillep** [comment]
Hi, i don't think this is a good change. I'd deprecate all usages of getenv and setenv in favor of at and atput. See #1980

**Comment by jecisc** [comment]
Ok, I was not aware of how this class should be used. I only saw that the methods were on all subclasses but not the superclass.

**Pull request merged**
