### PR TITLE
Improve ClySystemEnvironment>>defineNewClassFrom

### PR DESCRIPTION
**Pull request by privat**
Low-hanging fruit. A small cleanup of ClyClassDefinitionEditorToolMorph that reduces the hackish level a little

* merge fuild and non-fluid
* reduce hackish level (a little) or error diagnosis

Note: review commit by commit because the global diff is trash

### CODE REVIEW

**Comment by Ducasse** [comment]
Thanks!

**Comment by Ducasse** [comment]
I read the code and yes having several class definitions is making things more complex. this is why I continue to remove the old class definition usage.

**Comment by estebanlm** [comment]
please do not submit more enhancements until we open P12 development.
right now, we are just accepting bugfixes.

**Comment by privat** [comment]
New dependency detected (IDE needs FluidClassBuilder). The dependency was implicit, but now the class name is explicit. I still think this is better that the previous hack anyway.

**Comment by Ducasse** [comment]
Sure this dependency is not a problem.

**Comment by Ducasse** [comment]
Sure esteban this is not for P11
I created a tag for 12.0.0

**Review by MarcusDenker — APPROVED** [review]

**Comment by privat** [comment]
@estebanlm Maybe this PR might interest the Pharo11 branch since it fixes the error reporting issue when having undeclared variables in the class definition pane of calypso (see blogpost).

**Pull request merged**
