### PR TITLE
Correct a typo in ZnDefaultServerDelegate class

### PR DESCRIPTION
**Pull request by SergeStinckwich**
Correct a typo artifical => artificial

### CODE REVIEW

**Comment by astares** [comment]
Need to be corrected in Zinc original repo from @svenvc too.

**Comment by SergeStinckwich** [comment]
> Need to be corrected in Zinc original repo from @svenvc too.

Already send a PR for that: https://github.com/svenvc/zinc/pull/28

**Review by jecisc — APPROVED** [review]

**Comment by jecisc** [comment]
Test failure not related.

**Comment by svenvc** [comment]
applied upstream

**Comment by astares** [comment]
@SergeStinckwich It's would alway to good to interlink the different issues so all can reproduce.

**Pull request merged**
