### PR TITLE
Mark abstract classes in Microdown package

### LINKED ISSUE #9175: Mark abstract classes in Microdown package
- a few classes are considered abstract (according to class comment) but return false for #isAbstract    
- so make this more explicit

### PR DESCRIPTION
**Pull request by astares**
Fix #9175

### CODE REVIEW

**Review by MarcusDenker — APPROVED** [review]

**Comment by Ducasse** [comment]
I do not like this pattern. 
We do not need it.

**Comment by Ducasse** [comment]
Can we wait a bit before integrating changes?
I do not want to have all our classes cripple with such stupid code.

**Comment by Ducasse** [comment]
I will revert because I will not integrate this code in Microdown and Pillar because we real discussion. 
Sorry to look harsh but soon someone will come with a rule and we will do super dull work. 
I prefer to spend my time fix the parser of class definition or bugs in microdow.

**Comment by astares** [comment]
???

**Pull request merged**
