### PR TITLE
2274 remove active pc and previous pc from debug session

### PR DESCRIPTION
**Pull request by dupriezt**
Solves #2274

### CODE REVIEW

**Comment by dupriezt** [comment]
No idea why there are 4 more commits from other people above mine. :-)

**Comment by Ducasse** [comment]
may be because you did not start from a clean branch.
I will ask the boss of iceberg to see what to do .

**Comment by Ducasse** [comment]
Thomas 

can you redo your fix because you are modifying 

 src/BaselineOfIDE/BaselineOfIDE.class.st
and it this is suspicious. 

Stef

**Comment by dupriezt** [comment]
I tried to rebase the branch to remove all the erroneous commits.
But it made it worse with even more erroneous commits.
So I deleted the branch and started a fresh one.
New pull request: #2653

**Pull request closed without merging**
