### PR TITLE
[Backport]3437-Adding-an-instance-class-variable-remove-the-traits-of-a-class

### LINKED ISSUE #3437: Add test for: Adding an instance class variable remove the traits of a class
If you have a class with traits and use #addClassSlot: on it (or #addSlot: on its instance), it will remove the traits of the class.

### PR DESCRIPTION
**Pull request by jecisc**
Backport fix in class slot addition.

Fixes #3437

### CODE REVIEW

**Comment by MarcusDenker** [comment]
you need to look at fillFor:, too... it was missing setting something in Pharo8

**Comment by jecisc** [comment]
Oh, ok. Just this already fix the problem we had, but maybe there is another one?

**Comment by MarcusDenker** [comment]
ah, the fix there might have been a side effect of removing copyClassSlotsFromExistingClass...

**Comment by jecisc** [comment]
So, what would be the clean solution? Do you have an idea?

**Comment by jecisc** [comment]
I reverted the change on fillFor: since it can cause problem.

**Review by MarcusDenker — APPROVED** [review]
Ok

**Comment by jecisc** [comment]
Faling tests are already failing for me in a clean image.

**Comment by MarcusDenker** [comment]
So do we merge this? It is for Pharo7

**Comment by jecisc** [comment]
@tesonep Is that Ok for you?

**Comment by MarcusDenker** [comment]
So what do we do?

**Comment by MarcusDenker** [comment]
If nobody objects, this will be merged end of the week.

**Comment by jecisc** [comment]
We can ask people to review during the sprint

**Comment by jecisc** [comment]
Oups, I closed it by accident because I cleaned my branched and this one had more than 1 month.

**Comment by MarcusDenker** [comment]
I finally merged it.

**Pull request merged**
