### PR TITLE
2590-We-can-get-two-times-the-mouseEntermouseLeave-event-when-subscribing-to-the-eventHandler-of-a-Morph

### LINKED ISSUE #2590: We can get two times the mouseEnter/mouseLeave event when subscribing to the eventHandler of a Morph
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/22705
Status: Work Needed
Project: Morphic
Original Author: CyrilFerlicot
Date: 28 November 2018 2:19:44 pm
	
Description:
	
StringMorph new
  contents: 'test;
  on: #mouseEnter send: #mouseEnter:from: to: self;
  on: #mouseLeave send: #mouseLeave:from: to: self;
  on: #click send: #mouseClick:from: to: self;
  yourself.

With this piece of code, if you add the methods to the class and log each time an event happens, you will see that we have two enter and leave event each time.

The problem comes from Morph>>handleMouseEnter/Leave:

### PR DESCRIPTION
**Pull request by jecisc**
Try to fix double event announcement.

I am not 100% sure but since we are in alpha of Pharo 8 maybe we can try it?

Fixes #2590

### CODE REVIEW

**Comment by jecisc** [comment]
I am waiting for reviews...

**Comment by jecisc** [comment]
Ping

**Review by guillep — CHANGES_REQUESTED** [review]
Any chances to write a test about it? Simulating an event shouldn't be too difficult.

**Comment by Ducasse** [comment]
I tried to follow the code but I failed to see it.

**Review by MarcusDenker — APPROVED** [review]
ok, lets try

**Pull request merged**
