### PR TITLE
Refactor: push down method driver

### PR DESCRIPTION
**Pull request by balsa-sarenac**
This PR finished migration of push down method driver to the new architecture.
Besides migration it includes:

- reified preconditions for push down method refactoring
- make API consistent by making all refactorings accept class names as input (instead of RBClass objects or real classes)
- minimal set of tests for push down method driver
- migrate push down method refactoring to new architecture!
- and since it's minimal difference, push down method in some classes is migrated as well

Hope this PR is not too big, it's hard to split these kind of things in smaller chunks.

This work is co-authored with @hernanmd

### CODE REVIEW

**Comment by Ducasse** [comment]
Thanks Balsa! It was great to work with you!

**Comment by Ducasse** [comment]
Else the PR looks good. 
Great job.

**Comment by balsa-sarenac** [comment]
Failing tests seem unrelated

**Comment by balsa-sarenac** [comment]
@Ducasse it was great to work with you as well. Looking forward to next time!

**Pull request merged**
