### PR TITLE
Fix serialization of classes with traits in hierarchy

### LINKED ISSUE #16345: Tonel export of class trait can be wrong
Since a few weeks/months in Pharo 12 it happens that the Tonel export of some code generates wrong class trait. It will be `#classTraits : '{} + TraitedClass'`. 

This prevents the code from loading afterward and is not easy to catch. 

This should be fixed before the release of P12.

### PR DESCRIPTION
**Pull request by PalumboN**
Try to fix https://github.com/pharo-project/pharo/issues/16345

Probably related to https://github.com/pharo-project/pharo/issues/16014 (TOCHECK)

image

### CODE REVIEW

**Comment by jecisc** [comment]
Some tests are failing now. For example: 

```
testRedefinedTraitedClassSubclassClassTraitCompositionIncludesTraitedMetaclass – Unix64.Traits.Tests.TraitSubclassingTraitedClassTest9s
Error
Got {} instead of {} + TraitedClass.
Stacktrace
TestFailure
Got {} instead of {} + TraitedClass.
TraitSubclassingTraitedClassTest(TestAsserter)>>assert:description:resumable:
TraitSubclassingTraitedClassTest(TestAsserter)>>assert:description:
TraitSubclassingTraitedClassTest(TestAsserter)>>assert:equals:
TraitSubclassingTraitedClassTest>>testRedefinedTraitedClassSubclassClassTraitCompositionIncludesTraitedMetaclass
TraitSubclassingTraitedClassTest(TestCase)>>performTest
```

**Comment by MarcusDenker** [comment]
I checked the build artefact: image size and .sources size look good with the fix applied

**Comment by estebanlm** [comment]
nice, I am checking the associated errors

**Comment by MarcusDenker** [comment]
There are tests failing with this PR:

```
 testRedefinedTraitedClassSubclassClassTraitCompositionIncludesTraitedMetaclass – Unix64.Traits.Tests.TraitSubclassingTraitedClassTest
 testRedefinedTraitedClassSubclassClassTraitCompositionIncludesTraitedMetaclassAPI2 – Unix64.Traits.Tests.TraitSubclassingTraitedClassTest
 testTraitedClassSubclassClassTraitCompositionIncludesTraitedMetaclass – Unix64.Traits.Tests.TraitSubclassingTraitedClassTest
 testMethodsAddedInMetaclassPresentInSubclassesAfterChangingSuperclass – Unix64.Traits.Tests.TraitTest
 testMethodsAddedInMetaclassPresentInSubclassesAfterRemovingSuperclass – Unix64.Traits.Tests.TraitTest
 testRemovingTraitsRemoveTraitedClassMethodsWithSubclasses – Unix64.Traits.Tests.TraitTest
```

**Comment by MarcusDenker** [comment]
Newer version: https://github.com/pharo-project/pharo/pull/16487

**Pull request closed without merging**
