### PR TITLE
Fix issue #5542: Unnecessary double checks of infinity

### PR DESCRIPTION
**Pull request by SergeStinckwich**
Remove unnecessary double checks of infinity in Float class

### CODE REVIEW

**Comment by MarcusDenker** [comment]
I close and reopen to run against the latest code base of Pharo9

**Review by MarcusDenker — APPROVED** [review]
i checked the code. The only reason why this might be problematic would be if the methods that now have the infinite check removed would be called directly. But it seems that this makes no sense.

So I think it is safe to merge

**Comment by SergeStinckwich** [comment]
Yes you are right.

In the comment, this is written: "Print my value on a stream in the given base.  Assumes that my value is strictly positive; negative numbers, zero, and NaNs have already been handled elsewhere."

Why we would consider infinite numbers differently?

Maybe comments should be update like : "Print my value on a stream in the given base.  Assumes that my value is strictly positive; negative numbers, zero, NaNs and infinite numbers have already been handled elsewhere."

**Comment by MarcusDenker** [comment]
I will merge an open a new issue to improve the comment!

**Comment by MarcusDenker** [comment]
I added https://github.com/pharo-project/pharo/issues/5723 to update the comment

**Pull request merged**
