### PR TITLE
Cleanup newlines and blanks in "OpalCompiler" packages

### LINKED ISSUE #10589: Cleanup newlines and blanks in "OpalCompiler" packages
see #10396 and fix it for all "OpalCompiler" related packages:

```Smalltalk
badCases := SystemNavigation default allMethodsSelect: [ :each | each sourceCode trimRight size ~= each sourceCode size ].

fixInPackage := badCases select: [:each | each package name beginsWith: 'OpalCompiler' ].

fixInPackage do: [:each |
	| refactoring classOrTrait |
	classOrTrait := each traitSource ifNil: [ each methodClass ] ifNotNil: [ each traitSource innerClass ].
	refactoring := RBAddMethodChange compile: each sourceCode trimRight in: classOrTrait for: nil.				 
	refactoring execute	
]
```

### PR DESCRIPTION
**Pull request by astares**
Fix #10589

### CODE REVIEW

**Comment by MarcusDenker** [comment]
- [CI] Failing randomly: Spec related tests with DNU SmallFloat64 >> #nextCell: #10522

**Comment by MarcusDenker** [comment]
There is now a conflict

**Comment by astares** [comment]
OK - I will redo a new PR. Looks easier.

**Comment by astares** [comment]
New PR is in https://github.com/pharo-project/pharo/pull/10618

**Pull request closed without merging**
