### PR TITLE
22583 Tag ManifestCollectionsStreams and related classes in Collections-Streams

### PR DESCRIPTION
**Pull request by astares**
https://pharo.fogbugz.com/f/cases/22583

### CODE REVIEW

**Comment by MarcusDenker** [comment]
we have some problem with the bootstrap now... maybe wait to make more PRs till that is solved
(because even if we fix it, the PRs will stay broken)

**Comment by astares** [comment]
@MarcusDenker Just tell me when it is possible to continue

**Comment by MarcusDenker** [comment]
So the fix is now merged. I will re-run this PR to see if it is checked with the lated code ... (but I think it is not).

**Comment by MarcusDenker** [comment]
hmm.. yes, the PR is tested regarding to the version is was created. That version is broken. So the tests for this PR are broken until the PR is changed to be towards the latest versio

**Pull request merged**
