### PR TITLE
Background failures log in CI

### PR DESCRIPTION
**Pull request by dionisiydk**
It refactors HDTestReport and subclasses to allow specific reporting logic for concrete exceptions. 
Exception classes can override method: 
```Smalltalk
recordResultOf: aTestCase inHDTestReport: aHDTestReport
```
to put own logic. And an extra method to allow reporting of background failures in a special way:
```Smalltalk
recordBackgroundFailureOf: aTestCase inHDTestReport: aHDTestReport
```

TestFailedByForkedProcesses uses this mechanizm to report all background failures during the test.
For example following test:
```Smalltalk
testForCIWithOnlyBackgroundError
	[self error: 'backgroundErrorFromAnnouncerTest'] fork. 
```
will be reported as an error with a stack of background failure: (Jenkins xml)
```xml
<testcase classname="MacOSX64.JenkinsTools.Core.HDReportWithBrokenTestsExample" name="testForCIWithOnlyBackgroundError" time="0.002">
	<error type="Error" message="backgroundErrorFromAnnouncerTest">
Error
backgroundErrorFromAnnouncerTest
HDReportWithBrokenTestsExample(Object)>>error:
[self error: 'backgroundErrorFromAnnouncerTest'] in HDReportWithBrokenTestsExample>>testForCIWithOnlyBackgroundError
...
	</error>
</testcase>
```

And for multiple errors like in main test process and forked process there will be multiple error/failure nodes. For example following test:
```Smalltalk
testForCIWithMainAndBackgroundErrors
	[self error: 'backgroundErrorFromAnnouncerTest2'] fork. 

	self error: 'mainErrorFromTestWithBackgroundError'
```
will produce following Jenkins xml:
```xml
<testcase classname="MacOSX64.JenkinsTools.Core.HDReportWithBrokenTestsExample" name="testForCIWithMainAndBackgroundErrors" time="0.006">
	<error type="Error" message="mainErrorFromTestWithBackgroundError">
Error
mainErrorFromTestWithBackgroundError
HDReportWithBrokenTestsExample(Object)>>error:
HDReportWithBrokenTestsExample>>testForCIWithMainAndBackgroundErrors
HDReportWithBrokenTestsExample(TestCase)>>performTest
	</error>
	<error type="Error" message="backgroundErrorFromAnnouncerTest2">
Error
backgroundErrorFromAnnouncerTest2
HDReportWithBrokenTestsExample(Object)>>error:
[self error: 'backgroundErrorFromAnnouncerTest2'] in HDReportWithBrokenTestsExample>>testForCIWithMainAndBackgroundErrors
...
	</error>
</testcase>
```
Notice that Jenkins web UI shows the only error (the first error node). 

Subclasses of HDTestReport are also adjusted to support this logic. It is CommandLineTestRunner and VTermTestRunner. They were refactored to remove code duplication.

### CODE REVIEW

**Comment by dionisiydk** [comment]
I attached file with example tests with background errors. You can load it and check the report after test run:
```Smalltalk
HDTestReport currentStageName: (FileLocator imageDirectory / 'BadTests').
report := HDTestReport new.
report progressFileName: (FileLocator imageDirectory / 'progress.log') pathString.
report runSuite: HDReportWithBrokenTestsExample buildSuite.
```
[HDReportWithBrokenTestsExample.st.zip](https://github.com/pharo-project/pharo/files/5252795/HDReportWithBrokenTestsExample.st.zip)

**Comment by dionisiydk** [comment]
Nobody?

**Review by noha — APPROVED** [review]

**Comment by noha** [comment]
Looks good to me!

**Comment by dionisiydk** [comment]
great

**Pull request merged**
