### PR TITLE
added a comparisson to KeyboardKey

### PR DESCRIPTION
**Pull request by estebanlm**
because otherway `Character down alt` = `Character down alt` gives false (since they are not the same object).

### CODE REVIEW

**Comment by Ducasse** [comment]
Esteban please add tests!

**Comment by Ducasse** [comment]
We should not integrate a change like this without tests. Sorry but we should eat our own dog food and I'm sure you agree.

**Comment by estebanlm** [comment]
well, I can argue that I was fixing a problem that emerged because of something that *was* integrated without tests :)
But anyway, test it there.

**Comment by estebanlm** [comment]
Still, this problem was shown after a fuel materialization that included a KeyboardKey. 
Maybe there is a problem in fuel, not in `KeyboardKey` (since KeyboardKey is more like a flyweight?)

**Comment by guillep** [comment]
Keyboard Key is a flyweight and there are tests for equality, so the problem may be elsewhere

**Comment by MarcusDenker** [comment]
should this be merged?

**Comment by estebanlm** [comment]
nah (even if I do not think it would hurt)

**Comment by estebanlm** [comment]
in fact, I will insist with this, since we have some entries like this: 
```Smalltalk
KeyboardKey class>>valueForUnixPlatform: aKeyValue

	^self unixVirtualKeyTable at: aKeyValue ifAbsent: [ (self basicNew withValue: aKeyValue) ] 
```
and then, comparison redefinition has sense (even if fuel needs to be adapted to use the flyweight).

**Comment by guillep** [comment]
> in fact, I will insist with this, since we have some entries like this:
> 
> ```smalltalk
> KeyboardKey class>>valueForUnixPlatform: aKeyValue
> 
> 	^self unixVirtualKeyTable at: aKeyValue ifAbsent: [ (self basicNew withValue: aKeyValue) ] 
> ```
> 
> and then, comparison redefinition has sense (even if fuel needs to be adapted to use the flyweight).

Then in this case yes, it could make sense to add a couple of equality tests for cases of keys created outside the flyweight

**Comment by estebanlm** [comment]
bump? 
@MarcusDenker, @guillep ?

**Comment by guillep** [comment]
We need the equality test.

**Comment by estebanlm** [comment]
it is there: 
```Smalltalk
KeyboardKeyTest >> testEqual [ 

	self 
		assert: (KeyboardKey fromCharacter: Character arrowUp) 
		equals: (KeyboardKey new 
			withValue: 65362;
			yourself)
]
```

**Comment by estebanlm** [comment]
re-bump ?
@MarcusDenker, @guillep ?

**Review by MarcusDenker — APPROVED** [review]

**Comment by guillep** [comment]
Sorry, did not see it!

**Pull request merged**
