### PR TITLE
ReNotOptimizedIfRule

### PR DESCRIPTION
**Pull request by MarcusDenker**
First step of a Rule that warns if you use ifTrue: ifFalse: ifTrue:ifFalse: ifFalse:ifTrue:  in a way that it can not be optimized.

- need a test
- need to run it on the whole image to see if we get any false positives

### CODE REVIEW

**Comment by guillep** [comment]
We were just discussing with Pablo:
- since it should hold that x == x value, particularly for blocks
- And that the message send to ifTrue:ifFalse: will send `value` to the argument
- then the compiler could transform automatically `condition ifTrue: […] ifFalse: x` into `condition ifTrue: […] ifFalse: [ x value ]`

And we get the best of both worlds, right?
We write it nicely, and it avoids always the slow path.

We will work on that in the sprint :)

**Comment by MarcusDenker** [comment]
That sounds great!

**Comment by MarcusDenker** [comment]
I am 100% in agreement with Guille that this should be done automatically. 

I propose we add rules just until this is done. (ifTrue: is just one, there are more like and:, to:do: ...).

As soon as the system is then good enough to do these automatically, we remove the rule.

**Comment by astares** [comment]
Great!

**Pull request merged**
