### PR TITLE
Cleanup: Usage of "notNil" and "isEmpty not" in Zinc / Zodiac

### LINKED ISSUE #15251: Cleanup: Usage of "notNil" and "isEmpty not" in Zinc / Zodiac
- also in Zinc we have lots of senders of #notNil which should be using #isNotNil

```Smalltalk
(SystemNavigation default allSendersOf: #notNil)
	select: [:each | each package name beginsWith: 'Zinc-' ]
```	

- we also have many "isEmpty not" expressions we can convert into #isNotEmpty sends
  (for example ZnUrl>>#hasQuery)

- in ZnStaticFileServerDelegate>>#handleRequest: we can even use #ifNotNil:ifNil:
- we can also simplify ZnUrl>>#hasPath with #isNotEmpty

### PR DESCRIPTION
**Pull request by astares**
Fix #15251

### CODE REVIEW

**Comment by jecisc** [comment]
@svenvc is that ok for you?

**Comment by astares** [comment]
@jecisc / @svenvc 

To make it easier for @svenvc to get equal changes also into the original repo of Zinc I provided a PR there too.
See https://github.com/svenvc/zinc/pull/128

**Comment by astares** [comment]
Unrelated CI problem:

*** Warning: Deprecation: The method ShiftClassBuilder>>#category: called from Trait class>>#named:instanceVariableNames:package: has been deprecated. Trying to package a class using the concept of categpry is not supported anymore in Pharo. You can use #package: and #tag: instead to avoid any ambiguity on what part of the category is the package and what is the tag.

**Comment by astares** [comment]
image

**Comment by astares** [comment]
image

Still a CI problem. There is only one platform green at a time (last time it was unix, now mac).

Also Zinc Tests are green when loaded into image

**Comment by astares** [comment]
Now again unrelated CI issue

image

**Comment by astares** [comment]
Last CI run failed again with 

"PrimitiveFailed: primitive #primFreeDefinition in TFFunctionDefinition failed"

If I'm not mistaken CI is using different/newer VM (always or sometimes) and this seem to cause it.

@guillep, @MarcusDenker, @jecisc  any help appreciated as this is already merged into Zinc I dont want to wait too long until this is merged in

**Comment by jecisc** [comment]
If this is merged in Zinc, we can merge it too here.

The problem is not related to the VM but is general in Pharo and Pablo is currently working to fix it. We'll merge this one once this is fixed and we see it passes the CI

**Comment by astares** [comment]
@jecisc Thanks for the feedback. Highly appreciated!

**Pull request merged**
