### PR TITLE
21820-Simplify-OpalCompilerevaluate-move-requester-related-code-

### PR DESCRIPTION
**Pull request by MarcusDenker**
Simplify OpalCompiler>>#evaluate: move requester related code
  https://pharo.fogbugz.com/f/cases/21820/Simplify-OpalCompiler-evaluate-move-requester-related-code

### CODE REVIEW

**Comment by MarcusDenker** [comment]
I do not understand. Every time I try to do this change I get conflicts.

**Comment by jecisc** [comment]
Do you start from a synched dev branch?

Did you try to merge manually on your computer (externally to Pharo) to see what is the problem?

**Comment by MarcusDenker** [comment]
I 

- downloaded a fresh image
- cloned a fresh repo
- created a new new branch ("backstop", as I wanted to do more than one small OR)
- created branch for the issue
- did my changed
- commit, push 
- Pull request

**Comment by MarcusDenker** [comment]
maybe I should delete my fork on GitHub and do a new one.

**Comment by MarcusDenker** [comment]
something is really odd. I did it *again* and now I get a message "your repository is out of sync with the remote origin"  when I try to push (the MarcusDenker one). 
But how can that be? I started with cloning that.

**Pull request closed without merging**
