### PR TITLE
[improvement] add deprecation + transform to bytecode -> bytecodes

### PR DESCRIPTION
**Pull request by hogoww**
As requested in #11488 deprecation + usage of bytecode

### CODE REVIEW

**Comment by Ducasse** [comment]
I do not get why the build is failing

**Comment by Ducasse** [comment]
:(
```
MetacelloNotification: ...finished baseline
IceGitHubError: API rate limit exceeded for 128.93.193.1. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

**Comment by astares** [comment]
https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting

CI seems to fail to authenticate and is then limited on the number of GitHub API calls. Maybe a token is expired?

<blockquote><div> GitHub Docs</div><div><strong><a href="https://ghdocs-prod.azurewebsites.net/en/rest/overview/resources-in-the-rest-api">Resources in the REST API - GitHub Docs</a></strong></div><div>Learn how to navigate the resources provided by the GitHub API.</div></blockquote>

**Comment by hogoww** [comment]
Restart CI, see if that was indeed just this

**Comment by Ducasse** [comment]
Nope :(

**Pull request merged**
