### PR TITLE
20220-Speedup bootstrap process by caching VM maker loading

### PR DESCRIPTION
**Pull request by guillep**
Please wait until PR https://github.com/pharo-project/pharo/pull/157 is integrated. Like that, this PR will be validated by Jenkins.

### CODE REVIEW

**Comment by guillep** [comment]
Issue https://pharo.fogbugz.com/f/cases/20220/Speedup-bootstrap-process-by-caching-VM-maker-loading

**Comment by guillep** [comment]
run tests

**Review by gcotelli — COMMENTED** [review]
According to Shellcheck ( www.shellcheck.net) the bash script can be improved:

Line 12:
__base="$(basename ${__file} .sh)"
^-- SC2034: __base appears unused. Verify it or export it.
                   ^-- SC2086: Double quote to prevent globbing and word splitting.
 
Line 20:
./pharo Pharo.image ${__dir}/prepare_image.st --save --quit
                    ^-- SC2086: Double quote to prevent globbing and word splitting.
 
Line 22:
./pharo Pharo.image ${__dir}/bootstrap.st --ARCH=${BOOTSTRAP_ARCH} --quit
                    ^-- SC2086: Double quote to prevent globbing and word splitting.
                                                 ^-- SC2086: Double quote to prevent globbing and word splitting.
 
Line 23:
bash ${__dir}/build.sh
     ^-- SC2086: Double quote to prevent globbing and word splitting.

**Comment by guillep** [comment]
Already fixed in #177

**Pull request closed without merging**
