### PR TITLE
21886-Unload-Compiler-Tests-package

### PR DESCRIPTION
**Pull request by MarcusDenker**
Unload Compiler-Tests package
https://pharo.fogbugz.com/f/cases/21886/Unload-Compiler-Tests-package

### CODE REVIEW

**Comment by astares** [comment]
Why do we unload them?

**Comment by jecisc** [comment]
OpalCompiler is a replacement to Compiler. Compiler should be unloaded before P7 release.

**Comment by astares** [comment]
Could we reuse some of the tests?

**Comment by MarcusDenker** [comment]
No, it is just a test of a private class.

**Comment by MarcusDenker** [comment]
Just tests LiteralDictionary (the new compiler uses another private collection for that, a LiteralList).

**Pull request merged**
