### PR TITLE
Do not select the # in symbol selection

### PR DESCRIPTION
**Pull request by jecisc**
See discussion in: https://github.com/pharo-project/pharo/issues/14916

### CODE REVIEW

**Comment by Ducasse** [comment]
tx :)

**Comment by estebanlm** [comment]
this is not the same as #14916 ?

**Comment by jecisc** [comment]
This is what we discussed to do before the P12 release in this issue.

**Review by MarcusDenker — APPROVED** [review]

**Comment by estebanlm** [comment]
I know, so I can close also the other one?
EDIT: I see the real fix is for P13, better like that :)

**Pull request merged**
