### PR TITLE
22441 Tag and comment Manifests in all System packages

### PR DESCRIPTION
**Pull request by astares**
https://pharo.fogbugz.com/f/cases/22441/Tag-and-comment-Manifests-in-all-System-packages

ManifestSystemAnnouncements
ManifestSystemBasicCommandLineHandler
ManifestSystemCommandLine
ManifestSystemCommandLineHandler
ManifestSystemFinalization
ManifestSystemHashing
ManifestSystemSupport
ManifestSystemModel
ManifestSystemFileRegistry

tag and comment to structure related packages

ONLY TAGGING OF CLASSES AND COMMENTS, NO CHANGE IN BEHAVIOR
SHOULD BE SAFE TO INTEGRATE

### CODE REVIEW

**Comment by astares** [comment]
PLEASE IGNORE THIS PR FOR THE TIME BEING

I WILL PROVIDE SMALLER PR's

**Comment by guillep** [comment]
Hi @astares should we then close this PR?

**Comment by astares** [comment]
Yes

**Comment by astares** [comment]
This was split into other issues / PR's (see https://pharo.fogbugz.com/f/cases/22436/ for details)

**Pull request closed without merging**
