### PR TITLE
Integrating full block closure and fixing for make them work in the image

### PR DESCRIPTION
**Pull request by tesonep**
We have to activate the support and make the corresponding changes in the image. 
Building in the CI to check for the broken tests.

### CODE REVIEW

**Comment by Ducasse** [comment]
FBDExamples>>exampleWhileTrue3 (tmp1 is Undeclared) 
Syntax Error on line 6: 'Variable or expression expected'
=========================================================
1: MetaLink new
2: 	metaObject: nil;
3: 	selector: #value;
4: 	arguments: #();
5: 	control: #before;
6: 	condition: ![CompiledBlock>>hasSourceCode]!;

Then we get also The method RBMethodNode>>#tempNames called from CompiledMethod>>#tempNames has been deprecated.

**Comment by Ducasse** [comment]
None of the builds run so I restarted it.

**Comment by Ducasse** [comment]
I relaunched the build because none of the builds were  working.

**Comment by tesonep** [comment]
Keeping the PR alive.

**Comment by jecisc** [comment]
Error detected by Stephane is still present.

**Pull request closed without merging**
