### PR TITLE
removeBalloonCanvas

### PR DESCRIPTION
**Pull request by pavel-krivanek**
an experiment to remove BalloonCanvas (unify it with the FormCanvas) to obtain cleaner Canvas API.

(seems to work already)

### CODE REVIEW

**Comment by Ducasse** [comment]
Excellent. Now just a question do you think that Pharo can work only with athens/cairo?

**Comment by pavel-krivanek** [comment]
I hope so, that's why I want to make the Canvas API more transparent... and experiment with DPI independency

**Comment by Ducasse** [comment]
This is great. 
I see that sometimes we have sent to undefined methods :(
I do not get why we do not run the lint rules. I will try to relaunch this idea and process.

**Comment by pavel-krivanek** [comment]
single test failure - not related

**Review by tesonep — APPROVED** [review]

**Pull request merged**
