### PR TITLE
Fix #9136 - inconsistent handling of exception return

### LINKED ISSUE #9136: Inconsistent explicit and implicit exception return
Exception `return` should be handled the same whether it's called explicitly or not: The last line should send return: value to the exception instead of self - the exception return calls handlerContext return and although at the moment it's true the self is the handlerContext, in theory someone can e.g. change `return` definition and then the two returns won't be the same... Plus I think this is more consistent and readable. Thanks,
```
evaluateSignal: exception
	"The following primitive is just a marker used to find the evaluation context. 
	See MethodContext>>#isHandlerOrSignalingContext. "

	<primitive: 199>
	<debuggerCompleteToSender>
	| value |
	exception privHandlerContext: self contextTag.
	value := self exceptionHandlerBlock cull: exception.	
	"default return if not otherwise directed in handle block"
-	self return: value
+	exception return: value
```

### PR DESCRIPTION
**Pull request by isCzech**
Fixes #9136

### CODE REVIEW

**Review by dionisiydk — APPROVED** [review]

**Comment by isCzech** [comment]
Hi,
Apologies, I changed my mind: the two kinds of return as in
```
[] on: Error do: [:ex | ex return]
```
and
```
[] on: Error do: []
```
really are two distinct operations (and probably should remain as such). They are equivalent in Pharo thanks to their current implementation. I'm closing the PR.

**Comment by dionisiydk** [comment]
Hi @isCzech 

I am more convinced with your example that your proposal is correct.
Imagine that #return: is redefined for some exception class. Then the version with "ex return" will works differently than with simple block result. So they are not equivalent with the current implementation

**Comment by isCzech** [comment]
Thanks @dionisiydk for your feedback, I've done some more testing and realized there will be a problem with Exception>> #outer - I'll come up with a test showing it later - so the "fix" probably wouldn't be as simple as I suggested. Besides, as Stephane writes in Deep into Pharo (2013, p. 278), ANSI is not clear regarding the potential difference - or equivalence - between the two. What happened is I'd experimented with a modification of #return and realized the implicit return (or abandon as it's referred to in Deep Into Pharo) will become different from #return :)

**Comment by isCzech** [comment]
Hi @dionisiydk , you were right, my bad - I got confused and the suggested modification works well with #outer. I'm reopening the PR for your consideration :) Sorry for the confusion. Thanks

**Review by dionisiydk — APPROVED** [review]

**Comment by Ducasse** [comment]
I suggest that we keep this one for Pharo 10 because we really want to make sure that we do not have changes that can shake to o much the system. Pharo 90 should have been out in April. :(

**Comment by guillep** [comment]
Hi all, it's been really difficult to review the batch of issues (#8567 , #8845, #9137, #8993, #8509).
We have spent in the last internal sprints several hours taking a look at them, but it is a reality that those changes are difficult to review, some like #8567 are very big, their effects in the system are difficult to foresee independently and even worse in combination.

@tesonep is correctly (!!) proposing to my ear that we make a single PR joining all of them to reduce the merge noise, let the CI test the combination of all issues. I then propose that we eagerly merge this (meta) PR and be ready to quickly apply hot-fixes as soon as possible or revert it in case of fire.

Thoughts? @dionisiydk @Ducasse @isCzech @estebanlm

**Comment by guillep** [comment]
Superseeded by https://github.com/pharo-project/pharo/pull/10429

**Pull request closed without merging**
