### PR TITLE
Backport scale 2.0 icons support to Pharo 11

### PR DESCRIPTION
**Pull request by Rinzwind**
This pull request backports the support for scale 2.0 icons from earlier pull requests to Pharo 11.

One small change had to be made: `#magnifyBy:smoothing:` in `UITheme>>#newTreeForm:size:color:` was replaced by `#magnify:by:smoothing:`.

### CODE REVIEW

**Comment by Ducasse** [comment]
BTW I had the impression that we have some regressions with your changes in P12 like large buttons.
Did you experience something like that?

**Comment by Rinzwind** [comment]
Do you mean something like the tabs which are too large on the first screenshot in [Spec pull request #1397](https://github.com/pharo-spec/Spec/pull/1397)?

**Comment by jecisc** [comment]
This seems good to me. 

But for backport I prefer to wait for other opinion to know if we backport it or not :)

**Comment by Rinzwind** [comment]
Thanks! Could one of you maybe take a look at merging [Spec pull request #1429](https://github.com/pharo-spec/Spec/pull/1429) for Pharo 11 as well?

**Pull request merged**
