### PR TITLE
22669-UFFI-structures-are-not-recalculated-on-system-startup

### PR DESCRIPTION
**Pull request by guillep**
Reset should compile fields, because the compiledSpec field is not then lazily initialized by the instance side.

Issue: https://pharo.fogbugz.com/f/cases/22669/UFFI-structures-are-not-recalculated-on-system-startup

### CODE REVIEW

**Comment by guillep** [comment]
Running some benchmarks it seems this would have an impact on startup of ~30 milliseconds.

```
([ FFIExternalStructure allSubclassesDo: [:e | e reset].  ] benchFor: 5 seconds) period asMilliSeconds.
  => "30"
```

**Comment by dionisiydk** [comment]
Do we have a way to detect platform change on startup?
Then we can have very cheap flag to avoid this calculation for most of the
cases.

вт, 13 нояб. 2018 г. в 17:23, Guille Polito <notifications@github.com>:

**Comment by jecisc** [comment]
Test failure from the CI: windows-32 / Tests-windows-32 / testNestedStructure – Windows32.UnifiedFFI.Tests.Tests.FFIExternalStructureTests

**Comment by guillep** [comment]
Latest commit add support for rebuilding nested structures (what was causing the test failure on windows) and rebuilding only happens if platform changes.

**Review by estebanlm — APPROVED** [review]

**Pull request merged**
