### PR TITLE
Full sync from Zinc repository

### LINKED ISSUE #11028: Zinc-Resource-Meta-Core dirty package
In a fresh Pharo image connected to "Pharo10" branch the "Zinc-Resource-Meta-Core" package is dirty:

image

Maybe related to being out of synch between image and source for the following changes:

image

### PR DESCRIPTION
**Pull request by demarey**

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Problem: ZnServerTest>>usingClassicSocketStreamsOnWindowsDo: times out. This PR changes the test to use it.. thus introducing a problem.

(this is why I do not like those "let's batch all changes and merge just before the release" way of working... any change has the possibility to introduce a problem...)

**Comment by demarey** [comment]
is not mandatory to merge it for Pharo 10.
Let's postpone it for Pharo 11.

**Comment by svenvc** [comment]
I would strongly prefer to finish the merging of Zinc now, while we are fresh at it.

There is no general problem with #usingClassicSocketStreamsOnWindowsDo: just with one new test, #testTooManyConcurrentConnections

It was an attempt to fix that test on Windows (it works on macOS and linux).

We could also skip the test on Windows, as Christophe first suggested.

**Comment by MarcusDenker** [comment]
Tests now look good!

**Comment by svenvc** [comment]
Is this already in Pharo 10 ?
Can it be merged ?

**Comment by demarey** [comment]
Yes, Marcus integrated it already: https://github.com/pharo-project/pharo/commit/41ac2656d44e33f756901ecb815b1587f0f83795

**Comment by svenvc** [comment]
OK thank you !

**Pull request merged**
