### PR TITLE
2586 deleting a class with references gives extra do you want to delete anyway msg

### LINKED ISSUE #2586: Deleting a class with references gives extra "Do you want to delete anyway" msg
When you delete a class that has references to it - Pharo helpfully asks you if you want to view the references (which is cool) - if you answer No - you get a superfluous extra question "Do you want to remove anyway?".  This is annoying as if you say yes - you then get the refactoring window that shows you the removal which you can also accept and cancel. Thus you don't need that extra question as you can still cancel.

### PR DESCRIPTION
**Pull request by gcorriga**
Streamline the behaviour of the browser when removing classes, avoiding raising multiple dialogs.

The new behaviour is as follows:

if the class has no references, subclasses, or users, perform a refactoring to remove the class
if the class has references or users, ask the user what to do - browse the references/users, or do nothing.
if the class has subclasses, ask the user what to do - delete keeping subclasses, browse the subclasses, or do nothing.
As part of this change, remove the menu item to remove a class keeping subclasses since its behaviour is now integrate in the standard remove workflow.

Fixes #2586.
New version of #8297, #8305.

### CODE REVIEW

**Comment by Ducasse** [comment]
I wanted to merge it in my image and I got an improper store (after I review the code looks nice to me).

**Comment by Ducasse** [comment]
```
initializeWithName: nameString
superclassName: superclassString
traitComposition: traitCompositionString
classTraitComposition: classTraitCompositionString
category: categoryString 
instVarNames: ivarArray
classVarNames: cvarArray
poolDictionaryNames: poolArray
classInstVarNames: civarArray
type: typeSymbol
comment: commentString
commentStamp: stampStringOrNil
	name := nameString asSymbol.
	superclassName := superclassString ifNil: ['nil'] ifNotNil: [superclassString asSymbol].
	traitComposition := traitCompositionString.
	classTraitComposition := classTraitCompositionString.
	category := categoryString.
	name = #CompiledMethod ifTrue: [type := #compiledMethod] ifFalse: [type := typeSymbol].
	comment := commentString withInternalLineEndings.
	commentStamp := stampStringOrNil ifNil: [self defaultCommentStamp].
	variables := OrderedCollection  new.
	self addVariables: ivarArray ofType: MCInstanceVariableDefinition.
```

**Comment by Ducasse** [comment]
ivarArray is holding 'encoder' instead of an array!

**Comment by Ducasse** [comment]
I do not understand why it is breaking on my image so I restarted to the build.

**Comment by Ducasse** [comment]
So I'm in a funny situation since I cannot load the code to test the behavior. 
I will integrate it and we will see.

**Comment by MarcusDenker** [comment]
You can download the CI build image instead. This can be faster than loading

**Pull request merged**
