### PR TITLE
11544 enhance socket to show meaningful errors

### PR DESCRIPTION
**Pull request by carolahp**
Getting error message from ffi call and exposing it inside a Pharo Error

### CODE REVIEW

**Comment by Ducasse** [comment]
The build does not work at all.

**Comment by Ducasse** [comment]
May be should introduce first SocketError?

**Comment by MarcusDenker** [comment]
I think the build was broken due to https://github.com/pharo-project/pharo/pull/11922, I merged it and started a new build with that fix merged

**Comment by MarcusDenker** [comment]
Ah, now we get a real error message: full image build fails with:

```
+ echo '[Compiler] Initializing the packages in the Kernel'
[Compiler] Initializing the packages in the Kernel
+ /builds/workspace/est_and_branch_Pipeline_PR-11921/64/bootstrap-downloads/vmtarget/pharo --headless Pharo11.0-PR-compiler-64bit-92ccdb3.image --no-default-preferences initializePackages --protocols=protocolsKernel.txt --packages=packagesKernel.txt --save
Error: Could not found class: 'Socket' for selector: #socketErrorMessage
InitializePackagesCommandLineHandler(Object)>>error:
[] in InitializePackagesCommandLineHandler>>initializeProtocolsFrom: in Block: []
[] in File>>readStreamDo: in Block: []
FullBlockClosure(BlockClosure)>>ensure:
File>>readStreamDo:
InitializePackagesCommandLineHandler>>initializeProtocolsFrom:
InitializePackagesCommandLineHandler>>activate
InitializePackagesCommandLineHandler class(CommandLineHandler class)>>activateWith:
[] in PharoCommandLineHandler(BasicCommandLineHandler)>>activateSubCommand: in Block: []
FullBlockClosure(BlockClosure)>>on:do:
PharoCommandLineHandler(BasicCommandLineHandler)>>activateSubCommand:
PharoCommandLineHandler(BasicCommandLineHandler)>>handleSubcommand
PharoCommandLineHandler(BasicCommandLineHandler)>>handleArgument:
[] in [] in PharoCommandLineHandler(BasicCommandLineHandler)>>activate in Block: []
FullBlockClosure(BlockClosure)>>on:do:
[] in PharoCommandLineHandler(BasicCommandLineHandler)>>activate in Block: []
[] in FullBlockClosure(BlockClosure)>>newProcess in Block: []

script returned exit code 1
```

**Comment by MarcusDenker** [comment]
Now it fails with:

```
MetacelloNotification: 	Loaded -> Tool-Base-tonel.1 --- tonel:///builds/workspace/est_and_branch_Pipeline_PR-11921/64/src --- cache
MetacelloNotification: Finished atomic load
MetacelloNotification: Evaluating -> baseline [BaselineOfFuel] >> addPostloadHacks
MetacelloNotification: Evaluated -> baseline [BaselineOfFuel] >> addPostloadHacks
MetacelloNotification: Evaluating -> baseline [BaselineOfMorphic] >> postload:package:
SystemNotification: Starting postload action
ZnUnknownHttpVersion
[ (ZnUnknownHttpVersion version: string) signal ] in ZnStatusLine>>version: in Block: [ (ZnUnknownHttpVersion version: string) signal ]
Array(Collection)>>detect:ifFound:ifNone:
Array(Collection)>>detect:ifNone:
ZnStatusLine>>version:
ZnStatusLine>>readFrom:
ZnStatusLine class>>readFrom:
ZnResponse>>readHeaderFrom:
ZnResponse(ZnMessage)>>readStreamingFrom:
ZnResponse class(ZnMessage class)>>readStreamingFrom:
```

**Comment by MarcusDenker** [comment]
Failing tests:

```
testExternalCompilerDependencies – MacOSX64.System.DependenciesTests.SystemDependenciesTest
testExternalDisplayDependencies – MacOSX64.System.DependenciesTests.SystemDependenciesTest
testExternalFileSystemDependencies – MacOSX64.System.DependenciesTests.SystemDependenciesTest
testExternalKernelDependencies – MacOSX64.System.DependenciesTests.SystemDependenciesTest
testExternalLocalMonticelloDependencies – MacOSX64.System.DependenciesTests.SystemDependenciesTest
testExternalMetacelloDependencies – MacOSX64.System.DependenciesTests.SystemDependenciesTest
testExternalMonticelloDependencies – MacOSX64.System.DependenciesTests.SystemDependenciesTest
testExternalSUnitDependencies – MacOSX64.System.DependenciesTests.SystemDependenciesTest
testExternalSUnitKernelDependencies – MacOSX64.System.DependenciesTests.SystemDependenciesTest
```

**Pull request merged**
