### PR TITLE
2722-Symbol-should-not-implement-pragmas

### LINKED ISSUE #2722: Symbol should not implement #pragmas
Currently, GTInspector is extending Symbol to add a method #pragmas. This is wrong in my opinion. We should update the code calling this method or at least rename it #gtPragmas because it does not make much sense to be able to ask "pragmas" to a symbol.

### PR DESCRIPTION
**Pull request by jecisc**
Remove Symbol>>pragmas

Fixes #2722

### CODE REVIEW

**Comment by Ducasse** [comment]
Should deprecate it and may be we can move a part of it to SystemNavigation? 
I do not like the name #foo pragmas, it should have been at least #foo methodWithPragmas but it does not read well. May SystemNavigation current methodWithPragma: #foo.

**Comment by jecisc** [comment]
This does not even return CompiledMethod but Rings methods.

**Comment by MarcusDenker** [comment]
ah, the fact that it returns methods makes it really odd... we should check how many users it has

**Comment by jecisc** [comment]
@MarcusDenker I have the impression it has none.

**Review by guillep — APPROVED** [review]
Looks ok, there seem to be no users of this

**Pull request merged**
