### PR TITLE
RPackageOrganizer >> packageMatchingExtensionName: seems to be very slow

### LINKED ISSUE #8202: RPackageOrganizer >> packageMatchingExtensionName: seems to be very slow
We were profiling the loading of code in Metacello and noticed that during loading  of GT the method RPackageOrganizer >> packageMatchingExtensionName: was taking a significant amount of time:

Screenshot 2020-12-30 at 11 16 18

The slowdown seems to come from the concatenation `aSymbol, '-'` which creates a new symbol every time. Symbol creation however is an expensive operation.

In the GT loading build replacing that with `aSymbol asString, '-'` reduced the loading time on the CI from 30 minutes to 16 minutes!

This was observed in Pharo 8: Pharo-8.0.0+build.1145.sha.7dc39ed9e28dda58cf139f1723f350d5361d9b0f (64 Bit)
Unnamed

CoInterpreter * VMMaker-CompatibleUserName.1580983506 uuid: 7aff73cb-5a2e-5002-a356-37de4e762a49 Feb 12 2020
StackToRegisterMappingCogit * VMMaker-CompatibleUserName.1580983506 uuid: 7aff73cb-5a2e-5002-a356-37de4e762a49 Feb 12 2020
VM: 202002121007 https://github.com/pharo-project/opensmalltalk-vm.git Date: Wed Feb 12 11:07:12 2020 CommitHash: 2bd9e39 Plugins: 202002121007 https://github.com/pharo-project/opensmalltalk-vm.git

### PR DESCRIPTION
**Pull request by astares**
Fix #8202

### CODE REVIEW

**Comment by astares** [comment]
More testing should be done from other sides. Loading Seaside with the patch seems slower - but this is highly dependent on network:

```Smalltalk
Time millisecondsToRun: [ 
		Metacello new
 baseline:'Seaside3';
 repository: 'github://SeasideSt/Seaside:master/repository';
 load
	
 ] 
```
 "117060" in an image using the PR
 
```Smalltalk
 Time millisecondsToRun: [ 
		Metacello new
 baseline:'Seaside3';
 repository: 'github://SeasideSt/Seaside:master/repository';
 load
	
 ] 
 ```
 "77897" in an image NOT using the PR
 using latest version of Pharo 9 as of today 

Pharo9.0.0
Build information: Pharo-9.0.0+build.1000.sha.f92e709a70b5c621d55833be4ae6c310fd64e612 (64 Bit)
Unnamed
and home/astares/pharo/contribute/build/pharo-vm/lib/pharo
CoInterpreter VMMaker-tonel.1 uuid: 6b760ce6-6171-0d00-aeb1-fa250bd7ab2c Nov 26 2020
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: 6b760ce6-6171-0d00-aeb1-fa250bd7ab2c Nov 26 2020
cd12930 - Commit: cd12930 - Date: 2020-11-26 11:38:10 +0100

Pharo 9.0.0 built on Nov 26 2020 11:41:05 Compiler: 5.4.0 20160609
VMMaker versionString cd12930 - Commit: cd12930 - Date: 2020-11-26 11:38:10 +0100
CoInterpreter VMMaker-tonel.1 uuid: 6b760ce6-6171-0d00-aeb1-fa250bd7ab2c Nov 26 2020
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: 6b760ce6-6171-0d00-aeb1-fa250bd7ab2c Nov 26 2020


retrieved using ZeroConf 
 ```
 wget -O- https://get.pharo.org/64/90+vmHeadlessLatest | bash
 ```
 on LinuxMint within a Oracle Virtual Box (with Windows 10 as host)

**Comment by Ducasse** [comment]
Hi torsten
What I saw is that tag is super super slow. Browsing Bloc package is super super slow because it has 20 tags. 
Now we will have the time to revisit tags for P9.

**Comment by chisandrei** [comment]
On my laptop for seaside and Pharo 9 without the patch I get 67022 ms and with it 61157 ms

**Comment by chisandrei** [comment]
I also tried with loading Moose:
```
Time millisecondsToRun: [ Metacello new
  baseline: 'Moose';
  repository: 'github://moosetechnology/Moose:development/src';
  load ]
```
With the patch it takes 379413ms. Without the patch it takes 404455ms

**Comment by syrel** [comment]
We could also avoid concatenation all together, which would be more than 50% faster.

Since we always concatenate `aSymbol` with `'-'` we do not have to care about empty string (`withEmpty:` part of `beginsWithEmpty:`). Next since `-` is constant we can directly compare the value at a destination index with `-`

```smalltalk
aSymbol := #Package.
anExtensionName := 'Package-Tag-Examples'.

aSymbolIndex := anExtensionName findString: aSymbol startingAt: 1 caseSensitive: false.
aMinusIndex := aSymbolIndex + aSymbol size.
hasPrefix := aSymbolIndex > 0
	and: [ (aMinusIndex <= anExtensionName size)
		and: [ (anExtensionName at: aMinusIndex) = $- ] ]
```

**Comment by chisandrei** [comment]
I also tried loading a few more repos:

```
Time millisecondsToRun: [ 
	Metacello new
        repository: 'github://j-brant/smacc';
        baseline: 'SmaCC';
        load.

	Metacello new
        repository: 'github://PolyMathOrg/PolyMath';
        baseline: 'PolyMath';
        load.
	
	Metacello new
 		baseline:'Seaside3';
 		repository: 'github://SeasideSt/Seaside:master/repository';
 		load.
		
	Metacello new
    	baseline: 'PetitParser2';
    	repository: 'github://kursjan/petitparser2';
    	load.
	
	Metacello new
  		baseline: 'Moose';
  		repository: 'github://moosetechnology/Moose:development/src';
  		load.
 ] 
```

Without the patch it takes 681086ms on my laptop. With the patch 595249ms. So around one and a half minutes faster

**Review by MarcusDenker — APPROVED** [review]
small improvement, but good to do as a first step

**Comment by MarcusDenker** [comment]
I propose we merge this and then do a second one with the even better version as proposed by @syrel

**Comment by chisandrei** [comment]
@MarcusDenker There is another symbol concatenation in `RPackageOrganizer>>#hasPackageMatchingExtensionName:`

https://github.com/pharo-project/pharo/blob/c3cf32fbfd7c80b85b59c8df103ce36e8af1665e/src/RPackage-Core/RPackageOrganizer.class.st#L456

```
hasPackageMatchingExtensionName: anExtensionName

	(self hasPackageExactlyMatchingExtensionName: anExtensionName)
		ifTrue: [ ^true ].
		
	packages keysDo: [ :aSymbol | 
		(anExtensionName beginsWithEmpty: aSymbol, '-' caseSensitive: false)
			ifTrue: [ ^ true]].
	^ false
```

Not sure if this causes performance problems but it creates not needed symbols so we can also remove it.

**Comment by astares** [comment]
@chisandrei:
As this PR is already merged by Marcus it does not make sense to discuss/follow up here. So please open a new issue for #hasPackageMatchingExtensionName: (if you like pointing to the discussion here). 

Then a new contribution/PR could be done there as well. Thanks in advance!

**Comment by chisandrei** [comment]
Done: https://github.com/pharo-project/pharo/issues/8242

**Comment by MarcusDenker** [comment]
I copied the suggestion from @syrel there.

**Comment by astares** [comment]
@chisandrei / @MarcusDenker:  Thanks!

**Pull request merged**
