### PR TITLE
Rewrote algorithm of String>>#skipAnySubstring:start:

### LINKED ISSUE #6191: findBetweenSubstrings: freezes the image
**Describe the bug**
Running the following piece of code freezes the image 
```
'text' findBetweenSubstrings: #('te' 'x')
```
whereas
```
'text' findBetweenSubstrings: #('te' 't')
>>> a Collection('x')
```

**Version information:**
 - Version: Pharo9

### PR DESCRIPTION
**Pull request by dupriezt**
- Rewrote algorithm of String>>#skipAnySubstring:start: to remove bug,  use more explicit variable names, add comment and improve the structure.
- Added test method for String>>#skipAnySubstring:start

Fix #6191

### CODE REVIEW

**Comment by Ducasse** [comment]
Oh this is cool!. Thanks.

**Comment by Ducasse** [comment]
Just a question. Did you bench it a bit to see if we are in the same area in terms of complexity?

**Comment by dupriezt** [comment]
> Just a question. Did you bench it a bit to see if we are in the same area in terms of complexity?

I don't know if there's a specific method for benchmarking performance in pharo.
Here's what I did:
I ran the following code in a time profiler on an original pharo 9 image, and on one with my change, and looked at the time spent inside the #skipAnySubstring:startingAt: method. I did 10 measures for each case.
**The code:**
`1000000 timesRepeat: ['ababc' skipAnySubstring: 'ab' startingAt: 1]`
**Original Method**
Measures (ms): `305 286 313 302 290 276 267 283 283 283`
Average (ms): `288.8`
**Modified Method**
Measures (ms): `1037 1016 1093 1056 1099 1120 1076 1124 1119 1073`
Average (ms): `1081.3`
**Increase in Time: 374%**

So what should I do from there? This PR fixes an infinite loop problem in the original method, makes it so the method tries to skip the largest substring it finds (instead of the first one it finds) and rewrites the algorithm to "look nicer" (using #collect:, #beginsWith:, #max... instead of doing it imperative-style). It's probably possible to rewrite the fixed algorithm in a more imperative style.

*Note: Some tests were failing because they called the method directly with a string instead of with an array containing the string. I fixed that, and am now waiting on the next result of the CI to see if some tests remain broken.*

**Comment by dupriezt** [comment]
The broken tests that remain fail because they take too much time

**Comment by Ducasse** [comment]
Hi Thomas

bench and timeToRun are the way to bench and you have smark for benching. 
Usually we do a run multiple thousand times. 
It would be good to see if we can use this more imperative style. 

S

**Comment by guillep** [comment]
You don't want to bench. You want to profile :).
I tried profiling it a bit, but it becomes more evident with larger strings in addition to more iterations.

One main difference between the original algorithm and the new one is that the new one creates copies of substrings using `last:` to use `beginsWith:`. Maybe it coud be implemented alternatively using `findAnySubstring:startingAt:` or `findString:startingAt:` and keeping track of the current search index?

**Comment by guillep** [comment]
Seems there is no interest for this PR from the author. I'll close. Reopen if needed.

**Pull request closed without merging**
