### PR TITLE
Integrating UndefinedClass, ClassDefinition and modified classBuilder…

### PR DESCRIPTION
**Pull request by Alisu**
… to support classDefinition.

The objective is to create a class from its definition, the steps are:
-Add a ClassDefinition model et parser.
-Modify class builder/installer to create a class from previous model.
-Use several strategies in case of missing superclass, default raise Error, another is to use UndefinedClass.
-Add UndefinedClass (stubs for missing classes)

### CODE REVIEW

**Comment by dionisiydk** [comment]
Did you merge my changes required for calypso integration? 
The PR is in @Stef repo

**Comment by Alisu** [comment]
I am not sure of what you are asking (git noob).
I did not touch calypso and took a clean pharo 8 image.

________________________________
De : Denis Kudriashov <notifications@github.com>
Envoyé : mercredi 27 mars 2019 13:06
À : pharo-project/pharo
Cc : Alisu; Author
Objet : Re: [pharo-project/pharo] Integrating UndefinedClass, ClassDefinition and modified classBuilder… (#3030)


Did you merge my changes required for calypso integration?
The PR is in @stef<https://github.com/stef> repo

**Comment by Alisu** [comment]
OK i ask Pablo, he told me that we did not but that we could do it later.

________________________________
De : Denis Kudriashov <notifications@github.com>
Envoyé : mercredi 27 mars 2019 13:06
À : pharo-project/pharo
Cc : Alisu; Author
Objet : Re: [pharo-project/pharo] Integrating UndefinedClass, ClassDefinition and modified classBuilder… (#3030)


Did you merge my changes required for calypso integration?
The PR is in @stef<https://github.com/stef> repo

**Comment by stef** [comment]
in my repo?

**Comment by dionisiydk** [comment]
> in my repo?

Sorry, I mean another Stef @Ducasse .

**Comment by dionisiydk** [comment]
> OK i ask Pablo, he told me that we did not but that we could do it later.

This PR https://github.com/Ducasse/ClassInfrastructure/pull/3.
Will you continue develop in separate repo or in Pharo ? If in Pharo then how it will be merged later?

**Comment by Alisu** [comment]
Besides some refactors, i don't think i will continue develop classInfrastructure.

**Comment by Ducasse** [comment]
Ok for me. I was wondering why ShiftClassBuilder >> buildFromAST: as this logic (we will see when we introduce a visitor on the tree later).

**Comment by Ducasse** [comment]
@Denis we will drop the classInfrastructure repo and work in P8 directly.

**Comment by Ducasse** [comment]
I do not see the integration I did for the suggestions.

**Comment by Ducasse** [comment]
I checked and we are missing most of the extensions related to SugsSuggestion subclasses as in 40e6ce2

**Comment by Alisu** [comment]
I check and i don't have them on one image but have them in another one, i must have made a mistake, i'll try to fix this.

**Comment by MarcusDenker** [comment]
This PR seems to have broken the build: https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo8.0/203/

lots of tests failing

<blockquote><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo8.0/203/">Test pending pull request and branch Pipeline » Pharo8.0 #203 [Jenkins]</a></strong></div></blockquote>

**Comment by Alisu** [comment]
A lot of them are mines. Thanks, i gonna see what changed between my dev et my PR versions.

Edit: Something was missing in the initialize and retrieve the sugsuggestion. I think i failed to move a lot of things.

**Comment by MarcusDenker** [comment]
we need to revert this PR as the build is do broken that one can not make a new PR

**Pull request merged**
