### PR TITLE
20878-Alien-tests-should-be-in-a-Alien-Tests-package

### PR DESCRIPTION
**Pull request by estebanlm**
fixes 20878

https://github.com/estebanlm/pharo/tree/20878-Alien-tests-should-be-in-a-Alien-Tests-package

### CODE REVIEW

**Comment by MarcusDenker** [comment]
lots of tests in SystemDependenciesTest failing

**Comment by MarcusDenker** [comment]
only network relates test failing due to problems on CI infrastructure

**Comment by estebanlm** [comment]
ok, that was fast... I was about to say that test were not related and asking for verify/merge ;)

ps: we really need to fix those random failing tests.

**Comment by bencoman** [comment]
On 3 May 2018 at 19:52, Esteban Lorenzano <notifications@github.com> wrote:

> ps: we really need to fix those random failing tests.
>
The trouble is identifying the random failures at a time when there is time
to look at them.
I can't remember properly, was there a discussion sometime about re-running
failing tests
and pass a 2-out-of-3 result, but also log that random failure somewhere
visible to be dealt with.

cheers -ben

**Comment by jecisc** [comment]
I'm not sure rerun of tests is a good idea. 

Sometimes there is a random failure and we might miss those with a rerun.

**Pull request merged**
