### PR TITLE
[CI] Fix Refactoring related tests failing on the CI

### PR DESCRIPTION
**Pull request by carolahp**
Fix issue#17164
Reverts changes introduced in PR#17160

### CODE REVIEW

**Comment by Ducasse** [comment]
I would wait before reverting.

**Comment by Ducasse** [comment]
Ok the changes looks small so this is ok to revert them.

**Comment by guillep** [comment]
As commented in https://github.com/pharo-project/pharo/issues/17164, we are investigating this with @omarabedelkader.

Applying these changes locally fixes the following tests for us:

RBAddVariableAccessorsParametrizedTest.testNewClassVariableAccessors
RBAddVariableAccessorsWithLazyInitializationParametrizedTest.testNewClassVariableAccessors
RBMoveMethodParametrizedTest.testMoveMethodIntoArgument
RBMoveMethodParametrizedTest.testMoveMethodIntoInstanceVariable

Still the CI keeps failing, I don't understand why yet.

**Comment by guillep** [comment]
We found the difference between the original code and this revert: there was an extra send to `#name`.
We removed it, so we can let the CI run.

**Comment by demarey** [comment]
Ci is ok

**Pull request merged**
