### PR TITLE
Enhance roassal with version v1.04b #14985

### PR DESCRIPTION
**Pull request by akevalion**
The current version of Roassal in Pharo 12 is v1.03, in object profile.
v1.04b is in pharo-graphics https://github.com/pharo-graphics/Roassal/releases/tag/v1.04b

this pull request addresses this issue https://github.com/pharo-project/pharo/issues/14985

### CODE REVIEW

**Comment by MarcusDenker** [comment]
```
Error

Found undeclared Variables:  SpRoassal3InspectorPresenter in: AIGraphTestFixtureStructure>>#inspectGraph
Stacktrace

TestFailure
Found undeclared Variables: 
SpRoassal3InspectorPresenter in: AIGraphTestFixtureStructure>>#inspectGraph
ReleaseTest(TestAsserter)>>assert:description:resumable:
ReleaseTest(TestAsserter)>>assert:description:
ReleaseTest>>testUndeclared
ReleaseTest(TestCase)>>performTest
```

**Comment by MarcusDenker** [comment]
This now has a very strange error and I can not restart it. No re-run pissible, close and re-open has no effect:

```
Pull request #15013 updated
Connecting to https://api.github.com/ using pharo-ci using token as pass
Loading trusted files from base branch Pharo12 at 09a7567099a7a8c8763059629d86f1bc1068a511 rather than 4bd5bf3084f16679af0022166e233b25ce6f4848
hudson.plugins.git.GitException: Command "git fetch --tags --progress --prune origin +refs/heads/*:refs/remotes/origin/*" returned status code 137:
stdout: 
stderr: remote: Enumerating objects: 347, done.        

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2671)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2096)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:84)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:618)
	at jenkins.plugins.git.GitSCMFileSystem$BuilderImpl.build(GitSCMFileSystem.java:409)
	at jenkins.scm.api.SCMFileSystem.of(SCMFileSystem.java:293)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:106)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:311)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)

GitHub has been notified of this commit’s build result

Finished: FAILURE
```

**Comment by jecisc** [comment]
I think I found a way to restart it

**Comment by MarcusDenker** [comment]
This now seems to break everything by loading a wrong Iceberg? but why was it green itself?

https://github.com/pharo-project/pharo/issues/15057

**Comment by MarcusDenker** [comment]
Roassal was not the problem

**Pull request merged**
