### PR TITLE
22137-gif-read-writer-refactoring-and-animated-images

### PR DESCRIPTION
**Pull request by darth-cheney**
# GIFReadWriter and Animated GIFs #
_Please excuse the length of this PR documentation. I ended up making quite a few changes and feel the need to explain my decisions since this is my first real PR for Pharo_.
  
## Why ##
The current implementation of `GIFReadWriter` is incomplete, according to both GIF specifications. You can see this in the existing code — there are sections where entire bytes of the file structure are intentionally skipped over.
  
Perhaps more importantly, the current implementation has a subclass called `AnimatedGIFReadWriter` which is also an incomplete implementation. We also do not have a way to display any kind of animated images in the first place.
  
Then there is the issue of the readability/comprehensibility of what goes on when a GIF bytestream is read or written out. The current implementation is, in my opinion, kind of a mess (I think the original author knew it and meant to refactor at some point). It took a few weeks to wrap my head around it. It appears that the core of this code has not been updated much since the mid-90s Squeak version.
  
## What ##
This PR is not only a refactoring of the existing classes. It also adds some new classes and abilities as specified below.
  
### Refactor GIFReadWriter and deleting AnimatedGIFReadWriter ###
All GIF files are made up of constituent images. When you load a GIF that is not animated, it is (more or less) a "single frame" GIF. We should treat the ReadWriter this way and not have a separate class for reading/writing animated GIFs since they are the same thing! The `GIFReadWriter` class can simply tell us if a GIF is animated or not based on the number of frames it contains.
  
### AnimatedImageFrame ###
A constituent GIF image is **not** just a `Form` like other images; it is a frame that contains much more information, like how the image should be disposed of when played in animation and where it should be drawn on the overall canvas (which can have different dimensions than any one Form within).

The true result of a GIFReadWriter reading a GIF filestream is now a collection of these frames. I have preserved methods like `GIFReadWriter >> #form` for backward compatibility (it will respond with the first frame's form).
  
Thus I've added a new class called `AnimatedImageFrame` that contains this information. It is set up to work not only with decoded GIF Forms but any kind of Form, really. I have tried to make it as generic as possible.
  
### AnimatedImageMorph ###
As it stands, we don't have a way to show animated images. So I created the `AnimatedImageMorph` class, which can interpret and play `AnimatedImageFrames`. This part was kind of difficult and some may not agree with the exact implementation of how Forms are composited and played back (should they be compiled into just a collection of Forms ahead of time? I'm open to stuff like that).
  
Likewise, if you find a GIF that is not displaying correctly, the methods of this class are likely the culprit. Examples of this are most welcome!
  
### Separate Encoder / Decoder for compressed bitmap data ###
The current implementation of `GIFReadWriter` incorporates the GIF-specific [Lempel-Ziv-Welch (LZW)](https://en.wikipedia.org/wiki/Lempel%E2%80%93Ziv%E2%80%93Welch) in addition to the regular bytestream reading/writing and bitmap creation processes. The class is bloated with instance variables and strange methods that are hard to reason about. It also makes understanding how the actual LZW implementation is working quite difficult — I had to debug some aspects of the decoding process and found this to be the case.
  
So I decided to decompose this functionality, creating `LzwGifEncoder` and `LzwGifDecoder` as separate classes that only encode/decode streams of LZW data (for GIFs).
  
I realize some might disagree with this decision, but I think it makes understanding what the hell is going on a lot simpler, especially the way I've set up the methods and comments.

#### Special Case: `LzwGifEncoder` ####
Encoding bit data into LZW is actually fairly complex. I was not able to refactor that part of the process. Instead, this class rips out the implementation that already exists and cleans it up as best as possible.

(If you are curious, you can read a good blow-by-blow of the process [here](http://www.matthewflickinger.com/lab/whatsinagif/lzw_image_data.asp))
  
## Example of Use ##
Make sure you have a GIF (try an animated one!) file path and try:
  
```smalltalk
fs := 'some-path-to-a-GIF' asFileReference binaryReadStream.
gif := GIFReadWriter on: fs.
gif
   readHeader;
   readBody.

img := AnimatedImageMorph new
   height: gif canvasHeight;
   width: gif canvasWidth;
   frames: gif frames.

img openInHand.
```

## Tests ##
There were only 2 existing tests for reading and writing GIFs. I have added another three specifically for the GIFReadWriter class that should cover many cases, though I know this is lacking.
  
I also realize that having no tests for the encoder/decoder classes is bad form. But I had a really hard time coming up with the appropriate tests, since much of the interaction is dealing with streams and **TONS** of bitwise operations.
  
My only (paltry!) defense here is that I've added more tests than already exist.
  
Everything seems to be passing at the moment.
  
## Future Work ##
The compositing of frames in AnimatedImageMorph will probably need some improvements going forward, as mentioned above. I'm sure others will find bugs at some point.
  
I hope down the road someone can make better sense of the encoding method in `LzwGifEncoder`, which, as mentioned, was more or less copied from the existing implementation with little refactoring. I had a hard time understanding it and still don't completely.

### FileBrowser and Inspector ###
I have no idea how to get the File Browser to open GIFs that are animated as AnimatedImageMorphs rather than single-Form ImageMorphs. This is probably something we'll want to do.
  
Likewise, we should write a nifty Inspector extension that allows interaction with animated GIFs, like using a slider to go back and forth through the frames.
  
## Suggestions! ##
Any critiques and/or suggestions are most welcome. This is my first PR for Pharo and learning about LZW/GIFs was kind of a wild and frustrating ride.

### CODE REVIEW

**Comment by darth-cheney** [comment]
Whatever the CI process is here, it does not seem to have incorporated the new classes that are clearly in the commits (`AnimatedImageFrame`, for example). 
  
Tests that fail seem to have similar to this:
```
Error
receiver of "new" is nil
Stacktrace
UndefinedObject(Object)>>doesNotUnderstand: #new
GIFReadWriter>>nextPutImage:
GIFReadWriter class(ImageReadWriter class)>>putForm:onStream:
[ :out | GIFReadWriter putForm: form onStream: out ] in ImageReadWriterTests>>testGifWriteReadInMemory
ByteArray class(SequenceableCollection class)>>new:streamContents:
ByteArray class(SequenceableCollection class)>>streamContents:
ImageReadWriterTests>>testGifWriteReadInMemory
ImageReadWriterTests(TestCase)>>performTest
```  
  
Where `nextPutImage:` instantiates a new `AnimatedImageFrame`. But that class should be loaded, per [this commit](https://github.com/pharo-project/pharo/pull/1666/commits/8e252153025765c828b5530fcf3b8bf826dfa8dc) (and later commits on top of that).
  
Any ideas?

**Comment by tesonep** [comment]
Hi Eric, the problem is that the new packages should be added to the baseline to be loaded during the creation of the image.

You should add it to BaselineOfMorphic >> #baseline: in the same way as Graphics-Files is there, as they are related

Cheers,
Pablo

**Comment by darth-cheney** [comment]
Of course! Thanks @tesonep. 
  
I am also having some Iceberg issues that have prevented me from adding class comments in `AnimatedImageMorph` and `AnimatedImageFrame` (Iceberg does not see the changes at all). It might have something to do with how I've loaded my cloned branch into the image. For now, with fresh P7 images from the Launcher, I can't even load my forked branch at all, so I'm working with a slightly older image from last week.

**Comment by darth-cheney** [comment]
My bad @guillep

**Comment by Ducasse** [comment]
Hello darth-cheney 

this is super cool! It is important to keep your documentation. Did you add as package comment?
and as class comments?

Stef

**Comment by Ducasse** [comment]
I pushed it because it looks good. I could not find how to replay it just before.

**Comment by darth-cheney** [comment]
@Ducasse I created class comments for everything, yes (though I am not familiar with package comments).
  
What do you mean when you say you "could not find how to replay it just before"?

**Comment by Ducasse** [comment]
Hi eric do not worry. Normally there is button on details so that I can access the jenkins slave and rerun it. But now this is integrated. Thanks for your contribution.

**Comment by astares** [comment]
This introduced some ugly things (unused temp variables, methods that were uncategorized and methods that were not used). Before I cared that we had an image where all temps were used and no unused was left.

I opened https://pharo.fogbugz.com/f/cases/22426/ now and fixed this.

@Ducasse I would appreciate if integrators would really follow the process and 
                   let someone review/approve a change or quickly review themself before merging.
                   We should skip the review only for trivial stuff but not for bigger code changes. Thanks!

**Comment by darth-cheney** [comment]
For posterity: I made an effort to erase all temps and categorize all methods before submitting, but apparently these changes did not make it in. I had some difficulty working with Iceberg and dealing with an open working branch across multiple images.

**Comment by astares** [comment]
@darth-cheney No problem. Usually we have a review/approval which was skipped here. I already submitted a PR for cleanup. Nothing is carved in stone. 

Nonetheless we should think on how we could improve and avoid it next time. Because it took me a lot of time to clean sometimes trivial things in Pharo 7 and I'm still not finished. 

For the temps we could easily introduce a test - but it takes time to run it. See my post now on

http://lists.pharo.org/pipermail/pharo-dev_lists.pharo.org/2018-September/272927.html

**Comment by darth-cheney** [comment]
@astares Thanks. I think 20-30s is a minor price to pay for something to integral to the goals of a clean image.

**Comment by Ducasse** [comment]
Hi eric 
I personally accept to clean simple stuff if the change improves a lot the situation. 
So thanks a lot for your contribution. 
What we should do is to have a set of rules that we should run before publishing. 
But we are busy on something else. 
Stef

**Comment by astares** [comment]
@Ducasse @darth-cheney 

Can not happen anymore with new release test:
https://pharo.fogbugz.com/f/cases/22432/New-Release-test-NoUnusedTemporaryVariablesLeftTest

**Pull request merged**
