### PR TITLE
Integrate Teachable objects into SUnitMock

### PR DESCRIPTION
**Pull request by hernanmd**
As requested in #15806 this PR integrates the Teachable package from @emicklei into SUnitMock package.

### CODE REVIEW

**Comment by Ducasse** [comment]
Sound good to me. I remove the squeak link because it was going to a wrong place.

**Comment by hernanmd** [comment]
> Sound good to me. I remove the squeak link because it was going to a wrong place.

Cool thanks!

The failing tests are not related.

**Comment by Ducasse** [comment]
I wonder if this one is not relate

osx-64 / Tests-osx-64 / testManifestNamesAccordingToPackageNames – MacOSX64.ReleaseTests.ReleaseTest
<1s
Error

Assertion failed
Stacktrace

TestFailure
Assertion failed
ReleaseTest(TestAsserter)>>assert:description:resumable:
ReleaseTest(TestAsserter)>>assert:description:
ReleaseTest(Object)>>assert:
[:each |
		 self assert: (expectedManifestNames includes: each)] in ReleaseTest>>testManifestNamesAccordingToPackageNames
OrderedCollection>>do:
ReleaseTest>>testManifestNamesAccordingToPackageNames
ReleaseTest(TestCase)>>performTest

**Review by Ducasse — COMMENTED** [review]
I review it now can you check the broken test I mentioned?

**Comment by demarey** [comment]
I really do not like when one use `self should: [ ... ] raise: Exception` in tests. It should be avoided as much as possible.
In this PR, why not using `self should: [ ... ] raise: MessageNotUnderstood`? The expected behavior is  more clear in this case.

**Comment by hernanmd** [comment]
> I really do not like when one use `self should: [ ... ] raise: Exception` in tests. It should be avoided as much as possible. In this PR, why not using `self should: [ ... ] raise: MessageNotUnderstood`? The expected behavior is more clear in this case.

I didn't write this library, I just integrated it. In my opinion it is not critical and there are many usability issues in Pharo that need more attention, but you could open an issue with this requirement.

**Comment by astares** [comment]
@demarey / @hernanmd / @Ducasse 

As I wrote this library and the tests (together with some contributors) I guess I'm the one to blame for this. This issue is already fixed in https://github.com/astares/Pharo-Teachable/commit/472cbd17dcac09cc09dccea36760298506d4245a and there is a new release https://github.com/astares/Pharo-Teachable/releases/tag/v2.1

But I really dislike the way @hernanmd has integrated Teachable now. Instead of ripping off the code and just putting
it into another package I would have wished for a regular external package release inclusion like we do for other. 

This would allow original author and contributors to continue to maintain but also keep included version 
and the repo easily in synch. Same as we do for other packages.

But it reveals again the current Achilles heel of Pharo. The way we think about 
 - **modularity**
 - usage of external projects (which is related)
for the standard image these days is really bad and there were not enough improvement on this corner in recent year.

At the moment we continue to accept a strangely mixed and also confusing situation which is not good in the mid 
and long-term. Some package have been 

 -  ripped / just included (leaving original repo unmaintained and users confused or with the feeling of abondonware)
 -  sometimes we maintain own code but twice with effort to reintegrate (take Zinc for example)
 -  sometimes we properly work with an own package repo and use proper version to include (like Iceberg and Spec, ...)

Also sometimes we work with repos of specific users - sometimes with repos under the "pharo-project" umbrealla and
control.

This is not a good model, has side effects. increases the confusion (especially for new contributors) but also effort and yes 
would require some work to unify and go with a more professional model. We all know about capacity but this mixed 
situation burns a lot of cycles too. 

We should not move away from the idea:
 - to have a (tiny) kernel that is versioned
 - build additional image(s) or distributions based on top by loading versioned packages
as this is the way professional software is maintained

Remember: Not carving a house from a stone but building a (modular) house using bricks. And one of our reasons to fork from Squeak back in 2008 was the disagreements in release management.

I hope this specific topic could be improved for the new year 2024 in Pharo. Happy new year!


<blockquote><div> GitHub</div><div><strong><a href="/astares/Pharo-Teachable/releases/tag/v2.1">Release v2.1 · astares/Pharo-Teachable</a></strong></div><div>What's Changed

Grammar correcction by @bencoman in #1
Setup CI by @gcotelli in #2

New Contributors

@bencoman made their first contribution in #1
@gcotelli made their first contribution in #2

Fu...</div></blockquote>

**Comment by hernanmd** [comment]
> @demarey / @hernanmd / @Ducasse
> 
> As I wrote this library and the tests (together with some contributors) I guess I'm the one to blame for this. This issue is already fixed in [astares/Pharo-Teachable@472cbd1](https://github.com/astares/Pharo-Teachable/commit/472cbd17dcac09cc09dccea36760298506d4245a) and there is a new release https://github.com/astares/Pharo-Teachable/releases/tag/v2.1
> 
> But I really dislike the way @hernanmd has integrated Teachable now. Instead of ripping off the code and just putting it into another package I would have wished for a regular external package release inclusion like we do for other.
> 
> This would allow original author and contributors to continue to maintain but also keep included version and the repo easily in synch. Same as we do for other packages.
> 
> But it reveals again the current Achilles heel of Pharo. The way we think about
> 
>     * **modularity**
> 
>     * usage of external projects (which is related)
>       for the standard image these days is really bad and there were not enough improvement on this corner in recent year.
> 
> 
> At the moment we continue to accept a strangely mixed and also confusing situation which is not good in the mid and long-term. Some package have been
> 
>     * ripped / just included (leaving original repo unmaintained and users confused or with the feeling of abondonware)
> 
>     * sometimes we maintain own code but twice with effort to reintegrate (take Zinc for example)
> 
>     * sometimes we properly work with an own package repo and use proper version to include (like Iceberg and Spec, ...)
> 
> 
> Also sometimes we work with repos of specific users - sometimes with repos under the "pharo-project" umbrealla and control.
> 
> This is not a good model, has side effects. increases the confusion (especially for new contributors) but also effort and yes would require some work to unify and go with a more professional model. We all know about capacity but this mixed situation burns a lot of cycles too.
> 
> We should not move away from the idea:
> 
>     * to have a (tiny) kernel that is versioned
> 
>     * build additional image(s) or distributions based on top by loading versioned packages
>       as this is the way professional software is maintained
> 
> 
> Remember: Not carving a house from a stone but building a (modular) house using bricks. And one of our reasons to fork from Squeak back in 2008 was the disagreements in release management.
> 
> I hope this specific topic could be improved for the new year 2024 in Pharo. Happy new year!
> 
> >  GitHub**[Release v2.1 · astares/Pharo-Teachable](/astares/Pharo-Teachable/releases/tag/v2.1)**What's Changed
> > Grammar correcction by @bencoman in #1
> > Setup CI by @gcotelli in #2
> > New Contributors
> > @bencoman made their first contribution in #1
> > @gcotelli made their first contribution in #2
> > Fu...

Hi. If you read carefully even the [issue title](#15806) called for integrating into SUnitMock

It is a pity that you comment now about this that the PR is already integrated and you did not do it in the issue at the time BEFORE the PR was integrated. I suggest that next time you try to comment on the [issue itself](#15806) and not after it has been integrated, or be more attentive to review the PR you are interested in.

Anyway, there is nothing to stop you from opening another issue, and submitting a PR yourself. I'm sure your changes will be better.


<blockquote><div> GitHub</div><div><strong><a href="/astares/Pharo-Teachable/releases/tag/v2.1">Release v2.1 · astares/Pharo-Teachable</a></strong></div><div>What's Changed

Grammar correcction by @bencoman in #1
Setup CI by @gcotelli in #2

New Contributors

@bencoman made their first contribution in #1
@gcotelli made their first contribution in #2

Fu...</div></blockquote>

**Comment by demarey** [comment]
@hernanmd @astares 
Thank you both for your comments and answers. They are really appreciated.
We know that commenting is easier than doing and that it is difficult for everyone to keep an eye on all issues - PRs.
I was preparing a PR from my comments but I got stuck by a problem in Iceberg. I'm quite sure @astares will propose a PR when he will find time. I also appreciate @hernanmd pushed this topic.
So, at the end, I see a lot of positive energy to make Pharo better. Please no need to blame anyone, just try to **encourage contributions** ;)

**Comment by estebanlm** [comment]
Hi, I came late to this (I did not see it before) but I am pointing it for the future: I disagree with this integration :) 
Not with the content of it (which also would have deserved a discussion, but well... wont be the first time we integrate things without a proper discussion)...  but specially with the way it was integrated: it should have been an external project and not part of the core sources (which are already very hard to handle).

We cannot improve modularity if we do not think modular.

**Comment by hernanmd** [comment]
> Hi, I came late to this (I did not see it before) but I am pointing it for the future: I disagree with this integration :) Not with the content of it (which also would have deserved a discussion, but well... wont be the first time we integrate things without a proper discussion)... but specially with the way it was integrated: it should have been an external project and not part of the core sources (which are already very hard to handle).
> 
> We cannot improve modularity if we do not think modular.

Again, it is A LOT better if you comment on **the issue** BEFORE pull requests are integrated. And again, the issue title had enough information, you could have saved me time.

Now comments like that have information which will be lost here, could you provide links to integration guidelines for core libraries instead? Otherwise people cannot guess.

**Comment by Ducasse** [comment]
Esteban we are talking **one** single class and there is already a mock package in SUnit. So I do not see the point.

**Comment by guillep** [comment]
> Again, it is A LOT better if you comment on **the issue** BEFORE pull requests are integrated. And again, the issue title had enough information, you could have saved me time.

Please let's be patient also, we are in holidays. Many of us still with children at home :).
It's not easy to answer within a 2 day deadline ^^.
 
> Now comments like that have information which will be lost here, could you provide links to integration guidelines for core libraries instead? Otherwise people cannot guess.

Yes, I think documenting the right way to do it would be nice. I don't think there is such a documentation.
I think the starting point is to look at how spec is integrated in Pharo. Check `BaselineOfIDE>>specCode:` and `BaselineOfIDE class>>>declareExternalProjects`. Probably @estebanlm can give more details on that, it's been a long time I have not followed that.

**Comment by Ducasse** [comment]
You see what I learned from it. 
- I asked torsten if we can integrate one single class. And I should not have. What I should have done is just to reimplement it because this is trivial. And I should have put this class in my test package and this was done. 
- So I will rever the changes that hernan did. 
I do not want to have to manage a more complex baseline for a single class with 5 simple methods. 
If you have the time to play with that then perfect. I'm working the refactoring engine and this is painful. 
So I do not need more pain.

**Comment by astares** [comment]
Happy new year by the way!

I'm not sure a GH issue is the right way to discuss this but I hope my thoughts hopefully trigger more positive 
thinking/responses. Be aware that using uppercase does not mean to shout. 

Would we make such a noise if it would be just a discussion about a single class? It's not just a discussion
about Teachables content or a single class. It comes with a test class too, so there are two classes at least 😊

@guillep wrote:
>Please let's be patient also, we are in holidays. Many of us still with children at home :).
>It's not easy to answer within a 2 day deadline 

Yes

@Ducasse write:
>Esteban we are talking one single class and there is already a mock package in SUnit. So I do not see the point.

I fully agree that it is a simple framework, yes. But the way I provided it for now is in the form of a project in an own repo. 
Teachable can be used **standalone** and other users and projects might already have dependencies to this project. 

In the future users might want to use it even without all the SUnitMock stuff in their tiny image. Also my repo provides info/docu and a video, what about that now? 

More thoughts:
- sure it was easy to introduce MessageNotUnderstood - but i had to do it **twice**
- sure I can fix an issues as before - but I have to manage it now on two sides (doubling my efforts) 
- should every maintainer of a project that gets included into the standard image accept a double effort in the future?
- similar topics exist for Zinc and other - we have to do it *twice*, in the original repo and in the integrated / forked 
   code and often it is unclear and unnecessary forking /  copying around.
- where do users now open tickets - in my repo or within Pharo one?
- where do I now manage the docu?
- how can one now use it when he is only interested in the Teachable part, but not want to have the whole 
  SUnit /Sunit Mock stuff ion his image?
- also think of some user working with an already release Pharo 12 when community is working on Pharo 13
  iteration. In Pharo 13 we might have an improved version and my repo will offer it as a new Teachable version too. 
  When the user loads it into the stable release Pharo 12 the SUnitMock packages will become dirty - 
  same for users who load the project already via their baselines.
  
So the primary issue we discuss here is NOT HOW simple the code of Teachable is. If Teachable is useful for SUnitMock 
it should manage it via a DEPENDENCY and LOADING it and not by copying the code. This is where our understanding of INTEGRATION differs. 

Sure we can always copy and "inhale the code" into Pharo standard image. For Teachable today we might now decide it's so simple that we should not care and ignore the discussion. But what about next integration of other projects?

I'm sure we will face similar discussion next time with even more complex code or frameworks/components to integrate. And we will end up with a lot of "micro-forking" if we only apply proper versioning and loading to the bigger projects like Spec or Iceberg.

So the overall issue is more: how do we reuse and integrate (external) stuff now and in the future? And in a consistent and reproducible way.

On the high level this boils down to two approaches:

A) we "rip together what we need" (be it simple or complex) often leaving back the previous way "unmanaged/unmaintained" 

B) or we (professionally) construct our image by **composing** it from well tested "bricks" based on tested versions forming something bigger
    
IMHO our goal was to have a tiny (versioned) kernel and then building Pharo (minimal or bigger images) on top by loading. 
So depending on loaded artefact /version combinations we may even end up even in different Pharo distributions.

The idea of a Bootstrap is to to build different house(s) from bricks - not carve the sculpture out of the single stone, right?

At the moment Pharo unfortunately ignores that goal on some ends using the first approach (A) and with this 
we leave the world behind us with lots of confusion, abondened repositiories and outdated documentation. 
People see old repositories and get confused. They ask many questions - and many of them are also 
confused as it is often only obvious to long term members / contributors what the names of the projects are about.

Currently our nice Pharo image is a strange mixture of direct code, externally loaded code (sometimes versioned,
sometimes loaded from an open branch), ... and lots of things are broken now also in Pharo 12 as we sometimes 
randomly apply our changes.

Calypso me maintain in original Pharo repo, typically a browser should have a dependency to UI framework (Spec). Same for DrTest. But for Spec or Iceberg we have to apply changes outside in an own repo and we work with loadable versions. 

This mixture is not only inconsistent but also confusing. Sometimes I'm not sure if we stopped the layering / modularization or if this is just a temporary "in-between" situation because not all tools have been converted.

>So I do not need more pain.

Pain will increase over time if we continue with our current setting and applying model A.  You can argue that there is no capacity or money to solve this but with this model we also just burn more cycles over time. In the end everybody will just do firefighting.

And Pharo also does not scale that way as there is only a "single point of definition" what is included/assembled and what not. But People maybe want to build own distribution(s)/ images (maybe a production image without tests or SUnit) based upon their own requirements.

We only have a few Pharo integrators for the primary packages and they have to review/merge anything. The more external packages  get copied into Pharo the more they have to take care about. Choosing the approach A for integration means to also increase their pain over time.

In approach B (if properly done) the project maintainer cares on his (assembled) project and the only thing the integrator has to do is to  integrate the next proper versions of components or solve conflicts between colliding versions of the pieces.

Partly we already work with such a better model of "distributed responsibility", Roassal is a nice example. It runs parallel with own merging of issues and own PRs and when a new primary version is available this is what Pharo maintainers need to integrate. 

Also remember that users might have a different need for "their" usage of Pharo. They might want to have an (tiny or large) production image without any tests, without the tools or without SUnitMock. Today they can just "deconstruct" the image by removing the packages. We dont want to go back to the "stripping model" of some commercial Smalltalks, right?

One primary idea for Pharo was to have a more "modular" Smalltalk - built /composed from reproducible 
reusable parts. If we fail on that we are not better than old Squeak releases management with current maintainers collection/copying what they see as useful. 

If we continue with the (A) model there is the risk that users leave Pharo for other Smalltalks or technologies over time who are supporting proper package and dependency systems. 

For instance Cuis is also able to bootstrap an image now and also allows for componentized approach (with CuisDynamicLibraries) https://lists.cuis.st/mailman/archives/cuis-dev/2023-October/008099.html
And GT is loaded from different feenk projects if I'm not mistaken. I think they use Versionner or GT Releaser tool for that.
https://medium.com/feenk/gt-releaser-a-case-study-exemplifying-moldable-development-6c93b320d040

So the key to a growing ecosystem that scales is a proper package system with versions and a good dependency management. Declaring dependencies and loading is the way to go.

Java would have vanished if there would be no Maven, same for JavaScript if there would be no npm and they do better because they are **not shy to define clean dependencies**.

And yes - they can bring all kind of problems - but something they nonetheless work, give enough freedom to choose and therefore these package management systems are used widely. We should not ignore that. Because with a better model and tools in Pharo we could improve on our end as well and perform much better.

So if the gardener prepares the ground and nurtures the flowers will grow ....

**Pull request merged**
