### PR TITLE
Add rule for accessing/removing category

### LINKED ISSUE #10503: Add rule for accessing/removing category
Using "adding/removing" instead of "adding-removing" should be prefered

image

we should provide a lint rule with an autofix

image

image

### PR DESCRIPTION
**Pull request by astares**
Fix #10503

### CODE REVIEW

**Comment by astares** [comment]
Ready for review and integration

**Comment by MarcusDenker** [comment]
- [CI] Failing randomly: StPlaygroundPageTest>>testContents #10519

**Comment by demarey** [comment]
Why 'adding/removing' would be better than 'adding-removing' ?
I would like that there is a discussion with the community on "standards" category names before changing everything in the image. Would it be possible to write a Phep for this? https://github.com/pharo-project/pheps/blob/main/phep-0001.md

<blockquote><div> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 73 million people use GitHub to discover, fork, and contribute to over 200 million projects.</div></blockquote>

**Comment by guillep** [comment]
Closing as stated in #10503

**Comment by guillep** [comment]
> Why 'adding/removing' would be better than 'adding-removing' ? I would like that there is a discussion with the community on "standards" category names before changing everything in the image. Would it be possible to write a Phep for this? https://github.com/pharo-project/pheps/blob/main/phep-0001.md

I second this too. This categorization stuff being mandatory and very time consuming, should at least be discussed as @demarey says. And we should have a phep stablishing the accepted "style guides" for protocols.

The other thing to think about is that now that rules are checked at commit time by iceberg, the release test becomes much less valuable.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 73 million people use GitHub to discover, fork, and contribute to over 200 million projects.</div></blockquote>

**Pull request closed without merging**
