### PR TITLE
3233-Windows-file-references-broken-in-P8

### LINKED ISSUE #3233: Windows file references broken in P8
Windows 10

```Smalltalk
'C:\Dokumente und Einstellungen' asFileReference directories
```
works in Pharo 7 and gives empty Array (when not readable) - but not anymore in Pharo 8

Same for 

```Smalltalk
'C:\Dokumente und Einstellungen' asFileReference children
```

### PR DESCRIPTION
**Pull request by akgrant43**
Handle the root directory entry ('\') on Windows.

Unix file systems have a common root which is handled by the OS file system.  Windows doesn't have this, so the Pharo FileSystem needs to have a pseudo-root entry to be consistent across platforms.

Fixes: #3233

### CODE REVIEW

**Comment by akgrant43** [comment]
CI test failures appear unrelated:

- 6 of the 8 are the usual suspects (happen in lots of CI runs)
- I can't reproduce the #testSmokeTestForDemoPages and #testExplicitAcceptDoesNotAffectTextPort failures and don't see how they are related.

**Comment by Ducasse** [comment]
Thanks a lot Alistair.

**Comment by akgrant43** [comment]
@astares it would be great if you could review this.

**Comment by Ducasse** [comment]
Esteban/Pablo can you have a look?

**Review by tesonep — APPROVED** [review]

**Comment by akgrant43** [comment]
Thanks, Pablo & Stef!

**Pull request merged**
