### PR TITLE
Change #getTempPath:buffer: on WinPlatform to use ‘GetTempPathW’ instead of ‘GetTempPath2W’

### PR DESCRIPTION
**Pull request by Rinzwind**
This pull request changes `#getTempPath:buffer:` on WinPlatform to use ‘GetTempPathW’ instead of ‘GetTempPath2W’ for compatibility with versions of Windows older than ‘Windows 10 Build 20348’ or ‘Windows Server Build 20348’.

See the [‘Requirements’ for ‘GetTempPathW’](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettemppathw#requirements), the [‘Requirements’ for ‘GetTempPath2W’](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettemppath2w#requirements) and my [earlier comment in pull request #13777](https://github.com/pharo-project/pharo/pull/13777#issuecomment-2016488515).

The [documentation for ‘GetTempPath2W’](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettemppath2w) indicates it is equivalent to ‘GetTempPathW’ for non-SYSTEM processes: “When calling this function from a process running as SYSTEM it will return the path C:\Windows\SystemTemp, which is inaccessible to non-SYSTEM processes. For non-SYSTEM processes, GetTempPath2 will behave the same as GetTempPath.” As for how ‘GetTempPath2’ is related to ‘GetTempPath2W’: “The fileapi.h header defines GetTempPath2 as an alias which automatically selects the ANSI or Unicode version of this function based on the definition of the UNICODE preprocessor constant. […] For more information, see [Conventions for Function Prototypes](https://learn.microsoft.com/en-us/windows/win32/intl/conventions-for-function-prototypes).”

### CODE REVIEW

**Comment by Rinzwind** [comment]
I converted this to a draft. I expect this to fix the issue of the Windows test run timing out (issue #15104), but having a build in which that still times out after pull request #16341 is merged would allow checking that the test run’s `*.xml` and `*.fuel` files are then archived. It remains to be confirmed whether this actually fixes the timeout issue as for all of the builds so far, ‘pharo-ci-jenkins2-win10’ was used, which doesn’t run the tests at all (issue #15105).

**Comment by Rinzwind** [comment]
In build 5, there no longer was a SymbolNotFoundError in the `#setUp` of various tests in [‘Tests-windows-64-Epicea-Tests-Test.xml’](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16342/5/artifact/Tests-windows-64-Epicea-Tests-Test.xml/*view*/), but a PrimitiveFailed instead. I added a temporary additional commit to get more detailed stack traces to see what the argument to `#createDirectory:` is: commit f197b1a0dc905f6a. I tried opening [‘Tests-windows-64-Epicea-Tests-Test-EpAnnouncementsTest-testMonitorAnnouncesUpdateWhenDisabled.fuel’](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16342/5/artifact/Tests-windows-64-Epicea-Tests-Test-EpAnnouncementsTest-testMonitorAnnouncesUpdateWhenDisabled.fuel) in the image of [‘Pharo12.0-PR-64bit-6692750.zip’](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16342/5/artifact/build/bootstrap-cache/Pharo12.0-PR-64bit-6692750.zip) but that signaled an FLMethodChanged, and a MessageNotUnderstood after changing `#defaultMethodChangedWarningDisabled` to answer `true`.

**Comment by Rinzwind** [comment]
As can be seen in the [‘Tests-windows-64-Epicea-Tests-Test.xml’ of build 9](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16342/9/artifact/Tests-windows-64-Epicea-Tests-Test.xml/*view*/), the PrimitiveFailed was due to the argument to `#createDirectory:` referring to a nonexistent drive ‘X’:

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Epicea-Tests" tests="55" timestamp="8:45:43.838 pm" seed="377703460"  failures="0" errors="97" time="985.223">                                                            
	<testcase classname="Windows64.Epicea.Tests.EpAnnouncementsTest" name="testMonitorAnnouncesUpdateWhenDisabled" time="20.034">
		<error type="PrimitiveFailed" message="primitive #createDirectory: in WindowsStore failed">
PrimitiveFailed
primitive #createDirectory: in WindowsStore failed
[…]
WindowsStore(DiskStore)>>createDirectory:
	Receiver: a WindowsStore
	Arguments and temporary variables: 
		path: 	Path / 'X:'
[…]
```

That was in turn due to `#testResolveTempPathFromTMP` on WindowsResolverTest having been executed before which left its test value for ‘TMP’ in the environment. Fixed in: commit 2ab718df0205efb0.

The temporary additional commit to get the more detailed stack trace has been removed. This can be merged now.

**Comment by Rinzwind** [comment]
There are some [failing tests in build 15](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16342/15/testReport/). See issue #16119 for the SocketStreamTest failures, and issue #16280 for the ReleaseTest failures. The other test failures are not caused by the changes in this pull request, but show up because the Windows test run no longer times out.

**Comment by jecisc** [comment]
Is this ready to merge? @Rinzwind 

@MarcusDenker Do we merge with the failing windows tests? They seems linked to the strict FFI that @guillep enabled. (I think, I'm not sure since I never really used FFI :) )

**Comment by Rinzwind** [comment]
It’s ready to be merged yes.

I opened NewTools pull requests [#728](https://github.com/pharo-spec/NewTools/pull/728) and [#729](https://github.com/pharo-spec/NewTools/pull/729) to fix the [‘Windows64.NewTools.FileBrowser.Tests’](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16342/15/testReport/Windows64.NewTools.FileBrowser.Tests/) failures.

**Comment by Rinzwind** [comment]
The function signature I used in [NewTools pull request #729](https://github.com/pharo-spec/NewTools/pull/729) was not correct, I opened another pull request to (try to) fix it: [NewTools pull request #730](https://github.com/pharo-spec/NewTools/pull/730).

I’m not sure why using `ulong* nil` doesn’t work though, the FFI should perhaps be extended to support that.

**Comment by Rinzwind** [comment]
All three of the [failing tests in build 21](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16342/21/testReport/) are in SocketStreamTest (issue #16119).

**Pull request merged**
