### PR TITLE
Not possible to ask if a file or folder (via reference) is hidden

### LINKED ISSUE #15499: Not possible to ask if a file or folder (via reference) is hidden
In Pharo 12 we can ask a file reference if it is #isReadable or #isExecutable.

But it is not yet possible to directly ask the file reference if it is hidden, although we already have all 
the support for that in the standard image. The class  DiskDirectoryEntry already uses the necessary stat attributes
and provided a method #isHidden already in a platform independent manner and with tests.

So we should provide a #isHidden for file references using that so that it is possible to directly
write:

```Smalltalk
'/home/user/.bar' asFileReference isHidden 
```

### PR DESCRIPTION
**Pull request by astares**
Fix #15499

### CODE REVIEW

**Comment by Ducasse** [comment]
Nice

**Review by akgrant43 — CHANGES_REQUESTED** [review]
Looks good, but to be consistent with the other attribute checks I'd suggest changing:

```
FileReference>>isHidden
	^ filesystem isHidden: path attributes: nil
```

**Comment by astares** [comment]
@Ducasse 

Yes, I would like to get this in as it can also help to get the tests green for "NewTools-FileBrowser-Tests" on all platforms. 
At the moment it is green on Windows but failing on Linux/Mac due to an issue in StFBVisibleFilter

This can then be a preparation to fix https://github.com/pharo-project/pharo/issues/15455

**Comment by akgrant43** [comment]
> Looks good, but to be consistent with the other attribute checks I'd suggest changing:
> 
> ```
> FileReference>>isHidden
> 	^ filesystem isHidden: path attributes: nil
> ```

Actually, this change is more than cosmetic, the original suggestion will fail for `FileReference`s that point to a memory file store.

**Comment by astares** [comment]
> filesystem isHidden: path attributes: nil

@akgrant43 
Your suggestion will fail as well for memory file stores - so it is cosmetic only (but nonetheless we can switch to it for consistency reason).

The **file system** in FileSystem>>#isHidden:attributes: **dispatches** the #isHidden:attributes: messages **to** the platform specific **store** and MemoryStore does not provide a suitable implementation for #isHidden:attributes: yet

image

I will fix that and provide additional tests for that. Do not yet integrate.

**Comment by akgrant43** [comment]
Ahh, I should have checked further.  Thanks!

**Review by akgrant43 — APPROVED** [review]
Thanks!

**Pull request merged**
