### PR TITLE
Configuring the spec debugger to force contexts stepping into quick methods

### PR DESCRIPTION
**Pull request by StevenCostiou**
Just configuring the debugger model to correctly perform step into into contexts

### CODE REVIEW

**Comment by StevenCostiou** [comment]
Fixes #8711

**Comment by Ducasse** [comment]
Steven this changes is breaking many tests.

**Comment by Ducasse** [comment]
/ Tests-osx-64 / testDynamicShouldFilterStackUpdate – MacOSX64.NewTools.Debugger.Tests.Model.StDebuggerActionModelTest
<1s
osx-64 / Tests-osx-64 / testUpdateTopContextAfterSessionOperation – MacOSX64.NewTools.Debugger.Tests.Model.StDebuggerActionModelTest
<1s
osx-64 / Tests-osx-64 / testCancelCodeChangesFor – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest
<1s
osx-64 / Tests-osx-64 / testCodeChangeAfterContextChange – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest
<1s
osx-64 / Tests-osx-64 / testCodeSelectionAfterRestart – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest
<1s
osx-64 / Tests-osx-64 / testCodeSelectionAfterStepping – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest
<1s
osx-64 / Tests-osx-64 / testContextChangedAfterStepIn – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest
<1s
osx-64 / Tests-osx-64 / testContextChangedAfterStepOverAndReturn – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest
<1s
osx-64 / Tests-osx-64 / testContextTempVarList – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest
<1s
osx-64 / Tests-osx-64 / testContextUnchangedAfterStepOver – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest
<1s
osx-64 / Tests-osx-64 / testDiscardCodeChangesFor – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest
<1s
osx-64 / Tests-osx-64 / testReceiverChangedAfterStepIn – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest
<1s
osx-64 / Tests-osx-64 / testReceiverChangedAfterStepOverAndReturn – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest
<1s
osx-64 / Tests-osx-64 / testReceiverList – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest
<1s
osx-64 / Tests-osx-64 / testReceiverUnchangedAfterStepOver – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest
<1s
osx-64 / Tests-osx-64 / testRecordUnsavedCodeChanges – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest
<1s
osx-64 / Tests-osx-64 / testRestartContext – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest
<1s
osx-64 / Tests-osx-64 / testRestoreUnsavedCodeChanges – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest
<1s
osx-64 / Tests-osx-64 / testSelectLastStackElementWithMoreElements – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest
<1s
osx-64 / Tests-osx-64 / testStackTableAfterReturn – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest
<1s
osx-64 / Tests-osx-64 / testStackTableAfterStepIn – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest
<1s
osx-64 / Tests-osx-64 / testStackTableSelectionChanged – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest
<1s
osx-64 / Tests-osx-64 / testToolbarInDNUContext – MacOSX64.NewTools.Debugger.Tests.Presenters.StDebuggerTest

**Comment by StevenCostiou** [comment]
Grmp I used `isBlock` instead of `isCompiledBlock` in a guard...

**Review by guillep — APPROVED** [review]
Ok

**Pull request merged**
