### PR TITLE
22038-Replace-World-Menu-by-Menu-bar

### PR DESCRIPTION
**Pull request by guillep**
https://pharo.fogbugz.com/f/cases/22038/Replace-World-Menu-by-Menu-bar

The world menu is by large un-intuitive:
 - Users are not used to click on a background to open a menu
 - For those that "get it" they try to do it with right click (Of course, it looks like a context menu!) and that does not work

We should change that world menu by a menu bar like any application. That will lower the entrance barrier to new users, at the cost of having to move the cursor to the top to look for the menu...

This pull request
 - adds a menu bar
 - reorganizes the menu world
 - the world menu can still be obtained by clicking on the background to have a smoother transition
 - revises some #themeChanged to update all StringMorphs and not only labels
 - refactors DockingBarMorph to avoid repeated code
 - the first window open is open in the center instead of close to the cursor
 - fixed taskbar color

### CODE REVIEW

**Comment by jecisc** [comment]
image




screen shot 2018-06-01 at 14 17 47

**Comment by astares** [comment]
As with OSWindow one can open more than one window and break out 
of the single Pharo VM window the menu bar could also be the menu
bar of a Pharo tool running in a new native window. At least we should have that in mind ...

**Comment by MarcusDenker** [comment]
[32] Finished atomic load
[32] Evaluated -> baseline [BaselineOfMorphicCore] >> postload:package:'Starting postload action'
[32] NotFound: [:morph |  morph isKindOf: MenubarMorph ] not found in Array

**Comment by guillep** [comment]
Test failures not related

**Comment by pavel-krivanek** [comment]
I tried the prebuilt image. The Iceberg launcher was not working

**Comment by jecisc** [comment]
@pavel-krivanek Can you clarify "not working"? If it means that it's not on Tools but on the root it's because Iceberg needs to be updated after this PR is integrated.

**Comment by guillep** [comment]
Yes, we cannot update iceberg and this in the same PR

**Comment by Ducasse** [comment]
So what do we do?

**Comment by guillep** [comment]
To me if build is ok we can integrate. We can always do an iteration after.

**Comment by pavel-krivanek** [comment]
the Iceberg icon with the description in the menu bar does nothing when clicked on it

**Comment by guillep** [comment]
Yes, but it can still be used from the world menu obtained by clicking on the background. We will fix it in the next Iceberg release.

**Comment by pavel-krivanek** [comment]
ok

**Review by pavel-krivanek — APPROVED** [review]

**Comment by riverdusty** [comment]
This needs to be a setting to turn it off.
If I develop an application for my clients, I don't want my clients seeing a development environment menu bar. My application already has a menu bar and I think that this would just confuse everybody trying to use my application.
So, for a developer this is a nice to have. 
For end users using apps built in Pharo, this is going to add confusion and clutter.

**Comment by jecisc** [comment]
We knows. 

This is on my todo list. We integrated a first version with the hope that other people will participate. Then we will improve it little by little and the setting is one of the "must have" before Pharo 7 release.

**Comment by jecisc** [comment]
@riverdusty 
https://github.com/pharo-project/pharo/pull/1499

**Pull request merged**
