### PR TITLE
Odd PR builds use the the latest VM, else use the stable VM

### PR DESCRIPTION
**Pull request by guillep**
We need to slowly start pushing the latest VM version, right now hosted in the `pharoX` branch of the VM repository.
This branch so far has all our latest work on the VM for at least one year:
 - interpreter variable auto-localization (https://github.com/pharo-project/pharo-vm/pull/371)
 - slang cleanups and improvements (https://github.com/pharo-project/pharo-vm/pull/413, https://github.com/pharo-project/pharo-vm/pull/265, https://github.com/pharo-project/pharo-vm/pull/230, https://github.com/pharo-project/pharo-vm/pull/413, https://github.com/pharo-project/pharo-vm/pull/311, https://github.com/pharo-project/pharo-vm/pull/307, https://github.com/pharo-project/pharo-vm/pull/291)
 - SIMD support in the JIT (https://github.com/pharo-project/pharo-vm/pull/421, https://github.com/pharo-project/pharo-vm/pull/444)
 - the initial work on the perm space (https://github.com/pharo-project/pharo-vm/pull/377, https://github.com/pharo-project/pharo-vm/pull/388, https://github.com/pharo-project/pharo-vm/pull/372, https://github.com/pharo-project/pharo-vm/pull/416, https://github.com/pharo-project/pharo-vm/pull/418)
 - many many bugfixes
 - …

To not disrupt everybody’s work, I propose to make some kind of AB testing on the CI, **only impacting PRs**.
- odd builds (1,3,5,…) use the latest VM 
- even builds (2,4,6,…) use the stable VM

This will make sure that:
 - the latest VM will be tested in a complex scenario (load code, run tests…)
 - people that have a problem can re-run their builds to get a stable run

### CODE REVIEW

**Comment by nrainhart** [comment]
@guillep there's a problem with this approach. The changes in https://github.com/pharo-project/pharo-vm/pull/444 require using a `Pharo11` image.

I guess we could backport the changes needed to support SIMD bytecodes to `Pharo10` (and maybe also `Pharo9`?).

Does that sound good, or do you prefer to go a different route?

**Comment by MarcusDenker** [comment]
Failing tests not related for sure:

- [CI] Failing test: ProperMethodCategorizationTest>>testNoUncategorizedMethods #11669

Failing test not related?
- testSetColumnTitleInPresenterPutsColumnHeaderMorph (unix only)

**Comment by tesonep** [comment]
> @guillep there's a problem with this approach. The changes in [pharo-project/pharo-vm#444](https://github.com/pharo-project/pharo-vm/pull/444) require using a `Pharo11` image.
> 
> I guess we could backport the changes needed to support SIMD bytecodes to `Pharo10` (and maybe also `Pharo9`?).
> 
> Does that sound good, or do you prefer to go a different route?

The PR #444 requires the Pharo11 Image to run as VMMaker, not to run the image. Also, the changes will be in P11.

**Comment by guillep** [comment]
> > @guillep there's a problem with this approach. The changes in [pharo-project/pharo-vm#444](https://github.com/pharo-project/pharo-vm/pull/444) require using a `Pharo11` image.
> > I guess we could backport the changes needed to support SIMD bytecodes to `Pharo10` (and maybe also `Pharo9`?).
> > Does that sound good, or do you prefer to go a different route?
> 
> The PR #444 requires the Pharo11 Image to run as VMMaker, not to run the image. Also, the changes will be in P11.

This change only changes Pharo's PRs so far.
It does not affect what the "latest" vm means in zero conf or the launcher.
It for sure does not modify how the PRs in the VM repository work :).

**Comment by guillep** [comment]
There is a syntax error in the bash script, please do not yet integrate

```bash
++ is_development_build

bootstrap/scripts/runTests.sh: line 26: is_development_build: command not found

+ '[' == 1

bootstrap/scripts/runTests.sh: line 26: [: missing `]'
```

**Comment by guillep** [comment]
Tests are now green!

**Pull request merged**
