### PR TITLE
Faulty code: don't permit undeclared by default

### PR DESCRIPTION
**Pull request by privat**
This PR defaults `permitUndeclared` to false, meaning that unless instructed otherwise with the setter `permitUndeclared:`, `OpalCompiler` will consider the (static) use of undeclared variables to be errors.
Moreover, `OCUndeclaredVariableNotice` is officially promoted to `RBErrorNotice`. Until now, it was in some limbo state, neither an error nor a warning. This change means that an AST node with such a notice will answer true to `isFaulty`.

In order for this change to be successful, the following clients are adapted:
* Traits: `TaAbstractComposition` sets permitUndeclared
* Monticello: `MethodAddition` sets permitUndeclared
* All clients of `ClassDescription>>compile:*`, that includes CodeImport and some tests in newtools, permitUndeclared is set according to a heuristic (is a requestor present) that is comparible with the current usage.
  I think that's the right move since I consider `ClassDescription>>compile:*` a legacy API, so maintaining its behavior make sense.

Tests are also added. `RBCodeSnippet` gains a new ivar `isFaultyMinusUndeclared` (the name is not nice, but it is not used that much) that correspond to being faulty, while `permitUndeclared` is set to true.
It is used for the Monticello test on snippets and for a new test explicitly made to check `permitUndeclared:`

There are many small changes with specific goals, so there are a lot of commits (oneliner sometime).
The global diff is less big than I expected.

### CODE REVIEW

**Comment by jecisc** [comment]
Hi,
Can you elaborate on ClassDescription>>compile:* been legacy? Do you have plans to use something else in the future? 

I have the impression that this is the entry point of most method compilation happening in the image no?

**Comment by privat** [comment]
> Can you elaborate on ClassDescription>>compile:* been legacy? 

* Receiver (the class) is dubious
* Name `compile` is bad, because it also installs
* Returns a symbol. cf #12880
* Not configurable with optimization options or faulty-modes
* Most of them ask you for a requestor, but requestors are bad
* Hard to extend: adding a new parameter double the number of selectors

For me, `ClassDescription>>compiler` is the way forward.

**Comment by privat** [comment]
Bootstrap passed :tada:, but test failed :sob:  because I fumbled a rebase trying to restore some lost comments (cf #13246). So let's try again

**Comment by privat** [comment]
Tests are ok, Windows is still running, but who cares?

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
