### PR TITLE
Remove ZnUrlCopy

### LINKED ISSUE #10664: Remove ZnUrlCopy
The latest image contains ZnUrlCopy. I read the class comment.

This is horrible and incomplete as well.

More than a year ago https://github.com/svenvc/zinc/commit/7a42881f14144e0d9dcc2b3aa98a075f189eae69 added the preservation of URL query parameter order.

Of course, merging all of Zinc is hard because the many cosmetic changes that took place. I want to do it, but I can't do it alone.

The problem at hand can be fixed easily by changing the superclass of ZnMultiValueDictionary to OrderedDictionary. That's it.

Then ZnUrlCopy can be removed and the 2 users can revert back to ZnUrl.

I'll try to do a PR.

### PR DESCRIPTION
**Pull request by astares**
Fix #10664

### CODE REVIEW

**Comment by astares** [comment]
- class was deprecated and moved to Deprecated10
- class comment is pointing to #10664
- the two users have been switched to use ZnUrl

**Comment by svenvc** [comment]
Thanks.

I don't see the change in users.

I would not move it to deprecated, just delete it: it was a temporary measure, no one uses it.

**Comment by astares** [comment]
The other changes are in "Microdow"n - which is managed externally. Unfortunately not like other external packages (it does not work with clear releases). 

image

So I guess we need some help here.

**Comment by Ducasse** [comment]
It will be removed with the new version of MD we are preparing.

**Pull request closed without merging**
