### PR TITLE
Icons-Renames-3 

### PR DESCRIPTION
**Pull request by MarcusDenker**
More Icon Renames, a step for https://github.com/pharo-project/pharo/issues/11356

### CODE REVIEW

**Review by astares — APPROVED** [review]

**Comment by Ducasse** [comment]
In fact I do not understand why we remove the Icon from the names

**Comment by astares** [comment]
Because it is redundant and also clear from the selector that this the **name** of an icon. We manage a collection of icons (and their name depict what they visually represent).

If you would manage / return a collection of "status" you would also write the **name**:

#active
#stopped

and not

#activeStatus
#stoppedStatus

If you would manage / return a collection of "colors" you would also write the **name**:

#green
#red

and not

#redColor
#greenColor

At least that is how I would see it and I guess this is the intention here.

**Comment by Ducasse** [comment]
Ok I understand. Now it means that we will break all existing users of the old icon names and to me the added value is infinitisimal. So probably that we can get the icon version for a while. Now to me this kind of changes are not worth: The ratio changes / breakage is not in favor.

**Comment by astares** [comment]
@Ducasse 

My understanding of the PR's of @MarcusDenker is that we just fix the places in the image where the wrong name had been
used and where access is slower. By including his changes we become consistent and the access is faster.

As **we do not change** ThemeIcons>>iconNamed:ifNone: itself (which can also deal with the old "xxxIcon" names - we still do not break old usage in external packages. So no animal will be harmed and people can migrate their packages whenever they like without having a problem.

As you can see on:

image

using the right name is better and faster. But using the old name is still possible and we are still backward compatible.

**Comment by Ducasse** [comment]
Ah ok so this is better.

**Pull request merged**
