### PR TITLE
4459-Why-the-debugger-select-all-the-occurrences-of-a-message-

### LINKED ISSUE #4459: Why the debugger select all the occurrences of a message
Because the selection makes more difficult to spot the actual sender.

### PR DESCRIPTION
**Pull request by MarcusDenker**
fixes #4459

### CODE REVIEW

**Comment by dionisiydk** [comment]
It does not looks good.
Try debug second message in cascade

**Comment by MarcusDenker** [comment]
we could just detect if we are in a cascade:

debugHighlightStart
	^ parent isCascade
		ifTrue: [ self keywordsPositions first ]
		ifFalse: [ super debugHighlightStart ]

I will make a new PR

**Comment by dionisiydk** [comment]
But in case of cascade it will have original issue. No?

пн, 30 сент. 2019 г., 13:21 Marcus Denker <notifications@github.com>:

**Comment by MarcusDenker** [comment]
Yes, but there it makes sense to just highlight the selector...  yes, it will then show the other substrings, but it will be an improvement.

We need to have a way to highlight without the editor hightlighting similar strings in addition...

**Pull request closed without merging**
