### PR TITLE
fix-dependency-freetype-morphic

### PR DESCRIPTION
**Pull request by estebanlm**
FreeType cannot depend on Morphic, we may want Fonts without it!

### CODE REVIEW

**Comment by estebanlm** [comment]
test error not related

**Comment by MarcusDenker** [comment]
Why is Paragraph a class in Morpic? Shouldn't that be just text?

**Review by MarcusDenker — APPROVED** [review]
Besides the question why Paragraph is Morphic (which would be another PR), this looks good

**Comment by estebanlm** [comment]
I agree... with both: should be Text, and is for another PR ;)

**Pull request merged**
