### PR TITLE
Revert "Issue 2345 envversion.sh causes out-of-repository bootstrap to fail"

### PR DESCRIPTION
**Pull request by estebanlm**
Reverts pharo-project/pharo#2346

### CODE REVIEW

**Comment by akgrant43** [comment]
Hi Esteban,

Can we wait and see if #2368 resolves the issue?

Thanks,
Alistair

**Comment by akgrant43** [comment]
Hi Esteban,

I think I've resolved this in #2368.

Cheers,
Alistair

**Comment by akgrant43** [comment]
Hi Esteban,

Can you look at #2368 ?

Thanks,
Alistair

**Comment by akgrant43** [comment]
Sorry for the duplicate messages, I'm not trying to hurry you up, just not awake this early in the morning.

**Comment by estebanlm** [comment]
sound like #2368 makes this unnecessary

**Pull request closed without merging**
