### PR TITLE
20452-SUnit-UITesting-package-should-be-renamed-to-SUnit-UI-Tests

### PR DESCRIPTION
**Pull request by VincentBlondeau**
https://pharo.fogbugz.com/f/cases/20452/SUnit-UITesting-package-should-be-renamed-to-SUnit-UI-Tests

### CODE REVIEW

**Comment by astares** [comment]
Looks like the package contents is about addional support methods for "UITesting" and not about the testing of the SUnit UI. Sorry my fault. 

So we should name it "SUnit-Support-UITesting" to avoid further confusion.

**Comment by MarcusDenker** [comment]
lots of tests failing for this one that look related

**Comment by VincentBlondeau** [comment]
@astares Ok. SimulateKeystrokesSpecification and SimulateMouseSpecification however should be in their own test package: SUnit-Support-UITesting-Tests

**Comment by astares** [comment]
But we should let them end with "Test" in the class name, no?

So 
  SimulateKeystrokesSpecification -> SimulateKeystrokesSpecificationTest
  SimulateMouseSpecification -> SimulateMouseSpecificationTest

**Review by MarcusDenker — APPROVED** [review]
ok

**Pull request merged**
