### PR TITLE
Adds executable comments to False and True classes

### PR DESCRIPTION
**Pull request by ortegacmanuel**
This PR

- Adds executable comments to the True class.
- Adds executable comments to the False class.

### CODE REVIEW

**Comment by Ducasse** [comment]
I would keep the executable comments in the superclass because boolean are special.

**Comment by ortegacmanuel** [comment]
@Ducasse Ok! :+1: 

- I reverted the commit removing executable comments from the super class and updated this PR accordingly.
- Do you still see a value in adding - somehow duplicating - executable comments in the True and False classes?

**Comment by MarcusDenker** [comment]
Failing tests not related:

- [CI] Failing test: ProperMethodCategorizationTest>>testNoUncategorizedMethods #11669
- [CI] Failing test: ReleaseTest>>testUndeclared #11670
- #skipOnPharoCITestingEnvironment seems to not work on WIN and MAC #11425

**Comment by Ducasse** [comment]
Yes :)

**Pull request merged**
