### PR TITLE
3107-Remove-EpSorterLog-because-its-unused

### LINKED ISSUE #3107: Remove EpSorterLog because it's unused
And merge the sibling (EpLog) and the superclass (EpAbstractLog) since the hierarchy is not needed.

### PR DESCRIPTION
**Pull request by tinchodias**
Remove EpSorterLog since it's unused, and merge the sibling (EpLog) and the superclass (EpAbstractLog) since the hierarchy is not needed.

Note: bootstrap shouldn't have any issue, but anyone that wants to do live update of an image should disable and re enable the EpMonitor.

Fixes #3107.

### CODE REVIEW

**Comment by tinchodias** [comment]
This change was suggested by @jecisc last Friday.

**Comment by guillep** [comment]
Looks ok. Could you solve the conflict?

**Review by guillep — APPROVED** [review]
Looks ok!

**Comment by tinchodias** [comment]
Done. Merged this branch with current Pharo8.0

**Comment by guillep** [comment]
Failing tests not related

**Pull request merged**
