### PR TITLE
Update versions in #beautifulComments, #documentBrowser and #welcomeBrowser for BaselineOfPharo for Pharo 11 to ‘v1.0.1’, ‘v1.0.3’ and ‘v1.0.2’

### PR DESCRIPTION
**Pull request by Rinzwind**
This pull request updates the versions in `#documentBrowser` and `#welcomeBrowser` for BaselineOfPharo for Pharo 11 to ‘v1.0.3’ and ‘v1.0.2’ respectively. The tags need to be added first, I cannot do that; for NewTools-DocumentBrowser, ‘v1.0.3’ should refer to [commit 7d3996762a13](https://github.com/pharo-spec/NewTools-DocumentBrowser/commit/7d3996762a13), and for NewTools-WelcomeBrowser, ‘v1.0.2’ should refer to [commit ed5c5339466e](https://github.com/pharo-spec/NewTools-WelcomeBrowser/commit/ed5c5339466e).

### CODE REVIEW

**Comment by Ducasse** [comment]
Tx Kris

**Comment by Ducasse** [comment]
I'm trying to create a tag but with the GH UI so far I failed. I will check if I can do that on the command line.

**Comment by Ducasse** [comment]
I pushed the two tags.

**Comment by Ducasse** [comment]
So now rechecking the build

**Comment by Ducasse** [comment]
Looks like the there is a problem:

```
MetacelloNotification: Fetched -> (nearest) BaselineOfClap-tonel.1 --- tonel:///builds/workspace/est_and_branch_Pipeline_PR-17427/64/src --- tonel:///builds/workspace/est_and_branch_Pipeline_PR-17427/64/src
MetacelloNotification: Loading -> BaselineOfClap-tonel.1 --- tonel:///builds/workspace/est_and_branch_Pipeline_PR-17427/64/src --- tonel:///builds/workspace/est_and_branch_Pipeline_PR-17427/64/src
MetacelloNotification: Loaded -> BaselineOfClap-tonel.1 --- tonel:///builds/workspace/est_and_branch_Pipeline_PR-17427/64/src --- tonel:///builds/workspace/est_and_branch_Pipeline_PR-17427/64/src
MetacelloNotification: ...RETRY->BaselineOfWelcomeBrowser
MetacelloNotification: ...RETRY->BaselineOfWelcomeBrowser
[31mFileDoesNotExistException: '/tmp/github--pharospecNewToolsWelcomeBrowserv102265660148051765068214940904136247704441.zip'
[0mFile>>openForWrite:
File>>openForRead
File>>readStream
FileHandle>>binaryReadStream
FileSystem>>binaryReadStreamOn:
FileReference>>binaryReadStream
ZipArchive>>readFrom:
MetacelloPharo30Platform(MetacelloPharoPlatform)>>downloadZipArchive:to:
MCGitHubRepository class(MCGitBasedNetworkRepository class)>>projectDirectoryFrom:version:
MCGitHubRepository(MCGitBasedNetworkRepository)>>calculateRepositoryDirectory
MCGitHubRepository(MCGitBasedNetworkRepository)>>resolveLocalRespository
MCGitHubRepository(MCGitBasedNetworkRepository)>>ensureLocalRepository
MCGitHubRepository(MCGitBasedNetworkRepository)>>localRepository
MCGitHubRepository(MCGitBasedNetworkRepository)>>goferReferences
```

**Comment by Ducasse** [comment]
Ah but I'm also confused because it should be for Pharo 11 so I do not know how this build can show us anything.

**Comment by Rinzwind** [comment]
Thanks! There was no new build though because Jenkins didn’t process the ‘REMOVED event’ before you had reopened the pull request, see the following from the [‘Multibranch Pipeline Events’](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/indexing/events) log, and the example from the log I gave [in pull request #16172](https://github.com/pharo-project/pharo/pull/16172#issuecomment-2052539481):

```
[Sat Nov 23 17:33:18 CET 2024] Received Pull request #17427 closed […] REMOVED event […] with timestamp Sat Nov 23 17:33:13 CET 2024
[…]
No changes detected: PR-17427 […]
[…]
[Sat Nov 23 17:33:20 CET 2024] Received Pull request #17427 reopened […] UPDATED event […] with timestamp Sat Nov 23 17:33:15 CET 2024
[…]
No changes detected: PR-17427 […]
```

**Comment by Rinzwind** [comment]
I’m guessing the error in [build 2](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-17427/2/) is due to BaselineOfBeautifulComments referring to ‘master’ for Microdown. I added commit b6d150f52c4e0c14 and opened a pull request for that: [BeautifulComments pull request #49](https://github.com/pillar-markup/BeautifulComments/pull/49).

**Comment by tesonep** [comment]
Hi @Rinzwind thanks so much for the PR, I will see what is happening to help you with this

**Comment by jecisc** [comment]
I do not see any v1.0.1 tag in Beautiful comments.

https://github.com/pillar-markup/BeautifulComments/tags

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/pillar-markup/BeautifulComments">Tags · pillar-markup/BeautifulComments</a></strong></div><div>A nice extension of Pharo to support class comments in Microdown and better rendered. - Tags · pillar-markup/BeautifulComments</div></blockquote>

**Comment by jecisc** [comment]
I just released it. 

https://github.com/pillar-markup/BeautifulComments/releases/tag/v1.0.1

I'll restart the CI

<blockquote><div> GitHub</div><div><strong><a href="/pillar-markup/BeautifulComments/releases/tag/v1.0.1">Release v1.0.1 · pillar-markup/BeautifulComments</a></strong></div><div>What's Changed

Make BaselineOfBeautifulComments for Pharo 11 use the tag ‘v2.4.1’ instead of the branch ‘master’ for Microdown by @Rinzwind in #49

New Contributors

@Rinzwind made their first con...</div></blockquote>

**Comment by Rinzwind** [comment]
Ok, thanks! I’m afraid I don’t understand the error on Windows in [build 6](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-17427/6/), I’ll try starting another one.

**Comment by Rinzwind** [comment]
[Build 7](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-17427/7/) seems to have the same error(s) on Windows:

```
+ ./pharo Pharo.image test --junit-xml-output --stage-name=Tests-windows-64 '.*'
[ERROR] 2024-11-26 18:48:54.000 sqMakeMemoryNotExecutableFromTo (extracted/vm/src/win/sqWin32SpurAlloc.c:226):VirtualProtect(x,y,PAGE_EXECUTE_READWRITE): No error
Running tests in 759 Packages
[…]
PrimitiveFailed: primitive #primitivePerformWorkerCall:withArguments: in TFSameThreadRunner failed
TFSameThreadRunner(ProtoObject)>>primitiveFailed:
[…]
AthensCairoSurface class>>destroySurfaceHandle:
[…]
FFIExternalResourceExecutor>>finalize
```

**Comment by jecisc** [comment]
This PR allows the image to build even of the windows tests are broken. I'll merge

**Pull request merged**
