### PR TITLE
22175 senders implementors doesnt properly use the ast and cursor location

### PR DESCRIPTION
**Pull request by macta**
Improves how the senders/implementers functions work by using intersection on the AST. NOTE: in a Pharo7 image more additional changes are needed for Calypso to make use of the methods introduced here (however there is a chicken and egg in the current process due to project dependencies).

This does work in Pharo 6 using Nautilus, but will need this applied first so I can then commit the minor Calypso changes

### CODE REVIEW

**Comment by macta** [comment]
If you try and test this behaviour (like in the original bug report - by placing your cursor on a keyword msg without any selection) but are using Calypso, you won't see any difference because Calypso causes automatic selection of the entire line (and thus undoes what this fix is trying to do).

It should properly detect a full keyword msg even if nested as a bracketed parameter to another msg etc)

As mentioned above - I want to apply this fix to Calypso to - but need this first.

You can either use the base browsers, or temporarily hack Calypso :

in ClyTextEditor modify #browseIt, #implementorsOfIt and #referencesToIt - simple comment out the first line in each method where it says:
"self lineSelectAndEmptyCheck: [^ self]."

I'm very keen for @dionisiydk to look at this so I can coordinate with him to add these fixes into Calypso (assuming they aren't controversial)

**Comment by macta** [comment]
I don't know why the checks failed, it doesn't look like a consequence of my changes?

**Comment by jecisc** [comment]
I relaunched.

**Comment by macta** [comment]
I forgot to mention there are lots of tests in RubSmalltalkEditorTest - that seem to test conditions that sender/implementors would not encounter, this is because I have further changes based on AST interpretation to do useful things like "widen text selection" even on broken code (so you can select stuff to easily fix it - essentially I'd like to have more IntelliJ like smarts in our IDE). But I've tried to keep the change to minimum and will add another PR if this one can go though.

**Comment by MarcusDenker** [comment]
looks very interesting! The direction this is taking is very nice... text selection on the AST even when it is broken sounds great!

We should revisit the "AST based selection" code that is in the package NodeNavigation, which is for now disabled there where problems to get crtl-leftarrow key codes somehow.

**Comment by MarcusDenker** [comment]
(I guess your code would replace most of NodeNavigation if you can do "widen selection" based on the AST)

**Comment by macta** [comment]
@MarcusDenker widen selection ended up looking like this, and it works reasonably well (badly factored but I think you get the point). If you are liking the direction, I will quickly follow up with this - but possibly need to get this PR working in calypso as then you can more easily try it out and see what I mean.

```
widenSelectionOfIt
	"Extend the current highlight selection using knowledge of the AST and cursor location"
	| node start stop comments cursorIndex |
	
	cursorIndex := self textArea stopIndex.
	node := self bestNodeInTextAreaOnError: [ ^nil ].
	
	self hasSelection ifTrue: [ 
			node parent ifNotNil: [ node := node parent ].
			node isSequence ifTrue: [ node := node parent]].
	
	start := node start.	
	stop := node stop. 
	
       "check if widening in a comment"
	comments := RBCommentNodeVisitor visit: node flatCollect: [ :cmnts | cmnts ].

	comments 
		detect: [ :c | c start < cursorIndex and: [ c stop >= cursorIndex ] ] 
		ifFound: [ :c | start := c start. stop := c stop ].
	
	"Handle cascaded messages"
	node isMessage ifTrue: [
		(node isCascaded) 
			ifTrue: [ | i cascadeStart|
				(i := node parent messages indexOf: node) > 1 
					ifTrue: [ 
						cascadeStart := (node parent semicolons at: i - 1).
						cascadeStart < cursorIndex ifTrue: [ start := cascadeStart ]]]
			ifFalse: [
				"Try to select the first chained message send - experimental - haven't got this to work"
				"self hasSelection ifFalse: [ 
					start := node receiver stop + 1.
					node hasParentheses ifTrue: [stop := stop - 1]]"]].
			
	self selectFrom: start to: stop
```

**Comment by macta** [comment]
I also need to talk to @dionisiydk about keyboard handling in Calypso, as in Pharo 6, I had mapped Cmd+E to "extend selection" (aka widen selection), but I think that keystroke is taken in Calypso and he may have some ideas on how best to approach this.

**Comment by guillep** [comment]
Hi @macta, I cannot get from the comments if this is ready for integration :)

**Comment by macta** [comment]
Yes this is ready for integration - there are other things I’d like to introduce but they come after this one that gives the basis for finding nodes in broken code (eg the widen selection)

**Pull request merged**
