### PR TITLE
Update to fuel 303

### LINKED ISSUE #9282: Update to Fuel 3.0.3

### PR DESCRIPTION
**Pull request by theseion**
Fixes #9282.

### CODE REVIEW

**Comment by Ducasse** [comment]
Thanks Max!!!

**Comment by Ducasse** [comment]
since it touches newTools I will let esteban having a look @estebanlm

**Comment by theseion** [comment]
Yes please. I wasn't sure about that but since I'm the one maintaining Fuel, I want to have those things in the Fuel namespace. Or we decide to move `Fuel-Tools-Pharo` out of Fuel and it will have to be maintained by someone else as part of Pharo core. I'm ok with either solution (of course I would try to help maintain the tools in case we opt to move them out of Fuel, I just don't want to be the person responsible for them).

**Comment by MarcusDenker** [comment]
Full image can not be build:

```

MetacelloNotification: Fetched -> MonticelloMocks-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-9283/64/src --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-9283/64/src
MetacelloNotification: ...RETRY->Fuel-Platform-Pharo-Core-Tests
MetacelloNotification: ...RETRY->Fuel-Platform-Pharo-Core-Tests
MetacelloNotification: ...FAILED->Fuel-Platform-Pharo-Core-Tests
Could not resolve: Fuel-Platform-Pharo-Core-Tests [Fuel-Platform-Pharo-Core-Tests] in /builds/workspace/uest_and_branch_Pipeline_PR-9283/64/bootstrap-cache/pharo-local/package-cache tonel:///builds/workspace/uest_and_branch_Pipeline_PR-9283/64/src
MetacelloFetchingMCSpecLoader(MetacelloCommonMCSpecLoader)>>retryingResolvePackageSpecReferences:gofer:
```

**Comment by theseion** [comment]
Thanks. Just pushed a new commit. Let's hope that's the last one.

**Comment by theseion** [comment]
Well, I guess the decision has been made for me. Since NewTools is being loaded after Fuel, I can't load `Fuel-Tools-Pharo` because `StDebugger` isn't there yet. I've considered adding a dependency to NewTools but that feels bad, since
1. NewTools is an "internal" package and
2. the added functionality isn't really part of Fuel but part of the environment.

So I guess, it makes the most sense to move everything from `Fuel-Tools-Pharo` to NewTools. That includes the stuff for stack serialization and materialization and the command line handler.

I'll start working on that. Let me know if you don't agree or have a better solution.

**Comment by estebanlm** [comment]
question is... why fuel requires newtools at all :)
unless you add some extensions and *tools*, in which case, yes... is a new tool :)

**Comment by theseion** [comment]
Well exactly. Fuel shouldn't require NewTools. NewTools should require Fuel if it wants to.

**Comment by theseion** [comment]
I've created three packages:
- NewTools-Debugger-Fuel (which had existed before)
- NewTools-Debugger-Fuel-Tests (was FuelPlatform-Pharo-Core-Tests)
- NewTools-Fuel (was Fuel-Tools-Pharo)

I've adapted the NewTools baseline as I thought made sense. NewTools-Fuel is new in there and doesn't really belong to the Debugger group but I wasn't sure where else to put it.

**Comment by theseion** [comment]
Tests are green except for an allocation test and the Windows VM segfault.

@estebanlm can you take a look?

**Pull request merged**
