### PR TITLE
21698-ClassDefinitionShouldHideSlots

### PR DESCRIPTION
**Pull request by pavel-krivanek**
https://pharo.fogbugz.com/f/cases/21698/Class-definition-should-hide-slots-from-a-stateful-trait

introduce localSlots

### CODE REVIEW

**Review by dionisiydk — APPROVED** [review]
Good

**Review by MarcusDenker — APPROVED** [review]
Ok!

**Comment by MarcusDenker** [comment]
But: ChangeSetClassChangesTest>>testAddInstanceVariable is failing, we should look into that

**Comment by tesonep** [comment]
The error has to do with the notification of changes in the classes. 
When a class is modified, an announcement is propagated with the old and new class. 
However, the old class is not showing the definition correctly. 
The old definition is generated without slots. This is produced by:

- The #localSlot is filtering to keep only the slots that are defined in the class.
- When a class is modified the new class reuses the old slots when it can. 
- The reused slots are pointing to the new class as its defining class. 
- As a result the old class does not have any slot that is pointing to it as a defining class.

Maybe we should replace the slots in the old class with copies so it can describe themself properly. Copying the slots for the new class can generate problems, as the slots should could be potentially referenced from somebody else.

**Comment by dionisiydk** [comment]
We find the problem with @pavel-krivanek . 
The fix should be done in #copy method of Class. Now "aClass copy" produces a class which slots point to original class as definingClass which is wrong

**Comment by dionisiydk** [comment]
Fix can be of course not in the #copy method itself but in related code

**Review by dionisiydk — APPROVED** [review]
Good.
But it seems we don't have tests for class copy.
And I not see tests for owningClass and definingClass of slot.
Would be nice to add them

**Pull request merged**
