### PR TITLE
7240-PRRichTextComposer-does-not-need-to-use-PragmaCollector

### LINKED ISSUE #7240: PRRichTextComposer does not need to use PragmaCollector
PRRichTextComposer class>>#languageStylerFor: 

this can be rewritten to use Pragma allNamed:

Can I just submit to Pharo9 or is this some other repo?

### PR DESCRIPTION
**Pull request by MarcusDenker**
use Pragma>>#allNamed: instead of PragmaCollector in #languageStylerFor:, fixes #7240

### CODE REVIEW

**Comment by Ducasse** [comment]
Yes and this logic should really be revisited I did not look at it but to me it is far too complex for nothing

**Comment by Ducasse** [comment]
I will manage it the microdown repo. 
https://github.com/pillar-markup/MicroDown/issues/92

**Comment by MarcusDenker** [comment]
I close this but keep the issue open until this is in Pharo9. 
(but it shows again the negative side of "external packages": this case would be fixed. Now it is open until.. when?)

**Comment by MarcusDenker** [comment]
Checked with Stef: easiest is to commit it now, will later be merged upstream

**Pull request merged**
