### PR TITLE
5212-Executable-comment-checker-problem

### LINKED ISSUE #5212: Executable comment checker problem
I do not get why Bag >> includes: executable is reported as an error.
Same for 
Screenshot 2019-11-24 at 09 46 26

### PR DESCRIPTION
**Pull request by Ducasse**
Fixes: #5212 Some executable comments... .more to come.

### CODE REVIEW

**Comment by hogoww** [comment]
I worked on the drtest plugin this week end for that, and I wonder something. (will continue friday)
Do you think we should declare this comment wrongly written?
1 between:2 and:3 >>> false.
Because in this we send the message #>>> to 3 instead of the result.
(I did a checker that tries to '''''parse it''''' when it first fail . This works for half of the current drTest failures , so about 50.)
So either we authorise it, with the problems that come with, or we rewrite them if they are wrong.

**Comment by Ducasse** [comment]
Hi pierre
I fixed everything. We should use plain syntax.
I did not know you were working on it.

**Comment by Ducasse** [comment]
I'm now working on #5225 to avoid errors.

**Comment by hogoww** [comment]
Oh, you fixed the drtest pluggin as well?

**Comment by Ducasse** [comment]
Borken tests are related to blueInk removal and I will try to work on Enlumineur introduction this evening.

**Pull request merged**
