### PR TITLE
Queue pending mouse events

### LINKED ISSUE #6003: change on menu activation on list
May be this is not a bug. 
Now I noticed that in Epicea if I select a list of items and select one action, the action is only happening on the items currently getting the action (because when I select the menu item it deselect the list).
I experimented a bit and to have the action on the selected items I have to keep shift or option pressed. 

And I wonder if this is not related to the event change.

### PR DESCRIPTION
**Pull request by guillep**
Fix #6003

This PR should fix #6003 without having regressions in #5945 

 - refactor processEventsFromQueue:, split obtention of events in nextEventFrom:
 - add pendingEventQueue and queuePendingEvent:
 - make nextEventFrom: give priority to pending events
 - make MouseClickState queue pending mouseUp for next cycle

# Details

This solution restores the order of events (MouseDown, Click, MouseUp) while, not blocking MouseUp if a click starts a modal loop.
Changing the order of events like I did in #5964 is not a good solution because the event order makes sense for clients, and there are clients handling both clicks and mouseUps.
Also altering the order just moves the problem to mouseUp: If somebody tries to use a modal window on mouseUp => Boom same problem but with clicks.

This solution ensures that:
1) the order of events is the right one
2) no events get "blocked", so if an artificial event (e.g., click, double click) is created it can be queued and it will be managed in the next event cycle (from the same loop of from an inner modal loop).

## Background: How Mouse Events Work

The Hand is the one managing/dispatching the events.
When the Sensor (running in a higher priority thread) finds events, it puts them into a queue.
Eventually, the hand dequeues events and treats them.

Now, the mouse events have two main flavours: mouseDown and mouseUp
There is no click, nor double click event, they are simulated by the hand morph.

When a morph is interested on a click it has to
1. subscribe to mouse down first
2. when it receives a mouse down, it has to ask the hand "Hey! I would like clicks!"
Usually done by some code like this:

```smalltalk
anEvent hand waitForClicksOrDrag: h
  event: (anEvent transformedBy: tfm)
  selectors: { nil. nil. nil. #dragTarget:. }
  threshold: 5
```

When that happens, the hand changes its state, and stores a "MouseClickState object" that implements a kind of state machine to detect clicks and double clicks.

After the mouseDown, the morph receives a mouseUp (that should be transformed into a click).
So the hand, before sending the event to the morph, it makes it pass through the state machine which has some code like this:

```smalltalk
self click.    
aHand handleEvent: firstClickUp.
```

Where
1. click  will send a click event to the morph and
2. handleEvent: will send the mouseUp

## More details on the problem

One problem happens when a morph decides to BLOCK on a modal window on the click- :smile:
That means that mouseUp event will stay blocked in the stack, because the click does not return from the modal until modality finishes.
This means `handleEvent:` is never sent

In my fix the other day, I exchanged the order.
```smalltalk
aHand handleEvent: firstClickUp.
self click.
```

That solved that first problem. But that alters the order of the events.
So morphs used to receive MouseDown, Click, MouseUp now receive a MouseDown, MouseUp, then Click. This makes FastTable event logic loose the multiple selection.

### CODE REVIEW

**Comment by myroslavarm** [comment]
Hm is this also related to what Pavel was fixing regarding completion window not closing in https://github.com/pharo-project/pharo/pull/6017? There's so many UI bugs popping up :D

**Review by myroslavarm — APPROVED** [review]

**Comment by guillep** [comment]
It seems there is a broken tests introduced:

```
testNoUnusedTemporaryVariablesLeft – Windows64.ReleaseTests.CleanCode.NoUnusedTemporaryVariablesLeftTest
```

The other ones seem randomish

```
testPackageEnvironment – MacOSX64.Refactoring.Tests.Environment.RBBrowserEnvironmentTest
testExpressionInIncompleteParanthesis – Windows64.NECompletion.Tests.CompletionContextTest
testAllExamples – Windows64.Hiedra.Tests.Model.HiExamplesTest
```

**Comment by guillep** [comment]
Nope. This problem was introduced in build 178.
Pavel's problem exists already in build 172 (quick check).

**Comment by Ducasse** [comment]
Broken tests are unrelated.

**Pull request merged**
