### PR TITLE
3396-Integrate-Calypso-Packages-in-Pharo

### LINKED ISSUE #3396: Integrate Calypso Packages in Pharo
We need to put Calypso packages inside the Pharo repository.
We need that this is not optimal but the alternative to it (editing calypso in a separate repository) creates a ripple of effect of releases (tagging, changing baseline, PR, integration).
The objective is to ease updates to calypso's cross cutting aspects (Rubric usage, refactorings...).

Eventually this should be managed by subprojects/submodules/subtrees but the solution is not there yet.

### PR DESCRIPTION
**Pull request by guillep**
Fixes #3396

### CODE REVIEW

**Comment by jecisc** [comment]
Maybe we should also have System-Commands?

**Comment by guillep** [comment]
> Maybe we should also have System-Commands?

They are there, with commander and Class Annotation

**Comment by jecisc** [comment]
Ok, the email I got did not have all changes. Sorry for the noise.

**Comment by Ducasse** [comment]
The changes are breaking the build

[32] Loaded -> Commander-Activators-Shortcut-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-3397/32/src --- cache
[32] Loaded -> Commander-Activators-ContextMenu-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-3397/32/src --- cache
[32] Loaded -> Commander-Activators-DragAndDrop-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-3397/32/src --- cacheMessageNotUnderstood: ByteSymbol>>descending
[32] ByteSymbol(Object)>>doesNotUnderstand: #descending
[32] ContextualClassAnnotationExample2 class(ClassAnnotation class)>>createContainerForRegistry
[32] [ aClassAnnotation class createContainerForRegistry ] in ClassAnnotationRegistry>>addAnnotation: in Block: [ aClassAnnotation class createContainerForRegistr...etc...
[32] [ self at: key put: aBlock value ] in IdentityDictionary(Dictionary)>>at:ifAbsentPut: in Block: [ self at: key put: aBlock value ]
[32] IdentityDictionary(Dictionar

**Pull request merged**
