### PR TITLE
7338-Epicea-should-not-use-oldDefinition-for-class

### LINKED ISSUE #7338: Epicea should not use oldDefinition for class
Screenshot 2020-09-19 at 10 44 23

### PR DESCRIPTION
**Pull request by Ducasse**
fixes: #7338 make epicea works on definition and not old definition. 
Rigth now one test is failing: testClassRemoval and I may need help from Martin.

### CODE REVIEW

**Comment by Ducasse** [comment]
I do not get why this test is breaking

```
testClassRemoval

	| aClass className category |
	aClass := classFactory newClass.
	aClass classSide instanceVariableNames: 'hey'.
	className := aClass name.
	category := aClass category.
	aClass removeFromSystem.
	self setHeadAsInputEntry.

	self assert: (inputEntry content isKindOf: EpClassRemoval).
	self deny: (self class environment hasClassNamed: className).
	self revertInputEntry.
	self assert: (self class environment hasClassNamed: className).
	self assert: (self class environment classNamed: className) category equals: category.
	self assert: (self class environment classNamed: className) classSide instVarNames equals: #('hey').
```

**Comment by tinchodias** [comment]
I'm trying to understand:

When the test fails, I opened the World->Tools->Code Changes (Epicea Browser) and checked what is recorded by the monitor. The class is correctly added as:
```
Object subclass: #ClassForTestToBeDeleted6
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'CategoryForTestToBeDeleted-Default'.

ClassForTestToBeDeleted6 class
	instanceVariableNames: 'hey'
```

But wrongly deleted as:
```
Object subclass: #ClassForTestToBeDeleted6
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Unclassified'.

ClassForTestToBeDeleted6 class
	instanceVariableNames: 'hey'
```

So, when the test reverts the deletion, the class is recreated "correctly", with Unclassified.

The Epicea Browser obtains that definitions via `EpContentStringVisitor>>#stringForBehavior:` using `RGBehaviorDefinition>>#definitionSource`

**Comment by tinchodias** [comment]
OK, bingo... found the bug. I paste the new code below that fixes the bug for the moment. @Ducasse you will love the code... I'm sorry.

**Context**: At some point of the history of EpMonitor, I ended adapting in a very nasty way from what the system announces and what we wanted to record/redo/undo. This is the worst point that performs this adaptation, and not casually it had the bug...

`class: EpMonitor`
```smalltalk
behaviorRemoved: aClassRemovedAnnouncement

	self handleAnyErrorDuring: [
		"Workaround: the announcement occurs after class is renamed to AnObsolete 
		and removed from package."
		
		| classRemoved |
		classRemoved := aClassRemovedAnnouncement classRemoved asEpiceaRingDefinition.

		"Fix class name (remove AnObsolete prefix)"
		classRemoved definitionSource: 
			(classRemoved definitionSource
				copyReplaceAll: aClassRemovedAnnouncement classRemoved name printString
				with: aClassRemovedAnnouncement classRemoved originalName printString).

		"Fix class name in the metaclass"
		classRemoved classSide definitionSource: 
			(classRemoved classSide definitionSource
				copyReplaceAll: aClassRemovedAnnouncement classRemoved name
				with: aClassRemovedAnnouncement classRemoved originalName).

		"Fix category"
		classRemoved definitionSource: 
			(classRemoved definitionSource
				copyReplaceAll: 'package: ', 'Unclassified' printString
				with: 'package: ', aClassRemovedAnnouncement categoryName printString).

		classRemoved name: aClassRemovedAnnouncement classRemoved originalName.
		classRemoved category: aClassRemovedAnnouncement categoryName.
		classRemoved package: aClassRemovedAnnouncement packageAffected name.

		(aClassRemovedAnnouncement classRemoved methods, aClassRemovedAnnouncement classRemoved classSide methods) 
			do: [:each | self behaviorRemovedImpliesMethodRemoved: each defaultPackageName: classRemoved package ].

		aClassRemovedAnnouncement classAffected isTrait
			ifTrue:  [ self traitRemoved: classRemoved ]
			ifFalse: [ self classRemoved: classRemoved ] ]
```

(The diff is in the `"Fix category"`).

**Comment by Ducasse** [comment]
I thought the problem was coming from ClassFactoryForTestCase

**Comment by Ducasse** [comment]
I will merge your PR. Thanks!!

**Comment by tinchodias** [comment]
Great! I have an idea of how to remove this code... I will try in the afternoon

**Pull request merged**
