### PR TITLE
Enhance double click and drag behaviour

### LINKED ISSUE #12428: Double-click often selects only part of the word
**Bug description**
When user selects a word by double cliking on it, it often selects only part of the word.

Pharo_DZveYJC10q

It is caused by small movement of the mouse during double click. It is highly annoying and it was introduced in Pharo 11.

I discovered that it was introduced in the build 276 fixing https://github.com/pharo-project/pharo/issues/11727
The commit causing it is: https://github.com/pharo-project/pharo/pull/11838/files by @akevalion

**To Reproduce**
1. double click on a word and try to slightly move mouse right during double click

### PR DESCRIPTION
**Pull request by akevalion**
issues related:
- https://github.com/pharo-project/pharo/issues/12428

Old pull request https://github.com/pharo-project/pharo/pull/12445

### CODE REVIEW

**Comment by MarcusDenker** [comment]
It seems that https://github.com/pharo-project/pharo/pull/12460/ touches #previousWord, too

**Comment by akevalion** [comment]
Hello @MarcusDenker  method `previousWord:` in was to fix an error when you select a word sometimes to get an error.

I will discard my changes in `previousWord:` and I will add a new issue about the error in text selection

**Comment by MarcusDenker** [comment]
There is still a merge conflict after merging https://github.com/pharo-project/pharo/pull/12460

**Comment by akevalion** [comment]
I have reverted changes(spaces and clean code) on that method.

**Comment by akevalion** [comment]
It looks green now

**Comment by akevalion** [comment]
@MarcusDenker @guillep can we integrate this PR in Pharo?

**Review by privat — APPROVED** [review]
read the code and tried the image, looks good to me

**Comment by MarcusDenker** [comment]
As we have two testers, this should be save to merge

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
