### PR TITLE
22084-Menubar-root-items-without-children-should-be-clickable

### PR DESCRIPTION
**Pull request by jecisc**
If a menubar item does not have a submenu, create an item that can directly launch an action.

I would like some review on this because I'm not certain it's the best way :(

https://pharo.fogbugz.com/f/cases/22084/Menubar-root-items-without-children-should-be-clickable

### CODE REVIEW

**Comment by estebanlm** [comment]
Mmm... there *shoudln't be* root items without elements.
As I said in discord, that would create a toolbar, not a menubar.

**Comment by jecisc** [comment]
I did it because there was the request twice already. 

Maybe Pharo should have a menubar but let the users create a toolbar with their own world menu pragma?

**Comment by estebanlm** [comment]
honestly... no :)
I missed when people asked for it or I would have argue there. 
But basically, you can have a menu, a toolbar, a menu+toolbar or, if you are microsoft, you can have a ribbon (yup, they patented it so just they can do it).
what you cannot have is a menu that behaves like a toolbar. 
that's why I ask for: 
- no entries without children.
- no icons in roots

**Comment by jecisc** [comment]
So, should I let the modifications of the docking bar and then create a new "ToolbarMorph" with methods to add root elements with no children?

For the icon, there is only one, the pharo one. Like there is only one in OSX.

**Comment by jecisc** [comment]
In anycase I found a bug :( The submenus are not highlighted when we go in them.

**Comment by estebanlm** [comment]
so?

**Comment by jecisc** [comment]
I let you decide. 

Proposition 1: I correct the conflict, we merge it and we do not use it for Pharo Menubar to keep it as a Menubar and not a Toolbar.
Proposition 2: We create a new Morph that is a ToolbarMorph and that will act exactly as the Menubar, but with clickable buttons.

**Comment by estebanlm** [comment]
if easiest is 1, let's go for 1

**Comment by jecisc** [comment]
I merged but I'll need to test the generated image. I merge by hand.

**Comment by estebanlm** [comment]
ok then :)

**Pull request merged**
