### PR TITLE
22067-Duplicated-packages-in-Pharo-baselines-SUnit-and-BasicTools

### PR DESCRIPTION
**Pull request by jecisc**
Remove from BasicTools packages already defined in SUnit.

https://pharo.fogbugz.com/f/cases/22067/Duplicated-packages-in-Pharo-baselines-SUnit-and-BasicTools

### CODE REVIEW

**Comment by jecisc** [comment]
Errors not related.

**Comment by astares** [comment]
But Jenkins is not directly related to SUnit - maybe an own "ContinuousIntegration" group makes more sense.

**Comment by jecisc** [comment]
Probably but I try to do small PR since I don't know the bootstrap enough yet.

**Comment by estebanlm** [comment]
this is conflicting now

**Comment by jecisc** [comment]
Corrected.

**Pull request merged**
