### PR TITLE
Ensure subMenu is opened (backport)

### PR DESCRIPTION
**Pull request by StephanEggermont**
Solves Issue #2331, #2333. Backport for Pharo 7. See 22084 in Fogbugz

### CODE REVIEW

**Comment by estebanlm** [comment]
why this backport? why this is a critical fix?

**Comment by StephanEggermont** [comment]
It breaks client code

**Comment by estebanlm** [comment]
why? AFAIK, this never worked before (or it does not works since a lot of time).
and which client code?

**Comment by StephanEggermont** [comment]
It worked in Pharo 6. I have code that needs to work in Pharo 7 so I need the fix backported

**Comment by StephanEggermont** [comment]
unrelated failures

**Comment by estebanlm** [comment]
now that I remember, there was a reason why this was removed. 
@jecisc you were working there, do you have an observation to do ?

**Review by jecisc — APPROVED** [review]
The PR seems fine for me. 

I introduce this problem while removing duplication. I forgot one parameter in this method.

**Comment by jecisc** [comment]
Before each menu constructor was duplication the logic. I changed it to build in one method and have the other ones calling this one.

**Pull request merged**
