### PR TITLE
2466-Remove-unused-variables

### LINKED ISSUE #2466: Remove unused variables
We have a lot of unused variables. I'll do a PR to clean some of them.

```
Class: FileStream var: rwmode
Class: CategoryRenamed var: from
Class: CategoryRenamed var: to
Class: GLMTransmissionTriggered var: transmission
Class: GLMTestPane var: seenTransmissions
Class: GLMImplicitBrowser var: presentations
Class: GLMExpander var: rootPane
Class: GLMWizard var: wizardSize
Class: GLMWizard var: genericStep
Class: GLMWizard var: terminateButtonAction
Class: GLMWizard var: previousButtonAction
Class: GLMWizard var: nextButtonAction
Class: GLMWizard var: cancelButtonAction
Class: GLMTextualPresentation var: selectedText
Class: GLMTextualPresentation var: text
Class: ConfigurationCommandLineHandler var: version
Class: VTermOutputDriver class var: stdoutTerminalInstance
Class: VTermOutputDriver class var: stderrTerminalInstance
Class: EncodedCharSet class var: compoundTextSequence
Class: SpecPragmaCollector class var: behavior
Class: EyeInspector class var: useAutoRefresh
Class: RBClassToRename class var: notUsed
Class: MCMockClassB class var: ciVar
Class: DictionaryTest class var: testToto
Class: DictionaryTest class var: pt1
Class: StackTest class var: testSize
Class: FLBlockClosureSerializationTest class var: interval
Class: SimpleHierarchicalListMorph class var: expandedForm
Class: SimpleHierarchicalListMorph class var: notExpandedForm
Class: ATraitedClass class var: myMethodDict
Class: ATraitedClass class var: composition
Class: ReRuleManager class var: uniqueInstance
Class: SugsMockContext class var: anInstanceVar
Class: MorphicCoreUIManager var: interactiveParser
Class: MorphicCoreUIManager var: activeTranscript
Class: AthensCairoPatternPaint var: surface
Class: AthensCairoPatternPaint var: origin
Class: AthensCairoPatternPaint var: direction
Class: AthensCairoPatternPaint var: extent
Class: UnlimitedInstanceVariableSlot var: baseSlotSize
Class: NullTermInfo var: out
Class: TermInfoCharacter var: cache
Class: RPackageSet var: overriddenMethods
Class: SmalltalkImage var: deferredStartupActions
Class: SmalltalkImage var: session
Class: CompilationContext var: usesFullBlockClosure
Class: ChunkFileFormatParser var: nextChar
Class: MorphicTabManagerAdapter var: isClosedHolder
Class: ListPresenter var: shortcutsHolder
Class: FastTablePresenter var: displayBlock
Class: SliderPresenter var: isSetting
Class: TreePresenter var: selectedItem
Class: InspectorNavigator var: listOfOpenedInspectors
Class: KMDescriptionPresenter var: updatingBlock
Class: MessageBrowser var: browsedEnvironment
Class: IceTipMergePreviewBrowser var: mergeType
Class: IceTipCommentPanel var: message
Class: IceTipFiletreeToTonelDialog var: model
Class: GLMTreeMorphNodeModel var: onSelection
Class: PSMCClassChangeWrapper var: conflict
Class: GLMTreeMorphModel var: onSelection
Class: RubMethodEditingExample var: code
Class: ThemeSettings var: secondarySelectionColor
Class: Workspace var: lineEnding
Class: RBClassToRename var: rewriteRule
Class: RBClassToRename var: builder
Class: RBClassToRename var: class
Class: MCMockClassA var: ivar
Class: MCMockClassB var: ivarb
Class: StartupAction var: nameOfItem
Class: StartupPreferencesHandler var: firstLink
Class: MetacelloGoferPackage var: version
Class: ArrayTest var: otherArray
Class: ArrayTest var: sizeCollection
Class: BagTest var: elementExistsTwice
Class: BagTest var: element
Class: IdentityBagTest var: elementAlreadyIncluded
Class: IdentityBagTest var: identityBagWithoutElement
Class: OrderedCollectionTest var: elementExistsTwice
Class: OrderedCollectionTest var: collectionNotIncluded
Class: ClassTest var: renamedName
Class: FBDDecompilerTest var: decompiler
Class: SlotClassBuilderTest var: aClass
Class: SlotClassBuilderTest var: instance
Class: SlotClassBuilderTest var: anotherClass
Class: SlotClassBuilderTest var: yetAnotherClass
Class: SlotClassBuilderTest var: yetYetAnotherClass
Class: SlotClassVariableTest var: announcement
Class: SlotClassVariableTest var: collectedAnnouncements
Class: HiNodesAndLinksIteratorWithTwoLinkModelsTest var: d
Class: Array2DTest var: matrix3
Class: SplitJoinTest var: eg
Class: SplitJoinTest var: stringToSplit
Class: LinkedListTest var: collectionWithNil
Class: LinkedListTest var: sameAtendAndBegining
Class: GuideTest var: guide
Class: DateAndTimeLeapTest var: localTimeZoneToRestore
Class: UnicodeTest var: rng
Class: UnicodeTest var: nonCharacters
Class: IRBuilderTest var: testIvar
Class: OCBytecodeGeneratorTest var: a
Class: OCSourceCode2BytecodeTest var: instVar
Class: RBRefactoringTest var: changeSet
Class: MetacelloScriptingStdTstHarness var: monticelloRepository
Class: MetacelloScriptingStdTstHarness var: configurationRepository
Class: MCGitlabRepositoryTest var: hostname
Class: RPackageReadOnlyCompleteSetupTest var: p4
Class: RPackageTraitTest var: b1
Class: RPackageTraitTest var: a2
Class: RPackageTraitTest var: b2
Class: RPackageTraitTest var: a3
Class: RPackageOrganizerTest var: quadrangleClass
Class: MCClassDefinitionTest var: previousChangeSet
Class: MCMergingTest var: conflictBlock
Class: MCRepositoryTest var: ancestors
Class: ZipArchiveTest var: fileSystem
Class: DynamicMessageImplementorTest var: instVar
Class: DiskFileAttributesTests var: temporaryFile
Class: FreeTypeCacheTest var: cache1K
Class: GTEventDeliveryTest var: announcer
Class: KMCategoryTest var: categoryContainer
Class: MorphTest var: world
Class: ReDeadMethodTest var: validTestPackage
Class: AuthorTest var: author
Class: RBTransformationTest var: changes
Class: ClyItemFilterTestCase var: filter
Class: ClyBrowserQueryResultTestCase var: actualObjects
Class: ClyGroupedCritiquesTest var: critic
Class: ClyVariableReadersQueryTest var: var2
Class: ClyVariableWritersQueryTest var: var2
Class: ClySortFunctionTestCase var: function
Class: ClyNavigationHistoryTestCase var: navigationState
Class: UnicodeTestRNG var: nonCharacters
Class: WarpBlt var: sourceRGBmap
Class: FFIExternalStructureType var: structureSize
Class: GLMPaginatedMorphTreeMorph var: stopStepping
Class: LazyTabGroupMorph var: tabSelectorWidth
Class: IconicButton var: oldBorder
Class: GrowlMorph var: attr
Class: HandMorph var: keyboardListeners
Class: HandMorph var: eventSource
Class: HandMorph var: lastSystemEvent
Class: RubColumnDisplayer var: tabWidth
Class: RubTextSegmentIconBox var: icon
Class: MorphHandlingMiddleButton var: menu
Class: GLMInteractableBrick var: announcer
Class: GLMEmptyPopupBrick var: padding
Class: GLMEditorPopupBrick var: titleBrick
Class: GLMEditorPopupBrick var: titleText
Class: GTSpotterCategoryBrick var: listBrick
Class: GLMMorphBrick var: resizing
Class: GTSpotterHeaderBrick var: stepsBrick
Class: MenuRegistration var: ordering
Class: StrikeFont var: strikeLength
Class: StrikeFont var: xOffset
Class: StubFixedFont var: substitutionCharacter
Class: StubFixedFont var: displaySelector
Class: SpecTableLayoutAddSpacer var: commands
Class: CharacterScanner var: runStopIndex
Class: CharacterScanner var: wantsColumnBreaks
Class: DisplayScanner var: paragraphColor
Class: EditingState var: secondarySelectionToken
Class: Editor var: selectionShowing
Class: FLAnalyzer var: globalMappers
Class: FT2BitmapSize var: height
Class: FT2BitmapSize var: width
Class: FT2BitmapSize var: size
Class: FT2BitmapSize var: xPpEm
Class: FT2BitmapSize var: yPpEm
Class: KMTarget var: realTarget
Class: KMTarget var: directKeymaps
Class: KMTarget var: perInstanceCategories
Class: Locale var: shortDate
Class: Locale var: longDate
Class: Locale var: time
Class: Locale var: decimalSymbol
Class: Locale var: digitGrouping
Class: Locale var: currencySymbol
Class: Locale var: currencyNotation
Class: Locale var: measurement
Class: Locale var: offsetLocalToUTC
Class: Locale var: offsetVMToUTC
Class: Locale var: dstActive
Class: LzwGifEncoder var: bitMask
Class: LzwGifEncoder var: bitStream
Class: LzwGifEncoder var: outBlock
Class: RubCharacterScanner var: runStopIndex
Class: RubShoutStylerDecorator var: shoutIsAvailable
Class: SpecLayout var: currentOffset
Class: SpecLayout var: currentProportional
Class: SpecLayout var: numberOfProportionals
Class: SpecLayout var: lastFractionIndex
Class: SpecLayout var: autoFractionComputation
Class: SpecLayout var: size
Class: SpecLayoutFrame var: layout
Class: StackFilter var: stack
Class: ToggleMenuItemShortcut var: font
Class: RubScrolledTextModel var: textSegments
Class: GradientPaint var: stops
Class: AthensBalloonPath var: last
Class: AthensEllipticalArcSegment var: radii
Class: AthensEllipticalArcSegment var: phi
Class: AthensEllipticalArcSegment var: large
Class: AthensEllipticalArcSegment var: sweep
Class: AthensEllipticalArcSegment var: endPoint
Class: AthensCurveFlattener var: inverseTransform
Class: CairoUTF8Converter var: len
Class: CairoUTF8Converter var: asm
Class: CairoFreetypeFontRenderer var: surface
Class: FTEasyListDataSource var: header
Class: FTTreeItem var: children
Class: RBMethodRefactoring var: class
Class: AthensTextScanner var: paragraph
Class: GlyphRenderer var: font
Class: FT2GlyphRenderer var: hAdvance
Class: ShCBClassWithInstanceVariables var: inheritedSlot
Class: ATraitedClass var: somethingElse
Class: ATraitedClass var: something
Class: T2TestClass var: somethingElse
Class: SlotExampleMovie var: year
Class: RBPharoBootstrapRule var: renrakuRule
Class: OmFileStore var: entryReader
Class: OmSessionStore var: alternativeStore
Class: EpApplyPreviewer var: logBrowserModel
Class: EpApplyPreviewer var: sourceEntries
Class: HiTestNode var: owner
Class: WriteBarrierAnotherStub var: var2
Class: WriteBarrierAnotherStub var: var3
Class: WriteBarrierAnotherStub var: var4
Class: WriteBarrierAnotherStub var: var5
Class: WriteBarrierAnotherStub var: var6
Class: WriteBarrierAnotherStub var: var7
Class: WriteBarrierAnotherStub var: var8
Class: WriteBarrierAnotherStub var: var9
Class: WriteBarrierStub var: var2
Class: WriteBarrierStub var: var3
Class: WriteBarrierStub var: var4
Class: WriteBarrierStub var: var5
Class: WriteBarrierStub var: var6
Class: WriteBarrierStub var: var7
Class: WriteBarrierStub var: var8
Class: WriteBarrierStub var: var9
Class: MockForCompilation var: var1
Class: OCMockCompilationClass var: collection
Class: RBLintRuleTest var: foo1
Class: RBFooLintRuleTest var: result
Class: GLMTableColumn var: defaultSortBlock
Class: GlamourousBenchmark var: progressBarSize
Class: GlamourousBenchmark var: progress
Class: GLMMorphicActionListRenderer var: labelMorph
Class: GLMMorphicFinderRenderer var: container
Class: GLMMorphicPaneWithoutTitleRenderer var: container
Class: GLMMorphicValidatorPaneRenderer var: container
Class: GLMMorphicWatcherRenderer var: process
Class: GTSnippets var: instance
Class: GTPlayPage var: modificationTime
Class: GTFilterFuzzy var: matcher
Class: GTSpotterCandidatesListProcessor var: queryMatchingBlock
Class: ReAbstractRule var: one
Class: RBLiteralArrayContainsSuspiciousTrueFalseOrNilRule var: matcher
Class: SugsMockContext var: anInstanceVar
Class: NECTestClass var: third
Class: NECTestClass var: fourth
Class: RBCompositeVariableTransformation var: variableName
Class: RBCompositeVariableTransformation var: isClassVariable
Class: RBDummyLintRuleTest var: foo1
Class: RBFooDummyLintRuleTest var: result
Class: LGitReadStream var: rawBuffer
Class: IceTipInstallVersionCommand var: selectedCommit
Class: IceTipRefreshCommitCommand var: tool
Class: ClyCriticContext var: analyzedObject
Class: IceBasicProject var: repository
Class: IceBasicProject var: repositoryProperties
Class: IceChangeImporter var: sourceSnapshot
Class: IceChangeImporter var: targetSnapshot
Class: IceChangeImporter var: operation
Class: IceCommit var: packageCache
Class: IceMCPackageImporter var: packageName
Class: IceNode var: cachedChanges
Class: IceOperation var: diff
Class: IceOperation var: modifiedNode
Class: IceSavedPackageVersion var: originatingCommit
Class: IceTipCommitAction var: publish
Class: IceTipVersionModel var: commitModels
Class: IceTipDiffModel var: diff
Class: IceTipRepositoriesModel var: projects
Class: ClyProjectManager var: systemEnvironment
Class: ClyClass1FromP1 var: instanceSideVar2
Class: ClySubclassN1OfClass1FromP1 var: subclassSameVar
Class: ClySubclassN1OfClass1FromP1 var: subclassN1Var
Class: ClySubclassN2OfClass1FromP1 var: subclassSameVar
Class: ClyClass2FromP1 var: instVar
```

### PR DESCRIPTION
**Pull request by jecisc**
Remove unused instance variables.

Fixes #2466

For now it does not fix everything but it's a first step

### CODE REVIEW

**Comment by jecisc** [comment]
I cannot commit class instance var removal because of https://github.com/pharo-vcs/iceberg/issues/1168 :(

**Comment by jecisc** [comment]
I think I did not removed variables used for tests but I am not 100% sure. I'll wait the checks to verify.

**Comment by jecisc** [comment]
Some broken tests *are* related. I'll fix them next week.

**Comment by MarcusDenker** [comment]
failing tests now seem to be the ones that fail always (not related to the change)

**Review by MarcusDenker — APPROVED** [review]
looks good

**Comment by estebanlm** [comment]
this was not in "ignore" status? :P

**Comment by jecisc** [comment]
I corrected the tests failures so it was integrable. I just forgot to remove the ignore.

**Pull request merged**
