### PR TITLE
22232 the test runner should allow to do code coverage on packages having test in the their name

### PR DESCRIPTION
**Pull request by juliendelplanque**
Now it is possible to run coverage on packages containing "test" in their name.
However, the coverage is not done on methods of subclasses of TestCase, so no problem.

### CODE REVIEW

**Comment by bergel** [comment]
Just wondering. Why avoiding the coverage to be run on the test classes? It does not do any harm to do so actually. A unit test may have non-test methods, and knowing whether they are covered is relevant.

**Comment by juliendelplanque** [comment]
Well, for me computing coverage on test methods makes no sense because all methods with a name beginning by 'test' will be executed by the TestRunner.

So what I did is to classes inheriting from TestCase.

But maybe we can do as you said. However, this should be discussed with a large part of the community. My change does not change the hold behaviour but provide a smarter filter.

**Review by pavel-krivanek — APPROVED** [review]
ok

**Comment by bergel** [comment]
But, you can have methods defined in a TestCase that do not begins with 'test'. Such as utility methods
Anyway, no stress :-) Your change is good

**Comment by juliendelplanque** [comment]
@bergel I agree.

But then, we should still reject the methods beginning by 'test' and compute the coverage on utility methods? :-)

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
