### PR TITLE
4419-WeakValueDictionaryrehash-is-breaking-weak-associations

### LINKED ISSUE #4419: WeakValueDictionary>>#rehash is breaking weak associations
WeakValueDictionary works using WeakValueAssociations inside to get the weak part. 

MCDataStream is using this kind of dictionaries for WriteSelectors and ReadSelectors. But if we inspect the instances, they contain Associations and not WeakValueAssociations! Thus, they are not weak.

IMO, we should find how it is possible to do that and correct it in WeakValueDictionary and update MCDataStream. 

I discovered this because I wanted to move the nil wrapping logic of the WeakValueDictionary from the dictionary to the association to make this kind of association easier to use and I got errors saying that Association did not understand messages implemented on WeakValueAssociation.

### PR DESCRIPTION
**Pull request by jecisc**
Fix WeakValueDictionary to not lose the WeakValueAssociations during rehash.

Fixes #4419

### CODE REVIEW

**Review by MarcusDenker — APPROVED** [review]
ok

**Comment by MarcusDenker** [comment]
There is a git conflict now

**Comment by MarcusDenker** [comment]
Now strangely the boostrap is failing:

Loaded -> Transcript-NonInteractive-Tests-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-4421/32/src --- cacheTonelParseError: Can't parse method body
TonelSourceScanner>>scan
TonelParser>>methodBody
TonelParser>>methodDef
TonelParser>>methodDefList
TonelParser>>document
TonelParser>>start

**Comment by guillep** [comment]
> Now strangely the boostrap is failing:
> 
> Loaded -> Transcript-NonInteractive-Tests-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-4421/32/src --- cacheTonelParseError: Can't parse method body
> TonelSourceScanner>>scan
> TonelParser>>methodBody
> TonelParser>>methodDef
> TonelParser>>methodDefList
> TonelParser>>document
> TonelParser>>start

Because there effectively was a tonel syntax error: https://github.com/pharo-project/pharo/pull/4421/commits/590f862b1fa2b1ea84fbe565dbec6ed3134646d8

**Comment by MarcusDenker** [comment]
Failing test not related (will add another issue tracker entry for that)

**Pull request merged**
