### PR TITLE
21999-New-taskbar-design-proposal

### PR DESCRIPTION
**Pull request by jecisc**
Propose new taskbar design for Pharo light and dark theme. 

https://pharo.fogbugz.com/f/cases/21999/New-taskbar-design-proposal

### CODE REVIEW

**Comment by jecisc** [comment]
This is a new taskbar design proposal. 

# Changes

Compared to the old one, this one is not transparent, so the user knows there is a morph and that he cannot click to open the world menu. 

Also, I tried to get a look closer to current UIs because I thought the previous one was a little old style.

# Wait before integration

 Before this PR can be integrated it needs this PR to be integrated: 

https://github.com/pharo-project/pharo/pull/1384

Without this PR the dark theme taskbar is broken.

Also, I would like to have feedback from the community so I'll send a mail to the pharo-dev ML.

# Preview

Here is two GIF to show the taskbar with light and dark theme:

## Light theme

whitetheme

## Dark theme 

darktheme

**Comment by svenvc** [comment]
Looks great ! 

Do you get a World menu is you click in the unused area ?

**Comment by jecisc** [comment]
For now, no.

But I would like to add it after this one.

Also, with Pavel, we think we should add a first button to open the world menu. This allows removing the margin when we maximize a window in Pharo. For now, the margin is only here because we need the world menu a lot.

**Comment by jecisc** [comment]
I created an issue: https://pharo.fogbugz.com/f/cases/22000/Right-click-on-the-taskbar-empty-space-should-open-the-world-menu

**Comment by Ducasse** [comment]
Looks good!

**Comment by pavel-krivanek** [comment]
I have tried the prebuilt image and it works and looks fine. Maybe the black bottom line is too much intensive. Some grey one would be nicer

**Comment by jecisc** [comment]
@pavel-krivanek Ok, I'll try to change that tomorrow

**Comment by philippeback** [comment]
Nice work.
If we make the world menu go to the left of the taskbar, I still want it on the screen.
And if we do it "windows-like", then why not a "show desktop" when mousing to the bottom right? (hiding/showing all windows)

**Comment by philippeback** [comment]
And a pluggable widgets area to the right. (so we can put in widgets).

**Comment by bencoman** [comment]
On Mon, 28 May 2018, 03:14 Philippe Back, <notifications@github.com> wrote:

> Nice work.
> If we make the world menu go to the left of the taskbar, I still want it
> on the screen.
> And if we do it "windows-like", then why not a "show desktop" when mousing
> to the bottom right? (hiding/showing all windows)
>
+1. I use this a lot on MS Windows and would be a nice addition. (Maybe on
a different issue.)

>

**Comment by jecisc** [comment]
Yes, it would be cool in another issue. It will not be as simple as I first though since the taskbar can be in multiple lines and I don't know if it's easy to add a morph in full height when all the others are in lines.

**Review by estebanlm — APPROVED** [review]

**Comment by guillep** [comment]
Hi! I like it!

For the world menu, I'd like a bar on the top, I'd like to pair program one with you if you're coming one of these days :)

**Review by guillep — APPROVED** [review]
Great!

**Comment by akgrant43** [comment]
+1

I'm looking forward to seeing this integrated and the world menu added to the task bar (and proper full screen windows).

**Comment by jecisc** [comment]
@pavel-krivanek I updated the bottom line color to use Grey 700 and Grey 600 from: https://www.materialui.co/colors

**Comment by peteruhnak** [comment]
The placement of the old taskbar was "configurable" (`World taskbars first listDirection: #rightToLeft`), is this still possible? E.g. I am using dual-monitor setup (with a secondary on the left side), and when I drag Pharo over both screens, it is better to keep the taskbar on the right.

> Also, with Pavel, we think we should add a first button to open the world menu. This allows removing the margin when we maximize a window in Pharo. For now, the margin is only here because we need the world menu a lot.

Is this just `SystemWindow fullscreenMargin: 0.` , or a different change, that would actually cover the taskbar?

**Comment by jecisc** [comment]
This one only changes the style. What I need to check is if the setting still works with this one: https://github.com/pharo-project/pharo/pull/1450

**Comment by jecisc** [comment]
And yes, this margin.

**Comment by MarcusDenker** [comment]
do not forget to remove the [IGNORE] when it is ready

**Comment by MarcusDenker** [comment]
#1384 was merged

**Comment by jecisc** [comment]
Since the dependant PR was integrated and there are positive reviews I'll remove the [IGNORE] after testing the generated image from the CI check.

**Pull request merged**
