### PR TITLE
7770 cleaning old definition printer

### PR DESCRIPTION
**Pull request by Ducasse**

### CODE REVIEW

**Comment by Ducasse** [comment]
I do not get why it would be breaking since it was internal method logic refactoring.
let us try again.

**Comment by Ducasse** [comment]
I would like to test this now that #7816 has been integrated.

**Comment by Ducasse** [comment]
The tests are broken which is already an improvement.

**Comment by Ducasse** [comment]
To see with the merge of marcus fix if the test passes

**Comment by MarcusDenker** [comment]
Yes, looks better. Still some other tests failing, but far less

**Comment by Ducasse** [comment]
This is strange because I do not see the difference.

##one 
T2OldPharoClassDefinitionPrinterTest>>#testTrait3AndTagTests.
Got 'Trait named: #Trait3  uses: Trait2  package: ''Tests-Traits-MOP''' instead of 'Trait named: #Trait3   uses: Trait2   package: ''Tests-Traits-MOP'''.
Stacktrace

TestFailure
Got 'Trait named: #Trait3
	uses: Trait2
	package: ''Tests-Traits-MOP''' 
instead of 'Trait named: #Trait3
	 uses: Trait2
	 package: ''Tests-Traits-MOP'''.

## two 
testAddTraitPattern

## three
T2OldPharoClassDefinitionPrinterTest>>#testTBehavior

**Comment by MarcusDenker** [comment]
My fixe was for the other failing ones (the ones that made DNU for named: package, they where from Epicea)

**Comment by MarcusDenker** [comment]
(i think we did the close/reopen twice)

**Comment by Ducasse** [comment]
A new issue has been pushed: https://github.com/pharo-project/pharo/pull/7845

**Pull request closed without merging**
