### PR TITLE
2813-Failing-tests-in-MorphicTextInputFieldAdapterTest

### LINKED ISSUE #2813: Failing tests in MorphicTextInputFieldAdapterTest
Failing for Pharo8 on all 3 architectures:

MorphicTextInputFieldAdapterTest testChangeWidgetTextUpdatesPresenter 
MorphicTextInputFieldAdapterTest testMaxLengthIsSetInWidget

### PR DESCRIPTION
**Pull request by MarcusDenker**
fixes #2813 (workaround)

### CODE REVIEW

**Comment by StephanEggermont** [comment]
No. Needs a fix, not a workaround. Image is unusable atm

**Comment by MarcusDenker** [comment]
the original PR #2789 has this comment:

"I think that we can push the PR and fix the tests after because this is painful to checkout (on alain's machine we got several DNU unrelated to the changes)."

**Comment by MarcusDenker** [comment]
I will merge this, we can decide on reverting the other PR independently.

**Comment by Ducasse** [comment]
You are breaking my fun.

**Comment by MarcusDenker** [comment]
I can revert it. I thought it would make things simpler.

**Pull request merged**
