### PR TITLE
Add binary selector alias for #newFromArray: for Collection

### PR DESCRIPTION
**Pull request by Rinzwind**
This pull request adds a binary selector as an alias for `#newFromArray:` on Collection’s class as suggested in [pull request #22 in the Pharo Enhancement Proposals repository](https://github.com/pharo-project/pheps/pull/22). I used `#%>` as suggested in a [comment by @Ducasse](https://github.com/pharo-project/pheps/pull/22#issuecomment-1802010966). Other options I considered were `#<-` and `#<=`, which look like leftwards pointing arrows, to reflect that in `Set<-{1. 2}` the elements on the right are put into a collection of the class on the left. I implemented the alias only on Collection’s class, even though `#newFromArray:` is also implemented on Object’s class, as a [comment in pull request #11716](https://github.com/pharo-project/pharo/pull/11716#discussion_r979675710) explains the latter only exists for backwards compatibility.

### CODE REVIEW

**Comment by Ducasse** [comment]
Thanks!

**Comment by jecisc** [comment]
Personally I like <- the best

**Comment by Ducasse** [comment]
<- is for association so I would not use this one. we could use >-
I think that we should use %AnotherChar because it is a space that we do not use often.

**Comment by jecisc** [comment]
Association is using #->

#<- has no sender in the image currently :)

**Comment by Ducasse** [comment]
I ws confused now in old smalltalk it was assignment but it could work telling that the data will flow inside the collection especially if it has no sender.

**Comment by Rinzwind** [comment]
I renamed `#%>` to `#<-`.

**Comment by Ducasse** [comment]
Thanks a lot kris. We are fighting some daemons today :)

**Pull request merged**
