### PR TITLE
Make documentation more readable on github

### PR DESCRIPTION
**Pull request by jecisc**
Add `st` tags to doc to make it more readable on github

### CODE REVIEW

**Comment by privat** [comment]
`st` tags are nice, but are newline character intended? (not that I am against them, I like my `\n`)

**Comment by jecisc** [comment]
I think the documentation was generated from Pharo with cr line ending. But nobody uses cr anymore so I guess my code editor replaced the line endings?

I'm not sure it is bad because as I said, nobody except Pharo uses cr anymore

**Comment by privat** [comment]
Yep, 0A is the superior line ending :p

**Comment by jecisc** [comment]
The CI has its usual problems but this does not change the code of Pharo

**Comment by MarcusDenker** [comment]
we should really change the default line ending in Pharo to be the unix one...

**Comment by jecisc** [comment]
I’m 100% for it! But I don’t know where to start ahah

**Comment by privat** [comment]
> I’m 100% for it! But I don’t know where to start ahah

Some `tr` and `sed` could do the trick :p

**Comment by Ducasse** [comment]
Cyril the first step would be use newline instead of cr. 
Like we could change the newline without having to change everything. 
I do not like to be forced about oine ending when I do not need.

**Pull request merged**
