### PR TITLE
use-ifExists-in-more-places

### PR DESCRIPTION
**Pull request by jecisc**
Use #ifExists:(ifAbsent:) at more places.

### CODE REVIEW

**Comment by jecisc** [comment]
Apparently the problem I got in my previous PR comes from this subset of changes.

**Comment by jecisc** [comment]
I'll remove some candidates for the problem and see what the CI says.

**Comment by jecisc** [comment]
Apparently, the problem happens when we update UITheme. I wonder why.

Anyway, the tests passed here.

**Review by guillep — APPROVED** [review]
Ok! Thanks!

**Pull request merged**
