### PR TITLE
21863-Integrate-Calypso-v0113

### PR DESCRIPTION
**Pull request by dionisiydk**
new Calypso version 0.11.3

### CODE REVIEW

**Comment by dionisiydk** [comment]
https://pharo.fogbugz.com/f/cases/21863/Integrate-Calypso-v0-11-3

**Comment by MarcusDenker** [comment]
Loading baseline of BaselineOfCalypso...MetacelloConflictingProjectError: Load Conflict between existing BaselineOfClassAnnotation [baseline] from github://dionisiydk/ClassAnnotation:v0.3.1 and BaselineOfClassAnnotation [baseline] from github://pharo-ide/ClassAnnotation:v0.3.1

**Comment by dionisiydk** [comment]
Probably it conflicts with iceberg which also depends on Commands and ClassAnnotation. But Iceberg points to my old repo url (dionisiydk instead of pharo-ide).
I will try fix metacello script to force incoming version

**Comment by dionisiydk** [comment]
failed test is unrelated

**Pull request merged**
