### PR TITLE
Extract freetype to its own baseline (2nd pass)

### PR DESCRIPTION
**Pull request by estebanlm**
to address some dependency relations and better separate layers

### CODE REVIEW

**Comment by Ducasse** [comment]
Hi Esteban 
Some dependency tests are failing. 

```
1s
osx-64 / Tests-osx-64 / testExternalBasicToolsDependencies – MacOSX64.System.DependenciesTests.SystemDependenciesTest
4s
osx-64 / Tests-osx-64 / testExternalIDEDependencies – MacOSX64.System.DependenciesTests.SystemDependenciesTest
<1s
osx-64 / Tests-osx-64 / testExternalMorphicDependencies – MacOSX64.System.DependenciesTests.SystemDependenciesTest
<1s
osx-64 / Tests-osx-64 / testExternalSpec2Dependencies – MacOSX64.System.DependenciesTests.SystemDependenciesTest
1s
osx-64 / Tests-osx-64 / testExternalUIDependencies – MacOSX64.System.DependenciesTests.SystemDependenciesTest
```

**Comment by estebanlm** [comment]
yeah. Also, there are some methods moved that are not right, working (very slowly ;) ) on it.

**Comment by estebanlm** [comment]
okay, this is ready now (error is not related)

**Comment by estebanlm** [comment]
(I am working on decoupling Athens from FT2 now, there is no reason why they need to be coupled).

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
