### PR TITLE
Safer completion class access

### PR DESCRIPTION
**Pull request by pavel-krivanek**
Editing of package comments can cause DNUs. Use safer access to the completion class.
(Problem reported and patch provided by the Richard Uttner)

### CODE REVIEW

**Comment by Ducasse** [comment]
Hi Pavel,
Guille is asking the bug you have because he would like to make it robust from a user perspective but not hiding the problem. Because may be there is a use not using correctly completion

**Comment by Ducasse** [comment]
The editor should not configure the package comment to use a completion that requires a class because there is no class.

**Comment by Ducasse** [comment]
I add you so that we do not forget to discuss it.

**Comment by Ducasse** [comment]
May be my change to comment mode solved the problem.

**Comment by guillep** [comment]
Yes, I'd prefer to avoid having nil checks everywhere if a correct configuration can issue the right behavior...
@pavel-krivanek do you have some reproducible cases so we can test with @Ducasse changes?

**Comment by pavel-krivanek** [comment]
hmm, we are using slightly older version of P9 for development and it seems that this problem is no more valid. We can close this PR then. Thank you

**Comment by Ducasse** [comment]
Thanks pavel let us know in case it reappears.

**Pull request closed without merging**
