### PR TITLE
22221-Jump-to-next-keyword

### PR DESCRIPTION
**Pull request by macta**
Build on previous work to use the AST for senders/implementors, this provides low level support for intelligently jumping in the playground to the next keyword or or block or block variable.

It uses regular expressions so it can work with broken code, but then uses the AST to work out if a potential location actually makes sense.

NOTE: this requires a later PR for Calypso (actually SystemCommands)

To test it, you need to type cmd-J into a playground with some source code. It also provides an additional facility to intelligently widen the current source code selection (cmd-2) for easier refactoring

### CODE REVIEW

**Comment by MarcusDenker** [comment]
There is the NodeNavigation package, too. This was an experiment to implement general AST based navigation.

**Comment by macta** [comment]
I'll have a look at NodeNavigation - I haven't encountered that one. I did initially just try using just AST reasoning but found that my most common usecase for jumping was in creating new methods where the source code was broken and hence did a series of regex's to get me going. After using it like that for a few months (and tweaking it) I actually found it to be suprisingly good. 

I think it still needs improvement - I think it sometimes jumps to too many things, but i really miss it when I don't have it.

The widen selection is more AST based, and next I'd like to see if we can improve the keyboard refactoring flow as at the moment it is a bit clunky for common operations.

Anyway - its a nice little niche of the system where some nice improvments can be had, and it really demonstrates the flexiblity of Phao as even a mere mortal can delve into this area.

**Comment by macta** [comment]
@dionisiydk did a review of the Calypso code and he noticed some simplifications, so hold back on merging this for a moment while I get that bit straightened out.

**Comment by macta** [comment]
I've implemented @dionisiydk suggestions and made it a bit tighter and cleaner - this should now be reviewed and hopefully applied.

**Comment by Ducasse** [comment]
Hi tim, 
Do you have some tests for some of the new features?
It would help us to make sure that we can spot if we break them in the future.

Stef

**Comment by macta** [comment]
Yeah - I was feeling guilty as I submitted, but it’s sonething I’ve had sitting on my machine far too long so wanted to at least get it here for review.

I’ll work on some tests over the next few days.

**Comment by macta** [comment]
Ok - have added some jump tests (might be some useful cases for @girba to consider as they are adding similar functionality to bloc)

Will also add some similar tests for the "widen selection" functionality too - but wanted to get these ones in for review.

**Comment by macta** [comment]
Looks like the failure is something not related to this commit?

**Comment by macta** [comment]
@Ducasse ok - I've created a decent number of tests for this now that covers a good range of cases - so it it passes the CI, its good to merge.

**Comment by Ducasse** [comment]
TX we will have a look.

**Pull request merged**
