### PR TITLE
8145-Cleaning-subclass-users

### PR DESCRIPTION
**Pull request by Ducasse**
Removing senders of #subclass: style messages and replacing them with the use of the class installer.

### CODE REVIEW

**Comment by Ducasse** [comment]
Pblo we get 36 failing tests :)
So I think that it should be easy to fix. I will try to have a look tomorrow. 

testCreateNormalClassWithTrait – Unix64.ClassParser.Tests.ASTClassBuilderTest
<1s
testCreateTraitUsingAnotherSingleTrait – Unix64.ClassParser.Tests.ASTClassBuilderTest
<1s
testCreateTraitWithoutOtherTraits – Unix64.ClassParser.Tests.ASTClassBuilderTest
<1s
testNoUnusedTemporaryVariablesLeft – Unix64.ReleaseTests.CleanCode.NoUnusedVariablesLeftTest
19s
testDiskFiles – Unix64.STON.Tests.Write.Read.STONLargeWriteReadTest
<1s
testFileSystemSupport – Unix64.STON.Tests.Write.Read.STONLargeWriteReadTest
<1s
testUser2 – Unix64.STON.Tests.Write.Read.STONLargeWriteReadTest
<1s
testDiskFile – Unix64.STON.Tests.Reader.STONReaderTest
<1s
testUnknownClasses – Unix64.STON.Tests.Reader.STONReaderTest
<1s
testRoomExitCycles – Unix64.STON.Tests.Facade.STONTest
<1s
testDiskFiles – Unix64.STON.Tests.Write.Read.STONWriteAsciiOnlyReadTest
<1s
testFileSystemSupport – Unix64.STON.Tests.Write.Read.STONWriteAsciiOnlyReadTest
<1s
testUser2 – Unix64.STON.Tests.Write.Read.STONWriteAsciiOnlyReadTest
<1s
testDiskFiles – Unix64.STON.Tests.Write.Read.STONWritePrettyPrinterReadTest
<1s
testFileSystemSupport – Unix64.STON.Tests.Write.Read.STONWritePrettyPrinterReadTest
<1s
testUser2 – Unix64.STON.Tests.Write.Read.STONWritePrettyPrinterReadTest
<1s
testDiskFiles – Unix64.STON.Tests.Write.Read.STONWriteReadCommentsTest
<1s
testFileSystemSupport – Unix64.STON.Tests.Write.Read.STONWriteReadCommentsTest
<1s
testUser2 – Unix64.STON.Tests.Write.Read.STONWriteReadCommentsTest
<1s
testDiskFiles – Unix64.STON.Tests.Write.Read.STONWriteReadTest
<1s
testFileSystemSupport – Unix64.STON.Tests.Write.Read.STONWriteReadTest
<1s
testUser2 – Unix64.STON.Tests.Write.Read.STONWriteReadTest
<1s
testAddAndAddInstVarNamedWithTrait2 – Unix64.Slot.Tests.ClassBuilder.SlotIntegrationTest
<1s
testAddAndRemoveInstVarNamedWithTrait2 – Unix64.Slot.Tests.ClassBuilder.SlotIntegrationTest
<1s
testAddInstVarNamedWithTrait – Unix64.Slot.Tests.ClassBuilder.SlotIntegrationTest
<1s
testRemoveInstVarNamedWithTrait2 – Unix64.Slot.Tests.ClassBuilder.SlotIntegrationTest
<1s
testAddInstVarNamedWithTrait2 – Unix64.Slot.Tests.ClassBuilder.SlotIntegrationTest
<1s
testMethodClassBindingShouldBeClassBinding – Unix64.Slot.Tests.ClassBuilder.SlotMethodRecompilationTest
<1s
testClassReshapeShouldKeepClassBinding – Unix64.Slot.Tests.ClassBuilder.SlotMethodRecompilationTest
<1s
testClassReshapeShouldKeepClassBindingForTraitMethods – Unix64.Slot.Tests.ClassBuilder.SlotMethodRecompilationTest
<1s
testTraitMethodClassBindingShouldBeClassBinding – Unix64.Slot.Tests.ClassBuilder.SlotMethodRecompilationTest
<1s
testTraitUsersAfterClassReshape – Unix64.Slot.Tests.ClassBuilder.SlotTraitsTest
<1s
testRemoveTrait – Unix64.Slot.Tests.ClassBuilder.SlotTraitsTest
<1s
testTraitUsersAfterMetaclassReshape – Unix64.Slot.Tests.ClassBuilder.SlotTraitsTest
<1s
testModifyTraitComposition – Unix64.Slot.Tests.ClassBuilder.SlotTraitsTest
<1s
testUsingTraitInAnonymousSubClassAndRedefiningIt – Unix64.TraitsV2.Tests.T2TraitTest

**Comment by tesonep** [comment]
Yes, it looks like it is missing a #asTraitComposition 
Maybe it can be added in the accessor to ensure it is always sent

**Comment by Ducasse** [comment]
Hello pablo this is cool that you fixed them all. 
Now I do not get why the broken tests are related or not since they only break on windows.

**Comment by Ducasse** [comment]
I check the conflict and I'm not sure that I understand how to fix. 
I think that this is probably the changes in traits that got integrated that should be kept.

**Comment by Ducasse** [comment]
Tx pablo!!!

**Pull request merged**
