### PR TITLE
Activate smart characters even when in completion position

### LINKED ISSUE #8687: Smart characters does not work properly in some cases with spaces
**Describe the bug**

Sometimes smart characters are not inserted, and instead selection is replaced by a single character.

**To Reproduce**

1. write down `a  b  c` (notice there are two spaces between a and b, and between b and c.)
2. select `  b` (with the two spaces, starting just after the a)
3. type a smart character (e.g., opening parenthesis or quote)
4. => the selection is replaced by the typed character

**Expected behavior**

 => the selection is surrounded by the typed character

Also, notice that if selection is between the spaces, it works!
1. write down `a  b  c` (notice there are two spaces between a and b, and between b and c.)
2. select ` b` (with only one space, starting just after the first space)
3. type a smart character (e.g., opening parenthesis or quote)
4. => the selection is surrounded by the typed character

### PR DESCRIPTION
**Pull request by guillep**
Fixes #8687 
With Tests

### CODE REVIEW

**Comment by astares** [comment]
@guillep Could we become a little bit more descriptive in issues so other can reproduce too what issues are about ... what is situation, how to solve it and what should be the final result ...

**Comment by guillep** [comment]
Well, I was pretty informative in #8692, no? What is missing there?

**Comment by guillep** [comment]
Sorry, I actually mistook the issue number :)

**Comment by guillep** [comment]
Please, check #8687 and tell me what you would like (I could add the Pharo build, yes, but it happens since a while :) ...)

**Comment by astares** [comment]
@guillep OK - the corrected issue number includes a good description. Thanks!

**Comment by Ducasse** [comment]
Broken tests are unrelated

**Pull request merged**
