### PR TITLE
Deprecate #newMethod:header: with rewritting to #basicNew:header:

### PR DESCRIPTION
**Pull request by Inao0**
Related to #15625.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Now 
SindarinDebuggerTest>>testIsAboutToInstantiateClass

is failing.

There is https://github.com/pharo-spec/ScriptableDebugger/issues/87 which has to be fixed first

**Comment by MarcusDenker** [comment]
I did a PR: https://github.com/pharo-spec/ScriptableDebugger/pull/91

**Comment by MarcusDenker** [comment]
I merge the PR 90, close and re-open to rum the tests in a newly build image

**Comment by MarcusDenker** [comment]
The PR I merged was against the master branch, we should have one for the Pharo12 branch instead.

I re-opened https://github.com/pharo-spec/ScriptableDebugger/pull/91, which is the same but for Pharo12 branch

**Review by jecisc — APPROVED** [review]

**Pull request merged**
