### PR TITLE
2404-Add-rule-and-release-test-to-not-use-Smalltalk-ui-theme-in-subclasses-of-Morph

### LINKED ISSUE #2404: Add rule and release test to not use `Smalltalk ui theme` in subclasses of Morph
Morph implements in the instance and the class side a method #theme. Thus, its subclasses should never call `Smalltalk ui theme`. 

We should correct current usage, add a rule and a release test about that.

### PR DESCRIPTION
**Pull request by hilaire**
Fixes #2404
Add rule  to not use `Smalltalk ui theme` in subclasses of Morph and Model.
Correct the misusages.

### CODE REVIEW

**Comment by Ducasse** [comment]
Pay attention hilaire you commit contains also your old changes (MemoryStream....

**Comment by hilaire** [comment]
Ok. Somethings I did'nt understand because I carefully check the code to commit.

**Comment by hilaire** [comment]
Any ideas what's wrong when I push the pull request?

**Comment by Ducasse** [comment]
May be it show you the diff between the image and your last pushed commit. 
Hence you do not see it. 
What I do is the following

I have a bottom commit (the one that I create just after downloading an image)
and I checkout this branch (so that I go back undoing all my previous changes)
and only then I start to work by creating a new branch for a bug entry 
when I'm done (and I commit the bug and push) I got back to this bottom commit. 

Like that I can produce multiple independant changes.

**Comment by hilaire** [comment]
Ok. I will  try to understand because I am confused and the doc does not align with I see on the UI.

**Comment by jecisc** [comment]
The flow to do multiples fixes is:
- Checkout Pharo8.0
- Create a branch
- Commit, push and do a PR
- Checkout Pharo8.0 <== This is the missing step, you need to go back to the Pharo 8.0 branch before starting a new one, else the new one will have the commits of the previous branch as ancestor
- Create a branch
- Commit, push and do a PR
- Once again

**Comment by hilaire** [comment]
Questions:
**Checkout Pharo8.0**  From where? Guess: Checkout branch menu entries. Then pharo-project repo? I tried, it announce Pharo8.0 already exist. So wrong guess.

**Repair** The doc mentions repair operation. I don't see it in my image menu. It is likely out of sync though. My iceberg menu is different to the one in the doc

Capture

**Comment by Ducasse** [comment]
If you checkout Pharo 80 you will lose your commit. 
First you should commit them. So that after you can checkout a branch (and it will revert your changes) and then you can reload or not your changes.

**Comment by hilaire** [comment]
No change to commit.
CO of P8 branch does not work

Capture2
Capture

**Comment by Ducasse** [comment]
I do not know. If you know we can do a screen sharing session so that I show you what I'm doing.

**Comment by hilaire** [comment]
Why not, I can start from a fresh image but I need a hand to recover my fixes. When I look at Iceberg I have no clue how to do that.But let continue on the ml.

**Comment by hilaire** [comment]
Guys I have a long commit for this issue... I guess you can repoen the issue to let it be inserted...

**Pull request closed without merging**
