### PR TITLE
#flatCollect: implement using #streamContents:

### PR DESCRIPTION
**Pull request by MarcusDenker**
#flatCollect: should be implemented using streamcontents.

### CODE REVIEW

**Comment by Ducasse** [comment]
I have a stupid question but I dare asking it. 

when we do 
col := OrderedCollection
 		new: self size
 		streamContents: [ :str | self do: [ :each | str nextPutAll: (aBlock value: each) ] ]

The stream is preallocated but what will happen if the contents we will add via the nextPutAll: is larger? I imagine that the internal stream collection is copied into a larger one.

**Comment by Ducasse** [comment]
BTW how much faster is this new implementation?
It would be nice to give an indication in the method comments to educate the masses.

**Comment by MarcusDenker** [comment]
For 

new:streamContents:

the stream is initialised with a collection of size. If this estimate was not correct, we will create a larger collection, no problem there. The good thing is that it is done only once (we use the stream to avoid constantly having to make the collection larget, which is slow).

Sven added a really nice optimisation to new:streamContents: so that *if* the size estimate is correct, we do not need to copy the internal collection that the stream used.

**Comment by MarcusDenker** [comment]
benchmarks I did not yet do. I wanted to do that before deciding if the change is worth it

**Comment by svenvc** [comment]
I would change #flatCollect:as: to NOT use an intermediary collection

#withAll: is defined in terms of #addAll: so it would be possible to do it directly: instanciate the target collection, loop over the receiver and #addAll: each element

Agreed ?

**Comment by MarcusDenker** [comment]
it sadly does not work for String... as it does not allow #add:

**Comment by MarcusDenker** [comment]
I think I will make version if this PR with *only* the change to flatCollect:, as the code there is the same as we have in streamContents:

**Comment by svenvc** [comment]
Yes, I was wrong, it won't work for Array either, sorry for the noise

**Pull request merged**
