### PR TITLE
6040-TonelWriterwriteSnapshot-includes-tag-name-in-package-name-when-theres-no-OrganizationDefinition

### PR DESCRIPTION
**Pull request by carolahp**
Adding tags to MCClass definition.
Adding a MockClass whose category includes a tag

### CODE REVIEW

**Comment by carolahp** [comment]
Failures are due to the introduction of a new mock class MCMockClassJ.
Tests should pass considering the PR in the Tonel repository: https://github.com/pharo-vcs/tonel/pull/85

**Comment by tesonep** [comment]
Hi @carolahp , does it require to have a change in Tonel?

**Comment by carolahp** [comment]
> Hi @carolahp , does it require to have a change in Tonel?

Hello @tesonep 
Yes, I have made a PR in the Tonel repo https://github.com/pharo-vcs/tonel/pull/85

**Comment by tesonep** [comment]
I have merged the PR in tonel, I will release a new Iceberg and it will have this change, as soon I finish with the release I am doing.

**Comment by tesonep** [comment]
There are some tests that are broken in the Monticello package. 
Can you test them?

**Comment by carolahp** [comment]
@tesonep 
I checked the tests and found the cause.

Before my changes, no class in the MonticeloMocks package belonged to a tag, but I set the tag "Tag" in one class of the package and now the result of asking the snapshot all its categories includes the category "MonticeloMocks-Tag".

The failing tests are MonticelloGUI tests and they fail because the snapshot browser is showing separately each category (i.e. package name -  tag) instead of only the package name, as shown in the screenshot. 

Is this the desired behavior?

Screen Shot 2020-03-30 at 13 07 53

If it is then I would just need to modify the tests to expect the category "MonticeloMocks-Tag"

**Comment by tesonep** [comment]
> @tesonep
> I checked the tests and found the cause.
> 
> Before my changes, no class in the MonticeloMocks package belonged to a tag, but I set the tag "Tag" in one class of the package and now the result of asking the snapshot all its categories includes the category "MonticeloMocks-Tag".
> 
> The failing tests are MonticelloGUI tests and they fail because the snapshot browser is showing separately each category (i.e. package name - tag) instead of only the package name, as shown in the screenshot.
> 
> Is this the desired behavior?
> 
> Screen Shot 2020-03-30 at 13 07 53
> 
> If it is then I would just need to modify the tests to expect the category "MonticeloMocks-Tag"

I don't know. But it looks like ok for me.

**Comment by guillep** [comment]
I say we just make the tests green. Having two separate categories or as a single category is the same to me at this point. So maybe we need to change the tests.

**Comment by carolahp** [comment]
> I say we just make the tests green. Having two separate categories or as a single category is the same to me at this point. So maybe we need to change the tests.

I just changed the tests here and also in tonel, I just did a PR there https://github.com/pharo-vcs/tonel/pull/88

**Comment by guillep** [comment]
Seems there is no interest for this PR from the author. I'll close. Reopen if needed.

**Pull request closed without merging**
