### PR TITLE
2586 deleting a class with references gives extra do you want to delete anyway msg

### LINKED ISSUE #2586: Deleting a class with references gives extra "Do you want to delete anyway" msg
When you delete a class that has references to it - Pharo helpfully asks you if you want to view the references (which is cool) - if you answer No - you get a superfluous extra question "Do you want to remove anyway?".  This is annoying as if you say yes - you then get the refactoring window that shows you the removal which you can also accept and cancel. Thus you don't need that extra question as you can still cancel.

### PR DESCRIPTION
**Pull request by gcorriga**
Streamline the behaviour of the browser when removing classes, avoiding raising multiple dialogs.

The new behaviour is as follows:

if the class has no references, subclasses, or users, perform a refactoring to remove the class
if the class has references or users, ask the user what to do - browse the references/users, or do nothing.
if the class has subclasses, ask the user what to do - delete keeping subclasses, browse the subclasses, or do nothing.
As part of this change, remove the menu item to remove a class keeping subclasses since its behaviour is now integrate in the standard remove workflow.

Fixes #2586.
New version of #8297.

### CODE REVIEW

**Comment by gcorriga** [comment]
The issues seem related to defining new test packages.

1) how can I replicate the problem
2) what's the standard solution in these cases?

**Comment by guillep** [comment]
Hi @gcorriga sorry for coming late here.
There seem to be merge conflicts now.

Also, would you mind explaining what you mean by the following? I do not see any conversation, do you mean the tests failures?

> The issues seem related to defining new test packages.
> 
> 1. how can I replicate the problem
> 2. what's the standard solution in these cases?

**Comment by gcorriga** [comment]
@guillep the comment was referring to some spurious errors I was seeing when running the tests. If I remember correctly the errors were due to the fact that I was reinstating some packages which were previously included in the iceberg package definition.
This was causing some old tests that had not been deleted to be pulled from the repo when merging the code.

**Comment by gcorriga** [comment]
While trying to fix the merge issues, it looks like I've turned this merge request into a huge one with 900+ commits.

I'll close this PR and submit a clean one.

**Pull request closed without merging**
