### PR TITLE
Adding non-transforming deprecations that were suggested by DepMiner and accepted by Guille

### PR DESCRIPTION
**Pull request by olekscode**
Those methods were present in Pharo 8 but deleted in Pharo 9.
DepMiner tool (https://github.com/olekscode/DepMiner) recommended to return them deprecations.

For those methods, DepMiner could not generate the transformation rules.

Those recommendations we accepted by @guillep but rejected by @Ducasse, @MarcusDenker, and @tesonep

### CODE REVIEW

**Review by MarcusDenker — APPROVED** [review]
ok

**Comment by Ducasse** [comment]
Could remove this one: 
newRectButtonPressedDo:
Because I do not think that it is good to have it.

**Comment by olekscode** [comment]
@Ducasse @MarcusDenker done!

**Comment by MarcusDenker** [comment]
Wow, green green!

**Pull request merged**
