### PR TITLE
Refactor: preconditions return array of preconditions by default

### PR DESCRIPTION
**Pull request by balsa-sarenac**
We don't rely on a singe condition with and,or,not (we still use them when needed), but default return value of preconditions is array now.

Also, generateChanges method returns changes by default. A bunch of changes is caused by this, but they are trivial to review.

### CODE REVIEW

**Comment by jecisc** [comment]
15 tests are failings with this PR.

**Comment by Ducasse** [comment]
@jecisc where do you see the tests?

**Comment by jecisc** [comment]
> @jecisc where do you see the tests?

I click for example on the #1 at the top and select tests results

**Comment by jecisc** [comment]
image

**Comment by Ducasse** [comment]
OK thanks for the info.

**Comment by balsa-sarenac** [comment]
Failing tests seem unrelated

**Comment by Ducasse** [comment]
nice!

**Pull request merged**
