### PR TITLE
4026-migration-of-CriticBrowser-Spec-to-Spec-2-

### PR DESCRIPTION
**Pull request by CafeKrem**
migration of criticBrowser

### CODE REVIEW

**Comment by MarcusDenker** [comment]
key 'Tool-CriticBrowser-Tests' not found in Dictionary
Stacktrace
Dictionary>>errorKeyNotFound:
[ self errorKeyNotFound: key ] in Dictionary>>at:
Dictionary>>at:ifAbsent:
Dictionary>>at:
DADependencyReport>>dependenciesOf:
[ :aPackage | self dependenciesReport dependenciesOf: aPackage ] in SystemDependenciesTest>>externalDependendiesOf:
[ :each | col addAll: (aBlock value: each) ] in Array(Collection)>>flatCollect:as:
Array(SequenceableCollection)>>do:
Array(Collection)>>flatCollect:as:
SystemDependenciesTest>>externalDependendiesOf:
SystemDependenciesTest>>testExternalIDEDependencies

**Comment by jecisc** [comment]
I am doing a review of the code with Clément. 

Before integrating Clément will add more class comments.

**Comment by jecisc** [comment]
We just finished the revision with Clément. If tests pass, it's ready to merge.

**Comment by MarcusDenker** [comment]
two tests are failing:

ProperlyImplementedClassesTest>>testAllClassInstanceVariablesStartLowercase
Error
Class instance variable names must start with a lowercase letter

SystemDependenciesTest>>testExternalIDEDependencies
Error
Given Collections do not match! additions : #(#'Calypso-SystemTools-QueryBrowser') missing: #()

**Comment by jecisc** [comment]
I did a PR to Clément with the fixes: https://github.com/CafeKrem/pharo-1/pull/4

It should work once he integrates it.

**Comment by CafeKrem** [comment]
I had a problem with git. I create another PR #4148 
with all Cyril Review.
sorry for this mistake.
I close this PR

**Pull request closed without merging**
