### PR TITLE
[Backport] rapid click on two different items in a list gets interpreted as a double-click on the first item

### PR DESCRIPTION
**Pull request by ironirc**
This PR solves the problem with 2 subsequent clicks (within double click timing) on 2 different items of FTTableMorph.
Before the fix, this would execute a double click command on the first clicked item.
The fix involves comparing the 2 click positions and resulting item indexes.

A second problem occurs when double clicking on an already selected item.
Before the fix, the item gets de-selected, and nothing further happend.
This PR ensures that item is selected before dispatching the double click command.

### CODE REVIEW

**Comment by jecisc** [comment]
Hi, 

Current bug fixes should be done on Pharo 12. If the fix is integrated in Pharo 12 and works fine, we can then backport it to Pharo 11.
I'll try to rebase it and see if we have conflict against P12

**Comment by jecisc** [comment]
It brings other changes so I cannot just rebase it against P11

**Comment by ironirc** [comment]
@jecisc What should I do?

**Comment by jecisc** [comment]
I'll try to cherry pic your fix against P12. 
We can keep this PR for the backport but it should be merge after the P12 one

**Comment by jecisc** [comment]
https://github.com/pharo-project/pharo/pull/14346

**Comment by MarcusDenker** [comment]
(I did a close/reopen so we run the tests against the newest version of Pharo11)

**Comment by MarcusDenker** [comment]
The fix is in Pharo12 since end of July, it seems no problems came up.

We can merge the backport when the tests look ok

**Comment by MarcusDenker** [comment]
The CI run has some tests failing due to a DNU for #asPseudoDoubleClickEvent, for example #testDoubleClickActivatesRowInDoubleClickActivationMode

```
Error
Message not understood: MouseEvent >> #asPseudoDoubleClickEvent
Stacktrace
MessageNotUnderstood
Message not understood: MouseEvent >> #asPseudoDoubleClickEvent
MouseEvent(Object)>>doesNotUnderstand: #asPseudoDoubleClickEvent
SpFTTableMorph(FTTableMorph)>>doubleClick:
SpMorphicBackendForTest>>doubleClickFirstRowAndColumn:
SpListCommonPropertiestTest(SpAbstractListCommonPropertiestTest)>>testDoubleClickActivatesRowInDoubleClickActivationMode
SpListCommonPropertiestTest(TestCase)>>performTest
[ presenter := self classToTest new.
			self initializeTestedInstance.
			super performTest ] in SpListCommonPropertiestTest(SpAbstractAdapterTest)>>performTest
SpMorphicBackendForTest>>runTest:
SpListCommonPropertiestTest(SpAbstractAdapterTest)>>performTest



```

**Comment by jecisc** [comment]
I think this is because a change was integrated to Spec for the Pharo 11 branch but we need to do a new release

**Comment by jecisc** [comment]
BaselineOfPharo class>>#spec needs to be updated to point to v1.2.4 instead of v1.2.3

**Pull request closed without merging**
