### PR TITLE
[WIP] Fixes #7057: Commenting out a piece of code containing comments should maintain the inside comments

### LINKED ISSUE #7057: Commenting out a piece of code containing comments should maintain the inside comments
Right now, if one selects the following piece of code and presses " to comment it, then the comment inside is no longer a comment and the piece of code does not compile.

```Smaltlalk
code.
"comment"
code.
```
-> select all and press " ->
```Smalltalk
"code.
"comment"
code."
```
-> this code does not compile because the inside comment is interpreted as code
**Expected Behaviour**
```Smalltalk
"code.
""comment""
code."
```

### PR DESCRIPTION
**Pull request by ackerleytng**
Still a work in progress! Kicking off this pull request first

### CODE REVIEW

**Comment by ackerleytng** [comment]
Here's my proposed implementation:

I chose to replace every double quote in the selection with two double quotes, for consistency:

+ `code "comment" code` becomes `"code ""comment"" code"`
+ `invalid " code` becomes `"invalid "" code"`
+ `code "" code` becomes `"code """" code"`
+ `invalid """ code` becomes `"invalid """""" code"`

If we had ignored paired double quotes, i.e. allow `code "" code` to become `"code "" code"`,
then we would not have been able to restore these two cases from the enclosed versions

+ `case " one` becomes `"case "" one"`
+ `case "" two` becomes `"case "" two"`

since the right hand side is identical.

**Comment by Ducasse** [comment]
Pay attention that we will integrate before #7052

**Comment by ackerleytng** [comment]
I was also looking into refactoring to try and use classes to represent keyboard events instead of using many if elses throughout the CompletionEngine code.

Another option would be to add methods to the KeyboardEvent class. What do people think of these two options?

**Comment by ackerleytng** [comment]
@Ducasse, please feel free to merge #7052 and close both #7082 and #7057.

I saw some more issues surrounding TextEditor/Rubric at https://github.com/orgs/pharo-project/projects/20 and I would like to look into refactoring Rubric instead.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 50 million people use GitHub to discover, fork, and contribute to over 100 million projects.</div></blockquote>

**Comment by Ducasse** [comment]
You are welcome :)

**Comment by Ducasse** [comment]
Right now the team is in slow mode because many of them are in vacation.

**Comment by Ducasse** [comment]
What I would love to have is that when evaluating an expression the expression should be in "comment" and not directly modifying the text!

**Comment by Ducasse** [comment]
I would like to know the status in latest version now that the parser and comments/strings escaping behavior got integrated.

**Comment by guillep** [comment]
Hi @ackerleytng I think this behaviour is already in Pharo9 by default, and it covers also copy/past within comments. Could you check? I'll close the issue, tell us if this needs to be reopened.

**Pull request closed without merging**
