### PR TITLE
8921 gtDisplayString should be deprecated and use displayString

### PR DESCRIPTION
**Pull request by Ducasse**
two first steps to see the build.
Next step = cleaning more!

### CODE REVIEW

**Comment by Ducasse** [comment]
Working 
testMethodsOfTheClassShouldNotBeRepeatedInItsSuperclasses – MacOSX64.Collections.Sequenceable.Tests.Base.ArrayTest
<1s
testDisplayString – MacOSX64.Collections.Strings.Tests.Base.StringTest
<1s
testDisplayString – MacOSX64.Collections.Strings.Tests.Base.SymbolTest
<1s
testFastPointersTo – MacOSX64.Kernel.Tests.Objects.ProtoObjectTest
1m 15s

**Comment by Ducasse** [comment]
I do not get why the displayString test is not passing since it is passing in my image and my changes are published.

**Comment by Ducasse** [comment]
This is strange because when I look at the PR the code of String >> displayStringOn: is not the one I have in my image. It looks like iceberg is losing the code.

**Comment by Ducasse** [comment]
I will integrate this and we will see later for the duplicated methods. 
```
ArrayTest selectors 
	select: [ :each |  ReEquivalentSuperclassMethodsRule new basicCheck: ArrayTest >> each ]
>>> #()
```

**Comment by MarcusDenker** [comment]
the test tests the class that is the class under test (here Array):

Array selectors 
	select: [ :each |  ReEquivalentSuperclassMethodsRule new basicCheck: Array >> each ]

 "#(#gtDisplayString)"

**Pull request merged**
