### PR TITLE
22258 monticello problem

### PR DESCRIPTION
**Pull request by pdebruic**

### CODE REVIEW

**Comment by VincentBlondeau** [comment]
https://pharo.manuscript.com/f/cases/22258

**Review by VincentBlondeau — COMMENTED** [review]
I am not sure that ByteString should answer to fullName. I think that is more an issue in the UI calls that convert the file reference to a string instead of keeping it as it. But I may be wrong

**Comment by pdebruic** [comment]
Sure fixing the senders would be better but right now in Pharo 7 you can't load an mcz from your filesystem.  

Maybe fixing the senders of fullName could be a separate issue after this one gets accepted so that one can again immediately be able to load an mcz from the filesystem which seems to me like a bigger problem than clutter in the cluttered String class.

**Comment by estebanlm** [comment]
sorry, this does not seems the right solution.
I will not accept add #fullName idiom to ByteString. Instead, please fix the real problem (you should not arrive to send String>>fullName).

**Pull request closed without merging**
