### PR TITLE
Committing changes from GustavoSantos/Refactoring2 on Smalltalkhub

### PR DESCRIPTION
**Pull request by gustavojss**
In this commit I introduce:
- new package Refactoring2
- Code Transformations to be distinguished from Refactorings
- precondition checking is optional
- atomic transformations to be distinguished from composite ones
- examples of existing Refactoring, such as "Extract Method" and "Push Down Variable", as composite transformations
- introduction of new composite transformations, such as "Deprecate Class" and "Rename and Deprecate Class"

### CODE REVIEW

**Comment by Ducasse** [comment]
Super cool! I will have a look!

**Comment by Ducasse** [comment]
Pavel do you know if Refactoring2 should be added to a baseline? I have to check the code.

**Comment by Ducasse** [comment]
Gustavo do you have tests?

**Comment by Ducasse** [comment]
We saw the tests.
Now why do you have a new BRClass2?

**Comment by Ducasse** [comment]
You have tests for the transformations and I would like to know how I can change the refactorings to use your transformation and check the tests.

**Comment by gustavojss** [comment]
- I created RBNamespace2 and RBClass2 because I wanted to change the original classes without breaking the existing refactorings. It's in my long-term plan to completely refactor these classes because they are too big
- I test the preconditions in my tests; and for that purpose, I use transformations as refactorings. When you instantiate a *Transformation, you can send #asRefactoring then #transform

**Comment by Ducasse** [comment]
Thanks for the information I will have a look.

**Comment by pavel-krivanek** [comment]
I think that the tests should be placed in a separate package, they are now part of `Refactoring2-Transformations`

**Pull request merged**
