### PR TITLE
Migrate rename class to driver

### PR DESCRIPTION
**Pull request by Ducasse**
Nice pair programming session with caro.

### CODE REVIEW

**Comment by jecisc** [comment]
Bootstrap is failing with:

```
Error: Package Calypso-SystemTools-Core depends on the following classes:
  SycRenameClassCommand
You must resolve these dependencies before you will be able to load these definitions: 
  SycRenameClassCommand>>#browserContextMenuActivation
  SycRenameClassCommand>>#browserShortcutActivation
  SycRenameClassCommand>>#sourceCodeMenuActivation
  SycRenameClassCommand>>#sourceCodeShortcutActivation
```

**Comment by Ducasse** [comment]
Why the bootstrap is involved into that?

**Comment by Ducasse** [comment]
May be we lost this extensions.

**Comment by jecisc** [comment]
> Why the bootstrap is involved into that?

Here this is the full image load. It's possible that the load order of packages is not right

**Comment by guillep** [comment]
What @jecisc calls the bootstrap is the build of the image. Probably in the code you changed you changed some dependencies, so the Baselines should be adjusted

**Comment by Ducasse** [comment]
I just remove a class so the extensions to this class should probably be removed too. I will check.

**Comment by jecisc** [comment]
I have the impression that we again have a bug on the extension removal :( I'll investigate. I added a test about the last thing that broke it, but maybe another mechanism is involved

**Comment by Ducasse** [comment]
What I do not understand is:
- we copied (using the copy class) the class SycRenameClassCommand -> SycRenameClassCommand2
- This copy got the same extensions than the original.
- After working we just remove the class SycRenameClassCommand
- The extensions were removed. 
So everything looks correct to me. 
I checked SycRenameClassCommand2 has the extensions that were needed.

Now SycRenameClassCommand is making a reference to the class RBRenameClassDriver. 
However the dependencies to this package are not new because we are doing it all the time. we have around 13 reference from Syc*Command to Driver classes. 
So I do not really get what could be problem.

**Comment by Ducasse** [comment]
Ah I see and this is the really the problem.
When I removed the class SycRenameClass the extensions where not remove. 

So the package of these extension still wants to added method to the removed class.

```
Error: Package Calypso-SystemTools-Core depends on the following classes:
  SycRenameClassCommand
You must resolve these dependencies before you will be able to load these definitions: 
  SycRenameClassCommand>>#browserContextMenuActivation
```

**Comment by Ducasse** [comment]
I will add back an empty class to see.

**Comment by Ducasse** [comment]
What is really confusing is that I do not see the extending method of SycRenameClassCommand in the package Calypso-SystemTools-Core. I only see the ones of SycRenameClassCommand2.

So I will wait and see. Else I will try to rename SycRenameClassCommand2 into SycRenameClassCommand.

**Comment by Ducasse** [comment]
Now what is super super strange is that the consequence of my browsing of the package Calypso-SystemTools-Core did create probably a notification and now I could see the removal of the extension method of the class SycRenameClassRefactoring. So it means that the the triggering of the removal did not happen when I removed the class
but when I browsed the package :).

**Comment by jecisc** [comment]
I might have an idea why this is breaking. It might be due to the fact that RPackage does not use announcement anymore. Maybe before some code of Monticello happened before the update or RPackage and now it happens after and this changes the package of the updated classes and methods? I’ll check

**Comment by jecisc** [comment]
For the bug I opened this: https://github.com/pharo-project/pharo/issues/15401

**Comment by jecisc** [comment]
I proposed a fix here: https://github.com/pharo-project/pharo/pull/15403

:)

**Comment by Ducasse** [comment]
Thanks!!! I'm happy that you could understand what was happeining

**Pull request merged**
