### PR TITLE
Add 64 bits to the list of architectures for test runs

### PR DESCRIPTION
**Pull request by guillep**
Redo of #5261 , fixing #5260

### CODE REVIEW

**Comment by VincentBlondeau** [comment]
It seems that the fix is a bit more complex. The x64 files needs to be stashed correctly too.

**Comment by VincentBlondeau** [comment]
L 129 should be edited too. @guillep  I let you do it :)

**Comment by guillep** [comment]
Yes sir, let's see how this goes. Before bootstrapping in 64 bits used to crash the VM.

**Comment by VincentBlondeau** [comment]
Ok. The configuration change is working!
And, there are issues on the x64 version :)

**Review by VincentBlondeau — APPROVED** [review]
Change is working but tests are failing. Test should be solved in another PR

**Comment by estebanlm** [comment]
Moving to P9 because no time for the release (P9 is starting now anyway so you can continue working)

**Pull request merged**
