### PR TITLE
11301 fixes 10644 process terminate from is czech

### PR DESCRIPTION
**Pull request by isCzech**
Trying to update #11301 with commit a98ec5d. Sorry if it goes south again ;)

### CODE REVIEW

**Comment by isCzech** [comment]
Not sure the reported test failures are related to the proposed changes; nothing looks familiar to me (all are Zinc related).

**Comment by MarcusDenker** [comment]
odd.. they timed out. I have restarted a CI run to see if this was just some CI problem

**Comment by isCzech** [comment]
I've made some minor tweaks (covering extreme borderline situations, unrelated to the CI timeouts); the same result... No idea what it means, unfortunately.

**Comment by isCzech** [comment]
one more attempt - merged the changes into a fresh Pharo11 image and created #11310... let's see

**Comment by MarcusDenker** [comment]
replaced by https://github.com/pharo-project/pharo/pull/11310

**Comment by isCzech** [comment]
Thank you @MarcusDenker for the cleanup, sorry for the mess

**Pull request closed without merging**
