### PR TITLE
20258-Fix-to-make-recursive-links-work

### PR DESCRIPTION
**Pull request by badetitou**
20258 Fix  to make recursive links work
Add test for 20258

### CODE REVIEW

**Comment by MarcusDenker** [comment]
it misses the ivar addition to Process:

Found undeclared references: #(#level)

**Comment by tesonep** [comment]
@badetitou This problem is a clear limitation of our extension methods. It is not possible to add an instance variable as an extension. The question is if that instance variable should be in the Process class, what it is used for?

**Comment by badetitou** [comment]
@tesonep I so would like to add this variable as an extension. 

This variable is used by Reflectivity.
It could be used to specify the number of times you let a metalink active in a method (think about recursive method but you want to run the metaLink only 3 times or 1).

I have such a use case in SmartTest.

@MarcusDenker has fixed that with me last summer.

**Comment by MarcusDenker** [comment]
for now adding the var is the only solution I found to implement it... not nice, but I think it does not hurt too much for what it enables.

**Comment by MarcusDenker** [comment]
error not related

**Comment by MarcusDenker** [comment]
I wonder why we added  RFASTClosureAnalyzer >> visitMethodNode: I will make a note and double check after integration/

**Pull request merged**
