### PR TITLE
Cleaning up FFI usage of SDL2

### PR DESCRIPTION
**Pull request by tesonep**
- Using a FFILibrary
- Using FFILibraryFinders to find the libraries
- Removing old plugin code
- Removing old Surface plugin code

### CODE REVIEW

**Review by guillep — APPROVED** [review]
❤️

**Comment by MarcusDenker** [comment]
Full image buiild fails:

```
MetacelloNotification: Project: Microdown
MetacelloNotification: Project: WelcomeBrowser
SubscriptOutOfBounds: 1 in #[]
ByteArray(Object)>>errorSubscriptBounds:
ByteArray(Object)>>at:
ByteArray>>byteAt:
ZipReadStream(InflateStream)>>nextByte
ZipReadStream(InflateStream)>>nextBits:
ZipReadStream(InflateStream)>>getNextBlock
ZipReadStream(InflateStream)>>pastEndRead
ZipReadStream(InflateStream)>>next
ZipReadStream(InflateStream)>>next:into:startingAt:
[[ readDataRemaining > 0 ] whileTrue: [
		| chunkSize |
		chunkSize := 32768 min: readDataRemaining.
		buffer := decoder next: chunkSize into: buffer startingAt: 1.
		aStream next: chunkSize putAll: buffer startingAt: 1.
		readDataRemaining := readDataRemaining - chunkSize.
	]] in ZipFileMember>>uncompressDataTo: in Block: [[ readDataRemaining > 0 ] whileTrue: [...
FullBlockClosure(BlockClosure)>>on:do:
ZipFileMember>>uncompressDataTo:
```

**Comment by jecisc** [comment]
Since it's a zip problem I relaunched the CI because sometimes this code produce random failure

**Comment by Ducasse** [comment]
```
SystemNotification: Loading StartupPreferences-tonel.1.mcz
SystemNotification: Loading PragmaCollector-tonel.1.mcz
SystemNotification: Loading System-FileRegistry-tonel.1.mcz
[31m[33m
*** Warning: Warning: Package UNKNOWN depends on the following classes:
  FileList
You must resolve these dependencies before you will be able to load these definitions: 
  FileList>>#fileInto:
  FileList>>#fileReaderServicesForFile:suffix:
  FileList>>#serviceFileIn
  FileList>>#services
  FileList>>#sourceFileSuffixes

[0m[0mSystemNotification: Loading MonticelloFileTree-Core-tonel.1.mcz
NewUndeclaredWarning: MCFileTreeAbstractReader>>packageProperties (STON is Undeclared)
NewUndeclaredWarning: MCFileTreeStCypressReader>>addClassAndMethodDefinitionsFromEntry: (STON is Undeclared)
NewUndeclaredWarning: MCFileTreeStCypressReader>>addClassAndMethodDefinitionsFromEntry: (STON is Undeclared)
NewUndeclaredWarning: MCFileTreeStCypressReader>>addExtensionClassAndMethodDefinitionsFromEntry: (STON is Undeclared)
NewUndeclaredWarning: MCFileTreeStCypressReader>>addExtensionClassAndMethodDefinitionsFromEntry: (STON is Undeclared)
```

**Comment by MarcusDenker** [comment]
Tests are green!

**Pull request merged**
