### PR TITLE
Revert "Composite extract method refactoring"

### PR DESCRIPTION
**Pull request by MarcusDenker**
Reverts pharo-project/pharo#16525

I want to see if this introduced all the problemes.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
So indeed reverting the change fixes all these:

- [CI] Pharo13: Tests failing for RB #16571 
- [CI] Pharo13: code with halt was merged #16569
- [CI] Pharo13 tests on OSX crash in Refactoring-Transformations-Tests #16567

**Comment by MarcusDenker** [comment]
@balsa-sarenac what do you think? Can you do a fix soon or should be revert?

**Comment by balsa-sarenac** [comment]
I'm working on the fixes in the #16527 if that is fine. Will try to have a mergeable PR on Monday.

**Comment by balsa-sarenac** [comment]
I figured that the bad commit is https://github.com/pharo-project/pharo/pull/16525/commits/1600e39faa2ba1b6d088e59aad7fb3d92bc2afd4

Now on to fixing it!

**Pull request closed without merging**
