### PR TITLE
Deprecate String>>asDate

### PR DESCRIPTION
**Pull request by ISayarLu**
Date>>asDate is ambiguous regarding how to interpret the day, month and year fields. Sometimes it interprets them in some order and sometimes in other.

```smalltalk
'1-13-04' asDate => 13 january 2004
```

```smalltalk
'13-1-04' asDate => 13 january 2004
```

Recently an exception was added in one of the cases above, but the ambiguity remains.
We propose with @guillep to deprecate it in favor of `#readFrom:pattern:` with an explicit pattern.

We deprecate methods: 
- String>>asDate,
- Date>>fromString, and 
- Date>>readFrom.
Remove related tests on the deprecated methods.
Use Date>>#readFrom:pattern: specifying a concrete pattern instead + all other.

We also added an option into the pattern parser to continue parsing using the continueAfterParsing method.

### CODE REVIEW

**Comment by Ducasse** [comment]
Good idea!.

**Comment by MarcusDenker** [comment]
This PR as merged even though it has failing tests.

**Comment by noha** [comment]
What is the policy here. I would expect reverting is the obvious choice, no?

**Comment by guillep** [comment]
could we please just revert it instead of making an argument here ? I'm on vacations and not on a computer, otherwise I'd do it myself

**Comment by guillep** [comment]
PR Reverted in https://github.com/pharo-project/pharo/pull/15227 and reopened in https://github.com/pharo-project/pharo/pull/15228.

I'll rework it during the week when I come back from vacations.

**Pull request merged**
