### PR TITLE
22174-Remove-FileDoesNotExistExceptiondefaultAction

### PR DESCRIPTION
**Pull request by akgrant43**
22174 Remove FileDoesNotExistException>>defaultAction

FileDoesNotExist and FileDoesNotExistException were recently merged into FileDoesNotExistException.

FileDoesNotExistException has an interactive pop-up as its default action, while FileDoesNotExist didn't.  This causes problems as experienced recently in PR 1572 [1].

Core classes, such as the file system, shouldn't be relying on an interactive environment being present, so...

Remove the #defaultAction over-ride and update the class comment to suggest the interactive action that can be taken by applications if appropriate.

Fogbugz: https://pharo.fogbugz.com/f/cases/22174/Remove-FileDoesNotExistException-defaultAction

[1] https://github.com/pharo-project/pharo/pull/1572

### CODE REVIEW

**Comment by jecisc** [comment]
@akgrant Shouldn't you also remove fileDoesNotExistsDefaultAction: in the UIManager and its subclasses?

**Comment by akgrant43** [comment]
Hi Cyril,

My original thought was to leave it there so that applications that did want the interactive action could easily use it.  However:

- the name doesn't make much sense any more
- #readOnlyFileDoesNotExistUserHandling: can't work since it calls a method that doesn't exist: #correctAgainst:

So I think I agree that it would be better to remove these methods.

@guillep What do you think?

**Comment by akgrant43** [comment]
Hi Cyril,

I've deprecated, rather than immediately remove, #fileDoesNotExistsDefaultAction and associated methods.

What do you think?

Cheers,
Alistair

**Comment by jecisc** [comment]
Hi, 

In general we move the deprecated methods to Deprecated70 package. 

Except that, all I have to say is: Awsome! :)

Thank you

**Review by jecisc — APPROVED** [review]

**Comment by akgrant43** [comment]
Cyril, thanks for your feedback and approval.

Marcus, test failures appear to be unrelated - a character encoding error in an .ombu file.

Thanks again,
Alistair

**Comment by jecisc** [comment]
I relaunched the CI.

**Comment by akgrant43** [comment]
Thanks, Cyril.  And all checks passed this time. :-)

**Review by pavel-krivanek — APPROVED** [review]
looks good

**Comment by akgrant43** [comment]
Thanks, Cyril, Pavel & Esteban!
(@jecisc  @pavel-krivanek & @estebanlm)

**Pull request merged**
