### PR TITLE
fix a couple of regressions

### PR DESCRIPTION
**Pull request by estebanlm**
for some reasons, this changes were rolled back in other PRs (probably my fault ;) )

### CODE REVIEW

**Comment by MarcusDenker** [comment]
interesting: windows crash with

```
fred is number 1
charlie is number 2
elmer is number 32021-12-15T11:54:21.468+01:00
WARNING:  Had to GC to make room for more external objects.
If this happens often, it would be a good idea to either:
- Raise the maxExternalSemaphores size.
- Write your code to explicitly release them rather than wait for finalization.

Returning an object but pool is full./pharo: line 11: 24135 Segmentation fault      "$DIR"/"pharo-vm/PharoConsole.exe" --headless "$@"
```


But that seems to be not related to the change

**Review by MarcusDenker — APPROVED** [review]

**Comment by MarcusDenker** [comment]
The tfPointerAddress on ByteArray...  was this added somehow?

**Comment by MarcusDenker** [comment]
tfPointerAddress on Bitmap I mean...

**Comment by estebanlm** [comment]
yes, I moved it to `ThreadedFFI-Graphics-Extensions`, but for some reason it was not removed from `ThreadedFFI` causing a duplicate. The final image has  `tfPointerAddress` correct (since ThreadedFFI-Graphics-Extensions overrides ThreadedFFI),

**Comment by estebanlm** [comment]
yeah, the windows error is not related.

**Pull request merged**
