### PR TITLE
Removing makefile files that are obsolete (cheched with Guille)

### PR DESCRIPTION
**Pull request by Ducasse**
Removing makefile files that are obsolete (cheched with Guille)

### CODE REVIEW

**Comment by jecisc** [comment]
[CI] System variable environment on windows does not use adequate encodings #11407

**Comment by jecisc** [comment]
This is weird, this time it also failed of osx!

**Review by jecisc — APPROVED** [review]

**Comment by privat** [comment]
I'm reading that after the battle, but some issues of https://github.com/pharo-project/pharo/issues?q=is%3Aissue+is%3Aopen+bootstrap seems related and could be closed since the Makefile is kill

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo">Issues · pharo-project/pharo</a></strong></div><div>Pharo is a dynamic reflective pure object-oriented language supporting live programming inspired by Smalltalk. - Issues · pharo-project/pharo</div></blockquote>

**Comment by jecisc** [comment]
I'll do the cleaning. Thank you Jean

**Pull request merged**
