### PR TITLE
2895-remove-SmalltalkEditor

### PR DESCRIPTION
**Pull request by plantec**
removed SmalltalkEditor, GLMSmalltalkEditor,  GLM related classes (that was not refed)

### CODE REVIEW

**Comment by jecisc** [comment]
Only the initialization of SmalltalkEditor was removed. Not the class itself it seems.

**Comment by MarcusDenker** [comment]
errors not related

**Comment by Ducasse** [comment]
Ok we will check because we removed the class itself.

**Comment by Ducasse** [comment]
May be alain did not push the last changes we did on this branch and just committed it.

**Comment by Ducasse** [comment]
We need help because we have not idea how to fix this.

**Comment by MarcusDenker** [comment]
I added the PR to the Sprint board so we can check tomorrow

**Comment by Ducasse** [comment]
Ok the conflict was stupid but we needed the superpower of guille to resolve it. 
Now after the build we can integrate it.

**Comment by guillep** [comment]
Well, now it is failing because there are classes that depends on it :D

```
Loaded -> MonticelloMocks-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-3031/32/src --- cacheError: This package depends on the following classes:

[32]   SmalltalkEditor

[32] You must resolve these dependencies before you will be able to load these definitions: 

[32]   SmalltalkEditor>>#isWorkspace

[32]   SmalltalkEditor>>#sourceTextArea

[32] 

[32] MCPackageLoader(Object)>>notify:

[32] MCPackageLoader>>warnAboutDependencies

[32] MCPackageLoader>>validate

[32] MCPackageLoader>>loadWithNameLike:

[32] MCVersionLoader>>basicLoadWithNameLike:

[32] [ self basicLoadWithNameLike: aString ] in MCVersionLoader>>loadWithNameLike: in Block: [ self basicLoadWithNameLike: aString ]
```

**Comment by guillep** [comment]
Actually, it's the package NodeNavigation that is extending SmalltalkEditor with two methods.

image

We should remove those two methods as part of this PR too

**Comment by Ducasse** [comment]
Thanks guille.
I will need help to do it.

**Comment by Ducasse** [comment]
I'm trying to fix it now.

**Comment by Ducasse** [comment]
I do not know how to fix this because  I cannot find the method when I merge.
So I redid it by first removing the methods and merge the PR of Alain. 
Let us see.

**Comment by Ducasse** [comment]
I tried but I pushed I got a debug. So I will really need help.

**Comment by estebanlm** [comment]
Stef will provide a new PR

**Pull request closed without merging**
