### PR TITLE
2980 rubric failing tests in morphic text input field adapter test was tests should be run in the image before committing

### PR DESCRIPTION
**Pull request by Ducasse**
Normally this is ok to integrate. There may have some conflicts.

### CODE REVIEW

**Comment by Ducasse** [comment]
I'm lost with the github interface.

**Comment by guillep** [comment]
I've fixed the merge conflict. Let's wait until the CI runs.

**Comment by Ducasse** [comment]
Tx guille.

**Comment by Ducasse** [comment]
Red tests are announcer tests.

**Comment by Ducasse** [comment]
I think that we can integrate these changes.

**Pull request merged**
