### PR TITLE
Remove unnecessary methods from Microdown package

### LINKED ISSUE #9870: Remove unnecessary methods from Microdown package
Some methods in Microdown package are unnecessary as they are equivalently defined in superclass:

- MicAnnotatedBlock>>#label
- MicAnnotatedBlock>>#addLineAndReturnNextNode:
- MicAnnotatedBlock>>#canConsumeLine:

The method too
- MicHorizontalLineBlock>>#addLineAndReturnNextNode:
but we keep it due to the different comment depicting how line is written

### PR DESCRIPTION
**Pull request by astares**
Fix #9870

### CODE REVIEW

**Comment by MarcusDenker** [comment]
This seemingly needs to be better commited to the Microdown repository, as the idea is to manage it like we manage spec.
(but yes, this is not clear... even I do not know which packages are external and which not and am known to commit wrongly)

**Comment by astares** [comment]
???

Sorry - this is all too confusing.

**Comment by MarcusDenker** [comment]
I am redoing a PR in the microdown repo

**Comment by MarcusDenker** [comment]
PR is here: https://github.com/pillar-markup/Microdown/pull/228

**Pull request closed without merging**
