### PR TITLE
Scopes Browser P12

### PR DESCRIPTION
**Pull request by carolahp**
Creates a browser for creating and editing scopes.
Scopes are used to define an environment when applying code refactorings and while visualizing code in calypso. 
Pharo's main scope contains the code of the full pharo image.

### CODE REVIEW

**Comment by Ducasse** [comment]
Caro could you push it to http://gtihub.com/pharo-spec/newTools ? Because like that it loads after spec.

**Comment by carolahp** [comment]
> Caro could you push it to http://gtihub.com/pharo-spec/newTools ? Because like that it loads after spec.

No problem, [here's the new PR](https://github.com/pharo-spec/NewTools/pull/585)

**Comment by carolahp** [comment]
Replaced by [PR](https://github.com/pharo-spec/NewTools/pull/585)

**Comment by carolahp** [comment]
Replaced by [PR](https://github.com/pharo-spec/NewTools/pull/585)

**Pull request closed without merging**
