### PR TITLE
2341-memory-leak-through-NECController-uniqueInstance

### PR DESCRIPTION
**Pull request by MarcusDenker**
remove ivar

### CODE REVIEW

**Comment by MarcusDenker** [comment]
(somehow I could not commit the class ivar removal, might be a Iceberg issue, to be checked later)

**Comment by MarcusDenker** [comment]
tested it in the build artefact a little and code completion works ok with this change

**Comment by Ducasse** [comment]
I read everything but I do not have enough context. 

Stef

**Comment by MarcusDenker** [comment]
The idea is to do a new instance (per editor) instead of using #uniqueInstance on the class of the CodeCompletion controller.

I just hooked everything into the already prepared setup in the editor and it seems to work

I will merge so we test it for real

**Pull request merged**
