### PR TITLE
5093-Remove-Smart-Suggestions

### LINKED ISSUE #5093: Remove Smart Suggestions
We will redo it later with commander20 right now the context of SmartSuggestions is broken. 
Better removed broken code.

### PR DESCRIPTION
**Pull request by Ducasse**
fixes: #5093 Remove SSUGs from image!!!

### CODE REVIEW

**Comment by MarcusDenker** [comment]
[32] Evaluated -> baseline [BaselineOfAthens] >> postload:package:Error: This package depends on the following classes:
[32]   SugsRenameClass
[32]   SugsBrowseClassReferences
[32]   SugsStoresIntoInstVar
[32]   SugsRenameInstanceVar
[32]   SugsRenameClassVar
[32]   SugsCreateInstanceVarAccessors
[32]   SugsUseAccessorsForClassVar
[32]   SugsCreateClassVarAccessors
[32]   SugsSuggestion
[32] You must resolve these dependencies before you will be able to load these definitions: 
[32]   SugsBrowseClassReferences>>#nodes
[32]   SugsCreateClassVarAccessors>>#nodes
[32]   SugsCreateInstanceVarAccessors>>#nodes
[32]   SugsRenameClass>>#nodes
[32]   SugsRenameClassVar>>#nodes
[32]   SugsRenameInstanceVar>>#nodes
[32]   SugsStoresIntoInstVar>>#nodes
[32]   SugsSuggestion>>#for:
[32]   SugsUseAccessorsForClassVar>>#nodes

**Comment by MarcusDenker** [comment]
I would remove the code first step by step checking references.

**Comment by Ducasse** [comment]
I checked.  now I do not understand why Athens baseline is refering to Sugs. 
Now the problem is that we cannot test it without building it.

**Comment by Ducasse** [comment]
I do not get the problem with the BaselineOfAthens

baseline: spec
	<baseline>
	spec
		for: #common
		do: [ 
			spec postLoadDoIt: #'postload:package:'.

			"Inter packages dependencies are now added but it is missing some dependencies on other projects such as Morphic for Athens-Morphic"
			"Dependencies"
			self
				display: spec;
				unifiedFFI: spec.

			"Packages"
			spec
				package: 'Athens-Core' with: [ spec requires: 'Display' ];
				package: 'Athens-Text' with: [ spec requires: 'Athens-Core' ];
				package: 'Athens-Balloon' with: [ spec requires: #('Athens-Core' 'Athens-Text') ];
				package: 'Athens-Morphic' with: [ spec requires: #('Athens-Core' 'Athens-Text' 'Athens-Balloon' 'Athens-Cairo') ];
				package: 'Athens-Cairo' with: [ spec requires: #('Athens-Core' 'UnifiedFFI') ];
				package: 'Athens-Examples' with: [ spec requires: #('Athens-Morphic' 'Athens-Text' 'Athens-Balloon' 'Athens-Cairo') ];
				package: 'Athens-Cairo-Tests' with: [ spec requires: 'Athens-Cairo' ].

			"Groups"
			spec
				group: 'Core' with: #('Cairo-core' 'Athens-Text' 'Athens-Balloon' 'Athens-Morphic');
				group: 'Cairo-core' with: #('Athens-Core' 'Athens-Cairo');
				group: 'Examples' with: #('Athens-Examples');
				group: 'Tests' with: #('Athens-Cairo-Tests') ]

**Comment by Ducasse** [comment]
postload: loader package: packageSpec

	AthensCanvas initialize.

**Comment by Ducasse** [comment]
I really do not understand this dependencies.

**Comment by MarcusDenker** [comment]
I will have a look...

**Comment by Ducasse** [comment]
To check what will happen since I emptied the packages in previous PR

**Comment by Ducasse** [comment]
All tests passed :)

**Pull request merged**
