### PR TITLE
22376 Add a quick setup to the welcome page

### PR DESCRIPTION
**Pull request by astares**
Add a quick setup to the welcome page
- to switch themes
- to choose network bandwidth (and set catalog in spotter setting accordingly)
- give quick access to network proxy settings (for instance when behind a corporate proxy)

This should cover most cases people need to adjust initially.

- and open general settings browser for further configuration of the image

For the "link" functionality:
allow beside the #doItFrom: (where Code is displayd and evaluated) also
a #doItFrom:text: where a text is displayed but code evaluated

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Error
Given Collections do not match. Got left := #(#'Athens-Morphic' #NautilusRefactoring #'Refactoring-Critics' #'Reflectivity-Tools' #Shout #'Tool-Catalog'). instead of right :=#(#'Athens-Morphic' #NautilusRefactoring #'Refactoring-Critics' #'Reflectivity-Tools' #Shout). Collection size does not match: left=6 vs. right=5 Got 1 additional element(s) in the left collection: #(#'Tool-Catalog')

**Comment by MarcusDenker** [comment]
This is a system dependencies test

**Comment by astares** [comment]
To see the new functionality one should evaluate 

      WelcomeHelp open

(later when we release Pharo 7 this window is shown by default)

**Comment by astares** [comment]
And green. No reviewers available - all visiting ESUG I think ;)

@MarcusDenker any chance we can move this forward? Thanks in advance!

**Pull request merged**
