### PR TITLE
[improvement] add microsecond to API

### PR DESCRIPTION
**Pull request by hogoww**
Useful for people using microsecondsToRun:
The naming microSecond or microsecond is inconsistent to, I took one randomly.

This seems to be an oversight that is just missing from the API.

### CODE REVIEW

**Comment by hogoww** [comment]
All the failing test cases are passing on my local machine.
Will try restart the CI..

**Comment by hogoww** [comment]
Tests cases are still indeed passing locally but not in the CI.
Any comment welcome, as I am currently out of ideas to fix this.

**Comment by MarcusDenker** [comment]
The test FluidClassDefinitionPrinterTest>>#testChronologyConstants fails because the order of the variables somehow changed.. but only when printing the class definition for the fluid case, the other printouts (non-fluid) sort the class vars alphabetically and have no problem.


we could just change the test to be:

```
testChronologyConstants

	self
		assert: (self forClass: ChronologyConstants)
		equals: 'SharedPool << #ChronologyConstants
	sharedVariables: { #SqueakEpoch . #SecondsInDay . #DayNames . #MonthNames . #SecondsInHour . #MicrosecondsInDay . #NanosInSecond . #SecondsInMinute . #NanosInMillisecond . #DaysInMonth . #NanosInMicroSecond . #HoursInDay . #MinutesInHour };
	tag: ''Chronology'';
	package: ''Kernel'''
```

**Comment by hogoww** [comment]
> The test FluidClassDefinitionPrinterTest>>#testChronologyConstants fails because the order of the variables somehow changed.. but only when printing the class definition for the fluid case, the other printouts (non-fluid) sort the class vars alphabetically and have no problem.
> 
> we could just change the test to be:
> 
> ```
> testChronologyConstants
> 
> 	self
> 		assert: (self forClass: ChronologyConstants)
> 		equals: 'SharedPool << #ChronologyConstants
> 	sharedVariables: { #SqueakEpoch . #SecondsInDay . #DayNames . #MonthNames . #SecondsInHour . #MicrosecondsInDay . #NanosInSecond . #SecondsInMinute . #NanosInMillisecond . #DaysInMonth . #NanosInMicroSecond . #HoursInDay . #MinutesInHour };
> 	tag: ''Chronology'';
> 	package: ''Kernel'''
> ```

Already done, and they pass locally (see previous commit)

**Comment by MarcusDenker** [comment]
but if I download the build artefact, the test fails

**Comment by hogoww** [comment]
Good point.
I always forget we can do that.
My theory is that the formater may have changed the order.
I'll update when I can

**Pull request merged**
