### PR TITLE
Remove MCPatchBrowser

### PR DESCRIPTION
**Pull request by jecisc**
This browser is not used anymore and contains code thet use called but not implemented so it is not even functional

### CODE REVIEW

**Comment by Ducasse** [comment]
Beginning to run tests of ThreadedFFI-UFFI-Tests
PrimitiveFailed: primitive #primFreeDefinition in TFFunctionDefinition failed
TFFunctionDefinition(ProtoObject)>>primitiveFailed:
TFFunctionDefinition(ProtoObject)>>primitiveFailed
TFFunctionDefinition>>primFreeDefinition

Is breaking 
I think that this is not related
@tesonep

**Comment by Ducasse** [comment]
Look nice.

**Comment by Ducasse** [comment]
Now waiting for the tests to run.

**Comment by MarcusDenker** [comment]
There is a problem that TFFunctionDefinition>>primFreeDefinition started crashing and we have no idea why

Due to this, tests can not be run so all PRs are on hold for now

**Pull request merged**
