### PR TITLE
2782-Athens-does-not-have-a-way-to-set-and-get-the-fill-rule

### PR DESCRIPTION
**Pull request by akevalion**
Update fill rule for athens, check AthensSurfaceExamples >> #drawSetFillRule example

### CODE REVIEW

**Comment by MarcusDenker** [comment]
this seems to have the same problem as ##2796

**Comment by MarcusDenker** [comment]
Did you try to do the PR from Pharo 7?

**Comment by akevalion** [comment]
For this PR I use this video https://www.youtube.com/watch?v=PK2yCu2rWCc
In pharo7 32 bits in MacOs.
In this part of the video https://youtu.be/PK2yCu2rWCc?t=150 I use **new branch from issue** github version

I have a fork on https://github.com/akevalion/pharo but my image have all these commits, but I only work on athens

image

I will ask for help to @guillep

**Comment by Ducasse** [comment]
Milton 

You should do a PR from a P8 image. 
You should 
- Download the latest image but not necessary
- Use Repair -> creates a branch (call bottom) it will synchronise the image with the latest changes.
- Then you create a new branch for the bug issues
- And you do a PR.

If you want we can do a pair programming session.
Stef

**Comment by akevalion** [comment]
Hi Stéphane,

Thank you for your help.
Yes we can do a pair programming session, how can I contact you and when?

**Comment by Ducasse** [comment]
I shared screen with milton and we redid a new PR.

**Pull request closed without merging**
