### PR TITLE
Loaded Fuel 3.0.2

### LINKED ISSUE #5870: Integrate Fuel 3.0.2

### PR DESCRIPTION
**Pull request by theseion**
Fixes #5870

### CODE REVIEW

**Comment by MarcusDenker** [comment]
the build fails with:

l:///builds/workspace/uest_and_branch_Pipeline_PR-5871/32/src
[32] MetacelloNotification: Project: Fuel baseline
[32] Error: Name not found: Tools
[32] MetacelloMCVersionSpec(Object)>>error:

**Comment by astares** [comment]
Also note what I wrote on https://lists.pharo.org/pipermail/pharo-dev_lists.pharo.org/2020-March/277599.html

<blockquote><div><strong><a href="https://lists.pharo.org/pipermail/pharo-dev_lists.pharo.org/2020-March/277599.html">[Pharo-dev] Updated Fuel version for Pharo 8</a></strong></div></blockquote>

**Comment by theseion** [comment]
@MarcusDenker Thanks, I'll try to fix that.
@astares I did that. I merged everything from Pharo 9.

**Comment by astares** [comment]
@theseion OK thanks! Did not know you have seen the mail.

**Comment by theseion** [comment]
Arrgh... I need to update all users of BaselineOfFuel... BaselineOfUI, BaselineOfMorphic...

**Comment by theseion** [comment]
In `BaselineOfUI` there was a load instruction for `Tools` which hasn't existed for a couple of years now (no idea how that could work...).
In `BaselineOfMorphic` there's some weird initialization magic which I assume is necessary... for something.... Anyway, I left it there and just updated it to be independent from any version.

**Comment by theseion** [comment]
Verification fails with ```
OmFileStoreReadingError: Reading entry from File @ /builds/workspace/uest_and_branch_Pipeline_PR-5871/Tests-osx-32/pharo-local/ombu-sessions/Pharo8.0-PR-32bit-3a8bd24.2w3iz4fvj7bj1xptgktezs3z1.ombu@10223618: Illegal leading byte for utf-8 encoding```

**Comment by MarcusDenker** [comment]
The OmFileStoreReadingError is not related, it is some random test failing somtimes due to the CI setup having problems.

There are failing tests, though:     SystemDependenciesTest detects some changes in dependencies

**Comment by theseion** [comment]
Oh, ok. I didn't see that (the log is very prominent... :)).

**Comment by theseion** [comment]
Now the builds are just being aborted due to timeouts...

**Comment by guillep** [comment]
I relaunched the CI. Let's see how it goes.

**Comment by guillep** [comment]
The build fails. It's very probably an infinite loop while installing one of the baselines.
I'm checking the code in the PR, the changes in the baselines are too big...
It maybe makes sense to try to reproduce the build locally following the instructions in the README.

**Comment by theseion** [comment]
Thanks Guille. I'll see what I can find tomorrow.

**Comment by Ducasse** [comment]
The broken tests are unrelated (HTTP)

**Comment by Ducasse** [comment]
was this PR integrated in P9

**Comment by theseion** [comment]
Thanks Stef. I think the SystemDependenyTest fails because auf Fuel. I'll check that and open another PR if I have to.

**Pull request merged**
