### PR TITLE
Fix Year>>firstThursday

### LINKED ISSUE #2453: Year>>firstThursday sometimes returns a day from the preceding year.
Example: `(Year year: 1988) firstThursday year` yields `1987`.

(I have a bug fix with test that I will submit soon.)

### PR DESCRIPTION
**Pull request by khinsen**
Ensure that it never returns a date in the… preceding year.
Test case provided.
Fixes #2453.

### CODE REVIEW

**Comment by khinsen** [comment]
Note: my signed contributor agreement is in the mail.

**Comment by svenvc** [comment]
Assuming nothing else broke, I agree with this change

**Comment by Ducasse** [comment]
I love when fix are proposed with tests!!!! Excellent!
Tx

**Comment by khinsen** [comment]
What's wrong with continuous integration? It says that one check failed, but when I click on "Details" it shows no problem at all.

**Comment by Ducasse** [comment]
I can see the details and may be you do not have access. The failed tests are not related.

**Pull request merged**
