### PR TITLE
Move business logic from new tools to system-support

### LINKED ISSUE #7658: StSystemReporter and StSizeReporter should be splitted
**Describe the problem**
StSystemReporter  and StSizeReporter should be splitted to do not contain business logic but only the UI part

### PR DESCRIPTION
**Pull request by demarey**
fixes #7658

### CODE REVIEW

**Comment by Ducasse** [comment]
I like your fix. Because after StSystemReporter can just delegate to this low level object. 
Now we have many dependency tests broken and I still do not understand how to fix them.

**Comment by estebanlm** [comment]
splitting is ok... but why move that to System-Support?
IMO this would still be better as business logic of an optional tool.

**Comment by demarey** [comment]
Did you check that it is  now in a dedicated package?

**Comment by estebanlm** [comment]
yes, a dedicated package in BasicTools. 
why not to split 

NewTools-SystemReporter-View
NewTools-SystemReporter-Model

and put that into model? 
in other words, why this has to be moved to the base system, when is clearly a tool that could, or not, be in the image?

**Comment by demarey** [comment]
because some tools like smalltalkCI relies on that SystemReporter.
They expect it to be in the core image. It can be discussed. but then if the code is not in the core image, it will be duplicated in other tools :(

**Comment by Ducasse** [comment]
I agree with Christophe. BTW some tests broken. Such as undeclared.

**Comment by guillep** [comment]
Three tests are broken:

- testUndeclared – Unix64.ReleaseTests.Release.ReleaseTest
```
Error
Found undeclared references: #(#imageClassPackages #imageClasses #manifestClassLoc #effectiveClasses #testClassPackages #baselineClassLoc #effectiveClassPackages #manifestClasses #baselineClassPackages #testClasses #imageClassLoc #testClassLoc #baselineClasses)
Salida
TestFailure
Found undeclared references: #(#imageClassPackages #imageClasses #manifestClassLoc #effectiveClasses #testClassPackages #baselineClassLoc #effectiveClassPackages #manifestClasses #baselineClassPackages #testClasses #imageClassLoc #testClassLoc #baselineClasses)
ReleaseTest(TestAsserter)>>assert:description:resumable:
ReleaseTest(TestAsserter)>>assert:description:
ReleaseTest>>testUndeclared
ReleaseTest(TestCase)>>performTest
```
- testExternalBasicToolsDependencies – Unix64.System.DependenciesTests.SystemDependenciesTest
```
Error
key 'System-Reporter' not found in Dictionary
Salida
KeyNotFound
key 'System-Reporter' not found in Dictionary
Dictionary>>errorKeyNotFound:
[self errorKeyNotFound: key] in Dictionary>>at:
Dictionary>>at:ifAbsent:
Dictionary>>at:
DADependencyReport>>dependenciesOf:
[ :aPackage | self dependenciesReport dependenciesOf: aPackage ] in SystemDependenciesTest>>externalDependendiesOf:
[ :each | col addAll: (aBlock value: each) ] in Array(Collection)>>flatCollect:as:
Array(SequenceableCollection)>>do:
Array(Collection)>>flatCollect:as:
SystemDependenciesTest>>externalDependendiesOf:
SystemDependenciesTest>>testExternalBasicToolsDependencies
SystemDependenciesTest(TestCase)>>performTest
```
- testExternalIDEDependencies – Unix64.System.DependenciesTests.SystemDependenciesTest
```
Error
key 'System-Reporter' not found in Dictionary
Salida
KeyNotFound
key 'System-Reporter' not found in Dictionary
Dictionary>>errorKeyNotFound:
[self errorKeyNotFound: key] in Dictionary>>at:
Dictionary>>at:ifAbsent:
Dictionary>>at:
DADependencyReport>>dependenciesOf:
[ :aPackage | self dependenciesReport dependenciesOf: aPackage ] in SystemDependenciesTest>>externalDependendiesOf:
[ :each | col addAll: (aBlock value: each) ] in Array(Collection)>>flatCollect:as:
Array(SequenceableCollection)>>do:
Array(Collection)>>flatCollect:as:
SystemDependenciesTest>>externalDependendiesOf:
SystemDependenciesTest>>testExternalIDEDependencies
SystemDependenciesTest(TestCase)>>performTest
```

**Pull request merged**
