### PR TITLE
21680-haltIfTest-and-haltIfNotTest-and-comments

### PR DESCRIPTION
**Pull request by MarcusDenker**
haltIfTest and haltIfNotTest and comments
	https://pharo.fogbugz.com/f/cases/21680/haltIfTest-and-haltIfNotTest-and-comments

### CODE REVIEW

**Comment by MarcusDenker** [comment]
aargh...

**Comment by MarcusDenker** [comment]
I really do not understand why I get always problems.

**Comment by estebanlm** [comment]
someone changed it before you?

**Comment by MarcusDenker** [comment]
No

**Comment by estebanlm** [comment]
bue... I don't know. I fixed the conflicts in any case. 
but well, tomorrow the next iceberg version will be ready so we'll see there.

**Review by dionisiydk — APPROVED** [review]
Good

**Pull request merged**
