### PR TITLE
Remove Author

### PR DESCRIPTION
**Pull request by guillep**
Lots of cleanups
 - remove the Author class (and with it the useless popup)
 - remove dependency from many users

### CODE REVIEW

**Comment by Ducasse** [comment]
Trop cool ;)

**Comment by guillep** [comment]
Only 400 lines removed oveall, I'm disappointed

imagen

**Comment by badetitou** [comment]
Yeesss plleeaaassseee!!!!!

**Comment by MarcusDenker** [comment]
But is this for Pharo10? In the sense... there will be fallout that we did not expect for sure...

**Comment by astares** [comment]
Remove "Author" class or deprecate for one iteration? 

I guess some people might have to modify "startup.st" files where Author is set (like me).

**Comment by Ducasse** [comment]
Sorry but we will not deprecate Author removal.

**Comment by Ducasse** [comment]
Marcus we have one month else it will be in at least 14 months or more. 
For something that annoys us all the time and is useless.

**Comment by Ducasse** [comment]
I saw
```
NewUndeclaredWarning: BreakpointTest>>testAddRemoveBreakpointKeepTimeStamp (Author is Undeclared)
NewUndeclaredWarning: BreakpointTest>>testAddRemoveBreakpointKeepTimeStamp (Author is Undeclared)
NewUndeclaredWarning: LGitExternalStructure class>>createAccessorsFor: (Author is Undeclared)
NewUndeclaredWarning: LGitExternalStructure class>>createAccessorsFor: (Author is Undeclared)
NewUndeclaredWarning: LGitExternalStructure class>>createAccessorsFor: (Author is Undeclared)
NewUndeclaredWarning: LGitExternalStructure class>>createAccessorsFor: (Author is Undeclared)
SystemNotification: RBDummyRefactoryTestDataApp>>tempVarOverridesInstVar(temporaryVariable is shadowed)
SystemNotification: RBDummyRefactoryTestDataApp>>tempVarOverridesInstVar(temporaryVariable is shadowed)
SystemNotification: RBRefactoryTestDataApp>>tempVarOverridesInstVar(temporaryVariable is shadowed)
SystemNotification: RBRefactoryTestDataApp>>tempVarOverridesInstVar(temporaryVariable is shadowed)
SystemNotification: RBSmalllintTestObject>>tempVarOverridesInstVar(temporaryVariable is shadowed)
SystemNotification: RBSmalllintTestObject>>tempVarOverridesInstVar(temporaryVariable is shadowed)
SystemNotification: ReTempVarOverridesInstVarRuleTest>>sampleMethod:(dummy1 is shadowed)
SystemNotification: ReTempVarOverridesInstVarRuleTest>>sampleMethod:(dummy2 is shadowed)
SystemNotification: ReTempVarOverridesInstVarRuleTest>>sampleMethod:(dummy3 is shadowed)
SystemNotification: ReTempVarOverridesInstVarRuleTest>>sampleMethod:(dummy1 is shadowed)
SystemNotification: ReTempVarOverridesInstVarRuleTest>>sampleMethod:(dummy2 is shadowed)
SystemNotification: ReTempVarOverridesInstVarRuleTest>>sampleMethod:(dummy3 is shadowed)
NewUndeclaredWarning: Class>>inspectionClassComment (Author is Undeclared)
NewUndeclaredWarning: Class>>inspectionClassComment (Author is Undeclared)
NewUndeclaredWarning: ClyClassWithUndeclares>>method1WithUndeclares (undeclaredStubInstVar1 is Undeclared)
NewUndeclaredWarning: ClyClassWithUndeclares>>method1WithUndeclares (undeclaredStubInstVar1 is Undeclared)
NewUndeclaredWarning: ClyClassWithUndeclares>>method2WithUndeclares (undeclaredStubInstVar2 is Undeclared)
NewUndeclaredWarning: ClyClassWithUndeclares>>method2WithUndeclares (undeclaredStubInstVar2 is Undeclared)
NewUndeclaredWarning: IceMCVersionInfo>>fromPackage:message: (Author is Undeclared)
NewUndeclaredWarning: IceMCVersionInfo>>fromPackage:message: (Author is Undeclared)
```

**Comment by tesonep** [comment]
I don't know, we have users that still depends on the versioning done by the author and modification of methods. I will not push it now without having an alternative.

**Comment by tesonep** [comment]
I think we should provide a loadable package with this. It is true that for the newies is a crap to show the popup. An initial step could be to put a setting to not ask the author everytime.

**Comment by guillep** [comment]
I'm not against pushing this to after the release (I just did it and push it because I had 2 dead hours).

I agree with @tesonep's @astares's concern about backwards compatibility. We may have people requiring it, we should think about what to do with it. @sbragagnolo just proposed next to me a good alternative would be also to automatically take the name from the OS User (which could be done by reading environment variables ;)).

**Comment by Ducasse** [comment]
Ok but why do we need this?

**Comment by jordanmontt** [comment]
+1 for removing `Author`

**Comment by guillep** [comment]
As a follow up, this needs to be reworked a bit:
 - it has merge conflicts now :)
 - we need an altenative for those users that are not depending on Git and still need some Authorship support. I think we could build an authorship support using announcements.

**Comment by guillep** [comment]
Too many conflicts, I'll re-do it for now

**Pull request closed without merging**
