### PR TITLE
22802-ZipArchive-should-throw-specific-Error

### PR DESCRIPTION
**Pull request by Ducasse**
Introduce ZipArchiveError

### CODE REVIEW

**Comment by jecisc** [comment]
Seems fine. I'll wait CI validation to approve.

**Review by MarcusDenker — APPROVED** [review]
ok

**Comment by MarcusDenker** [comment]
https://pharo.fogbugz.com/f/cases/22802/ZipArchive-should-throw-specific-Error

**Comment by MarcusDenker** [comment]
(it simplifies things if there is a link from the PR to the issue)

**Comment by Ducasse** [comment]
To me this is not a problem but I'm not sure. 



First time build. Skipping changelog.
[Pipeline] sh
+ git log -1 --format=%B
[Pipeline] sh
+ git log -1 --format=%p
[Pipeline] mail
[Pipeline] cleanWs
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 143
Finished: FAILURE

**Pull request merged**
