### PR TITLE
Is FormCanvas available?

### PR DESCRIPTION
**Pull request by kasperosterbye**
This PR is for trying to figure out what is the error in #10625.
Do not merge just now even if succeeding.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
I am sure that the class exists. The image is the same... it just fails the test because it is running headless or something like that.

**Comment by kasperosterbye** [comment]
Now - When I press details above I get this image: 
image

When pressing the yellow osx-64 I get something like this:
image

I can download the log, but I can not find out what actually caused the osx-64 to fail - where do you and Stef look that I overlook?

**Comment by tesonep** [comment]
The class exists in the image, the image used in the tests is the same that is produced. 
You can get the image with the changes from the artefacts of the CI execution. 
For example, for this PR the artifacts are here:
https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-10627/1/artifacts

And the image you wish is in the .zip file **bootstrap-cache/Pharo10.0-PR-64bit-9fc141b.zip**
In this case, as the PR has been integrated, the test will fail in the latest image.
To execute the test and see the error you can do in a terminal:

```bash
./pharo Pharo10.0-PR-64bit-634eaa6.image test --junit-xml-output "Rubric.*"
````
This will generate the same .xml files that the CI (it is the command executed by the CI).

<blockquote><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-10627/1/artifacts">Jenkins</a></strong></div></blockquote>

**Comment by kasperosterbye** [comment]
Thanks for pointing to the artifacts tab @tesonep. When downloading the Pharo10.0-PR-64bit-9fc141b image and starting it on my machine all rubrics tests are green.

**Pull request closed without merging**
