### PR TITLE
Unification of simple form of "isAbstract" method.

### PR DESCRIPTION
**Pull request by kamk**
Among three most common implementations:
1. self = SomeClass
2. self == SomeClass
3. self name = #SomeClass

second one is the most fastest.

See original FogBugz [case #22771](https://pharo.fogbugz.com/f/cases/22771/isAbstract-for-classes-should-be-unified).

### CODE REVIEW

**Comment by dionisiydk** [comment]
We had discussion in mailing list in past: [Pharo-dev] how implement isAbstract?. 
I did not remember if we had any agreement. The discussion seems was moved to another question why we need isAbstract.

**Comment by Ducasse** [comment]
Thanks denis. I think that in addition it can also give an indirection in case of proxies.

**Comment by Ducasse** [comment]
I think that we should close all the fogbugz because they are old now.

**Comment by kamk** [comment]
I see, I've found the [discussion here](http://forum.world.st/how-implement-isAbstract-td5097729.html#a5097747).

**Comment by Ducasse** [comment]
Thanks for putting the reference. I reread all the thread and I like the remark of guille.
I like that people mark the class as abstract while relying on subclassResponsibility.

**Pull request closed without merging**
