### PR TITLE
Enhance double click and drag behaviour 

### PR DESCRIPTION
**Pull request by akevalion**
issues related: 
- https://github.com/pharo-project/pharo/issues/12428

### CODE REVIEW

**Comment by MarcusDenker** [comment]
- CI] testExternalMorphicCoreDependencies is failing #12441

**Review by guillep — CHANGES_REQUESTED** [review]
these are tricky changes... Would be nice they are accompanied by some test...

**Comment by akevalion** [comment]
Hi I will add a test class for MouseClickState,
I also check the test `testExternalMorphicCoreDependencies`, It pass on my machine, however I see the dependency between `Morphic-Core` and `Graphics-Files`.  Because the method `ImageMorph class >> #fromStream:`

Then I do not know why this tests is failing in CI

**Comment by guillep** [comment]
The testExternalMorphicCoreDependencies is my wrong doing, there is a pr to fix it already

**Comment by akevalion** [comment]
@MarcusDenker can we reopen this issue it was closed by mistake

**Comment by MarcusDenker** [comment]
The PR can not be re-opened, strangely

**Comment by jecisc** [comment]
The branch on Milton repository is up to date with the current Pharo. 
Was there a force push?

**Comment by jecisc** [comment]
There was indeed. You forced push Milton and removed all changes

**Comment by MarcusDenker** [comment]
problem

**Comment by akevalion** [comment]
I see, I will create a new pull request with test and I will refer to this pull request

**Pull request closed without merging**
