### PR TITLE
10319-OSSDL2BackendWindowfetchDPI-seems-broken

### LINKED ISSUE #10319: OSSDL2BackendWindow>>#fetchDPI seems broken
**Bug description**
`OSSDL2BackendWindow>>#fetchDPI` can't fetch correct DPI settings, newScreenScaleFactor temp is always 1.0d0
I tested on Windows 10 machines, both virtual and physical

**To Reproduce**
1. In Windows display settings (right click on desktop>Display settings), set the scale factor (DPI) to anything but 100%
2. Open a Pharo image (notice the scale of Pharo is wrong compared to other apps)
3. Inspect `OSSDL2BackendWindow allInstances first screenScaleFactor`.
4. You get `1` instead of your actual scale factor

**Expected behavior**
`OSSDL2BackendWindow>>#fetchDPI` should get the correct DPI value, so that Pharo scales correctly

**Screenshots**
On the screenshot, notice Pharo's scale factor set to 1, with this setting we except Pharo to scale like other apps, but it can't because `OSSDL2BackendWindow>>#screenScaleFactor` returns `1` instead of `1.75`
pharo-DPI

**Version information:**
 - OS: Windows 10
Pharo 9.0.0
Build information: Pharo-9.0.0+build.1564.sha.f5f541cb35c8609abfec418e35d5506715c7987d (64 Bit)

### PR DESCRIPTION
**Pull request by tesonep**
Fix #10319 
It is related to #9038 
@sonibla can you check if it improves #9038?

### CODE REVIEW

**Comment by astares** [comment]
@tesonep Be aware that this reverts https://github.com/pharo-project/pharo/pull/9716/files which was done to fix https://github.com/pharo-project/pharo/issues/9715 which might then reappear, no?

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo/pull/9716">Pharo 9 looks bad on Windows HiDPI Devices (Microsoft Surface) by astares · Pull Request #9716 · pharo-project/pharo</a></strong></div><div>Fix #9715</div></blockquote>

**Comment by tesonep** [comment]
Yes, the previous PR was disabling the scaling basically. It is true that the scaled version is blured, but it is better than have an smaller world. I will put a setting to disable automatic scaling.

**Comment by guillep** [comment]
Needs to be forward ported to Pharo 10

**Comment by astares** [comment]
@tesonep: it was already merged by @guillep.  Will you open another issue so we can have it as a setting?

**Pull request merged**
