### PR TITLE
Use-platform-visitor-in-native-browser

### PR DESCRIPTION
**Pull request by jecisc**
Chirstophe added platform visitor in Pharo8. This PR takes advantage of it in NativeBrowser.

### CODE REVIEW

**Review by pavel-krivanek — APPROVED** [review]
works ;-)

**Comment by astares** [comment]
Can we still please rename into NativeFileBrowser?

**Comment by MarcusDenker** [comment]
So what is the status? Do we merge and then rename? or is the idea that this PR will be updated? or replaced?

In general, it is much easier to merge everything that is a good step and do the next step in next PR

**Comment by astares** [comment]
Side note: the renaming is handled in https://github.com/pharo-project/pharo/issues/2523

**Comment by MarcusDenker** [comment]
There is now a conflict

**Comment by MarcusDenker** [comment]
So this is why I asked about merging... to me it was clear that if we merge the second step before this then we would get a conflict.

**Comment by jecisc** [comment]
Fixed.

**Comment by jecisc** [comment]
Can we remove the Need More Work tag, please? This is working and pass the tests.

**Comment by jecisc** [comment]
Ping

**Pull request merged**
