### PR TITLE
21677-Accept-for-Test

### PR DESCRIPTION
**Pull request by MarcusDenker**
Accept for Test
	https://pharo.fogbugz.com/f/cases/21677/Accept-for-Test

### CODE REVIEW

**Comment by dionisiydk** [comment]
Few notes:

- Sugs are not used in Calypso anymore. Look how ClyAddBreakpointCommand is done.
- This new metalink is definitely should be managed like breakpoints and counters. So we can show them in the browser with menu options and auto updates. And even to show dirty editor with actual code when user opens such method
- Would not it better to extract #isTest check to metalink #condition: instead of anything inside metaobject? And maybe "metalink activateInTest" would be nice addition (like new halts).
- And tests are really welcome for this especially that it looks not difficult to test

**Comment by MarcusDenker** [comment]
to all of them: yes :-)

**Comment by pavel-krivanek** [comment]
I tried to test the generated image and it does not seem to work. Can you, please, check it?

**Comment by MarcusDenker** [comment]
I will close this and redo it for Calypso

**Pull request closed without merging**
