### PR TITLE
10536 rubric embedded morphs sometimes misplaced

### PR DESCRIPTION
**Pull request by kasperosterbye**
I drew inspiration from how segments morphs were handled, and added a new instance variable embeddedMorphs to handle embedded morphs more consistently. 
The way it is done is a collaboration between RubAbstractTextArea and the RubDisplayScanner. 

Besides the added tests, there is also an example on the class side of RubAbstractTextArea which can be used to check the behaviour with ones eyes.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Failin tests are related:

unix-64 / Tests-unix-64 / testSetUpMethodInSUnitTestsNeedsToBeInRunningProtocol – Unix64.ReleaseTests.Categorization.ProperMethodCategorizationTest
unix-64 / Tests-unix-64 / testEmbeddedAnchorInTextAreDrawnAtRightPosition

**Comment by kasperosterbye** [comment]
Thanks @MarcusDenker, yes, I forgot to run the release tests before I made the PR.

**Comment by kasperosterbye** [comment]
The release tests are now running at my newly downloaded image - a few hours at most. 
Waiting for the CI to start.

**Comment by kasperosterbye** [comment]
Cool - so that is how one restarts the CI - close and reopen the issue :-)

**Comment by kasperosterbye** [comment]
Well, I cannot find those errors you pointed out anymore @MarcusDenker.
Is there an explanation of the CI chain used so I might get a better understanding of if an error is in my code or somewhere else.

**Comment by kasperosterbye** [comment]
Trying once more to see if I can find the errors

**Comment by kasperosterbye** [comment]
I just installed this PR in a clean image, ran all tests related to Rubrics and Calypso (which makes heavy use of Rubrics) - all green. I ran the Release tests - no errors related to this PR.

**Comment by kasperosterbye** [comment]
So I try once again to see if it is OK

**Comment by Ducasse** [comment]
Hi kasper
Are the following tests passing in your setup?

testEmbeddedAnchorInTextAreDrawnAtRightPosition – MacOSX64.Rubric.Tests.Base.RubEditingAreaTest
testEmbeddedAnchorInTextAreDrawnAtRightPosition – MacOSX64.Rubric.Tests.Base.RubScrolledTextMorphTest
testOpenPresenterRaisesDisplayEvent – MacOSX64.Spec2.Tests.Examples.Wrapper.SpOpenOnStringExampleTest
testEmbeddedAnchorInTextAreDrawnAtRightPosition – Unix64.Rubric.Tests.Base.RubEditingAreaTest
testEmbeddedAnchorInTextAreDrawnAtRightPosition – Unix64.Rubric.Tests.Base.RubScrolledTextMorphTest

Because they fail on the CI.

S

**Comment by Ducasse** [comment]
We will investigate.

**Comment by tesonep** [comment]
I have checked and the tests are failing when those are run in headless.
I think they are depending in the state of open windows and Morphic.

**Comment by kasperosterbye** [comment]
Yes, the test succeed in my setup @Ducasse - I checked again this morning in a fresh image.

The tests I have do indeed depend on morphic windows opening (and being closed). I will see if I can come up with a way in which this is not the case. Thanks for deciphering this for me @tesonep.

**Comment by kasperosterbye** [comment]
> Hi kasper Are the following tests passing in your setup?
> 
> testEmbeddedAnchorInTextAreDrawnAtRightPosition – MacOSX64.Rubric.Tests.Base.RubEditingAreaTest testEmbeddedAnchorInTextAreDrawnAtRightPosition – MacOSX64.Rubric.Tests.Base.RubScrolledTextMorphTest testOpenPresenterRaisesDisplayEvent – MacOSX64.Spec2.Tests.Examples.Wrapper.SpOpenOnStringExampleTest testEmbeddedAnchorInTextAreDrawnAtRightPosition – Unix64.Rubric.Tests.Base.RubEditingAreaTest testEmbeddedAnchorInTextAreDrawnAtRightPosition – Unix64.Rubric.Tests.Base.RubScrolledTextMorphTest
> 
> Because they fail on the CI.
> 
> S

Where do you find that list @Ducasse? I am obviously rather clueless, but I have looked everywhere I know of and quite a few more, and I cannot find that list.

**Comment by Ducasse** [comment]
You can find them when you click on details.

**Comment by MarcusDenker** [comment]
It seems that

RubEditingAreaTest>>testEmbeddedAnchorInTextAreDrawnAtRightPosition


is now failing on the CI for all three platforms, I opened a new issue tracker entry (#10625  )

**Comment by tesonep** [comment]
@MarcusDenker this PR introduced the error in the test.
Maybe we need to revert the PR. It is clearly related, if there is not a fix soon maybe reverting the merge is the best option.

**Comment by kasperosterbye** [comment]
I will fix it later tonight. Removing the test will keep it working. It's related to headless somehow. Make a  new issue to get a working test

**Pull request merged**
