### PR TITLE
3820-Spec2-update

### LINKED ISSUE #3820: Spec2 update
## New features

*   Add a widget to select a Method ([ed1e7be](https://github.com/pharo-spec/Spec/commit/ed1e7be0e3882cefbdaf464fbac75797f5f4170d))

## Bug fixes

*   ModalWindowPresenter Does not allow to expand dropList ([b768ad2](https://github.com/pharo-spec/Spec/commit/b768ad25b09ad3a094a1d451939cb59bf679e631))

## Cleaning

*   Do a pass on the API to improve its coherency 
*   Use the direction strategy instead of performs in paned layout ([73dc7c1](https://github.com/pharo-spec/Spec/commit/73dc7c171a5d9360329fbde060d1aebeb2bd9ea9))
*   SpObservableSlot should not depend on ValueHolder ([944734e](https://github.com/pharo-spec/Spec/commit/944734eee94937bb0c477db0a5a1e153f65f86f1))
*   Migrate new value holders to observable slot step 2 ([e792b87](https://github.com/pharo-spec/Spec/commit/e792b87c9e826e5db3fc8cbe6faaf200b5ede157))
*   Adapters bindings default fonts methods are not used ([b77f753](https://github.com/pharo-spec/Spec/commit/b77f7535ad0429f9ef050c7fece04c395c4c862d))
*   Deprecate SearchableList in favor of list filtering ([c5543d7](https://github.com/pharo-spec/Spec/commit/c5543d757177f857071dde6c8cc55905c55dd787))
*   Migrate more layouts to executable layouts ([2beb04a](https://github.com/pharo-spec/Spec/commit/2beb04aa3c5833fa61e4313f67435911bca24367))
*   Reduce references to theme singleton ([b6f8de2](https://github.com/pharo-spec/Spec/commit/b6f8de2521331034f9b5d990f288c8dc2b814c40))
*   addAllwithSpec is dead code ([235ab64](https://github.com/pharo-spec/Spec/commit/235ab64d3cdbd6bd6c3563702a513bcc0b66ad79))
*   Clean EyeInspector ([6e60302](https://github.com/pharo-spec/Spec/commit/6e603021d44e50bf2816dd343604b96de5417f62))
*   Remove deprecated examples ([3b1ea77](https://github.com/pharo-spec/Spec/commit/3b1ea778cf5ee75cb551266c12a6254dc84f1a24))

## Infrastructure

*   Skip failing tests for now ([bb194b4](https://github.com/pharo-spec/Spec/commit/bb194b47983c60a617d394eb7eef84a2559e2f26))
*   Harvest changes from Pharo ([61e8b9f](https://github.com/pharo-spec/Spec/commit/61e8b9fa80a5d4cb7695189d2f5214b134457295))

### PR DESCRIPTION
**Pull request by jecisc**
## New features

*   Add a widget to select a Method ([ed1e7be](https://github.com/pharo-spec/Spec/commit/ed1e7be0e3882cefbdaf464fbac75797f5f4170d))

## Bug fixes

*   ModalWindowPresenter Does not allow to expand dropList ([b768ad2](https://github.com/pharo-spec/Spec/commit/b768ad25b09ad3a094a1d451939cb59bf679e631))

## Cleaning

*   Do a pass on the API to improve its coherency 
*   Use the direction strategy instead of performs in paned layout ([73dc7c1](https://github.com/pharo-spec/Spec/commit/73dc7c171a5d9360329fbde060d1aebeb2bd9ea9))
*   SpObservableSlot should not depend on ValueHolder ([944734e](https://github.com/pharo-spec/Spec/commit/944734eee94937bb0c477db0a5a1e153f65f86f1))
*   Migrate new value holders to observable slot step 2 ([e792b87](https://github.com/pharo-spec/Spec/commit/e792b87c9e826e5db3fc8cbe6faaf200b5ede157))
*   Adapters bindings default fonts methods are not used ([b77f753](https://github.com/pharo-spec/Spec/commit/b77f7535ad0429f9ef050c7fece04c395c4c862d))
*   Deprecate SearchableList in favor of list filtering ([c5543d7](https://github.com/pharo-spec/Spec/commit/c5543d757177f857071dde6c8cc55905c55dd787))
*   Migrate more layouts to executable layouts ([2beb04a](https://github.com/pharo-spec/Spec/commit/2beb04aa3c5833fa61e4313f67435911bca24367))
*   Reduce references to theme singleton ([b6f8de2](https://github.com/pharo-spec/Spec/commit/b6f8de2521331034f9b5d990f288c8dc2b814c40))
*   addAllwithSpec is dead code ([235ab64](https://github.com/pharo-spec/Spec/commit/235ab64d3cdbd6bd6c3563702a513bcc0b66ad79))
*   Clean EyeInspector ([6e60302](https://github.com/pharo-spec/Spec/commit/6e603021d44e50bf2816dd343604b96de5417f62))
*   Remove deprecated examples ([3b1ea77](https://github.com/pharo-spec/Spec/commit/3b1ea778cf5ee75cb551266c12a6254dc84f1a24))

## Infrastructure

*   Skip failing tests for now ([bb194b4](https://github.com/pharo-spec/Spec/commit/bb194b47983c60a617d394eb7eef84a2559e2f26))
*   Harvest changes from Pharo ([61e8b9f](https://github.com/pharo-spec/Spec/commit/61e8b9fa80a5d4cb7695189d2f5214b134457295))

Fixes #3820

### CODE REVIEW

**Comment by MarcusDenker** [comment]
errors are related, most seem to be

Error
receiver of "for:" is nil
Stacktrace
UndefinedObject>>doesNotUnderstand: #for:
SpCodePresenter>>buildCodeMenu

**Comment by jecisc** [comment]
Let's hope it pass now :)

**Comment by MarcusDenker** [comment]
Error
Given Collections do not match. Got left := #(#'Commander-Activators-ContextMenu'). instead of right :=#(). Collection size does not match: left=1 vs. right=0 Got 1 additional element(s) in the left collection: #(#'Commander-Activators-ContextMenu')
Stacktrace
SystemDependenciesTest(TestAsserter)>>assert:description:resumable:
SystemDependenciesTest(TestAsserter)>>assert:description:
SystemDependenciesTest(TestAsserter)>>assertCollection:equals:
SystemDependenciesTest>>testExternalIDEDependencies

**Comment by jecisc** [comment]
Tests passed.

**Pull request merged**
