### PR TITLE
Loading documentation reader.

### PR DESCRIPTION
**Pull request by Ducasse**

### CODE REVIEW

**Comment by MarcusDenker** [comment]
There where lots of failing tests... e.g. due to halt in the code.

This now means that all the work to get the CI green was for nothing

**Comment by MarcusDenker** [comment]
These are:

NoUnusedVariablesLeftTest>>testNoUnusedInstanceVariablesLeft
ProperMethodCategorizationTest>>testNoUtilsMethods
ProperMethodCategorizationTest>>testSetUpMethodInSUnitTestsNeedsToBeInRunningProtocol
ReleaseTest>>testMethodsContainNoHalt
ProperMethodCategorizationTest>>testNoUncategorizedMethods
ReleaseTest>>testUndeclared
ReleaseTest>>testNoEquivalentSuperclassMethods


I will add an issue tracker entry for each of them.

**Comment by MarcusDenker** [comment]
But this is getting boring

**Comment by Ducasse** [comment]
Do not worry we will fix them.
The problem is that the critic browser sucks!

**Comment by astares** [comment]
@Ducasse yes it sucks. But we need a new one anyway due to Spec2, no?

Best would be to have immediate feedback directly in the system browser (instead of a separate tool) as in other modern IDE's like Eclipse. There is a yellow/red exclamation mark on packages and classes icons if the rules are violated:

image

and a **Problems** tab (not a pane as in calypso) showing errors and warnings:

image

**Pull request merged**
