### PR TITLE
5494-Rename-rules-to-end-up-with-Rule

### LINKED ISSUE #5494: Rename rules to end up with Rule!!!
ReTestClassNameShouldEndWithTest is a rule should it should terminate with Rule.
We should make also a rule for that!!!!

### PR DESCRIPTION
**Pull request by myroslavarm**
fixes #5494

### CODE REVIEW

**Comment by MarcusDenker** [comment]
ReGlobalVariablesUsageTest
ReTestCaseShouldNotUseInitializeTest

are failing (I guess they reference renamed rules by name)

**Comment by myroslavarm** [comment]
@MarcusDenker it's weird because they don't reference rules by names in the code (and I renamed everything automatically so the references should be updated in any case), but it seems the problem is with the tests names themselves? Let's see if my last commit fixes the fail.

**Review by MarcusDenker — APPROVED** [review]

**Comment by astares** [comment]
@myroslavarm Would be good to add a Release test (see package with this name) to check that included rules end up with "Rule" in the name.

So we keep the quality status and make sure future rules added later to the image follow the same pattern.

**Comment by myroslavarm** [comment]
@astares yeah i thought about it but wasn't sure how to check if something is a rule... i will look into this once i have more time on my hands in a couple of weeks!

**Comment by astares** [comment]
@myroslavarm Thx!

**Pull request merged**
