### PR TITLE
Detach Calypso navigation model

### PR DESCRIPTION
**Pull request by hernanmd**
This PR is part of the effor to #17167 to extract parts of Calypso that can be used outside from Calypso (e.g. NewTools) without the need to load the whole Calypso baseline.

- Create a new Baseline for the Calypso navigation model.
- Update the BaselineOfCalypso

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Build fails with:

```
MetacelloNotification: Loaded -> BaselineOfCalypso --- unresolved
Error: Name not found: Calypso-NavigationModel-Tests
```

**Comment by Ducasse** [comment]
It does not build. So I relaunch the build to verify

**Comment by hernanmd** [comment]
Failing step is not related: Failed step: Archive JUnit-formatted test results: https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-17174/13/pipeline-console/?selected-node=96


<blockquote><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-17174/13/pipeline-console/?selected-node=96">Build log [#13] [Jenkins]</a></strong></div></blockquote>

**Comment by Ducasse** [comment]
Hi hernan

we have 
```
Error Message

Given Collections do not match!  additions : #('Calypso-NavigationModel')  missing: #() 
Stacktrace

TestFailure
Given Collections do not match!
	additions : #('Calypso-NavigationModel')
	missing: #()

SystemDependenciesTest(TestAsserter)>>assert:description:resumable:
SystemDependenciesTest(TestAsserter)>>assert:description:
SystemDependenciesTest(TestAsserter)>>assertCollection:hasSameElements:
SystemDependenciesTest>>testExternalBasicToolsDependencies
SystemDependenciesTest(TestCase)>>performTest
		
```

**Comment by hernanmd** [comment]
> Hi hernan
> 
> we have
> 
> ```
> Error Message
> 
> Given Collections do not match!  additions : #('Calypso-NavigationModel')  missing: #() 
> Stacktrace
> 
> TestFailure
> Given Collections do not match!
> 	additions : #('Calypso-NavigationModel')
> 	missing: #()
> 
> SystemDependenciesTest(TestAsserter)>>assert:description:resumable:
> SystemDependenciesTest(TestAsserter)>>assert:description:
> SystemDependenciesTest(TestAsserter)>>assertCollection:hasSameElements:
> SystemDependenciesTest>>testExternalBasicToolsDependencies
> SystemDependenciesTest(TestCase)>>performTest
> 		
> ```

Hi Stef, since Pharo is checking for external UI dependencies (i.e. NewTools), I've been waiting for [this PR](https://github.com/pharo-spec/NewTools/pull/851) to be integrated for some weeks, so we can kill this dependency.

**Comment by jecisc** [comment]
I reviewed and integrated it

**Comment by hernanmd** [comment]
> I reviewed and integrated it

Thanks Cyril

**Comment by hernanmd** [comment]
> Hi hernan
> 
> we have
> 
> ```
> Error Message
> 
> Given Collections do not match!  additions : #('Calypso-NavigationModel')  missing: #() 
> Stacktrace
> 
> TestFailure
> Given Collections do not match!
> 	additions : #('Calypso-NavigationModel')
> 	missing: #()
> 
> SystemDependenciesTest(TestAsserter)>>assert:description:resumable:
> SystemDependenciesTest(TestAsserter)>>assert:description:
> SystemDependenciesTest(TestAsserter)>>assertCollection:hasSameElements:
> SystemDependenciesTest>>testExternalBasicToolsDependencies
> SystemDependenciesTest(TestCase)>>performTest
> 		
> ```

Sorry for the noise, now only [4 Windows socket tests failing](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-17174/lastCompletedBuild/testReport/), so it can be integrated. @jecisc ?

**Pull request merged**
