### PR TITLE
Improving the performance of SourceFileArray [Backport Pharo7]

### PR DESCRIPTION
**Pull request by tesonep**

### CODE REVIEW

**Comment by tesonep** [comment]
Backport of the fix in Pharo 8. Improving the performance of the Source File

**Review by guillep — APPROVED** [review]
This should get us closer to the performances when writing to the changes file in Pharo6.1.

**Comment by guillep** [comment]
@estebanlm This deserves probably a 7.0.3?

**Comment by estebanlm** [comment]
yes, it deserves it.

**Pull request merged**
