### PR TITLE
Propose a DarkBlueTheme

### PR DESCRIPTION
**Pull request by jecisc**
As discussed during the Pharo 13 planning meeting, I am proposing a new theme for Pharo 13: DarkBlueTheme

Here is a preview:

image

### CODE REVIEW

**Comment by guillep** [comment]
Nice looking!

Some of the broken tests look related.

imagen

**Comment by jecisc** [comment]
I'm sure they are the tests relying on the current style and not on a mock :/

I'll check that

**Comment by guillep** [comment]
> I'm sure they are the tests relying on the current style and not on a mock :/
> 
> I'll check that

Yes, probably making those tests less fragile is a good move

**Comment by jecisc** [comment]
I already rewrote a lot of those tests in P12 to not compare the style applied but to compare the name of the applied style. 

I'll check if I can use that also for those 4 tests because I don't want to have to update them at each theme change

**Comment by jecisc** [comment]
I don't know if the failing AST tests are related. I'll try to check

**Comment by jecisc** [comment]
The remaining failing tests are not related!

**Pull request merged**
