### PR TITLE
Fix clean blocks serialization

### LINKED ISSUE #13755: [Clean Blocks] Test failing with clean blocks enabled: Fuel
When turning on the clean block option in the compiler and recompile all, these tests in Fue fail:

- testSerializeContextToFileNamed 
- testSerializeStackFromContext

### PR DESCRIPTION
**Pull request by PalumboN**
Fix https://github.com/pharo-project/pharo/issues/13755
_By @guillep @DurieuxPol and me in the Sprint, with love ❤️_

### How it was working before

To save a compiled block, before it was saving the `literalIndex` in the method where it is.

The problem is with CleanBlocks, because in that case the method has the ClanBlock object (who has the compiled block).

So, during serialization it was saving `index = 0` and in the materialization it was getting the wrong literal from the method.

### How it is working after this PR

- Serialization: we are saving all the "path" from the method to the compiled block (through literals and CleanBlock objects). This includes the case for nested blocks.
- Materialization: we follow the path from the method until de compiled block 😃

### CODE REVIEW

**Comment by jordanmontt** [comment]
Probable this PR needs to go to: https://github.com/theseion/Fuel too

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/theseion/Fuel">GitHub - theseion/Fuel: Fuel, the Smalltalk object serializer</a></strong></div><div>Fuel, the Smalltalk object serializer. Contribute to theseion/Fuel development by creating an account on GitHub.</div></blockquote>

**Comment by MarcusDenker** [comment]
Some related tests in FLBlockClosureSerializationTest are failing:

 -testBlockClosureChangeDifferentBytecodesConstant
 -testBlockClosureChangeSameBytecodesConstant
 -testBlockClosureChangeDifferentBytecodesClean
 -testCleanBlockClosure 
 -testNestedCleanBlockClosure

**Comment by PalumboN** [comment]
Tests are green! 🟢 🎉

**Review by MarcusDenker — APPROVED** [review]

**Comment by MarcusDenker** [comment]
AARG, so now I merged in Pharo12. What a shit. I reverted it there, so now we have to re-do this PR in Pharo13

**Comment by jecisc** [comment]
> AARG, so now I merged in Pharo12. What a shit. I reverted it there, so now we have to re-do this PR in Pharo13

https://github.com/pharo-project/pharo/pull/16970

**Pull request merged**
