### PR TITLE
Extract Halt from kernel

### PR DESCRIPTION
**Pull request by jecisc**
Halt is a debugging utility. Maybe we can load it later than in the Kernel?

### CODE REVIEW

**Comment by Ducasse** [comment]
:)
We should find all the halt left in the system too :)

**Comment by MarcusDenker** [comment]
There is #testMethodsContainNoHalt 

All methods with a halt are tagged with the pragmas #haltOrBreakpointForTesting or #debuggerCompleteToSender

```
testMethodsContainNoHalt

	| methods |
	methods := SystemNavigation new allMethods select: [ :method | method containsHalt ].
	"these methods are using halt for testing something"
	methods := methods reject: [ :method |
		           method hasPragmaNamed: #haltOrBreakpointForTesting ].
	"these methods are implementing halt, we are not interested"
	methods := methods reject: [ :method |
		           method hasPragmaNamed: #debuggerCompleteToSender ].

	"there should be no method left"
	self assert: methods isEmpty description: [
		String streamContents: [ :stream |
			stream
				nextPutAll: 'Found methods with halt';
				print: methods ] ]
```

**Comment by jecisc** [comment]
Tests are failing because some code is checking the methods of a specific protocol

**Comment by Ducasse** [comment]
Looks good to me. I do not get if the calypso failing test is related

**Comment by jecisc** [comment]
Seems like a random failure. I'll restart it

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
