### PR TITLE
Cleanup: Condense EnlumineurFormatter packages

### LINKED ISSUE #12321: Cleanup: Condense EnlumineurFormatter packages
```Smalltalk
cms := CompiledMethod allInstances select: [:each |
each package ifNil: [ false ] ifNotNil: [:p |
	p name beginsWith: 'EnlumineurFormatter' ] ].

cms do: [:cm |
    ((RBRefactoryChangeFactory instance)
         addMethodSource: (ReMethodSourceCleaner clean: cm sourceCode) in: cm origin) execute ]
```

### PR DESCRIPTION
**Pull request by astares**
Fix #12321

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Lots of tests failing... which is to be expected as the formatter needs to be fixed, too

**Comment by guillep** [comment]
Yes, this is probably the acid test for these changes :)

**Comment by astares** [comment]
Any Enlumineur experts around  ... ;)

**Comment by guillep** [comment]
Now there are only the conflicts to fix

**Comment by astares** [comment]
We close this one. And double check once we have integrated the other Enlumnieur change from @PalumboN

**Pull request closed without merging**
