### PR TITLE
Small cleanups - class side initialize and other

### LINKED ISSUE #10017: Small cleanups - class side initialize and other in Monticello
Similar to #9882 we want to clean Monticello (classes starting with MC)

### PR DESCRIPTION
**Pull request by astares**
Fix #10017

### CODE REVIEW

**Comment by Ducasse** [comment]
I was about to press the button after reading the changes but the tests that are failing are related to MC and I do not get why protocol renamings break so many tests.

**Comment by Ducasse** [comment]
```
testPush – Unix64.Gofer.Tests.Tests.GoferOperationTest
<1s
testEmbeddingCompressedSourceCode – Unix64.Kernel.Tests.Methods.CompiledMethodTrailerTest
<1s
testAddAndLoad – Unix64.Monticello.Tests.Repository.MCDirectoryRepositoryTest
<1s
testMcdSerialization – Unix64.Monticello.Tests.IO.MCSerializationTest
<1s
testMczSerialization – Unix64.Monticello.Tests.IO.MCSerializationTest
<1s
testWriteSnapshot – Unix64.MonticelloTonel.Tests.TonelWriterTest
<1s
testWriteSnapshotWithoutOrganization – Unix64.MonticelloTonel.Tests.TonelWriterTest
<1s
testInstallFromFile – Unix64.System.Installers.Tests.MCMczInstallerTest
<1s
testInstallFromStream – Unix64.System.Installers.Tests.MCMczInstallerTest
<1s
```

**Comment by MarcusDenker** [comment]
The failing tests seem to not be caused bu this PR but another already merged one, as we see those with the other CI runs, too

**Comment by astares** [comment]
@Ducasse / @MarcusDenker 

OK - then lets close this. I can redo it based again on latest version (but including the merge that happend inbetween)

**Comment by MarcusDenker** [comment]
I opend an issue for the failing tests: https://github.com/pharo-project/pharo/issues/10021

**Pull request closed without merging**
