### PR TITLE
[improvement] fix 5603 overlayCompilerbug

### PR DESCRIPTION
**Pull request by hogoww**
I have no idea where I put my feet on this one, but this seems to fix the overlay compiler.
It does not break additional tests on OpalCompiler.
We'll see what the ci says

### CODE REVIEW

**Comment by hogoww** [comment]
It does not seems to work.
This is still weird because what I changed is a message send to super, which DIRECTLY hits a subclassresponsibility, even if the problem is not coming from that part of the code

**Comment by MarcusDenker** [comment]
Here is a test that shows that we need to 

^ outerScope lookupVar: name

at the end, not return nil.

testArrayEvaluateWithBindingsReadGlobal
	| result |
	result := Smalltalk compiler
		bindings: {(#a -> 3)};
		evaluate: 'OrderedCollection'.
	self assert: result equals: OrderedCollection

**Comment by hogoww** [comment]
Thanks To @MarcusDenker which found the fix !

**Review by MarcusDenker — APPROVED** [review]
ok!

**Pull request merged**
