### PR TITLE
fix issue #12434, pair programming with Valentin

### PR DESCRIPTION
**Pull request by akevalion**
Note that we change the keyDown with keyUp to avoid the keyDown repetition

Close this issue :-)
https://github.com/pharo-project/pharo/issues/12434

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Failing tests that are not caused by this PR:

- [CI] failing test: testClassSideInitializeMethodNeedsToBeInClassInitializationProtocol #12440
- [CI] testExternalMorphicCoreDependencies is failing #12441

**Review by guillep — APPROVED** [review]
ok!

**Comment by jecisc** [comment]
I have the impression that since this PR was merged, we have a side effect in the image. 

For example in a playground, if I do an inspect it, I see a research field appearing with an "i" in it

**Comment by akevalion** [comment]
Hello I notice it too, it happens for FastTables in general

@MarcusDenker what should we do?
- a revert and reopen the issue.
- create a new issue and send a new pull request

**Comment by MarcusDenker** [comment]
I added an issue.

Whatever is faster... as this is a bit annoying, maybe reverting and then improving the PR to not have the problem is better?

**Comment by akevalion** [comment]
@MarcusDenker I will to the revert

**Comment by akevalion** [comment]
I have created:
- https://github.com/pharo-project/pharo/pull/12505

**Pull request merged**
