### PR TITLE
20390 - Enforce Proper method categorization - Part 1 - SUnit

### PR DESCRIPTION
**Pull request by astares**
- properly categorize all #setUp methods in test case in category running 
- properly categorize all #tearDown methods in test case in category running

Add ProperMethodCategorizationTest as release test to ensure the methods
#setUp, #tearDown and #runCase from SUnit are properly categorized also in the future.

We should raise the bar on quality and consistency!

### CODE REVIEW

**Comment by astares** [comment]
https://pharo.fogbugz.com/f/cases/20390/Enforce-Proper-method-categorization-Part-1-SUnit

**Comment by jecisc** [comment]
Maybe instead of a test it should be a rule? Then the users would see the problem while code in the code browser.

**Comment by astares** [comment]
There already is a rule !!!  But nobody respects that. 

So the idea is to cleanup the Pharo 7 image now (which is the general Pharo idea) and making sure we keep up with this higher standard by having tests. 
Otherwise we have to do the work over and over again and will never end up in a cleaned image.

**Comment by jecisc** [comment]
It would maybe be good to select some rules and to make the build fail if those rules fail.

**Comment by jecisc** [comment]
But I totally agree that we need to increase the criterias to includes contributions.

**Pull request merged**
