### PR TITLE
2319-Split-FastTable-in-multiple-packages

### LINKED ISSUE #2319: Split FastTable in multiple packages
I would split Morphic-Widgets-FastTable into multiple packages:
- Morphic-Widgets-FastTable
- Morphic-Widgets-FastTable-Trees
- Morphic-Widgets-FastTable-Examples
- Morphic-Widgets-FastTable-Compatibility (For the Pluggable adaptor)

### PR DESCRIPTION
**Pull request by jecisc**
Split Morphic-Widgets-FastTable into multiple packages:

    Morphic-Widgets-FastTable
    Morphic-Widgets-FastTable-Trees
    Morphic-Widgets-FastTable-Examples
    Morphic-Widgets-FastTable-Compatibility (For the Pluggable adaptor)

Fixes #2319

### CODE REVIEW

**Comment by Ducasse** [comment]
I relaunched the build

**Comment by Ducasse** [comment]
Cyril there is a conflict. No idea why.

**Comment by jecisc** [comment]
I'll correct the conflict later because to integrate FastTable changes it will be easier to do it before the split. So I'll do multiple PR before integrating this one.

**Comment by Ducasse** [comment]
Close in agreement with jesic

**Pull request closed without merging**
