### PR TITLE
Spec based find & replace dialog

### PR DESCRIPTION
**Pull request by pavel-krivanek**
Replaces the current completely broken Rubric find & replace dialog with a new one that uses Spec.

It does not introduce dependency between Spec and Rubric because it is an optional package that uses (new) service registration.

### CODE REVIEW

**Comment by Ducasse** [comment]
{ #category : #accessing }
 SpRubFindReplaceService class >> newFor: anObject [

 	^ super new
 ]

=>

{ #category : #accessing }
 SpRubFindReplaceService class >> newFor: anObject [

 	^ self new
 ]

Idem here
DummyFindReplaceService class >> newFor: anObject [

 	^ super new
 ]

**Comment by Ducasse** [comment]
I see you introduce a registration in rub and then use it!

**Comment by pavel-krivanek** [comment]
Pharo_15j1cx2JhE

**Comment by pavel-krivanek** [comment]
Pharo_UrncAMNGXF

**Pull request merged**
