### PR TITLE
Categorize uncategorized methods in classes starting with M

### LINKED ISSUE #8833: Categorize uncategorized methods in classes starting with M
```Smalltalk
Smalltalk globals allBehaviors select: [ :class | class  protocols includes: #'as yet unclassified'. ]
```
- MCFileRepositoryInspector
- MCFileTreeStSnapshotWriter
- MCMergeBrowser
- MCMock
- MCMockASubclass
- MCMockClassA
- MCMockClassD
- MCMockClassE
- MCRepositoryInspector
- MCTestCase
- MFClassA
- MFClassB
- MagnitudeTest
- ManifestSlotCore
- MergeJoinSection
- MetacelloMCBaselineProject
- MetacelloMCProject
- MicArgumentsSplitter
- MicRootBlock
- MockSourceEditor
- ModelDependentDialogWindow
- MorphTest
- MorphTreeMorph
- MorphTreeResizerMorph
- MorphicFastTableAdapter
- MulticolumnLazyListMorph

### PR DESCRIPTION
**Pull request by astares**
Fix #8833

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Failing tests:

TonelWriterTest>>testWriteSnapshotWithoutOrganization

TonelWriterTest>>testWriteSnapshot

MCSnapshotBrowserTest>>testProtocolIsCleared

MCStWriterTest>>testClassMethodDefinition

**Comment by MarcusDenker** [comment]
two tests are still failing:

TonelWriterTest>>testWriteSnapshot
TonelWriterTest>>testWriteSnapshotWithoutOrganization

**Comment by astares** [comment]
I fixed TonelWriterTest **now a second time** just to find out afterwards that it is not serialized as it is not a standard project (and externally managed) while the changed MC prefixed classes that have been changed are part of the standard source set.

My changes are lost now a second time. Trying to rescue/serialize them with a change sorter is not possible for two reasons:
  - there is no change sorter tool available anymore in the Pharo 9 menus
  - classes like SpChangeSorterPresenter and SpDualChangeSorterPresenter are broken when one wants to use the #5838 

This is frustrating and a good way to kill the few remaining contributors who are knowedgable enough (and creative enough) to still find their way through a constantly changing system where nothing can be considered really stable.

**So I can not deliver the fix for this PR as TonelWriterTest can not be made part of the PR, sorry.**

The whole source concept is disrupted and utterly broken:
 - either we have a real small bootstrap base image with dependent building blocks (managed as external projects) to 
   build the general image
 - or we have all source managed together for the base system

The way we mix both models at the moment (while asking for green tests at the same time) is just bogus...

**Comment by astares** [comment]
Still green after fixing it a third time - but this time being able to file it out as a full class:

[TonelWriterTest.st.txt](https://github.com/pharo-project/pharo/files/6185294/TonelWriterTest.st.txt)


So long ... and thanks for all the fish!

**Comment by Ducasse** [comment]
Hi torsten
I understand your frustration. You can imagine mine :). Now there are tons of code in Pharo that is brittle, implementing old logic without any tests. This is why we are rewriting the tools. The changesorter is old and its logic is not the best we can do because it implemented a kind of merging logic we do not need anymore. 
I did not follow exactly: I do not understand why you code is lost may be the fix should be pushed to the tonel project. 
I saw that there is one test of tonel that is still failing.

**Comment by Ducasse** [comment]
@estebanlm esteban how should we manage this PR?

**Comment by astares** [comment]
@Ducasse  The PR is to categorize methods in some classes starting with the letter "M" so we decrease the number of uncategorized methods in the image (and satisfy the release test that Marcus has provided). 

During such a simple change the TonelWriterTest starts to fail. So I fixed/changed it to be green in the image (to get a regular *complete* PR that is accepted with green tests by CI). All looked fine within the image ...

But when I commited the changes I did not see that TonelWriterTest changes were not written and went to nirvana when I saved my stuff to "pharo". It was not saved as Tonel is managed externally in an own project. One will not notice that it is not saved as the Tonel project is not visible inside of Iceberg. 

I did this two time (so I lost two times my changes) and then I wanted to at least rescue the change to TonelWriterTest - but also this failed as filing out / change sorter is broken too.

So you can not get the PR to fix what need to be done and have green tests.

The only cumbersome way I see:
 - deactivate TonelWriterTest in Tonel 
 - make a new release of Tonel
 - include the new release of Tonel
 - change the classes starting with "M" to have no uncategorized methods and integrate
 - fix and reactivate TonelWriterTest in Tonel again
 - and make this available as another Tonel release
 - ...

**Comment by MarcusDenker** [comment]
there are now lots of conflicts, I think it might be better to close it and redo the PR?

**Comment by astares** [comment]
Yes - they have been fixed already. I will close

**Pull request closed without merging**
