### PR TITLE
20570-Move-LayoutFrame-out-of-Morphic-Base-and-put-it-close-to-Margin

### PR DESCRIPTION
**Pull request by samakhov**
Fix issue 20570.
- Move LayoutFrame, LayoutProperties, and sub from Morphic-Base to Kernel-BasicObjects

### CODE REVIEW

**Comment by jecisc** [comment]
Could you explain why LayoutFrame should be in Kernel?

I don't see Kernel depending on this and I had the impression the way to go was to reduce the size of the Kernel.

**Comment by estebanlm** [comment]
yes, this is not clear for me either. 
what's the rational of this issue? @Ducasse, do you have an idea?

**Comment by Ducasse** [comment]
LayoutFrame is not bound to a particular UI implementation this is the same for rectangle and margin.

**Comment by astares** [comment]
We can agree that LayoutFrame is UI independent, yes. But it is some kind of UI or graphic related utility nonetheless.

So why should the Kernel (which we like to have as minimal as possible) care on LayoutFrames? 
For what purpose?

Maybe we should rather think about moving Rectangle and Margin out of the kernel into a "graphic support layer" above kernel then - no?

**Comment by Ducasse** [comment]
If you want. I just think that layoutFrame should be close to rectangle and margin. 
Now I do not know how to change that in presence of bootstrap. It is a good exercise but I do not know concretely how to do it.

**Comment by estebanlm** [comment]
as it is now this is not good solution. 
let's find a better one :)

**Pull request closed without merging**
