### PR TITLE
20941-deprecate-theMetaclass-and-the-theNonMeta

### PR DESCRIPTION
**Pull request by Ducasse**
https://pharo.fogbugz.com/f/cases/20941/deprecate-theMetaclass

I'm issuing a first PR:
- added protocol deprecated (but did not deprecated methods)
- inverse the logic ie theMetaclass and theNonMetaclass are calling now instanceSide/classSide. 
- Added some simple tests. 
- Added systematically method comments!!
- fixed all theMetaclass in RB, Class, Ring, 
- Avoid to change traits because waiting for Pablo
- fixed some missing globals. 

- nextPR should handle theNonMetaclass part

### CODE REVIEW

**Comment by dionisiydk** [comment]
On github it looks fine. But I am not able look at it from Pharo. Iceberg gives me error

**Comment by Ducasse** [comment]
Thanks denis
This is strange because I did not deprecate anything. 
Now may be there are some case where a subclassResponsibility may be executed prior to a change. So may be I will have to cut it in part.

**Comment by Ducasse** [comment]
Denis I could review the code in a new image without problem

**Comment by astares** [comment]
Why no deprecation?

The correct way to do it would be to call #deprecated: in the method one wants to declare as 
obsolete:

  isMeta [
	self deprecated: 'Please use #isClassSide'.
 	^self isClassSide	 	
 ]

Also they should be moved as extension methods into existing package "Deprecated70"
by giving them a "*Deprecated70" method category.
Because this will also show that these methods are deprecated and when we start the
Pharo 8 release iteration we can easily throw them out by deleting/unloading 
Deprecated70 package.

**Comment by Ducasse** [comment]
Because we go wisely. 
First make sure that this can be loaded and everything works well, then we will see.

**Comment by jecisc** [comment]
Even better than `deprecated:`

```Smalltalk
isMeta
	self 
		deprecated: 'Use #isClassSide instead'
		on: 	'16 Febuary 2018' 
		in: 'Pharo-7'
		transformWith: '`@receiver isMeta-> '`@receiver isClassSide.
	^ self isClassSide
```

**Comment by Ducasse** [comment]
Ok now we should be in good shape. 
Thanks Pablo.

**Pull request merged**
