### PR TITLE
22501-Some-packages-are-not-loaded-in-the-image

### PR DESCRIPTION
**Pull request by VincentBlondeau**
https://pharo.fogbugz.com/f/cases/22501/Some-packages-are-not-loaded-in-the-image

### CODE REVIEW

**Comment by pavel-krivanek** [comment]
it looks good but it needs an update. The `NoUnusedTemporaryVariablesLeftTest` class was added to the release-tests and it should be moved to the new package

**Comment by jecisc** [comment]
There is still some failures. 

Maybe we should cut this PR in multiple PR to better locate the problematic parts.

**Comment by jecisc** [comment]
I re-do the changes + added some others in:
- https://github.com/pharo-project/pharo/pull/2178
- https://github.com/pharo-project/pharo/pull/2183
- https://github.com/pharo-project/pharo/pull/2182
- https://github.com/pharo-project/pharo/pull/2181
- https://github.com/pharo-project/pharo/pull/2186

**Comment by guillep** [comment]
I think the related tests are related

**Pull request closed without merging**
