### PR TITLE
3847-TestRunner-code-coverage-does-not-need-to-use-method-reference-wrapping

### LINKED ISSUE #3847: TestRunner code coverage does not need to use method reference wrapping
TestRunner code coverage does not need to use method reference wrapping, it can use use the methods directly

### PR DESCRIPTION
**Pull request by MarcusDenker**
remove methodReference usage... (yes, these methods can be simplified further...(

fixes #3847

### CODE REVIEW

**Comment by jecisc** [comment]
I tried to run some coverage in my image but when I do Pharo does not answer anymore. :(

**Comment by MarcusDenker** [comment]
is this change the reason?

**Comment by jecisc** [comment]
No, it happens also without this change. But because of that I cannot test using the TestCoverage :(

Either Pharo does not answer as soon as I click on "Run Coverage" or when I select a package to cover.

Are you able to launch a test coverage selecting AST-Core-* tags for example?

**Comment by Ducasse** [comment]
I would remove coverage from the SUnit.

**Pull request merged**
