### PR TITLE
22400-Delays-are-not-working-properly

### PR DESCRIPTION
**Pull request by pavel-krivanek**
Add setting of the idle time

https://pharo.fogbugz.com/f/cases/22400/Delays-are-not-working-properly

### CODE REVIEW

**Comment by bencoman** [comment]
Please hold off integrating this for a few days.  My recent cleanup/refactoring of the delay-scheduler left me with an insight into this, to introduce DelayIdleTicker (https://pharo.fogbugz.com/f/cases/22549)

**Review by juliendelplanque — APPROVED** [review]

**Comment by bencoman** [comment]
My DelayIdleTicker was deemed too invasive for the late stage of Pharo 7,  so go with this simpler alternative.  
But @zecke @ronsaldo what should the default be? The original 1000, or the more recent 50000?

**Comment by zecke** [comment]
> On 20. Oct 2018, at 14:36, Ben Coman <notifications@github.com> wrote:
> 
> My DelayIdleTicker was deemed too invasive for the late stage of Pharo 7, so go with this simpler alternative.
> But @zecke @ronsaldo what should the default be? The original 1000, or the more recent 50000?

Sleep as long as possible. it saves battery on mobile and money on cloud installations.

holger

**Comment by ronsaldo** [comment]
Hi Ben, for me having the longer default delay it is not a problem for now, because for my use case I can just patch the default idle time when loading my projects. However, on the long term I would really like to have sub-millisecond delays, which is needed for some 3D applications such as VR.

**Review by bencoman — APPROVED** [review]

**Review by guillep — APPROVED** [review]
Tested, it works. It requires restarting the image

**Pull request merged**
