### PR TITLE
Composing and reusing add method refactoring/transformation

### PR DESCRIPTION
**Pull request by balsa-sarenac**
We have `RBAddMethodRefactoring` that compiles a method in the class. It has precondition that class in which we’re compiling the method doesn’t already have method’s selector. The compilation logic is duplicated across multiple refactorings. I wanted to reuse existing refactoring instead of duplicating code.

Example: `RBCreateAccessorsForVariableRefactoring` and `RBCreateLazyAccessorsForVariableRefactoring` create and compile accessors for a class. They override existing methods.

`RBAddMethodRefactoring` fails if a selector already exists so I couldn't reuse it for the above mentioned classes. For that purpose I've defined `RBAddMethodTransformRefactoring`. This refactoring checks applicability preconditions and perform actual transformation.
`RBAddMethodRefactoring` is then composed of `RBAddMethodTransformRefactoring`. `RBAddMethodRefactoring` delegates transformation to the `RBAddMethodTransformRefactoring`. `RBAddMethodRefactoring` preconditions check preconditions of `RBAddMethodTransformRefactoring`.

Finally, I'd like to rename `RBAddMethodTransformRefactoring` to just `RBAddMethodTransformation`. Because this class doesn't preserve behaviour. Current name is only temporary until I the new name is settled. If you have a proposal of new name, that is not transformation, please do comment. Until the name is settled and all is cleaned, I open this PR as a draft.

### CODE REVIEW

**Comment by Ducasse** [comment]
Sound good. Did you copy the tests of AddMethodRefactoring to AddMethodTransformRefactoring? This way we can check that eveything works and after we remove AddMethodRefactoring and rename AddMethodTransformRefactoring into AddMethodRefactoring. I like the idea that the AddMethodTransformation can check or not its precondition because may be when scripting a transformation I do want to override an existing method. So this is a super good case :)

**Review by Ducasse — APPROVED** [review]

**Comment by Ducasse** [comment]
@balsa-sarenac you have some related tests failing

```
unix-64 / Tests-unix-64 / testAddMethod – Unix64.Refactoring2.Transformations.Tests.SingleParametrized.RBAddMethodTransformRefactoringTest
10s
Error

receiver of "nil" is nil
Stacktrace

MessageNotUnderstood
receiver of "nil" is nil
UndefinedObject(Object)>>doesNotUnderstand: nil
RBAddMethodTransformRefactoringTest(RBWithDifferentConstructorsParametrizedTest)>>createRefactoringWithArguments:
RBAddMethodTransformRefactoringTest>>testAddMethod
RBAddMethodTransformRefactoringTest(TestCase)>>performTest
```

**Comment by Ducasse** [comment]
```
unix-64 / Tests-unix-64 / testAddMethod – Unix64.Refactoring2.Transformations.Tests.SingleParametrized.RBAddMethodTransformRefactoringTest
10s
unix-64 / Tests-unix-64 / testFailureBadMethod – Unix64.Refactoring2.Transformations.Tests.SingleParametrized.RBAddMethodTransformRefactoringTest
10s
unix-64 / Tests-unix-64 / testModelAddMethod – Unix64.Refactoring2.Transformations.Tests.SingleParametrized.RBAddMethodTransformRefactoringTest
10s
osx-64 / Tests-osx-64 / testAddMethod – MacOSX64.Refactoring2.Transformations.Tests.SingleParametrized.RBAddMethodTransformRefactoringTest
7s
osx-64 / Tests-osx-64 / testFailureBadMethod – MacOSX64.Refactoring2.Transformations.Tests.SingleParametrized.RBAddMethodTransformRefactoringTest
7s
osx-64 / Tests-osx-64 / testModelAddMethod – MacOSX64.Refactoring2.Transformations.Tests.SingleParametrized.RBAddMethodTransformRefactoringTest
7s
```

**Comment by balsa-sarenac** [comment]
It's weird I cannot reproduce failing tests locally. I'll trigger a re-run and if it still fails I'll investigate further.

**Comment by Ducasse** [comment]
This is strange because they still break :(

**Comment by Ducasse** [comment]
Strange this one is not a failure 
unix-64 / Tests-unix-64 / testModelAddMethod – Unix64.Refactoring2.Transformations.Tests.SingleParametrized.RBAddMethodTransformRefactoringTest

**Pull request merged**
