### PR TITLE
6705-Display-tearDown-tab-for-test-classes-in-Calypso-in-the-same-way-as-we-display-the-setUp-tab

### PR DESCRIPTION
**Pull request by olekscode**
Fixing  #6705. Added a comment describing the hack

### CODE REVIEW

**Comment by MarcusDenker** [comment]
one slave timeout, two green

**Comment by dionisiydk** [comment]
How it looks with setUp and tearDown together? One of the reason why I did not add it is a limitation of the default size of the browser. Considering that tearDown is less interesting than setUp for understanding the test I kept only this tab.

**Comment by MarcusDenker** [comment]
This has now a merge conflict

**Comment by MarcusDenker** [comment]
as there was another PR that was touching the same code, the best is to re-submit a new PR

**Pull request closed without merging**
