### PR TITLE
feature/add-libraryfinder

### PR DESCRIPTION
**Pull request by estebanlm**
add some helpers to find libraries according to platforms. This should easy the lookup of libraries specially on linux, but also others.

### CODE REVIEW

**Comment by Ducasse** [comment]
A question why the basePaths are only customisable via subclasses and overriding?
I was thinking that clients could also specify their base paths (so turning the basePaths in an instance variable that can also be set).

**Comment by estebanlm** [comment]
Because I didn't think it has sense: This is a tool to find libraries in the standard directories of a platform (specially annoying in linux, since different distributions put libraries sin different places), not anywhere.
I do not understand who would want to use them outside this purpose?

**Comment by Ducasse** [comment]
Oki

**Comment by Ducasse** [comment]
BTW why do you return all the times newly created ordered collections?
If you call 10 times basePaths you will create 10 collections while one is enough.

**Comment by Ducasse** [comment]
Esteban did you see my last remark?

**Comment by estebanlm** [comment]
yes I saw it. 
Just no time :)
Originally I thought this helpers as a "one time shot", hence caching the arrays wouldn't have much sense... but I can add them, in case someone wants to keep the finder.

**Comment by Ducasse** [comment]
Ok my sole point is that if the method is only invoked once we do not care.
Now if it is regularly invoked then it can be worth.

**Pull request merged**
