### PR TITLE
Fix calypso browsing of Ring models

### PR DESCRIPTION
**Pull request by jecisc**
It is possible to browse a ring model in Calypso and this is used to browse external code for example.

I would like to replace the MCSnapshotBrowser by this but thi feature is currently broken. Here I'm proposing fixes to not rely on image entities in Calypso code.  In the next version of Calypso it would be nice to have tests for this. 

Once this PR is integrated I will be able to remove the use of the Snapshot browser (written in Morphic) from Iceberg and then from Pharo

### CODE REVIEW

**Comment by Ducasse** [comment]
It looks like the build is broken

```
MetacelloNotification: Project: WelcomeBrowser
[31mSubscriptOutOfBounds: 1 in #[]
[0mByteArray(Object)>>errorSubscriptBounds:
ByteArray(Object)>>at:
ByteArray>>byteAt:
ZipReadStream(InflateStream)>>nextByte
ZipReadStream(InflateStream)>>nextBits:
ZipReadStream(InflateStream)>>getNextBlock
ZipReadStream(InflateStream)>>pastEndRead
ZipReadStream(InflateStream)>>next
ZipReadStream(InflateStream)>>next:into:startingAt:
[[ readDataRemaining > 0 ] whileTrue: [
		| chunkSize |
		chunkSize := 32768 min: readDataRemaining.
		buffer := decoder next: chunkSize into: buffer startingAt: 1.
		aStream next: chunkSize putAll: buffer startingAt: 1.
		readDataRemaining := readDataRemaining - chunkSize.
	]] in ZipFileMember>>uncompressDataTo: in Block: [[ readDataRemaining > 0 ] whileTrue: [...
FullBlockClosure(BlockClosure)>>on:do:
ZipFileMember>>uncompressDataTo:
ZipFileMember(ZipArchiveMember)>>writeDataTo:
ZipFileMember(ZipArchiveMember)>>extractTo:
[ :str | self extractTo: str 
```

**Comment by astares** [comment]
@Ducasse / @jecisc / @MarcusDenker 

Yes - build seems broken. Maybe I'm to blame:

Because 4 days ago my PR for WelcomeBrowser was merged:
https://github.com/pharo-spec/NewTools-WelcomeBrowser/commit/8046cf7fc6da91544554f4374fadf38ce192c824

which typically should be in with the next merge in Pharo standard project. 

If I download latest P13 image using Launcher I get 
Pharo-13.0.0+SNAPSHOT.build.106.sha.53c363d00558709c61cb24c916bb1473c4bcea34 (64 Bit)
and the change is not inside. Basically it loads another image from the git repo of Welcome Browser to preview the new dark blue theme.

This reflects commit in Pharo Repo from 5 days ago
https://github.com/pharo-project/pharo/commit/53c363d00558709c61cb24c916bb1473c4bcea34

but source code is already at https://github.com/pharo-project/pharo/commit/34cad1347d14c5c029a3796d2e59c545ccae7067

**Comment by astares** [comment]
My PR in the WelcomeBrowser repo included a change in **"BaselineOfWelcomeBrowser >> repositoryLocation"**
(see https://github.com/pharo-spec/NewTools-WelcomeBrowser/commit/8046cf7fc6da91544554f4374fadf38ce192c824)
which was not working - so I fixed it.

Maybe this one has trouble when run on CI

**Comment by Ducasse** [comment]
Broken tests are unrelated 

```
[osx-64 / Tests-osx-64 / MacOSX64.UnifiedFFI.Tests.FFIAutoReleaseOptionCalloutTest.testExternalStructure](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16802/2/testReport/junit/MacOSX64.UnifiedFFI.Tests/FFIAutoReleaseOptionCalloutTest/osx_64___Tests_osx_64___testExternalStructure/)
[osx-64 / Tests-osx-64 / MacOSX64.UnifiedFFI.Tests.FFIAutoReleaseOptionCalloutTest.testVoidPointer](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16802/2/testReport/junit/MacOSX64.UnifiedFFI.Tests/FFIAutoReleaseOptionCalloutTest/osx_64___Tests_osx_64___testVoidPointer/)
```

**Pull request merged**
