### PR TITLE
8732 class abstract tool is not really abstract

### PR DESCRIPTION
**Pull request by astares**

### CODE REVIEW

**Comment by MarcusDenker** [comment]
MetacelloNotification: Loaded -> NewTools-MethodBrowsers-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-8733/64/src --- cache
MetacelloNotification: Loading -> NewTools-ChangeSorter-tonel.1 --- tonel:///builds/workspace/uest_and_branch_Pipeline_PR-8733/64/src --- cache
Error: This package depends on the following classes:
  AbstractTool
You must resolve these dependencies before you will be able to load these definitions:

**Comment by astares** [comment]
@MarcusDenker But AbstractTool is provided (now as a subclass of the renamed class) as you see on the changed files

My guess is that CI only catches the first commit, not the full PR (with the second commit) and thats why it was failing

Can you restart it?

**Comment by Ducasse** [comment]
Let us try to rebuild it. 
This is strange.

**Review by guillep — APPROVED** [review]
Good!

**Comment by guillep** [comment]
I'm sorry, I'll revert this. I was in trance, I did not see there were dependency issues.

Of course, the deprecated package is loaded at the very end, to make sure there are no users of it in the build.

Looking at the logs, I'd say there are users of it in NewTools-ChangeSorter ?
@astares would you mind redoing a new PR? (I'd do it otherwise to make up from my mistake, but given that there is still work to do in this one...)

**Pull request merged**
