### PR TITLE
upgrading Pharo 9 with Roassal 0.9.6

### LINKED ISSUE #8407: Update Pharo 9 with Roassal 0.9.6
We have produced a new release of Pharo 0.9.6, with essentially some improvement related to documentation and cleaning. It should be easy to review this change

### LINKED ISSUE #8424: Roassal: classes with unused ivas
**Describe the problem**
Roassal has some classes with ivars that are not referenced:

RSAbstractContext
RSAbstractContainerBuilder
RSAbstractFlowLayout
RSAbstractLineLayout

### PR DESCRIPTION
**Pull request by bergel**
Simple and very small change in the baseline

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Some release tests are failing:

	
testLocalMethodsOfTheClassShouldNotBeRepeatedInItsTraits
If a class has a method in its trait composition, the method should not be implemented in the class. Violations:  - RSLineBuilder


testAndMakeSureSuperSetupIsCalledAsFirstMessageInSetupMethodsOfTestCases
an OrderedCollection(RSElasticBoxTest>>#setUp) should have been empty

testNoUnusedTemporaryVariablesLeft
the following methods have unused temporary variables and should be cleaned: an OrderedCollection(RSMarker>>#setPositionTo:vector:do:)
	

In addition, it would be good to fix the unused ivars, see https://github.com/pharo-project/pharo/issues/8424

**Comment by bergel** [comment]
Thanks Marcus, we will have a close look at this.

Cheers,
Alexandre
-- 
_,.;:~^~:;._,.;:~^~:;._,.;:~^~:;._,.;:~^~:;._,.;:
Alexandre Bergel  http://www.bergel.eu
^~:;._,.;:~^~:;._,.;:~^~:;._,.;:~^~:;._,.;:~^~:;.

**Comment by MarcusDenker** [comment]
any news? these do not look hard to fix

**Comment by bergel** [comment]
We will fix this today. We have a new PR

Cheers,
Alexandre
-- 
_,.;:~^~:;._,.;:~^~:;._,.;:~^~:;._,.;:~^~:;._,.;:
Alexandre Bergel  http://www.bergel.eu
^~:;._,.;:~^~:;._,.;:~^~:;._,.;:~^~:;._,.;:~^~:;.

**Comment by bergel** [comment]
Hi @MarcusDenker 
We have just modified the baseline. It should be good for inclusion if tests are okay with it :-)

Thanks you very much for reviewing.

**Comment by MarcusDenker** [comment]
all the one that failed befoe are still failing and one more:

Error
Classes that use traits with explicit requirement methods should either implement the method or inherit it. Violations:  - RSObjectWithProperty
Stacktrace
TestFailure
Classes that use traits with explicit requirement methods should either implement the method or inherit it.
Violations: 
- RSObjectWithProperty
ReleaseTest(TestAsserter)>>assert:description:resumable:
ReleaseTest(TestAsserter)>>assert:description:
ReleaseTest>>assertValidLintRule:withExceptions:
ReleaseTest>>assertValidLintRule:
ReleaseTest>>testExplicitRequirementMethodsShouldBeImplementedInTheirUsers

**Comment by akevalion** [comment]
I have fixed this in the last version of roassal, we will create a new release with this change

**Comment by MarcusDenker** [comment]
any news?

**Comment by bergel** [comment]
Hi! We released a minor of Roassal that fixes the reported issues. Thanks! We think it should be ready to be included.

**Comment by MarcusDenker** [comment]
The CI shows still these failures:

unix-64 / Tests-unix-64 / testNoUnusedTemporaryVariablesLeft – Unix64.ReleaseTests.CleanCode.NoUnusedVariablesLeftTest
unix-64 / Tests-unix-64 / testSetUpMethodInSUnitTestsNeedsToBeInRunningProtocol – Unix64.ReleaseTests.Categorization.ProperMethodCategorizationTest
unix-64 / Tests-unix-64 / testAndMakeSureSuperSetupIsCalledAsFirstMessageInSetupMethodsOfTestCases – Unix64.ReleaseTests.Tests.ProperlyImplementedSUnitClassesTest
unix-64 / Tests-unix-64 / testLocalMethodsOfTheClassShouldNotBeRepeatedInItsTraits – Unix64.ReleaseTests.Release.ReleaseTest

**Comment by MarcusDenker** [comment]
are we sure that the idea with the letter works? to me it looks like it loads the version without the letter

**Comment by MarcusDenker** [comment]
It seems to load "c":

MetacelloNotification: Loading -> Roassal3-Layouts-tonel.1 --- github://ObjectProfile/Roassal3:v0.9.6c/src --- cache


But this means that the original failing tests where never fixed, which is strange, because these are the tests that I listed originally as problematic.

**Comment by bergel** [comment]
Thanks Marcus for being so patient with us :-)
We have produced a new release of Roassal, which fixes the problem reported by the tests. Let's see what the CI will say now...

**Comment by bergel** [comment]
We got an error: 
image

But I am not sure whether there is something we could do....

**Comment by Ducasse** [comment]
I should be ok this is a protoObjectTest I guess not something you broke.

**Comment by MarcusDenker** [comment]
Looks good, the test that times out is unrelated

**Comment by bergel** [comment]
Thanks Marcus! 
This is great!

Alexandre
-- 
_,.;:~^~:;._,.;:~^~:;._,.;:~^~:;._,.;:~^~:;._,.;:
Alexandre Bergel  http://www.bergel.eu
^~:;._,.;:~^~:;._,.;:~^~:;._,.;:~^~:;._,.;:~^~:;.

**Pull request merged**
