### PR TITLE
Unification of simple form of "isAbstract" method.

### PR DESCRIPTION
**Pull request by kamk**
Among three most common implementations:
1. self = SomeClass
2. self == SomeClass
3. self name = #SomeClass

second one is the most fastest.

See original FogBugz [case #22771](https://pharo.fogbugz.com/f/cases/22771/isAbstract-for-classes-should-be-unified).

### CODE REVIEW

**Comment by Ducasse** [comment]
Thanks for your submission. 
Did you check if class override = because in Object = is defined as ==.
Another point could you issue the PR for P9 because P8 is in beta and we do not integrate changes except for the urgent and important bug fixes.

**Comment by kamk** [comment]
Okay, I will create new PR for Pharo-9.0 branch.
I didn't find any override of = at class side.

**Comment by Ducasse** [comment]
Ok so before doing it it would be nice to really measure be difference between == and = because using = gives another method that we can redefine in case we want to play with spies and other tooling. While we cannot redefine easily ==.

**Comment by kamk** [comment]
I see. Maybe it should be noticed in ProtoObject>>#== comment that this primitive should not be used directly (except in Object's "=" comparison method).

**Comment by Ducasse** [comment]
This is not systematic, sometimes you overrides = and still need to use ==.

**Pull request closed without merging**
