### PR TITLE
[IGNORE]22876-Mixup-during-tho-renaming-of-ReleaseTests

### PR DESCRIPTION
**Pull request by jecisc**
Clean mixup we've got with Release-Tests.

- Remove not up to date Release-Tests
- Rename ReleaseTests to Release-Tests
- Update baseline
- Remove useless code + duplication from ImageCleaner

Fixes https://pharo.fogbugz.com/f/cases/22876/Mixup-during-tho-renaming-of-ReleaseTests

### CODE REVIEW

**Comment by jecisc** [comment]
Failure seems related. Now I do not understand how it is possible since I just did a rename of the package.

**Comment by jecisc** [comment]
Maybe the TestRunner choose the order of the tests by the name of the packages and so they are now executed later and they find dirty states let by tests?

**Comment by jecisc** [comment]
Not for Pharo 7 since it will require more cleanings

**Comment by jecisc** [comment]
First fix: 

- https://github.com/pharo-project/pharo/pull/2199

New opened issue: https://github.com/pharo-project/pharo/issues/2201

**Comment by Ducasse** [comment]
So guys what should we do? Close it?

**Comment by Ducasse** [comment]
So guys what should we do? Close it?

**Pull request closed without merging**
