### PR TITLE
Improve faulty parsing - simplify RBParser error API

### PR DESCRIPTION
**Pull request by privat**
Error handling in the whole compilation infrastructure of Pharo is sometime really weird, possibly for a lot of reasons (going from stacked historical compatibility hacks; to insane design choices that could be used as counter example and case study in a graduated software engineering course).

This PR tries to clean up (a little) the current status. Now that `RBScanner` is a little better (cf #12900) it is the turn of `RBParser`.

It is important to remember that `RBParser` is a simple *utility* component in the whole compilation infrastructure. Its main client is `OpalCompiler` that is a far more complex beast (unfortunately). Therefore:

* Providing the possibility of interactive recovery on syntax error is overengineering (and seems not really used by any client). The simpler used solution is to inform the client of errors and let it run a new parser.
* `RBParser` is not the place to have complex UI/UX/event-programming design. `OpalCompiler` and its clients, like the Rubric code editor, are (maybe) a better place to do fancy things.
* Syntax errors are a normal thing to expect, and most of the time, manipulating faulty AST is what one really want.

The main thing of the PR is to kill `errorBlock` and stop using `ReparseAfterSourceEditing`.

The proposed API is now:

* low level: a class toggle `beFaulty` (and instance variable `isFaulty`) to activate fault-tolerant parsing that produce AST that contains `RBParseErrorNode`, and otherwise signals `SyntaxErrorNotification`.
* helpers methods `parseFaulty*` are preserved (and still do not signal SyntaxError).
* helpers `Xxxx:OnError:` are also preserved, the behavior change a little so that the given block is used to intercept the syntax error signal in a compatible way. The only change is that there is no recovery (no client never cared about that anyway). The value of the block will be the value of the whole `Xxx:OnError:` call.

Note that bugs in the PR might break the usability of images by limiting the possibility to compile new code. So good reviewing is needed :)

### CODE REVIEW

**Comment by MarcusDenker** [comment]
Bootrap failure:

```
    [+] Preparing bootstrapInstance of RGInstanceVariableSlot did not understand #allowsShadowing
RGInstanceVariableSlot(Object)>>doesNotUnderstand: #allowsShadowing
OCASTSemanticAnalyzer>>declareVariableNode:as:

```

**Comment by privat** [comment]
The error is weird.

**Comment by MarcusDenker** [comment]
Re-running is now triggers

- [CI] full image load is broken #12926

**Comment by MarcusDenker** [comment]
Very strange. We get

```
RGInstanceVariableSlot(Object)>>doesNotUnderstand: #allowsShadowing
OCASTSemanticAnalyzer>>declareVariableNode:as:
OCASTSemanticAnalyzer>>declareTemporaryNode:
```

RGInstanceVariableSlot  is Ring2 RGInstanceVariableSlot instance, which models slots in Ring2 and should be API compatible to Slots).

But what is strange as RGInstanceVariableSlot actually does implement #allowsShadowing. 

Maybe the code that the boostrap uses is not up to date compared to the version used by Pharo11?

(I always wanted to push for including everything that the bootstap uses into the main image to make it more visible and easier to keep up to date... but that is another thing for another time)

**Comment by privat** [comment]
Yes, this is really strange. Either the change introduced a subtle bug, or just uncover a potential one (or both).

Anyway, after thinking more about that, I'm not entirely sure about the PR. Maybe keeping an error block but with a failBlock semantic, ie the returned value is not used to recover compilation, but become the value of the high-level public parsing method called (the one that give the whole AST)

**Comment by privat** [comment]
Better attempt proposed #13042 , so close this one

**Pull request closed without merging**
