### PR TITLE
Update BaselineOfPharo.class.st

### PR DESCRIPTION
**Pull request by akevalion**
this pull request addresses this issue:
- https://github.com/pharo-project/pharo/issues/14985

### CODE REVIEW

**Comment by jecisc** [comment]
MetacelloNotification: ...RETRY->BaselineOfRoassal3

MetacelloNotification: ...RETRY->BaselineOfRoassal3

MetacelloNotification: ...FAILED->BaselineOfRoassal3

Could not resolve: BaselineOfRoassal3 [BaselineOfRoassal3] in /builds/workspace/est_and_branch_Pipeline_PR-14986/64/build/bootstrap-cache/pharo-local/package-cache github://pharo-graphics/Roassal:v1.04/src

**Comment by MarcusDenker** [comment]
Found undeclared Variables:  SpRoassal3InspectorPresenter in: AIGraphTestFixtureStructure>>#inspectGraph

**Review by astares — APPROVED** [review]

**Comment by astares** [comment]
image


```Smalltalk
Metacello new
	githubUser: 'pharo-graphics' project: 'Roassal' commitish: 'v1.04' path: 'src';
	baseline: 'Roassal';
	load
```

**Comment by MarcusDenker** [comment]
SpRoassal3InspectorPresenter is missing in the image that the CI created (I checked the build artefact)

**Comment by akevalion** [comment]
Hi, this is the pr https://github.com/pharo-project/pharo/pull/15013

**Comment by MarcusDenker** [comment]
pr https://github.com/pharo-project/pharo/pull/15013 was merged

**Pull request closed without merging**
