### PR TITLE
Patch PNGReadWriter to allow and ignore excess chunks after IEND

### PR DESCRIPTION
**Pull request by svenvc**
Make PNGReadWriter>>#processNextChunk return #IEND instead of self and use that in PNGReadWriter>>#nextImage to stop parsing

### CODE REVIEW

**Review by jecisc — APPROVED** [review]
Maybe a new test can be nice but this PR seems good anyway 👍

**Comment by svenvc** [comment]
> Maybe a new test can be nice but this PR seems good anyway 👍

Normally, I would agree, but this is about parsing a 'bogus' PNG file, a test needs that resource. Either you include it, but that takes more space than we would like, or you refer to a URL, but that is very brittle over time, as various Zinc tests have shown and couples the graphics to the network code.

**Comment by privat** [comment]
Having png assets to tests a png package seams reasonable to me. Another possibility could be to base64 encode images in tests and generate the png on the fly, but this could take up more space in fact.

**Comment by privat** [comment]
there is methods and classes larger than `iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIW2P4v5ThPwAG7wKklwQ/bwAAAABJRU5ErkJggg==` :)

**Comment by svenvc** [comment]
Danke

**Pull request merged**
