### PR TITLE
faulty code: test runtimeSyntaxError

### PR DESCRIPTION
**Pull request by privat**
New Kernel tests that ensure that signaled `RuntimeSyntaxError` exceptions are correct and that their contexts are sane with usable source code information.

Because of all the good work about faulty compilation, there is no special case and faulty code is correctly caught and the source code information is useful. So debugger should behave correctly.
These tests check 3 scenarios: doit (scripts), installed method, and uninstalled method. And they will help to prevent future regressions.

Note: I understand what `debuggerCompleteToSender` does, but I have trouble understanding the English of the symbol string. What "*complete*" means here?

Update: I did another pass and added commits

I removed the AST node from the Exception `RuntimeSyntaxError`. That make the model saner. And the node was superfluous. Because the context (and debuggers and everything) can (now) retrieve the original source code and AST node exactly like other exceptions.
So now, the exception only have a `messageText` like most other exceptions, and is computed early at compile time.
Doing so, I realized the that `RuntimeSyntaxError` what the general runtime exception also for other kind of runtime semantic error. It could be improved because there is "*syntax*" in `RuntimeSyntaxError` (it's hidden in the middle if you don't see it).

### CODE REVIEW

**Comment by privat** [comment]
Note: To confirm, I did also run a GUI session with faulty code, debugger, and reparation attempts. All checks are checked! :tada:

See Sect. "Current debugger GUI on faulty code"in #12883

Capture d’écran du 2023-04-12 20-46-47

**Comment by jecisc** [comment]
CI VM crash. MetacelloNotification BaselineOfDisplay postload:package #13419 
 
 :/

**Comment by guillep** [comment]
Found the cause. That method calls

```
supportsDisplayDepth: pixelDepth
	"Return true if this pixel depth is supported on the current host platform.
	Primitive. Optional."
	<primitive: 91>
	^#(1 2 4 8 16 32) includes: pixelDepth
```

But primitive 91 (which was unused) was redefined in the latest VM:

```
	"Perm Space primitives"
		(90 primitiveMoveToPermSpace)
		(91 primitiveMoveToPermSpaceInBulk)
		(92 primitiveIsInPermSpace)
```

**Comment by guillep** [comment]
One solution is to remove the <primitive: 91> from the offending method in P>=11

**Review by jecisc — APPROVED** [review]
I also don't like the name debuggerCompleteToSender.

The next step you talked about seems good to me from what you are saying.

**Comment by MarcusDenker** [comment]
yes, "debuggerCompleteToSender" is not good. And there was the idea that one negative aspect of pragmas is that they have no place to put documentation... there were Pragma implementations in other Smalltalks that required to create a subclass of Pragma for each pragma symbol used... it could be interesting to think how to add something like that (but maybe optional)

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
