### PR TITLE
20151-new-halt-messages

### PR DESCRIPTION
**Pull request by MarcusDenker**
new halt messages
	https://pharo.fogbugz.com/f/cases/20151/new-halt-messages

### CODE REVIEW

**Review by dionisiydk — APPROVED** [review]
Good

**Comment by Ducasse** [comment]
Super cool, now could we have better comments than "This is the typical message to use for inserting breakpoints during 
 +	debugging."

We should say insideTest will not be stopped when run from the Unit tests..

I love this. I want to use that.

**Comment by MarcusDenker** [comment]
I will do a pass over the comments in a second step.

**Comment by Ducasse** [comment]
Ok this important because I do not really understand which one I should use.

**Pull request merged**
