### PR TITLE
2363 Add ProperManifestCategorizationTest as new release test

### LINKED ISSUE #2363: Add ProperManifestCategorizationTest as new release test
If a package provides a PackageManifest subclass then this manifest class should be packaged 
with 'Manifest' tag similar to all other manifests.

We cleaned the package manifests in https://pharo.fogbugz.com/f/cases/22436/PackageManifest-subclasses-should-be-packaged-with-Manifest-tag and subcases. 

Now we should add a new release test that keeps that quality level: Package manifests should not be untagged but tagged in a class category 'Manifest'.

### PR DESCRIPTION
**Pull request by astares**
Fixes #2363

### CODE REVIEW

**Comment by jecisc** [comment]
Can we wait for https://github.com/pharo-project/pharo/pull/2314 and use #assertEmpty: please? 

Release tests are the typical tests where this is the most useful.

**Comment by astares** [comment]
There is no need to wait for 2314 ... can we move forward please?

**Comment by astares** [comment]
2314 is closed, can we move on?

**Comment by estebanlm** [comment]
checking the crash

**Pull request merged**
