### PR TITLE
Kernel dependencies cleanup

### PR DESCRIPTION
**Pull request by pavel-krivanek**
Do some cleanup in known kernel dependencies and related tests

### CODE REVIEW

**Comment by pavel-krivanek** [comment]
The only dependency left is FileSystem-Core, I will not solve it in this PR (it requires superpower)

**Comment by Ducasse** [comment]
I read everything and this is cool. 
It is an example of what we should continue to push. 
I like the systemNotification!!!

**Comment by Ducasse** [comment]
the following broken tests seem related

unix-32 / Tests-unix-32 / testTraitCreationInDifferentCategories – Unix32.SUnit.Tests.Core.ClassFactoryForTestCaseTest
<1s
unix-32 / Tests-unix-32 / testDuplicateClassWithNewName – Unix32.SUnit.Tests.Core.ClassFactoryForTestCaseTest
<1s
unix-32 / Tests-unix-32 / testDefaultCategoryCleanUp – Unix32.SUnit.Tests.Core.ClassFactoryForTestCaseTest
<1s
unix-32 / Tests-unix-32 / testSingleTraitCreation – Unix32.SUnit.Tests.Core.ClassFactoryForTestCaseTest
<1s
unix-32 / Tests-unix-32 / testAnnouncement – Unix32.SUnit.Tests.Core.TestCaseTest

**Comment by Ducasse** [comment]
I do not get why testDefaultCategoryCleanUp
	| createdClassNames allClasses allTraits |
	
	3 timesRepeat: [
		factory newClass.
		factory newTrait].
	
	createdClassNames := factory createdClassNames.
	
	factory cleanUp.	
	
	self assert: (factory createdClasses allSatisfy: [:class| class isObsolete]). 
	self assert: (factory createdTraits allSatisfy: [:trait| trait isObsolete]). 
	
	allClasses := SystemNavigation new allClasses.
	allTraits := testingEnvironment allTraits.
	
	self assert: (factory createdClasses noneSatisfy: [:class| allClasses includes: class]).
	self assert: (factory createdTraits noneSatisfy: [:trait| allTraits includes: trait]).
	self deny: (SystemOrganization categories includes: factory defaultCategory). 
	self class environment at: #ChangeSet ifPresent: [:changeSet |
		self deny: (changeSet current changedClassNames includesAnyOf: createdClassNames) ].

is broken

**Comment by pavel-krivanek** [comment]
nothing from these tests is failing on local machine, let's try to restart the build

**Comment by pavel-krivanek** [comment]
maybe it is somehow related to the SystemNotification when it is processed in the non-interactive mode

**Comment by Ducasse** [comment]
Ok let us check. I do not understand why these tests are impacted.

**Comment by pavel-krivanek** [comment]
The CI reports were not really clear. I tried to run the tests from the command line and they were green. The problem was in the fact that the failing tests were part of Kernel tests job, the one that loads SUnit and some kernel tests into the raw bootstrapped image.

BTW. it is possible to restart the job validation without need of closing and re-opening of the PR in the CI web interface.

**Comment by pavel-krivanek** [comment]
I like GREEN color ;-)

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
