### PR TITLE
22637-Minor-cleanup-of-Delay

### PR DESCRIPTION
**Pull request by bencoman**
22637-Minor-cleanup-of-Delay

### CODE REVIEW

**Comment by pavel-krivanek** [comment]
I think it should be moved to Pharo 8

**Comment by bencoman** [comment]
okay - I'm not able to add any labels like "Hold" or a Milestone.

**Comment by estebanlm** [comment]
this now has conflicts. 
can you fix and commit?

**Comment by Ducasse** [comment]
Hi Ben 
Can you check because now there is a conflict. I'm trying to clean the backlog of PRs so that we can focus. 

Stef

**Comment by Ducasse** [comment]
Ben? Do you have cycle for this PR?

**Comment by Ducasse** [comment]
So it is ready for integration?

**Review by guillep — APPROVED** [review]
I think the changes are good

**Comment by bencoman** [comment]
I will update PR.

**Comment by estebanlm** [comment]
@bencoman we are waiting for you ;)

**Comment by bencoman** [comment]
I've tried four or five times to get back into this, but every time I am trying to bring the old commit forward to latest Pharo 8 I'm hit with a really immense wall of unrelated changes.  I saw it **briefly** mentioned on the mail list that its "just" a display problem with the diff morph and behind the scenes the three-way-merge is working, but the actions to take are not clear.    The unreliable operation of the diff-view is really undermining my confidence in my contributions and discouraging my efforts.

**Comment by jecisc** [comment]
@bencoman I did a branch from yours and did the merge myself to resolve the conflict. 

If it's fine with you, the new PR is: https://github.com/pharo-project/pharo/pull/3860

**Pull request merged**
