### PR TITLE
2279-We-should-revisit-definitionForNautilus-

### LINKED ISSUE #2279: We should revisit definitionForNautilus
We can ask a class its definition and definition for nautilus. 
The definition returns old format
 'Object subclass: #Point
	instanceVariableNames: ''x y''
	classVariableNames: ''''
	poolDictionaries: ''''
	category: ''Kernel-BasicObjects'''

and definitionForNautilus

'Object subclass: #Point
	instanceVariableNames: ''x y''
	classVariableNames: ''''
	package: ''Kernel-BasicObjects'''

which is a lot better. 

Now it would be good make sure that changersorter and other tools can load the new version 
and rename definitionForNautilus into definition and definition in oldDefinition

### PR DESCRIPTION
**Pull request by estebanlm**
do not use #definitionForNautilus anymore (instead, use just definition).

Fixes #2279

### CODE REVIEW

**Comment by MarcusDenker** [comment]
lots of failing tests.

I tried this once and gave up...

**Comment by MarcusDenker** [comment]
#3339 touches definitionForNautilus, too... I should have merged it, but I am waiting for a review.

**Comment by MarcusDenker** [comment]
but it looks already quite good: mostly RB tests failing, my problem was Monticello back then

**Review by MarcusDenker — DISMISSED** [review]
failing tests need to be fixed

**Comment by Ducasse** [comment]
Oops we still have related test failing.

**Comment by estebanlm** [comment]
resuming this. 
I will try to fix it today, but this is going to be just a middle-term solution. In a next issue, we need to change all the #oldDefinition sends with a real ClassDefinition object, that can compare by entity and not a single string comparison as it is now.

**Comment by estebanlm** [comment]
ok now, errors not related :)

**Review by MarcusDenker — APPROVED** [review]
ok

**Pull request merged**
