### PR TITLE
Extend FFIExternalStructureReferenceHandle with tfPointerAddress

### PR DESCRIPTION
**Pull request by tinchodias**
Related to https://github.com/pharo-project/pharo/issues/4452

### CODE REVIEW

**Comment by tinchodias** [comment]
Often the handle of a `FFIExternalStructure` is either a `ExternalAddress` or a `ByteArray`. They both respond to `tfPointerAddress` when they are arguments to FFI calls, but I've found a third kind of handles: the `FFIExternalStructureReferenceHandle`. See examples in following code:

```
TFPointTestStruct externalNew autoRelease getHandle class. "ExternalAddress"
TFPointTestStruct new getHandle class. "ByteArray"

anArray := FFIExternalArray newType: TFPointTestStruct size: 3.
anArray third getHandle class. "FFIExternalStructureReferenceHandle"
```

I don't know the design, I'm not expert in TFFI at all, just a user. But I propose in this request to add the missing `tfPointerAddress`.

**Comment by tinchodias** [comment]
My change includes 2 new tests that I think show the fix. However, I added 4 tests more that I don't know why they signal error. I attach them in the ombu file that should be applied after loading this PR.

[otherTestsThatSignalError.ombu.zip](https://github.com/pharo-project/pharo/files/13532179/otherTestsThatSignalError.ombu.zip)

**Comment by estebanlm** [comment]
that seems reasonable :)

**Comment by tinchodias** [comment]
Thanks Esteban! so it can be merged in P12. Do you think it can be backported to P11 too?

**Comment by estebanlm** [comment]
if you make the PR ;)

**Comment by tinchodias** [comment]
@estebanlm thanks here it is for P11: https://github.com/pharo-project/pharo/pull/15951

**Pull request merged**
