### PR TITLE
Move to Iceberg v2

### LINKED ISSUE #8423: unused Ivars in Iceberag: IceTipAdoptCommitCommand , LGitReadStream
**Describe the problem**
LGitReadStream and IceTipAdoptCommitCommand have unused instance variables

### PR DESCRIPTION
**Pull request by tinchodias**
Hi. It's a request to merge this tag:

https://github.com/pharo-vcs/iceberg/releases/tag/v2.0.0

### CODE REVIEW

**Comment by Ducasse** [comment]
Hi martin 

```
The build says:
NewUndeclaredWarning: IceTipNewRepositoryPanel>>newRepository (IceRepositoryCreator is Undeclared)
NewUndeclaredWarning: IceTipRepositoryTypePanel>>defaultLocation (IceLibgitRepository is Undeclared)
NewUndeclaredWarning: IceTipRepositoryTypePanel>>defaultSubdirectory (IceLibgitRepository is Undeclared)
MetacelloNotification: Loaded -> Iceberg-TipUI-tonel.1 --- github://pharo-vcs/iceberg:v2.0.0 --- cache
MetacelloNotification: Loading -> Iceberg-Plugin-tonel.1 --- github://pharo-vcs/iceberg:v2.0.0 --- cache
MetacelloNotification: Loaded -> Iceberg-Plugin-tonel.1 --- github://pharo-vcs/iceberg:v2.0.0 --- cache
MetacelloNotification: Loading -> Iceberg-Plugin-Calypso-tonel.1 --- github://pharo-vcs/iceberg:v2.0.0 --- cache
Error: This package depends on the following classes:
  ClyIcebergShowMethodVersionCommand
You must resolve these dependencies before you will be able to load these definitions: 
  ClyIcebergShowMethodVersionCommand>>#execute

MCPackageLoader(Object)>>notify:
MCPackageLoader>>warnAboutDependencies
MCPackageLoader>>validate
MCPackageLoader>>loadWithNameLike:
MCVersionLoader>>basicLoadWithNameLike:
[ self basicLoadWithNameLike: aString ] in MCVersionLoader>>loadWithNameLike: in Block: [ self basicLoadWithNameLike: aString ]
[ returnValue := aBlock value ] in [ 
		[ returnValue := aBlock value ] ensure: [ 
			self announceLoadStop: aString ] ] in MCVersionLoader>>announceLoad:do: in Block: [ returnValue := aBlock value ]
BlockClosure>>ensure:
[ 
```

**Comment by tinchodias** [comment]
What are the yellow "Recording test results [Checks API] No suitable checks publisher found."?

**Comment by MarcusDenker** [comment]
Four tests are failing:


testEqualMethodNeedsToBeInComparingProtocol

```
Violations: IceTipCachedModel>>#=.   Reason: IceTipCachedModel>>#= subclasses should have #Object in protocol =
```

testMethodsContainNoHalt


```
Found methods with haltan OrderedCollection(IceFileSystemDefinition>>#path:)
```

testExternalIDEDependencies

```
Given Collections do not match!  additions : #(#'Ring-Core')  missing: #()
```

testDefaultImageDoesNotStoreAnySetting

```
Given Collections do not match!  additions : an Array(a StoredSetting('#commitPreferences#saveImageOnCommit') a StoredSetting('#commitPreferences#pushOnCommit'))  missing: #()
```

**Comment by tinchodias** [comment]
Thank you, Marcus. I'd like to learn where to click to see the errrors. After clicking in the "continuous-integration/jenkins/pr-merge" Details (https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-8461/4/display/redirect)

I clicked on unix-64 which had the yellow warning mark, and then clicked to expand each of the horizontal small reports below... and couldn't see that info.

<blockquote><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-8461/4/display/redirect">Jenkins</a></strong></div></blockquote>

**Comment by tinchodias** [comment]
I have fixed 2/4. Remaining:
- external dependencies: I have a fix in mind
- settings issue, I'm a bit lost (https://github.com/pharo-vcs/iceberg/issues/1405)

**Comment by tinchodias** [comment]
I didn't understand where are the failed tests, with the new commit.

Anyway I wanted to wait until tomorrow for a changeset from "gcorriga" user in Discord, to update the world menu entry.

**Comment by tinchodias** [comment]
I managed to read the output of Jenkins. I'm fixing the failing dependency test.

**Comment by tinchodias** [comment]
This time, only windows build failed

**Pull request merged**
