### PR TITLE
Add file out for Epicea entries

### PR DESCRIPTION
**Pull request by hernanmd**
This initial PR add support to file out selected entries from the Epicea Browser. It is intended to replace the ChangeSet tools similar behavior.

- Add a chunk exporter for Epicea along with file out protocol for multiple Epicea opeartions (Method/Class/Protocol/traits modifications, removals, additions, etc.).
- Include a new Epicea menu item entry to file out selected elements.
- Add tests in #EpFileOutModificationsTest.

### CODE REVIEW

**Comment by jecisc** [comment]
We have a few tests failures:

```
Message not understood: BehaviorForTestToBeDeleted76 class >> #origin
Stacktrace
MessageNotUnderstood
Message not understood: BehaviorForTestToBeDeleted76 class >> #origin
BehaviorForTestToBeDeleted76 class(Object)>>doesNotUnderstand: #origin
EpMethodModification>>fileOutEntryOn:
OmEntry>>fileOutEntryOn:
EpChunkExporter>>fileOutSelectedEntry:on:
[ : epEntryItem |
		self 
			fileOutSelectedEntry: epEntryItem 
			on: internalStream ] in EpChunkExporter>>fileOut:in:
OrderedCollection>>do:
EpChunkExporter>>fileOut:in:
EpChunkExporter>>fileOut:
EpFileOutModificationsTest>>testFileOutSingleMethodModificationOfProtocol
EpFileOutModificationsTest(TestCase)>>performTest
```

**Comment by Ducasse** [comment]
Hi hernan 
We would like to fileout tonel format and not chunk formats.

**Comment by hernanmd** [comment]
> Hi hernan We would like to fileout tonel format and not chunk formats.

So far I don't see enough Tonel support for emulating all the chunk export operations. For example if my changes are only method/protocol or package removals, what should the TonelWriter write?

**Comment by MarcusDenker** [comment]
For being able to remove the changesorter and even the changeset infrastructure (loading we would keep anyway), this could be a first step

**Comment by MarcusDenker** [comment]
I propose to merge this

- after, clean up changesets
- then, independent, look into using tonnel format

**Comment by jecisc** [comment]
I think as Marcus

**Review by MarcusDenker — APPROVED** [review]

**Comment by Ducasse** [comment]
Agreed. I have this item on my list for hernan.

**Pull request merged**
