### PR TITLE
Shout: Manage syntax highlight of dynamic array

### LINKED ISSUE #12923: Shout: braces in return do not honor their style
If a dynamic array is in a return, the style of the return is applied and not the style defined for #leftBrace and #rightBrace.

I'll see to fix that soon

### LINKED ISSUE #12941: Shout: Braces styling does not work like parenthesis and block styling
For parenthesis and blocks we can give different styles depending on the imbrication. It is not possible for dynamic arrays.

I propose to manage it as we manage the others.

I'll do a PR when my other PRs on styling will be integrated

### PR DESCRIPTION
**Pull request by jecisc**
The braces have a style declared in Shout but this is never used. 

This PR introduce the highlighting of dynamic array and makes it like parenthesis or block: have some imbrications

Fixes #12941 
Fixes #12923

### CODE REVIEW

**Comment by MarcusDenker** [comment]
- [CI] Fail on WIN random: OmSessionStoreTest(OmStoreTest)>>testEntryForAbsentEntry #12126

**Review by MarcusDenker — APPROVED** [review]

**Comment by estebanlm** [comment]
this PR seems to have broke something.
1) I have an "unary"  style tag missing (maybe others). 
2) For some reason it breaks styles like my solarized dark: 

Screenshot from 2023-03-09 23-10-33

I am not saying this is a mistake, but I would like to understand the rational in the removals and what is intended to be replaced for.

**Comment by jecisc** [comment]
This was done in a previous PR.

Some styles were removed because shout was never assigning them. Since the Theme system was already changed in P11, we are also cleaning shout and doing the breaking changes now. I was planning to do a PR to your style after the work on shout is done

**Comment by estebanlm** [comment]
but the shout does assign them (even if many times they are not used).
and there is the SpCodeAdapterTest to prove it :)
(in fact I wonder how is possible you had a green test with it)

**Comment by jecisc** [comment]
I’ll try to check today in an old image how it is possible we ended up with “unary” or “binary” in the style because I’ve never seen it assigned anywhere in the styler.

**Comment by estebanlm** [comment]
unary, binary and keyword.
all them can be used (even if they may not be used in the styles present in the image)

**Pull request merged**
