### PR TITLE
4088-Commit-should-have-been-implemented-in-IceUnknownCommit

### LINKED ISSUE #4088: Commit should have been implemented in IceUnknownCommit
In Pharo build 453.sha.43f21722, select any package and attempt to commit:

image

### PR DESCRIPTION
**Pull request by jecisc**
Inform the user of error while trying to commit with a non operational git repository.

A Camp smalltalk fix with James Foster ;)

Fixes #4088

### CODE REVIEW

**Review by VincentBlondeau — APPROVED** [review]
targetRepo isMissing or: [ targetRepo isCodeMissing or: [ targetRepo isDetached or: [ targetRepo hasUnbornProject ] ] ]
Could be extracted to a method in the targetRepo class and message can be adapted accordingly too.

**Comment by VincentBlondeau** [comment]
Tests failures are not related

**Comment by Ducasse** [comment]
may be we should commit this to iceberg repo?

**Comment by tesonep** [comment]
Yes, it should go in iceberg and maybe using polymorphism for handling the messages instead of a chained condition (only the nil, we should not add messages to nil)

**Comment by jecisc** [comment]
I agree it should be improved and probably moved. I did this PR to at least fix it until we have time to further improve it because it currently causes trouble to newcomers to get an exception.

**Comment by MarcusDenker** [comment]
Changes to Iceberg tend to take very long till they end up in Pharo. So having a workaround is good

**Pull request merged**
