### PR TITLE
3373-Integrate-SUnit-visitor

### LINKED ISSUE #3373: Integrate SUnit visitor
SUnit-Visitor has been implemented some times ago and it allows to reuse visit logic of SUnit.

After a discussion with Steph, Guille and Damien we think it should be integrated.

Actual repository: https://github.com/juliendelplanque/SUnit-Visitor

### PR DESCRIPTION
**Pull request by juliendelplanque**
Added visitor entries in baseline.

Fix #3373

### CODE REVIEW

**Comment by juliendelplanque** [comment]
@cdlm @guillep You might be interested in reviewing.

**Comment by juliendelplanque** [comment]
Failing because no space left on CI's disk.
Needs to be restarted once this problem is fixed.

**Review by jecisc — CHANGES_REQUESTED** [review]
Dependencies tests are failing. (You should also maybe merge Pharo8.0 in your branch to fix the announcements tests)

**Comment by juliendelplanque** [comment]
Just merged Pharo8. Looking at dependencies problem.

**Comment by juliendelplanque** [comment]
Not sure how to solve the dependencies problem. Any hints?

**Comment by Ducasse** [comment]
Yes I would like to sit with guille and pablo to see because I also do not get why when I extracted a baseline I got dependencies violation that I could not find with the package analyzer.

**Comment by Ducasse** [comment]
Many for the dependencies it would be something to do for this PR and the one we did with cyril to extract the recentActivity. 
What we could do is to integrate them both one after the other and fix all the dependencies in one shot?
What do you think?

**Comment by tesonep** [comment]
@juliendelplanque these days we can check it. Don't let the impulse die!

**Comment by juliendelplanque** [comment]
Yeah we should I have been a bit busy these last week.

**Comment by estebanlm** [comment]
whoa. Why all this changes?
Maybe worths a merge with Pharo8.0 before?

**Comment by Ducasse** [comment]
We are trying with guille to integrate this change and the problem is that the SystemDependenciesTest are super painful and I do not think that there are really useful. (we get an broken test and a package not loaded instead of a broken build).

**Comment by jecisc** [comment]
I did a cleaner merge in this new PR: https://github.com/pharo-project/pharo/pull/3859

**Comment by jecisc** [comment]
@Ducasse This one can be closed.

**Pull request closed without merging**
