### PR TITLE
6036-Test-should-not-rely-on-random-formatter

### PR DESCRIPTION
**Pull request by Ducasse**
do not hard BI in default settings.

### CODE REVIEW

**Review by guillep — APPROVED** [review]
Good!

**Comment by guillep** [comment]
There is related broken test, failing in the three platforms equally:

```
SystemSettingsPersistenceTest >> testDefaultImageDoesNotStoreAnySetting
```

**Comment by Ducasse** [comment]
I tried to understand but I have no idea about how this test is working. 
I do not even understand where these settings are stored and sorry but these tests are not self documented.

**Comment by Ducasse** [comment]
And I do not get why there are 10 elements while apparently one only is related to BIformatter.
Seriously this is totally arcane to me.

**Comment by guillep** [comment]
Probably related to

https://github.com/pharo-project/pharo/pull/5572
https://github.com/pharo-project/pharo/issues/5571
https://github.com/pharo-project/pharo/pull/5473
https://github.com/pharo-project/pharo/issues/5434

Settings that make this test fail make images in the pharo launcher behave strangely.
Probably those tests deserve better comments, yes.
I don't know the details.

**Comment by Ducasse** [comment]
I know that this is linked with the idea that we should not save setting when they did not change or something like that but after 30 min I could not understand the factory and the tests. :(

**Comment by Ducasse** [comment]
I think that I will need pablo to have a look because I'm lost there.

**Comment by tesonep** [comment]
I have changed back the default formatter in the settings to BIConfigurableFormatter
As it is initialized by BaselineOfIDE

**Comment by Ducasse** [comment]
ah but I want to be able to unload BIConfigurableFormatter so I will check.

**Comment by Ducasse** [comment]
I'm confused. I put the simple formatter because the Configurable to be optional and we should unload it.

**Comment by Ducasse** [comment]
So should I merge my changes then later we address the problem of the reference to the configurationFormatter?

**Pull request merged**
