### PR TITLE
fixes 10525 -  extract Keymapping packages to its own baseline

### LINKED ISSUE #10525: extract Keymapping packages to its own baseline
**Describe the request**
Today Keymapping packages are embeded in the pharo structure without clear division, making it hard to take it independently (as it would be the case if starting from Pharo minimal images to arrive to something that includes keymapping but not the whole image)

**Expected behavior**
There is a baseline that allows to load the keymapping infrastructure without needing to hack.

### PR DESCRIPTION
**Pull request by estebanlm**
Fixes https://github.com/pharo-project/pharo/issues/10525

### CODE REVIEW

**Comment by MarcusDenker** [comment]
bootstrap problem:

```
Instance of MetacelloBaselineConstructor did not understand #for:with:
MetacelloBaselineConstructor(Object)>>doesNotUnderstand: #for:with:
BaselineOfKeymapping>>baseline:
```

**Comment by estebanlm** [comment]
oops :P

**Comment by estebanlm** [comment]
mmm... I do not understand that failure, no idea if this is related to me.
Any idea @MarcusDenker ?

**Comment by MarcusDenker** [comment]
very odd.. I have restarted the CI run

**Comment by estebanlm** [comment]
I did touch the bootstrap process, but that didn't look like mine ;)

**Comment by MarcusDenker** [comment]
the error is:

```
Error: This package depends on the following classes:
  TextMorph
  PluggableListMorph
  StringMorph
  UITheme
  TextLine
You must resolve these dependencies before you will be able to load these definitions: 
  GrowlMorph
  GrowlMorph>>#contents:
  GrowlMorph>>#growlPositionChoices
  GrowlMorph>>#growlSettingsOn:
  GrowlMorph>>#growlTypeChoices
  GrowlMorph>>#label:contents:
  GrowlMorph>>#openWithContents:
  GrowlMorph>>#openWithLabel:contents:
  GrowlMorph>>#openWithLabel:contents:backgroundColor:labelColor:
  GrowlMorph>>#openWithLabel:contents:color:
  GrowlMorph>>#position
  GrowlMorph>>#position:
  GrowlMorph>>#possiblePositions
  GrowlMorph>>#possibleTypes
  GrowlMorph>>#type
  GrowlMorph>>#type:
  GrowlMorph>>#actionBlock:
  GrowlMorph>>#activeGrowlMorphs
  GrowlMorph>>#alpha
  GrowlMorph>>#alpha:
  GrowlMorph>>#backgroundColor
  GrowlMorph>>#contents:
  GrowlMorph>>#contentsAttributes
  GrowlMorph>>#contentsColor
  GrowlMorph>>#contentsColor:
  GrowlMorph>>#createDismissHandle
  GrowlMorph>>#defaultBackgroundColor
  GrowlMorph>>#defaultBorderColor
  GrowlMorph>>#defaultTextStyle
  GrowlMorph>>#defaultVanishDelay
  GrowlMorph>>#enabled
  GrowlMorph>>#handlesMouseDown:
  GrowlMorph>>#initialize
  GrowlMorph>>#initializeContentsAttributes
  GrowlMorph>>#initializeLabelAttributes
  GrowlMorph>>#is:saneWithRespectTo:
  GrowlMorph>>#label:contents:
  GrowlMorph>>#labelAttributes
  GrowlMorph>>#labelColor
  GrowlMorph>>#labelColor:
  GrowlMorph>>#minimumExtent
  GrowlMorph>>#mouseDown:
  GrowlMorph>>#nextColorStep:
  GrowlMorph>>#preOpenInWorld:
  GrowlMorph>>#resetAlpha
  GrowlMorph>>#resetVanishTimer
  GrowlMorph>>#step
  GrowlMorph>>#stepTime
  GrowlMorph>>#streamDo:
  GrowlMorph>>#unoccupiedPosition
  GrowlMorph>>#unoccupiedPositionBottomLeft
  GrowlMorph>>#unoccupiedPositionBottomRight
  GrowlMorph>>#unoccupiedPositionTopLeft
  GrowlMorph>>#unoccupiedPositionTopRight
  GrowlMorph>>#vanishDelay
  GrowlMorph>>#vanishDelay:
  GrowlMorph>>#wantsSteps
  PluggableListMorph>>#setListFont
  StringMorph>>#changeFont
  TextLine>>#justifiedPadFor:font:
  UITheme>>#growlBorderColorFor:
  UITheme>>#growlContentsColorFor:
  UITheme>>#growlDismissHandleFor:
  UITheme>>#growlFillColorFor:
  UITheme>>#growlLabelColorFor:
```

**Comment by estebanlm** [comment]
yeah, but is while trying to load the GlowlMorph, which I think I am not touching?
that's why I do not understand.

**Comment by estebanlm** [comment]
now failing tests are not related :)

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
