### PR TITLE
Cleanup: Condense STON packages

### LINKED ISSUE #12627: Cleanup: Condense STON packages
```Smalltalk
cms := CompiledMethod allInstances select: [:each |
each package ifNil: [ false ] ifNotNil: [:p |
	p name beginsWith: 'STON' ] ].
 

cms do: [:cm |
    ((RBRefactoryChangeFactory instance)
         addMethodSource: (ReMethodSourceCleaner clean: cm sourceCode) in: cm origin) execute ]
```

### PR DESCRIPTION
**Pull request by astares**
Fix #12627

### CODE REVIEW

**Comment by astares** [comment]
image

**Comment by jecisc** [comment]
CI failure not related

**Comment by demarey** [comment]
These changes should also be proposed as a PR to the original repository: https://github.com/svenvc/ston

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/svenvc/ston">GitHub - svenvc/ston: STON - Smalltalk Object Notation - A lightweight text-based, human-readable data interchange format for class-based object-oriented languages like Smalltalk.</a></strong></div><div>STON - Smalltalk Object Notation - A lightweight text-based, human-readable data interchange format for class-based object-oriented languages like Smalltalk. - GitHub - svenvc/ston: STON - Smalltal...</div></blockquote>

**Comment by guillep** [comment]
Yes, I agree with @demarey . This should be done in the STON repo upstream, and then just a new version of STON should be installed.

**Comment by astares** [comment]
@guillep But why is the source code then in the Pharo repo (when we can load from other repo like in Roasssal3 case during bootstrap?)

**Comment by jecisc** [comment]
@astares i don’t know for ston, but lot of Sven’s work is needed for the bootstrap and it is not so easy to extract it.

**Pull request closed without merging**
