### PR TITLE
Revert "22284-Freeze-during-startup"

### PR DESCRIPTION
**Pull request by VincentBlondeau**
Reverts pharo-project/pharo#1659

It was not so good idea to remove the high priority process that launch the image. Setting up the core objects with the new parameters should be done before resuming any old process (that is the case when you "save as:" the image). I made a dummy test case you could try:
```
[
[SmalltalkImage current snapshot: true andQuit: true.] forkAt: Processor lowestPriority .	
[SmalltalkImage current snapshot: true andQuit: true.] forkAt: Processor highestPriority .
 .]forkAt: 50
```
If you execute this on the current image, you will not be able to use you image anymore, it will close in an infinite loop.
If you execute this on before the integration, the image will close itself exactly twice.

### CODE REVIEW

**Comment by dionisiydk** [comment]
The change was related to another issue with hanged image after snapshot.
There was no issue in pharo 6. Probably we should try revert this version:
```Smalltalk
snapshot: save andQuit: quit
	| isImageStarting snapshotResult |
	ChangesLog default logSnapshot: save andQuit: quit.
	
	self currentSession stop: quit.	"Image not usable from here until the session is restarted!"
	save
		ifTrue: [
					snapshotResult := Smalltalk snapshotPrimitive.	"<-- PC frozen here on image file"
					isImageStarting := snapshotResult == true. ]
		ifFalse: [ isImageStarting := false ].
	(quit and: [ isImageStarting not ])
		ifTrue: [ Smalltalk quitPrimitive ].

	"create a new session object if we're booting"
	isImageStarting ifTrue: [ self installNewSession ].

	self currentSession start: isImageStarting.
	snapshotResult 
		ifNil: [ self error: 'Failed to write image file (disk full?)' ]
		ifNotNil: [ 
			SystemAnnouncer uniqueInstance snapshotDone: isImageStarting ].
	
	"We return the resuming state, which may be useful for users to know the state of the image"
	^ isImageStarting
```

**Comment by dionisiydk** [comment]
But it is exact code of launchSnapshot method.
The question why it was not issue in Pharo 6?

**Comment by dionisiydk** [comment]
I checked your test does not work in Pharo 6. At least it is not new issue.
But the problem with forked snapshot gives us more bad behaviour. 
For example saving image with running http-server breaks it.

**Comment by VincentBlondeau** [comment]
Processor highestPriority should not be used as process value for forking.
See detail explanation in: https://pharo.fogbugz.com/f/cases/22284/Freeze-during-startup

I added some comments too

**Comment by guillep** [comment]
Well, theoretically I like the change, I like the idea that the startup cannot get interrupted (or almost).

@VincentBlondeau can you confirm if the problems in https://github.com/pharo-project/pharo/pull/1659 are gone?

**Comment by VincentBlondeau** [comment]
@guillep Could you tell me how to reproduce your issue with the stack corruption? I haven't find how to reproduce it

**Comment by guillep** [comment]
@VincentBlondeau have you tried the script sent by Christophe https://pharo.fogbugz.com/f/cases/22284/Freeze-during-startup

**Comment by VincentBlondeau** [comment]
@guillep I tried and working!

**Pull request merged**
