### PR TITLE
21523-package-ReflectionMirrors-Primitives-needs-to-be-moved-to-the-BaselineOfPharoBootstrap

### PR DESCRIPTION
**Pull request by dionisiydk**
ReflectionMirrors-Primitives is moved from BaselineOfIDE to BaselineOfPharoBootstrap.

https://pharo.fogbugz.com/f/cases/21523/package-ReflectionMirrors-Primitives-needs-to-be-moved-to-the-BaselineOfPharoBootstrap

### CODE REVIEW

**Comment by tesonep** [comment]
Why it is added there? Can it be loaded after? Because adding dependencies to the bootstraped image is not a good idea.

**Comment by dionisiydk** [comment]
Idea to replace all code like:
```Smalltalk
thisContext objectClassOf: anObject
thisContext object: anObject at: 1 put: aValue
```
For example it is used in Slot's which are part of bootstrap baseline. 

Generally any thisContext call makes senders slow. So we need another way to access mirror primitives. And that's why I introduced MirrorPrimitives class. Maybe It is not the best solution but it is better than thisContext.

Another user of these primitives is Context itself. So mirror primitives are already in kernel. And from this point of view we do not introduce new feature into Kernel but we kind of refactor it. At next step we will be able remove mirror methods from Context. (probably with deprecation).

And it also means that we have duplication of mirror methods in Context and MirrorPrimitives. There is a bit complex logic there to handle primitives failure (It starts to be more complex with write barrier cases).

**Comment by tesonep** [comment]
Ok, great, I understand, but the question is that if it is needed to be inside the bootstrapped image, or if it can be loaded afterwards (like Multilingual packages). Because if they are not used during the simulation of the image (in the creation of the image) it is better to install it later. 

If you want I can show you how to add it.

**Comment by dionisiydk** [comment]
Unrelated

**Pull request merged**
