### PR TITLE
20364 Pharo 7 Help should already use Pharo 7 instead of 6 and show some first highlights

### PR DESCRIPTION
**Pull request by astares**
- use 7.0 alpha instead of 6.0 in welcome help
-  already inform about some of the new highlights like development process with git, Hermes, Renraku, WebBrowser, ...

### CODE REVIEW

**Comment by astares** [comment]
FogBugz number: https://pharo.fogbugz.com/f/cases/20364/Pharo-7-Help-should-already-use-Pharo-7-instead-of-6-and-show-some-first-highlights

**Comment by MarcusDenker** [comment]
I wonder why the PR fails the build?

**Comment by astares** [comment]
I do not understand it either. The changes should not affect any tests ...

**Comment by MarcusDenker** [comment]
The build itself is failing, so maybe that is the same reason

**Comment by astares** [comment]
It fails also for https://github.com/pharo-project/pharo/pull/238

**Review by MarcusDenker — APPROVED** [review]
looks good! and now even the build / tesrun was successful

**Pull request merged**
