### PR TITLE
22112-Remove-code-related-to-HostSystemMenus

### PR DESCRIPTION
**Pull request by jecisc**
Remove code related to HostSystemMenus. This also remove a dependency from  System-VMEvents to Morphic-Core. 

https://pharo.fogbugz.com/f/cases/22112/Remove-code-related-to-HostSystemMenus

### CODE REVIEW

**Comment by jecisc** [comment]
If someone knows when the vm send EventTypeMenu events and if they're still sent, it would be a big help :)

**Review by MarcusDenker — APPROVED** [review]
my guess is that EventTypeMenu is send only by the plugin that was removed

**Comment by jecisc** [comment]
I sent a mail to the VM mailing list to get more info.

**Comment by pavel-krivanek** [comment]
```
David T. Lewis 
I do not know if event type 4 is still produced, but it was introduced in the
Mac OS VM, and there is in explanation in platforms/vm/Documentation/3.8.x Release Notes.rtf:

  sq.h  Added events, EventTypeMenu, EventTypeWindow to handle menu and window
  events generated by the Host OS and placed on the Squeak Event Queue to be
  read by EventSensor
```

**Review by pavel-krivanek — APPROVED** [review]
looks ok

**Pull request merged**
