### PR TITLE
16569-CI-Pharo13-code-with-halt-was-merged 

### LINKED ISSUE #16567: [CI] Pharo13 tests on OSX crash  in  Refactoring-Transformations-Tests
**Bug description**
The test run hard crashes after ~4min when running  Refactoring-Transformations-Tests

```
Beginning to run tests of Refactoring-Transformations-Tests with random seed 980020457
TestTookTooMuchTime
Process>>pvtSignal:list:
Context(Object)>>copy
Context>>copyTo:
Context>>copyTo:
Context>>copyTo:
Context>>copyTo:
Context>>copyTo:
Context>>copyTo:
Context>>copyTo:

script returned exit code 1
```

### LINKED ISSUE #16569: [CI] Pharo13: code with halt was merged
**Bug description**
We merged PRs with bad code:

```
NoUnusedVariablesLeftTest.testNoUnusedInstanceVariablesLeft
ProperMethodCategorizationTest.testNoUncategorizedMethods
ReleaseTest.testMethodsContainNoHalt
```

### LINKED ISSUE #16571: [CI]  Pharo13: Tests failing for RB
**Bug description**
Related to Refactoring transformation, we have these tests failing 

```
Unix64.Refactoring.Transformations.Tests.RBAbstractTransformationTest.testAPl

   an OrderedCollection(ReCompositeExtractSetUpMethodRefactoring) should have been empty
```

The next two run into a timeout after 20 seconds:

```
Unix64.Refactoring.Transformations.Tests.RBExtractSetUpMethodAndOccurrencesParametrizedTest.testExtractSimpleMethodAndOcurrences#rbClass->RBExtractSetUpMethodAndOccurrences)

+ Unix64.Refactoring.Transformations.Tests.RBFindAndReplaceSetUpParametrizedTest.testReplaceSetUp(#rbClass->RBFindAndReplaceSetUpTransformation)|
```

### PR DESCRIPTION
**Pull request by MarcusDenker**
- remvove halt
- remove unused ivars
- categorize methods
- 
fixes #16569

### CODE REVIEW

**Comment by MarcusDenker** [comment]
I wonder if a better idea is not to revert https://github.com/pharo-project/pharo/pull/16525

**Comment by MarcusDenker** [comment]
Before merging, we need to decide if we do not better revert the PR that introduced these (and many more) problemsl.

The revert is here: https://github.com/pharo-project/pharo/pull/16572

**Review by balsa-sarenac — APPROVED** [review]
You can merge the fixes from here, they should make all the tests green.

https://github.com/MarcusDenker/pharo/pull/2

**Comment by Ducasse** [comment]
It was painful to work on non Pharo13 so let us lower our pain in Pharo13.

**Pull request merged**
