### PR TITLE
4161 less transcript hardcoded references

### PR DESCRIPTION
**Pull request by VincentBlondeau**
Related to issue: #4161.

- Deprecating Object >> *log* for *trace*
- Improve a bit some tests and printing patterns
84 references still to kill.

### CODE REVIEW

**Comment by Ducasse** [comment]
Wooo! this is cool.
I will review that later but this is cool

**Comment by Ducasse** [comment]
The build does not work because of bootstrap. 
I do not know how to proceed but this is a good case for me to learn. 
Could you split this issue with the change that are not in Object and related.

**Comment by VincentBlondeau** [comment]
The issue is the integration of the zip changes. Reverted by  https://github.com/pharo-project/pharo/pull/4449. If you trigger the build again, it should go a bit further

**Comment by Ducasse** [comment]
ouch. Thanks!!!

**Comment by dionisiydk** [comment]
Hi @VincentBlondeau 
Why #trace name is better than #log?

**Comment by Ducasse** [comment]
We should discuss it on the mailing-list.
I cleaned the beacon package and I would like to introduce it. 
So we should check that there is not API clash.
Denis log does not work because numbers understand it. So it can introduce super strange bugs.

**Comment by VincentBlondeau** [comment]
Where should KMLog class initialization should be called from?

**Pull request merged**
