### PR TITLE
add trace to #iconNamed:ifNone: to log all old names

### PR DESCRIPTION
**Pull request by MarcusDenker**
For #15198

- add trace to #iconNamed:ifNone:
- fix some

### CODE REVIEW

**Review by jecisc — APPROVED** [review]

**Comment by MarcusDenker** [comment]
I should fix more of the logs we see when running the tests before merging

**Comment by Ducasse** [comment]
I did not understand the PR because it is no in sync with the title.
I see just fixing names of icons (which is ok).

**Comment by Ducasse** [comment]
So I did not why the work needed status is set. So I will not integrate it.

**Comment by jecisc** [comment]
The change was to add a log when we use the fallback code for icons. But there are still way to many uses of this fallback and this floods the logs. This is the reason Marcus added the need more work tag

**Review by jecisc — APPROVED** [review]

**Comment by jecisc** [comment]
I think we can merge and fix the last icons in a next PR?

**Pull request merged**
