### PR TITLE
Unify protocol of baselines

### PR DESCRIPTION
**Pull request by jecisc**

### CODE REVIEW

**Comment by jecisc** [comment]
I also added a release test. 

With the unification, the system should automatically classify the #baseline: method of BaselineOfXX in the right protocol

**Comment by jecisc** [comment]
Github API limit rate..

**Review by MarcusDenker — APPROVED** [review]

**Comment by jecisc** [comment]
Oh boy, this will be long with the number of external changes to do

**Comment by jecisc** [comment]
I'm too lazy to fix all external projects for something this trivial so I'll just close.

**Pull request closed without merging**
