### PR TITLE
Optimized ephemeron support for Fuel

### LINKED ISSUE #15562: Optimized ephemeron support for Fuel
Fuel now supports optimized support for serializing ephemerons. The mechanism is the same as it has been for weak references, where weak references (or the ephemeron's key) are only serialized if there's also a strong reference to them from within the graph that is being serialized. The point of this is to reduce the size of the serialized graph, as weakly referenced objects would be collected by the garbage collector during materialization anyway, making it pointless for them to be serialized in the first place.

### PR DESCRIPTION
**Pull request by theseion**
Fixes #15562

### CODE REVIEW

**Comment by tinchodias** [comment]
I like the tests and detailed comments! thanks Max

**Comment by Ducasse** [comment]
This is strange that I cannot find the build. not even a failure o_O

**Comment by jecisc** [comment]
Hi, 

On another PR we got:

```
osx-64 / Tests-osx-64 / testWeakKeyAssociationMourningAfterMaterialization – MacOSX64.Fuel.Core.Tests.FLEphemeronTest7s
Error
Message not understood: WeakKeyAssociation >> #isEmpty
Stacktrace
MessageNotUnderstood
Message not understood: WeakKeyAssociation >> #isEmpty
WeakKeyAssociation(Object)>>doesNotUnderstand: #isEmpty
FLEphemeronTest>>testWeakKeyAssociationMourningAfterMaterialization
FLEphemeronTest(TestCase)>>performTest


osx-64 / Tests-osx-64 / testWeakKeyAssociationMourningBeforeMaterialization – MacOSX64.Fuel.Core.Tests.FLEphemeronTest8s
Error
Message not understood: WeakKeyAssociation >> #isEmpty
Stacktrace
MessageNotUnderstood
Message not understood: WeakKeyAssociation >> #isEmpty
WeakKeyAssociation(Object)>>doesNotUnderstand: #isEmpty
FLEphemeronTest>>testWeakKeyAssociationMourningBeforeMaterialization
FLEphemeronTest(TestCase)>>performTest
```

**Comment by theseion** [comment]
Which PR? I just checked. Those errors don't make sense...

**Comment by jecisc** [comment]
I do not remember the PR. 
But here is another one with a random failure: 

https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-15595/2/tests

```
unix-64 / Tests-unix-64 / testWeakKeyAssociationMourningAfterMaterialization – Unix64.Fuel.Core.Tests.FLEphemeronTest10s
Error
Denial failed
Stacktrace
TestFailure
Denial failed
FLEphemeronTest(TestAsserter)>>assert:description:resumable:
FLEphemeronTest(TestAsserter)>>deny:description:resumable:
FLEphemeronTest(TestAsserter)>>deny:description:
FLEphemeronTest(TestAsserter)>>deny:
FLEphemeronTest>>testWeakKeyAssociationMourningAfterMaterialization
FLEphemeronTest(TestCase)>>performTest
```

<blockquote><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-15595/2/tests">Jenkins</a></strong></div></blockquote>

**Comment by theseion** [comment]
I can reproduce it by brute force. There's some kind of race condition but I haven't yet figured out what it is.

**Comment by jecisc** [comment]
Here I have a failure for the #isEmpty!

https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-15636/2/tests

<blockquote><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-15636/2/tests">Jenkins</a></strong></div></blockquote>

**Comment by theseion** [comment]
https://github.com/theseion/Fuel/issues/288

**Pull request merged**
