### PR TITLE
7974 file class  open and truncate for write file named is a clunky name

### LINKED ISSUE #7974: File class >> openAndTruncateForWriteFileNamed: is a clunky name
I'm sure that we can do better.

### PR DESCRIPTION
**Pull request by AleCossioCh**
Fix #7974
- Add deprecation >>openAndTruncateForWriteFileNamed:

### CODE REVIEW

**Comment by Ducasse** [comment]
Alejandra I should have told you that you can use deprecated: transformWith: check the actual users because like that the system can rewrite users of the functionality automatically.

**Comment by Ducasse** [comment]
Yes!
Thanks. 
Now you should pay attention because we are in beta so we do not accept changes that changes too much. 
This one should be ok.

**Comment by estebanlm** [comment]
uhm... I am not so sure Iike the new name more than the old one :P

**Comment by Ducasse** [comment]
After discussion we will deprecated this method.

**Pull request closed without merging**
