### PR TITLE
Improve-WeakValueDictionary

### PR DESCRIPTION
**Pull request by jecisc**
Improve WeakValueDictionary in three way:
- Document the internal mecanism to explain why we need a wrapper around the values
- Fix bug in #at:ifPresent: (with test)
- Rename SetElement into CollectionElementWrapper since this class is use by other collections than Set

### CODE REVIEW

**Comment by dionisiydk** [comment]
Hi @jecisc.

Why SetElement is a bad name?
It was introduced specifically to allow a Set to include nil. It has zero relation to weak structures.

IMHO proposal rename feels bad because
```Smalltalk
anObject asCollectionElementWrapper == anObject "==> true"
``` 
It is not logical from the words meaning. I would expect a wrapper instance as a result.

In contrast
```Smalltalk
anObject asSetElement == anObject "==> true"
``` 
looks fine because any object can be an element of a Set. 
With your proposal we will say that any object is a wrapper for collection element. It sounds weird.

**Comment by jecisc** [comment]
Hi,

I proposed to rename it because SetElement is not only used by sets but also by other collections such as weak collections. So, IMO, it is not a good name. (I caused me trouble when I was looking at an issue with WeakValueDictionary).

CollectionElementWrapper is not a name that I really like but I did not found anything better yet. I am open to suggestions about that. CollectionElement would be better?

**Comment by jecisc** [comment]
> It has zero relation to weak structures.

@dionisiydk It is used to manage internal behavior of WeakValueDictionary

**Comment by dionisiydk** [comment]
> > It has zero relation to weak structures.
> 
> @dionisiydk It is used to manage internal behavior of WeakValueDictionary

Right

**Comment by dionisiydk** [comment]
> Hi,
> 
> I proposed to rename it because SetElement is not only used by sets but also by other collections such as weak collections. So, IMO, it is not a good name. (I caused me trouble when I was looking at an issue with WeakValueDictionary).
> 
> CollectionElementWrapper is not a name that I really like but I did not found anything better yet. I am open to suggestions about that. CollectionElement would be better?

Looks better to me

**Comment by jecisc** [comment]
I’ll update it tomorrow.

Thank you for the review! I really appreciate it :)

**Comment by dionisiydk** [comment]
Thank you too @jecisc . You are doing very good job

**Comment by jecisc** [comment]
I did new commit to the branch but they do not appear... I'll open a new PR.

**Comment by jecisc** [comment]
@dionisiydk https://github.com/pharo-project/pharo/pull/4396

**Pull request closed without merging**
