### PR TITLE
Add indentation rules

### PR DESCRIPTION
**Pull request by AngelHely**
This PR propose many indentation rules from https://github.com/SeasideSt/PharoWithStyle by @jbrichau + other indentation rules #16698

### CODE REVIEW

**Comment by Ducasse** [comment]
Super nice!

**Comment by MarcusDenker** [comment]
There are now many, many tests failing related to Code Critiques.


Are we sure that these failing tests are not due to merging this PR?

**Comment by MarcusDenker** [comment]
Maye related:

- [CI] RBCodeSnippetTest #testCritiques failing test runs #16829
- [CI] Calypso tests related to Rules are failing #16828

**Comment by jecisc** [comment]
I opened a PR with a revert. We can check if it fixes the tests

https://github.com/pharo-project/pharo/pull/16833

**Pull request merged**
