### PR TITLE
11007 isPrime does not work for large numbers

### PR DESCRIPTION
**Pull request by johnhwoods**
modified Integer>>isPrime so it works with Integers larger than `Float fmax` and slightly tidied the method code.

### CODE REVIEW

**Comment by MarcusDenker** [comment]
something is wrong with the PR: too many changes, conflicts

**Comment by johnhwoods** [comment]
@MarcusDenker yes I've cocked up the PR somehow, apologies.  It's supposed to be a single commit - one method change.  Couldn't work out how to recall it so I will close it and try again.

**Comment by astares** [comment]
@johnhwoods you need to create your branch based on latest commit in "Pharo10" branch or update your isse branch to latest commit commit in "Pharo10" by pulling and merging latest changes

**Comment by johnhwoods** [comment]
@astares yes, sorry, Covid brain playing up again.  Will try again, apologies

**Comment by astares** [comment]
@johnhwoods No problem. If you need help with git itself I found this free book very helpful: https://git-scm.com/book/en/v2

<blockquote><div><strong><a href="https://git-scm.com/book/en/v2">Git - Book</a></strong></div></blockquote>

**Pull request closed without merging**
