### PR TITLE
Variables-isBlockVar-via-Variable

### PR DESCRIPTION
**Pull request by MarcusDenker**
#isBlockVar can be implemented much simplei via the variable.

in additon, use isDefinition in methodOrBlockArgStyleFor: which shows the intention of the code better.

### CODE REVIEW

**Comment by astares** [comment]
@MarcusDenker 

we have #isClassVariable but #isBlockVar ... why not use isBlockVariable?
Maybe this is for another issue - but we should use proper names.

**Comment by MarcusDenker** [comment]
yes, I often do first just the implementation change and then later clean naming independently. 

But isBlockVariable is not good: you would think that there would be a BlockVariable class.

so the real name should be something like "isDefinedByBlock" or similar.

**Comment by Ducasse** [comment]
I do not get why RBProgramNode does not need to define isBlockVar, a better name should be IsBlockVariable to be coherent with isSelfVariable.

**Comment by Ducasse** [comment]
Removing isBlockVar from ProgramNode means that we will have check that we are on a VariableNode first. 
Or to be sure that are. And again I would let it so that people can avoid to use isKindOf:

**Comment by MarcusDenker** [comment]
I do not get why RBProgramNode does not need to define isBlockVar --> because you should call it only on Variables. Like isDefinition.

**Comment by MarcusDenker** [comment]
IsBlockVariable and isSelfVariable are different: a Variable is either a SelfVariable or not. this "isBlock" is like isDefinition: it can be true for nodes that are isArgumentVariable and for nodes that are isTempVariable.

**Comment by MarcusDenker** [comment]
(the only user of isBlockVar is Shout... it only calls it on Variables. To be in sync with #isDefinition, it is good that it is *not* defined on RBProgramNode. It was a mistake. it should never have  been defined there)

**Comment by Ducasse** [comment]
Ok may be I did not get it. 
The method comments should be better.

**Pull request merged**
