### PR TITLE
4533-Provide-a-trimAlltrimAll-to-complete-the-trim-messages

### LINKED ISSUE #4533: Provide a trimAll/trimAll: to complete the trim messages
We have
 - trimLeft
 - trimRight
 - trimBoth

but no way to replace overall separators or character provided in a block expression.

But this is something one often needs in parsing or data reading.

We should therefore provide additionally
 - trimAll
 - trimAll: aBlock

### PR DESCRIPTION
**Pull request by astares**
Provide a trimAll/trimAll: to complete the trim messages

Fix #4533

### CODE REVIEW

**Comment by astares** [comment]
Test failure seems unrelated

**Review by juliendelplanque — COMMENTED** [review]
I was checking how `#trimmed` is implemented and, there is actually `#trimBoth` and `#trimBoth:` messages that implement what you propose in this PR.

So I think it is not needed.
But need to be documented more. :-)

**Comment by astares** [comment]
@juliendelplanque  No. Just have a closer look.
#trimmed and #trimmedBoth are the same - combining the trimming left and right.

But #trimAll removes all separators - also the ones in the middle as it is stated in its comment and test. 

```Smalltalk
' He     l l O Wordl' trimBoth.  "'He     l l O Wordl'"
' He     l l O Wordl' trimmed.   "'He     l l O Wordl'"
' He     l l O Wordl' trimAll    "'HellOWordl'"
```

**Comment by noha** [comment]
But trimming is usually left and/or right according to https://en.wikipedia.org/wiki/Trimming_(computer_programming). In every more complex case I would rather use a variant of #copyWithout: that utilizes a block. Your example can be done using 

`' Hello World !' copyWithoutAll: Character separators `

<blockquote><div><strong><a href="https://en.wikipedia.org/wiki/Trimming_(computer_programming)">Trimming (computer programming) - Wikipedia</a></strong></div></blockquote>

**Comment by juliendelplanque** [comment]
Then, what is the difference with `#reject:` ?

**Comment by juliendelplanque** [comment]
I agree with @noha btw, to me trimming should only touch left and/or right side of the string not its middle.

**Comment by noha** [comment]
Of course #reject: is the block variant

**Comment by astares** [comment]
Ok, we close it

https://twitter.com/awbjs/status/1172273315727101952?s=20

<blockquote><div>Twitter</div><div><strong><a href="https://twitter.com/awbjs/status/1172273315727101952">Allen Wirfs-Brock on Twitter</a></strong></div><div>“Reminded today that trimStart and trimEnd are in ES2019—a little later doing some organizing of my long term storage I found this. I guess somethings just keep recurring forever. (Looks like a bug in the comment on example line 4, something else that never changes)”</div></blockquote>

**Pull request closed without merging**
