### PR TITLE
22161-Add-more-log-to-bootstrap

### PR DESCRIPTION
**Pull request by jecisc**
When launching the tests on a slave here are the steps:

- Delete workspace
- Unstash bootstrap files
- Download the VM
- Launch the tests

There is a log printing the content of the folder before downloading the VM and sometimes we see that there is a folder pharo-vm/ already.

I would like to add more logs to see if it is here or not after the step Delete Workspace.

https://pharo.fogbugz.com/f/cases/22161/Add-more-log-to-bootstrap

### CODE REVIEW

**Comment by jecisc** [comment]
Weird, I added the execution of a script to JenkinsFile but I don't see it in the result. 

Does the build take the JenkinsFile of the PR? @guillep ?

**Comment by guillep** [comment]
No, you should be added in the list of collaborators. Otherwise for security reasons the jenkins file changes are ignored.

I'll check how to add you later.

**Comment by jecisc** [comment]
Thank you!

**Review by VincentBlondeau — APPROVED** [review]
Great logging changes to see why the CI jobs are failing

**Pull request merged**
